#=========================================================================================================================================================
#                                                  REQUIRES STATS REVISION
#=========================================================================================================================================================
[General]
# UGM-133A Trident-II
Type=Missile                           // can be Projectile, Missile, Torpedo
TargetType=ASuW                        // can be AAW, ASuW, ASW
LandAttackCapability=Installation      // can be  All, Installation, Mobile, ShoreTargetsOnly
CanNotAttackTypes=Vessel,Submarine     // Seeker ignores objects of this type while in default mode

DefaultCameraDistance=0.6
MinCameraDistanceForeAft=0.29
MinCameraDistanceBroadside=0.29
CameraPivotHeight=0.0

DecalClass=Standard  // referenced in effects/decals.ini

[SensorData]
#Visual
VisualIdentificationRange=6  // at what range in nm this unit can be visually identified
IRSignature=Small
# Radar related (RCS => radar cross section)
RCS=Small
# Sonar related
# Transient
TransientRCS=Meager                    // Transient visibility on the radar
TransientVisualIdentificationRange=15  // Transient can be visually detected at this distance in nmi
TransientBaseNoise=220                 // In db

[---------- Warhead Data ----------]
############################################################
# Warhead Data
############################################################
#Warhead Types:
#0 = Blast Fragmentation
#1 = Armor Piercing
#2 = HEAT
#3 = Illumination
#4 = Cluster
#5 = Runway Cratering

# Fuze Types:
# 0 = Impact Fuze
# 1 = Proximity Fuze
[WarheadData]
WarheadType=0
Power=10000
ImpactSize=5000                      // Impact size, can be small, medium, large, verylarge
Penetration=Always                     // can be minor, moderate, heavy, always

[---------- Guidance ----------]
############################################################
# Guidance System
############################################################
# Guidance Types:
# 0 = None
# 1 = IR Homing
# 2 = Semi-Active Radar Homing
# 3 = Active Radar Homing
# 4 = Anti-Radiation Homing
# 5 = Laser-Homing
# 6 = TV-Homing
# 7 = Active Sonar Homing
# 8 = Passive Sonar Homing
# 9 = Wake Homing
[Guidance]
GuidanceType=0
MidCourseCorrection=0                  // 0 = None, 1 = Radio Command, 2 = Wire Guided
InitialFlightPhaseDuration=3.0         // time in seconds where the missile moves straight on without guiding
#======================================== Flight Profile ===========================================================
#flight phase 1: loft-----------------------------------------------------------------------------------------------------------------
#1st stage of missile flight - high altitude
MaxLoftAngle=90.0                      // Climb angle for initial loft
MaxLoftAlt=99990                          // in feet. Maximum altitude for lofting
#flight phase 2: sea skimming---------------------------------------------------------------------------------------------------------
#2nd stage of missile flight - low altitude
#SeaSkimmingAlt=20.0                    // height in feet for sea skimming TODO:make terrain following
#SeaSkimmingAlt=2000.0                    // height in feet for sea skimming
#SeaSkimmingMaxDescentAngle=45.0        // Dive angle whlie going to sea skimming
#SeaSkimmingNoseUp=2.0                  // "nose up" angle in degrees for sea skimming, reflecting the aerodynamics
#SeaSkimmingStartDistToTarget=1000      // in N. miles.
#flight phase 3: final flight phase (e.g. terminal popup)------------------------------------------------------------------------------
#Pop-Up. Missile climbs to higher altitude before activating the seeker. Or in some cases going even lower
#FinalFlightPhaseAlt=3500.0             // in feet. altitude of pop-up
#FinalFlightPhaseMaxAngle=40.0
#FinalFlightPhaseDistToTarget=20.0       // in N. miles. Recommended to set this distance equal to the seeker range
#flight phase 4: terminal approach------------------------------------------------------------------------------------------------------
#Last stage - missile activates seeker and locks on target
TerminalApproachDist=50               // in N. miles. Recommended to set this distance slightly less than the seeker range. For SAM must be slightly more than max range
TerminalDiveDistance=50                // in N. miles.
#========================================= Launch stats ============================================================
MaxVelocity=12000.0                      // Maximum speed in knots
Acceleration=25.0                       // Acceleration factor
MaxTurnRate=10.0                       // Maximum turnrate in degrees per second
MinLaunchRange=100.0                    // Minimum launch range in nautical miles
MaxLaunchRange=6500.0                   // Maximum launch range in nautical miles
LaunchReliability=97                   // The lower the value, the greater risk of misfire or accident (0...100)
#========================================     Seeker     ===========================================================
CircularErrorRadiusInstallation=150     // Circular error vs 'Installation' land units
#Homing
#N/A
#ECCM
#SelfDestruct
SelfDestructAfterTargetGone=False      // in case the target is destroyed and therefor lost, shall the missile be destroyed too?
SelfDestructDelay=5.0                  // delay in seconds for self destruction
[---------- Mesh definitions----------]
############################################################
# Main Model with collider
############################################################
[Models]
############################################################
# AssetBundle related
############################################################
AssetBundleMeshes=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMaterials=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMesh=usn_rim-7
AssetBundleDamagedMesh=
AssetBundleMaterial=usn_rim-7_mat
AssetBundleMeshHullCollider=usn_rim-7_coll
############################################################
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=weapons/wp_ss-n-19/
ResourcesRoot=wp_ss-n-19
ResourcesMesh=wp_ss-n-19_dummy
ResourcesMaterial=trident_mat.ini
ResourcesMeshForLaunch=wp_ss-n-19_dummy
ResourcesMeshCanister=wp_ss-n-19_dummy
ResourcesMeshSwitchTime=0.5  // time in seconds after launch to switch from launch mesh to main mesh
############################################################
[---------- Effects ----------]
[Particles]
BoosterEffect=effects/weapons/emitters/wp_ss-n-19_booster
BoosterEffectPosition=0,0,-0.02
InFlightEffect=effects/weapons/emitters/turbojet_sustainer
InFlightEffectPosition=0,0,-0.072
InFlightEffectStartTime=2.0  // in seconds, after that the Inflight Effect will be played if available

HitShipExplosion=effects/explosions/emitters/nuclear_underwater_surface_part
HitGroundExplosion=effects/explosions/emitters/nuclear_underwater_surface_part
HitShipExplosionClass=effects/explosions/emitters/nuclear_underwater_surface_part
HitAirExplosionClass=effects/explosions/emitters/nuclear_underwater_surface_part
HitDefaultExplosionClass=effects/explosions/emitters/nuclear_underwater_surface_part
HitWaterSplashClass=LargeWaterSplashes
HitGroundExplosionClass=VeryLargeGroundHitExplosions

ExplosionOverwaterSplash=effects/explosions/emitters/nuclear_underwater_surface_part
UnderwaterTrail=effects/weapons/emitters/aswtorpedo_cavitation_particle
UnderwaterTrailPosition=0,0,-0.08


[---------- Colliders ----------]
############################################################
# Colliders definition
############################################################
[Colliders]
#creates the hit boxes for this object
Collider=col_main

[col_main]
Collider=Box
Position=0,0,0
Rotation=0,0,0
Scale=0.017,0.017,0.14