[LoadoutNames]

# ---------- SEST Rafale F5 ----------
SEST_Intercept260F5=SEST Intercept (AIM-260)
SEST_MALICE=SEST InterceptMALICE (AIM-424/AIM-260)
SEST_AntiShipLRASM=SEST AntiShip LRASM
SEST_Intercept260Heavy=SEST Intercept Heavy (6x AIM-260)
SEST_LRASM_ER=SEST AntiShip LRASM LongRange (3 tanks)
SEST_MALICE_ER=SEST InterceptMALICE LongRange (3 tanks)
