[---------- General Data ----------]
[General]
UnitType=Aircraft
Size=SemiSmall

DefaultCameraDistance=1
MinCameraDistanceForeAft=0.39
MinCameraDistanceBroadside=0.39
CameraPivotHeight=0.0

Length=18.68

GroundedPitchAngle=0  // this angle is the pitch (x) angle at ground with gears down
GroundPivot=0,-0.027,-0.0333
LandingPitch=-1

Pilot1=usaf_pilot_f-15c
PilotPositions=0,0.003309,0.056113
EjectChance=0.6

[OpticalView]
Views=binocular_7x50,binocular_10x50
DefaultView=binocular_7x50

[AI]
Role=Fighter

[SensorData]
#Visual
VisualIdentificationRange=6.0  // at what range in nm this unit can be visually identified
IRSignature=SemiSmall
# Radar related (RCS => radar cross section)
RCS=SemiSmall

[Animations]
NumberOfAnimationReferences=1
AnimationFile_1=animations_am_tornado_adv

[---------- Flight Model ----------]
[Engine]
EngineIntakeArea=1.09                 //Pi* r * r where r is engine radius, in meters

[FlightModel]
PitchGain=0.8                         // Vertical manuverability
VelocityGain=0.1136                   // Acceleration
HeadingGain=2.8                       // Horizontal manuverability
YawRateLimit=130                      // in degrees per second

BankGain=0.8                          // Roll change speed
MaxRollForHeading=50.0                // bank limit in normal flight
MaxRollRate=90.0                      // in degrees per second

ThrustGain=0.325                      // Thrust change speed
SpeedBrakeFractionGain=10             // Speed brakes deploy speed

SpeedDeltaPerAltitudeChange=0.0885

[Performance]
#Dimensions
WingSpan=13.91                        //meters
#Parameters
MaxG=8                                // Mostly for horizontal turns

MaxClimbRate=165                      //Meters per second
EmptyMass=14501.0                     // in kg
MaxFuel=6030.0                        // in kg

PerEngineMaxThrust=40500              //Newtons
PerEngineMaxAfterburnerThrust=73000   //Newtons
EngineCount=2

Ceiling=50000.0                       // ceiling in feet
CruiseAltitude=37000                  //in feet
#"Engine" efficiency at 0ft, 37000 ft, 65000 ft. Always 1 for cruise altitude
AltitudeEfficiency=0.5,0.5,0.25       // Defines fuel consumption with altitude

#Governing of max speed
MaxSpeedAtSeaLevel=800                //in knots, Defines max speed at altitude curve
StallSpeed=120.0                      //in knots
MachLimit=2.27                        //for 37000ft, Defines max speed at altitude curve

#SpeedAndRange   MachNumbers or knots, Specified units or multiplier (except Cruise range)
RangeUnits=Miles                      // Can be: Km. Any other value = nmi. Defines measurment units of ranges of SpeedAndRange values

SpeedAndRange_Landing=0.28,0.4        // Landing
SpeedAndRange_Loiter=0.4,0.6          // Loiter
SpeedAndRange_Cruise=0.85,1001        // Cruise
SpeedAndRange_Max=1.5,0.8             // Attack/Fast/High/Max without AB
SpeedAndRange_Afterburner=2.2,0.2     // AB max

Altitudes=50,300,1000,3000,6000,10000,20000,30000  // in feet

[---------- Main Systems ----------]
[FlightControls]
NumberOfAilerons=2
Aileron1_Model=aileron_l
Aileron1_MinAngle=50.0
Aileron1_MaxAngle=0
Aileron1_BaseAngle=0.0
Aileron2_Model=aileron_r
Aileron2_MinAngle=-50.0
Aileron2_MaxAngle=0
Aileron2_BaseAngle=0.0

NumberOfElevators=2
Elevator1_Model=Right_elevator
Elevator1_MinAngle=-20.0
Elevator1_MaxAngle=20.0
Elevator1_BaseAngle=0.0
Elevator1_RotationAxis=X
Elevator2_Model=Left_Elevator
Elevator2_MinAngle=-20.0
Elevator2_MaxAngle=20.0
Elevator2_BaseAngle=0.0
Elevator2_RotationAxis=X

NumberOfRudders=1
Rudder1_Model=Rudder
Rudder1_MinAngle=-20.0
Rudder1_MaxAngle=20.0
Rudder1_BaseAngle=0
Rudder1_RotationAxis=Z

AfterBurnerSubModel=Afterburner    // optional entry
MaxAfterBurnerIntensity=0.2
AfterBurnerFadeTime=0.5

[WingSweep]
LeftWingModel=WingL
RightWingModel=WingR
LeftWingPylons=PylonL
RightWingPylons=PylonR
WingSweepDegreesPerSecond=10
NumberOfAngles=3
SweepAngle1=0.0
SweepSpeed1=0.5    // mach
SweepAngle2=25.0
SweepSpeed2=0.9    // mach
SweepAngle3=38.5
SweepSpeed3=1.5    // mach

[---------- Sensor Systems ----------]
[SensorSystems]
NumberOfSensorSystems=3

[SensorSystem1] #Cockpit
Type=Visual
SystemName=Eyes
Mount=Dummy
ViewArcs=-150,150|-25,91
ModuleType=Sensor

#---------- Surface only search radars ----------
[SensorSystem2] #Orion-A Radar
Type=Radar
SystemName=Foxhunter
Mount=Dummy
ModuleType=Sensor

#---------- ESM ----------
[SensorSystem3] #RWR
Type=ESM
SystemName=ARI_18241
Mount=Dummy
ModuleType=Sensor

[---------- Weapon Systems ----------]
[WeaponSystems]
NumberOfWeaponSystems=3
AvailableLoadouts=AirToAir,AirToAirLongrange

[WeaponSystem1] #Hardpoint
Type=Hardpoint
SystemName=Hardpoint
AssociatedSensors=SensorSystem2

FiringArcs=-10,10

NumberOfStations=10
Station1=-0.004964,-0.006006,0.033116       //aam center left front
Station2=0.004964,-0.006006,0.040967    //aam center right front
Station3=-0.004964,-0.006506,-0.021893     //aam center left rear
Station4=0.004964,-0.006506,-0.013973        //aam center right rear
Station5=-0.04818,0.006172,-0.015959             //aam wing left1
Station6=0.04818,0.006172,-0.015959          //aam wing right1
Station7=-0.035448,0.006172,-0.015959             //aam wing left2
Station8=0.035448,0.006172,-0.015959          //aam wing right2
Station9=-0.041845,-0.002457,-0.022288             //tank left
Station10=0.041845,-0.002457,-0.022288          //tank right

Station1Rotation=0,0,-45
Station2Rotation=0,0,-45
Station3Rotation=0,0,-45
Station4Rotation=0,0,-45

Station5Rotation=0,0,45
Station6Rotation=0,0,-45
Station7Rotation=0,0,-45
Station8Rotation=0,0,45

Station5Parent=PylonL
Station7Parent=PylonL
Station6Parent=PylonR
Station8Parent=PylonR

Station9Parent=PylonL
Station10Parent=PylonR

ModuleType=Weapon

[WeaponSystem2]
Type=CIWS
SystemName=BK-27
#Sensors
#Animations
#Mount
Mount=Dummy
MountPosition=0.009009,-0.003888,0.082155
IsMountRotatable=True
#Containers
ContainerBase=Dummy
Gun=Dummy
AreContainersRotatable=True
#Angles
FiringArcs=-3,3
ElevationArc=-3,3
#Loading
AssociatedMagazine=WeaponMagazineBK-27
#Effects
#Other
IsOffensive=True
ModuleType=Weapon

[WeaponSystem3] #Chaff
Type=Chaff
SystemName=US_AIR_CHAFF_DISP
#Sensors
#Animations
#Mount
Mount=Dummy
#MountPosition=0,-0.01,-0.016
#Containers
ContainerBase=Dummy
#Angles
#Loading
AssociatedMagazine=WeaponMagazineChaff
#Effects
NumberOfEffects=1
DelayBetweenLaunches=0.1
#Other
WorksStandalone=True
ModuleType=Weapon

[--------------------------- Loadouts ---------------------------]
[WeaponSystem1Default]
ReadyUpTime=30               // in minutes. Time that plane will spend refueling and rearming before takeoff.
CoolDownTime=60              // in minutes. Time that plane will spend in maintenance after landing.

Station1=am_slyflash
Station2=am_slyflash
Station3=am_slyflash
Station4=am_slyflash

Station5=usn_aim-9l
Station6=usn_aim-9l
Station7=usn_aim-9l
Station8=usn_aim-9l

[WeaponSystem1AirToAir]
ReadyUpTime=30               // in minutes. Time that plane will spend refueling and rearming before takeoff.
CoolDownTime=60              // in minutes. Time that plane will spend in maintenance after landing.

Station1=am_slyflash
Station2=am_slyflash
Station3=am_slyflash
Station4=am_slyflash

Station5=usn_aim-9l
Station6=usn_aim-9l
Station7=usn_aim-9l
Station8=usn_aim-9l

[WeaponSystem1AirToAirLongrange]
ReadyUpTime=35               // in minutes. Time that plane will spend refueling and rearming before takeoff.
CoolDownTime=60              // in minutes. Time that plane will spend in maintenance after landing.

Station1=am_slyflash
Station2=am_slyflash
Station3=am_slyflash
Station4=am_slyflash

Station5=usn_aim-9l
Station6=usn_aim-9l
Station7=usn_aim-9l
Station8=usn_aim-9l

Station9=am_tornado_adv_tank
Station10=am_tornado_adv_tank


[---------- WeaponMagazines ----------]
[WeaponMagazineChaff]
NumberOfAmmunitionTypes=1
Ammunition1_Count=16
Ammunition1=wp_aircraft_chaff
ModuleType=WeaponMagazine

[WeaponMagazineBK-27]
NumberOfAmmunitionTypes=1
Ammunition1_Count=180
Ammunition1=am_cal_27mm
ModuleType=WeaponMagazine

[--------------------------- Mesh definitions ---------------------------]
[Models]
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=aircraft/am_tornado_adv/
ResourcesRoot=am_tornado_adv.obj
ResourcesMesh=hull
ResourcesMaterialFolder=aircraft/am_tornado_adv/textures/
ResourcesMaterial=am_tornado_adv_mat.ini


NumberOfDamageModels=1
DamageModel1=hull_dmg
DamageModelMaterial1=am_tornado_adv_mat.ini
DamageModelLostWingSide1=Left
############################################################
[Submodels]
#---------- General ----------
General_1=Seats
General_2=pilot
General_3=windshield
General_4=Canopy
General_5=CanopyGlass
General_6=Hud
General_7=Afterburner
General_8=AirbrakeL
General_9=AirbrakeR

#---------- Left Wing ----------
LeftWing_1=WingL
LeftWing_2=FlapL
LeftWing_3=aileron_l
LeftWing_4=PylonL
LeftWing_5=2IRMRailL2

#---------- Right Wing ----------
RightWing_1=WingR
RightWing_2=FlapR
RightWing_3=aileron_r
RightWing_4=PylonR
RightWing_5=2IRMRailR1

#---------- Tail ----------
Tail_1=Rudder
Tail_2=Right_Elevator
Tail_3=Left_Elevator
#---------- Nose Gear ----------
NoseGear_1=nose_gear
NoseGear_2=nose_gear_door1
NoseGear_3=nose_gear_door2
NoseGear_4=nose_gear_door3

#----------Left Gear ----------
Gear_l_1=GearL
Gear_l_2=GearDoorL

#----------Right Gear ----------
Gear_r_1=GearR
Gear_r_2=GearDoorR

#---------- Modex ----------
number=number
#---------- Weapons ----------
############################################################
#---------- General ----------
############################################################
[Seats]
Mesh=Seats
Material=am_tornado_adv_mat.ini

[pilot]
Mesh=pilot
ResourcesMaterialFolder=characters/materials/
Material=usn_pilot_a_mat

[windshield]
Mesh=windshield
ResourcesMaterialFolder=aircraft/materials/
Material=cockpit_glass

[Hud]
Mesh=Hud
ResourcesMaterialFolder=aircraft/materials/
Material=cockpit_glass

[Canopy]
Mesh=Canopy
Material=am_tornado_adv_mat.ini
Position=0,0.022829,0.025383

[CanopyGlass]
Mesh=CanopyGlass
ResourcesMaterialFolder=aircraft/materials/
Material=cockpit_glass
Parent=Canopy

[AirbrakeR]
Mesh=AirbrakeR
Rotation=0,11,0
Position=0.012809,0.016401,-0.055122
Material=am_tornado_adv_mat.ini

[AirbrakeL]
Mesh=AirbrakeL
Rotation=0,-11,0
Position=-0.012805,0.016401,-0.055122
Material=am_tornado_adv_mat.ini

[Afterburner]
Mesh=Afterburner
ResourcesMaterialFolder=aircraft/materials/
Material=afterburner_mat
CastShadows=False

############################################################
#---------- Left Wing ----------
############################################################
[WingL]
Mesh=WingL
Material=am_tornado_adv_mat.ini
Position=-0.022183,0.016235,-0.01636
Rotation=0,0,0

[FlapL]
Mesh=FlapL
Material=am_tornado_adv_mat.ini
Rotation=0,-15,2.5
Parent=WingL
Position=-0.032651,-0.003828,-0.018382

[aileron_l]
Mesh=aileron_l
Material=am_tornado_adv_mat.ini
Parent=WingL
Rotation=-3,75,0
Position=-0.032505,-0.001987,-0.01647

[PylonL]
Mesh=PylonL
Material=am_tornado_adv_mat.ini
Parent=WingL
Position=-0.019646,-0.007863,-0.003686

[2IRMRailL2]
Mesh=2IRMRailL2
Material=am_tornado_adv_mat.ini
Parent=PylonL

############################################################
#---------- Right Wing ----------
############################################################
[WingR]
Mesh=WingR
Material=am_tornado_adv_mat.ini
Position=0.022183,0.016235,-0.01636
Rotation=0,0,0

[FlapR]
Mesh=FlapR
Material=am_tornado_adv_mat.ini
Parent=WingR
Rotation=0,15,-2.5
Position=0.032651,-0.003829,-0.018382

[aileron_r]
Mesh=aileron_r
Material=am_tornado_adv_mat.ini
Parent=WingR
Rotation=-3,-75,0
Position=0.032508,-0.001988,-0.016469

[PylonR]
Mesh=PylonR
Material=am_tornado_adv_mat.ini
Parent=WingR
Position=0.019646,-0.007864,-0.003686

[2IRMRailR1]
Mesh=2IRMRailR1
Material=am_tornado_adv_mat.ini
Parent=PylonR

############################################################
#---------- Tail ----------
############################################################
[Rudder]
Mesh=Rudder
Material=am_tornado_adv_mat.ini
Position=0.0,0.031466,-0.094034
Rotation=53,0.0,0.0

[Right_Elevator]
Mesh=Right_Elevator
Material=am_tornado_adv_mat.ini
Position=0.016357,0.007697,-0.082787

[Left_Elevator]
Mesh=Left_Elevator
Material=am_tornado_adv_mat.ini
Position=-0.016357,0.007697,-0.082787

############################################################
#---------- Nose Gear ----------
############################################################
[nose_gear]
Mesh=nose_gear
Material=am_tornado_adv_mat.ini
Position=0,-0.003071,0.055313
Rotation=0,0,0

[nose_gear_door1]
Mesh=nose_gear_door1
Material=am_tornado_adv_mat.ini
Position=-0.003489,-0.005492,0.070043
Rotation=0,0,0

[nose_gear_door2]
Mesh=nose_gear_door2
Material=am_tornado_adv_mat.ini
Position=0.003496,-0.005492,0.070043

[nose_gear_door3]
Mesh=nose_gear_door3
Material=am_tornado_adv_mat.ini
Position=0,-0.005662,0.054804

############################################################
#----------Left Gear ----------
############################################################

[GearL]
Mesh=GearL
Material=am_tornado_adv_mat.ini
Position=-0.016097,0.001538,-0.023904

[GearDoorL]
Mesh=GearDoorL
Material=am_tornado_adv_mat.ini
Rotation=0,-4,0
Position=-0.019291,0.002516,-0.009359

############################################################
#----------Right Gear ----------
############################################################

[GearR]
Mesh=GearR
Material=am_tornado_adv_mat.ini
Position=0.016097,0.001538,-0.023904

[GearDoorR]
Mesh=GearDoorR
Material=am_tornado_adv_mat.ini
Rotation=0,4,0
Position=0.019293,0.002516,-0.009359

############################################################
#---------- Modex ----------
############################################################
[number]
Mesh=number
ResourcesMaterialFolder=aircraft/materials/numbers/
Material=numbers

############################################################
#---------- Weapons ----------
############################################################

[---------- Effects ----------]
[Particles]
ShotDownFireEffect=effects/aircraft_kill_effects/usaf_f-15c_kill
ShotDownFireEffectPosition=0,0,0
HitWaterEffect=effects/splashes/emitters/splash_bomb
HitGroundEffect=effects/explosions/emitters/aircraft_hit_ground
HitAirEffectClass=LargeMissileExplosions
ExhaustSmoke=aircraft/particles/wp_su-24a_smokeemitter
#Contrail=aircraft/particles/usn_f-14a_contrail
TipVortexPosition=0.094,-0.002,-0.034
TipVortex=effects/aircraft/emitters/tipvortex_full
LeftWingVortexPosition=0,0,0
LeftWingVortex=effects/aircraft/emitters/wingvortex_su-24_left
RightWingVortexPosition=0,0,0
RightWingVortex=effects/aircraft/emitters/wingvortex_su-24_right
ShockConePosition=0,0,0
ShockCone=effects/aircraft/emitters/shockcone

############################################################
# Sounds
############################################################

[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=3
# Front
EngineAudioClip=audio/aircraft/J79_Front
EngineAudioPosition=0,0,0
EngineAudioRollOff=Logarithmic
EngineAudioDistance=1,20
EngineAudioPitchRange=1.0,2.0
EngineAudioVolumeRange=0.25,1.0
EngineAudioAspectAngle=0
EngineAudioAspectArcHalfRange=180
EngineAudioAudibility=AboveAndBelow  // layer of sound audibility: Above, Below, AboveAndBelow
# Rear
ExhaustAudioClip=audio/aircraft/jet_rear_1
ExhaustAudioPosition=0,0,0
ExhaustAudioRollOff=Logarithmic
ExhaustAudioDistance=1,20
ExhaustAudioPitchRange=1.0,1.5
ExhaustAudioVolumeRange=0.5,1.0
ExhaustAudioAspectAngle=180
ExhaustAudioAspectArcHalfRange=180
ExhaustAudioAudibility=AboveAndBelow  // layer of sound audibility: Above, Below, AboveAndBelow
# Far
FarAudioClip=audio/aircraft/jet_far_2
FarAudioPosition=0,0,0
FarAudioRollOff=Logarithmic
FarAudioDistance=3,20
FarAudioPitch=0.75
FarAudioVolume=1.0
FarAudioFadeRange=0.1,0.2	      // nautical miles min/max
FarAudioAudibility=AboveAndBelow  // layer of sound audibility: Above, Below, AboveAndBelow
# Afterburner
AfterburnerAudioClip=audio/aircraft/J79_AB
AfterburnerAudioPosition=0,0,0
AfterburnerAudioRollOff=Logarithmic
AfterburnerAudioDistance=1,20
AfterburnerAudioPitch=0.75
AfterburnerAudioVolume=1.0
AfterburnerAudioAudibility=AboveAndBelow  // layer of sound audibility: Above, Below, AboveAndBelow
# Gears
#GearsAudioClip=audio/aircraft/gears
GearsAudioClip=audio/aircraft/LandingGearRetraction_v1
GearsAudioPosition=0,0,0
GearsAudioRollOff=Logarithmic
GearsAudioDistance=1,20
GearsAudioPitch=1.0
GearsAudioVolume=1.0
# Flaps
#FlapsAudioClip=audio/aircraft/flaps
FlapsAudioClip=audio/aircraft/LandingGearRetraction_v1
FlapsAudioPosition=0,0,0
FlapsAudioRollOff=Logarithmic
FlapsAudioDistance=1,20
FlapsAudioPitch=1.0
FlapsAudioVolume=1.0

//Front Sound = audio/aircraft/JE_Front_3 v=0.25, p=1.2
//Rear	Sound = audio/aircraft/JE_Burner_2
//Far	Sound = audio/aircraft/JetExhaustLoop p=0.75
//Afterburner = audio/aircraft/AfterburnerLarge_v1 p=0.75


[---------- Colliders ----------]
[Colliders]
// creates the hit boxes for this object
NumberOfColliders=2
Collider1=coll_body
Collider2=coll_wings


[coll_body]
Collider=Box
Position=0,0,0
Rotation=0,0,0
Scale=0.02361928,0.02891341,0.1916716

[coll_wings]
Collider=Box
Position=0.0023026,0.0051,-0.012915
Rotation=0,0,0
Scale=0.169098,0.006968998,0.05797473