[General]
SerialnumberReferences=
EmblemReference=Emblem
NationFlagReference=Flag19
NumberOfSquadrons=2

[Default]
Nation=Italy
ServiceDate=1968|1991

[Squadron1] #1° Gruppo Elicotteri
ResourcesSerialnumberFolder=aircraft/mm_sh-3/modex/
SerialNumberPrefix=
SerialnumberTextures=21.png,22.png,23.png,24.png,25.png,26.png,27.png,28.png,29.png,30.png,31.png
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=
LiveryTexture=
ResourcesFlagFolder=
FlagTexture=flag_italy
# nations are referenced in the layout.ini file:
Nation=Italy
ServiceDate=1971|1991

[Squadron2] #3° Gruppo Elicotteri
ResourcesSerialnumberFolder=aircraft/mm_sh-3/modex/
SerialNumberPrefix=
SerialnumberTextures=21.png,22.png,23.png,24.png,25.png,26.png,27.png,28.png,29.png,30.png,31.png
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=
LiveryTexture=
ResourcesFlagFolder=
FlagTexture=flag_italy
# nations are referenced in the layout.ini file:
Nation=Italy
ServiceDate=1968|1991