[LoadoutNames]
#------------------------------------------ New system ------------------------------------------
AA=Anti-Air
MST=MST
AABF=Anti-Air Battle Flag
MSTBF=MST Battle Flag
ASWBF=ASW Battle Flag
# - LongRange means operating range of aircraft, not the weapons range
# ---------- Mandatory loadouts ----------
Default=Default                            // Usually most common loadout for this plane
Ferry=Ferry                                // Maximum fueltanks, no weapons, except guns and chaff
Empty=Empty                                // No fueltanks, no weapons, except guns and chaff

#----------- Murder Hornet ---------------
MurderHornetCAP=MH CAP 174				   // F/A-18E/F Specific
MH_CAP_120=MH CAP 120						// F/A-18E/F Specific
MH_CAP_120EF=MH CAP 120-EF	// F/A-18E/F Specific
MurderHornetInterceptor=MH Interceptor		// F/A-18E/F Specific
MurderHornetPenetrator=MH Penetrator		// F/A-18E/F Specific
MurderHornetGunSlinger=MH Gunslinger  		// F/A-18E Specific
MurderHornetFistFight=MH Fist Fight			// F/A-18E Specific
MurderHornetStrikeLight=MH Strike Light			// F/A-18E/F Specific
MurderHornetStrikeHeavy=MH GBU-10		// F/A-18E Specific
MurderHornetCAS=MH CAS			// F/A-18E/F Specific
MurderHornetCASAGM=MH CAS AGM			// F/A-18F Specific
MH_CASAGMEF=MH CAS AGM-EF			// F/A-18F Specific
MurderHornetCASSDB=MH CAS SDB			// F/A-18F Specific
MH_CASSDBEF=MH CAS SDB-EF			// F/A-18F Specific
MurderHornetSEAD=MH SEAD			// F/A-18E/F Specific
MurderHornetAntiShip=MH Anti-Ship			// F/A-18E/F Specific
MH_AntiShipEF=MH Anti-Ship-EF			// F/A-18E/F Specific
MH_LRASM=MH LRASM			// F/A-18E/F Specific
#MH_GBU-12=MH GBU-12			// F/A-18E/F Specific
#MH_GBU-31=MH GBU-31			// F/A-18E/F Specific
MH_GBU-75=MH GBU-75			// F/A-18E/F Specific
MH_AGM-154JSOW=MH JSOW			// F/A-18E/F Specific
MH_AGM-154EF=MH JSOW-EF			// F/A-18E/F Specific
MH_AGM-154JSOWclus=MH JSOW Cluster			// F/A-18E/F Specific
MH_AGM-154clusEF=MH JSOW Cluster-EF			// F/A-18E/F Specific
MurderHornetStrikeJDAM=MH JDAM Land			// F/A-18E/F Specific
MH_GBU-31EF=MH JDAM Land-EF			// F/A-18E/F Specific
MurderHornetStrikeGBU=MH GBU 24			// F/A-18E/F Specific
MH_GBU-24EF=MH GBU 24-EF			// F/A-18E/F Specific
MH_QCSK31=MH Quicksink GBU-31
MH_QCSK31EF=MH Quicksink GBU-31-EF
MH_QCSK38=MH Quicksink GBU-38
MH_QCSK38EF=MH Quicksink GBU-38-EF
MurderHornetSEADHeavy=MH SEAD
MurderHornetSEADHeavyTanks=MH SEAD+Extra Fuel Tanks
MurderHornetLightsOut=MH SEAD Full