[Language_en]
Name=SU-25 Frogfoot
Description=by misaka

[Language_cn]
Name=苏-25 蛙足
Description=由misaka制作

[Language_ru]
Name=Су-25 русификатор
Description=by misaka

[Compatibility]
;ApproximateVersion is the second check and will override all statements below. This checks MAJOR and MINOR match but will accept higher PATCH.
;Would recommend this as a default case for starters.
ApproximateVersion=0.7.0