[General]
Type=Chaff                             // can be Projectile, Missile, Torpedo
TargetType=AAW                         // can be AAW, ASuW, ASW

Mass=3.5
AmmoPoints=2.5

[ECM]
# Chaff -related parameters
SpoofChance=0.65
DefensiveEffectTime=90
ReactionRange=10.0

[SensorData]
IRSignature=VeryLarge
# radar related (RCS => radar cross section)
RCS=VeryLarge