[General]
# RBS15 Mk3
Type=Missile
TargetType=ASuW
LandAttackCapability=Installation,ShoreTargetsOnly

Mass=1450                              // in kg. Used for aircraft
AmmoPoints=2700                        // For Supply System. Defines "price" of ammunition based on mass, volume, complexity and availability
SupplyCategory=Harpoon                 // For Supply System. Makes that presence of such category is required for replenishment of this weapon

DefaultCameraDistance=0.5
MinCameraDistanceForeAft=0.20
MinCameraDistanceBroadside=0.20
CameraPivotHeight=0.0

CIWSDefenceBonus=30                     // added chance to evade CIWS compounded by below factors
MissileDefenceBonus=0.15                     // added chance to evade missile compounded by below factors
#weaving terminal maneuver


DecalClass=Standard

[SensorData]
#Visual
VisualIdentificationRange=4  // at what range in nm this unit can be visually identified
IRSignature=Small
# Radar related (RCS => radar cross section)
RCS=0.1
# Sonar related
# Transient
TransientRCS=SemiSmall                    // Transient visibility on the radar
TransientVisualIdentificationRange=20  // Transient can be visually detected at this distance in nmi
TransientBaseNoise=220                 // In db

[---------- Warhead Data ----------]
[WarheadData]
WarheadType=1
Power=42
ImpactSize=Large                       // Impact size, can be small, medium, large, verylarge
Penetration=Heavy                     // can be minor, moderate, heavy, always

[---------- Guidance ----------]
[Guidance]
GuidanceType=3
LandAttackGuidanceType=0
MidCourseCorrection=1                  // 0 = None, 1 = Radio Command, 2 = Wire Guided
InitialFlightPhaseDuration=1.0         // time in seconds where the missile moves straight on without guiding
PerformsSlightBallisticInitialFlight=False  // flag if the missile performs a slight ballistic flight curve during the initial phase (e.g. vessel launched harpoon)
TargetRequired=False                 
TerrainFollowFlight=True
SupportsBanking=True                   // if the missile will bank when turning
#======================================== Flight Profile ===========================================================
#flight phase 1: loft-----------------------------------------------------------------------------------------------------------------
#1st stage of missile flight - high altitude
#flight phase 2: sea skimming---------------------------------------------------------------------------------------------------------
#2nd stage of missile flight - low altitude
SeaSkimmingAlt=12.0                    // height in feet for sea skimming TODO:make terrain following
SeaSkimmingMaxDescentAngle=35.0        // Dive angle whlie going to sea skimming
SeaSkimmingNoseUp=2.0                  // "nose up" angle in degrees for sea skimming, reflecting the aerodynamics
SeaSkimmingStartDistToTarget=1000      // in N. miles.
#flight phase 3: final flight phase (e.g. terminal popup)------------------------------------------------------------------------------
#Pop-Up. Missile climbs to higher altitude before activating the seeker. Or in some cases going even lower
FinalFlightPhaseAlt=6                 // in feet. altitude of pop-up
FinalFlightPhaseMaxAngle=15.0
FinalFlightPhaseDistToTarget=20.0      // in N. miles. Recommended to set this distance equal to the seeker range
#flight phase 4: terminal approach------------------------------------------------------------------------------------------------------
#Last stage - missile activates seeker and locks on target
TerminalApproachDist=12.0               // in N. miles. Recommended to set this distance slightly less than the seeker range. For SAM must be slightly more than max range
TerminalVerticalTurnRate=35            // Override of vertical turn rate in terminal (intended for Pop-up)
#========================================= Launch stats ============================================================
MaxVelocity=600.0                       // Maximum speed in knots                                                 
Acceleration=5.5                        // Acceleration factor                                                    
MaxTurnRate=16.0                        // Maximum turnrate in degrees per second                                 
MinLaunchRange=3.0                      // Minimum launch range in nautical miles                                 
MaxLaunchRange=108.0                    // Maximum launch range in nautical miles                                 
LaunchReliability=98                    // The lower the value, the greater risk of misfire or accident (0...100) 
WobblingStrength=120.5                   // amplitude of wobbling. Marks that missile performs some wobbling flight
WobblingSpeed=1.5                      // frequency of wobbling
#VerticalWobblingStrength=9.5                   // amplitude of wobbling. Marks that missile performs some wobbling flight
#VerticalWobblingSpeed=2                      // frequency of wobbling

;GroupSize=4                            // Indicates that missiles can join into groups
;GroupJoinRange=1.5                      // in miles
;GroupSpacing=4.0                       // in miles. interval between misseles in line
;GroupLeaderAlt=6.0                    // in feet. altitude of leading missile. Only for FinalFlightPhase
;GroupWingmanAlt=6.0                   // in feet. altitude of non-leading missile. FinalFlightPhase
#========================================     Seeker     ===========================================================
#Homing
SeekerGain=70.0                        // Seeker gain in dB
SeekerFOV=60                        // Seeker active range in nautical miles. Relevant for  Active Radar Homing, Laser-Homing and Active Sonar Homing (3, 5 and 7)
SeekerActiveRange=20.0                 // Seeker active range in nautical miles. Relevant for Semi-Active Radar Homing, Active Radar Homing, Laser-Homing and Active Sonar Homing (2, 3, 5 and 7)
SeekerPassiveRange=0                   // Seeker passive range in nautical miles. Relevant for IR Homing, Semi-Active Radar Homing, Anti-Radiation Homing, TV-Homing, Passive Sonar Homing and Passive Sonar Homing (1, 2, 4, 6, 8 and 9)
SecondaryPassiveRadarGuidanceType=Full  //Used with Active or SemiActive radar seeker. Used to detect emitting targets and home on them prior getting active target lock. Supported values: Full for both radar and ECM emissions and HomeOnJam if can home on jammers only
PassiveRadarGuidanceFrequencies=All    // Frequences Anti-Radiation and HomeOnJam weapons can detect
Frequency=Ku-Band
PeakPower=0.00003
DefaultIgnoredTypes=LandUnit           // Seeker ignores objects of this type while in default mode
UseFinalFlightInLandMode=False         // Skip FinalFlightPhase when in LandAttack mode
#Misc Guidance Properties
RangeGate=2							   // 
SizeGate=5						   //
#ECCM
AntiCountermeasuresBonus=0.45           // This value substracted from probability of spoofing by countermeasures (0...1)
AntiJammerBonus=0.45                   // This value substracted from probability of being jammed  (0...1)
ReattackMode=1                         // 0 = None, 1 = Circle, 2 = Drive-around
#SelfDestruct
SelfDestructAfterTargetGone=False      // in case the target is destroyed and therefor lost, shall the missile be destroyed too?
SelfDestructDelay=20.0                  // delay in seconds for self destruction

[---------- Mesh definitions----------]
############################################################
# Main Model with collider
############################################################
[Models]
############################################################
# AssetBundle related
############################################################
AssetBundleMeshes=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMaterials=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMesh=usn_rim-7
AssetBundleDamagedMesh=
AssetBundleMaterial=usn_rim-7_mat
AssetBundleMeshHullCollider=usn_rim-7_coll
############################################################
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=assets/europack/models/
ResourcesRoot=weapons.obj
ResourcesMesh=eu_missile_RBS15
ResourcesMaterialFolder=assets/europack/materials/RBS15/
ResourcesMaterial=RBS15_mat.ini
ResourcesMeshForLaunch=eu_launch_RBS15
#ResourcesMeshCanister=eu_launch_RBS15
ResourcesMeshSwitchTime=1.0 // time in seconds after launch to switch from launch mesh to main mesh
############################################################
NumberOfSubModels=0

[Debris]
DebrisProbability=95                // probability for debris to happen
ResourcesMeshForDebris=usaf_agm-86c_d // optional debris mesh after destruction
DebrisPosition=0.05                 // moves it in front of the warhead to have the trailing effect at correct position
DebrisLifeTime=10.0
DebrisVelocityDampening=0.99
DebrisHeightLossAdd=0.0005          // determines how quickly the debris loses height

[---------- Effects ----------]
# Effects are referenced in /effects/effects.ini when using an effects class
# e.g. either:
# BoosterEffect=effects/weapons/emitters/submarine_torpedo_launch
# or
# BoosterEffectClass=BoosterEffects  // this will be referenced in effects.ini

# possible values (optionally with suffix "Class")
# BoosterEffect, InFligheEffect, UnderwaterTrail, ParachuteEffect, TorpedoSurfaceSplash, HitWaterSplash
# DebrisTrail, DebrisSplash, SmallFireEffect, ModerateFireEffect, SevereFireEffect,
# HitAirExplosion, HitShipExplosion, HitObjectExplosion, HitGroundExplosion, HitDefaultExplosion

[Particles]
BoosterEffect=effects/weapons/emitters/otomat_launch_effect
BoosterEffectPosition=0,0,-0.012

InFlightEffect=effects/weapons/emitters/turbojet_sustainer_small
InFlightEffectPosition=0,0,-0.035
InFlightEffectStartTime=2.0  // in seconds, after that the Inflight Effect will be played if available

SustainerEffect=effects/weapons/emitters/wp_ss-n-3_sustainer
SustainerEffectPosition=0,0.0005,0.00
SustainerEffectScale=0.3,0.3,0.3
SustainerEffectStartTime=1.0

HitShipExplosionClass=LargeShipHitExplosion
HitAirExplosionClass=LargeMissileExplosions
HitDefaultExplosionClass=LargeMissileExplosions
HitWaterSplashClass=LargeWaterSplashes
DebrisTrailClass=MissileDebrisFire
DebrisSplashClass=MediumWaterSplashes

DebrisTrail=effects/aircraft/emitters/helicopterfireeffect
HitWaterSplashClass=LargeWaterSplashes
ExplosionOverwaterSplash=False

[---------- Colliders ----------]
############################################################
# Colliders definition
############################################################
[Colliders]
#creates the hit boxes for this object
Collider=col_main

[col_main]
Collider=Box
Position=0,0,0
Rotation=0,0,0
Scale=0.005,0.005,0.02
