#!alias ammunition/usn_an_slq_25c_nixie_decoy.ini

# AN/SLQ-25E Nixie towed decoy

[SensorData]
BaseNoise=218                   // base sound level in db at 1m distance
TargetReflectionStrength=75		// reflection on active sonar

[ECM]
# Decoy related
SpoofChance=0.95                       // Base chance to spoof torpedo