#!alias ammunition/usn_rgm-84n.ini

# RGM-84Q Block II+ ER «Harpoon»

[---------- Warhead Data ----------]
[WarheadData]
Power=30
ImpactSize=Medium                      // Impact size, can be small, medium, large, verylarge
Penetration=heavy                     // can be minor, moderate, heavy, always

[---------- Guidance ----------]
[Guidance]
#========================================= Launch stats ============================================================
MaxLaunchRange=167.0                    // Maximum launch range in nautical miles