#!alias ammunition/usn_rim-66g.ini

# RIM-66K SM-2MR Block IIIA

# Arm launched, NTU ships

[---------- Warhead Data ----------]
[WarheadData]
Power=35

FuzeProximityDistance=30.0             // for proximity fuze: distance to target in yard
KillProbability=0.85                     //Chance to intercept missile
InterceptOutOfAltitudePenalty=0.18                  // yay!
InterceptSpeedPenaltyMultiplier=0.7                  // yay!
InterceptSizePenaltyMultiplier=0.55					// multiplier to the size penalty, 1.0 is default

[---------- Guidance ----------]
[Guidance]
InitialFlightPhaseDuration=1.0                // time in seconds where the missile moves straight on without guiding
#======================================== Flight Profile ===========================================================
#flight phase 4: terminal approach------------------------------------------------------------------------------------------------------
#Last stage - missile activates seeker and locks on target
IgnoreHeightDifferenceForTargetDist=True  // useful for hight loft alt missiles to ignore the height for distance calculation
#========================================= Launch stats ============================================================
MinAttackAltitude=15                   // Minimum altitude of a target, in feet. Outside Min/Max altitude missile deviation is greatly increaced
#========================================     Seeker     ===========================================================
#ECCM
AntiCountermeasuresBonus=0.40          // This value substracted from probability of spoofing by countermeasures (0...1)

[---------- Mesh definitions----------]

[Models]
ResourcesMeshSwitchTime=0.5  // time in seconds after launch to switch from launch mesh to main mesh