#!alias ammunition/usn_rim-66k.ini

# RIM-66M-2 SM-2MR Block IIIA

# Mk41 launched

[---------- Mesh definitions----------]
[Models]
ResourcesMaterialFolder=assets/europack/materials/RIM-66/
ResourcesMaterial=RIM-66M_mat.ini