[Animations]
NumberOfAnimations=4



Animation1=HangarLeftOpenAnim
Animation2=HangarLeftCloseAnim
Animation3=HangarRightOpenAnim
Animation4=HangarRightCloseAnim

##########################################################################


[HangarLeftOpenAnim]
NumberOfSequencesToPlay=7
Sequence1=Door_Up_1
Sequence1_Model=hangar_door_l1
Sequence2=Door_Up_2
Sequence2_Model=hangar_door_l2
Sequence3=Door_Up_3
Sequence3_Model=hangar_door_l3
Sequence4=Door_Up_4
Sequence4_Model=hangar_door_l4
Sequence5=Status_Red_Open_Launch
Sequence5_Model=Landing_Lights_Red
Sequence6=Status_Amber_Open_Launch
Sequence6_Model=Landing_Lights_Amber
Sequence7=Status_Green_Open_Launch
Sequence7_Model=Landing_Lights_Green

[HangarRightOpenAnim]
NumberOfSequencesToPlay=7
Sequence1=Door_Up_1
Sequence1_Model=hangar_door_r1
Sequence2=Door_Up_2
Sequence2_Model=hangar_door_r2
Sequence3=Door_Up_3
Sequence3_Model=hangar_door_r3
Sequence4=Door_Up_4
Sequence4_Model=hangar_door_r4
Sequence5=Status_Red_Open_Launch
Sequence5_Model=Landing_Lights_Red
Sequence6=Status_Amber_Open_Launch
Sequence6_Model=Landing_Lights_Amber
Sequence7=Status_Green_Open_Launch
Sequence7_Model=Landing_Lights_Green

[HangarLeftCloseAnim]
NumberOfSequencesToPlay=7
Sequence1=Door_Down_1
Sequence1_Model=hangar_door_l1
Sequence2=Door_Down_2
Sequence2_Model=hangar_door_l2
Sequence3=Door_Down_3
Sequence3_Model=hangar_door_l3
Sequence4=Door_Down_4
Sequence4_Model=hangar_door_l4
Sequence5=Status_Red_Close_Launch
Sequence5_Model=Landing_Lights_Red
Sequence6=Status_Amber_Close_Launch
Sequence6_Model=Landing_Lights_Amber
Sequence7=Status_Green_Close_Launch
Sequence7_Model=Landing_Lights_Green

[HangarRightCloseAnim]
NumberOfSequencesToPlay=7
Sequence1=Door_Down_1
Sequence1_Model=hangar_door_r1
Sequence2=Door_Down_2
Sequence2_Model=hangar_door_r2
Sequence3=Door_Down_3
Sequence3_Model=hangar_door_r3
Sequence4=Door_Down_4
Sequence4_Model=hangar_door_r4
Sequence5=Status_Red_Close_Launch
Sequence5_Model=Landing_Lights_Red
Sequence6=Status_Amber_Close_Launch
Sequence6_Model=Landing_Lights_Amber
Sequence7=Status_Green_Close_Launch
Sequence7_Model=Landing_Lights_Green

[------------------------------ Sequences ------------------------------]

[Door_Up_1]
NumberOfSteps=2
Step1=0|x,0.023,0.0255|x,y,z|Linear
Step2=4|x,0.038,0.0285|x,y,z|Linear

[Door_Up_2]
NumberOfSteps=2
Step1=0|x,0,0|x,y,z|Linear
Step2=4|x,0.016,0.006|x,y,z|Linear

[Door_Up_3]
NumberOfSteps=2
Step1=0|x,0,0|x,y,z|Linear
Step2=4|x,0.016,0.009|x,y,z|Linear

[Door_Up_4]
NumberOfSteps=2
Step1=0|x,0,0|x,y,z|Linear
Step2=4|x,0.019,0.0012|x,y,z|Linear

[Door_Down_1]
NumberOfSteps=2
Step1=0|x,0.038,0.0285|x,y,z|Linear
Step2=4|x,0.023,0.0255|x,y,z|Linear

[Door_Down_2]
NumberOfSteps=2
Step1=0|x,0.016,0.006|x,y,z|Linear
Step2=4|x,0,0|x,y,z|Linear

[Door_Down_3]
NumberOfSteps=2
Step1=0|x,0.016,0.009|x,y,z|Linear
Step2=4|x,0,0|x,y,z|Linear

[Door_Down_4]
NumberOfSteps=2
Step1=0|x,0.019,0.0012|x,y,z|Linear
Step2=4|x,0,0|x,y,z|Linear



######## Lights ########
# Amber and Red
# -90 = On, 0 = Off

# Green
# 0 = On, 90 = Off


[Status_Red_Open_Launch]
NumberOfSteps=3
Time1=0
RotationX1=-90
Smoothness1=EaseInOut
Time2=4
RotationX2=-90
Smoothness2=EaseInOut
Time3=4.1
RotationX3=0
Smoothness3=EaseInOut

[Status_Amber_Open_Launch]
NumberOfSteps=3
Time1=0
RotationX1=0
Smoothness1=EaseInOut
Time2=4
RotationX2=0
Smoothness2=EaseInOut
Time3=4.1
RotationX3=-90
Smoothness3=EaseInOut

[Status_Green_Open_Launch]
NumberOfSteps=3
Time1=0
RotationX1=90
Smoothness1=EaseInOut
Time2=4
RotationX2=90
Smoothness2=EaseInOut
Time3=4.1
RotationX3=90
Smoothness3=EaseInOut

[Status_Red_Close_Launch]
NumberOfSteps=3
Time1=0
RotationX1=0
Smoothness1=EaseInOut
Time2=4
RotationX2=0
Smoothness2=EaseInOut
Time3=4.1
RotationX3=0
Smoothness3=EaseInOut

[Status_Amber_Close_Launch]
NumberOfSteps=3
Time1=0
RotationX1=-90
Smoothness1=EaseInOut
Time2=4
RotationX2=-90
Smoothness2=EaseInOut
Time3=4.1
RotationX3=0
Smoothness3=EaseInOut

[Status_Green_Close_Launch]
NumberOfSteps=3
Time1=0
RotationX1=90
Smoothness1=EaseInOut
Time2=4
RotationX2=90
Smoothness2=EaseInOut
Time3=4.1
RotationX3=0
Smoothness3=EaseInOut