[LoadoutNames]
#------------------------------------------ New system ------------------------------------------
# - LongRange means operating range of aircraft, not the weapons range
# ---------- Mandatory loadouts ----------
Default=Mặc định                         // Usually most common loadout for this plane
Ferry=Tầm bay tối đa                          // Maximum fueltanks, no weapons, except guns and chaff
Empty=Rỗng                                // No fueltanks, no weapons, except guns and chaff

# ---------- Anti Air loadouts ----------
AirToAir=Không đối không                        // Standard Air to Air loadout for the type
AirToAirLongRange=Không đối không tầm xa    // Air to Air with less weapons and more fuel
AirToAirIntercept=Không đối không đánh chặn    // Air to Air loadouts with emphasis on MRAAM/SRAAM

# ---------- Anti Surface loadouts ----------
Strike=Không kích                              // Dumb bombs in 1 salvo
StrikeLongRange=Không kích tầm xa         // Same as Strike but less weapons, more fuel
StrikePrecision=Không kích chính xác           // Guided bombs or Strike missiles (like AS-7)
StrikeHeavy=Không kích hạng nặng                   // Strike loadout for heavy bombers. (To mark it for AI usage)
StrikeDemo=Không kích phá hủy              // Specialized loadout for super-heavy bombs (>1300kg) meant to obliterate point targets such as bunkers, bridges, and other hard targets
StrikeLowAlt=Không kích tầm thấp           // Low-level strike meant for retarded bombs, such as Snakeye or parachute bombs

CAS=Hỗ trợ mặt đất                      // Rockets, Cluster bombs, Bombs. Usually in small salvos to increace number of attacks
CASLight=Hỗ trợ mặt đất nhẹ          // Like CAS, but focusing on endurance over payload
AntiArmor=Chống xe tăng                         // Strike missiles mostly useful only land vehicles(like AS-7)

# ---------- Anti Ship loadouts ----------
AntiShip=Chống tàu                         // Most vague loadout. Can include anything from dumb bombs to medium-range missilies
AntiShipLongRange=Chống tàu tầm xa     // Same as AntiShip, but with fueltanks
AntiShipPrecision=Chống tàu chính xác      // Another vague loadout. Can include guided bombs and missilies
AntiShipHeavy=Chống tàu hạng nặng              // Designed to mark heavy anti-ship bombers like Tu-22 and Tu-16 and small planes with most weapons

# ---------- Anti Sub loadouts ----------
ASW=Chống ngầm                                    // Multirole ASW: Torpedoes, Depth Charges, Sonobuoys
ASWHunter=Săn ngầm                     // Sonobuoys only, no weapons
ASWHunterLight=Săn ngầm (Nhẹ)         // Sonobuoys only, no weapons
ASWKiller=Diệt ngầm                    // ASW weapons only
ASWBomb=Diệt ngầm (Bom chìm)                // ASW depth charges
ASWLongRange=Diệt ngầm tầm xa              // Torpedo + fuel tank

# ---------- Special loadouts ----------
SEAD=Áp chế phòng không                                  // Anti-radiation missilies, Cluster bombs
SEADLongRange=Áp chế phòng không tầm xa             // Same as SEAD, but less weaзons and more fueltanks
SEADAdvanced=Áp chế phòng không Nâng cao           	   // SEAD, but using accountable, limited-supply or time-restricted ammo like HARM, STARM or AS-11

AEW=Cảnh báo sớm                        // Just a flavor naming to indicate plane purpose. This loadout supposed to be equal to "Empty"
Recon=Trinh sát                                // Also indicates plane purpose. In some cases used for carrying recon pods.
EW=Tác chiến điện tử                     // Also indicates plane purpose. In some cases used for carrying EW pods.
Transport=Vận tải                       // Also indicates purpose.

Tanker=Tanker                              // Tanker loadout. Allows refueling

Gun=Chỉ mang pháo                              // Only Gun ammo loaded

# ---------- Cargo loadouts ----------
Containers=Container
Munitions=Đạn dược
MilitaryVehicles=Phương tiện quân sự
DryCargo=Hàng khô
Vehicles=Phương tiện
Fertilizer=Phân bón
Lighters=Sà lan
Oil=Dầu
Ore=Quặng
Passengers=Hành khách
Troops=Binh lính

# ---------- Generic Unit Loadout Options ----------
Early=Đời đầu
Late=Đời sau
