[Animations]
NumberOfAnimations=8

Animation1=Flaps_Takeoff
Animation2=Flaps_Takeoff_Retract
Animation3=Flaps_Landing
Animation4=Flaps_Landing_Retract
Animation5=Gear_Extend
Animation6=Gear_Retract
Animation7=Refueling_Extend
Animation8=Refueling_Retract

[Flaps_Takeoff]
NumberOfSequencesToPlay=4
Sequence1=left_outer_Down
Sequence1_Model=left_outer_flap
Sequence2=right_outer_Down
Sequence2_Model=right_outer_flap
Sequence3=Flap_Down_L
Sequence3_Model=left_inner_flap
Sequence4=Flap_Down_R
Sequence4_Model=right_inner_flap


[Flaps_Takeoff_Retract]
NumberOfSequencesToPlay=4
Sequence1=left_outer_up
Sequence1_Model=left_outer_flap
Sequence2=right_outer_up
Sequence2_Model=right_outer_flap
Sequence3=Flap_up_L
Sequence3_Model=left_inner_flap
Sequence4=Flap_up_R
Sequence4_Model=right_inner_flap

[Flaps_Landing]
NumberOfSequencesToPlay=4
Sequence1=left_outer_Down
Sequence1_Model=left_outer_flap
Sequence2=right_outer_Down
Sequence2_Model=right_outer_flap
Sequence3=Flap_Down_L
Sequence3_Model=left_inner_flap
Sequence4=Flap_Down_R
Sequence4_Model=right_inner_flap

[Flaps_Landing_Retract]
NumberOfSequencesToPlay=4
Sequence1=left_outer_up
Sequence1_Model=left_outer_flap
Sequence2=right_outer_up
Sequence2_Model=right_outer_flap
Sequence3=Flap_up_L
Sequence3_Model=left_inner_flap
Sequence4=Flap_up_R
Sequence4_Model=right_inner_flap

[Gear_Extend]
NumberOfSequencesToPlay=16
Sequence1=Nose_Gear_Down
Sequence1_Model=nose_gear
Sequence2=Mid_Gear_Down
Sequence2_Model=mid_gear
Sequence3=Right_Gear_Down
Sequence3_Model=right_gear
Sequence4=Left_Gear_Down
Sequence4_Model=left_gear

Sequence5=nose_door_L_small_open
Sequence5_Model=nose_gear_door_L_small
Sequence6=nose_door_R_small_open
Sequence6_Model=nose_gear_door_R_small
Sequence7=nose_door_L_open
Sequence7_Model=nose_gear_door_L
Sequence8=nose_door_R_open
Sequence8_Model=nose_gear_door_R

Sequence9=mid_door_L_small_open
Sequence9_Model=nose_mid_door_L_small
Sequence10=mid_door_R_small_open
Sequence10_Model=nose_mid_door_R_small
Sequence11=mid_door_L_open
Sequence11_Model=nose_mid_door_L
Sequence12=mid_door_R_open
Sequence12_Model=nose_mid_door_R

Sequence13=left_gear_door_1_open
Sequence13_Model=left_gear_door_1
Sequence14=right_gear_door_1_open
Sequence14_Model=right_gear_door_1
Sequence15=left_gear_door_2_open
Sequence15_Model=left_gear_door_2
Sequence16=right_gear_door_2_open
Sequence16_Model=right_gear_door_2

[Gear_Retract]
NumberOfSequencesToPlay=16
Sequence1=Nose_Gear_up
Sequence1_Model=nose_gear
Sequence2=Mid_Gear_up
Sequence2_Model=mid_gear
Sequence3=Right_Gear_up
Sequence3_Model=right_gear
Sequence4=Left_Gear_up
Sequence4_Model=left_gear

Sequence5=nose_door_L_small_close
Sequence5_Model=nose_gear_door_L_small
Sequence6=nose_door_R_small_close
Sequence6_Model=nose_gear_door_R_small
Sequence7=nose_door_L_open
Sequence7_Model=nose_gear_door_L
Sequence8=nose_door_R_open
Sequence8_Model=nose_gear_door_R

Sequence9=mid_door_L_small_close
Sequence9_Model=nose_mid_door_L_small
Sequence10=mid_door_R_small_close
Sequence10_Model=nose_mid_door_R_small
Sequence11=mid_door_L_open
Sequence11_Model=nose_mid_door_L
Sequence12=mid_door_R_open
Sequence12_Model=nose_mid_door_R

Sequence13=left_gear_door_1_close
Sequence13_Model=left_gear_door_1
Sequence14=right_gear_door_1_close
Sequence14_Model=right_gear_door_1
Sequence15=left_gear_door_2_open
Sequence15_Model=left_gear_door_2
Sequence16=right_gear_door_2_open
Sequence16_Model=right_gear_door_2

[Refueling_Extend]
NumberOfSequencesToPlay=1
Sequence1=Refueling_Down
Sequence1_Model=Refueling_boom

[Refueling_Retract]
NumberOfSequencesToPlay=1
Sequence1=Refueling_Up
Sequence1_Model=Refueling_boom

#############################################################
#Flaps_Takeoff
#############################################################

[left_outer_Down]
NumberOfSteps=2
Step1=0|0.184045,-0.005594,-0.130757|0,0,0|EaseInOut
Step2=5|0.184045,-0.005594,-0.130757|-15,0,7|EaseInOut

[right_outer_Down]
NumberOfSteps=2
Step1=0|-0.184045,-0.005594,-0.130757|0,0,0|EaseInOut
Step2=5|-0.184045,-0.005594,-0.130757|-15,0,-7|EaseInOut

[Flap_Down_L]
NumberOfSteps=2
Step1=0|0.069039,-0.018592,-0.089855|0,0,0|EaseInOut
Step2=5|0.069039,-0.018592,-0.089855|-10,0,2|EaseInOut

[Flap_Down_R]
NumberOfSteps=2
Step1=0|-0.069039,-0.018592,-0.089855|0,0,0|EaseInOut
Step2=5|-0.069039,-0.018592,-0.089855|-10,0,-2|EaseInOut

#############################################################
#Flaps_Takeoff_Retract
#############################################################

[left_outer_up]
NumberOfSteps=2
Step1=0|0.184045,-0.005594,-0.130757|-15,0,7|EaseInOut
Step2=5|0.184045,-0.005594,-0.130757|0,0,0|EaseInOut


[right_outer_up]
NumberOfSteps=2
Step1=0|-0.184045,-0.005594,-0.130757|-15,0,-7|EaseInOut
Step2=5|-0.184045,-0.005594,-0.130757|0,0,0|EaseInOut


[Flap_up_L]
NumberOfSteps=2
Step1=0|0.069039,-0.018592,-0.089855|-10,0,2|EaseInOut
Step2=5|0.069039,-0.018592,-0.089855|0,0,0|EaseInOut


[Flap_up_R]
NumberOfSteps=2
Step1=0|-0.069039,-0.018592,-0.089855|-10,0,-2|EaseInOut
Step2=5|-0.069039,-0.018592,-0.089855|0,0,0|EaseInOut

#############################################################
#Gear_Extend
#############################################################

[Nose_Gear_Down]
NumberOfSteps=2
Step1=2|x,y,z|-90,0,0|Linear
Step2=7|x,y,z|0,0,0|Linear

[Mid_Gear_Down]
NumberOfSteps=2
Step1=2|x,y,z|-90,0,0|Linear
Step2=7|x,y,z|0,0,0|Linear

[Right_Gear_Down]
NumberOfSteps=2
Step1=2|x,y,z|0,0,80|Linear
Step2=7|x,y,z|0,0,0|Linear

[Left_Gear_Down]
NumberOfSteps=2
Step1=2|x,y,z|0,0,-80|Linear
Step2=7|x,y,z|0,0,0|Linear



[nose_door_L_small_open]
NumberOfSteps=2
Step1=0|x,y,z|0,0,0|Linear
Step2=3|x,y,z|0,0,80|Linear

[nose_door_R_small_open]
NumberOfSteps=2
Step1=0|x,y,z|0,0,0|Linear
Step2=3|x,y,z|0,0,-80|Linear

[nose_door_L_open]
NumberOfSteps=4
Step1=0|x,y,z|0,0,0|Linear
Step2=3|x,y,z|0,8,78|Linear
Step3=5|x,y,z|0,8,78|Linear
Step4=8|x,y,z|0,0,0|Linear

[nose_door_R_open]
NumberOfSteps=4
Step1=0|x,y,z|0,0,0|Linear
Step2=3|x,y,z|0,-8,-78|Linear
Step3=5|x,y,z|0,-8,-78|Linear
Step4=8|x,y,z|0,0,0|Linear




[mid_door_L_small_open]
NumberOfSteps=2
Step1=0|x,y,z|0,0,0|Linear
Step2=3|x,y,z|0,0,80|Linear

[mid_door_R_small_open]
NumberOfSteps=2
Step1=0|x,y,z|0,0,0|Linear
Step2=3|x,y,z|0,0,-80|Linear

[mid_door_L_open]
NumberOfSteps=4
Step1=0|x,y,z|0,0,0|Linear
Step2=3|x,y,z|0,0,80|Linear
Step3=5|x,y,z|0,0,80|Linear
Step4=8|x,y,z|0,0,0|Linear

[mid_door_R_open]
NumberOfSteps=4
Step1=0|x,y,z|0,0,0|Linear
Step2=3|x,y,z|0,0,-80|Linear
Step3=5|x,y,z|0,0,-80|Linear
Step4=8|x,y,z|0,0,0|Linear




[left_gear_door_1_open]
NumberOfSteps=2
Step1=2|x,y,z|0,0,0|Linear
Step2=7|x,y,z|0,0,85|Linear

[right_gear_door_1_open]
NumberOfSteps=2
Step1=2|x,y,z|0,0,0|Linear
Step2=7|x,y,z|0,0,-85|Linear

[left_gear_door_2_open]
NumberOfSteps=4
Step1=0|x,y,z|0,0,0|Linear
Step2=3|x,y,z|0,0,-80|Linear
Step3=5|x,y,z|0,0,-80|Linear
Step4=8|x,y,z|0,0,0|Linear

[right_gear_door_2_open]
NumberOfSteps=4
Step1=0|x,y,z|0,0,0|Linear
Step2=3|x,y,z|0,0,80|Linear
Step3=5|x,y,z|0,0,80|Linear
Step4=8|x,y,z|0,0,0|Linear


#############################################################
#Gear_Retract
#############################################################

[Nose_Gear_up]
NumberOfSteps=2
Step1=0|x,y,z|0,0,0|Linear
Step2=5|x,y,z|-90,0,0|Linear

[Mid_Gear_up]
NumberOfSteps=2
Step1=0|x,y,z|0,0,0|Linear
Step2=5|x,y,z|-90,0,0|Linear

[Right_Gear_up]
NumberOfSteps=2
Step1=0|x,y,z|0,0,0|Linear
Step2=5|x,y,z|0,0,80|Linear

[Left_Gear_up]
NumberOfSteps=2
Step1=0|x,y,z|0,0,0|Linear
Step2=5|x,y,z|0,0,-80|Linear

[nose_door_L_small_close]
NumberOfSteps=2
Step1=0|x,y,z|0,0,80|Linear
Step2=3|x,y,z|0,0,0|Linear


[nose_door_R_small_close]
NumberOfSteps=2
Step1=0|x,y,z|0,0,-80|Linear
Step2=3|x,y,z|0,0,0|Linear

[mid_door_L_small_close]
NumberOfSteps=2
Step1=0|x,y,z|0,0,80|Linear
Step2=3|x,y,z|0,0,0|Linear


[mid_door_R_small_close]
NumberOfSteps=2
Step1=0|x,y,z|0,0,-80|Linear
Step2=3|x,y,z|0,0,0|Linear

[left_gear_door_1_close]
NumberOfSteps=2
Step1=0|x,y,z|0,0,85|Linear
Step2=5|x,y,z|0,0,0|Linear

[right_gear_door_1_close]
NumberOfSteps=2
Step1=0|x,y,z|0,0,-85|Linear
Step2=5|x,y,z|0,0,0|Linear


#############################################################

#############################################################

[Refueling_Down]
NumberOfSteps=2
Step1=0|x,y,z|x,y,z|Linear
Step2=4|x,y,z|-40,y,z|Linear

[Refueling_Up]
NumberOfSteps=2
Step1=0|x,y,z|-40,y,z|Linear
Step2=4|x,y,z|0,y,z|Linear
