[Animations]
Animation1=HangarOpenAnim
Animation2=HangarCloseAnim
Animation3=TorpedoDoorOpenL
Animation4=TorpedoDoorCloseL
Animation5=TorpedoDoorOpenR
Animation6=TorpedoDoorCloseR


[HangarOpenAnim]
NumberOfSequencesToPlay=2
Sequence1=HangarOpenDoorLAnimSequence
Sequence1_Model=HangarDoor_1
Sequence2=HangarOpenDoorRAnimSequence
Sequence2_Model=HangarDoor_2

[HangarCloseAnim]
NumberOfSequencesToPlay=2
Sequence1=HangarCloseDoorLAnimSequence
Sequence1_Model=HangarDoor_1
Sequence2=HangarCloseDoorRAnimSequence
Sequence2_Model=HangarDoor_2

[TorpedoDoorOpenL]
NumberOfSequencesToPlay=1
Sequence1=TorpedoDoorOpenSequence
Sequence1_Model=Torpille_door_d


[TorpedoDoorOpenR]
NumberOfSequencesToPlay=1
Sequence1=TorpedoDoorOpenSequence2
Sequence1_Model=Torpille_door_g


[TorpedoDoorCloseL]
NumberOfSequencesToPlay=1
Sequence1=TorpedoDoorCloseSequence
Sequence1_Model=Torpille_door_d

[TorpedoDoorCloseR]
NumberOfSequencesToPlay=1
Sequence1=TorpedoDoorCloseSequence2
Sequence1_Model=Torpille_door_g


[------------------------------ Sequences ------------------------------]
// possible values for rotations are either a complete vector (x,y,z)
// or single axis like RotationX1, RotationY1, RotationZ1
// same is true for positions
// both rotation and position values are optional, so if you leave the position away,
// only the rotation will be applied

[------------------------------ FlightDeck Sequences ------------------------------]
#Open Hangar Doors
[HangarOpenDoorLAnimSequence]
NumberOfSteps=2
Time1=1                // time in seconds for the start
RotationX1=0
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time2=10            // time in seconds - here for the end
RotationX2=80
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry

[HangarOpenDoorRAnimSequence]
NumberOfSteps=2
Time1=1                // time in seconds for the start
RotationX1=0
PositionY1=0.13929
PositionZ1=-0.6695
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time2=9.5            // time in seconds - here for the end
RotationX2=-90
PositionY2=0.182
PositionZ2=-0.709
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry

[HangarCloseDoorLAnimSequence]
NumberOfSteps=2
Time1=1                // time in seconds for the start
RotationX1=80
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time2=10           // time in seconds - here for the end
RotationX2=0
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry

[HangarCloseDoorRAnimSequence]
NumberOfSteps=2
Time1=1                // time in seconds for the start
RotationX1=-90
PositionY1=0.182
PositionZ1=-0.709
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time2=9.5            // time in seconds - here for the end
RotationX2=0
PositionY2=0.13929
PositionZ2=-0.6695
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry

[TorpedoDoorOpenSequence]
NumberOfSteps=2
Time1=0
RotationZ1=0
Smoothness1=EaseInOut
Time2=3
RotationZ2=90
Smoothness2=EaseInOut

[TorpedoDoorCloseSequence]
NumberOfSteps=2
Time1=0
RotationZ1=90
Smoothness1=EaseInOut
Time2=3
RotationZ2=0
Smoothness2=EaseInOut

[TorpedoDoorOpenSequence2]
NumberOfSteps=2
Time1=0
RotationZ1=0
Smoothness1=EaseInOut
Time2=3
RotationZ2=-90
Smoothness2=EaseInOut

[TorpedoDoorCloseSequence2]
NumberOfSteps=2
Time1=0
RotationZ1=-90
Smoothness1=EaseInOut
Time2=3
RotationZ2=0
Smoothness2=EaseInOut

