[LoadoutNames]
#------------------------------------------ New system ------------------------------------------
# - LongRange means operating range of aircraft, not the weapons range
# - LongRangeは兵装の射程ではなく、機体の航続距離を指す
# ---------- Mandatory loadouts ----------
Default=デフォルト                            // 通常、その機体で最も一般的な兵装
Ferry=増槽                                // 最大数の燃料タンクを装備。武器なし（機関砲とチャフを除く）
Empty=装備なし                                // 燃料タンクなし、武器なし（機関砲とチャフを除く）

# ---------- Anti Air loadouts ----------
AirToAir=空対空(標準)                        // 当該機種の標準的な対空兵装
AirToAirLongRange=空対空(長距離航続)    // 武装を減らし、燃料を増やした対空兵装
AirToAirIntercept=空対空(迎撃)     // MRAAM/SRAAMを重視した迎撃用兵装

# ---------- Anti Surface loadouts ----------
Strike=爆装(標準)                              // 無誘導爆弾（1斉射分）
StrikeLongRange=爆装(長距離航続)          // Strikeと同様だが、武装を減らし燃料を増加
StrikePrecision=爆装(誘導兵器)           // 誘導爆弾または対地ミサイル（AS-7など）
StrikeHeavy=爆装(重装備)                   // 重爆撃機用の攻撃兵装（AI識別用）
StrikeDemo=対建造物                 // バンカー、橋梁、その他の堅固な点目標を粉砕するための、1300kg超の超重量級爆弾を用いた特殊兵装
StrikeLowAlt=低空攻撃                   // スネークアイやパラシュート爆弾などの高抵抗爆弾を用いた低高度攻撃

CAS=近接航空支援                      // ロケット弾、クラスター爆弾、通常爆弾。攻撃回数を増やすため小分けにして使用
CASLight=近接航空支援(軽装)             // CASと同様だが、兵装搭載量よりも滞空性能を重視した構成
AntiArmor=対戦車                         // 主に陸上車両に有効な対地ミサイル（AS-7など）
LandAttack=対地攻撃                         // 長距離空対地（地対地）巡航ミサイル搭載（対地攻撃用、例：AGM-86CまたはRGM-109C対地巡航ミサイル）
# ---------- Anti Ship loadouts ----------
AntiShip=対艦(標準)                       // 最も広範な区分。無誘導爆弾から中距離ミサイルまでを含む
AntiShipLongRange=対艦(長距離航続)     // AntiShipと同様だが、増槽を装備
AntiShipPrecision=対艦(誘導兵器)           // 誘導爆弾やミサイルを含む精密対艦兵装
AntiShipHeavy=対艦(重装備)              // Tu-22やTu-16といった重対艦爆撃機、および最大兵装の小型機用

# ---------- Anti Sub loadouts ----------
ASW=対潜(多目的)                                    // 多用途対潜：魚雷、爆雷、ソノブイ
ASWHunter=ソノブイ                       // ソノブイのみ、攻撃兵器なし
ASWHunterLight=ソノブイ(軽装)          // ソノブイのみ、攻撃兵器なし
ASWKiller=対潜兵装                       // 対潜兵器のみ
ASWBomb=対潜(爆雷)                  // 対潜用深海爆雷
ASWLongRange=対潜(長距離航続)				   // 魚雷 + 増槽

# ---------- Special loadouts ----------
SEAD=SEAD(敵防空網制圧)                                  // 対レーダーミサイル、クラスター爆弾
SEADLongRange=敵防空網制圧(長距離航続)              // SEADと同様だが、武装を減らし燃料を増加
SEADAdvanced=敵防空網制圧(高度)            	   // SEAD。HARM、STARM、AS-11といった、数量限定または供給制限のある弾薬を使用

AEW=早期警戒                          // 機体用途を示す呼称。兵装自体は"Empty"と同等
Recon=偵察                                // 機体用途を示す。偵察ポッドを装備する場合がある
EW=電子戦                                // 機体用途を示す。電子戦ポッドを装備する場合がある
Transport=輸送                        // 機体用途を示す

Tanker=空中給油機                              // 給油兵装。他機への給油を可能にする

Gun=機関砲のみ                               // 機関砲弾のみを搭載

# ---------- Cargo loadouts ----------
Containers=コンテナ
Munitions=弾薬
MilitaryVehicles=軍用車両
DryCargo=ドライカーゴ
Vehicles=車両
Fertilizer=肥料
Lighters=はしけ
Oil=石油
Ore=鉱石
Passengers=乗客
Troops=部隊

# ---------- Generic Unit Loadout Options ----------
Early=早期
Late=後期
Kiev=Kiev レーダーデコイ
Kirov=Kirov レーダーデコイ
Udaloy=Udaloy レーダーデコイ
Sovremenny=Sovremenny レーダーデコイ
Sverdlov=Sverdlov レーダーデコイ
Kynda=Kynda レーダーデコイ
KrestaI=Kresta I レーダーデコイ
KrestaII=Kresta II レーダーデコイ
Kara=Kara レーダーデコイ
Petya=Petya レーダーデコイ
KrivakI=Krivak I レーダーデコイ
KrivakII=Krivak II レーダーデコイ