#########################################################
# BRIDGES
#########################################################
[Objects]
NumberOfObjects=4
Object1=bridge_paul_doumer
Object2=bridge_generic_3part
Object3=bridge_generic_6part
Object4=bridge_generic_arched_6part

[bridge_paul_doumer]
Name=Bridge Paul Doumer
IniFile=bridge_paul_doumer_full

[bridge_generic_3part]
Name=Bridge Generic Red 3 parts
IniFile=bridge_generic_3part

[bridge_generic_6part]
Name=Bridge Generic Red 6 parts
IniFile=bridge_generic_6part

[bridge_generic_arched_6part]
Name=Bridge Arched Green 6 parts
IniFile=bridge_generic_arched_6part
