#########################################################
# PERSIAN GULF PROPS (city chunks ports fields etc)
#########################################################
[Objects]
NumberOfObjects=17
Object1=pg_fields_1
Object2=pg_fields_2
Object3=pg_fields_3
Object4=pg_fields_4
Object5=pg_fields_5
Object6=pg_fields_6
Object7=pg_harbour_1
Object8=pg_harbour_2
Object9=pg_harbour_3
Object10=pg_harbour_4
Object11=pg_harbour_5
Object12=pg_harbour_6
Object13=pg_shore_town_1
Object14=pg_shore_town_2
Object15=pg_shore_town_3
Object16=pg_shore_town_4
Object17=pg_shore_town_5

[pg_fields_1]
Name=Persian Gulf fields 1
IniFile=pg_fields_1

[pg_fields_2]
Name=Persian Gulf fields 2
IniFile=pg_fields_2

[pg_fields_3]
Name=Persian Gulf fields 3
IniFile=pg_fields_3

[pg_fields_4]
Name=Persian Gulf fields 4
IniFile=pg_fields_4

[pg_fields_5]
Name=Persian Gulf fields 5
IniFile=pg_fields_5

[pg_fields_6]
Name=Persian Gulf fields 6
IniFile=pg_fields_6

[pg_harbour_1]
Name=Persian Gulf Harbour 1
IniFile=pg_harbour_1

[pg_harbour_2]
Name=Persian Gulf Harbour 2
IniFile=pg_harbour_2

[pg_harbour_3]
Name=Persian Gulf Harbour 3
IniFile=pg_harbour_3

[pg_harbour_4]
Name=Persian Gulf Harbour 4
IniFile=pg_harbour_4

[pg_harbour_5]
Name=Persian Gulf Harbour 5
IniFile=pg_harbour_5

[pg_harbour_6]
Name=Persian Gulf Harbour 6
IniFile=pg_harbour_6

[pg_shore_town_1]
Name=Persian Gulf Shore Town 1
IniFile=pg_shore_town_1

[pg_shore_town_2]
Name=Persian Gulf Shore Town 2
IniFile=pg_shore_town_2

[pg_shore_town_3]
Name=Persian Gulf Shore Town 3
IniFile=pg_shore_town_3

[pg_shore_town_4]
Name=Persian Gulf Shore Town 4
IniFile=pg_shore_town_4

[pg_shore_town_5]
Name=Persian Gulf Shore Town 5
IniFile=pg_shore_town_5
