[------------------------------ Images ------------------------------]
[NationFlags]
Unknown=ui/bottom/flag_unknown
Albania=ui/bottom/flag_albania.png
Albania_Navy=ui/bottom/flag_albania.png
Algeria=ui/bottom/flag_algeria
Angola=ui/bottom/flag_angola.png
Argentina=ui/bottom/flag_argentina.png
Australia=ui/bottom/flag_australia
Australian_Navy=ui/bottom/flag_australia
Austria=ui/bottom/flag_austria.png
Austrian_Navy=ui/bottom/flag_austria.png
Bahamas=ui/bottom/flag_bahamas.png
Bahamas_Navy=ui/bottom/flag_bahamas.png
Belgium=ui/bottom/flag_belgium.png
Belgium_navy=ui/bottom/flag_belgium.png
Bosnia=ui/bottom/flag_bosnia.png
Brazil=ui/bottom/flag_brazil
Bulgaria=ui/bottom/flag_bulgaria
Cameroon=ui/bottom/flag_cameroon.png
Canada=ui/bottom/flag_canada
Canadian_Navy=ui/bottom/flag_canada
Chile=ui/bottom/flag_chile.png
China=ui/bottom/flag_china
Chinese_Navy=ui/bottom/flag_china
Colombia=ui/bottom/flag_colombia.png
Colombia_Navy=ui/bottom/flag_colombia.png
Costa_Rica=ui/bottom/flag_costarica.png
Cote_divoire=ui/bottom/flag_cote_divoire.png
Croatia=ui/bottom/flag_croatia.png
Croatia_Navy=ui/bottom/flag_croatia.png
Cuba=ui/bottom/flag_cuba
Cyprus=ui/bottom/flag_cyprus
Czech=ui/bottom/flag_czech
DDR=ui/bottom/flag_ddr
DDR_Navy=ui/bottom/flag_ddr
Denmark=ui/bottom/flag_dk
Dominican_Republic=ui/bottom/flag_domenicanrep.png
Dominican_Republic_Navy=ui/bottom/flag_domenicanrep.png
Egypt=ui/bottom/flag_egypt                //Egypt 1977-1984
Egyptian_Navy=ui/bottom/flag_egypt
Ecuador=ui/bottom/flag_ecuador.png
Ecuador_Navy=ui/bottom/flag_ecuador.png
El_Salvador=ui/bottom/flag_elsalvador.png
El_Salvador_Navy=ui/bottom/flag_elsalvador.png
Estonia=ui/bottom/flag_estonia.png
Finland=ui/bottom/flag_finland
France=ui/bottom/flag_france
Germany=ui/bottom/flag_ger
Georgia=ui/bottom/flag_georgia.png
Georgia_Navy=ui/bottom/flag_georgia.png
Ghana=ui/bottom/flag_ghana.png
Ghana_Navy=ui/bottom/flag_ghana.png
Greece=ui/bottom/flag_greece
Grenada=ui/bottom/flag_grenada.png
Grenadan_CG=ui/bottom/flag_grenada.png
Guatemala=ui/bottom/flag_guatemala.png
Guatemala_Navy=ui/bottom/flag_guatemala.png
Haiti=ui/bottom/flag_haiti.png
Haiti_Navy=ui/bottom/flag_haiti.png
Honduras=ui/bottom/flag_honduras.png
Honduras_Navy=ui/bottom/flag_honduras.png
Hungary=ui/bottom/flag_hungary
Iceland=ui/bottom/flag_iceland
India=ui/bottom/flag_india
Indian_Navy=ui/bottom/flag_india
Indonesia=ui/bottom/flag_indonesia.png
Iran=ui/bottom/flag_iran
Iraq=ui/bottom/flag_iraq
Israel=ui/bottom/flag_israel
Israeli_Navy=ui/bottom/flag_israel
Italy=ui/bottom/flag_italy
Italian_Navy=ui/bottom/flag_italy
Jamaica=ui/bottom/flag_jamaica.png
Jamaica_Navy=ui/bottom/flag_jamaica.png
Japan=ui/bottom/flag_japan
Japanese_Navy=ui/bottom/flag_japan
Jordan=ui/bottom/flag_jordan
Jordanian_Navy=ui/bottom/flag_jordan
Kuwait=ui/bottom/flag_kuwait
Latvia=ui/bottom/flag_latvia.png
Latvia_Navy=ui/bottom/flag_latvia.png
Libya=ui/bottom/flag_libya
Libyan_Navy=ui/bottom/flag_libya
Liberia=ui/bottom/flag_liberia
Lithuania=ui/bottom/flag_lithuania.png
Madagascar=ui/bottom/flag_madagascar.png
Malaysia=ui/bottom/flag_malaysia.png
Malaysia_Navy=ui/bottom/flag_malaysia.png
Mauritania=ui/bottom/flag_mauritania.png
Mexico=ui/bottom/flag_mexico.png
Malta=ui/bottom/flag_malta
Marshall_Islands=ui/bottom/flag_marshall_islands
Montenegro=ui/bottom/flag_montenegro.png
Montenegro_Navy=ui/bottom/flag_montenegro.png
Morocco=ui/bottom/flag_morocco.png
Morocco_Navy=ui/bottom/flag_morocco.png
Myanmar=ui/bottom/flag_myanmar
Myanmar_Navy=ui/bottom/flag_myanmar
NATO=ui/bottom/flag_nato.png
Netherlands=ui/bottom/flag_nl
NewZealand=ui/bottom/flag_nz_state
NewZealand_Navy=ui/bottom/flag_nz_state
Nigeria=ui/bottom/flag_nigeria.png
Nigeria_Navy=ui/bottom/flag_nigeria.png
North_Korea=ui/bottom/flag_north_korea
North_Korean_Navy=ui/bottom/flag_north_korea
Norway=ui/bottom/flag_no
Oman=ui/bottom/flag_oman.png
Oman_Navy=ui/bottom/flag_oman.png
Pakistan=ui/bottom/flag_pakistan
Panama=ui/bottom/flag_panama
Pirates=ui/bottom/flag_pirate.png
Philippines=ui/bottom/flag_philippines
Philippines_Navy=ui/bottom/flag_philippines
Poland=ui/bottom/flag_poland
Portugal=ui/bottom/flag_portugal
Qatar=ui/bottom/flag_qatar.png
Romania=ui/bottom/flag_romania
Russia=ui/bottom/flag_russia2.png
Russia_Navy=ui/bottom/flag_russia2.png
Saudi_Arabia=ui/bottom/flag_saudi_arabia.png
Saudi_Arabia_Navy=ui/bottom/flag_saudi_arabia.png
Slovenia=ui/bottom/flag_slovenia.png
South_Africa=ui/bottom/flag_south_africa
South_African_Modern=ui/bottom/flag_south_africa_mod.png
South_African_Navy=ui/bottom/flag_south_africa
South_African_Navy_Mod=ui/bottom/flag_south_africa_mod.png
South_Korea=ui/bottom/flag_s_korea
South_Vietnam=ui/bottom/flag_s_vietnam
Singapore=ui/bottom/flag_singapore
Singapore_Navy=ui/bottom/flag_singapore
Spain=ui/bottom/flag_spain
Sweden=ui/bottom/flag_sweden
Switzerland=ui/bottom/flag_switzerland
Syria=ui/bottom/flag_syria                //Also Egypt 1958-1972
Taiwan=ui/bottom/flag_roc.png
Thailand=ui/bottom/flag_thailand
Thai_Navy=ui/bottom/flag_thailand
Trinidad=ui/bottom/flag_trinidad.png
Trinidad_Navy=ui/bottom/flag_trinidad.png
Tunisia=ui/bottom/flag_tunisia.png
Turkiye=ui/bottom/flag_turkiye.png
UAE=ui/bottom/flag_uae.png
UK=ui/bottom/flag_uk
UK_Navy=ui/bottom/flag_uk
Ukraine=ui/bottom/flag_ukraine.png
Ukraine_Navy=ui/bottom/flag_ukraine.png
United_Nations=ui/bottom/flag_un.png
Uruguay=ui/bottom/flag_uruguay.png
US=ui/bottom/flag_us
Venezuela=ui/bottom/flag_venezuela.png
#SovietNavy=ui/bottom/flag_soviet
Soviet=ui/bottom/flag_ussr
Soviet_Navy=ui/bottom/flag_ussr
Vietnam=ui/bottom/flag_vietnam
Yugoslavia=ui/bottom/flag_yugoslavia.png
Yugoslavia_Navy=ui/bottom/flag_yugoslavia.png
Western_Sahara=ui/bottom/flag_wsahara.png

[MastFlags]
Albania=flag_albania.png
Albania_Navy=flag_albania_an.png
Algeria=flag_algeria
Angola=flag_angola.png
Argentina=flag_argentina.png
Australia=flag_civ_australia
Australian_Navy=flag_australia
Austria=flag_austria.png
Austrian_Navy=flag_austria_an.png
Bahamas=flag_bahamas_civ.png
Bahamas_Navy=flag_bahamas_bn.png
Belgium=flag_belgium.png
Belgium_Navy=flag_belgium_bn.png
Bosnia=flag_bosnia.png
Brazil=flag_brazil
Bulgaria=flag_bulgaria
Cameroon=flag_cameroon.png
Canada=flag_canada.png
Canadian_Navy=flag_canada_rcn.png
Chile=flag_chile.png
China=flag_prc
Chinese_Navy=flag_china_pla.png
Colombia=flag_colombia_civ.png
Colombia_Navy=flag_colombia_cn.png
Costa_Rica=flag_costarica.png
Cote_divoire=flag_cote_divoire.png
Croatia=flag_croatia_civ.png
Croatia_Navy=flag_croatia_cn.png
Cuba=flag_cuba.png
Cyprus=flag_cyprus
Czech=flag_czech.png
DDR=flag_ddr
DDR_Navy=flag_ddr_ensign
Denmark=flag_dk
Dominican_Republic=flag_domenicanrep_civ.png
Dominican_Republic_Navy=flag_domenicanrep.png
Ecuador=flag_ecuador_civ.png
Ecuador_Navy=flag_ecuador.png
Egypt=flag_egypt.png
Egyptian_Navy=flag_egypt_en.png
El_Salvador=flag_elsalvador.png
El_Salvador_Navy=flag_elsalvador_ens.png
Estonia=flag_estonia.png
Finland=flag_finland.png
France=flag_france
Georgia=flag_georgia.png
Georgia_Navy=flag_georgia_warsign.png
Germany=flag_ger
Ghana=flag_ghana.png
Ghana_Navy=flag_ghana_gn.png
Greece=flag_greece
Grenada=flag_grenada.png
Grenadan_CG=flag_grenada_gcg.png
Guatemala=flag_guatemala_civ.png
Guatemala_Navy=flag_guatemala.png
Haiti=flag_haiti_civ.png
Haiti_Navy=flag_haiti.png
Honduras=flag_honduras.png
Honduras_Navy=flag_honduras_hn.png
Hungary=flag_hungary
Iceland=flag_ice
India=flag_india2.png
Indian_Navy=flag_india_in.png
Indonesia=flag_indonesia.png
Iran=flag_iran
Iraq=flag_iraq
Israel=flag_civ_israel
Israeli_Navy=flag_israel
Italy=flag_italy
Italian_Navy=flag_civ_italy
Jamaica=flag_jamaica_civ.png
Jamaica_Navy=flag_jamaica_jn.png
Japan=flag_civ_japan
Japanese_Navy=flag_japan_jsdn.png
Jordan=flag_jordan.png
Jordanian_Navy=flag_jordan_jn.png
Kuwait=flag_kuwait
Latvia=flag_latvia.png
Latvia_Navy=flag_latvia_ln.png
Libya=flag_libya
Libyan_Navy=flag_libya_ln.png
Liberia=flag_liberia
Lithuania=flag_lithuania.png
Madagascar=flag_madagascar.png
Malaysia=flag_malaysia.png
Malaysia_Navy=flag_malaysia_rmn.png
Malta=flag_civ_malta
Marshall_Islands=flag_mar_isl
Mauritania=flag_mauritania.png
Mexico=flag_mexico.png
Montenegro=flag_montenegro.png
Montenegro_Navy=flag_montenegro_mn.png
Morocco=flag_morocco.png
Morocco_Navy=flag_morocco_rmn.png
Myanmar=flag_myanmar
Myanmar_Navy=flag_myanmar_mn.png
NATO=flag_nato.png
Netherlands=flag_nl
NewZealand=flag_civ_nz
NewZealand_Navy=flag_nz_rnzn.png
Nigeria=flag_nigeria.png
Nigeria_Navy=flag_nigeria_nn.png
Norway=flag_nor
North_Korea=flag_northkorea.png
North_Korean_Navy=flag_northkorea_kpn.png
Oman=flag_oman.png
Oman_Navy=flag_oman_ron.png
Pakistan=flag_pak,flag_civ_pakistan
Panama=flag_panama
Philippines=flag_phil
Philippines_Navy=flag_phil_pn.png
Pirates=flag_pirate.png
Poland=flag_pl
Portugal=flag_portugal
Qatar=flag_qatar.png
Romania=flag_romania
Russia=flag_rus
Russia_Navy=flag_civ_rus
Saudi_Arabia=flag_saudi_arabia.png
Saudi_Arabia_Navy=flag_saudi_arabia_san.png
Slovenia=flag_slovenia.png
South_Africa=flag_south_africa.png
South_African_Modern=flag_south_africa_mod.png
South_African_Navy=flag_south_africa_san.png
South_African_Navy_Mod=flag_south_africa_mod_san.png
South_Korea=flag_s_korea
South_Vietnam=flag_s_vietnam
Singapore=flag_singapore
Singapore_Navy=flag_singapore_sn.png
Spain=flag_spain
Sweden=flag_swe
Switzerland=flag_switzerland
Syria=flag_syria
Taiwan=flag_roc.png
Thailand=flag_thailand.png
Thai_Navy=flag_thailand_rtn.png
Trinidad=flag_trinidad.png
Trinidad_Navy=flag_trinidad_tn.png
Tunisia=flag_tunisia.png
Turkiye=flag_turkiye.png
UAE=flag_uae.png
UK=flag_red_ensign
UK_Navy=flag_rn
Ukraine=flag_ukraine.png
Ukraine_Navy=flag_ukraine_un.png
United_Nations=flag_un.png
Uruguay=flag_uruguay.png
US=flag_us
Soviet=flag_civ_soviet
Soviet_Navy=flag_soviet
Venezuela=flag_venezuela.png
Vietnam=flag_viet_vn.png
Western_Sahara=flag_wsahara.png
#Vietnam=flag_viet,flag_civ_vietnam
Yugoslavia=flag_yugoslavia.png
Yugoslavia_Navy=flag_yugoslavia_yn.png








