[---------- General Data ----------]
[General]
UnitType=Aircraft
Size=Large

DefaultCameraDistance=1
MinCameraDistanceForeAft=0.7
MinCameraDistanceBroadside=0.7
CameraPivotHeight=0.0

#Taxi values
GroundedPitchAngle=0.0    // this angle is the pitch (x) angle at ground with gears down
GroundPivot=0,-0.0408,0   // defines the relative location of the landing gear
TaxiInterval=0.85              // In unity units. Minimum distance between planes while taxiing
LandingPitch=-5

[AI]
Role=AEW

[SensorData]
#Visual
VisualIdentificationRange=6.0  // at what range in nm this unit can be visually identified
IRSignature=Meager
# Radar related (RCS => radar cross section)
RCS=Meager

[Animations]
NumberOfAnimationReferences=1
AnimationFile_1=animations_dts_saab_ge

[---------- Flight Model ----------]
[Engine]
EngineIntakeArea=1.48             //Pi* r * r where r is engine radius, in meters

[FlightModel]
PitchGain=0.8                         // Vertical manuverability
VelocityGain=0.1136                   // Acceleration
HeadingGain=2                         // Horizontal manuverability
YawRateLimit=130                      // in degrees per second

BankGain=0.8                          // Roll change speed
MaxRollForHeading=45.0                // bank limit in normal flight
MaxRollRate=60.0                      // in degrees per second

ThrustGain=0.325                      // Thrust change speed
SpeedBrakeFractionGain=10            // Speed brakes deploy speed

SpeedDeltaPerAltitudeChange=0.0885

[Performance]
#Dimensions
WingSpan=28.60                           //meters
#Parameters
MaxG=5                                // Mostly for horizontal turns

MaxClimbRate=20.0                     //Meters per second
EmptyMass=23691                       // in kg
MaxFuel=20434                         // in kg

PerEngineMaxThrust=65600              //Newtons
EngineCount=2

Ceiling=35000.0                       // ceiling in feet
CruiseAltitude=30000                  //in feet
#"Engine" efficiency at 0ft, 37000 ft, 65000 ft. Always 1 for cruise altitude
AltitudeEfficiency=0.5,0.6,0.25       // Defines fuel consumption with altitude

#Governing of max speed
MaxSpeedAtSeaLevel=430                //in knots, Defines max speed at altitude curve
StallSpeed=110.0                      //in knots
MachLimit=0.8                         //for 37000ft, Defines max speed at altitude curve

#SpeedAndRange   MachNumbers or knots, Specified units or multiplier (except Cruise range)
RangeUnits=Miles                      // Can be: Km. Any other value = nmi. Defines measurment units of ranges of SpeedAndRange values

SpeedAndRange_Landing=0.24,0.4        // Landing
SpeedAndRange_Loiter=0.5,0.6          // Loiter
SpeedAndRange_Cruise=0.64,6200        // Cruise
SpeedAndRange_Max=0.8,0.8             // Attack/Fast/High/Max without AB


Altitudes=1000,3000,6000,10000,20000,35000  // in feet

[---------- Main Systems ----------]
[FlightControls]
NumberOfAilerons=2
Aileron1_Model=Left_Aileron
Aileron1_MinAngle=-15.0
Aileron1_MaxAngle=15.0
Aileron1_BaseAngle=0.0
Aileron2_Model=Right_Aileron
Aileron2_MinAngle=-15.0
Aileron2_MaxAngle=15.0
Aileron2_BaseAngle=0.0

NumberOfElevators=2
Elevator1_Model=Elevator_l
Elevator1_MinAngle=-20.0
Elevator1_MaxAngle=20.0
Elevator1_BaseAngle=0.0
Elevator2_Model=Elevator_r
Elevator2_MinAngle=-20.0
Elevator2_MaxAngle=20.0
Elevator2_BaseAngle=0.0

NumberOfRudders=1
Rudder1_Model=Rudder
Rudder1_MinAngle=-30.0
Rudder1_MaxAngle=30.0

[---------- Sensor Systems ----------]
############################################################
# Sensor Systems
############################################################
[SensorSystems]
NumberOfSensorSystems=6

#---------- Visual ----------
[SensorSystem1] #Cockpit
# Cockpit
Type=Visual
SystemName=Optics 
Mount=Dummy
MountPosition=0,0.01356125,0.2954407
ViewArcs=-110,110|-25,91
ModuleType=Sensor

[SensorSystem2] #Safire_380_HD FLIR Detector
Type=Visual
SystemName=Safire_380_HD
Mount=Dummy
MountPosition=0,0.01356125,0.2954407
ViewArcs=-110,110|-25,91
ModuleType=Sensor

[SensorSystem3] #Erieye_ER(AESA) Leftside
Type=Radar
SystemName=Erieye_ER
ViewArcs=-165,-15|-75,75
Mount=Dummy
ModuleType=Sensor
[SensorSystem4] #Erieye_ER(AESA) Rigntside
Type=Radar
SystemName=Erieye_ER
ViewArcs=15,165|-75,75
Mount=Dummy
ModuleType=Sensor

[SensorSystem5] #Seaspray 7500E
Type=Radar
SystemName=Seaspray_7500E
Mount=Dummy
ModuleType=Sensor

[SensorSystem6]#ELINT
Type=ESM
SystemName=AircraftELINT
Mount=Dummy
ModuleType=Sensor


[---------- Weapon Systems ----------]
[WeaponSystems]
NumberOfWeaponSystems=2
AvailableLoadouts=AEW

[WeaponSystem1] #Hardpoint
Type=Hardpoint
SystemName=Hardpoint
NumberOfStations=0

[WeaponSystem2] #Chaff
Type=Chaff
SystemName=US_AIR_CHAFF_DISP
#Sensors
#Animations
#Mount
Mount=Dummy
#MountPosition=0,-0.01,-0.016
#Containers
ContainerBase=Dummy
#Angles
#Loading
AssociatedMagazine=WeaponMagazineChaff
#Effects
NumberOfEffects=10
DelayBetweenLaunches=0.05
#Other
WorksStandalone=True
ModuleType=Weapon


[--------------------------- Loadouts ---------------------------]
[WeaponSystem1Default]
ReadyUpTime=35               // in minutes. Time that plane will spend refueling and rearming before takeoff.
CoolDownTime=90             // in minutes. Time that plane will spend in maintenance after landing.

[WeaponSystem1AEW]
ReadyUpTime=35               // in minutes. Time that plane will spend refueling and rearming before takeoff.
CoolDownTime=90             // in minutes. Time that plane will spend in maintenance after landing.

[---------- WeaponMagazines ----------]
############################################################
# Weapon Magazine Systems
############################################################
[WeaponMagazineChaff]
NumberOfAmmunitionTypes=1
Ammunition1_Count=20
Ammunition1=wp_aircraft_chaff
ModuleType=WeaponMagazine

[--------------------------- Mesh definitions ---------------------------]
[Models]
############################################################
# AssetBundle related
############################################################
AssetBundleMeshes=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMaterials=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMesh=wp_tu-16k
AssetBundleDamagedMesh=wp_tu-16k_d
AssetBundleMaterial=wp_tu-16k_mat
AssetBundleMeshHullCollider=wp_tu-16k_coll_hull
############################################################

############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=assets\models\vechicle\aircraft\global_eye\
ResourcesRoot=dts_global_eye.obj
ResourcesMesh=hull
ResourcesMaterial=dts_global_eye_mat.ini

NumberOfDamageModels=1
DamageModel1=hull_d
DamageModelMaterial1=dts_global_eye_mat.ini
DamageModelLostWingSide1=Left
############################################################
[Submodels]
SubModel1=Glass
SubModel2=Cockpit
SubModel3=Crew
SubModel4=Flapgear_r1
SubModel5=Flapgear_r2
SubModel6=Flapgear_r3
SubModel7=Flap_r1
SubModel8=Flap_r2
SubModel9=Flap_r3
SubModel10=Flapgear_l1
SubModel11=Flapgear_l2
SubModel12=Flapgear_l3
SubModel13=Flap_l1
SubModel14=Flap_l2
SubModel15=Flap_l3

NoseGear_1=Gear_f
NoseGear_2=Gearpad_f1l
NoseGear_3=Gearpad_f1r
NoseGear_4=Gearpad_f2

LeftGear_1=Gear_l
LeftGear_2=Gearpad_l1
LeftGear_3=Gearpad_l2
RightGear_1=Gear_r
RightGear_2=Gearpad_r1
RightGear_3=Gearpad_r2

Tail1=Elevator_l
Tail2=Elevator_r

[Cockpit]
Mesh=cockpit
Material=dts_global_eye_mat.ini
HideWithActiveDamageModel=False
[Glass]
Mesh=glass
ResourcesMaterialFolder=aircraft/materials/
Material=cockpit_glass
[Crew]
Mesh=crew
ResourcesMaterialFolder=characters/materials/
Material=usn_pilot_d_mat

######################## LEFT WING  ####################
[Flapgear_r1]
Mesh=flapgear_r1
Material=dts_global_eye_mat.ini
Position=0,-0.01661,-0.059561
[Flapgear_r2]
Mesh=flapgear_r2
Material=dts_global_eye_mat.ini
Position=0,-0.015064,-0.082283
[Flapgear_r3]
Mesh=flapgear_r3
Material=dts_global_eye_mat.ini
Position=0,-0.01425,-0.112951
#Rotation=0,0,0
[Flap_r1]
Mesh=flap_r1
Material=dts_global_eye_mat.ini
Position=0.047617,-0.015759,-0.058997
Rotation=0,4.48,1.37
[Flap_r2]
Mesh=flap_r2
Material=dts_global_eye_mat.ini
Position=0.097247,-0.014573,-0.07154
Rotation=-0.5,23.8276,0
[Flap_r3]
Mesh=flap_r3
Material=dts_global_eye_mat.ini
Position=0.177126,-0.01367,-0.115572
Rotation=0,30.2213,0

######################## LEFT WING  ####################
[Flapgear_l1]
Mesh=flapgear_l1
Material=dts_global_eye_mat.ini
Position=0,-0.01661,-0.059561
[Flapgear_l2]
Mesh=flapgear_l2
Material=dts_global_eye_mat.ini
Position=0,-0.015064,-0.082283
[Flapgear_l3]
Mesh=flapgear_l3
Material=dts_global_eye_mat.ini
Position=0,-0.01425,-0.112951
#Rotation=0,0,0
[Flap_l1]
Mesh=flap_l1
Material=dts_global_eye_mat.ini
Position=-0.047617,-0.015759,-0.058997
#Rotation=0,-4.28,-1.37
[Flap_l2]
Mesh=flap_l2
Material=dts_global_eye_mat.ini
Position=-0.097247,-0.014573,-0.07154
Rotation=-0.5,-23.8276,0
[Flap_l3]
Mesh=flap_l3
Material=dts_global_eye_mat.ini
Position=-0.177126,-0.01367,-0.115572
Rotation=0,-30.2213,0
######################### TAIL  #########################

[Elevator_l]
Mesh=elevator_l
Material=dts_global_eye_mat.ini
Position=-0.010735,0.081809,-0.251266
Rotation=2.60172,-33.0889,3.84988
[Elevator_r]
Mesh=elevator_r
Material=dts_global_eye_mat.ini
Position=0.010735,0.081809,-0.251266
Rotation=-2.60172,33.0889,-3.84988

######################## GEAR ########################
[Gear_f]
Mesh=gear_f
Material=dts_global_eye_mat.ini
Position=0,-0.00582,0.15204
Rotation=20,0,0
[Gearpad_f1l]
Mesh=gearpad_f1l
Material=dts_global_eye_mat.ini
Position=-0.004173,-0.004601,0.171274
Rotation=-11.6576,0,0
[Gearpad_f1r]
Mesh=gearpad_f1r
Material=dts_global_eye_mat.ini
Position=0.004173,-0.004601,0.171274
Rotation=-11.6576,0,0
[Gearpad_f2]
Mesh=gearpad_f2
Material=dts_global_eye_mat.ini
Position=0,-0.008123,0.150471
Rotation=-76.9675,0,0

[Gear_r]
Mesh=gear_r
Material=dts_global_eye_mat.ini
Position=0.027907,-0.013497,-0.050851
Rotation=0,0,45
[Gearpad_r1]
Mesh=gearpad_r1
Material=dts_global_eye_mat.ini
Position=0.034654,-0.01655,-0.054716
#Rotation=0,0,87.4
[Gearpad_r2]
Mesh=gearpad_r2
Material=dts_global_eye_mat.ini
Position=0.000161,-0.018905,-0.05687
#Rotation=0,0,80

[Gear_l]
Mesh=gear_l
Material=dts_global_eye_mat.ini
Position=-0.027907,-0.013497,-0.050851
Rotation=0,0,-45
[Gearpad_l1]
Mesh=gearpad_l1
Material=dts_global_eye_mat.ini
Position=-0.034654,-0.01645,-0.054716
#Rotation=0,0,-87.4
[Gearpad_l2]
Mesh=gearpad_l2
Material=dts_global_eye_mat.ini
Position=-0.000161,-0.018905,-0.05687
#Rotation=0,0,-80
[---------- Effects ----------]
[Particles]
ShotDownFireEffect=effects/aircraft_kill_effects/wp_taifun_kill
ShotDownFireEffectPosition=0,0,0
HitWaterEffect=effects/splashes/emitters/splash_missile
HitGroundEffect=effects/explosions/emitters/aircraft_hit_ground
HitAirEffectClass=LargeMissileExplosions
ExhaustSmoke=aircraft/particles/civ_h700_smokeemitter

[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=3
# Front
EngineAudioClip=audio/aircraft/SmallJet_v1
EngineAudioPosition=0,0,0
EngineAudioRollOff=Logarithmic
EngineAudioDistance=1,20
EngineAudioPitchRange=0.8,2.4
EngineAudioVolumeRange=0.25,1.0
EngineAudioAspectAngle=0
EngineAudioAspectArcHalfRange=180
EngineAudioAudibility=AboveAndBelow  // layer of sound audibility: Above, Below, AboveAndBelow
# Rear
ExhaustAudioClip=audio/aircraft/jet_rear_2
ExhaustAudioPosition=0,0,0
ExhaustAudioRollOff=Logarithmic
ExhaustAudioDistance=1,20
ExhaustAudioPitchRange=0.8,1.2
ExhaustAudioVolumeRange=0.5,1.4
ExhaustAudioAspectAngle=180
ExhaustAudioAspectArcHalfRange=180
ExhaustAudioAudibility=AboveAndBelow  // layer of sound audibility: Above, Below, AboveAndBelow
# Far
FarAudioClip=audio/aircraft/jet_far_4
FarAudioPosition=0,0,0
FarAudioRollOff=Logarithmic
FarAudioDistance=3,20
FarAudioPitch=0.75
FarAudioVolume=1.0
FarAudioFadeRange=0.05,0.25	      // nautical miles min/max
FarAudioAudibility=AboveAndBelow  // layer of sound audibility: Above, Below, AboveAndBelow
# Afterburner
AfterburnerAudioClip=audio/aircraft/afterburner_mig-29
AfterburnerAudioPosition=0,0,0
AfterburnerAudioRollOff=Logarithmic
AfterburnerAudioDistance=1,20
AfterburnerAudioPitch=0.75
AfterburnerAudioVolume=1.0
AfterburnerAudioAudibility=AboveAndBelow  // layer of sound audibility: Above, Below, AboveAndBelow
# Gears
#GearsAudioClip=audio/aircraft/gears
GearsAudioClip=audio/aircraft/LandingGearRetraction_v1
GearsAudioPosition=0,0,0
GearsAudioRollOff=Logarithmic
GearsAudioDistance=1,20
GearsAudioPitch=1.0
GearsAudioVolume=1.0
GearsAudioAudibility=AboveAndBelow  // layer of sound audibility: Above, Below, AboveAndBelow
# Flaps
#FlapsAudioClip=audio/aircraft/flaps
FlapsAudioClip=audio/aircraft/LandingGearRetraction_v1
FlapsAudioPosition=0,0,0
FlapsAudioRollOff=Logarithmic
FlapsAudioDistance=1,20
FlapsAudioPitch=1.0
FlapsAudioVolume=1.0
FlapsAudioAudibility=AboveAndBelow  // layer of sound audibility: Above, Below, AboveAndBelow

[---------- Colliders ----------]
[Colliders]
NumberOfColliders=2
Collider1=col_body
Collider2=col_wings
[col_body]
Collider=Box
Position=0,0.005,0.0114
Rotation=0,0,0
Scale=0.03,0.03,0.2
[col_wings]
Collider=Box
Position=0,-0.0056,-0.0094
Rotation=0,0,0
Scale=0.2,0.01,0.05
