[AmmunitionNames]
# ------------------ AAM ------------------
wp_aa-11=AA-11,Archer,AAM,The R-73 air-to-air missile is a Soviet/Russian type of close range air-to-air combat missile, and was one of the world's best performing combat infrared guided air-to-air missiles in the 1990s.

# ------------------ SAM ------------------

# ---------- Anti-radar Missiles ---------

# ---------- Anti-ship Missiles ----------

#-----------Land Strike only missiles---------

ru_kh-38mt=KH-38MT,IR,Land Attack,The Kh-38/Kh-38M (Russian: Х-38) is a family of standoff air-to-surface missiles meant to succeed the Kh-25 and Kh-29 missile families. The Kh-38 also serves as the basis for the Kh-36 unpowered and powered glide-bombs.MT is IR guide

wp_as-14a=AS-14L,Laser,Land Attack,The Kh-29 (Russian: Х-29; NATO: AS-14 'Kedge'; GRAU: 9M721) is a Soviet air-to-surface missile with a range of 10–30 km. It has a large warhead of 320 kg, has a choice of laser, infrared, active radar or TV guidance, and is typically carried by tactical aircraft such as the Su-24, Su-30, MiG-29K as well as the Su-25, giving these aircraft an expanded standoff capability.

wp_as-14=AS-14T,TV,Land Attack,The Kh-29 (Russian: Х-29; NATO: AS-14 'Kedge'; GRAU: 9M721) is a Soviet air-to-surface missile with a range of 10–30 km. It has a large warhead of 320 kg, has a choice of laser, infrared, active radar or TV guidance, and is typically carried by tactical aircraft such as the Su-24, Su-30, MiG-29K as well as the Su-25, giving these aircraft an expanded standoff capability.

# ---------- Anti-sub  Missilies ----------

# ------------------ RBU ------------------

# --------------- Torpedoes ---------------

# ------------------ Bombs -----------------

wp_kab-500kr=KAB-500Kr,TV,Land Attack,The KAB-500Kr is an electro-optical TV-guided fire and forget bomb developed by the Soviet Air Force in the 1980s.

# ---------------- Sonobuoys ---------------

# ------------------ FFAR -----------------

# ------------------ MLRS -----------------

# ------------------ Guns -----------------

# ------------------ CIWS -----------------

# ----------- Noisemakers/Chaff -----------

# ----------------- Decoys ----------------

# ----------------- Special ----------------

# Depth charge

# ----------------- Fueltanks ----------------


