
[SystemNames]
# ***********************************************************************************************
#                                          Main SYSTEMS
# ***********************************************************************************************

# ***********************************************************************************************
#                                          Sensor SYSTEMS
# ***********************************************************************************************
#======================================== Generic ========================================
#---------------------------------------- Visual ----------------------------------------

#---------------------------------------- Radar ----------------------------------------
#---------- Surface ships ----------
#---Air/Air&Surface---

#---Surface only---

#---Fire Control---
#SAM
#Guns

#---------- Submarines ----------
#---------------------------------------- Aircraft radar ----------------------------------------
#---------- Containers ----------

#---------------------------------------- Sonar ----------------------------------------
#Towed
#Dipping
#---------------------------------------- ESM ----------------------------------------

#---------- Targeting ----------

#---------- ELINT ----------

#---------------------------------------- ECM ----------------------------------------

#---------------------------------------- MAD ----------------------------------------
#---------------------------------------- Laser Designator ---------------------------

#======================================== China ========================================
#---------------------------------------- Visual ----------------------------------------
#光电探测设备
IR-XX_IRS=IR-XX| IR-XX is a 360-degree enhanced IR/EO surveillance system.
3rd_Gen_FLIR=FLIR|Airbone EO/IR FLIR system.
J-15_IRST=IRST|Airbone IRST
J-35_EOTS=EOTS|。Next-gen EO/IR system for 5th gen fighter, providing advanced passive situational awareness.
#---------------------------------------- Radar ----------------------------------------
#雷达

#---------- Surface ships ----------
#舰载探测设备
Navigation_radar=Navigation Radar|Navigation Radar
#---Air/Air&Surface---
#舰载对空雷达
LJQ-36X=H/LJQ-36X radar|The H/LJQ-36X radar is a new dual-band, ultra-low-altitude/surface search radar employing an Active Electronically Scanned Array (AESA) array. It operates in the X-band (for ultra-low-altitude search) and I-band (for surface search). Primarily designed to address the blind zones of the H/LJG-346A radar in detecting close-range, sea-skimming targets, it is integrated with the integrated mast system. This radar can also provide target parameters to close-in weapon systems (CIWS).
LJG-346A=H/LJG-346A|The H/LJG-346 "Sea Star" radar is the first large dual-band active electronically scanned array (AESA) radar system deployed by the Chinese Navy, operating in S-band (for search/tracking) and C-band (for guidance). The upgraded H/LJG-346A variant features enhanced detection capabilities and improved thermal management. The system comprises four radar arrays cooled by liquid cooling circuits. Each array consists of a central S-band panel flanked by elongated C-band panels above and below. A single S-band array contains over 5,000 transmit/receive (T/R) modules, with a maximum detection range exceeding 500 kilometers. Integrated with a new-generation digital automated command-and-control system, the radar can simultaneously track hundreds of aerial targets, automatically identify and assess threat levels, assign engagement priorities, and guide HHQ-9 series surface-to-air missiles to engage the highest-priority threats.
#---Surface only---
#舰载对地雷达
LJQ-3XX=H/LJQ-3XX radar|The H/LJQ-3XX is a new-generation L-band surface search radar capable of operating in both active and passive modes, providing target indication for ship-launched anti-ship missiles.
#---Fire Control---
#舰载火控雷达
#SAM
#舰载导弹引导雷达

#Guns
#舰载火炮控制雷达

#---------- Submarines ----------
#潜艇雷达

#---------------------------------------- Aircraft radar ----------------------------------------
#机载雷达
KLC-600=KLC-600|The KLC-600 (fictional designation) is a mechanically scanned active electronically scanned array (AESA) radar equipping the KJ-600 carrier-based airborne early warning (AEW) aircraft. It features long detection range and high detection accuracy.
KLC-600_low-band_mode=KLC-600 Low Band Mode|KLC-600 Low Band Mode，The radar will switch to operating in the UHF band, which is primarily used for detecting stealth targets, though its max range is limited to 250 kilometers.
KLJ-15=KLJ-15|The KLJ-15 (fictional designation) is a new-generation active electronically scanned array (AESA) airborne radar fitted on the J-15T carrier-based fighter aircraft.
KLC-4=KLC-4|The KLC-4 (fictional designation) is an active electronically scanned array (AESA) radar employed on the Z-18JA carrier-based early warning helicopter.Mounted under the helicopter’s rear fuselage, it provides surface ship formations with detection and fire control guidance capabilities against low-altitude and sea-skimming targets.
KLC-18=KLC-18|The KLC-18 (fictional designation) is a multi-purpose search radar fitted to the Z-18FA carrier-based anti-submarine warfare (ASW) helicopter.It features omnidirectional detection capability and can detect submarine periscopes and snorkels.
KLJ-35=KLJ-35|The KLJ-35 (fictional designation) is an active electronically scanned array (AESA) airborne radar equipped on the J-35 carrier-based stealth fighter.
#---------------------------------------- Land units radar ----------------------------------------
#陆基雷达
#---Air/Air&Surface---
#陆基对空雷达

#---Surface only---
#陆基对地雷达

#---Fire Control---
#陆基火控雷达

#---------------------------------------- Sonar ----------------------------------------
#声呐
SJK-562_TW=H/SJK-562|The Type H/SJK-562 Underwater Acoustic Countermeasure System consists of a torpedo warning sonar, acoustic decoy launchers, and an anti-torpedo weapon fire control system. It is capable of conducting acoustic jamming or hard-kill interception against incoming torpedoes.
#---------- Submarines ----------
#潜艇声呐

#Towed
#拖曳声呐

#Dipping
#吊放声呐
SKD-144=K/SKD-144|The K/SKD-144 is a large-aperture dipping sonar deployed on large carrier-based anti-submarine warfare (ASW) helicopters of the People's Liberation Army Navy (PLAN).

#Sonobuoys
#浮标声呐
SKF-16=H/SKF-16|The H/SKF-16 (fictional designation) is a new-generation passive directional aviation sonobuoy employed by the People's Liberation Army Navy (PLAN).
SKF-20=H/SKF-20|The H/SKF-20 (fictional designation) is an active directional aviation sonobuoy fielded by the People's Liberation Army Navy (PLAN).

#---------------------------------------- ESM ----------------------------------------
#电子支援，被动探测
RJL-XXX_ESM=H/RJL-XXX ESM|The H/RJZ-XXX shipborne electronic warfare system is the fourth-generation integrated modular electronic warfare equipment deployed by the People's Liberation Army Navy. It comprises electronic support measures (ESM), radar warning receivers (RWR), active/passive electronic countermeasures (ECM), and passive countermeasure launchers. The system enables fully automated jamming frequency and mode allocation based on threat target information from the combat command system, effectively disrupting sensors of incoming threats. Its ESM component possesses over-the-horizon passive detection capability.
RJZ-XXX_RWR=H/RJZ-XXX RWR|The H/RJZ-XXX shipborne electronic warfare system is the fourth-generation integrated modular electronic warfare equipment deployed by the People's Liberation Army Navy. It comprises electronic support measures (ESM), radar warning receivers (RWR), active/passive electronic countermeasures (ECM), and passive countermeasure launchers. The system enables fully automated jamming frequency and mode allocation based on threat target information from the combat command system, effectively disrupting sensors of incoming threats.
RKL-500_ESM=K/RKL-500 ESM|K/RKL-500 (fictional designation) is the ESM system standard to new generation of EW aircraft equipped by the PLAAF. It possesses capabilities for intercepting electromagnetic radiation signals and communications signals, alongside electronic intelligence analysis functions.
RKL-600=K/RKL-600 RWR|Radar warning receiver.
RKL-15=K/RKL-15 RWR|Radar warning receiver.
RKL-18_ESM=K/RKL-18 ESM|K/RKL-18 ESM (fictional designation) is the ESM/ELINT equipment of the Z-18JA AEW helicopter.
RKL-18=K/RKL-18 RWR|Radar warning receiver.
RKL-35_ESM=K/RKL-35 ESM|K/RKL-35 (fictional designation) is the passive situational awareness system euipped by J-35.
RKL-35=K/RKL-35 RWR|Radar warning receiver.

#---------- ELINT ----------

#---------------------------------------- ECM ----------------------------------------
#电子干扰
RJZ-XXX_CV=H/RJZ-XXX ECM|The H/RJZ-XXX shipborne electronic warfare system is the fourth-generation integrated modular electronic warfare equipment deployed by the People's Liberation Army Navy. It comprises electronic support measures (ESM), radar warning receivers (RWR), active/passive electronic countermeasures (ECM), and passive countermeasure launchers. The system enables fully automated jamming frequency and mode allocation based on threat target information from the combat command system, effectively disrupting sensors of incoming threats. Its ESM component possesses over-the-horizon passive detection capability.
RKZ-15=K/RKZ-15 ECM|The K/RKZ-15 (fictional designation) is an integrated airborne self-defense electronic jamming suite fitted on the J-15 fighter aircraft.
RKZ-930A=K/RKZ-930A ECM|The K/RKZ-930A is a multi-purpose electronic jamming pod in service with the People's Liberation Army Air Force (PLAAF).
RKZ-35=K/RKZ-35 ECM|The K/RKZ-35 (fictional designation) is an integrated airborne electronic warfare (EW) suite equipped on the J-35 fighter, featuring self-defense electronic jamming capability.
#---------------------------------------- MAD ----------------------------------------
#磁力异常探测
#---------------------------------------- Laser Designator ---------------------------
#探测吊舱
YINGS-IIIA=YINGS-IIIA Aiming Pod|YINGS-IIIA is a multi-purpose combined targeting pod fielded by the People's Liberation Army Air Force (PLAAF), integrating infrared, television and laser guidance capabilities. It features day-and-night observation and weapon guidance functionalities.
YINGS-IIIA_Designator=YINGS-IIIA Laser Designator|Laser Designator of the YINGS-IIIA aimming pod.
# ***********************************************************************************************
#                                          WEAPON SYSTEMS
# ***********************************************************************************************

#======================================== China ========================================
#---------------------------------------- Missile Launchers ----------------------------------------
#导弹发射器

#---------------------------------------- Torpedo Launchers ----------------------------------------
#鱼雷发射器
#********** Ships **********
#舰载鱼雷发射器

#********** Submarines **********
#潜艇鱼雷发射器

#---------------------------------------- RBU ----------------------------------------
#反潜深弹发射器


#---------------------------------------- MLRS ----------------------------------------
#火箭发射器
#CHY-1型反潜导弹（755型火箭助飞鱼雷）
#---------------------------------------- Land Guns ----------------------------------------
#陆基火炮

#---------------------------------------- Naval Guns ----------------------------------------
#舰载火炮


# ------------------ CIWS -----------------
#近防武器


Type_1130=H/PJ-11|The H/PJ-11 is deployed aboard the People's Liberation Army Navy's major surface combatants as a universal close-in weapon system (CIWS). Its core component is an 11-barrel 30mm rotary cannon firing Armor-Piercing Fin-Stabilized Discarding Sabot (APFSDS) ammunition at a rate of approximately 10,000 rounds per minute. The turret can traverse at speeds up to 90 degrees per second, and is equipped with independent infrared/electro-optical sensors and a laser rangefinder. Each turret is supported by a dedicated H/LJP-349 fire-control radar for targeting solutions. The system is capable of effectively engaging incoming supersonic sea-skimming missiles, as well as fixed-wing and rotary-wing aircraft, surface vessels and small boats, coastal targets, and floating mines.

#---------------------------------------- Aircraft Guns ----------------------------------------
#机载火炮

#---------------------------------------- Chaff ----------------------------------------
#箔条

#---------------------------------------- Noisemaker ----------------------------------------
#噪音诱饵