[ ------------------------ Visual/Infared ------------------------- ]

[OLS-27]
Kind=Visual
#Infrared
VIDRangeMultiplier=0.8           // Target VID range multiplied by this for identification check. 0 means it cannot identify
MaxRangeMultiplier=1.1           // Target VID range multiplied by this for detection check. Can not be less then VID multiplier
LookDownMultiplier=0.7             // Final VID/Detection range is multiplied by this in case when target observed on surface background
NightVisionLevel=0.9             // the portion of full daylight added to the visibility level where 1 is roughly a mid-day

[OLS-35]
Kind=Visual
#Infrared
VIDRangeMultiplier=1.1           // Target VID range multiplied by this for identification check. 0 means it cannot identify
MaxRangeMultiplier=1.3           // Target VID range multiplied by this for detection check. Can not be less then VID multiplier
LookDownMultiplier=0.9            // Final VID/Detection range is multiplied by this in case when target observed on surface background
NightVisionLevel=0.9             // the portion of full daylight added to the visibility level where 1 is roughly a mid-day

[------------------------- Radar ---------------------------]

[---Air/Air&Surface---]


[N001]
#Users: wp_su-27,plaaf_j-11,plaaf_j-11a
Kind=Radar
Type=DirectedSearch    // 雷达类型
HasDataLink=False      // 数据链
Role=Air             // Role can be "Surface", "Air", "AirAndSurface"
Mode=Illuminate        // Can be "Illuminate", "RadioCommand"
TargetChannels=10       // 如果适用，它可以同时跟踪的目标数量
WeaponChannels=2       // 火力通道，如果武器（导弹）数量合适，它可以同时制导
ViewArcs=-60,60|-55,60     // 左：水平左右视场，右：垂直视场
LookDownMultiplier=0.6     // 多径地形杂波系数，当目标投影到地形/海洋背景上时，应用于最大雷达距离的乘数，默认值为1.0
MinRange=0.4           // 最小距离
MaxRange=145           // 最大距离
MinAltitude=70          // 最低海拔高度，不适用于对地
MaxAltitude=30480      // 最大高度
RangeResolution=30.5   // 识别间距，定义了后方两个目标可以被识别为两个的最小范围；单位为米
BeamWidth=1.2          // 定义承载分辨率>=2*Dist*sin（波束宽度/2）的波束宽度（度）
Gain=49.0              // 传感器上的增益（dB）
Frequency=X-Band       // 波段
PeakPower=11.0         // 功率 in kW
RequiresAlignment=True// 对于飞机。允许飞机制导武器的同时不飞向目标

[1493]
#Users: plaaf_j-11b
Kind=Radar
Type=DirectedSearch    // Classes can be "DirectedSearch", "Search", "Targeting"
HasDataLink=True      // true means the sensor data will be used for the entire task force via data link, false local use only
Role=Air               // Role can be "Surface", "Air", "AirAndSurface"
Mode=Illuminate        // Can be "Illuminate", "RadioCommand"
TargetChannels=20       // if applicable number of targets it can track simultaneously
WeaponChannels=6       // if applicable number of weapons (missiles) it can guide simultaneously
ViewArcs=-60,60|-60,60               // Field of View of the radar
LookDownMultiplier=0.8     // 多径地形杂波系数，当目标投影到地形/海洋背景上时，应用于最大雷达距离的乘数，默认值为1.0
MinRange=0.4           // min range in km
MaxRange=180           // max range in km
MinAltitude=10         // min altitude in meters, relevant for air, unused for surface
MaxAltitude=30480      // max altitude in meters, relevant for air, unused for surface
RangeResolution=26.5  // defines the minimum range where two targets behind can be recognized as two; in meters
BeamWidth=1.1          // defines the beam width in degrees for BearingResolution >= 2*Dist*sin(BeamWidth/2)
Gain=55             // gain in dB on the sensor
Frequency=X-Band       // frequency band
PeakPower=13.0         // output peak power in kW

[J-11BG_AESA]
#Users: plaaf_j-11bg
Kind=Radar
Type=DirectedSearch    // Classes can be "DirectedSearch", "Search", "Targeting"
HasDataLink=True      // true means the sensor data will be used for the entire task force via data link, false local use only
Role=AirAndSurface               // Role can be "Surface", "Air", "AirAndSurface"
Mode=Illuminate        // Can be "Illuminate", "RadioCommand"
TargetChannels=80       // if applicable number of targets it can track simultaneously
WeaponChannels=15       // if applicable number of weapons (missiles) it can guide simultaneously
ViewArcs=-80,80|-80,80               // Field of View of the radar
LookDownMultiplier=0.8     // 多径地形杂波系数，当目标投影到地形/海洋背景上时，应用于最大雷达距离的乘数，默认值为1.0
MinRange=0.3           // min range in km
MaxRange=250           // max range in km
MinAltitude=10         // min altitude in meters, relevant for air, unused for surface
MaxAltitude=30480      // max altitude in meters, relevant for air, unused for surface
RangeResolution=18.5  // defines the minimum range where two targets behind can be recognized as two; in meters
BeamWidth=0.8          // defines the beam width in degrees for BearingResolution >= 2*Dist*sin(BeamWidth/2)
Gain=55             // gain in dB on the sensor
Frequency=X-Band       // frequency band
PeakPower=50.0      //AESA   // output peak power in kW

[---------------------------------------- ESM ----------------------------------------]


