[AmmunitionNames]
# ------------------ AAM ------------------
usn_aim-9m=AIM-9M,Sidewinder,AAM,The AIM-9M Sidewinder is an American infrared-guided air-to-air missile. The M model has increased anti-interference capability based on the L model, and uses a low-tail flame engine, making it difficult to be detected when used at close range.

usn_aim-9x=AIM-9X,Sidewinder,AAM,The AIM-9X Sidewinder is an American infrared-guided air-to-air missile. The X-model has been significantly upgraded, with strong anti-jam capabilities, a longer range, and an impressive backwards firing capability.

usaf_aim-120c7=AIM-120C-7,AMRAAM,AAM,AIM-120 is an active radar-guided air-to-air missile of the United States, used to replace the old Sparrow semi-active radar-guided air-to-air missile. It is relatively small and can be carried by most aircraft.

# ------------------ SAM ------------------

# ---------- Anti-radar Missiles ---------

# ---------- Anti-ship Missiles ----------
usaf_jsm=JSM,,Anti Ship,The Joint Strike Missile (JSM) is a multi-role, air-launched cruise missile under development by the Norwegian company Kongsberg Defence & Aerospace and American company Raytheon Missiles & Defense. 

#-----------Land Strike only missiles---------
usaf_gbu-31_v1=GBU-31(V)1,JDAM,Land Strike,The Joint Direct Attack Munition is an air-dropped bomb accessory developed jointly by Boeing for the U.S. Navy and Air Force. It is installed on traditional bombs dropped by aircraft to transform the originally uncontrolled traditional aerial bombs into controllable precision-guided weapons that can be used in severe weather conditions.

usaf_jsm_land=JSM,,Land Strike,The Joint Strike Missile (JSM) is a multi-role, air-launched cruise missile under development by the Norwegian company Kongsberg Defence & Aerospace and American company Raytheon Missiles & Defense. 

usaf_gbu-53=GBU-53,StormBreaker,Land Strike,The GBU-53 is an air-launched precision-guided glide bomb. The bomb was developed by Raytheon. In the initial bidding, the team of Boeing and Lockheed Martin won the contract for the bomb, but it was shelved for several years due to the Darlene Drewyn corruption case and was not re-bid until September 2005.

# ---------- Anti-sub  Missilies ----------


# ------------------ RBU ------------------
# --------------- Torpedoes ---------------
# ------------------ Bombs -----------------

# ---------------- Sonobuoys ---------------
# ------------------ FFAR -----------------
# ------------------ MLRS -----------------
# ------------------ Guns -----------------
# ------------------ CIWS -----------------
# ----------- Noisemakers/Chaff -----------
# ----------------- Decoys ----------------
# ----------------- Special ----------------
# ----------------- Fueltanks ----------------
