
[LanguageResources]


[SystemNames]
#---------------------------------------- Visual ----------------------------------------
3rd_Gen_FLIR=FLIR|FLIR 3rd generation airbone EO and IR sensor

#---------------------------------------- ESM ----------------------------------------
RKL-500_ESM=K/RKL-500 ESM|K/RKL-500 (fictional designation) is the ESM system standard to new generation of EW aircraft equipped by the PLAAF. It possesses capabilities for intercepting electromagnetic radiation signals and communications signals, alongside electronic intelligence analysis functions.
RKL-500B_OTH_ESM=K/RKL-500B ESM|K/RKL-500B (fictional designation) is a large-apeture ESM system used on PLAAF Y-9DZ ELINT aircraft. It is capable of detecting radiation signals over the horizon, and utlizes a large-apeture conformal antenna.
Morden_RWR=RWR|RWR Radar Warning Receiver 
#---------------------------------------- ECM ----------------------------------------
RKZ-500_ECM=K/RKZ-500 ECM|K/RKZ-500(fictitional designation) is a self-defence airborne electronic jamming system for the PLAAF's new generation of EW aircraft
RKZ-1000_ECM=K/RKZ-1000 ECM|K/RKZ-1000 (fictitional designation) is the offensive ECM system of the PLAAF Y-9LG jamming aircraft. It features high power and long efffective range. 
#---------------------------------------- MAD ----------------------------------------
KQT-8=KQT-8 MAD|KQT-8 MAD (fictitional designation) is the MAD device used by Y-8FQ and Y-9FQ
#---------------------------------------- Laser Designator ---------------------------

#======================================== Soviet Union ========================================
#---------------------------------------- Radar ----------------------------------------
Y-9DZ_SAR_L=SAR pod (left)|Synthetic-aperture radar (SAR) pod
Y-9DZ_SAR_R=SAR pod (right)|Synthetic-aperture radar (SAR) pod
#---------- Surface ships ----------]
#---Air/Air&Surface---
KLC-500=KLC-500 radar|The KLC-500 radar (fictional designation) is an active electronically scanned array digital radar (DAR) fitted to the PLA Air Force's KJ-500 airborne early warning aircraft. Employing a fixed three-panel array configuration, it achieves detection ranges comparable to the AN/APY-2 radar on the E-3C AWACS aircraft despite its smaller antenna weight and dimensions, whilst possessing robust multi-target tracking capabilities. The radar can detect and track stealth targets in head-on aspects at distances of approximately 100 kilometres. It can also update air situation awareness information within the region to other units via satellite data links.

KLC-8=KLC-8 radar|KLC-8 radar (fictional designation) is the surface search radar used by the Y-8FQ. Mounted under the nose, it is capable of searching in 360-degrees surface for targets, including submarine periscopes and submarine masts.
KLC-8A=KLC-8A radar|KLC-8A radar (fictional designation) is the surface search radar used by the Y-9FQ. Adopting an AESA array, it is capable of searching surface targets on the front hemisphere, including submarine periscopes and submarine masts.








