#!alias loadouts/usn_f-14a_loadouts.ini
FueltankTextures=lau-92/93,aircraft/usn_f-14a/iriaf/iriaf_f-14a_tx.png

[Station1]
NumberOfOptions=2
Option1=AIM-9E
Option2=AIM-9J

[Station2]
Option1=AIM-9E_LAU
Option2=AIM-9J_LAU
Option3=Empty
Option4=Empty
Option5=Empty
Option7=AIM-23
Option8=Empty
Option10=Empty //Zuni
Option11=AGM-23

[Station3]
Option1=Empty

[Station4]
Option2=Empty
Option3=Empty
Option5=Empty
Option6=Empty
Option7=MK-82_Front
Option9=Empty
Option10=M117_Front

[Station5]
Option2=Empty
Option3=Empty
Option5=Empty
Option6=Empty
Option7=MK-82_Rear
Option9=Empty
Option10=M117_Rear

[Station6]
Option2=Empty
Option3=Empty
Option5=Empty
Option6=Empty
Option7=MK-82_Rear
Option9=Empty
Option10=M117_Rear

[Station7]
Option2=Empty
Option3=Empty
Option5=Empty
Option6=Empty
Option7=MK-82_Front
Option9=Empty
Option10=M117_Front

[Station8]
Option1=Empty

[Station9]
Option1=AIM-9E_LAU
Option2=AIM-9J_LAU
Option3=Empty
Option4=Empty
Option5=Empty
Option7=AIM-23
Option8=Empty
Option10=Empty //Zuni
Option11=AGM-23

[Station10]
NumberOfOptions=2
Option1=AIM-9E
Option2=AIM-9J

[AIM-9E]
Ammunition=usaf_aim-9e
Icon=small_aam_ir_1

[AIM-9J]
Ammunition=usaf_aim-9j
Icon=small_aam_ir_2
IntroductionYear=1972

[AIM-9E_LAU]
WeaponSystemUsed=WeaponSystem1
Ammunition=usaf_aim-9e
Launchers=LAU7
LAU7OffsetPosition=0,0.0016,-0.005
Icon=small_aam_ir_1

[AIM-9J_LAU]
WeaponSystemUsed=WeaponSystem1
Ammunition=usaf_aim-9j
Launchers=LAU7
LAU7OffsetPosition=0,0.0016,-0.005
IntroductionYear=1972
Icon=small_aam_ir_2

[AIM-7E4]
Ammunition=usn_aim-7e2

[AIM-23]
WeaponSystemUsed=WeaponSystem1
Ammunition=iriaf_aim-23b
Launchers=LAU93
LAU93OffsetPosition=0,0.008,-0.005
LAU93PresetGroup=Hawk
Icon=medium_aam_radar_2

[AGM-23]
WeaponSystemUsed=WeaponSystem1
Ammunition=iriaf_agm-23
Launchers=LAU93
LAU93OffsetPosition=0,0.008,-0.005
LAU93PresetGroup=Hawk
Icon=medium_agm_unguided_2

[M117_Front]
WeaponSystemUsed=WeaponSystem2
Ammunition=usaf_m117
Launchers=ADU703
ADU703PresetGroup=MK-84
ADU703OffsetPosition=0,0.0027,0
Icon=medium_bomb_2
SubModelsToShow=Phoenix_Pallet_Front

[M117_Rear]
WeaponSystemUsed=WeaponSystem2
Ammunition=usaf_m117
Launchers=ADU703
ADU703PresetGroup=MK-84
ADU703OffsetPosition=0,0.0027,0
Icon=medium_bomb_2
SubModelsToShow=Phoenix_Pallet_Rear

##--- Meshes ---##
[Phoenix_Pallet_Front]
ResourcesMaterialFolder=aircraft/iriaf_f-14a/
Material=iriaf_f-14a_mat

[Phoenix_Pallet_Rear]
ResourcesMaterialFolder=aircraft/iriaf_f-14a/
Material=iriaf_f-14a_mat

[Enlarged_Glove_Stations]
ResourcesMaterialFolder=aircraft/iriaf_f-14a/
Material=iriaf_f-14a_mat