[General]
NumberOfStations=4

Station1=WeaponSystem1Station4
Station1DisplayName=HVAR

Station2=WeaponSystem2Station4
Station2DisplayName=Bay R

Station3=WeaponSystem2Station3
Station3DisplayName=Bay L

Station4=WeaponSystem1Station3
Station4DisplayName=HVAR

BaseReadyUpTime=30
CoolDownTime=120

SubModelsToHide=Pylons,Torpedo_pods,Torpedo_door_l_l,Torpedo_door_l_r,Torpedo_door_r_l,Torpedo_door_r_r

MaxTakeoffWeight=47400

[SonoBuoySystem]
WeaponSystem=WeaponSystem1
Station=Station7
Definitions=Sonobuoys,SonobuoysActive

NumberOfBuoys=2
Buoy1=usn_ssq-53
Buoy2=usn_ssq-62,20

#Bomb Bay
[Station2]
NumberOfOptions=2
Option1=MK-46
Option2=MK-54
; Option3=MK-82
; Option4=MK-83

SymmetryPartner=Station3
SubModelsToShow=Torpedo_pods,Torpedo_door_l_l,Torpedo_door_l_r,Torpedo_door_r_l,Torpedo_door_r_r

[Station3]
NumberOfOptions=2
Option1=MK-46
Option2=MK-54
; Option3=MK-82
; Option4=MK-83

IsMirrored=True
SymmetryPartner=Station2
SubModelsToShow=Torpedo_pods,Torpedo_door_l_l,Torpedo_door_l_r,Torpedo_door_r_l,Torpedo_door_r_r

#HVAR
[Station1]
NumberOfOptions=1
Option1=HVAR
SymmetryPartner=Station4
SubModelsToShow=Pylons

[Station4]
NumberOfOptions=1
Option1=HVAR
IsMirrored=True
SymmetryPartner=Station1
SubModelsToShow=Pylons

##--- All Stations ---##
[MK-46]
Ammunition=usn_mk46_air
Launchers=Dummy
DummyMirrorAllowed=True
DummyPositions=0,0,0|0.0055,0,0
MaximumAmount=2
Icon=medium_torpedo_2

; [MK-82]
; Ammunition=usn_mk-82
; Launchers=Dummy
; DummyMirrorAllowed=True
; DummyPositions=-0.0035,0,0.01|0.0035,0,0.01|-0.0035,0.005,0.01|0.0035,0.005,0.01
; MaximumAmount=4
; Icon=small_bomb_1

; [MK-83]
; Ammunition=usn_mk-83
; Launchers=Dummy
; DummyMirrorAllowed=True
; DummyPositions=-0.0035,0,0|0.0035,0,0
; MaximumAmount=2
; Icon=medium_bomb_1

[MK-54]
Ammunition=usn_mk54_dc
Launchers=Dummy
DummyMirrorAllowed=True
DummyPositions=0,0,0.01|0.0055,0,0.01|0.00275,0,-0.01
MaximumAmount=3
SortWith=MK-46
Icon=small_depth_bomb_1

[HVAR]
Ammunition=usn_zuni
Launchers=Dummy
DummyMirrorAllowed=True
DummyPositions=-0.0077,-0.0004,0|0,0,0|0.0076,0.0004,0
MaximumAmount=3
Icon=small_agm_unguided_1
