[General]
NumberOfStations=4
Station1=WeaponSystem2Station2
Station1Position=0.0581,-0.0055,0.009
Station1Rotation=2.6,0,0
Station1DisplayName=RO
Station2=WeaponSystem1Station2
Station2DisplayName=Bay R
Station3=WeaponSystem1Station1
Station3DisplayName=Bay L
Station4=WeaponSystem2Station1
Station4Position=-0.0581,-0.0055,0.009
Station4Rotation=2.6,0,0
Station4DisplayName=LO

DropOrder=AlternatingOutToIn

MaxAsymmetricMoment=17000
MaxTakeoffWeight=23830
MaxTakeoffWeightCarrier=20710

FueltankTextures=usn_tank_300_a-6,aircraft/usn_a-6e/va-34/usn_a-6e_tx
SubModelsToHide=Fuel_Tank,TER_Rack_Right,TER_Rack_Left
BaseReadyUpTime=15
CoolDownTime=30

[SonoBuoySystem]
WeaponSystem=WeaponSystem2
Station=Station3
Definitions=Sonobuoys,SonobuoysActive
# OR
; Positions=-0.0116,-0.0084,-0.0382|0.0116,-0.0084,-0.0382|-0.0116,-0.008,-0.0413|0.0116,-0.008,-0.0413|-0.0116,-0.0078,-0.0443|0.0116,-0.0078,-0.0443|-0.0116,-0.0073,-0.0472|0.0116,-0.0073,-0.0472|-0.0116,-0.0068,-0.05|0.0116,-0.0068,-0.05|-0.0088,-0.0085,-0.0382|0.0088,-0.0085,-0.0382|-0.0088,-0.0081,-0.0413|0.0088,-0.0081,-0.0413|-0.0088,-0.0078,-0.0443|0.0088,-0.0078,-0.0443|-0.0088,-0.0074,-0.0472|0.0088,-0.0074,-0.0472|-0.0088,-0.0069,-0.05|0.0088,-0.0069,-0.05|-0.006,-0.0086,-0.0382|0.006,-0.0086,-0.0382|-0.006,-0.0082,-0.0413|0.006,-0.0082,-0.0413|-0.006,-0.0079,-0.0443|0.006,-0.0079,-0.0443|-0.006,-0.0075,-0.0472|0.006,-0.0075,-0.0472|-0.006,-0.007,-0.05|0.006,-0.007,-0.05|-0.0016,-0.0108,-0.0178|0.0016,-0.0108,-0.0178|-0.0016,-0.0106,-0.0207|0.0016,-0.0106,-0.0207|-0.0016,-0.0104,-0.0235|0.0016,-0.0104,-0.0235|-0.0016,-0.0102,-0.0262|0.0016,-0.0102,-0.0262|-0.0016,-0.0099,-0.0291|0.0016,-0.0099,-0.0291|-0.0016,-0.0095,-0.0322|0.0016,-0.0095,-0.0322|-0.0016,-0.0092,-0.0352|0.0016,-0.0092,-0.0352|-0.0016,-0.0088,-0.0382|0.0016,-0.0088,-0.0382|-0.0016,-0.0084,-0.0413|0.0016,-0.0084,-0.0413|-0.0016,-0.008,-0.0443|0.0016,-0.008,-0.0443|-0.0016,-0.0076,-0.0472|0.0016,-0.0076,-0.0472|-0.0016,-0.0072,-0.05|0.0016,-0.0072,-0.05|-0.0016,-0.0067,-0.0528|0.0016,-0.0067,-0.0528|-0.0016,-0.0062,-0.0556|0.0016,-0.0062,-0.0556|-0.0016,-0.0057,-0.0584|0.0016,-0.0057,-0.0584|-0.0016,-0.0052,-0.0611|0.0016,-0.0052,-0.0611
; Rotations=90,0,0
NumberOfBuoys=4
Buoy1=usn_ssq-53
Buoy2=usn_ssq-62#,12
Buoy3=usn_ssq-77,12
Buoy4=usn_ssq-101,12
Buoy4_IntroductionYear=2001

[Station1]
NumberOfOptions=10
Option1=MK-84
Option2=MK-83
Option3=MK-82
Option4=MK-82SE
Option5=Rockeye
Option6=Zuni
Option7=Hydra19
Option8=Hydra7
Option9=FuelTank
Option10=D-704

IsMirrored=True
AsymmetricMomentFactor=-4
SymmetryPartner=Station4

[Station2]
NumberOfOptions=3
Option1=Torpedo
Option2=DepthBomb
Option3=Mk-82_Bay
; Option4=Mk-82SE_Bay

IsMirrored=True
AsymmetricMomentFactor=0
SymmetryPartner=Station3

[Station3]
NumberOfOptions=3
Option1=Torpedo
Option2=DepthBomb
Option3=Mk-82_Bay
; Option4=Mk-82SE_Bay

AsymmetricMomentFactor=0
SymmetryPartner=Station2

[Station4]
NumberOfOptions=10
Option1=MK-84
Option2=MK-83
Option3=MK-82
Option4=MK-82SE
Option5=Rockeye
Option6=Zuni
Option7=Hydra19
Option8=Hydra7
Option9=FuelTank
Option10=D-704

AsymmetricMomentFactor=4
SymmetryPartner=Station1

[Station1Blockers]
WeaponD-704BlockedWeaponsStation4=D-704

[Launchers]
TERFile=usn_ter

##--- All Stations ---##
[Torpedo]
Launchers=Dummy
DummyPositions=-0.0025,0,0|0.0025,0,0
Ammunition=usn_mk46_air
Icon=medium_torpedo_2
MaximumAmount=2

[DepthBomb]
Ammunition=usn_mk54_dc
Launchers=Dummy
DummyPositions=0,0,-0.01|0,0,0.01
Icon=small_depth_bomb_1
MaximumAmount=2
SortWith=Torpedo

[Mk-82_Bay]
Ammunition=usn_mk-82
Launchers=Dummy
DummyPositions=-0.0025,0,0|0.0025,0,0
Icon=small_bomb_1
MaximumAmount=2
SortWith=Torpedo

[Mk-82SE_Bay]
Ammunition=usn_mk-82_snakeye
Launchers=Dummy
DummyPositions=-0.0025,0,0|0.0025,0,0
Icon=small_bomb_retarded_1
MaximumAmount=2
SortWith=Torpedo

[MK-84]
Ammunition=usn_mk-84
Launchers=Dummy
DummyPositions=0,-0.0031,0.002
Icon=large_bomb_1

[MK-83]
Ammunition=usn_mk-83
Launchers=Dummy
DummyPositions=0,-0.0025,0.002
Icon=medium_bomb_1

[MK-82]
Ammunition=usn_mk-82
Launchers=Dummy,TER
DummyPositions=0,-0.00181,0.002
Icon=small_bomb_1
TERPresetGroup=PresetGroupLeft
MaximumAmount=3

[MK-82SE]
Ammunition=usn_mk-82_snakeye
Launchers=Dummy,TER
DummyPositions=0,-0.00181,0.002
Icon=small_bomb_retarded_1
TERPresetGroup=PresetGroupLeft
MaximumAmount=3

[Rockeye]
SortWith=MK-82
Ammunition=usn_rockeye
Launchers=Dummy,TER
DummyPositions=0,-0.00181,0.002
Icon=small_cluster_1
TERPresetGroup=PresetGroupLeft
MaximumAmount=3

[Zuni]
Ammunition=usn_lau-10a
Launchers=Dummy,TER
DummyPositions=0,-0.00181,0.004
DisplayContainerName=True
AlternativeLauncherPositions=Zuni
Icon=small_rocket_launcher_4x_1
TERPresetGroup=PresetGroupLeft
MaximumAmount=3

[Hydra19]
Ammunition=usn_lau-3a
Launchers=Dummy,TER
DummyPositions=0,-0.0025,0.004
DisplayContainerName=True
AlternativeLauncherPositions=Hydra19
Icon=medium_rocket_launcher_19x_1
TERPresetGroup=PresetGroupLeft
MaximumAmount=3

[Hydra7]
Ammunition=usn_lau-68
Launchers=Dummy,TER
DummyPositions=0,-0.00151,0.004
DisplayContainerName=True
AlternativeLauncherPositions=Hydra7
Icon=small_rocket_launcher_7x_1

TERPresetGroup=PresetGroupLeft
MaximumAmount=3

[FuelTank]
Ammunition=usn_tank_300_a-6
Launchers=Dummy
DummyPositions=0,-0.004,0.003
Icon=medium_fueltank_2fin_1

[D-704]
Ammunition=usn_d-704
Launchers=Dummy
DummyPositions=0,-0.004,0.003
Icon=pod_refueling_1
ReadyUpTime=10
SymmetryPartner=FuelTank