[General]
NumberOfStations=4
Station1=WeaponSystem2Station2
Station1DisplayName=2
Station2=WeaponSystem1Station0
Station2Position=0,-0.021,-0.0128
Station2DisplayName=Rear
Station3=WeaponSystem1Station0
Station3Position=0,-0.021,0.0172
Station3DisplayName=Forward
Station4=WeaponSystem2Station1
Station4DisplayName=1

DropOrder=1,4,2,3

SubModelsToHide=Pylons

BaseReadyUpTime=15
MaxReadyUpTime=30
CoolDownTime=30

[Station1]
NumberOfOptions=1
Option1=UB-16-57

SubModelsToShow=Pylons
AsymmetricMomentFactor=auto
SymmetryPartner=Station4

[Station2]
NumberOfOptions=4
Option1=FAB250
Option2=RBK-250
Option3=PLAB100
Option4=RGB-NM-1

[Station3]
NumberOfOptions=5
Option1=AT-1
Option2=FAB250
Option3=RBK-250
Option4=PLAB100
Option5=RGB-NM-1

[Station3Blockers]
WeaponAT-1BlockedStations=2

[Station4]
NumberOfOptions=1
Option1=UB-16-57

SubModelsToShow=Pylons
AsymmetricMomentFactor=auto
SymmetryPartner=Station4
##--- All Stations ---##
[RGB-NM-1]
Ammunition=wp_rgb-nm1
DummyPositions=0.002,0.001,-0.0105|0,0.001,-0.0105|-0.002,0.001,-0.0105|0.002,0.003,-0.0105|0,0.003,-0.0105|-0.002,0.003,-0.0105|0.002,0.005,-0.0105|0,0.005,-0.0105|-0.002,0.005,-0.0105|0.002,0.001,0.004|0,0.001,0.004|-0.002,0.001,0.004|0.002,0.003,0.004|0,0.003,0.004|-0.002,0.003,0.004|0.002,0.005,0.004|0,0.005,0.004|-0.002,0.005,0.004
Icon=small_bomb_retarded_3
MaximumAmount=18
SortWith=FAB250

[AT-1]
Ammunition=wp_at-1
DummyPositions=0,0.005,-0.014|0,0,-0.014
Icon=medium_torpedo_1
MaxReadyUpTime=15
MaximumAmount=2
SortWith=FAB250

[PLAB100]
Ammunition=wp_plab-100
DummyPositions=0,0.005,0|0,0,0
MaximumAmount=2
Icon=small_depth_bomb_1
SortWith=FAB250

[FAB250]
Ammunition=wp_fab-250
DummyPositions=0,0.005,0|0,0,0
MaximumAmount=2
Icon=small_bomb_2

[RBK-250]
Ammunition=wp_rbk-250
DummyPositions=0,0.005,0|0,0,0
MaximumAmount=2
Icon=small_cluster_1
SortWith=FAB250

[UB-16-57]
Ammunition=wp_ub-16-57KV
DisplayContainerName=True
Icon=small_rocket_launcher_7x_2