[General]
NumberOfStations=4
Station1=WeaponSystem1Station4
Station1DisplayName=4
Station1Position=0.0665,-0.001,-0.035
Station2=WeaponSystem1Station3
Station2DisplayName=3
Station2Position=0.0487,-0.001,-0.022
Station3=WeaponSystem1Station1
Station3DisplayName=2
Station4=WeaponSystem1Station2
Station4DisplayName=1

DropOrder=AlternatingOutToIn

MaxAsymmetricMoment=17000
MaxTakeoffWeight=35150

BaseReadyUpTime=15
CoolDownTime=120

[Station1]
NumberOfOptions=1
Option1=AA6A

AsymmetricMomentFactor=-4.57
SymmetryPartner=Station4

[Station2]
NumberOfOptions=2
Option1=AA6A
Option2=AA6B

AsymmetricMomentFactor=-3.35
SymmetryPartner=Station3

[Station3]
NumberOfOptions=2
Option1=AA6A
Option2=AA6B

AsymmetricMomentFactor=3.35
SymmetryPartner=Station2

[Station4]
NumberOfOptions=1
Option1=AA6A

AsymmetricMomentFactor=4.57
SymmetryPartner=Station1

[Launchers]

##--- All Stations ---##

[AA6A]
Ammunition=wp_aa-6a
Icon=medium_aam_radar_1

[AA6B]
Ammunition=wp_aa-6b
Icon=medium_aam_ir_1
SortWith=AA6A