[General]
NumberOfStations=5
Station1=WeaponSystem1Station4
Station1DisplayName=5
Station1Position=0.0665,-0.001,-0.035
Station2=WeaponSystem1Station3
Station2DisplayName=4
Station2Position=0.0487,-0.001,-0.022
Station3=WeaponSystem1Station9
Station3DisplayName=3
Station4=WeaponSystem1Station1
Station4DisplayName=2
Station5=WeaponSystem1Station2
Station5DisplayName=1

DropOrder=AlternatingOutToIn

MaxAsymmetricMoment=17000
MaxTakeoffWeight=39500

BaseReadyUpTime=15
CoolDownTime=120

SubModelsToHide=APU-60-2_left,APU-60-2_right#,APU-60-2_adapter_left,APU-60-2_adapter_right

[Station1]
NumberOfOptions=3
Option1=AA6A
Option2=AA6C
Option3=AA8Right

AsymmetricMomentFactor=-4.57
SymmetryPartner=Station5

[Station2]
NumberOfOptions=4
Option1=AA6A
Option2=AA6C
Option3=AA6B
Option4=AA6D

AsymmetricMomentFactor=-3.35
SymmetryPartner=Station4

[Station3]
NumberOfOptions=1
Option1=FuelTank

[Station4]
NumberOfOptions=4
Option1=AA6A
Option2=AA6C
Option3=AA6B
Option4=AA6D

AsymmetricMomentFactor=3.35
SymmetryPartner=Station2

[Station5]
NumberOfOptions=3
Option1=AA6A
Option2=AA6C
Option3=AA8Left

AsymmetricMomentFactor=4.57
SymmetryPartner=Station1

[Launchers]
APU60-2LeftFile=wp_apu-60-2_left
APU60-2RightFile=wp_apu-60-2_right
##--- All Stations ---##

[AA6A]
Ammunition=wp_aa-6a
Icon=medium_aam_radar_1

[AA6B]
Ammunition=wp_aa-6b
Icon=medium_aam_ir_1
SortWith=AA6A

[AA6C]
Ammunition=wp_aa-6c
Icon=medium_aam_radar_2

[AA6D]
Ammunition=wp_aa-6d
Icon=medium_aam_ir_2
SortWith=AA6A

[AA8Left]
Ammunition=wp_aa-8
Launchers=Dummy,APU60-2Left
DummyPositions=0,-0.0025,0.005
APU60-2LeftOffsetPosition=0,-0.0017,0.005
Icon=small_aam_ir_3
SubModelsToShow=APU-60-2_adapter_left
MaximumAmount=2
SymmetryPartner=AA8Right

[AA8Right]
Ammunition=wp_aa-8
Launchers=Dummy,APU60-2Right
DummyPositions=0,-0.0025,0.005
APU60-2RightOffsetPosition=0,-0.0017,0.005
Icon=small_aam_ir_3
SubModelsToShow=APU-60-2_adapter_right
MaximumAmount=2
SymmetryPartner=AA8Left

[FuelTank]
Ammunition=wp_tank_5280_mig-25
Icon=large_fueltank_0fin_1