[General]
NumberOfStations=2

Station1=WeaponSystem1Station2
Station1DisplayName=Bay R

Station2=WeaponSystem1Station1
Station2DisplayName=Bay L

BaseReadyUpTime=30
CoolDownTime=60

MaxTakeoffWeight=27100

[SonoBuoySystem]
WeaponSystem=WeaponSystem2
Station=Station1
Definitions=Sonobuoys,SonobuoysActive

NumberOfBuoys=3
Buoy1=wp_rgb-1
Buoy2=wp_rgb-3
Buoy3=wp_rgb-nm1,12

#Bomb Bay
[Station1]
NumberOfOptions=8
Option1=AT1
Option2=UMGT
; Option3=AT2
Option4=Fab250
Option5=Fab500
Option6=Rbk250
Option7=Rbk500
Option8=Plab100

IsMirrored=True
SymmetryPartner=Station2

[Station2]
NumberOfOptions=8
Option1=AT1
Option2=UMGT
; Option3=AT2
Option4=Fab250
Option5=Fab500
Option6=Rbk250
Option7=Rbk500
Option8=Plab100

SymmetryPartner=Station1

##--- All Stations ---##
[UMGT]
Ammunition=wp_umgt-1
Launchers=Dummy
DummyMirrorAllowed=True
DummyPositions=0.00285,-0.005,0.002|-0.0031,0,0.002
MaximumAmount=2
IntroductionYear=1981
Icon=medium_torpedo_2

[AT1]
Ammunition=wp_at-1
Launchers=Dummy
DummyMirrorAllowed=True
DummyPositions=0.00285,-0.005,0.004|-0.0031,0,0.004
MaximumAmount=2
Icon=medium_torpedo_1

; [AT2]
; Ammunition=wp_at-2
; Launchers=Dummy
; DummyMirrorAllowed=True
; DummyPositions=0.00285,-0.005,0.002|-0.0031,0,0.002
; MaximumAmount=2
; Icon=medium_torpedo_3

[Fab250]
Ammunition=wp_fab-250
Launchers=Dummy
DummyMirrorAllowed=True
DummyPositions=0.00285,-0.005,0.002|-0.0031,0,0.002
MaximumAmount=2
Icon=small_bomb_1

[Fab500]
Ammunition=wp_fab-500
Launchers=Dummy
DummyMirrorAllowed=True
DummyPositions=0.00285,-0.005,0.002|-0.0031,0,0.002
MaximumAmount=2
Icon=medium_bomb_1

[Rbk250]
Ammunition=wp_rbk-250
Launchers=Dummy
DummyMirrorAllowed=True
DummyPositions=0.00285,-0.005,0.002|-0.0031,0,0.002
MaximumAmount=2
Icon=small_cluster_1

[Rbk500]
Ammunition=wp_rbk-500
Launchers=Dummy
DummyMirrorAllowed=True
DummyPositions=0.00285,-0.005,0.002|-0.0031,0,0.002
MaximumAmount=2
Icon=medium_cluster_1

[Plab100]
Ammunition=wp_plab-100
Launchers=Dummy
DummyMirrorAllowed=True
DummyPositions=0.00285,-0.005,0.01|-0.0031,0,0.01|0.00285,-0.005,-0.01|-0.0031,0,-0.01
MaximumAmount=4
Icon=small_depth_bomb_1
