[General]
NumberOfStations=4
Station1=WeaponSystem1Station4
Station1DisplayName=4
Station1Position=0.0298,-0.0058,-0.01
Station2=WeaponSystem1Station3
Station2DisplayName=3
Station2Position=0.0209,-0.0022,-0.005
Station3=WeaponSystem1Station1
Station3DisplayName=2
Station3Position=-0.0209,-0.0022,-0.005
Station4=WeaponSystem1Station2
Station4DisplayName=1
Station4Position=-0.0298,-0.0058,-0.01

DropOrder=AlternatingOutToIn

MaxAsymmetricMoment=3500
MaxTakeoffWeight=12000

MaxVTOLWeight=10300
VTOLFuelUse=78 //in kg, proportional to takeoff weight | 78 is 30 seconds of thrust of all engines with a TSFC of 0.7 lb/lbf-hr

BaseReadyUpTime=15
CoolDownTime=120

[Station1]
NumberOfOptions=10
Option1=AA-8
Option2=AS-7
Option3=FAB-500
Option4=FAB-500_m54
Option5=FAB-250
Option6=OFAB-100
Option7=S-24
Option8=UB-16-57
Option9=B8M
Option10=UPK-23-250

IsMirrored=True
AsymmetricMomentFactor=auto
SymmetryPartner=Station4

[Station2]
NumberOfOptions=9
Option1=AA-8
Option4=FAB-250
Option5=OFAB-100
Option6=S-24
Option7=UB-16-57
Option9=UPK-23-250

IsMirrored=True
MERBlockedPositions=all
AsymmetricMomentFactor=auto
SymmetryPartner=Station3

[Station3]
NumberOfOptions=10
Option1=AA-8
Option4=FAB-250
Option5=OFAB-100
Option6=S-24
Option7=UB-16-57
Option9=UPK-23-250
Option10=Delta-NG

MERBlockedPositions=all
AsymmetricMomentFactor=auto
SymmetryPartner=Station2

[Station4]
NumberOfOptions=10
Option1=AA-8
Option2=AS-7
Option3=FAB-500
Option4=FAB-500_m54
Option5=FAB-250
Option6=OFAB-100
Option7=S-24
Option8=UB-16-57
Option9=B8M
Option10=UPK-23-250

AsymmetricMomentFactor=auto
SymmetryPartner=Station1

[Launchers]
MERFile=wp_mbd2-u2-67
##--- All Stations ---##
[AA-8]
Ammunition=wp_aa-8
Launchers=Dummy
DummyPositions=0,-0.0005,0
Icon=small_aam_ir_3

[AS-7]
Ammunition=wp_as-7
Launchers=Dummy
DummyPositions=0,-0.0015,0
Icon=small_agm_unguided_2
RequiredStore=Delta-NG

[OFAB-100]
Ammunition=wp_fab-100
Launchers=Dummy,MER
DummyPositions=0,-0.0015,0
MERPresetGroup=PresetGroupLeft
Icon=small_bomb_1
MaximumAmount=3

[FAB-250]
Ammunition=wp_fab-250
Launchers=Dummy
DummyPositions=0,-0.0015,0
Icon=small_bomb_2

[FAB-500]
Ammunition=wp_fab-500
Launchers=Dummy
DummyPositions=0,-0.0023,0
Icon=medium_bomb_2

[FAB-500_m54]
Ammunition=wp_fab-500_m54
Launchers=Dummy
DummyPositions=0,-0.0026,0
Icon=medium_bomb_1

[S-24]
Ammunition=wp_s-24
Launchers=Dummy
DummyPositions=0,-0.0014,0
Icon=small_agm_unguided_1

[UB-16-57]
Ammunition=wp_ub-16-57
Launchers=Dummy
DummyPositions=0,-0.0024,0
DisplayContainerName=True
Icon=small_rocket_launcher_7x_2

[B8M]
Ammunition=wp_b8m-1
Launchers=Dummy
DummyPositions=0,-0.0016,0
DisplayContainerName=True
Icon=medium_rocket_launcher_19x_1

[UPK-23-250]
Ammunition=wp_upk_23-250
Launchers=Dummy
DummyPositions=0,-0.002,0
Icon=medium_gunpod_twin_horizontal_1

[Delta-NG]
Ammunition=wp_pod_delta_fcr
Launchers=Dummy
DummyPositions=0,-0.0033,0
Icon=pod_datalink_1