
[LanguageResources]


[SystemNames]

#---------------------------------------- Visual ----------------------------------------
3rd_Gen_FLIR=FLIR|机载综合红外光电系统
#---------------------------------------- ESM ----------------------------------------
RKL-500_ESM=K/RKL-500 ESM|K/RKL-500（虚构代号）是人民空军新一代特种飞机装备的综合电子支援和侦查分析设备，具备电磁辐射信号，通讯信号拦截和电子情报分析功能
RKL-500B_OTH_ESM=K/RKL-500B ESM|K/RKL-500B（虚构代号）是人民空军运-9电子侦察机装备的大孔径综合电子支援设备，具备超地平线辐射探测和跟踪能力，采用大孔径共形天线。
Morden_RWR=RWR|雷达告警设备 
#---------------------------------------- ECM ----------------------------------------
RKZ-500_ECM=K/RKZ-500 ECM|K/RKZ-500（虚构代号）是人民空军新一代特种飞机装备的自卫型机载电子干扰设备。
RKZ-1000_ECM=K/RKZ-1000 ECM|K/RKZ-1000（虚构代号）是运-9雷达干扰机装备的进攻型机载电子干扰设备，具有功率大，作用距离远的特点，具备综合射频能力。
#---------------------------------------- MAD ----------------------------------------
KQT-8=KQT-8 磁异探测器|KQT-8磁异探测器（虚构代号）是运-8和运-9反潜巡逻机使用的磁异探测器
#---------------------------------------- Laser Designator ---------------------------

#======================================== Soviet Union ========================================
#---------------------------------------- Radar ----------------------------------------
Y-9DZ_SAR_L=合成孔径雷达（左）|合成孔径雷达吊舱（左侧）
Y-9DZ_SAR_R=合成孔径雷达（右）|合成孔径雷达吊舱（右侧）

#---------- Surface ships ----------]
#---Air/Air&Surface---
KLC-500=KLC-500 雷达|KLC-500雷达（虚构代号）是一种主动电子扫描数字阵列雷达（DAR），装备人民空军空警-500预警机。雷达采用固定三面阵布局，在雷达天线重量和尺寸都较小的情况下，探测作用距离和E-3C预警机的AN/APY-2雷达相当，具备强大的多目标跟踪处理能力。雷达能够在约100公里的距离上发现并跟踪迎头姿态的隐身目标，并能通过卫星数据链向其他单位更新区域内空情态势信息。

KLC-8=KLC-8 雷达|KLC-8雷达（虚构代号）是运-8FQ反潜巡逻机使用的水面搜索雷达，安装于机鼻下方，可360度探测水面目标，包括潜望镜和通气桅杆等。
KLC-8A=KLC-8A 雷达|KLC-8A雷达（虚构代号）是运-9FQ反潜巡逻机使用的水面搜索雷达，采用有源相控阵天线，可探测前半球水面目标，包括潜望镜和通气桅杆等。
# ----------- Noisemakers/Chaff -----------







