[AmmunitionNames]
# ------------------ AAM ------------------
# ------------------ SAM ------------------
usn_rim-116=RIM-116,RAM,SAM,The RIM-116 Rolling Airframe Missile is a short-range air defence missile that uses IR and laser guidance as part of the Mk49 short-range air defense missile system.

usn_rim-162=RIM-162,ESSM,SAM,The RIM-162 Evolved Sea Sparrow Missile (ESSM) is a development of the RIM-7 Sea Sparrow missile used to protect ships from attacking missiles and aircraft.[8] ESSM is designed to counter supersonic maneuvering anti-ship missiles. ESSM also has the ability to be "quad-packed" in the Mark 41 Vertical Launch System, allowing up to four ESSMs to be carried in a single cell.
# ---------- Anti-radar Missiles ---------

# ---------- Anti-ship Missiles ----------

#-----------Land Strike only missiles---------

# ---------- Anti-sub  Missilies ----------

# ------------------ RBU ------------------


# --------------- Torpedoes ---------------

# ------------------ Bombs -----------------


# ---------------- Sonobuoys ---------------


# ------------------ FFAR -----------------


# ------------------ MLRS -----------------

# ------------------ Guns -----------------

# ------------------ CIWS -----------------


# ----------- Noisemakers/Chaff -----------


# ----------------- Decoys ----------------

# ----------------- Special ----------------


# ----------------- Fueltanks ----------------
