[General]
SerialnumberReferences=Modex,Modex_Left_Flap,Modex_Right_Flap
EmblemReference=CarrierName
NationFlagReference=Flag1
NumberOfSquadrons=10

[Default]
ResourcesSerialnumberFolder=aircraft/usn_a-6e/va-35/modex/
SerialNumberPrefix=
SerialnumberTextures=505
ResourcesEmblemFolder=textures/Misc/
EmblemTexture=transparent
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=a6_roadrunners.png
Nation=US

[Squadron1] #
ResourcesSerialnumberFolder=aircraft/usn_a-6e/va-34/modex/
SerialNumberPrefix=
SerialnumberTextures=500,501,502,503,504,505,506,507,510,511
#ResourcesEmblemFolder=assets/ships/materials/
#EmblemTexture=usn_cvn_75_aircraft.png
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=a6_blue_blasters.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
Nation=US

[Squadron2] #
ResourcesSerialnumberFolder=aircraft/usn_a-6e/va-35/modex/
SerialNumberPrefix=
SerialnumberTextures=500,501,502,503,504,505,506,507,510,511,512
#ResourcesEmblemFolder=assets/ships/materials/
#EmblemTexture=usn_cvn_76_aircraft.png
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=a6_black_panthers.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
Nation=US

[Squadron3] #
ResourcesSerialnumberFolder=aircraft/usn_a-6e/va-52/modex/
SerialNumberPrefix=
SerialnumberTextures=500,501,502,503,504,505,506,507,510,511,512
#ResourcesEmblemFolder=assets/ships/materials/
#EmblemTexture=usn_cvn_77_aircraft.png
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=a6_roadrunners.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
Nation=US

[Squadron4] #
ResourcesSerialnumberFolder=aircraft/usn_a-6e/va-65/modex/
SerialNumberPrefix=
SerialnumberTextures=500,501,502,503,504,505,506,507,510,511,512
#ResourcesEmblemFolder=assets/ships/materials/
#EmblemTexture=usn_cvn_78_aircraft.png
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=a6_tigers.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
Nation=US

[Squadron5] #
ResourcesSerialnumberFolder=aircraft/usn_a-6e/va-95/modex/
SerialNumberPrefix=
SerialnumberTextures=500,501,502,503,504,505,506,507,510,511,512
#ResourcesEmblemFolder=assets/ships/materials/
#EmblemTexture=usn_cvn_79_aircraft.png
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=a6_black_falcons.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
Nation=US

[Squadron6] #
ResourcesSerialnumberFolder=aircraft/usn_a-6e/va-165/modex/
SerialNumberPrefix=
SerialnumberTextures=500,501,502,503,504,505,506,507,510,511
#ResourcesEmblemFolder=assets/ships/materials/
#EmblemTexture=usn_cvn_80_aircraft.png
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=a6_eagles.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
Nation=US

[Squadron7] #
ResourcesSerialnumberFolder=aircraft/usn_a-6e/va-176/modex/
SerialNumberPrefix=
SerialnumberTextures=500,501,502,503,504,505,506,507,510,511,512
#ResourcesEmblemFolder=assets/ships/materials/
#EmblemTexture=usn_cvn_81_aircraft.png
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=a6_silver_fox.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
Nation=US

[Squadron8] #
ResourcesSerialnumberFolder=aircraft/usn_a-6e/va-145/modex/
SerialNumberPrefix=
SerialnumberTextures=500,501,502,503,504,506,507,510,511,512
#ResourcesEmblemFolder=assets/ships/materials/
#EmblemTexture=usn_cvn_82_aircraft.png
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=a6_swordsmen.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
Nation=US

[Squadron9] #
ResourcesSerialnumberFolder=aircraft/usn_a-6e/va-85/modex/
SerialNumberPrefix=
SerialnumberTextures=500,501,502,503,504,505,506,510,511,512
#ResourcesEmblemFolder=assets/ships/materials/
#EmblemTexture=usn_cvn_83_aircraft.png
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=a6_nighthawks.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
Nation=US

[Squadron10] #
ResourcesSerialnumberFolder=aircraft/usn_a-6e/va-75/modex/
SerialNumberPrefix=
SerialnumberTextures=500,501,502,503,504,505,506,507,511,512
#ResourcesEmblemFolder=assets/ships/materials/
#EmblemTexture=usn_cvn_84_aircraft.png
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=a6_sunday_punchers.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
Nation=US
