[General]
SerialnumberReferences=Modex,Modex_Left_Flap,Modex_Right_Flap,Modex_Rudder
EmblemReference=CarrierName
NationFlagReference=Flag1
NumberOfSquadrons=16

[Default]
ResourcesSerialnumberFolder=aircraft/usn_ea-6b/vaq-138/modex/
SerialNumberPrefix=
SerialnumberTextures=604,605,606,607
#ResourcesEmblemFolder=aircraft/materials/emblem/
#EmblemTexture=cvn-68
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=ea6_zappers.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
FueltanksMaterialFolder=aircraft/usn_f-4j/
FueltanksMaterial=usn_f-4j_tanks

FueltanksMaterialFolder=aircraft/usn_a-6e/
FueltanksMaterial=usn_ea-6b_mat
Nation=US

[Squadron1] #United States
ResourcesSerialnumberFolder=aircraft/usn_ea-6b/vaq-138/modex/
SerialNumberPrefix=
SerialnumberTextures=604,605,606,607
#ResourcesEmblemFolder=assets/ships/materials/
#EmblemTexture=usn_cvn_75_aircraft.png
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=ea6_zappers.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
FueltanksMaterialFolder=aircraft/usn_a-6e/
FueltanksMaterial=usn_ea-6b_mat
Nation=US

[Squadron2] #Alan Shepard
ResourcesSerialnumberFolder=aircraft/usn_ea-6b/vaq-131/modex/
SerialNumberPrefix=
SerialnumberTextures=604,605,606,607
#ResourcesEmblemFolder=assets/ships/materials/
#EmblemTexture=usn_cvn_76_aircraft.png
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=ea6_lancers.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
FueltanksMaterialFolder=aircraft/usn_a-6e/
FueltanksMaterial=usn_ea-6b_mat
Nation=US

[Squadron3] #James Monroe
ResourcesSerialnumberFolder=aircraft/usn_ea-6b/vaq-132/modex/
SerialNumberPrefix=
SerialnumberTextures=604,605,606,607
#ResourcesEmblemFolder=assets/ships/materials/
#EmblemTexture=usn_cvn_77_aircraft.png
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=ea6_scorpions.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
FueltanksMaterialFolder=aircraft/usn_a-6e/
FueltanksMaterial=usn_ea-6b_mat
Nation=US

[Squadron4] #Independence
ResourcesSerialnumberFolder=aircraft/usn_ea-6b/vaq-133/modex/
SerialNumberPrefix=
SerialnumberTextures=604,605,606,607
#ResourcesEmblemFolder=assets/ships/materials/
#EmblemTexture=usn_cvn_78_aircraft.png
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=ea6_patriots.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
Nation=US

[Squadron5] #Franklin D. Roosevelt
ResourcesSerialnumberFolder=aircraft/usn_ea-6b/vaq-139/modex/
SerialNumberPrefix=
SerialnumberTextures=604,605,606,607
#ResourcesEmblemFolder=assets/ships/materials/
#EmblemTexture=usn_cvn_79_aircraft.png
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=ea6_cougars.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
FueltanksMaterialFolder=aircraft/usn_a-6e/
FueltanksMaterial=usn_ea-6b_mat
Nation=US

[Squadron6] #Enterprise
ResourcesSerialnumberFolder=aircraft/usn_ea-6b/vaq-135/modex/
SerialNumberPrefix=
SerialnumberTextures=604,605,606,607
#ResourcesEmblemFolder=assets/ships/materials/
#EmblemTexture=usn_cvn_80_aircraft.png
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=ea6_shadowhawks.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
FueltanksMaterialFolder=aircraft/usn_a-6e/
FueltanksMaterial=usn_ea-6b_mat
Nation=US

[Squadron7] #Benjamin Franklin
ResourcesSerialnumberFolder=aircraft/usn_ea-6b/vaq-136/modex/
SerialNumberPrefix=
SerialnumberTextures=604,605,606,607
#ResourcesEmblemFolder=assets/ships/materials/
#EmblemTexture=usn_cvn_81_aircraft.png
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=ea6_gauntlets.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
Nation=US

[Squadron8] #Ulysses S. Grant
ResourcesSerialnumberFolder=aircraft/usn_ea-6b/vaq-137/modex/
SerialNumberPrefix=
SerialnumberTextures=604,605,606,607
#ResourcesEmblemFolder=assets/ships/materials/
#EmblemTexture=usn_cvn_82_aircraft.png
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=ea6_rooks.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
FueltanksMaterialFolder=aircraft/usn_a-6e/
FueltanksMaterial=usn_ea-6b_mat
Nation=US

[Squadron9] #Horatio Gates
ResourcesSerialnumberFolder=aircraft/usn_ea-6b/vaq-130/modex/
SerialNumberPrefix=
SerialnumberTextures=610,611,612,613
#ResourcesEmblemFolder=assets/ships/materials/
#EmblemTexture=usn_cvn_83_aircraft.png
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=ea6_zappers.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
Nation=US

[Squadron10] #Helen Keller
ResourcesSerialnumberFolder=aircraft/usn_ea-6b/vaq-134/modex/
SerialNumberPrefix=
SerialnumberTextures=604,605,606,607
#ResourcesEmblemFolder=assets/ships/materials/
#EmblemTexture=usn_cvn_84_aircraft.png
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=ea6_zappers.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
FueltanksMaterialFolder=aircraft/usn_a-6e/
FueltanksMaterial=usn_ea-6b_mat
Nation=US

[Squadron11] #Shokaku
ResourcesSerialnumberFolder=aircraft/usn_ea-6b/vaq-138/modex/
SerialNumberPrefix=
SerialnumberTextures=604,605,606,607
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=jp_ea_6b.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
FueltanksMaterialFolder=aircraft/usn_a-6e/
FueltanksMaterial=usn_ea-6b_mat
Nation=Japan

[Squadron12] #Zuikaku
ResourcesSerialnumberFolder=aircraft/usn_ea-6b/vaq-138/modex/
SerialNumberPrefix=
SerialnumberTextures=604,605,606,607
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=jp_ea_6b_2.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
FueltanksMaterialFolder=aircraft/usn_a-6e/
FueltanksMaterial=usn_ea-6b_mat
Nation=Japan

[Squadron13] #Yamato
ResourcesSerialnumberFolder=aircraft/usn_ea-6b/vaq-138/modex/
SerialNumberPrefix=
SerialnumberTextures=604,605,606,607
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=jp_ea_6b_3.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
FueltanksMaterialFolder=aircraft/usn_a-6e/
FueltanksMaterial=usn_ea-6b_mat
Nation=Japan

[Squadron14] #Musashi
ResourcesSerialnumberFolder=aircraft/usn_ea-6b/vaq-138/modex/
SerialNumberPrefix=
SerialnumberTextures=604,605,606,607
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=jp_ea_6b_4.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
FueltanksMaterialFolder=aircraft/usn_a-6e/
FueltanksMaterial=usn_ea-6b_mat
Nation=Japan

[Squadron15] #Shinano
ResourcesSerialnumberFolder=aircraft/usn_ea-6b/vaq-138/modex/
SerialNumberPrefix=
SerialnumberTextures=604,605,606,607
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=jp_ea_6b_5.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
FueltanksMaterialFolder=aircraft/usn_a-6e/
FueltanksMaterial=usn_ea-6b_mat
Nation=Japan

[Squadron16] #Kii
ResourcesSerialnumberFolder=aircraft/usn_ea-6b/vaq-138/modex/
SerialNumberPrefix=
SerialnumberTextures=604,605,606,607
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=jp_ea_6b_6.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
FueltanksMaterialFolder=aircraft/usn_a-6e/
FueltanksMaterial=usn_ea-6b_mat
Nation=Japan