[General]
SerialnumberReferences=Modex,Right_Outer_Wing_Modex,Left_Rudder_Modex,Right_Rudder_Modex
EmblemReference=CarrierName
NationFlagReference=Flag1
NumberOfSquadrons=16

[Default]
ResourcesSerialnumberFolder=aircraft/usn_e-2c/vaw-112/modex/
SerialNumberPrefix=
SerialnumberTextures=600,601,602,603
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=e2_default_tx.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
# nations are referenced in the layout.ini file:
Nation=US

[Squadron1]  #Nimitz
ResourcesSerialnumberFolder=aircraft/usn_e-2c/vaw-112/modex/
SerialNumberPrefix=
SerialnumberTextures=600,601,602,603
ResourcesEmblemFolder=assets/ships/materials/
EmblemTexture=usn_cvn_68_aircraft.png
ResourcesLiveryFolder=aircraft/usn_e-2c/vaw-112/
LiveryTexture=usn_e-2c_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
# nations are referenced in the layout.ini file:
Nation=US

[Squadron2]  #Dwight D. Eisenhower
ResourcesSerialnumberFolder=aircraft/usn_e-2c/vaw-114/modex/
SerialNumberPrefix=
SerialnumberTextures=601,602,603,604
ResourcesEmblemFolder=assets/ships/materials/
EmblemTexture=usn_cvn_69_aircraft.png
ResourcesLiveryFolder=aircraft/usn_e-2c/vaw-114/
LiveryTexture=usn_e-2c_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
# nations are referenced in the layout.ini file:
Nation=US

[Squadron3]  #Carl Vinson
ResourcesSerialnumberFolder=aircraft/usn_e-2c/vaw-117/modex/
SerialNumberPrefix=
SerialnumberTextures=600,601,602,603
ResourcesEmblemFolder=assets/ships/materials/
EmblemTexture=usn_cvn_70_aircraft.png
ResourcesLiveryFolder=aircraft/usn_e-2c/vaw-117/
LiveryTexture=usn_e-2c_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
# nations are referenced in the layout.ini file:
Nation=US

[Squadron4]  #Theodore Roosevelt
ResourcesSerialnumberFolder=aircraft/usn_e-2c/vaw-121/modex/
SerialNumberPrefix=
SerialnumberTextures=011,012,013,014
ResourcesEmblemFolder=assets/ships/materials/
EmblemTexture=usn_cvn_71_aircraft.png
ResourcesLiveryFolder=aircraft/usn_e-2c/vaw-121/
LiveryTexture=usn_e-2c_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
# nations are referenced in the layout.ini file:
Nation=US

[Squadron5]  #Abraham Lincoln
ResourcesSerialnumberFolder=aircraft/usn_e-2c/vaw-123/modex/
SerialNumberPrefix=
SerialnumberTextures=600,601,602,603
ResourcesEmblemFolder=assets/ships/materials/
EmblemTexture=usn_cvn_72_aircraft.png
ResourcesLiveryFolder=aircraft/usn_e-2c/vaw-123/
LiveryTexture=usn_e-2c_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
# nations are referenced in the layout.ini file:
Nation=US

[Squadron6]  #George Washington
ResourcesSerialnumberFolder=aircraft/usn_e-2c/vaw-124/modex/
SerialNumberPrefix=
SerialnumberTextures=600,601,602,603
ResourcesEmblemFolder=assets/ships/materials/
EmblemTexture=usn_cvn_73_aircraft.png
ResourcesLiveryFolder=aircraft/usn_e-2c/vaw-124/
LiveryTexture=usn_e-2c_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
# nations are referenced in the layout.ini file:
Nation=US

[Squadron7]  #Independence
ResourcesSerialnumberFolder=aircraft/usn_e-2c/vaw-122/modex/
SerialNumberPrefix=
SerialnumberTextures=600,601,602,603
ResourcesEmblemFolder=assets/ships/materials/
EmblemTexture=usn_cvn_78_aircraft.png
ResourcesLiveryFolder=aircraft/usn_e-2c/vaw-122/
LiveryTexture=usn_e-2c_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
# nations are referenced in the layout.ini file:
Nation=US

[Squadron8]  #United States
ResourcesSerialnumberFolder=aircraft/usn_e-2c/vaw-116/modex/
SerialNumberPrefix=
SerialnumberTextures=600,601,602,603
ResourcesEmblemFolder=assets/ships/materials/
EmblemTexture=usn_cvn_75_aircraft.png
ResourcesLiveryFolder=aircraft/usn_e-2c/vaw-116/
LiveryTexture=usn_e-2c_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
# nations are referenced in the layout.ini file:
Nation=US

[Squadron9]  #Alan Shepard
ResourcesSerialnumberFolder=aircraft/usn_e-2c/vaw-125/modex/
SerialNumberPrefix=
SerialnumberTextures=600,601,602,603
ResourcesEmblemFolder=assets/ships/materials/
EmblemTexture=usn_cvn_76_aircraft.png
ResourcesLiveryFolder=aircraft/usn_e-2c/vaw-125/
LiveryTexture=usn_e-2c_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
# nations are referenced in the layout.ini file:
Nation=US

[Squadron10]  #James Monroe
ResourcesSerialnumberFolder=aircraft/usn_e-2c/vaw-126/modex/
SerialNumberPrefix=
SerialnumberTextures=010,011,012,013
ResourcesEmblemFolder=assets/ships/materials/
EmblemTexture=usn_cvn_77_aircraft.png
ResourcesLiveryFolder=aircraft/usn_e-2c/vaw-126/
LiveryTexture=usn_e-2c_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
# nations are referenced in the layout.ini file:
Nation=US

[Squadron11]  #
ResourcesSerialnumberFolder=aircraft/usn_e-2c/vaw-112/modex/
SerialNumberPrefix=
SerialnumberTextures=600,601,602,603
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=jp_e_2c.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
# nations are referenced in the layout.ini file:
Nation=Japan

[Squadron12]  #
ResourcesSerialnumberFolder=aircraft/usn_e-2c/vaw-112/modex/
SerialNumberPrefix=
SerialnumberTextures=600,601,602,603
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=jp_e_2c_2.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
# nations are referenced in the layout.ini file:
Nation=Japan

[Squadron13]  #
ResourcesSerialnumberFolder=aircraft/usn_e-2c/vaw-112/modex/
SerialNumberPrefix=
SerialnumberTextures=600,601,602,603
ResourcesEmblemFolder=assets/ships/materials/
EmblemTexture=
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=jp_e_2c_3.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
# nations are referenced in the layout.ini file:
Nation=Japan

[Squadron14]  #
ResourcesSerialnumberFolder=aircraft/usn_e-2c/vaw-114/modex/
SerialNumberPrefix=
SerialnumberTextures=601,602,603,604
ResourcesEmblemFolder=assets/ships/materials/
EmblemTexture=
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=jp_e_2c_3.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
# nations are referenced in the layout.ini file:
Nation=Japan

[Squadron15]  #
ResourcesSerialnumberFolder=aircraft/usn_e-2c/vaw-117/modex/
SerialNumberPrefix=
SerialnumberTextures=600,601,602,603
ResourcesEmblemFolder=assets/ships/materials/
EmblemTexture=
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=jp_e_2c_3.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
# nations are referenced in the layout.ini file:
Nation=Japan

[Squadron16]  #
ResourcesSerialnumberFolder=aircraft/usn_e-2c/vaw-121/modex/
SerialNumberPrefix=
SerialnumberTextures=011,012,013,014
ResourcesEmblemFolder=assets/ships/materials/
EmblemTexture=
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=jp_e_2c_3.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
# nations are referenced in the layout.ini file:
Nation=Japan
