[General]
SerialnumberReferences=Modex
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfSquadrons=26

[Default]
Nation=US

#USA
[Squadron1]  #VP-1
Nation=US

[Squadron2]  #VP-4
Nation=US

[Squadron3]  #VP-5
Nation=US

[Squadron4]  #VP-9
Nation=US

[Squadron5]  #VP-10
Nation=US

[Squadron6]  #VP-16
Nation=US

[Squadron7]  #VP-26
Nation=US

[Squadron8]  #VP-30
Nation=US

[Squadron9]  #VP-40
Nation=US

[Squadron10]  #VP-45
Nation=US

[Squadron11]  #VP-46
Nation=US

[Squadron12]  #VP-47
Nation=US

[Squadron13]  #VP-62
Nation=US

[Squadron14]  #VP-69
Nation=US

#UK
[Squadron15]  #No. 42
Nation=uk

[Squadron16]  #No. 54
Nation=uk

[Squadron17]  #No. 120
Nation=uk

[Squadron18]  #No. 201
Nation=uk

#Germany
[Squadron19]  #MFG 3
Nation=germany

#Norway
[Squadron20]  #333 Squadron
Nation=norway

#Australia
[Squadron21]  #No. 11
Nation=Australia

[Squadron22]  #No. 292
Nation=Australia

#New Zealand
[Squadron23]  #No. 5
Nation=newzealand

#South Korea
[Squadron24]  #Air Group 61
Nation=south_korea

#India
[Squadron25]  #INAS 312-A
Nation=india

[Squadron26]  #INAS 316
Nation=india
