[---------- General Data ----------]
[General]
UnitType=Aircraft
Size=VeryLarge

DefaultCameraDistance=1
MinCameraDistanceForeAft=0.7
MinCameraDistanceBroadside=0.7
CameraPivotHeight=0.0

#Taxi values
GroundedPitchAngle=-0.3    // this angle is the pitch (x) angle at ground with gears down
GroundPivot=0,-0.0461,0   // defines the relative location of the landing gear

[AI]
UnitScoreValue=10             // value for calculation of mission score
Role=AEW,Recon

[SensorData]
#Visual
VisualIdentificationRange=9.0  // at what range in nm this unit can be visually identified
IRSignature=Medium
# Radar related (RCS => radar cross section)
RCS=Medium

[Animations]
NumberOfAnimationReferences=1
AnimationFile_1=animations_wp_il_76

[---------- Flight Model ----------]
[Engine]
EngineIntakeArea=1.54             //Pi* r * r where r is engine radius, in meters

[FlightModel]
PitchGain=0.8                         // Vertical manuverability
VelocityGain=0.1136                   // Acceleration
HeadingGain=2                         // Horizontal manuverability
YawRateLimit=130                      // in degrees per second

BankGain=0.8                          // Roll change speed
MaxRollForHeading=45.0                // bank limit in normal flight
MaxRollRate=60.0                      // in degrees per second

ThrustGain=0.325                      // Thrust change speed
SpeedBrakeFractionGain=10            // Speed brakes deploy speed

SpeedDeltaPerAltitudeChange=0.0885

[Performance]
#Dimensions
WingSpan=50.5                           //meters
#Parameters
MaxG=4                                // Mostly for horizontal turns

MaxClimbRate=13.2                     //Meters per second
MaxClimbPitch=15                      // in degrees Default: 20
MaxCombatClimbPitch=20                // in degrees Defaults: 80 for MachLimit 1+ and 45 otherwise
MaxDescentPitch=-15                   // in degrees Default: -20
MaxCombatDescentPitch=-20             // in degrees Defaults: -60 for MachLimit 1+ and -30 otherwise
EmptyMass=61000                       // in kg
MaxFuel=80000                         // in kg

PerEngineMaxThrust=117680              //Newtons
EngineCount=4

Ceiling=50900.0                       // ceiling in feet
CruiseAltitude=36000                  //in feet
#"Engine" efficiency at 0ft, 37000 ft, 65000 ft. Always 1 for cruise altitude
AltitudeEfficiency=0.5,0.5,0.25       // Defines fuel consumption with altitude

#Governing of max speed
MaxSpeedAtSeaLevel=493                //in knots, Defines max speed at altitude curve
StallSpeed=105.0                      //in knots
MachLimit=0.98                        //for 37000ft, Defines max speed at altitude curve

#SpeedAndRange   MachNumbers or knots, Specified units or multiplier (except Cruise range)
RangeUnits=Miles                      // Can be: Km. Any other value = nmi. Defines measurment units of ranges of SpeedAndRange values

SpeedAndRange_Landing=0.21,0.4        // Landing
SpeedAndRange_Loiter=0.4,0.6          // Loiter
SpeedAndRange_Cruise=0.60,4700        // Cruise
SpeedAndRange_Max=0.68,0.8            // Attack/Fast/High/Max without AB


Altitudes=1000,3000,6000,10000,20000  // in feet

[---------- Main Systems ----------]
[FlightControls]
NumberOfAilerons=2
Aileron1_Model=Left_Aileron
Aileron1_MinAngle=-15.0
Aileron1_MaxAngle=15.0
Aileron1_BaseAngle=0.0
Aileron2_Model=Right_Aileron
Aileron2_MinAngle=-15.0
Aileron2_MaxAngle=15.0
Aileron2_BaseAngle=0.0

NumberOfElevators=2
Elevator1_Model=Left_Elevator
Elevator1_MinAngle=-20.0
Elevator1_MaxAngle=20.0
Elevator1_BaseAngle=0.0
Elevator2_Model=Right_Elevator
Elevator2_MinAngle=-20.0
Elevator2_MaxAngle=20.0
Elevator2_BaseAngle=0.0

NumberOfRudders=1
Rudder1_Model=Rudder
Rudder1_MinAngle=-30.0
Rudder1_MaxAngle=30.0

[---------- Sensor Systems ----------]
############################################################
# Sensor Systems
############################################################
[SensorSystems]
NumberOfSensorSystems=5

#---------- Visual ----------
[SensorSystem1] #Cockpit
# Cockpit
Type=Visual
SystemName=Eyes 
Mount=Dummy
MountPosition=0,0.0121,0.2002
ViewArcs=-150,150|-25,91
ModuleType=Sensor

[SensorSystem2] #Shmel-M
Type=Radar
SystemName=Shmel-M
Mount=Radar
ModuleType=Sensor

#---------- ESM ----------
[SensorSystem3] #ESM
Type=ESM
SystemName=AircraftELINT
Mount=Dummy
ModuleType=Sensor

[SensorSystem4] #RWR
Type=ESM
SystemName=SPO-15M
Mount=Dummy
ModuleType=Sensor

[SensorSystem5] #ECM
Type=ECM
SystemName=AircraftDECM_Late
Mount=Dummy
ModuleType=Sensor

[---------- Weapon Systems ----------]
[WeaponSystems]
NumberOfWeaponSystems=1

[WeaponSystem1] #Chaff
Type=Chaff
SystemName=US_AIR_CHAFF_DISP
#Sensors
#Animations
#Mount
Mount=Dummy
#MountPosition=0,-0.01,-0.016
#Containers
ContainerBase=Dummy
#Angles
#Loading
AssociatedMagazine=WeaponMagazineChaff
#Effects
NumberOfEffects=4
DelayBetweenLaunches=0.1
#Other
WorksStandalone=True
ModuleType=Weapon

[---------- WeaponMagazines ----------]
############################################################
# Weapon Magazine Systems
############################################################
[WeaponMagazineChaff]
NumberOfAmmunitionTypes=1
Ammunition1_Count=25
Ammunition1=wp_aircraft_chaff
ModuleType=WeaponMagazine

##Could carry 13 standard pallets or 205 troops or 168 paratroopers. 

[--------------------------- Mesh definitions ---------------------------]
[Models]
#LODLevels=2
#LOD1Distance=0.5  // nautical miles
#LOD2Distance=1.0  // nautical miles

############################################################
# AssetBundle related
############################################################
AssetBundleMeshes=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMaterials=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMesh=usaf_c-141b
AssetBundleDamagedMesh=usaf_c-141b_d
AssetBundleMaterial=usaf_c-141b_mat
AssetBundleMeshHullCollider=usaf_c-141b_coll_hull
############################################################

############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=aircraft/usaf_c-141b/
ResourcesRoot=usaf_c-141b
ResourcesMesh=Dummy
ResourcesMaterial=usaf_c-141b_mat
############################################################
[Submodels]
SubModel1=Canopyglass
SubModel2=Cockpit
SubModel3=Crew
SubModel4=WheelWells
SubModel5=Nose_Gear
SubModel6=Main_Gear
SubModel7=Main_Gear_Boogie
SubModel8=Main_Gear_Link_1
SubModel9=Main_Gear_Link_2
SubModel10=Main_Gear_Actuator
SubModel11=Nose_Gear_Door_L
SubModel12=Nose_Gear_Door_R
SubModel13=Nose_Gear_Door_A
SubModel14=Left_Gear_Door_1
SubModel15=Left_Gear_Door_2
SubModel16=Left_Gear_Door_3
SubModel17=Right_Gear_Door_1
SubModel18=Right_Gear_Door_2
SubModel19=Right_Gear_Door_3
SubModel20=Left_Inner_Flap
SubModel21=Left_Outer_Flap
SubModel22=Left_Aileron
SubModel23=Right_Inner_Flap
SubModel24=Right_Outer_Flap
SubModel25=Right_Aileron
SubModel26=Left_Elevator
SubModel27=Right_Elevator
SubModel28=Rudder

Fuselage1=Fuselage_1
Fuselage2=Fuselage_2
Fuselage3=Fuselage_3
Fuselage4=Fuselage_4
Fuselage5=Fuselage_5
Fuselage6=Fuselage_6
Fuselage7=Fuselage_7

Radar_Struts1=Strut_1
Radar_Struts2=Strut_2
Rotodome=Radar

#Probe=Probe1
#Probe2=Probe2

[Probe1]
ResourcesMeshFolder=ships/usn_ddg_kidd/
RootMesh=usn_ddg_kidd
Mesh=usn_ddg_kidd_mk45_barrel
ResourcesMaterialFolder=ships/materials/
Material=usn_parts
Position=0,0.015,0.188
Scale=1.1,1.1,0.5

[Probe2]
ResourcesMeshFolder=ships/usn_ddg_kidd/
RootMesh=usn_ddg_kidd
Mesh=usn_ddg_kidd_mk45_barrel
ResourcesMaterialFolder=ships/materials/
Material=usn_parts
Position=0,0,0.05
Scale=0.5,0.5,1.5
Parent=Probe1

[Radar]
ResourcesMeshFolder=aircraft/wp_p-42_rldn/
RootMesh=wp_p-42_rldn
Mesh=wp_p-42_rldn_radar
Material=wp_a_50_radar_mat.ini
Position=0,0.096,-0.0959
Rotation=0,0,0
Scale=1.5,1.5,1.5
HideWithActiveDamageModel=False

[Strut_1]
ResourcesMeshFolder=ships/usn_dd_spruance/
RootMesh=usn_dd_spruance
Mesh=usn_dd_spruance_asroc_box_1
Material=wp_il_76_mat.ini
Position=0.02,0.02,-0.101
Rotation=0,0,8
Scale=0.1,2.5,0.36

[Strut_2]
ResourcesMeshFolder=ships/usn_dd_spruance/
RootMesh=usn_dd_spruance
Mesh=usn_dd_spruance_asroc_box_1
Material=wp_il_76_mat.ini
Position=-0.02,0.02,-0.101
Rotation=0,0,-8
Scale=-0.1,2.5,0.36

[Fuselage_1]
ResourcesMeshFolder=aircraft/usaf_c-141b/
RootMesh=usaf_c-141b
Mesh=usaf_c-141b
ResourcesMaterialFolder=aircraft/usaf_c-141b/
Material=wp_il_76_fuselage_mat.ini
Position=0,0.005,-0.028
Scale=1.2,1.2,0.91

[Fuselage_2] #Engines
ResourcesMeshFolder=aircraft/usaf_c-141b/
RootMesh=usaf_c-141b
Mesh=usaf_c-141b
ResourcesMaterialFolder=aircraft/usaf_c-141b/
Material=wp_il_76_engines_mat.ini
Position=0,0.0096,-0.015
Scale=0.99,0.96,1.3

[Fuselage_3] #Wings
ResourcesMeshFolder=aircraft/usaf_c-141b/
RootMesh=usaf_c-141b
Mesh=usaf_c-141b
ResourcesMaterialFolder=aircraft/usaf_c-141b/
Material=wp_il_76_wings_mat.ini
Position=0,0.0098,-0.025
Scale=0.99,1.05,1.2

[Fuselage_4] #Hump
ResourcesMeshFolder=aircraft/usaf_c-141b/
RootMesh=usaf_c-141b
Mesh=usaf_c-141b
ResourcesMaterialFolder=aircraft/usaf_c-141b/
Material=wp_il_76_hump_mat.ini
Position=0,0.0098,-0.025
Scale=0.99,1.05,1.2

[Fuselage_5] #Gearbay
ResourcesMeshFolder=aircraft/usaf_c-141b/
RootMesh=usaf_c-141b
Mesh=usaf_c-141b
ResourcesMaterialFolder=aircraft/usaf_c-141b/
Material=wp_il_76_gearbay_mat.ini
Position=0,0.0055,0.005
Scale=1.2,1.22,1.5

[Fuselage_6] #Tail
ResourcesMeshFolder=aircraft/usaf_c-141b/
RootMesh=usaf_c-141b
Mesh=usaf_c-141b
ResourcesMaterialFolder=aircraft/usaf_c-141b/
Material=wp_il_76_tail_mat.ini
Position=0,-0.0055,0.09
Scale=1.2,1.2,1.2

[Fuselage_7] #Nose
ResourcesMeshFolder=aircraft/usaf_c-141b/
RootMesh=usaf_c-141b
Mesh=usaf_c-141b
ResourcesMaterialFolder=aircraft/usaf_c-141b/
Material=wp_il_76_nose_mat.ini
Position=0,0.005,-0.288
Scale=1.4,1.2,1.8

[Canopyglass]
Mesh=usaf_c-141b_glass
ResourcesMaterialFolder=aircraft/materials/
Material=cockpit_glass
Position=0,0.005,-0.028
Scale=1.2,1.2,0.91

[Cockpit]
Mesh=usaf_c-141b_cockpit
Material=usaf_c-141b_mat
Position=0,0.005,-0.028
Scale=1.2,1.2,0.91

[Crew]
Mesh=usaf_c-141b_crew
ResourcesMaterialFolder=characters/materials/
Material=usn_pilot_d_mat
Position=0,0.005,-0.028
Scale=1.2,1.2,0.91

[WheelWells]
Mesh=usaf_c-141b_wheel_wells
Material=usaf_c-141b_mat
Position=0,0.005,-0.028
Scale=1.2,1.2,0.91

############################################################
#---------- Left Wing ----------
############################################################
[Left_Inner_Flap]
Mesh=usaf_c-141b_left_inner_flap
Material=wp_il_76_mat.ini
Position=-0.085,0.0215,-0.0834
Rotation=0,-100,0
Scale=1.2,1.05,1

[Left_Outer_Flap]
Mesh=usaf_c-141b_left_outer_flap
Material=wp_il_76_mat.ini
Position=-0.1995,0.0193,-0.1115
Rotation=0,-108,0
Scale=1.2,1.05,1

[Left_Aileron]
Mesh=usaf_c-141b_left_aileron
Material=wp_il_76_mat.ini
Parent=Left_Outer_Wing
Position=-0.2967,0.026,-0.140
Rotation=0,-108,3
Scale=1.2,1.05,1

############################################################
#---------- Right Wing ----------
############################################################
[Right_Inner_Flap]
Mesh=usaf_c-141b_right_inner_flap
Material=wp_il_76_mat.ini
Position=0.085,0.0215,-0.0834
Rotation=0,-80,0
Scale=1.2,1.05,1

[Right_Outer_Flap]
Mesh=usaf_c-141b_right_outer_flap
Material=wp_il_76_mat.ini
Position=0.2,0.0193,-0.1115
Rotation=0,-70,0
Scale=1.2,1.05,1

[Right_Aileron]
Mesh=usaf_c-141b_right_aileron
Material=wp_il_76_mat.ini
Parent=Right_Outer_Wing
Position=0.2965,0.026,-0.140
Rotation=0,-70,-3
Scale=1.2,1.05,1

############################################################
#---------- Tail ----------
############################################################

[Rudder]
Mesh=usaf_c-141b_rudder
Material=wp_il_76_mat.ini
Position=0,0.097,-0.367
Rotation=64,0,0
Scale=1.2,1.2,1.1

[Left_Elevator]
Mesh=usaf_c-141b_left_elevator
Material=wp_il_76_mat.ini
Position=0,0.157,-0.387
Rotation=0,-16,0
Scale=1.2,1.2,1.2

[Right_Elevator]
Mesh=usaf_c-141b_right_elevator
Material=wp_il_76_mat.ini
Position=0,0.157,-0.387
Rotation=0,16,0
Scale=1.2,1.2,1.2

############################################################
# Landing Gear
############################################################

[Nose_Gear]
Mesh=usaf_c-141b_nose_gear
Material=usaf_c-141b_mat
Position=0,-0.0184,0.259
Rotation=0,-90,0
Parent=WheelWells
Scale=1,1,1

[Main_Gear]
Mesh=usaf_c-141b_main_gear
Material=usaf_c-141b_mat
Position=0,-0.0196,-0.036
Parent=WheelWells
Scale=1,1,1

[Main_Gear_Boogie]
Mesh=usaf_c-141b_main_gear_boogie
Material=usaf_c-141b_mat
Position=0,-0.0152,0.0032
Parent=Main_Gear
Scale=1,1,1

[Main_Gear_Link_1]
Mesh=usaf_c-141b_main_gear_link1
Material=usaf_c-141b_mat
Position=0,0,0.0072
Parent=Main_Gear
Scale=1,1,1

[Main_Gear_Link_2]
Mesh=usaf_c-141b_main_gear_link2
Material=usaf_c-141b_mat
Position=0,-0.0047,0.0173
Parent=Main_Gear_Link_1
Scale=1,1,1

[Main_Gear_Actuator]
Mesh=usaf_c-141b_main_gear_actuator
Material=usaf_c-141b_mat
Position=0,0.0121,-0.0002
Parent=Main_Gear
Scale=1,1,1

############################################################
# Landing Gear Doors
############################################################

[Nose_Gear_Door_L]
Mesh=usaf_c-141b_nose_gear_door_l
Material=wp_il_76_mat.ini
Position=-0.0093,-0.0248,0.222
Rotation=-22,0,0
Scale=1.2,1.2,1

[Nose_Gear_Door_R]
Mesh=usaf_c-141b_nose_gear_door_r
Material=wp_il_76_mat.ini
Position=0.0093,-0.0248,0.222
Rotation=-22,0,0
Scale=1.2,1.2,1

[Nose_Gear_Door_A]
Mesh=usaf_c-141b_nose_gear_door_a
Material=wp_il_76_mat.ini
Position=-0,-0.0299,0.198
Rotation=-15,0,0
Scale=1.2,1.2,1

[Left_Gear_Door_1]
Mesh=usaf_c-141b_main_gear_door_l1
Material=wp_il_76_mat.ini
Position=-0.0588,-0.0205,-0.0326
Scale=1.2,1.22,1.5

[Left_Gear_Door_2]
Mesh=usaf_c-141b_main_gear_door_l2
Material=wp_il_76_mat.ini
Position=-0.0306,-0.0305,-0.0323
Scale=1.2,1.22,1.5

[Left_Gear_Door_3]
Mesh=usaf_c-141b_main_gear_door_l3
Material=wp_il_76_mat.ini
Position=-0.042,-0.0054,-0.052
Scale=1.2,1.22,1.5

[Right_Gear_Door_1]
Mesh=usaf_c-141b_main_gear_door_r1
Material=wp_il_76_mat.ini
Position=0.0588,-0.0205,-0.0326
Scale=1.2,1.22,1.5

[Right_Gear_Door_2]
Mesh=usaf_c-141b_main_gear_door_r2
Material=wp_il_76_mat.ini
Position=0.0306,-0.0305,-0.0323
Scale=1.2,1.22,1.5

[Right_Gear_Door_3]
Mesh=usaf_c-141b_main_gear_door_r3
Material=wp_il_76_mat.ini
Position=0.042,-0.0054,-0.052
Scale=1.2,1.22,1.5

[---------- Effects ----------]
[Particles]
ShotDownFireEffect=effects/aircraft_kill_effects/usaf_c-141b_kill
ShotDownFireEffectPosition=0,0,0
HitWaterEffect=effects/splashes/emitters/splash_missile
HitGroundEffect=effects/explosions/emitters/aircraft_hit_ground
HitAirEffectClass=LargeMissileExplosions
ExhaustSmoke=aircraft/particles/usaf_c-141b_smokeemitter

[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=3
# Front
EngineAudioClip=audio/aircraft/707_Front
EngineAudioPosition=0,0,0
EngineAudioRollOff=Logarithmic
EngineAudioDistance=1,20
EngineAudioPitchRange=0.8,2.4
EngineAudioVolumeRange=0.25,1.0
EngineAudioAspectAngle=0
EngineAudioAspectArcHalfRange=120
EngineAudioAudibility=AboveAndBelow  // layer of sound audibility: Above, Below, AboveAndBelow
# Rear
ExhaustAudioClip=audio/aircraft/jet_rear_1
ExhaustAudioPosition=0,0,0
ExhaustAudioRollOff=Logarithmic
ExhaustAudioDistance=1,20
ExhaustAudioPitchRange=0.8,1.2
ExhaustAudioVolumeRange=0.8,1.4
ExhaustAudioAspectAngle=180
ExhaustAudioAspectArcHalfRange=180
ExhaustAudioAudibility=AboveAndBelow  // layer of sound audibility: Above, Below, AboveAndBelow
# Far
FarAudioClip=audio/aircraft/jet_far_4
FarAudioPosition=0,0,0
FarAudioRollOff=Logarithmic
FarAudioDistance=3,20
FarAudioPitch=0.75
FarAudioVolume=1.0
FarAudioFadeRange=0.05,0.25	      // nautical miles min/max
FarAudioAudibility=AboveAndBelow  // layer of sound audibility: Above, Below, AboveAndBelow
# Afterburner
AfterburnerAudioClip=audio/aircraft/afterburner_mig-29
AfterburnerAudioPosition=0,0,0
AfterburnerAudioRollOff=Logarithmic
AfterburnerAudioDistance=1,20
AfterburnerAudioPitch=0.75
AfterburnerAudioVolume=1.0
AfterburnerAudioAudibility=AboveAndBelow  // layer of sound audibility: Above, Below, AboveAndBelow
# Gears
#GearsAudioClip=audio/aircraft/gears
GearsAudioClip=audio/aircraft/LandingGearRetraction_v1
GearsAudioPosition=0,0,0
GearsAudioRollOff=Logarithmic
GearsAudioDistance=1,20
GearsAudioPitch=1.0
GearsAudioVolume=1.0
GearsAudioAudibility=AboveAndBelow  // layer of sound audibility: Above, Below, AboveAndBelow
# Flaps
#FlapsAudioClip=audio/aircraft/flaps
FlapsAudioClip=audio/aircraft/LandingGearRetraction_v1
FlapsAudioPosition=0,0,0
FlapsAudioRollOff=Logarithmic
FlapsAudioDistance=1,20
FlapsAudioPitch=1.0
FlapsAudioVolume=1.0
FlapsAudioAudibility=AboveAndBelow  // layer of sound audibility: Above, Below, AboveAndBelow

[---------- Colliders ----------]
[Colliders]
NumberOfColliders=2
Collider1=col_body
Collider2=col_nose

[col_body]
Collider=Box
Position=0,0.005,-0.1
Rotation=0,0,0
Scale=0.08,0.042,0.372

[col_nose]
Collider=Box
Position=0,0.005,0.19
Rotation=0,0,0
Scale=0.03,0.036,0.0223