[AmmunitionNames]
# ------------------ AAM ------------------

# ------------------ SAM ------------------
# ---------- Anti-radar Missiles ---------

# ---------- Anti-ship Missiles ----------

#-----------Land Strike only missiles---------

# ---------- Anti-sub  Missilies ----------

# ------------------ RBU ------------------

# ---------- Torpedoes ----------

# ------------------ Bombs -----------------

# ---------------- Sonobuoys ---------------

# ------------------ FFAR -----------------

# ------------------ MLRS -----------------

# ------------------ Guns -----------------

30mm_lionfish_AB=30mm AB
30mm_lionfish_AP=30mm AP

# ------------------ CIWS -----------------

# ----------- Noisemakers/Chaff -----------

# ----------------- Decoys ----------------

# ----------------- Special ----------------

# Depth charge

# ----------------- Fueltanks ----------------
