[ -------------- Destroyers --------------- ]
[ita_ddg_orizzonte]
Type=DDG,Destroyer
Default=Andrea Doria class,Andrea Doria
DefaultDescription=The Andrea Doria class is the Italian version of the advanced Franco-Italian Horizon guided missile destroyer family. Developed as a next-generation air-defense frigate to replace the aging AAW classes of France, Italy and the UK in the 1990s the class featured modern and powerful sensors and was to carry the new and advanced PAAMS integrated anit-air missile system. After the UK dropped out of the project in 1999 due to diverging requirements Italy and France would continue on their own, with the respective versions of the class for each nation featuring slightly different sensors and weapons. While Italy originally planned to accquire six ships of the type to replace the Andrea Doria class cruisers and Audace class destroyers this would drop to two ships by the turn of the century.
Variant1=(D 553) Andrea Doria,Andrea Doria
Variant2=(D 554) Caio Duilio,Caio Duilio

[ita_ddg_orizzonte_18]
Type=DDG,Destroyer
Default=Andrea Doria class,Andrea Doria
DefaultDescription=The Andrea Doria class is the Italian version of the advanced Franco-Italian Horizon guided missile destroyer family. Developed as a next-generation air-defense frigate to replace the aging AAW classes of France, Italy and the UK in the 1990s the class featured modern and powerful sensors and was to carry the new and advanced PAAMS integrated anit-air missile system. After the UK dropped out of the project in 1999 due to diverging requirements Italy and France would continue on their own, with the respective versions of the class for each nation featuring slightly different sensors and weapons. While Italy originally planned to accquire six ships of the type to replace the Andrea Doria class cruisers and Audace class destroyers this would drop to two ships by the turn of the century.
Variant1=(D 553) Andrea Doria,Andrea Doria
Variant2=(D 554) Caio Duilio,Caio Duilio

[ita_ddg_orizzonte_26]
Type=DDG,Destroyer
Default=Andrea Doria class,Andrea Doria
DefaultDescription=The Andrea Doria class is the Italian version of the advanced Franco-Italian Horizon guided missile destroyer family. Developed as a next-generation air-defense frigate to replace the aging AAW classes of France, Italy and the UK in the 1990s the class featured modern and powerful sensors and was to carry the new and advanced PAAMS integrated anit-air missile system. After the UK dropped out of the project in 1999 due to diverging requirements Italy and France would continue on their own, with the respective versions of the class for each nation featuring slightly different sensors and weapons. While Italy originally planned to accquire six ships of the type to replace the Andrea Doria class cruisers and Audace class destroyers this would drop to two ships by the turn of the century.
Variant1=(D 553) Andrea Doria,Andrea Doria
Variant2=(D 554) Caio Duilio,Caio Duilio

[ -------------- Frigates --------------- ]
[ita_ffg_fremm]
Type=FFG,Guided Missile Frigate
Default=Bergamini class (GP),Bergamini
DefaultDescription=The FREMM (European Multi-Mission Frigate) is a family of modern guided missile frigates collaboratively designed by Italy and France in the early 2000s to replace their aging classes of cold war frigates. The Italian Navy ordered their set of FREMMs as the Bergamini class in 2006 to personalized designs, splitting them into one group of general purpose frigates and another group geared towards anti-submarine warfare respectively. The majority of the class would consist of the 'General Purpose' version, featuring a heavier gun armament while omitting the variable depth sonar.
Variant1=(F 590) Carlo Bergamini,Carlo Bergamini
Variant2=(F 595) Luigi Rizzo,Luigi Rizzo
Variant3=(F 596) Federico Martinengo,Federico Martinengo
Variant4=(F 597) Antonio Marceglia,Antonio Marceglia
Variant5=(F 598) Spartaco Schergat,Spartaco Schergat

[ita_ffg_fremm_asw]
Type=FFG,Guided Missile Frigate
Default=Bergamini class (ASW),Bergamini
DefaultDescription=The FREMM (European Multi-Mission Frigate) is a family of modern guided missile frigates collaboratively designed by Italy and France in the early 2000s to replace their aging classes of cold war frigates. The Italian Navy ordered their set of FREMMs as the Bergamini class in 2006 to personalized designs, splitting them into one group of general purpose frigates and another group geared towards anti-submarine warfare respectively. The ASW version of the Bergamini features a lighter OTO-Melara STRALES rapid fire gun instead of the Leonardo 127mm found on the General Purpose variant and embarks a variable depth sonar.
Variant1=(F 591) Virginio Fasan,Virginio Fasan
Variant2=(F 592) Carlo Margottini,Carlo Margottini
Variant3=(F 593) Carabiniere,Carabiniere
Variant4=(F 594) Alpino,Alpino

#[ita_ffg_fremm_evo]
#Type=FFG,Guided Missile Frigate
#Default=Bergamini Class EVO,Bergamini
#Variant1=F600 Bersagliere,Bersagliere
#Variant2=F601 Zzocalu,Zzocalu

[ita_ffg_ppa]
Type=FFG,Guided Missile Frigate
Default=Thaon di Revel class,Thaon di Revel
DefaultDescription=The Thaon di Revel class is a highly modular class of multipurpose offshore patrol ships developed for the Italian Navy. These vessels are distinguished by their "double-bow" hull design, which improves hydrodynamic efficiency and increases maximum speed in rough sea states. The class is built on a "plug-and-fight" architecture, allowing the ship to be configured into three distinct variants: Light, Light+ and Full, which is the current configuration. 
Variant1=(P 430) Paolo Thaon di Revel,Thaon di Revel
Variant2=(P 431) Francesco Morosini,Francesco Morosini
Variant3=(P 432) Raimondo Montecuccoli,Montecuccoli
Variant4=(P 434) Giovanni delle Bande Nere,Bande Nere
Variant5=(P 436) Domenico Millelire,Domenico Millelire

[ita_ffg_ppa_evo]
Type=FFG,Guided Missile Frigate
Default=Thaon di Revel EVO Class,Thaon di Revel
DefaultDescription=The Thaon di Revel class is a highly modular class of multipurpose offshore patrol ships developed for the Italian Navy. These vessels are distinguished by their "double-bow" hull design, which improves hydrodynamic efficiency and increases maximum speed in rough sea states. The class is built on a "plug-and-fight" architecture, allowing the ship to be configured into three distinct variants: Light, Light+ and Full, which is the current configuration. The modernized EVO version carries 64 VLS cells, replacing the modular section midship, and a new pair of 30 mm CIWS in place of the 25 mm light cannons.
Variant1=(P 433) Marcantonio Colonna,Marcantonio Colonna
Variant2=(P 435) Ruggiero di Lauria,Ruggiero di Lauria

[ -------------- Submarines --------------- ]
[ita_ssk_todaro_batch1]
Type=SSK,Attack Submarine
Default=Todaro class (Batch I),Todaro
DefaultDescription=The Todaro is the Italian variant of the German Type 212A. Designed as a modern air-independent propulsion (AIP) attack submarine the Todaro-class emphasizes stealth, endurance, and ambush capability in both littoral and open-ocean environments. A low-signature hull, quiet electric drive, and fuel-cell AIP enable prolonged submerged operations at very low acoustic output, supporting covert patrols and patient target prosecution. The combat system integrates a comprehensive sonar suite, including flank and intercept sensors plus a towed array for improved long-range detection - allowing the boat to build a high-quality underwater picture while minimizing emissions. Primary lethality is delivered through heavyweight wire-guided torpedoes for anti-submarine and anti-surface warfare, complemented by layered soft-kill countermeasures to break torpedo engagements and regain separation. Overall: a highly survivable, intelligence-capable hunter optimized for covert presence and decisive underwater strikes rather than high-speed pursuit.
Variant1=(S 526) Salvatore Todaro,Salvatore Todaro
Variant2=(S 527) Scire,Scire
Variant3=(S 528) Pietro Venuti,Pietro Venuti
Variant4=(S 529) Romeo Romei,Romeo Romei