[---------- General Data ----------]
[General]
UnitType=Aircraft

DefaultCameraDistance=1
MinCameraDistanceForeAft=0.36
MinCameraDistanceBroadside=0.36
CameraPivotHeight=0.0

#Taxi values
GroundedPitchAngle=-0.6  // 这个角度是降落时地面的俯仰角（x）
GroundPivot=0,-0.037,0.017997 // 主轮之间的点，起飞落地抬轮的参考点

Pilot1=wp_pilot_a                      // 飞行员调用，在ammunition里
Pilot1Positions=0,0.010982,0.099698        // 飞行员位置
EjectChance=0.6                        
        // 弹射机会

[AI]
Role=Fighter,Bomber,SEAD                       //脚本
// 目前种类有：Fighter、Bomber、HeavyBomber、SEAD、Recon、EW、ESM、Transport、MPA、AEW、ASW、ASuW、Attack、Airliner

[SensorData]
#Visual
VisualIdentificationRange=6       // Biggest range in nm at which this unit can be visually identified
IRSignature=SemiSmall
# Radar related (RCS => radar cross section)
RCS=SemiSmall

[Animations]
NumberOfAnimationReferences=1
AnimationFile_1=animations_plaaf_j-11

[---------- Flight Model ----------]
[Engine]
EngineIntakeArea=1.05                //Pi* r * r where r is engine radius, in meters

[FlightModel]
PitchGain=1                         // Vertical manuverability
VelocityGain=0.1136                   // Acceleration
HeadingGain=3                         // Horizontal manuverability
YawRateLimit=130                      // in degrees per second

BankGain=1                          // Roll change speed
#MaxRollForHeading=65.0                // bank limit in normal flight
MaxRollRate=120.0                      // in degrees per second

ThrustGain=0.35                      // Thrust change speed
SpeedBrakeFractionGain=10            // Speed brakes deploy speed

SpeedDeltaPerAltitudeChange=0.0885

[Performance]
#Dimensions
WingSpan=14.7                       //meters
#Parameters
MaxG=9.6                                // Mostly for horizontal turns

MaxClimbRate=300                      //Meters per second
EmptyMass=15000.0                     // in kg
MaxFuel=5600                        // in kg, internal tanks only

PerEngineMaxThrust=89170              //Newtons
PerEngineMaxAfterburnerThrust=132000  //Newtons
EngineCount=2
EngineWarmUp=15

Ceiling=65000.0                       // ceiling in feet
CruiseAltitude= ????                  //in feet
#"Engine" efficiency at 0ft, 37000 ft, 65000 ft. Always 1 for cruise altitude
AltitudeEfficiency=0.5,0.5,0.25       // Defines fuel consumption with altitude

#Governing of max speed
MaxSpeedAtSeaLevel=615                //in knots, Defines max speed at altitude curve
StallSpeed=140                      //in knots
MachLimit=2.3                         //for 37000ft, Defines max speed at altitude curve

#SpeedAndRange   MachNumbers or knots, Specified units or multiplier (except Cruise range)
RangeUnits=Miles                      // Can be: Km. Any other value = nmi. Defines measurment units of ranges of SpeedAndRange values

SpeedAndRange_Landing=0.2,0.4        // Landing
SpeedAndRange_Loiter=0.5,0.6          // Loiter
SpeedAndRange_Cruise=0.9,1906        // Cruise
SpeedAndRange_Max=1.6,0.8             // Attack/Fast/High/Max without AB
SpeedAndRange_Afterburner=2.3,0.2     // AB max

Altitudes=200,1000,3000,6000,10000,20000,30000  // in feet

[---------- Main Systems ----------]
[FlightControls]
NumberOfAilerons=2
Aileron1_Model=aileron_l
Aileron1_MinAngle=-20.0
Aileron1_MaxAngle=20.0
Aileron1_RotationAxis=X

Aileron2_Model=aileron_r
Aileron2_MinAngle=-20.0
Aileron2_MaxAngle=20.0
Aileron2_RotationAxis=X

NumberOfElevons=1
Elevon1_Model=elevator
Elevon1_MinAngle=-20.0s
Elevon1_MaxAngle=20.0
Elevon1_RotationAxis=X

NumberOfRudders=2
Rudder1_Model=rudder_l
Rudder1_MinAngle=-30.0
Rudder1_MaxAngle=30.0


Rudder2_Model=rudder_l
Rudder2_MinAngle=-30.0
Rudder2_MaxAngle=30.0


AfterBurnerSubModel=afterburner    // optional entry
MaxAfterBurnerIntensity=0.2
AfterBurnerFadeTime=0.5

[---------- Sensor Systems ----------]
[SensorSystems]
NumberOfSensorSystems=6

[SensorSystem1] #Cockpit
# Cockpit
Type=Visual
SystemName=Eyes
Mount=Dummy
ViewArcs=-181,181|-25,91
ModuleType=Sensor

[SensorSystem2] #IRST
Type=Infrared
SystemName=OLS-35
MountPosition=0,0.03,0
ViewArcs=-30,30|-30,30

[SensorSystem3] #RWR
Type=ESM
SystemName=AircraftRWR
Mount=Dummy
ModuleType=Sensor

[SensorSystem4]
Type=Radar
SystemName=1493
Mount=Dummy
ModuleType=Sensor

[SensorSystem5] #ECM
Type=ECM
SystemName=AircraftDECM_Late
Mount=Dummy
ModuleType=Sensor

[SensorSystem6] #ESM
Type=ESM
SystemName=AircraftELINT
Mount=Dummy
ModuleType=Sensor

[---------- Weapon Systems ----------]
[WeaponSystems]
NumberOfWeaponSystems=3
AvailableLoadouts=AirToAir,Strike,CAS

[WeaponSystem1] #Hardpoint
Type=Hardpoint
SystemName=Hardpoint
AssociatedSensors=SensorSystem4
NumberOfStations=10

Station1=-0.0004,-0.008378,0.005017                         //PL-12
Station2=-0.0004,-0.010877,-0.048258  
Station3=0.017306,-0.021749,-0.010331
Station4=-0.018475,-0.021749,-0.010331
Station5=0.065014,-0.003309,-0.028607
Station6=-0.066018,-0.003309,-0.028607
Station7=0.086258,-0.003455,-0.052553   //PL-8
Station8=-0.086881,-0.003455,-0.052553
Station9=0.10538,0.000971,-0.052177
Station10=-0.10638,0.000971,-0.052177

Station1Rotation=1.5,0,0
Station2Rotation=1.5,0,0

FiringArcs=-15,15

#S-8
S-8Positions=-0.0042,-0.002222,-0.002383|0.0042,-0.002222,-0.002383

#MBD

#500-3
500-3Positions=0,0.001678,-0.003277
500-3CHPositions=-0.004082,-0.00146,-0.004415|0.004397,-0.00146,-0.004415




ModuleType=Weapon

[WeaponSystem2] #Gun
Type=CIWS
SystemName=Gsh-301
#Sensors
#Animations
#Mount
Mount=Dummy
MountPosition=0.015012,0.006799,0.071144
IsMountRotatable=True
#Containers
ContainerBase=Dummy
Gun=Dummy
AreContainersRotatable=True
#Angles
FiringArcs=-1,1
ElevationArc=-1,1
#Loading
AssociatedMagazine=WeaponMagazineGsh-301
#Effects
#Other
IsOffensive=True
ModuleType=Weapon

[WeaponSystem3] #Chaff
Type=Chaff
SystemName=WP_AIR_CHAFF_DISP_DORSAL
#Sensors
#Animations
#Mount
Mount=Dummy
#MountPosition=0,-0.01,-0.016
#Containers
ContainerBase=Dummy
#Angles
#Loading
AssociatedMagazine=WeaponMagazineChaff
#Effects
NumberOfEffects=4
DelayBetweenLaunches=0.1
#Other
WorksStandalone=True
ModuleType=Weapon

[--------------------------- Loadouts ---------------------------]
#--------------- Standart --------------
[WeaponSystem1Empty]
SubModelsToHide=AAM_wings,r73_rail_out,pl12_rail_mid,pl12_rail_in,pl12_rail_down,bomb_in,bomb_up,bomb_down,ECM

[WeaponSystem1Ferry]
SubModelsToHide=AAM_wings,r73_rail_out,pl12_rail_mid,pl12_rail_in,pl12_rail_down,bomb_in,bomb_up,bomb_down,ECM



[WeaponSystem1Default]
ReadyUpTime=15              // in minutes. Time that plane will spend refueling and rearming before takeoff.
SubModelsToHide=bomb_up,bomb_down
Station1=plaaf_pl-12
Station2=plaaf_pl-12
Station3=plaaf_pl-12
Station4=plaaf_pl-12
Station5=plaaf_pl-12
Station6=plaaf_pl-12
Station7=plaaf_pl-8b
Station8=plaaf_pl-8b
Station9=plaaf_pl-8b
Station10=plaaf_pl-8b


#--------------- Anti-Air --------------
[WeaponSystem1AirToAir]
ReadyUpTime=15              // in minutes. Time that plane will spend refueling and rearming before takeoff.
SubModelsToHide=bomb_up,bomb_down
Station1=plaaf_pl-12
Station2=plaaf_pl-12
Station3=plaaf_pl-12
Station4=plaaf_pl-12
Station5=plaaf_pl-12
Station6=plaaf_pl-12
Station7=plaaf_pl-8b
Station8=plaaf_pl-8b
Station9=plaaf_pl-8b
Station10=plaaf_pl-8b

#---------- Anti-Surface ----------
[WeaponSystem1Strike]
SubModelsToHide=pl12_rail_mid,pl12_rail_in,pl12_rail_down
Station1=plaaf_500-Ⅲ|500-3
Station2=plaaf_500-Ⅲ|500-3
Station3=plaaf_500-Ⅲ|500-3
Station4=plaaf_500-Ⅲ|500-3
Station5=plaaf_500-Ⅲ|500-3CH
Station6=plaaf_500-Ⅲ|500-3CH
Station7=plaaf_pl-8b
Station8=plaaf_pl-8b
Station9=plaaf_pl-8b                           
Station10=plaaf_pl-8b

[WeaponSystem1CAS]
SubModelsToHide=pl12_rail_mid,bomb_down
Station1=plaaf_pl-12
Station2=plaaf_pl-12
Station3=plaaf_pl-12
Station4=plaaf_pl-12
Station5=wp_b8m-1|S-8
Station6=wp_b8m-1|S-8
Station7=plaaf_pl-8b
Station8=plaaf_pl-8b
Station9=plaaf_pl-8b                           
Station10=plaaf_pl-8b


[---------- WeaponMagazines ----------]
############################################################
# Weapon Magazine Systems
############################################################
[WeaponMagazineGsh-301]
NumberOfAmmunitionTypes=1
Ammunition1_Count=150
Ammunition1=wp_cal_30mm
ModuleType=WeaponMagazine

[WeaponMagazineChaff]
NumberOfAmmunitionTypes=1
Ammunition1_Count=25
Ammunition1=wp_aircraft_chaff
ModuleType=WeaponMagazine

[--------------------------- Mesh definitions ---------------------------]
[Models]
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=assets/models/aircraft/j-11b/
ResourcesRoot=J-11B.obj
ResourcesMesh=hull
ResourcesMaterialFolder=assets/models/aircraft/textures/
ResourcesMaterial=j-11_mat.ini
############################################################
NumberOfDamageModels=1
DamageModel1=hull_d1
DamageModelMaterial1=j-11_mat.ini
DamageModelLostWingSide1=Left
############################################################
[Submodels]
#---------- General ----------
General_1=afterburner
General_2=windshield
General_3=hatch
General_4=glass
General_5=pilot
General_6=hud
General_7=Emblem
General_8=Number

#---------- Left Wing ----------
LeftWing_1=aileron1
LeftWing_2=aileron_l

#---------- Right Wing ----------
RightWing_1=aileron2
RightWing_2=aileron_r

#---------- Tail ----------
Tail_1=elevator
Tail_2=Airbrake
Tail_3=rudder_l
Tail_4=rudder_r

#---------- Nose Gear ----------
NoseGear_1=nose_gear1
NoseGear_2=nose_hatch
NoseGear_3=nose_gear


#---------- Left Gear ----------
LeftGear_1=left_gear_up
LeftGear_2=left_gear_mid
LeftGear_3=left_gear_down
LeftGear_4=left_hatch_aft
LeftGear_5=left_hatch_for

#---------- Right Gear ----------
RightGear_1=right_gear_up
RightGear_2=right_gear_mid
RightGear_3=right_gear_down
RightGear_4=right_hatch_aft
RightGear_5=right_hatch_for

#---------- Modex ----------

#---------- Weapons ----------
Weapons_1=AAM_wings
Weapons_2=ECM
Weapons_3=r73_rail_out
Weapons_4=pl12_rail_mid
Weapons_5=pl12_rail_in
Weapons_6=pl12_rail_down

Weapons_9=bomb_in
Weapons_10=bomb_up
Weapons_11=bomb_down

#--------- Composite hanger ---------
############################################################
#---------- General ----------
############################################################

[afterburner]
Mesh=afterburner
ResourcesMaterialFolder=aircraft/materials/
Material=afterburner_mat
Position=0,0,0
Rotation=0,0,0
CastShadows=False

[windshield]
Mesh=windshield
ResourcesMaterialFolder=aircraft/materials/
Material=cockpit_glass

[hatch]
Mesh=hatch
ResourcesMaterialFolder=assets/models/aircraft/textures/
Material=j-11_mat.ini
Position=0,0.021,0.071
Rotation=0,0,0

[glass]
Mesh=glass
ResourcesMaterialFolder=aircraft/materials/
Material=cockpit_glass
Parent=hatch

[pilot]
Mesh=pilot
ResourcesMaterialFolder=characters/materials/
Material=wp_pilot_a_mat

[hud]
Mesh=hud
ResourcesMaterialFolder=aircraft/materials/
Material=cockpit_glass

[Number]
Mesh=number
ResourcesMaterialFolder=aircraft/materials/numbers/
Material=numbers

[Emblem]
Mesh=emblem
ResourcesMaterialFolder=aircraft/materials/emblem/
Material=emblem

############################################################
#---------- Left Wing ----------
############################################################
[aileron1]
Mesh=point
Position=-0.051,0.003,-0.049
Rotation=0,0,-2.22914

[aileron_l]
Mesh=aileron_l
ResourcesMaterialFolder=assets/models/aircraft/textures/
Material=j-11_mat.ini
Parent=aileron1
Position=0,0,0
Rotation=0,-24.6526,0

############################################################
#---------- Right Wing ----------
############################################################
[aileron2]
Mesh=point
Position=0.051,0.003,-0.049
Rotation=0,0,2.22914

[aileron_r]
Mesh=aileron_r
ResourcesMaterialFolder=assets/models/aircraft/textures/
Material=j-11_mat.ini
Parent=aileron2
Position=0,0,0
Rotation=0,24.6526,0

############################################################
#---------- Tail ----------
############################################################
[elevator]
Mesh=elevator
ResourcesMaterialFolder=assets/models/aircraft/textures/
Material=j-11_mat.ini
Position=0,-0.004,-0.093
Rotation=0,0,0

[rudder_l]
Mesh=rudder_l
ResourcesMaterialFolder=assets/models/aircraft/textures/
Material=j-11_mat.ini
Position=-0.0298,0.025,-0.084
Rotation=-104.64,0,0

[rudder_r]
Mesh=rudder_r
ResourcesMaterialFolder=assets/models/aircraft/textures/
Material=j-11_mat.ini
Position=0.0298,0.025,-0.084
Rotation=-104.64,0,0

[Airbrake]
Mesh=Airbrake
ResourcesMaterialFolder=assets/models/aircraft/textures/
Material=j-11_mat.ini
Position=0,0.019,0.037

############################################################
#---------- Nose Gear ----------
############################################################
[nose_gear1]
Mesh=point
Position=0,0.0035,0.0568
Rotation=0,0,0

[nose_gear]
Mesh=nose_gear
ResourcesMaterialFolder=assets/models/aircraft/textures/
Material=j-11_mat.ini
Parent=nose_gear1
Position=0,0,0
Rotation=0,0,0

[nose_hatch]
Mesh=nose_gear_hatch
ResourcesMaterialFolder=assets/models/aircraft/textures/
Material=j-11_mat.ini
Position=0.003,-0.001,0
Rotation=0,0,0

############################################################
#---------- Left Gear ----------
############################################################
[left_gear_up]
Mesh=left_gear_up
ResourcesMaterialFolder=assets/models/aircraft/textures/
Material=j-11_mat.ini
Position=-0.024,0,-0.028
Rotation=0,0,0

[left_gear_mid]
Mesh=left_gear_mid
ResourcesMaterialFolder=assets/models/aircraft/textures/
Material=j-11_mat.ini
Parent=left_gear_up
Position=0,0,0
Rotation=0,19,0

[left_gear_down]
Mesh=left_gear_down
ResourcesMaterialFolder=assets/models/aircraft/textures/
Material=j-11_mat.ini
Parent=left_gear_mid
Position=-0.004331,0.00115,0
Rotation=0,0,0

[left_hatch_aft]
Mesh=left_hatch_aft
ResourcesMaterialFolder=assets/models/aircraft/textures/
Material=j-11_mat.ini
Position=-0.034,0.003,0
Rotation=0,0,0

[left_hatch_for]
Mesh=left_hatch_for
ResourcesMaterialFolder=assets/models/aircraft/textures/
Material=j-11_mat.ini
Position=-0.036,0.005,0
Rotation=0,0,0


############################################################
#---------- Right Gear ----------
############################################################
[right_gear_up]
Mesh=right_gear_up
ResourcesMaterialFolder=assets/models/aircraft/textures/
Material=j-11_mat.ini
Position=0.023,0,-0.028
Rotation=0,0,0

[right_gear_mid]
Mesh=right_gear_mid
ResourcesMaterialFolder=assets/models/aircraft/textures/
Material=j-11_mat.ini
Parent=right_gear_up
Position=0,0,0
Rotation=0,-19,0

[right_gear_down]
Mesh=right_gear_down
ResourcesMaterialFolder=assets/models/aircraft/textures/
Material=j-11_mat.ini
Parent=right_gear_mid
Position=0.004331,0.00115,0
Rotation=0,0,0

[right_hatch_aft]
Mesh=right_hatch_aft
ResourcesMaterialFolder=assets/models/aircraft/textures/
Material=j-11_mat.ini
Position=0.034,0.003,0
Rotation=0,0,0

[right_hatch_for]
Mesh=right_hatch_for
ResourcesMaterialFolder=assets/models/aircraft/textures/
Material=j-11_mat.ini
Position=0.037,0.005,0
Rotation=0,0,0

############################################################
#---------- Modex ----------
############################################################


############################################################
#---------- Weapons ----------
############################################################

[AAM_wings]
Mesh=AAM_wings
ResourcesMaterialFolder=assets/models/aircraft/textures/
Material=j-11_mat.ini

[ECM]
Mesh=ECM
ResourcesMaterialFolder=assets/models/aircraft/textures/
Material=j-11_mat.ini

[r73_rail_out]
Mesh=pl_rail_out
ResourcesMaterialFolder=assets/models/aircraft/textures/
Material=j-11_mat.ini

[pl12_rail_mid]
Mesh=pl12_rail_mid
ResourcesMaterialFolder=assets/models/aircraft/textures/
Material=j-11_mat.ini

[pl12_rail_in]
Mesh=pl12_rail_in
ResourcesMaterialFolder=assets/models/aircraft/textures/
Material=j-11_mat.ini

[pl12_rail_down]
Mesh=pl12_rail_down
ResourcesMaterialFolder=assets/models/aircraft/textures/
Material=j-11_mat.ini

[bomb_down]
Mesh=bomb_down
ResourcesMaterialFolder=assets/models/aircraft/textures/
Material=j-11_mat.ini

[bomb_up]
Mesh=bomb_up
ResourcesMaterialFolder=assets/models/aircraft/textures/
Material=j-11_mat.ini

[bomb_in]
Mesh=bomb_in
ResourcesMaterialFolder=assets/models/aircraft/textures/
Material=j-11_mat.ini

############################################################
#N/A
[---------- Effects ----------]
[Particles]
ShotDownFireEffect=effects/aircraft_kill_effects/usaf_f-15c_kill
ShotDownFireEffectPosition=0,0,0
HitWaterEffect=effects/splashes/emitters/splash_bomb
HitGroundEffect=effects/explosions/emitters/aircraft_hit_ground
HitAirEffectClass=LargeMissileExplosions
ExhaustSmoke=aircraft/particles/usaf_f-15c_smokeemitter
TipVortexPosition=0.096,0.004,0.135
TipVortex=effects/aircraft/emitters/tipvortex
LeftWingVortexPosition=0,0,0.05
LeftWingVortex=effects/aircraft/emitters/wingvortex_f-15_left
RightWingVortexPosition=0,0,0.05
RightWingVortex=effects/aircraft/emitters/wingvortex_f-15_right
ShockConePosition=0,0,0
ShockCone=effects/aircraft/emitters/shockcone

[Sounds]
############################################################
# Sounds
############################################################
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=3
# Front
EngineAudioClip=audio/aircraft/TF30
EngineAudioPosition=0,0,0
EngineAudioRollOff=Logarithmic
EngineAudioDistance=1,20
EngineAudioPitchRange=1.0,2.4
EngineAudioVolumeRange=0.1,0.5
# Rear
ExhaustAudioClip=audio/aircraft/jet_rear_1
ExhaustAudioPosition=0,0,0
ExhaustAudioRollOff=Logarithmic
ExhaustAudioDistance=1,20
ExhaustAudioPitchRange=0.6,1.0
ExhaustAudioVolumeRange=0.75,1.0
# Far
FarAudioClip=audio/aircraft/jet_far_1
FarAudioPosition=0,0,0
FarAudioRollOff=Logarithmic
FarAudioDistance=5,20
FarAudioPitch=1.0
FarAudioVolume=1.0
FarAudioFadeRange=0.0,0.15	      // nautical miles min/max
# Afterburner
AfterburnerAudioClip=audio/aircraft/afterburner_f-15
AfterburnerAudioPosition=0,0,0
AfterburnerAudioRollOff=Logarithmic
AfterburnerAudioDistance=1,20
AfterburnerAudioPitch=1.0
AfterburnerAudioVolume=1.0
# Gears
#GearsAudioClip=audio/aircraft/gears
GearsAudioClip=audio/aircraft/LandingGearRetraction_v1
GearsAudioPosition=0,0,0
GearsAudioRollOff=Logarithmic
GearsAudioDistance=1,20
GearsAudioPitch=1.0
GearsAudioVolume=1.0
# Flaps
#FlapsAudioClip=audio/aircraft/flaps
FlapsAudioClip=audio/aircraft/LandingGearRetraction_v1
FlapsAudioPosition=0,0,0
FlapsAudioRollOff=Logarithmic
FlapsAudioDistance=1,20
FlapsAudioPitch=1.0
FlapsAudioVolume=1.0

//Front Sound = audio/aircraft/JE_Front_3 v=0.25, p=1.2
//Rear	Sound = audio/aircraft/JE_Burner_2
//Far	Sound = audio/aircraft/JetExhaustLoop p=0.75
//Afterburner = audio/aircraft/AfterburnerLarge_v1 p=0.75

[---------- Colliders ----------]
############################################################
# Colliders definition
############################################################
[Colliders]
# creates the hit boxes for this object
NumberOfColliders=3
Collider1=coll_body
Collider2=coll_body2
Collider3=coll_wings

[coll_body]
Collider=Box
Position=0,0,0.062
Rotation=0,0,0
Scale=0.023,0.028,0.18

[coll_body2]
Collider=Box
Position=0,-0.01,-0.01
Rotation=0,0,0
Scale=0.05,0.02,0.16

[coll_wings]
Collider=Box
Position=0,0,-0.013
Rotation=0,0,0
Scale=0.17,0.007,0.058