[Language_en]
Name=A-10C
Description=by Texas_the-Omertosa and misaka

[Language_cn]
Name=A-10C
Description=由Texas_the_Omertosa与misaka共同制作

[Compatibility]
;ApproximateVersion is the second check and will override all statements below. This checks MAJOR and MINOR match but will accept higher PATCH.
;Would recommend this as a default case for starters.
ApproximateVersion=0.7.0