[LoadoutNames]
#------------------------------------------ New system ------------------------------------------
# - LongRange means operating range of aircraft, not the weapons range
# ---------- Mandatory loadouts ----------
Default=Default                            // Usually most common loadout for this plane
DefaultAlt=Default Alt
DefaultHeavy=Default Heavy

CAS=Close Air Support                      // Rockets, Cluster bombs, Bombs. Usually in small salvos to increace number of attacks
CASHeavy=Close Air Support Heavy

AntiArmor=AntiTank                         // Strike missiles mostly useful only land vehicles(like AS-7)
AntiArmorAlt=AntiTank Alt
AntiArmorHeavy=AntiTank Heavy
