[General]
SerialnumberReferences=
EmblemReference=Emblem
NationFlagReference=Flag19
NumberOfSquadrons=2

[Default]
Nation=France

[Squadron1] #Flottile 34 Early
ResourcesSerialnumberFolder=/aircraft/materials/numbers/
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/rn_wasp/Variants/
LiveryTexture=
ResourcesFlagFolder=
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=France

[Squadron2] #Flottile 34 Late
ResourcesSerialnumberFolder=/aircraft/materials/numbers/
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/nl_sea_lynx/Variants/
LiveryTexture=Lynx_French_camo.png
ResourcesFlagFolder=
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=France