[WeaponSystem3] # Bofors left
Type=Gun
SystemName=Bofors_L/70_MkIII
#Sensors
#NumberOfAssociatedSensors=1
AssociatedSensors=SensorSystem5,SensorSystem6
#Animations
#Mount
Mount=Bofors_Mount_left
IsMountRotatable=True
#Containers
ContainerBase=Bofors_Gun_left
NumberOfGuns=1
Gun1=Bofors_Barrel_left
AreContainersRotatable=True
#Angles
FiringArcs=-180,5
ElevationArc=-5,85
RestAngles=0
#Loading
AssociatedMagazine=WeaponMagazine_Bofors_left
#Effects
#Other
WorksStandalone=True
Collider=coll_bofors_port
ModuleType=CIWS

[WeaponSystem4] # Bofors right
Type=Gun
SystemName=Bofors_L/70_MkIII
#Sensors
#NumberOfAssociatedSensors=1
AssociatedSensors=SensorSystem5,SensorSystem6
#Animations
#Mount
Mount=Bofors_Mount_right
IsMountRotatable=True
#Containers
ContainerBase=Bofors_Gun_right
NumberOfGuns=1
Gun1=Bofors_Barrel_right
AreContainersRotatable=True
#Angles
FiringArcs=-5,180
ElevationArc=-5,85
RestAngles=0
#Loading
AssociatedMagazine=WeaponMagazine_Bofors_right
#Effects
#Other
WorksStandalone=True
Collider=coll_bofors_stbd
ModuleType=CIWS




[WeaponMagazine_Bofors_left]
NumberOfAmmunitionTypes=1
Ammunition1=usn_cal_40mm
Ammunition1_Count=101
SystemGroup=SG_Gun
Collider=coll_magazine_bofors_port
ModuleType=SmallMagazine

[WeaponMagazine_Bofors_right]
NumberOfAmmunitionTypes=1
Ammunition1=usn_cal_40mm
Ammunition1_Count=101
SystemGroup=SG_Gun
Collider=coll_magazine_bofors_stbd
ModuleType=SmallMagazine



Bofors_Mount_left=Bofors_Mount_left
Bofors_Gun_left=Bofors_Gun_left
Bofors_Barrel_left=Bofors_Barrel_left

Bofors_Mount_right=Bofors_Mount_right
Bofors_Gun_right=Bofors_Gun_right
Bofors_Barrel_right=Bofors_Barrel_right



[Bofors_Mount_left]
ResourcesMeshFolder=assets/europack/models/weapons/
RootMesh=weapons.obj
Mesh=eu_40mm_Mk3_TurretB
ResourcesMaterialFolder=ships/materials/
Material=usn_fastforty
Position=-0.073096,0.168354 ,0.205649
Rotation=0,0,0
[Bofors_Gun_left]
ResourcesMeshFolder=assets/europack/models/weapons/
RootMesh=weapons.obj
Mesh=eu_40mm_Mk3_Gun
ResourcesMaterialFolder=ships/materials/
Material=usn_fastforty
Parent=Bofors_Mount_left
Position=0.000000,0.020880,-0.002736
[Bofors_Barrel_left]
ResourcesMeshFolder=assets/europack/models/weapons/
RootMesh=weapons.obj
Mesh=eu_40mm_Mk3_Barrel
ResourcesMaterialFolder=ships/materials/
Material=usn_fastforty
Parent=Bofors_Gun_left
Position=-0.000000,-0.000032,0.018429

[Bofors_Mount_right]
ResourcesMeshFolder=assets/europack/models/weapons/
RootMesh=weapons.obj
Mesh=eu_40mm_Mk3_TurretB
ResourcesMaterialFolder=ships/materials/
Material=usn_fastforty
Position=0.073096,0.168354 ,0.205649
Rotation=0,0,0
[Bofors_Gun_right]
ResourcesMeshFolder=assets/europack/models/weapons/
RootMesh=weapons.obj
Mesh=eu_40mm_Mk3_Gun
ResourcesMaterialFolder=ships/materials/
Material=usn_fastforty
Parent=Bofors_Mount_right
Position=0.000000,0.020880,-0.002736
[Bofors_Barrel_right]
ResourcesMeshFolder=assets/europack/models/weapons/
RootMesh=weapons.obj
Mesh=eu_40mm_Mk3_Barrel
ResourcesMaterialFolder=ships/materials/
Material=usn_fastforty
Parent=Bofors_Gun_right
Position=-0.000000,-0.000032,0.018429
