[SensorSystem13]  #Mk38 1 EO / Mk48 EOSS
Type=Radar
SystemName=eu_Mk20_EOSS
Mount=Dummy
MountPosition=0.0978,0.2000,0.1538
Collider=coll_Mk38_right

[SensorSystem14]  #Mk38 2 EO / Mk48 EOSS
Type=Radar
SystemName=eu_Mk20_EOSS
Mount=Dummy
MountPosition=-0.0978,0.2000,0.1538
Collider=coll_Mk38_left

[WeaponSystem18] # Mk38 Mod 4 (30x173)
Type=CIWS
SystemName=eu_Mk38_Mod4
#Sensors
AssociatedSensors=SensorSystem13
ExternalGuidingSystems=SensorSystem1,SensorSystem2,SensorSystem3,SensorSystem4,SensorSystem5,SensorSystem6,SensorSystem7,SensorSystem8,SensorSystem9,SensorSystem10,SensorSystem13,SensorSystem16
#Animations
#Mount
Mount=Mk38_turret_1
IsMountRotatable=True
#Containers
ContainerBase=Mk38_gun_1
Gun=Mk38_gun_1
AreContainersRotatable=True
#Angles
FiringArcs=4,182
ElevationArc=-15,60
RestAngles=90
#Loading
AssociatedMagazine=WeaponMagazine_30mm
#Effects
#Other
WorksStandalone=True
Collider=coll_Mk38_right

[WeaponSystem19] # Mk38 Mod 4 (30x173)
Type=CIWS
SystemName=eu_Mk38_Mod4
#Sensors
AssociatedSensors=SensorSystem14
ExternalGuidingSystems=SensorSystem1,SensorSystem2,SensorSystem3,SensorSystem4,SensorSystem5,SensorSystem6,SensorSystem7,SensorSystem8,SensorSystem9,SensorSystem10,SensorSystem13,SensorSystem16
#Animations
#Mount
Mount=Mk38_turret_2
IsMountRotatable=True
#Containers
ContainerBase=Mk38_gun_2
Gun=Mk38_gun_2
AreContainersRotatable=True
#Angles
FiringArcs=178,356
ElevationArc=-15,60
RestAngles=-90
#Loading
AssociatedMagazine=WeaponMagazine_30mm
#Effects
#Other
WorksStandalone=True
Collider=coll_Mk38_left


[---------- WeaponMagazines ----------]

[WeaponMagazine_30mm]
NumberOfAmmunitionTypes=1
Ammunition1_Count=3174
Ammunition1=usn_cal_30mm
Collider=coll_mlg_left
ModuleType=SmallMagazine

[---------- Mesh definitions----------]
############################################################
# Main Model with collider
############################################################

[Submodels]
SubModel51=Mk38_mount_1   
SubModel52=Mk38_mount_2     
SubModel53=Mk38_turret_1   
SubModel54=Mk38_turret_2 
SubModel55=Mk38_gun_1    
SubModel56=Mk38_gun_2 

[Mk38_mount_1]
ResourcesMeshFolder=assets/europack/models/
RootMesh=weapons.obj
Mesh=eu_Mk38_Mod4_base
ResourcesMaterialFolder=assets/europack/materials/Mk38_Mod4/
Material=Mk38_Mod4_mat.ini
Position=0.1355,0.1623,-0.18988
Rotation=0,90,0

[Mk38_turret_1]
ResourcesMeshFolder=assets/europack/models/
RootMesh=weapons.obj
Mesh=eu_Mk38_Mod4_turret
ResourcesMaterialFolder=assets/europack/materials/Mk38_Mod4/
Material=Mk38_Mod4_mat.ini
Parent=Mk38_mount_1

[Mk38_gun_1]
ResourcesMeshFolder=assets/europack/models/
RootMesh=weapons.obj
Mesh=eu_Mk38_Mod4_gun
ResourcesMaterialFolder=assets/europack/materials/Mk38_Mod4/
Material=Mk38_Mod4_mat.ini
Parent=Mk38_turret_1
Position=0.000144,0.022305,-0.004982

[Mk38_mount_2]
ResourcesMeshFolder=assets/europack/models/
RootMesh=weapons.obj
Mesh=eu_Mk38_Mod4_base
ResourcesMaterialFolder=assets/europack/materials/Mk38_Mod4/
Material=Mk38_Mod4_mat.ini
Position=-0.1355,0.1623,-0.18988
Rotation=0,-90,0

[Mk38_turret_2]
ResourcesMeshFolder=assets/europack/models/
RootMesh=weapons.obj
Mesh=eu_Mk38_Mod4_turret
ResourcesMaterialFolder=assets/europack/materials/Mk38_Mod4/
Material=Mk38_Mod4_mat.ini
Parent=Mk38_mount_2

[Mk38_gun_2]
ResourcesMeshFolder=assets/europack/models/
RootMesh=weapons.obj
Mesh=eu_Mk38_Mod4_gun
ResourcesMaterialFolder=assets/europack/materials/Mk38_Mod4/
Material=Mk38_Mod4_mat.ini
Parent=Mk38_turret_2
Position=0.000144,0.022305,-0.004982



[---------- Colliders ----------]
############################################################
# Colliders definition
############################################################

Collider11=coll_Mk38_right                       
Collider12=coll_Mk38_left 

[coll_Mk38_right]
Collider=Sphere
Position=0.1402,0.1823,-0.18988
Rotation=0,0,0
Scale=0.0330,0.0330,0.0330

[coll_Mk38_left]
Collider=Sphere
Position=-0.1402,0.1823,-0.18988
Rotation=0,0,0
Scale=0.0330,0.0330,0.0330