[WeaponSystem16]  #NSM_quad_launcher 1
Type=Missile
SystemName=eu_NSM_quad_launcher
#Sensors
AssociatedSensors=SensorSystem2,SensorSystem3,SensorSystem4,SensorSystem5,SensorSystem6,SensorSystem7,SensorSystem8,SensorSystem9,SensorSystem13
#Animations
#Mount
Mount=NSM_quad_launcher_1
#Containers
NumberOfContainers=4
NumberOfHatchesPerContainer=1

Container1=Dummy
Container1_Position=0.0061,0.0390,-0.0073
Container1_Rotation=-20,-90,0
Container1_Hatch1=NSM_1_hatch_R1
Container1_OpenHatchAnimation=NSM_1_R1_Open
Container1_CloseHatchAnimation=NSM_1_R1_Close

Container2=Dummy
Container2_Position=0.0061,0.0390,0.0073
Container2_Rotation=-20,-90,0
Container2_Hatch1=NSM_1_hatch_L1
Container2_OpenHatchAnimation=NSM_1_L1_Open
Container2_CloseHatchAnimation=NSM_1_L1_Close

Container3=Dummy
Container3_Position=0.0032,0.0199,-0.0080
Container3_Rotation=-20,-90,0
Container3_Hatch1=NSM_1_hatch_R2
Container3_OpenHatchAnimation=NSM_1_R2_Open
Container3_CloseHatchAnimation=NSM_1_R2_Close

Container4=Dummy
Container4_Position=0.0032,0.0199,0.0080
Container4_Rotation=-20,-90,0
Container4_Hatch1=NSM_1_hatch_L2
Container4_OpenHatchAnimation=NSM_1_L2_Open
Container4_CloseHatchAnimation=NSM_1_L2_Close

#AreContainersRotatable=False
#Angles
FixVerticalLaunchAngle=20
PreferredArcs=180,360
#Loading
Ammunition=knm_nsm_1a
#Effects
#Other
HideWithActiveDamageModel=True
#SystemGroup=NSM_Launcher_1
SharedLaunchInterval=2
Collider=coll_NSM_1

[WeaponSystem17]  #NSM_quad_launcher 2
Type=Missile
SystemName=eu_NSM_quad_launcher
#Sensors
AssociatedSensors=SensorSystem2,SensorSystem3,SensorSystem4,SensorSystem5,SensorSystem6,SensorSystem7,SensorSystem8,SensorSystem9,SensorSystem13
#Animations
#Mount
Mount=NSM_quad_launcher_2
#Containers
NumberOfContainers=4
NumberOfHatchesPerContainer=1

Container1=Dummy
Container1_Position=0.0061,0.0390,-0.0073
Container1_Rotation=-20,-90,0
Container1_Hatch1=NSM_2_hatch_R1
Container1_OpenHatchAnimation=NSM_2_R1_Open
Container1_CloseHatchAnimation=NSM_2_R1_Close

Container2=Dummy
Container2_Position=0.0061,0.0390,0.0073
Container2_Rotation=-20,-90,0
Container2_Hatch1=NSM_2_hatch_L1
Container2_OpenHatchAnimation=NSM_2_L1_Open
Container2_CloseHatchAnimation=NSM_2_L1_Close

Container3=Dummy
Container3_Position=0.0032,0.0199,-0.0080
Container3_Rotation=-20,-90,0
Container3_Hatch1=NSM_2_hatch_R2
Container3_OpenHatchAnimation=NSM_2_R2_Open
Container3_CloseHatchAnimation=NSM_2_R2_Close

Container4=Dummy
Container4_Position=0.0032,0.0199,0.0080
Container4_Rotation=-20,-90,0
Container4_Hatch1=NSM_2_hatch_L2
Container4_OpenHatchAnimation=NSM_2_L2_Open
Container4_CloseHatchAnimation=NSM_2_L2_Close

#AreContainersRotatable=False
#Angles
FixVerticalLaunchAngle=20
PreferredArcs=1,179
#Loading
Ammunition=knm_nsm_1a
#Effects
#Other
HideWithActiveDamageModel=True
#SystemGroup=NSM_Launcher_2
SharedLaunchInterval=2
Collider=coll_NSM_1


SubModel221=NSM_quad_launcher_1                 
SubModel222=NSM_1_hatch_L1           
SubModel223=NSM_1_hatch_L2           
SubModel224=NSM_1_hatch_R1           
SubModel225=NSM_1_hatch_R2           
SubModel226=NSM_quad_launcher_2
SubModel227=NSM_2_hatch_L1           
SubModel228=NSM_2_hatch_L2           
SubModel229=NSM_2_hatch_R1           
SubModel230=NSM_2_hatch_R2


[NSM_quad_launcher_1]
ResourcesMeshFolder=assets/europack/models/
RootMesh=weapons.obj
Mesh=eu_NSM_quad_launcher
ResourcesMaterialFolder=assets/europack/materials/NSM/
Material=NSM_mat.ini
Position=-0.0600,0.1623,0.0250
Rotation=0,0,0

[NSM_1_hatch_L1]
ResourcesMeshFolder=assets/europack/models/
RootMesh=weapons.obj
Mesh=eu_NSM_hatch
ResourcesMaterialFolder=assets/europack/materials/NSM/
Material=NSM_mat.ini
Parent=NSM_quad_launcher_1
Position=-0.0247,0.0421,0.0073
Rotation=0,0,0

[NSM_1_hatch_L2]
ResourcesMeshFolder=assets/europack/models/
RootMesh=weapons.obj
Mesh=eu_NSM_hatch
ResourcesMaterialFolder=assets/europack/materials/NSM/
Material=NSM_mat.ini
Parent=NSM_quad_launcher_1
Position=-0.0276,0.0230,0.0080
Rotation=0,0,0

[NSM_1_hatch_R1]
ResourcesMeshFolder=assets/europack/models/
RootMesh=weapons.obj
Mesh=eu_NSM_hatch
ResourcesMaterialFolder=assets/europack/materials/NSM/
Material=NSM_mat.ini
Parent=NSM_quad_launcher_1
Position=-0.0247,0.0421,-0.0073
Rotation=0,0,0

[NSM_1_hatch_R2]
ResourcesMeshFolder=assets/europack/models/
RootMesh=weapons.obj
Mesh=eu_NSM_hatch
ResourcesMaterialFolder=assets/europack/materials/NSM/
Material=NSM_mat.ini
Parent=NSM_quad_launcher_1
Position=-0.0276,0.0230,-0.0080
Rotation=0,0,0

[NSM_quad_launcher_2]
ResourcesMeshFolder=assets/europack/models/
RootMesh=weapons.obj
Mesh=eu_NSM_quad_launcher
ResourcesMaterialFolder=assets/europack/materials/NSM/
Material=NSM_mat.ini
Position=0.0600,0.1623,0.0250
Rotation=0,180,0

[NSM_2_hatch_L1]
ResourcesMeshFolder=assets/europack/models/
RootMesh=weapons.obj
Mesh=eu_NSM_hatch
ResourcesMaterialFolder=assets/europack/materials/NSM/
Material=NSM_mat.ini
Parent=NSM_quad_launcher_2
Position=-0.0247,0.0421,0.0073
Rotation=0,0,0

[NSM_2_hatch_L2]
ResourcesMeshFolder=assets/europack/models/
RootMesh=weapons.obj
Mesh=eu_NSM_hatch
ResourcesMaterialFolder=assets/europack/materials/NSM/
Material=NSM_mat.ini
Parent=NSM_quad_launcher_2
Position=-0.0276,0.0230,0.0080
Rotation=0,0,0

[NSM_2_hatch_R1]
ResourcesMeshFolder=assets/europack/models/
RootMesh=weapons.obj
Mesh=eu_NSM_hatch
ResourcesMaterialFolder=assets/europack/materials/NSM/
Material=NSM_mat.ini
Parent=NSM_quad_launcher_2
Position=-0.0247,0.0421,-0.0073
Rotation=0,0,0

[NSM_2_hatch_R2]
ResourcesMeshFolder=assets/europack/models/
RootMesh=weapons.obj
Mesh=eu_NSM_hatch
ResourcesMaterialFolder=assets/europack/materials/NSM/
Material=NSM_mat.ini
Parent=NSM_quad_launcher_2
Position=-0.0276,0.0230,-0.0080
Rotation=0,0,0