[AmmunitionNames]
# ------------------ AAM ------------------

su_aa-10a=R-27R,,空对空,信号旗R-27R（AA-10A白杨）是苏联研发的一种半主动雷达制导中程空对空导弹，R-27开创性的使用了非常特殊的倒梯形翼，有效增强了此导弹的机动能力。

su_aa-10c=R-27ER,,空对空,信号旗R-27ER（AA-10C白杨）是苏联的半主动雷达制导中程空对空导弹，是R-27R的改进型，对导弹进行了增程处理，提高了导弹的射程。

su_aa-10c_navy=R-27EM,,空对空,信号旗R-27EM（AA-10C白杨）是苏联的半主动雷达制导中程空对空导弹，海军对R-27ER的改进型，其配备了更先进的导引头，进一步提高了导弹的远距离打击能力。

su_aa-10d=R-27ET,,空对空,信号旗R-27ET(AA-10D白杨)是苏联的半主动雷达制导中程空对空导弹，采用红外导引头，相比R-27ER，射程更近。

su_aa-11=R-73,,空对空,闪电机械R-73（AA-11射手）是苏联在1970~80年代研发的一种红外空对空导弹，R-73开创性的使用了矢量发动机，让导弹拥有远超同时期导弹的机动性，被认为是最具威胁的空对空导弹之一。

# ------------------ SAM ------------------

su_sa-n-11=2K22,通古斯卡,面对空/反水面,2K22通古斯卡（SA-N-11/SA-19巢鼬）是苏联研发的一种近程防空导弹，主要应用于卡什坦和通古斯卡弹炮一体化防空系统
# ---------- Anti-radar Missiles ---------

# ---------- Anti-ship Missiles ----------

su_ss-n-22_air=Kh-41,白蛉,反水面,Kh-41是P-270白蛉（SS-N-22日炙）的机载版本，相比P-270,Kh-41拥有更远的射程。

#-----------Land Strike only missiles---------

# ---------- Anti-sub  Missilies ----------

# ------------------ RBU ------------------
su_rgb-12=RBU-12000,龙卷风-2,深水炸弹,RBU-12000龙卷风-2是苏联的300毫米反潜火箭发射器，射程约为13000码。
# --------------- Torpedoes ---------------
# ------------------ Bombs -----------------

# ---------------- Sonobuoys ---------------
# ------------------ FFAR -----------------
# ------------------ MLRS -----------------
# ------------------ Guns -----------------
# ------------------ CIWS -----------------
# ----------- Noisemakers/Chaff -----------
# ----------------- Decoys ----------------
# ----------------- Special ----------------
# ----------------- Fueltanks ----------------