[Shader]
Path=Marmoset/Transparent/Cutout/Diffuse IBL

#[Properties]
_Color=Color,{}808080ff
_SpecColor=Color,{}ffffffff
_SpecInt=Float,1.0
_Shininess=Float,6.5
_Fresnel=Float,0.75

[Textures]
_MainTex=ships/mm_ffg_lupo/textures/railingstextures/railings.png
_SpecTex=ships/mm_ffg_lupo/textures/railingstextures/railings_spec.png
_BumpMap=ships/mm_ffg_lupo/textures/railingstextures/railings_nm.png