[Campaign]
Difficulty=1
BackgroundTraffic=Hidden	//Possible values: Enabled: traffic used and displayed, Hidden: traffic used but hidden on map, any other value: traffic is not used
MapLabelsFiles=campaigns/map_labels.ini
PatrolAreasFiles=campaigns/patrol_areas.ini
PortsFiles=campaigns/ports.ini,campaigns/soviet_ports_west.ini, campaigns/us_ports_atlantic.ini,campaigns/britishisles_ports.ini
SeaPointsFiles=campaigns/sea_points.ini, campaigns/baltic_sea_points.ini
SeaLinksFiles=campaigns/sea_links.ini, campaigns/baltic_sea_links.ini
AirportsFiles=campaigns/airports.ini
AirPointsFiles=campaigns/air_points.ini
AirLinksFiles=campaigns/air_links.ini
InstallationsFiles=campaigns/britishisles_installations.ini
CitiesFiles=campaigns/cities.ini, campaigns/soviet_cities_west.ini, campaigns/us_cities_atlantic.ini, campaigns/us_cities_pacific.ini, campaigns/us_cities_gulf.ini, campaigns/britishisles_cities.ini
LandPointsFiles=campaigns/land_points.ini
LandLinksFiles=campaigns/land_links.ini

[Language_en]
Name=Campaign Prototype 1
Description=A test of the text parsing system.

[Environment]
StartYear=1970
StartMonth=4
StartDay=1
StartHour=12
StartMinutes=0

[PlayerSide]
PlayerNation=US
FriendlyNations=UK,France,Germany,Belgium,Netherlands,Denmark,Canada,Iceland,Norway,Spain
PlayerObjectives=Hamburg,Wolfsburg,Bamberg,Regensburg

[PlayerSurfaceGroups]
NumberOfGroups=27

Group1Name=SUBRON 6
Group1Location=Port Norfolk
Group1Units=usn_ssn_sturgeon|20|Patrol, usn_ssn_sturgeon|21|Patrol, usn_ssn_sturgeon|23|Patrol, usn_ssn_sturgeon|24|Patrol, usn_ssn_sturgeon|25|False, usn_ssn_sturgeon|26|False, usn_ssn_sturgeon|28|False, usn_ssn_sturgeon|29|False, usn_ssn_sturgeon|31|False
Group2Name=SUBRON 8
Group2Location=Port Norfolk
Group2Units=usn_ssn_los_angeles|22|Patrol, usn_ssn_los_angeles|23|Patrol, usn_ssn_los_angeles|25|Patrol, usn_ssn_los_angeles|27|False, usn_ssn_sturgeon|35|False, usn_ssn_sturgeon|36|False
Group3Name=DESRON 2
Group3Location=Port Norfolk
Group3Units=usn_ddg_adams_early|2, usn_ddg_adams_early|3, usn_ddg_adams_early|4, usn_ddg_adams_early|5, usn_ff_knox|31, usn_ff_knox|33, usn_ff_knox|39, usn_ff_knox|41, usn_ff_knox|43
Group4Name=DESRON 10
Group4Location=Port Norfolk
Group4Units=usn_ddg_adams_late|3|Escort, usn_ddg_adams_late|9|Patrol, usn_ddg_kidd|1|False, usn_ddg_kidd|3|False, usn_dd_spruance|1|False, usn_dd_spruance|6|False, usn_dd_spruance|7|False, usn_dd_spruance|8|False, usn_dd_spruance|12|False, usn_dd_spruance|15|False, usn_dd_spruance|16|False, usn_dd_spruance|17|False, usn_dd_spruance|31|False, usn_ff_knox|30|False, usn_ff_knox|34|False, usn_ff_knox|40|False, usn_ff_knox|44|False, usn_ff_knox|46|False
Group6Name=PHIBRON 2
Group6Location=Port Norfolk
Group6Units=usn_lpd_austin|1|False, usn_lst_newport|1|False, usn_lst_newport|2|False, usn_lst_newport|3|False
Group7Name=PHIBRON 4
Group7Location=Port Norfolk
Group7Units=usn_lpd_austin|9|False, usn_lst_newport|10|False, usn_lst_newport|14|False
Group8Name=PHIBRON 6
Group8Location=Port Norfolk
Group8Units=usn_lpd_austin|10|False, usn_lst_newport|15|False, usn_lst_newport|16|False
Group9Name=PHIBRON 8
Group9Location=Port Norfolk
Group9Units=usn_lpd_austin|11|False, usn_lst_newport|18|False, usn_lst_newport|19|False

Group10Name=SUBDEVRON 12
Group10Location=Port New London
Group10Units=usn_ssn_los_angeles|2|Patrol, usn_ssn_los_angeles|3|Patrol, usn_ssn_los_angeles|4|Patrol, usn_ssn_los_angeles|6|False, usn_ssn_los_angeles|7|False
Group11Name=SUBGRU 2
Group11Location=Port New London
Group11Units=usn_ssn_los_angeles|8|Patrol, usn_ssn_los_angeles|12|False, usn_ssn_permit|6|Patrol, usn_ssn_permit|7|False
Group12Name=SUBRON 10
Group12Location=Port New London
Group12Units=usn_ssn_permit|8|Patrol, usn_ssn_permit|11|Patrol, usn_ssn_permit|12|False, usn_ssn_sturgeon|1|False, usn_ssn_sturgeon|2|Patrol, usn_ssn_sturgeon|4|Patrol, usn_ssn_sturgeon|7|Patrol, usn_ssn_sturgeon|8|False, usn_ssn_sturgeon|11|False
Group13Name=SUBRON 14
Group13Location=Port New London
Group13Units=usn_ssn_skipjack|1|Patrol, usn_ssn_skipjack|2|False, usn_ssn_skipjack|3|Patrol, usn_ssn_skipjack|4|False, usn_ssn_skipjack|5|False

Group14Name=SUBGRU 6
Group14Location=Port Charleston
Group14Units=usn_ssbn_franklin|1|Patrol, usn_ssbn_franklin|2|Patrol, usn_ssbn_franklin|4|Patrol, usn_ssbn_franklin|8|Patrol, usn_ssbn_franklin|10|Patrol, usn_ssbn_franklin|11|Patrol
Group15Name=SUBRON 4
Group15Location=Port Charleston
Group15Units=usn_ssn_los_angeles|13|Patrol, usn_ssn_los_angeles|15|False, usn_ssn_los_angeles|16|Patrol, usn_ssn_los_angeles|17|False, usn_ssn_los_angeles|19|False, usn_ssn_los_angeles|21|False, usn_ssn_sturgeon|12|False, usn_ssn_sturgeon|13|Patrol, usn_ssn_sturgeon|15|False, usn_ssn_sturgeon|16|False, usn_ssn_sturgeon|18|False, usn_ssn_sturgeon|19|Patrol
Group16Name=CRUDESGRU 2
Group16Location=Port Charleston
Group16Units=usn_cg_leahy|5|False, usn_cg_belknap|1|False
Group17Name=CRUDESGRU 8
Group17Location=Port Charleston
Group17Units=usn_cgn_virginia|1|False, usn_cgn_virginia|3|False, usn_cgn_virginia|4|False, usn_cg_leahy|2|False, usn_cg_belknap|2|False, usn_cg_belknap|8|False, usn_cg_ticonderoga|1|False, usn_cg_ticonderoga|2|False
Group18Name=DESRON 4
Group18Location=Port Charleston
Group18Units=usn_ddg_adams_early|10|False, usn_ddg_adams_late|4|False, usn_ff_garcia|4|False, usn_ff_garcia|8|False, usn_ff_knox|17|False, usn_ff_knox|24|False, usn_ff_knox|38|False
Group19Name=DESRON 6
Group19Location=Port Charleston
Group19Units=usn_dd_spruance|18|False, usn_dd_spruance|19|False, usn_dd_spruance|20|False, usn_dd_spruance|21|False, usn_dd_spruance|25|False, usn_dd_spruance|26|False, usn_dd_spruance|27|False, usn_ffg_oliver_hazard_perry_longhull|10|False, usn_ffg_oliver_hazard_perry_longhull|12|False, usn_ffg_oliver_hazard_perry_longhull|14|False, usn_ffg_oliver_hazard_perry_longhull|16|False, usn_ffg_oliver_hazard_perry_longhull|18|False, usn_ffg_oliver_hazard_perry_longhull|19|False, usn_ffg_oliver_hazard_perry_longhull|21|False, usn_ffg_oliver_hazard_perry_longhull|22|False, usn_ffg_oliver_hazard_perry_longhull|24|False
Group20Name=NRF
Group20Location=Port Charleston
Group20Units=usn_ff_knox|21|False

Group21Name=SUBRON 14
Group21Location=Holy Loch
Group21Units=usn_ssbn_franklin|3|Patrol, usn_ssbn_franklin|5|Patrol, usn_ssbn_franklin|6|Patrol, usn_ssbn_franklin|7|Patrol, usn_ssbn_franklin|9|Patrol, usn_ssbn_franklin|12|Patrol

Group22Name=NRF
Group22Location=Port Philadelphia
Group22Units=usn_ffg_oliver_hazard_perry|1|False, usn_ff_knox|10|False

Group23Name=CRUDESGRU 12
Group23Location=Mayport
Group23Units=usn_cg_leahy|4|False
Group24Name=DESRON 8
Group24Location=Mayport
Group24Units=usn_ffg_oliver_hazard_perry_longhull|1|False, usn_ffg_oliver_hazard_perry|5|False, usn_ffg_oliver_hazard_perry|7|False, usn_ffg_oliver_hazard_perry|12|False, usn_ffg_oliver_hazard_perry|13|False, usn_ffg_oliver_hazard_perry|14|False, usn_ffg_oliver_hazard_perry|16|False, usn_ffg_oliver_hazard_perry|18|False, usn_ffg_oliver_hazard_perry|20|False, usn_ffg_oliver_hazard_perry|21|False, usn_ffg_oliver_hazard_perry|23|False, usn_ffg_oliver_hazard_perry|24|False, usn_ffg_oliver_hazard_perry|2|False, usn_ffg_oliver_hazard_perry_longhull|6|False, usn_ffg_oliver_hazard_perry_longhull|9|False
Group25Name=DESRON 12
Group25Location=Mayport
Group25Units=usn_ddg_adams_early|1|False, usn_ddg_adams_early|9|False, usn_ddg_adams_late|5|False, usn_ff_garcia|3|False, usn_ff_garcia|6|False, usn_ff_knox|8|False, usn_ff_knox|29|False

Group5Name=SURFGRU 4
Group5Location=Port Newport
Group5Units=usn_ffg_oliver_hazard_perry|10|False, usn_ffg_oliver_hazard_perry_longhull|25|False, usn_ffg_oliver_hazard_perry_longhull|27|False, usn_ffg_oliver_hazard_perry_longhull|28|False, usn_ff_knox|5|False, usn_ff_knox|27|False, usn_ff_knox|28|False, usn_ff_knox|40|False, usn_ff_knox|42|False, usn_ff_knox|45|False

Group26Name=TESTGRU 1
Group26Location=Port Akureyri
Group26Units=usn_bb_iowa|1|False,usn_dd_spruance|2|False,usn_dd_spruance|3|False,usn_dd_spruance|4|False,usn_dd_spruance|5|False,usn_cg_belknap|3|False,usn_cg_belknap|4|False,usn_cg_belknap|5|False,usn_cg_belknap|6|False

Group27Name=TESTGRU 2
Group27Location=Port Charleston
Group27Units=usn_bb_iowa|1|Transit
Group27TransitLocation=Port Newport

[PlayerAirGroups]
NumberOfGroups=3
Group1Name=VAW-112
Group1Location=KNGU
Group1PatrolState=Patrol
Group1Units=usn_e-2c|1|4

Group2Name=VP-40
Group2Location=EGQS
Group2PatrolState=Patrol
Group2Units=usn_p-3c|1|8

Group3Name=TEST AIR TRANSIT
Group3Location=EGQS
Group3PatrolState=False
Group3Units=usn_p-3c|1|8
Group3TransitLocation=KNGU

[PlayerLandGroups]
NumberOfGroups=1
Group1Name=7 ADG
Group1Location=Norfolk
Group1Units=wp_sa-4_launcher|1

[EnemySide]
EnemyNations=Soviet,GDR,Belarus,Poland,Cuba

[EnemySurfaceGroups]
NumberOfGroups=7

Group1Name=Project 667 A
Group1Location=Port Murmansk
Group1Units=wp_ssbn_yankee|1|Patrol, wp_ssbn_yankee|2|Patrol, wp_ssbn_yankee|3|Patrol, wp_ssbn_yankee|4|Patrol, wp_ssbn_yankee|5|Patrol, wp_ssbn_yankee|6|Patrol, wp_ssbn_yankee|7|Patrol, wp_ssbn_yankee|8|Patrol, wp_ssbn_yankee|9|Patrol, wp_ssbn_yankee|10|Patrol, wp_ssbn_yankee|11|Patrol, wp_ssbn_yankee|12|Patrol, wp_ssbn_yankee|13|Patrol, wp_ssbn_yankee|14|Patrol, wp_ssbn_yankee|15|Patrol, wp_ssbn_yankee|16|Patrol, wp_ssbn_yankee|17|Patrol, wp_ssbn_yankee|18|Patrol, wp_ssbn_yankee|19|Patrol, wp_ssbn_yankee|20|Patrol, wp_ssbn_yankee|21|Patrol, wp_ssbn_yankee|22|Patrol, wp_ssbn_yankee|23|Patrol, wp_ssbn_yankee|24|Patrol

Group2Name=Project 667 B
Group2Location=Port Murmansk
Group2Units=wp_ssbn_delta3|1|Patrol, wp_ssbn_delta3|2|Patrol, wp_ssbn_delta3|3|Patrol, wp_ssbn_delta3|4|Patrol, wp_ssbn_delta3|5|Patrol, wp_ssbn_delta3|6|Patrol, wp_ssbn_delta3|7|Patrol, wp_ssbn_delta3|8|Patrol, wp_ssbn_delta3|9|Patrol, wp_ssbn_delta3|10|Patrol

Group3Name=AGIs
Group3Location=Port Havana
Group3Units=wp_agi_okean|1|Patrol, wp_agi_okean|2|Patrol, wp_agi_okean|3|Patrol, wp_agi_okean|4|Patrol, wp_agi_okean|5|Patrol, wp_agi_okean|6|Patrol, wp_agi_okean|7|Patrol, wp_agi_okean|8|Patrol, wp_agi_okean|9|Patrol, wp_agi_okean|10|Patrol, wp_agi_okean_mod|1|Patrol, wp_agi_okean_mod|2|Patrol, wp_agi_okean_mod|3|Patrol, wp_agi_okean_mod|4|Patrol, wp_agi_okean_mod|5|Patrol

Group4Name=LSTs
Group4Location=Port Severodvinsk
Group4Units=wp_bdk_ivan_rogov|1|False, wp_bdk_alligator|1|False, wp_bdk_alligator|2|False, wp_bdk_alligator|3|False, wp_bdk_alligator|4|False, wp_bdk_ropucha|1|False, wp_bdk_ropucha|2|False, wp_bdk_ropucha|3|False, wp_bdk_ropucha|4|False, wp_bdk_ropucha|5|False, wp_bdk_ropucha|6|False

Group5Name=Auxiliary
Group5Location=Port Murmansk
Group5Units=wp_vt_boris_chilikin|3|False, wp_vt_boris_chilikin|5|False, wp_vt_kazbek|1|False, civ_ms_andizhan|39|False, civ_ms_andizhan|40|False, civ_ms_andizhan|41|False, civ_ms_andizhan|42|False, civ_ms_roro_b|1|False, civ_ms_roro_b|2|False, civ_ms_roro_b|3|False, civ_ms_roro_b|4|False, civ_ms_roro_b|5|False, civ_ms_roro_b|6|False

Group6Name=Surface Combatants
Group6Location=Port Severodvinsk
Group6Units=wp_cv_orel|1|False, wp_rkr_kirov|1|False, wp_rkr_slava|1|False, wp_rkr_slava|2|False, wp_rkr_kresta1|1|False, wp_rkr_kresta1|2|False, wp_bdk_ropucha|2|False, wp_bpk_kresta2|1|False, wp_bpk_kresta2|2|False, wp_rkr_kynda|1|False, wp_rkr_kynda|2|False, wp_em_sovremenny|1|False, wp_em_sovremenny|2|False, wp_em_sovremenny|3|False, wp_em_sovremenny|4|False, wp_em_sovremenny|5|False, wp_em_sovremenny|6|False, wp_bpk_udaloy|1|False, wp_bpk_udaloy|2|False, wp_bpk_udaloy|3|False, wp_bpk_udaloy|4|False, wp_bpk_kanin|1|False, wp_bpk_kanin|2|False, wp_bpk_kanin|3|False, wp_bpk_kanin|4|False, wp_bpk_kara|1|False, wp_bpk_kara|2|False, wp_bpk_kashin|1|False, wp_bpk_kashin|2|False, wp_bpk_kashin|3|False, wp_bpk_kashin|4|False, wp_bpk_kashin|5|False, wp_bpk_kashin|6|False, wp_bpk_kashin|7|False, wp_kr_sverdlov|1|False, wp_kr_sverdlov|2|False, wp_kr_sverdlov|3|False, wp_kr_sverdlov|4|False, wp_kr_sverdlov|5|False, wp_mpk_grisha3|1|Patrol, wp_mpk_grisha3|2|Patrol, wp_mpk_grisha3|3|Patrol, wp_mpk_grisha3|4|False, wp_mpk_grisha3|5|False, wp_mpk_grisha3|6|False, wp_mpk_grisha3|7|False, wp_mpk_grisha3|8|False, wp_mpk_grisha3|9|False, wp_mpk_grisha3|10|False, wp_mpk_grisha3|11|False, wp_mpk_grisha3|12|False, wp_skr_krivak1|1|False, wp_skr_krivak1|2|False, wp_skr_krivak1|3|False, wp_skr_krivak1|4|False, wp_skr_krivak1|5|False, wp_skr_krivak1|6|False, wp_skr_krivak1|7|False, wp_skr_krivak2|1|False, wp_skr_krivak2|2|Patrol, wp_skr_krivak2|3|Patrol, wp_skr_krivak2|4|Patrol, wp_skr_krivak2|5|Patrol

Group7Name=SSNs
Group7Location=Port Murmansk
Group7Units=wp_ssn_victor1|1|False, wp_ssn_victor1|2|False, wp_ssn_victor1|3|False, wp_ssn_victor1|4|False, wp_ssn_victor1|5|False, 

[EnemyAirGroups]
NumberOfGroups=2
Group1Name=924 MRAP
Group1Location=XLMF
Group1PatrolState=False
Group1Units=wp_tu-22m2|2|24

Group2Name=514 RAP
Group2Location=XLMF
Group2PatrolState=Patrol
Group2Units=wp_il-38|1|16


[Missions]
NumberOfMissionFiles=8
MissionFile1=campaigns/campaign-proto-1/wp_invasion_sea_small.ini
#MissionFile2=campaigns/campaign-proto-1/wp_invasion_sea_smalldecoy.ini
MissionFile3=campaigns/campaign-proto-1/wp_invasion_land_small.ini
MissionFile4=campaigns/campaign-proto-1/nato_patrol_air_radar.ini
MissionFile5=campaigns/campaign-proto-1/nato_patrol_air_maritime.ini
MissionFile6=campaigns/campaign-proto-1/nato_patrol_surface_maritime.ini
MissionFile7=campaigns/campaign-proto-1/nato_invasion_land_small.ini
MissionFile8=campaigns/campaign-proto-1/wp_airfieldstrike_standoff_medium.ini

[Events]
NumberOfEventFiles=0
EventFile1=campaigns/campaign-proto-1/wp_invasion_iceland_win.ini
EventFile2=campaigns/campaign-proto-1/wp_invasion_iceland_fail.ini

[Objectives]
NumberOfObjectives=5

[Objective1]
ObjectiveSide=Red
ObjectiveType=Take

ObjectiveMissions=wp_invasion_sea_small
ObjectiveNodes=Port Reykjavik, Port Akureyri, Vik Beach
ObjectiveMissionsTriggered=1

NumberOfSecondaryMissions=2
SecondaryMission1=wp_airfieldstrike_standoff_medium
SecondaryMission1Nodes=BIKF
SecondaryMission1Triggered=1
SecondaryMission2=wp_airfieldstrike_standoff_medium
SecondaryMission2Nodes=BIAR
SecondaryMission2Triggered=1

NumberOfTriggers=1
TriggerCondition1=Start

EventWin=wp_invasion_iceland_win
EventFail=wp_invasion_iceland_fail

[Objective2]
ObjectiveSide=Red
ObjectiveType=Take
ObjectiveNodes=Reykjavik, Akureyri
ObjectiveMissions=wp_invasion_land_small
ObjectiveMissionsTriggered=2
NumberOfTriggers=1
TriggerCondition1=Held, Vik

[Objective3]
ObjectiveSide=Red
ObjectiveType=Take
ObjectiveNodes=Reykjavik
ObjectiveMissions=wp_invasion_land_small
ObjectiveMissionsTriggered=1
NumberOfTriggers=1
TriggerCondition1=Held, Akureyri

[Objective4]
ObjectiveSide=Blue
ObjectiveType=Take
ObjectiveNodes=Akureyri
ObjectiveMissions=nato_invasion_land_small
ObjectiveMissionsTriggered=1
NumberOfTriggers=1
TriggerCondition1=Lost, Akureyri

[Objective5]
ObjectiveSide=Blue
ObjectiveType=Take
ObjectiveNodes=Vik
ObjectiveMissions=nato_invasion_land_small
ObjectiveMissionsTriggered=1
NumberOfTriggers=1
TriggerCondition1=Lost, Vik