#!alias aircraft/spa_sh-60b_block1.ini
# ver. 20260428
#
[General]

GroundedPitchAngle=0.8    		   // VERSION LPD CLASE GALICIA (Por el ángulo de la pista) - this angle is the pitch (x) angle at ground with gears down
GroundPivot=0,-0.029,0.02          // defines the relative location of the landing gear
OnDeckPositionOffset=0,0,-0.023
GroundTaxiInterval=0.25
