[General]
HullnumberReference=Hullnumber
EmblemReference=Emblem
NationFlagReference=Flag1
#AllVariantsAreOfSameNation=False //Speeds up nation sorting. Only needed if there is more then 1 nation variants. Default is 'true'
GenericVariants=True //Variants specified are generic and multiple instances of the same variant could be spawned in same mission
NumberOfVariants=3

[Default]
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_nor
Nation=UK

[Variant1]
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=uk_fv_funnel
ResourcesLiveryFolder=ships/civ_fv_sterntrawler_b/uk/
LiveryTexture=civ_fv_sterntrawler_b_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_red_ensign
Nation=UK

[Variant2]
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=ddr_fv_funnel
ResourcesLiveryFolder=ships/civ_fv_sterntrawler_b/ddr/
LiveryTexture=civ_fv_sterntrawler_b_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_ddr
Nation=DDR

[Variant3]
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=none
ResourcesLiveryFolder=ships/civ_fv_sterntrawler_b/red/
LiveryTexture=civ_fv_sterntrawler_b_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_canada
Nation=Canada