[General]
HullnumberReference=Hullnumber
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfVariants=3

[Default]
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_civ_japan
Nation=Japan
ServiceDate=1976|2007

[Variant1]
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=jmsdf_ddg-168
ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=desron_15
ResourcesLiveryFolder=ships/jmsdf_ddg_tachikaze/
LiveryTexture=jmsdf_ddg_tachikaze_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_civ_japan
Nation=Japan
ServiceDate=1976|2007

[Variant2]
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=jmsdf_ddg-169
ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=desron_23
ResourcesLiveryFolder=ships/jmsdf_ddg_tachikaze/
LiveryTexture=jmsdf_ddg_tachikaze_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_civ_japan
Nation=Japan
ServiceDate=1979|2008

[Variant3]
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=jmsdf_ddg-170
ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=desron_7
ResourcesLiveryFolder=ships/jmsdf_ddg_tachikaze/
LiveryTexture=jmsdf_ddg_tachikaze_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_civ_japan
Nation=Japan
ServiceDate=1983|2010