[General]
HullnumberReference=Hullnumber
EmblemReference=Emblem
NationFlagReference=Flag1
AllVariantsAreOfSameNation=True //Speeds up nation sorting. Only needed if there is more then 1 nation variants. Default is 'true'
NumberOfVariants=15

[Default]  #Norway
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_nor
Nation=Norway
ServiceDate=1965|2000

[Variant1] #Norway
ResourcesHullnumberFolder=ships/materials/hullnumbers/pns_ss_han1
HullnumberTexture=transparent
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=ae-26
#ResourcesLiveryFolder=ships/rn_dd_c-class/
#LiveryTexture=usn_ae_kilauea_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_nor
Nation=Norway

[Variant2] #Norway
ResourcesHullnumberFolder=ships/materials/hullnumbers/pns_ss_han1
HullnumberTexture=transparent
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=ae-26
#ResourcesLiveryFolder=ships/rn_dd_c-class/
#LiveryTexture=usn_ae_kilauea_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_nor
Nation=Norway

[Variant3] #Norway
ResourcesHullnumberFolder=ships/materials/hullnumbers/pns_ss_han1
HullnumberTexture=transparent
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=ae-26
#ResourcesLiveryFolder=ships/rn_dd_c-class/
#LiveryTexture=usn_ae_kilauea_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_nor
Nation=Norway

[Variant4] #Norway
ResourcesHullnumberFolder=ships/materials/hullnumbers/pns_ss_han1
HullnumberTexture=transparent
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=ae-26
#ResourcesLiveryFolder=ships/rn_dd_c-class/
#LiveryTexture=usn_ae_kilauea_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_nor
Nation=Norway

[Variant5] #Norway
ResourcesHullnumberFolder=ships/materials/hullnumbers/pns_ss_han1
HullnumberTexture=transparent
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=ae-26
#ResourcesLiveryFolder=ships/rn_dd_c-class/
#LiveryTexture=usn_ae_kilauea_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_nor
Nation=Norway

[Variant6] #Norway
ResourcesHullnumberFolder=ships/materials/hullnumbers/pns_ss_han1
HullnumberTexture=transparent
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=ae-26
#ResourcesLiveryFolder=ships/rn_dd_c-class/
#LiveryTexture=usn_ae_kilauea_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_nor
Nation=Norway

[Variant7] #Norway
ResourcesHullnumberFolder=ships/materials/hullnumbers/pns_ss_han1
HullnumberTexture=transparent
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=ae-26
#ResourcesLiveryFolder=ships/rn_dd_c-class/
#LiveryTexture=usn_ae_kilauea_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_nor
Nation=Norway

[Variant8] #Norway
ResourcesHullnumberFolder=ships/materials/hullnumbers/pns_ss_han1
HullnumberTexture=transparent
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=ae-26
#ResourcesLiveryFolder=ships/rn_dd_c-class/
#LiveryTexture=usn_ae_kilauea_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_nor
Nation=Norway

[Variant9] #Norway
ResourcesHullnumberFolder=ships/materials/hullnumbers/pns_ss_han1
HullnumberTexture=transparent
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=ae-26
#ResourcesLiveryFolder=ships/rn_dd_c-class/
#LiveryTexture=usn_ae_kilauea_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_nor
Nation=Norway

[Variant10] #Norway
ResourcesHullnumberFolder=ships/materials/hullnumbers/pns_ss_han1
HullnumberTexture=transparent
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=ae-26
#ResourcesLiveryFolder=ships/rn_dd_c-class/
#LiveryTexture=usn_ae_kilauea_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_nor
Nation=Norway

[Variant11] #Norway
ResourcesHullnumberFolder=ships/materials/hullnumbers/pns_ss_han1
HullnumberTexture=transparent
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=ae-26
#ResourcesLiveryFolder=ships/rn_dd_c-class/
#LiveryTexture=usn_ae_kilauea_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_nor
Nation=Norway

[Variant12] #Norway
ResourcesHullnumberFolder=ships/materials/hullnumbers/pns_ss_han1
HullnumberTexture=transparent
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=ae-26
#ResourcesLiveryFolder=ships/rn_dd_c-class/
#LiveryTexture=usn_ae_kilauea_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_nor
Nation=Norway

[Variant13] #Norway
ResourcesHullnumberFolder=ships/materials/hullnumbers/pns_ss_han1
HullnumberTexture=transparent
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=ae-26
#ResourcesLiveryFolder=ships/rn_dd_c-class/
#LiveryTexture=usn_ae_kilauea_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_nor
Nation=Norway

[Variant14] #Norway
ResourcesHullnumberFolder=ships/materials/hullnumbers/pns_ss_han1
HullnumberTexture=transparent
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=ae-26
#ResourcesLiveryFolder=ships/rn_dd_c-class/
#LiveryTexture=usn_ae_kilauea_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_nor
Nation=Norway

[Variant15] #Norway
ResourcesHullnumberFolder=ships/materials/hullnumbers/pns_ss_han1
HullnumberTexture=transparent
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=ae-26
#ResourcesLiveryFolder=ships/rn_dd_c-class/
#LiveryTexture=usn_ae_kilauea_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_nor
Nation=Norway