[General]
HullnumberReference=Hullnumber
EmblemReference=Emblem
NationFlagReference=Flag1
AllVariantsAreOfSameNation=True //Speeds up nation sorting. Only needed if there is more then 1 nation variants. Default is 'true'
NumberOfVariants=2

[Default]
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_pak
Nation=Pakistan
ServiceDate=1979|2026

[Variant1] #Hashmat
ResourcesHullnumberFolder=ships/materials/hullnumbers/	
#HullnumberTexture=fr_s641
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=ae-26
#ResourcesLiveryFolder=ships/rn_dd_c-class/
#LiveryTexture=usn_ae_kilauea_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_pak
Nation=Pakistan
ServiceDate=1979

[Variant2] #Hurmat
ResourcesHullnumberFolder=ships/materials/hullnumbers/	
#HullnumberTexture=fr_s642
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=ae-26
#ResourcesLiveryFolder=ships/rn_dd_c-class/
#LiveryTexture=usn_ae_kilauea_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_pak
Nation=Pakistan
ServiceDate=1980
