[General]
HullnumberReference=Hullnumber
EmblemReference=Emblem
NationFlagReference=Flag1
AllVariantsAreOfSameNation=False //Speeds up nation sorting. Only needed if there is more then 1 nation variants. Default is 'true'
NumberOfVariants=3

[Default]  #France
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_pak
Nation=Pakistan
ServiceDate=1970|2006

[Variant1] #Pakistan
ResourcesHullnumberFolder=ships/materials/hullnumbers/	
HullnumberTexture=pns_S131
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=ae-26
#ResourcesLiveryFolder=ships/rn_dd_c-class/
#LiveryTexture=usn_ae_kilauea_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_pak
Nation=Pakistan
ServiceDate=1970|2006

[Variant2] #Pakistan
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=pns_S132
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=ae-26
#ResourcesLiveryFolder=ships/rn_dd_c-class/
#LiveryTexture=usn_ae_kilauea_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_pak
Nation=Pakistan
ServiceDate=1970|2006

[Variant3] #Pakistan
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=pns_S133
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=ae-26
#ResourcesLiveryFolder=ships/rn_dd_c-class/
#LiveryTexture=usn_ae_kilauea_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_pak
Nation=Pakistan
ServiceDate=1970|2006

#Variant4 removed as it's been trassfered to Albacora class
