[---------- General Data ----------]
[General]
UnitType=Vessel
HideIn=Encyclopedia,MissionEditor,Signatures
DefaultCameraDistance=1.5
MinCameraDistanceForeAft=0.15
MinCameraDistanceBroadside=0.15
CameraPivotHeight=0.03

Length=1                       // in meters
Beam=1                         // in meters

CompartmentsHeight=0.01        // Governs bouyancy compartment height and also missile aimpoint
ArmorType=None

[OpticalView]
Views=binocular_7x50,binocular_10x50,bridge_binocular_20x120_stab
DefaultView=binocular_7x50

[Physics]
#all damping values can go from 0 (max damping) up to 1 (no damping)
Displacement=0.1               // in tons

MaxForwardVelocity=0           // sets the max forward velocity
MaxBackwardVelocity=0          // sets the max backward velocity
LinearDrag=0.92                // this is for velocity damping (linear drag)
MaxAccelerationFactor=0
MinAccelerationFactor=0
TrimDepth=1                   // default trim depth in feet
TiltFactor=0.8                 // defines how strong the tilting will be

[Buoyancy]
Density=0.5                    // density of water is 1. Density < 1 means it will swim
OutOfWaterDrag=25.0            // drag for the water physics in case the vessel is above the water line
SubmergedDrag=25.0             // drag for the water physics in case the vessel is below the water line

[SensorData]
#Visual
VisualIdentificationRange=0.02   // Biggest range in nm at which this unit can be visually identified
Camouflaged=True                 // Ignores non-IR system bonuses and makes VID range equal max range
IRSignature=None
# Radar related (RCS => radar cross section)
RCS=VerySmall
# Sonar related

[---------- AI related ----------]
[AI]
Role=SeaMine

[SensorSystems]
#Presence of this section allows object to be detectable

[SeaMine]
WarheadType=0
Power=80
ImpactSize=Large                    // Impact size, can be small, medium, large, verylarge
Penetration=Always                  // can be minor, moderate, heavy, always
DecalClass=Standard                 // referenced in effects/decals.ini
ExplosionClass=UnderwaterExplosions
ExplosionOverwaterSplash=effects/splashes/emitters/splash_torpedo

[--------------------------- Mesh definitions ---------------------------]
[Models]
LODLevels=1
LOD1Distance=0.3  // nautical miles

############################################################
# AssetBundle related
############################################################

AssetBundleMeshes=/AssetBundles/StandaloneWindows/ships
AssetBundleMaterials=/AssetBundles/StandaloneWindows/ships
AssetBundleMesh=sea_mine
AssetBundleDamagedMesh=sea_mine
AssetBundleMaterial=
AssetBundleMeshHullCollider=sea_mine_coll_hull
############################################################

############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=ships/sea_mine/
ResourcesRoot=sea_mine
ResourcesMesh=sea_mine
ResourcesMaterialFolder=ships/materials/
ResourcesMaterial=modular_parts
############################################################
[Submodels]

[---------- Effects ----------]
[Particles]
SmallFireEffectClass=SmallShipFire_Small
ModerateFireEffectClass=ModerateShipFire_Small
SevereFireEffectClass=SevereShipFire_Small
SecondaryExplosionEffect=False
KillExplosionEffect=False
OilSlickEffect=False
SinkingBubblesEffect=False
BowWave=False
PropWash=False
Cavitation=False

[---------- Colliders ----------]
[Colliders]
UseKinematicCollision=False
NumberOfMeshColliders=1
NumberOfColliders=1

MeshCollider1=coll_hull

Collider1=coll_trigger

[coll_hull]
Collider=sea_mine_coll_hull

[coll_trigger]
Collider=Sphere
Position=0,0,0
Rotation=0,0,0
Scale=0.1,0.1,0.1
Layer=Default
