[General]
HullnumberReference=Hullnumber
EmblemReference=Emblem
NationFlagReference=Flag1
AllVariantsAreOfSameNation=False //Speeds up nation sorting. Only needed if there is more then 1 nation variants. Default is 'true'
NumberOfVariants=7

[Default]
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_s_vietnam
Nation=South_Vietnam
ServiceDate=1941|2000

#RVNN/RVNS variants:

[Variant1] //RVNS Trần Quang Khải (HQ-02)
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=rvnn_02
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/usn_avp_barnegat/
LiveryTexture=usn_avp_barnegat_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_s_vietnam
Nation=South_Vietnam

[Variant2] //RVNS Trần Nhật Duật (HQ-03)
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=rvnn_03
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/usn_avp_barnegat/
LiveryTexture=usn_avp_barnegat_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_s_vietnam
Nation=South_Vietnam

[Variant3] //RVNS Trần Bình Trọng (HQ-05)
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=rvnn_05
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/usn_avp_barnegat/
LiveryTexture=usn_avp_barnegat_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_s_vietnam
Nation=South_Vietnam

[Variant4] //RVNS Trần Quốc Toản (HQ-06)
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=rvnn_06
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/usn_avp_barnegat/
LiveryTexture=usn_avp_barnegat_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_s_vietnam
Nation=South_Vietnam

[Variant5] //RVNS Phạm Ngũ Lão (HQ-15) 
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=rvnn_15
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/usn_avp_barnegat/
LiveryTexture=usn_avp_barnegat_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_s_vietnam
Nation=South_Vietnam

[Variant6] //RVNS Lý Thường Kiệt (HQ-16)
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=rvnn_16
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/usn_avp_barnegat/
LiveryTexture=usn_avp_barnegat_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_s_vietnam
Nation=South_Vietnam

[Variant7] // RVNS Ngô Quyền (HQ-17)
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=rvnn_17
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/usn_avp_barnegat/
LiveryTexture=usn_avp_barnegat_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_s_vietnam
Nation=South_Vietnam