[General]
UnitType=Vessel
DefaultCameraDistance=0.75
MinCameraDistanceForeAft=0.6
MinCameraDistanceBroadside=0.4
CameraPivotHeight=0.07

Length=34.2                     // in meters
Beam=6.8                        // in meters

CompartmentsHeight=0.04         // Governs bouyancy compartment height and also missile aimpoint
ArmorType=None

[OpticalView]
Views=binocular_7x50,binocular_10x50,bridge_binocular_20x120_stab
DefaultView=binocular_7x50

[---------- Physics and Control ----------]
############################################################
# Physics definition
############################################################
[Physics]
# all damping values can go from 0 (max damping) up to 1 (no damping)
Displacement=241                // in tons

MaxForwardVelocity=48         // sets the max forward velocity
MaxBackwardVelocity=7.0         // sets the max backward velocity
LinearDrag=0.96                 // this is for velocity damping (linear drag)
MaxAccelerationFactor=2.69
MinAccelerationFactor=0.1

RudderTurnRate=10.0             // turn rate of the rudder in degrees per second
RudderForce=2.0                 // multiplicator defining how agile the ship can turn

#TiltFactor=-2.0                 // defines how strong the tilting will be, negative means it turns into the direction of turning
TiltFactor=-0.5
PitchFactor=0.0                 // defines how strong the pitch will be based on speed and acceleration
LiftFactor=0.75
LiftVelocityInKnots=15,25

MaxSeaStateForPitchAndLift=4

TrimDepth=0                     // default trim depth in feet
TrimAngle=0                     // default base trim angle (x-axis, so pitch)
CenterToKeelDist=0.0            // distance from the center of the mesh to the keel in Unity units
CenterOfMass=0,-0.01,0          // center of mass for physics
CavitationSpeed=4		 	  // defines the telegraph that, after exceeding it, the boat will begin to cavitate

[Buoyancy]
Density=0.5                     // density of water is 1. Density < 1 means it will swim
OutOfWaterDrag=25.0             // drag for the water physics in case the vessel is above the water line
SubmergedDrag=25.0              // drag for the water physics in case the vessel is below the water line

[SensorData]
#Visual
VisualIdentificationRange=7.5   // Biggest range in nm at which this unit can be visually identified
IRSignature=Meager
# Radar related (RCS => radar cross section)
RCS=Meager
# Sonar related
BaseNoise=150                   // base sound level in db at 1m distance
FlowNoise=1                     // additional flow noise per knot in db (
CavitationNoise=10               // additional noise for cavitation in db
BladesCount=4					 //number of blades on vessel's propulsion systems
MinNoiseClassificationTreshold=5 //in dBs, the minimal value of noise on sonar system to begin classification/identification process of this vessel
ElectricFrequency=60             //in Hz, typical values 50 or 60, 400 for Soviet Alfa class SSN

[---------- AI related ----------]
[AI]
UnitCostValue=100             // value for the unit cost for least valuable target checks
UnitScoreValue=1              // value for calculation of mission score

#Sensors
Radar_Capability=TBD
Sonar_Capability=TBD
AirRecon_Capability=TBD

#Offence
AAW_Capability=1
ASuW_Capability=2
ASW_Capability=0

#Defence
MissilesToSaturate=1      //AI will try to shoot missiles with this SaturationValue combined to kill this target
TorpedoesToSaturate=1     //AI will try to shoot torpedoes with this SaturationValue combined to kill this target

AMD_Capability=TBD    //Anti-Missile Defence
ATD_Capability=TBD      //Anti-Torpedo Defence

#Special
Role=FAC

[ControlSystem]
############################################################
# Control System (CIC or Bridge)
############################################################
Collider=coll_bridge

[MainPowerSystem]
############################################################
# Main Power System (engine room, boiler, reactor)
############################################################
Type=GasTurbine
HorsePower=20500
Collider=coll_engineroom

[PropulsionSystems]
############################################################
# Propulsion Systems
############################################################
NumberOfPropulsionSystems=2
[PropulsionSystem1]
Mount=Waterjet_Left
RotationDirection=Left
Collider=coll_prop_port

[PropulsionSystem2]
Mount=Waterjet_Right
RotationDirection=Right
Collider=coll_rudder_starboard

[RudderSystems]
NumberOfRudderSystems=2
############################################################
# Rudder Systems
############################################################
[RudderSystem1]
Mount=Rudder_Left
Collider=coll_rudder_port

[RudderSystem2]
Mount=Rudder_Right
Collider=coll_rudder_starboard

[---------- Sensor Systems ----------]
############################################################
# Sensor Systems
############################################################
[SensorSystems]
NumberOfSensorSystems=4

#---------- Visual ----------
[SensorSystem1] #Bridge
Type=Visual
SystemName=Optics
Mount=Dummy
MountPosition=0,0.096,0.105

#---------- Air and Air&Surface search radars ----------
#---------- Surface only search radars ----------

[SensorSystem2] #Nav Radar
Type=Radar
SystemName=Nav_Radar
Mount=Nav_Radar
Collider=coll_navradar

#---------- FC radars ----------
#SAM
#ASM
#Guns
#CIWS
[SensorSystem3] #MK92_FCS
#Sphere on top of the bridge
Type=Radar
SystemName=MK92_FCS
Mount=Dummy
MountPosition=0,0.155,0.35
SystemGroup=SG_FCRadarSAM
Collider=coll_mk92
#---------- Sonar ----------
#---------- ESM ----------
[SensorSystem4] #ESM
Type=ESM
SystemName=VesselESM
Mount=Dummy
MountPosition=0,0.23,-0.062
Collider=coll_esm

[---------- Weapon Systems ----------]
############################################################
# Weapon Systems
############################################################
[WeaponSystems]
NumberOfWeaponSystems=5

# ------------------ SAM ------------------
# ---------- Anti-ship Missilies ----------
[WeaponSystem1] #MK141 Port
Type=Missile
SystemName=MK141
#Sensors
#Animations
#Mount
Mount=Dummy
MountPosition=-0.0312,0.0646,-0.275
#Containers
NumberOfContainers=1
Container1=Dummy
Container1_Position=0,0,0
Container1_Rotation=-35,-20,0
#AreContainersRotatable=False
#Angles
FixVerticalLaunchAngle=35
PreferredArcs=1,179
#Loading
Ammunition=usn_rgm-84a
#Effects
#Other
HideWithActiveDamageModel=True
SharedLaunchInterval=5
Collider=coll_mk141_port

[WeaponSystem2] #MK141 Stbd
Type=Missile
SystemName=MK141
#Sensors
#Animations
#Mount
Mount=Dummy
MountPosition=0.0312,0.0646,-0.275
#Containers
NumberOfContainers=1
Container1=Dummy
Container1_Position=0,0,0
Container1_Rotation=-35,20,0
#Angles
FixVerticalLaunchAngle=35
PreferredArcs=-179,-1
#Loading
Ammunition=usn_rgm-84a
#Effects
#Other
HideWithActiveDamageModel=True
Collider=coll_mk141_starboard
# ---------- Anti-sub  Missilies ----------
# ------------------ RBU ------------------
# --------------- Torpedoes ---------------
# ------------------ Guns -----------------
[WeaponSystem3] #MK75 Gun
Type=Gun
SystemName=MK75
#Sensors
NumberOfAssociatedSensors=1
AssociatedSensor1=SensorSystem3
#Animations
#Mount
Mount=MK75_Turret
IsMountRotatable=True
#Containers
ContainerBase=MK75_Gun
NumberOfGuns=1
Gun1=MK75_Barrel
AreContainersRotatable=True
#Angles
FiringArcs=-120,120
ElevationArc=-15,85
RestAngles=0
#Loading
AssociatedMagazine=WeaponMagazineMK75
#Effects
#Other
Collider=coll_mk75
# ----------- Noisemakers/Chaff -----------
[WeaponSystem4] #Chaff
Type=Chaff
SystemName=Mk_36_SRBOC
#Sensors
#Animations
#Mount
Mount=Dummy
MountPosition=-0.5,1.1,2
#Containers
ContainerBase=Dummy
#Angles
#Loading
Ammunition=usn_rr144_chaff
#Effects
NumberOfEffects=6
DelayBetweenLaunches=0.1
EffectOffset=80,140,100
#Other
WorksStandalone=True

[WeaponSystem5] #Chaff
Type=Chaff
SystemName=Mk_36_SRBOC
#Sensors
#Animations
#Mount
Mount=Dummy
MountPosition=0.5,1.1,2
#Containers
ContainerBase=Dummy
#Angles
#Loading
Ammunition=usn_rr144_chaff
#Effects
NumberOfEffects=6
DelayBetweenLaunches=0.1
EffectOffset=80,140,100
#Other
WorksStandalone=True

[---------- WeaponMagazines ----------]

[WeaponMagazineMK75]
NumberOfAmmunitionTypes=1
Ammunition1=usn_cal_76mm
Ammunition1_Count=400
Collider=coll_mk75_magazine
ModuleType=MediumMagazine

[Compartments]
Compartment1FirePosition=0,0.04,0.14
Compartment2FirePosition=0,0.04,-0.11
[---------- Mesh definitions----------]
############################################################
# Main Model with collider
############################################################
[Models]
LODLevels=1
LOD1Distance=1.0  // nautical miles
############################################################
# AssetBundle related
############################################################
AssetBundleMeshes=/AssetBundles/StandaloneWindows/ships
AssetBundleMaterials=/AssetBundles/StandaloneWindows/ships
AssetBundleMesh=usn_phm_pegasus
AssetBundleDamagedMesh=usn_phm_pegasus_d
AssetBundleMaterial=usn_phm_pegasus_mat
AssetBundleMeshHullCollider=usn_phm_pegasus_coll_hull
############################################################

############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=ships/usn_phm_pegasus/
ResourcesRoot=usn_phm_pegasus
ResourcesMesh=usn_phm_pegasus
ResourcesDamagedMesh=usn_phm_pegasus_d
ResourcesMaterial=usn_phm_pegasus_mat
############################################################
[Submodels]

#---------- General ----------
General_1=Undersides
General_2=Trans
General_3=Parts
General_4=Flag1
General_5=Hullnumber
#---------- Main Systems ----------
Systems_1=Waterjet_Left
Systems_2=Waterjet_Right
Systems_3=Rudder_Left
Systems_4=Rudder_Right
#--------- Sensor Systems ----------
Sensors_1=Nav_Radar

#---------- Weapon Systems ----------
Weapons_1=MK75_Turret
Weapons_2=MK75_Gun
Weapons_3=MK75_Barrel

############################################################
#---------- General ----------
############################################################
[Undersides]
Mesh=usn_phm_pegasus_undersides
DamagedMesh=usn_phm_pegasus_undersides_d
ResourcesMaterialFolder=ships/materials/
Material=underside

[Trans]
Mesh=usn_phm_pegasus_trans
DamagedMesh=usn_phm_pegasus_trans_d
ResourcesMaterialFolder=ships/materials/
Material=trans

[Parts]
Mesh=usn_phm_pegasus_parts
DamagedMesh=usn_phm_pegasus_parts_d
ResourcesMaterialFolder=ships/materials/
Material=usn_parts

[Flag1]
Mesh=usn_phm_pegasus_animatedflag
ResourcesMaterialFolder=ships/materials/
Material=flag_soviet
Rotation=-90,0,90
HideWithActiveDamageModel=True

[Hullnumber]
Mesh=usn_phm_pegasus_hullnumber
ResourcesMaterialFolder=ships/materials/hullnumbers/
Material=hullnumber

############################################################
#---------- Main Systems ----------
############################################################
[Waterjet_Left]
Mesh=usn_phm_pegasus_waterjet
Material=usn_phm_pegasus_mat
Position=-0.0285,-0.003,-0.28

[Waterjet_Right]
Mesh=usn_phm_pegasus_waterjet
Material=usn_phm_pegasus_mat
Position=0.0285,-0.003,-0.28

[Rudder_Left]
Mesh=usn_phm_pegasus_rudder
Material=usn_phm_pegasus_mat
Position=-0.04,-0.009,-0.28

[Rudder_Right]
Mesh=usn_phm_pegasus_rudder
Material=usn_phm_pegasus_mat
Position=0.04,-0.009,-0.28

############################################################
#--------- Sensor Systems ----------
############################################################
[Nav_Radar]
Mesh=usn_phm_pegasus_navradar
ResourcesMaterialFolder=ships/materials/
Material=usn_parts
Position=0,0.185,-0.0413
Rotation=0,0,0
HideWithActiveDamageModel=True

############################################################
#--------- Weapon Systems ----------
############################################################
[MK75_Turret]
Mesh=usn_phm_pegasus_mk75_turret
ResourcesMaterialFolder=ships/usn_ffg_oliver_hazard_perry/
Material=usn_ffg_oliver_hazard_perry_mat
Position=0,0.05186,0.1712
Rotation=0,0,0

[MK75_Gun]
Mesh=usn_phm_pegasus_mk75_gun
ResourcesMaterialFolder=ships/usn_ffg_oliver_hazard_perry/
Material=usn_ffg_oliver_hazard_perry_mat
Parent=MK75_Turret
Position=0,0.0126,0.0026

[MK75_Barrel]
Mesh=usn_phm_pegasus_mk75_barrel
ResourcesMaterialFolder=ships/usn_ffg_oliver_hazard_perry/
Material=usn_ffg_oliver_hazard_perry_mat
Parent=MK75_Gun
Position=0,0,0

[---------- Effects ----------]
############################################################
# Wake and smoke
############################################################
[Particles]
SmallFireEffectClass=SmallShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=SmallShipFire	//ModerateShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=SmallShipFire	    //SevereShipFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffectClass=SecondaryExplosions
SecondaryExplosionEffectPosition=0,-0.05,0	//0,0,0
#kill explosion will be played to switch over to the damage model
KillExplosionEffect=effects/explosions/emitters/missile_hit_ship_3
KillExplosionEffectPosition=0,0.05,-0.1
OilSlickEffect=effects/damage/emitters/OilSlick_Medium
OilSlickEffectPosition=0,0,0
SinkingBubblesEffect=effects/ships/emitters/sinkingbubbles_ship
SinkingBubblesEffectPosition=0,0,0
DistressFlareEffect=None
DistressFlareEffectPosition=0,0.1,0

BowWave=ships/particles/bowwave_small
PropWash=ships/particles/propwash_small
Cavitation=ships/particles/usn_phm_pegasus_cavitation
FunnelSmoke=ships/particles/usn_phm_pegasus_smokeemitter
BowWavePosition=0,0,0.23
PropWashPosition=0,-0.02,-0.23
############################################################
# Foam
############################################################
[Foam]
HullFoamTexture=ships/particles/wake/Ceto_Hullwake
HullFoamPosition=0,0,0.19
HullFoamDuration=7.5
HullFoamSize=0.2
HullFoamSpacing=0.1
HullFoamExpansion=0.06
HullFoamMomentum=0
HullFoamSpin=0
HullFoamAlpha=2
HullFoamJitter=0.25

SternFoamTexture=ships/particles/wake/Ceto_Propwash
SternFoamPosition=0,0,-0.243
SternFoamDuration=25
SternFoamSize=0.25
SternFoamSpacing=0.1
SternFoamExpansion=0.025
SternFoamMomentum=0.01
SternFoamSpin=0
SternFoamAlpha=2
SternFoamJitter=0.25

OverlayHeightTexture=ships/particles/wake/bowwave_hm
OverlayHeightMaskTexture=ships/particles/wake/bowwave_hm
OverlayHeightMaxAlpha=0.1
OverlayNormalTexture=ships/particles/wake/bowwave_normal
OverlayNormalMaskTexture=ships/particles/wake/bowwave_normal
OverlayNormalMaxAlpha=10.0
OverlayFoamTexture=ships/particles/wake/bowwave_tx2
OverlayFoamMaskTexture=ships/particles/wake/bowwave_mask
OverlayFoamMaxAlpha=1.0
KelvinWaves=0.9,0.9
VelocityForMaxParticles=15  // velocity in knots from where on the particles shall show maximum effect

############################################################
# Sounds
############################################################

[Sounds]
SoundMode=1
EngineAudioClip=audio/ships/Ship-Turbine-Small
EngineAudioPosition=0,0,0
EngineAudioRollOff=Logarithmic
EngineAudioDistance=1,20
EngineAudioPitchRange=0.4,1
EngineAudioVolume=1
PropAudioClip=audio/ships/Ship-Propeller
PropAudioPosition=0,0,0
PropAudioRollOff=Logarithmic
PropAudioDistance=1,20
PropAudioPitchRange=0.1,0.6
PropAudioVolume=1
FlowAudioClip=audio/ships/Ship-Flow
FlowAudioPosition=0,0,0
FlowAudioRollOff=Logarithmic
FlowAudioDistance=1,20
FlowAudioPitch=1
FlowAudioVolume=1
#SonarAudioClip=audio/environment/sonar_ping   //TODO
SonarAudioClip=audio/environment/Sonar-MF
SonarAudioPosition=0,0,0
SonarAudioRollOff=Logarithmic
SonarAudioDistance=1,50
SonarAudioPitch=1
SonarAudioVolume=1

[---------- Colliders ----------]
############################################################
# Colliders definition
############################################################
[Colliders]
UseKinematicCollision=True

NumberOfMeshColliders=7
NumberOfColliders=13

MeshCollider1=coll_hull
MeshCollider2=coll_ph
MeshCollider3=coll_ss
MeshCollider4=coll_strut_f
MeshCollider5=coll_strut_l
MeshCollider6=coll_strut_r
MeshCollider7=coll_collider

#Movement&Control
Collider1=coll_bridge
Collider2=coll_engineroom
Collider3=coll_rudder_port
Collider4=coll_rudder_starboard
Collider5=coll_prop_port
Collider6=coll_prop_starboard

#Sensors
Collider7=coll_navradar
Collider8=coll_mk92
Collider9=coll_esm

#Weapons
Collider10=coll_mk75
Collider11=coll_mk75_magazine
Collider12=coll_mk141_port
Collider13=coll_mk141_starboard

#Other



[coll_hull]
Collider=usn_phm_pegasus_coll_hull

[coll_ss]
Collider=usn_phm_pegasus_coll_ss

[coll_ph]
Collider=usn_phm_pegasus_coll_ph

[coll_strut_f]
Collider=usn_phm_pegasus_coll_strut_f

[coll_strut_l]
Collider=usn_phm_pegasus_coll_strut_l

[coll_strut_r]
Collider=usn_phm_pegasus_coll_strut_r

[coll_collider]
Collider=usn_phm_pegasus_collider
Kinematic=True

[coll_bridge]
Collider=Box
Position=0,0.09,0.085
Rotation=0,0,0
Scale=0.065985,0.03,0.0212166


[coll_engineroom]
Collider=Box
Position=0,0.0063,-0.2267
Rotation=0,0,0
Scale=0.09768,0.03,0.14

[coll_rudder_port]
Collider=Box
Position=-0.03999585,-0.01639998,-0.2811082
Rotation=0,0,0
Scale=0.002,0.02,0.015

[coll_rudder_starboard]
Collider=Box
Position=0.0399,-0.0164,-0.2811
Rotation=0,0,0
Scale=0.002,0.02,0.015

[coll_prop_port]
Collider=Box
Position=-0.0292,-0.001,-0.2577
Rotation=0,0,0
Scale=0.005,0.005,0.12

[coll_prop_starboard]
Collider=Box
Position=0.0291988,-0.00100007,-0.2576954
Rotation=0,0,0
Scale=0.005,0.005,0.12

[coll_navradar]
Collider=Sphere
Position=0,0.185,-0.042
Rotation=0,0,0
Scale=0.04000001,0.04,0.04000001

[coll_esm]
Collider=Box
Position=0,0.2317,-0.0612
Rotation=0,44.99997,0
Scale=0.04254514,0.00826667,0.04364038

[coll_mk92]
Collider=Sphere
Position=0,0.1454,0.0009
Rotation=0,0,0
Scale=0.035,0.035,0.035

[coll_mk75]
Collider=Sphere
Position=0,0.0599,0.1681
Rotation=0,0,0
Scale=0.05,0.05,0.04999999

[coll_mk75_magazine]
Collider=Box
Position=0,0.02495,0.1669
Rotation=0,0,0
Scale=0.05999998,0.0280602,0.05999998

[coll_mk141_port]
Collider=Box
Position=-0.0318,0.0656,-0.2747
Rotation=0,250,34.99998
Scale=0.06403001,0.01611,0.02316

[coll_mk141_starboard]
Collider=Box
Position=0.0318,0.0656,-0.2747
Rotation=0,110,325
Scale=0.06403,0.01610659,0.0231615
