[General]
HullnumberReference=Hullnumber
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfVariants=19

[Default]
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet
ServiceDate=1962|1991

[Variant1]  #Komsomolets Ukrainy
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=wp_ddg_714
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/wp_bpk_kashin/
LiveryTexture=wp_bpk_kashin_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet
ServiceDate=1962|1991

[Variant2]  #Krasny Kavkaz
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=wp_ddg_710
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/wp_bpk_kashin/
LiveryTexture=wp_bpk_kashin_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet
ServiceDate=1963|1992

[Variant3]  #Krasny Krym
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=wp_ddg_711
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/wp_bpk_kashin/
LiveryTexture=wp_bpk_kashin_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet
ServiceDate=1964|1990

[Variant4]  #Obraztsovyy
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=wp_ddg_446
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/wp_bpk_kashin/
LiveryTexture=wp_bpk_kashin_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet
ServiceDate=1965|1990

[Variant5]  #Ognevoy
# Modernized into Pr. 61MP in 1971-1973
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=wp_ddg_296
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/wp_bpk_kashin/
LiveryTexture=wp_bpk_kashin_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet
ServiceDate=1965|1971

[Variant6]  #Odarennyy
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=wp_ddg_583
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/wp_bpk_kashin/
LiveryTexture=wp_bpk_kashin_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet
ServiceDate=1965|1974

[Variant7]  #Otvazhnyy
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=wp_ddg_530
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/wp_bpk_kashin/
LiveryTexture=wp_bpk_kashin_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet
ServiceDate=1966|1993

[Variant8]  #Provornyy
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=wp_ddg_724
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/wp_bpk_kashin/
LiveryTexture=wp_bpk_kashin_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet
ServiceDate=1967|1998

[Variant9]  #Reshitelnyy
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=wp_ddg_722
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/wp_bpk_kashin/
LiveryTexture=wp_bpk_kashin_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet
ServiceDate=1967|1989

[Variant10] #Skoryy
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=wp_ddg_729
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/wp_bpk_kashin/
LiveryTexture=wp_bpk_kashin_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet
ServiceDate=1968|1993

[Variant11] #Slavnyy
# Modernized into Pr. 61MP in 1973-1975
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=wp_ddg_462
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/wp_bpk_kashin/
LiveryTexture=wp_bpk_kashin_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet
ServiceDate=1966|1973

[Variant12] #Smelyy
# Modernized into Pr. 61MP in 1972-1974
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=wp_ddg_739
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/wp_bpk_kashin/
LiveryTexture=wp_bpk_kashin_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet
ServiceDate=1969|1972

[Variant13] #Smetlivy
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=wp_ddg_745
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/wp_bpk_kashin/
LiveryTexture=wp_bpk_kashin_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet
ServiceDate=1969|2020

[Variant14] #Smyshlenyy
# Modernized into Pr. 61MP in 1972-1974
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=wp_ddg_648
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/wp_bpk_kashin/
LiveryTexture=wp_bpk_kashin_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet
ServiceDate=1968|1972

[Variant15] #Soobrazitelnyy
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=wp_ddg_717
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/wp_bpk_kashin/
LiveryTexture=wp_bpk_kashin_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet
ServiceDate=1970|1993

[Variant16] #Sposobnyy
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=wp_ddg_522
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/wp_bpk_kashin/
LiveryTexture=wp_bpk_kashin_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet
ServiceDate=1971|1993

[Variant17] #Steregushchiy
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=wp_ddg_563
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/wp_bpk_kashin/
LiveryTexture=wp_bpk_kashin_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet
ServiceDate=1972|1997

[Variant18] #Strogiy
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=wp_ddg_574
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/wp_bpk_kashin/
LiveryTexture=wp_bpk_kashin_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet
ServiceDate=1964|1989

[Variant19] #Stroynyy
# Modernized into Pr. 61MP in 1975-1981
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=wp_ddg_610
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/wp_bpk_kashin/
LiveryTexture=wp_bpk_kashin_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet
ServiceDate=1966|1975