[General]
HullnumberReference=Hullnumber
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfVariants=3

[Default]
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet
ServiceDate=1975|1993

[Variant1]
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=wp_cv_069
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/wp_takr_kiev/
LiveryTexture=wp_takr_kiev_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet
ServiceDate=1975|1993

[Variant2]
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=wp_cv_025
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/wp_takr_kiev/
LiveryTexture=wp_takr_kiev_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet
ServiceDate=1978|1993
CustomAirGroup=True
wp_yak-38=Squadron3,16
#wp_ka-25=Squadron3,2
wp_ka-25ts=Squadron3,2
wp_ka-27=Squadron3,16

[Variant3]
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=wp_cv_137
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/wp_takr_kiev/
LiveryTexture=wp_takr_kiev_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet
ServiceDate=1982|1993
CustomAirGroup=True
wp_yak-38=Squadron4,16
#wp_ka-25=Squadron4,2
wp_ka-25ts=Squadron4,2
wp_ka-27=Squadron4,16