[ ------------------------------------ Israel Squadrons ------------------------------------ ]

[69th Sqn 'Hammers' IDF]
F-4E						Ok									24		Ramat David AB

[105th Sqn 'Scorpion' IDF]
F-4E						Ok									24		Hatzor AB

[107th Sqn 'Orange Tails' IDF]
F-4E						Ok									24		Hatzerim AB

[119th Sqn 'Bat' IDF ]
F-4E						Ok									24		Tel Nof AB

[201st Sqn 'The One' IDF]
F-4E						Ok									24		Hatzor AB

[ ------------------------------------ Iran Squadrons ------------------------------------ ]
##۰۱۲۳۴۵۶۷۸۹

# 1st Tactical Air Base , Tehran (Mehrabad)

[11th TFS]
F-4E						 									16		Mehrabad AB

[12th TFS]
F-4E						 									16		Mehrabad AB

[11th TTS]
C-130																	Mehrabad AB

[12th TTS]
C-130																	Mehrabad AB

## 2nd Tactical Air Base , Tabriz

[21st TFS]
F-5E						 									18		Tabriz AB

[22nd TFS]
F-5E						 									18		Tabriz AB

[23rd TFS]
F-5E						 									18		Tabriz AB

## 3rd Tactical Air Base, Hamadan (Shahrokhi)

[31st TFS]
F-4E																	Hamadan AB

3-6617
3-6618
3-6619
3-6620

3-6621
3-6622
3-6623
3-6624

3-6625
3-6626
3-6627
3-6628

3-6629
3-6630
3-6631
3-6632

[32nd TFS]
F-4E						 									16		Hamadan AB

[33rd TFS]
F-4E						 									16		Hamadan AB

[34th TFS]
F-4E						 									16		Hamadan AB

## 4th Tactical Air Base, Dezfull (Vahdati)

[41st TFS]
F-5E						 									18		Dezful AB

[42nd TFS]
F-5E						 									18		Dezful AB

[43rd TFS]
F-5E						 									18		Dezful AB

## 5th Tactical Air Base , Agha Jari (Omidieh) 

[51st TFS]
F-5E						 									20		Agha Jari AB

[52nd TFS]
F-5E						 									20		Agha Jari AB

[53rd TFS]
F-5E						 									20		Agha Jari AB

## 6th Tactical Air Base, Bushehr

[61st TFS]
F-4E						 									16		Bushehr AB

3-6633
3-6634
3-6635
3-6636

3-6637
3-6638
3-6639
3-6640

3-6641
3-6642
3-6643			
3-6644

3-6645
3-6646
3-6647
3-6648

[62nd TFS]
F-4E						 									16		Bushehr AB

[63rd TFS]
F-4D						 									16		Bushehr AB

3-601 -> 3-6686
3-611 -> 3-6697
3-616
3-632 -> 3-6718
# 7th Tactical Air Base, Shiraz

[71st ASWS]
P-3F																	Shiraz AB

[73rd TFTS]
F-14A						 									20		Shiraz AB

3-6001
3-6003
3-6004
3-6006

3-6010
3-6016
3-6021
3-6023

3-6027
3-6035
3-6036
3-6040

3-6043
3-6045
3-6047
3-6052

3-6055
3-6058
3-6061
3-6062

3-6063
3-6067
3-6070
3-6076

[71st TTS]
C-130																	Shiraz AB

[72nd TTS]
C-130																	Shiraz AB

# 8th Tactical Air Base , Isfahan ( Khatami ) 

[81st TFS]
F-14A						 									20		Esfahan AB

3-6002
3-6005
3-6009
3-6011

3-6014
3-6015
3-6017
3-6020

3-6024
3-6028
3-6029
3-6032

3-6034
3-6042
3-6044
3-6050

3-6051
3-6056
3-6060
3-6066

3-6071
3-6075
3-6078
3-6079

[82nd TFS]
F-14A						 									20		Esfahan AB

3-6007
3-6008
3-6012
3-6018

3-6019
3-6022
3-6025
3-6030

3-6031
3-6033
3-6037
3-6038

3-6039
3-6041
3-6046
3-6049

3-6054
3-6059
3-6064
3-6065

3-6068
3-6069
3-6072
3-6077

[85th TFS]
F-5A						 									20		Esfahan AB

## 9th Tactical Air Base, Bandar Abbas

[91st TFS]
F-4E						 									16		Bandar Abbas AB

3-6649
3-6650
3-6651
3-6652

3-6675
3-6676
3-6682
3-6683

3-6684
3-6685
3-6686
3-6687

3-6688
3-6689
3-6690
3-6691

[92nd TS]
P-3F																	Bandar Abbas AB

## 10th Tactical Air Base, Chabahar

[101st TFS]
F-5E						 									18		Chahbahar AB

[102nd TFS]
F-4E						 									16		Chahbahar AB

[103rd TFS]
F-4D						 									16		Chahbahar AB

## Notes:

Each F-5E Squadron has > 18 aircraft
Each F-4E Squadron has > 15 aircraft
Each F-14 Squadron has 20 aircraft

About Iranian Register Numbers , as you know IRIAF starts with 3-xxxx for fighters and 5-xxxx for cargo or transporters and etc , for Mig 29 is 61XX, so result is 3-61XX and about 2 other digits , i have seen pictures showing from 10 until 32 or maybe more , like 3-6110 to 3-6132 or more !

3-7316/3-7301/3-7059 & 3-7125/3-7140 & 3-7147


IRGC has 15-XXXX serial

## Iran Air Defence Command

Karadj 			- American Westinghouse radar
Tabriz 			- British radar (Marconi?)
Baboolsar		- British radar
Mashad			- British radar
ShahrAbad		- British Marconi radar
Dezful			- American radar (project Spellout)
Hamadan			- American radar (project Spellout)
Bushehr			- American radar (project Peace Ruby)
Isfahan			- American radar
Bandar Abbas	- American radar (project Peace Ruby)
Bandar Jask		- American radar (project Peace Ruby)
Kish Island		- American radar (project Peace Ruby)
Chah-Bahar		- Incomplete

Each site has Hawk/Rapier SAM, Oerlikon AAA, landing strip

[ ------------------------------------ Ecuador Squadrons ------------------------------------ ]

[2112 Sq.]
Mirage F1E				 											16		Taura AB


[ ------------------------------------ Greece Squadrons ------------------------------------ ]

[334th Sqn]
Mirage F1C				 											16		Tanagra AB

[335th Sqn]
#F-104G				 												16		Araxos AB

[336th Sqn]
#F-104G				 												16		Andravida AB

[337th Sqn]
F-4E				 												16		Larissa AB

[338th Sqn]
F-4E				 												16		Andravida AB

[339th Sqn]
F-4E				 												16		Andravida AB

[340th Sqn]
A-7H				 												19		Souda AB

[342nd Sqn]
Mirage F1C				 											16		Tanagra AB

[347th Sqn]
A-7H				 												19		Larissa AB

[ ------------------------------------ Iraq Squadrons ------------------------------------ ]


#Kirkuk------------------------------------

[No.1 FBS]
#Su-20				 												17		Al-Hurriyah AB

[No.5 FBS]
#Su-22M				 												17		Al-Hurriyah AB

[No.17 FS]
MiG-21MF			 												17		Al-Hurriyah AB

[No.44 FBS]
#Su-22M				 												17		Al-Hurriyah AB

#Mosul-------------------------------------

[No.11 FS Det.]
MiG-21MF			 												17		Firnas AB

#Habbaniyah--------------------------------

[No.39 FS]
MiG-23MS			 												17		Tahmmouz AB

[No.63 FS]
MiG-23MLA			 												17		Tahmmouz AB

[No.84 FRS]
MiG-25RB			 												17		Tahmmouz AB

[No.96 FS]
MiG-25PDS			 												17		Tahmmouz AB

[7th Sqn]
Tu-22B		 														17		Tahmmouz AB

[8th Sqn]
Tu-16K		 														17		Tahmmouz AB

#Baghdad-----------------------------------

[No.9 FS]
MiG-21PFM			 												17		Rashid AB

[No.11 FS]
MiG-21bis			 												17		Rashid AB

[No.9 FRS]
MiG-21RF			 												17		Rashid AB

[31st Sqn A Flt.]
Il-76MD			 													17		Saddam International

[31st Sqn A Flt.]
AN-12B		 														17		Rashid AB

#Qayyarah----------------------------------

[No.79 FS]
Mirage F1E			 												17		Qayyarah West

[No.92 FS]
Mirage F1E			 												17		Qayyarah West

#Al Kut------------------------------------

[No.3 FBS]
Su-7BMK			 													17		Abu Ubaida Al-Jarrah AB

[No.23 FBS]
MiG-23BN		 													17		Abu Ubaida Al-Jarrah AB

#Nasseriyah---------------------------------

[No.73 FS]
MiG-23MF		 													17		Ali Ibn Abu-Talib AB

[No.77 FBS]
MiG-23BN		 													17		Ali Ibn Abu-Talib AB

#Shoibiyah---------------------------------

[No.73 FS]
MiG-23MF		 													17		Ali Ibn Abu-Talib AB

[No.77 FBS]
MiG-23BN		 													17		Ali Ibn Abu-Talib AB

#Um-ol-Qassr--------------------------------

[No.1 NS]
SA-321	 															16		 NAS Um-ol-Qassr

[ ------------------------------------ Jordan Squadrons ------------------------------------ ]

[No.1 Sq.]
Mirage F1E				 											17		Azraq AFB

[No.2 Sq.]
F-5A				 												12		King Hussein AFB, Mafraq

[No.25 Sq.]
Mirage F1C				 											17		Azraq AFB

[ ------------------------------------ Kuwait Squadrons ------------------------------------ ]

[9th FS]
Mirage F1C				 											20		Ahmad Al-Jaber AB

[25th FS]
A-4KU			 													24		Ahmad Al-Jaber AB

[41st TS]
C130				 												4		Abdullah Al-Mubarak AB

[ ------------------------------------ Libya Squadrons ------------------------------------ ]

[1st FS]
MiG-25PD				 											16		Sabha AB

[2nd FS]
MiG-23MS				 											16		Al Bumbah AB

[3rd FS]
MiG-23MS				 											16		Okba Ben Nafi AB

[5th FS]
MiG-23MS				 											16		Ghardabiya AB

[9th FS]
Mirage F1A				 											20		Okba Ben Nafi AB

[10th FS]
Mirage F1E				 											20		Al-Watiya AB

[1st FBS]
Su-22M				 												20		Ghardabiya AB

[2nd FBS]
Su-22M				 												20		Al-Watiya AB

[1025th FS]
MiG-25PD				 											16		Jufra-Hun AB

[1055th FS]
MiG-25RBK				 											16		Ghardabiya AB

[1124th BS]
Tu-22																14		Sabha AB

[1st TS]
C130				 												8		Okba Ben Nafi AB

//Inventory, about 50% in storage as per US Department of State 1983

110 Mirage 5

9 SA-321

54 MiG-23MS

35 MiG-23BN

64 MiG-21bis

14 Tu-22

16 Mirage F1A

16 Mirage F1E

20 CH-47

[ ------------------------------------ Quatar Squadrons ------------------------------------ ]

[No.7 Sq.]
Mirage F1E				 											12		Doha International

[ ------------------------------------ South Africa Squadrons ------------------------------------ ]

[1 Sq.]
Mirage F1A				 											32		AFB Hoedspruit 

[2 Sq.]
Mirage III				 											16		AFB Hoedspruit 

[3 Sq.]
Mirage F1C				 											16		AFB Waterkloof 

[4 Sq.]
Atlas Impala				 										24		Lanseria Airport

[6 Sq.]
Cheetah E				 											16		AFB Louis Trichardt 

[6 Sq.]
Atlas Impala				 										24		AFB Port Elizabeth 

[8 Sq.]
Atlas Impala				 										24		AFB loemfontein 

[12 Sq.]
Canberra				 										 	16		AFB 

[16 Sq.]
Alouette III				 										16		AFB Port Elizabeth 

[17 Sq.]
Puma, Alouette III				 									16		AFB Swartkop 

[24 Sq.]
Buccaneer S.Mk 50						 							16		AFB Waterkloof 

[120 Sq.]
Crotale SAM						 											

[121 Sq.]
Tigercat SAM						 										

[122 Sq.]
Crotale SAM						 											

##Spain Squadrons---------------------------------------------------------------------

[141 Sqn]
Mirage F1CE				 											20		Los Llamos AB 

[142 Sqn]
Mirage F1CE				 											20		Los Llamos AB 

[462 Sqn]
Mirage F1EE				 											20		Gando AB 