[Language_en]
Name=Dassault Rafale
Description=by misaka/Llinqs

[Language_cn]
Name=达索阵风
Description=misaka/Llinqs 制作

[Compatibility]
;ApproximateVersion is the second check and will override all statements below. This checks MAJOR and MINOR match but will accept higher PATCH.
;Would recommend this as a default case for starters.
ApproximateVersion=0.8.0