[General]
Type=Container                       // can be Projectile, Missile, RBU, ASROC, Torpedo,AerialRocket,MLRS
Mass=122                                    // in kg. Used for aircraft. Container mass. Weapon mass is read from weapon ini

[Ammunition]
Ammunition=usn_gbu-39

NumberOfAttachments=4
AttachmentPosition1=0.001602,-0.003858,0.01171
AttachmentRotation1=0,0,180
AttachmentPosition2=-0.001602,-0.003858,-0.015422
AttachmentRotation2=0,0,180
AttachmentPosition3=0.001602,-0.003858,-0.015422
AttachmentRotation3=0,0,180
AttachmentPosition4=-0.001602,-0.003858,0.01171
AttachmentRotation4=0,0,180

SalvoFireAmount=2                     // number of shots fired

[---------- Mesh definitions----------]
############################################################
# Main Model with collider
############################################################
[Models]
############################################################
# AssetBundle related
############################################################
AssetBundleMeshes=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMaterials=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMesh=usn_rim-7
AssetBundleDamagedMesh=
AssetBundleMaterial=usn_rim-7_mat
AssetBundleMeshHullCollider=usn_rim-7_coll
############################################################
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=assets/models/ammunition/gbu-39/
ResourcesRoot=bru-61a.obj
ResourcesMesh=bru-61a
ResourcesMaterial=bru-61a_mat.ini


