[Models]

############################################################
# Internal Resources folder related
############################################################

ResourcesFolder=scenery/asian cities/
ResourcesRoot=asian_city_chunk_7
############################################################

NumberOfSubModels=2

SubModel1=Buildings
SubModel2=Trees
//SubModel3=Terrain

############################################################
# Scenery model parts
############################################################

[Buildings]
Mesh=asian_city_chunk_7
DamagedMesh=asian_city_chunk_7
ResourcesMaterialFolder=scenery/materials/
Material=asian_houses
//industrial_buildings_ne_us_1

[Trees]
Mesh=asian_city_chunk_7_trees
DamagedMesh=asian_city_chunk_7_trees
ResourcesMaterialFolder=scenery/materials/
Material=trees

//[Terrain]
//Mesh=asian_city_1_terrain
//DamagedMesh=asian_city_1_terrain
//ResourcesMaterialFolder=terrain/materials/
//Material=SEA_Spring

//[Decal]
//Mesh=module_industry_buildings_1_decal
//DamagedMesh=module_industry_buildings_1_decal
//ResourcesMaterialFolder=scenery/modular industry/
//Material=module_industry_decal