[Models]

############################################################
# Internal Resources folder related
############################################################

ResourcesFolder=scenery/bridges/
ResourcesRoot=bridge_generic_6part
############################################################

NumberOfSubModels=2

SubModel1=Deck
SubModel2=Trans


############################################################
# Scenery model parts
############################################################

[Deck]
Mesh=bridge_generic_6part
DamagedMesh=bridge_generic_6part
ResourcesMaterialFolder=scenery/materials/
Material=pier_tx

[Trans]
Mesh=bridge_generic_6part_trans
DamagedMesh=bridge_generic_6part_trans
ResourcesMaterialFolder=scenery/materials/
Material=trans