[Models]

############################################################
# Internal Resources folder related
############################################################

ResourcesFolder=scenery/modular industry/
ResourcesRoot=module_small_refinery_2
############################################################

NumberOfSubModels=4

SubModel1=Refinery
SubModel2=Parts
SubModel3=Trans
SubModel4=Decal

############################################################
# Scenery model parts
############################################################

[Refinery]
Mesh=module_small_refinery_2
DamagedMesh=module_small_refinery_2
ResourcesMaterialFolder=scenery/materials/
Material=refinery_main_tx

[Parts]
Mesh=module_small_refinery_2_industry
DamagedMesh=module_small_refinery_2_industry
ResourcesMaterialFolder=ships/materials/	
#scenery/materials/
Material=usn_parts

[Trans]
Mesh=module_small_refinery_2_trans
DamagedMesh=module_small_refinery_2_trans
ResourcesMaterialFolder=scenery/materials/
Material=trans

[Decal]
Mesh=module_small_refinery_2_decal
DamagedMesh=module_small_refinery_2_decal
ResourcesMaterialFolder=scenery/modular industry/
Material=module_industry_decal