[Models]

############################################################
# Internal Resources folder related
############################################################

ResourcesFolder=scenery/modular industry/
ResourcesRoot=module_industry_buildings_2_brown
############################################################

NumberOfSubModels=2

SubModel1=Buildings
SubModel2=Decal

############################################################
# Scenery model parts
############################################################

[Buildings]
Mesh=module_industry_buildings_2_brown
DamagedMesh=module_industry_buildings_2_brown
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1

[Decal]
Mesh=module_industry_buildings_2_brown_decal
DamagedMesh=module_industry_buildings_2_brown_decal
ResourcesMaterialFolder=scenery/modular industry/
Material=module_industry_decal