[Models]

############################################################
# Internal Resources folder related
############################################################

ResourcesFolder=scenery/persiangulf_towns/
ResourcesRoot=pg_fields3
############################################################

NumberOfSubModels=2

SubModel1=Trees
SubModel2=Decal

############################################################
# Scenery model parts
############################################################

[Trees]
Mesh=pg_fields3_trees
DamagedMesh=pg_fields3_trees
ResourcesMaterialFolder=scenery/materials/
Material=trees

[Decal]
Mesh=pg_fields3_decal
DamagedMesh=pg_fields3_decal
ResourcesMaterialFolder=scenery/persiangulf_towns/
Material=pg_fields_decal_mat