[Models]

############################################################
# Internal Resources folder related
############################################################

ResourcesFolder=scenery/persiangulf_towns/
ResourcesRoot=pg_harbour3
############################################################

NumberOfSubModels=11

SubModel1=Cargo
SubModel2=Containers
SubModel3=Cranes
SubModel4=Crew
SubModel5=Decal
SubModel6=Houses
SubModel7=Lighthouse
SubModel8=Pier
SubModel9=Trans
SubModel10=Trees
SubModel11=Warehouses
//SubModel2=Cleats
//SubModel8=Industry

############################################################
# Hull, Deck and other parts
############################################################

[Cargo]
Mesh=pg_harbour3_cargo
DamagedMesh=pg_harbour3_cargo
ResourcesMaterialFolder=ships/materials/
Material=ms_cargoatlas

[Containers]
Mesh=pg_harbour3_containers
DamagedMesh=pg_harbour3_containers
ResourcesMaterialFolder=scenery/materials/
//ships/materials/
Material=containers_tiled

//[Cleats]
//Mesh=pg_harbour3_cleats
//DamagedMesh=pg_harbour3_cleats
//ResourcesMaterialFolder=scenery/materials/
//Material=industrial_buildings_ne_us_1

[Cranes]
Mesh=pg_harbour3_cranes
DamagedMesh=pg_harbour3_cranes
ResourcesMaterialFolder=scenery/materials/
Material=harbour_crane_tx

[Crew]
Mesh=pg_harbour3_crew
DamagedMesh=pg_harbour3_crew
ResourcesMaterialFolder=ships/materials/
Material=crew_civ

[Decal]
Mesh=pg_harbour3_decal
DamagedMesh=pg_harbour3_decal
ResourcesMaterialFolder=scenery/persiangulf_towns/
Material=pg_harbours_decal_mat

[Houses]
Mesh=pg_harbour3_houses
DamagedMesh=pg_harbour3_houses
ResourcesMaterialFolder=scenery/persiangulf_towns/
Material=pg_buildings_tx

[Lighthouse]
Mesh=pg_harbour3_lighthouse //Stary: disable due to unknown status of model
DamagedMesh=pg_harbour3_lighthouse
ResourcesMaterialFolder=scenery/persiangulf_towns/
Material=pg_buildings_tx

//[Industry]
//Mesh=pg_harbour3_industry
//DamagedMesh=pg_harbour3_industry
//ResourcesMaterialFolder=scenery/materials/
//Material=industrial_buildings_ne_us_1

[Pier]
Mesh=pg_harbour3_pier
DamagedMesh=pg_harbour3_pier
ResourcesMaterialFolder=scenery/materials/
Material=pier_tx

[trans]
Mesh=pg_harbour3_trans
DamagedMesh=pg_harbour3_trans
ResourcesMaterialFolder=ships/materials/
Material=trans

[trees]
Mesh=pg_harbour3_trees
DamagedMesh=pg_harbour3_tress
ResourcesMaterialFolder=scenery/materials/
Material=pg_trees

[Warehouses]
Mesh=pg_harbour3_warehouses
DamagedMesh=pg_harbour3_warehouses
ResourcesMaterialFolder=scenery/persiangulf_towns/
Material=pg_industry_tx