[Models]

############################################################
# Internal Resources folder related
############################################################

ResourcesFolder=scenery/persiangulf_towns/
ResourcesRoot=pg_harbour5
############################################################

NumberOfSubModels=9

SubModel1=Cargo
SubModel2=Cranes
SubModel3=Crew
SubModel4=Decal
SubModel5=Houses_2
SubModel6=Pier
SubModel7=Trans
SubModel8=Trees
SubModel9=Warehouses

############################################################
# Hull, Deck and other parts
############################################################

[Cargo]
Mesh=pg_harbour5_cargo
DamagedMesh=pg_harbour5_cargo
ResourcesMaterialFolder=ships/materials/
Material=ms_cargoatlas

[Cranes]
Mesh=pg_harbour5_cranes
DamagedMesh=pg_harbour5_cranes
ResourcesMaterialFolder=scenery/materials/
Material=harbour_crane_tx

[Crew]
Mesh=pg_harbour5_crew
DamagedMesh=pg_harbour5_crew
ResourcesMaterialFolder=ships/materials/
Material=crew_civ

[Decal]
Mesh=pg_harbour5_decal
DamagedMesh=pg_harbour5_decal
ResourcesMaterialFolder=scenery/persiangulf_towns/
Material=pg_harbours_decal_mat

[Houses_2]
Mesh=pg_harbour5_houses2
DamagedMesh=pg_harbour5_houses2
ResourcesMaterialFolder=scenery/persiangulf_towns/
Material=pg_buildings_tx

[Pier]
Mesh=pg_harbour5_pier
DamagedMesh=pg_harbour5_pier
ResourcesMaterialFolder=scenery/materials/
Material=pier_tx

[trans]
Mesh=pg_harbour5_trans
DamagedMesh=pg_harbour5_trans
ResourcesMaterialFolder=ships/materials/
Material=trans

[trees]
Mesh=pg_harbour5_trees
DamagedMesh=pg_harbour5_tress
ResourcesMaterialFolder=scenery/materials/
Material=pg_trees

[Warehouses]
Mesh=pg_harbour5_warehouses
DamagedMesh=pg_harbour5_warehouses
ResourcesMaterialFolder=scenery/persiangulf_towns/
Material=pg_industry_tx