[Models]

############################################################
# Internal Resources folder related
############################################################

ResourcesFolder=scenery/persiangulf_towns/
ResourcesRoot=pg_shoretown4
############################################################

NumberOfSubModels=5

SubModel1=Decal
SubModel2=Trees
SubModel3=Houses
SubModel4=Houses2
SubModel5=Industry

############################################################
# MODEL PARTS
############################################################


[Decal]
Mesh=pg_shoretown4_decal
DamagedMesh=pg_shoretown4_decal
ResourcesMaterialFolder=scenery/persiangulf_towns/
Material=pg_towns2_decal_mat

[Trees]
Mesh=pg_shoretown4_trees
DamagedMesh=pg_shoretown4_trees
ResourcesMaterialFolder=scenery/materials/
Material=pg_trees

[Houses]
Mesh=pg_shoretown4_houses
DamagedMesh=pg_shoretown4_houses
ResourcesMaterialFolder=scenery/persiangulf_towns/
Material=pg_buildings_tx

[Houses2]
Mesh=pg_shoretown4_houses
DamagedMesh=pg_shoretown4_houses2
ResourcesMaterialFolder=scenery/persiangulf_towns/
Material=pg_buildings_tx

[Industry]
Mesh=pg_shoretown4_industry
DamagedMesh=pg_shoretown4_industry
ResourcesMaterialFolder=scenery/persiangulf_towns/
Material=pg_industry_tx