[AmmunitionNames]
# ------------------ AAM ------------------
# ------------------ SAM ------------------
usn_rim-116=RIM-116,RAM,SAM,The RIM-116 Rolling Airframe Missile is a short-range air defence missile that uses IR and laser guidance as part of the Mk49 short-range air defense missile system.


usn_rim-66h=RIM-66H,SM-2MR Blk II,SAM,The RIM-66H Standard Missile 2 is the VLS AEGIS version of the Block II SM-2 series, and is virtually identical to its Mk26 counterpart. The improved rocket motor improves all aspects of the missile, but primarily increases speed and over doubles the maximum effective range of the weapon, while increasing its high and low altitude performance.

usn_rim-162=RIM-162,ESSM,SAM,The RIM-162 Evolved Sea Sparrow Missile (ESSM) is a development of the RIM-7 Sea Sparrow missile used to protect ships from attacking missiles and aircraft.[8] ESSM is designed to counter supersonic maneuvering anti-ship missiles. ESSM also has the ability to be "quad-packed" in the Mark 41 Vertical Launch System, allowing up to four ESSMs to be carried in a single cell.
# ---------- Anti-radar Missiles ---------

# ---------- Anti-ship Missiles ----------
usn_rgm-84d=RGM-84D,Harpoon,ASM,The Harpoon is an American standoff anti-ship weapon used widely throughout NATO. The weapon has an active radar seeker that is activated after following a pre-programmed route. The RGM-84D variant has improved range of 120nm.

#-----------Land Strike only missiles---------

# ---------- Anti-sub  Missilies ----------

# ------------------ RBU ------------------


# --------------- Torpedoes ---------------

# ------------------ Bombs -----------------


# ---------------- Sonobuoys ---------------


# ------------------ FFAR -----------------


# ------------------ MLRS -----------------

# ------------------ Guns -----------------

# ------------------ CIWS -----------------


# ----------- Noisemakers/Chaff -----------


# ----------------- Decoys ----------------

# ----------------- Special ----------------


# ----------------- Fueltanks ----------------
