[AmmunitionNames]
# ------------------ AAM ------------------
dts_agm-158b-2=AGM-158B-2,JASSM-ER,对地攻击,由洛克希德·马丁公司研制的AGM-158B-2增程型联合空对地防区外导弹是一种隐身远程巡航导弹，采用涡轮风扇发动机，射程超过1900公里。它配备惯性导航+GPS+红外成像末制导系统和454公斤弹头，具备升级后的GPS接收机和抗干扰软件，能够对高价值目标实施防区外打击，并与多种战斗机兼容
dts_agm-158c-3=AGM-158C-3,LRASM-ER,反水面,AGM-158C-3 是洛克希德·马丁公司为美海空军研发的 AGM-158C 远程反舰导弹（LRASM）最新改进型，拥有更远射程、更强协同攻击与隐身突防能力。可从 B-1B、F/A-18E/F、F-15EX 等平台发射。
dts_agm-158c-sl=AGM-158C-SL,LRASM-SL,反水面,AGM-158C-SL 是洛克希德·马丁公司为美海空军研发的 AGM-158C 远程反舰导弹的水面发射型（Suface-Launch）。其后部绑定了一枚MK114火箭助推器，可以由MK41垂发单元发射。

dts_agm-183a=AGM-183A,ARRW,弹道导弹,AGM-183A（ARRW，空射快速响应武器）是美国洛克希德・马丁公司为空军研制的助推滑翔式高超音速导弹，全长约 5.89 米，重 2.27 吨，最大速度达 10 马赫，射程超 926 千米。它采用惯性 + GPS 复合制导，配备 68 千克高爆钨制破片战斗部
dts_agm-183a(w62)=AGM-183A(W62),ARRW,弹道导弹,AGM-183A（ARRW，空射快速响应武器）是美国洛克希德・马丁公司为空军研制的助推滑翔式高超音速导弹，这个版本搭载了一枚W62核弹头。请注意：不当使用可能会导致世界末日！

dts_b-61=B61,,核航弹,B61核弹是美国研发的战术核武器。其采用模块化设计及两级辐射内爆技术，爆炸当量可在0.3千吨至30万吨TNT间调节。体积小巧,可由B-2、F-16、F-35等机型搭载。