[Haifa]
Type=Port //Port automaticaly doesnt snap to terrain and does not flatten terrain around it
Role=Civil
LandUnit=port_haifa
VariantReference=Default
LoadoutVariant=Default
Location=32.826,35.0223,0
#SnapToTerrain=True
Heading=0
Nation=Israel
Movements=5
Destinations={Port Dublin,1,civ_}, {Port Belfast,1,civ_}, {Port Halifax,1,civ_}, {Port Norfolk,1,civ_}, {Port Boston,1,civ_}, {Port Saint John,1,civ_}, {Port Algiers,1,civ_}, {Port Barcelona,1,civ_}, {Port Valencia,1,civ_}, {Port Genoa,1,civ_}, {Port Alexandria,1,civ_}, {Port Naples,1,civ_}, {Port Tunis,1,civ_}, {Port Buenos Aires,1,civ_}, {Port Cape Town,1,civ_}, {Port Reykjavik,1,civ_}

[Tel Aviv]
Type=Port //Port automaticaly doesnt snap to terrain and does not flatten terrain around it
Role=Civil
LandUnit=port_telaviv
VariantReference=Default
LoadoutVariant=Default
Location=32.0636,34.7406,0
#SnapToTerrain=True
Heading=0
Nation=Israel
Movements=5
Destinations={Port Dublin,1,civ_}, {Port Belfast,1,civ_}, {Port Halifax,1,civ_}, {Port Norfolk,1,civ_}, {Port Boston,1,civ_}, {Port Saint John,1,civ_}, {Port Algiers,1,civ_}, {Port Barcelona,1,civ_}, {Port Valencia,1,civ_}, {Port Genoa,1,civ_}, {Port Alexandria,1,civ_}, {Port Naples,1,civ_}, {Port Tunis,1,civ_}, {Port Buenos Aires,1,civ_}, {Port Cape Town,1,civ_}, {Port Reykjavik,1,civ_}

[Ashdod]
Type=Port //Port automaticaly doesnt snap to terrain and does not flatten terrain around it
Role=Civil
LandUnit=port_ashdod
VariantReference=Default
LoadoutVariant=Default
Location=31.8436,34.6423,0	//31.8327, 34.6459,0
#SnapToTerrain=True
Heading=0
Nation=Israel
Movements=5
Destinations={Port Dublin,1,civ_}, {Port Belfast,1,civ_}, {Port Halifax,1,civ_}, {Port Norfolk,1,civ_}, {Port Boston,1,civ_}, {Port Saint John,1,civ_}, {Port Algiers,1,civ_}, {Port Barcelona,1,civ_}, {Port Valencia,1,civ_}, {Port Genoa,1,civ_}, {Port Alexandria,1,civ_}, {Port Naples,1,civ_}, {Port Tunis,1,civ_}, {Port Buenos Aires,1,civ_}, {Port Cape Town,1,civ_}, {Port Reykjavik,1,civ_}

[Latakia]
Type=Port //Port automaticaly doesnt snap to terrain and does not flatten terrain around it
Role=Civil
LandUnit=port_latakia
VariantReference=Default
LoadoutVariant=Default
Location=35.5265,35.759,0	//35.5208, 35.767,0
#SnapToTerrain=True
Heading=0
Nation=Israel
Movements=5
Destinations={Port Dublin,1,civ_}, {Port Belfast,1,civ_}, {Port Halifax,1,civ_}, {Port Norfolk,1,civ_}, {Port Boston,1,civ_}, {Port Saint John,1,civ_}, {Port Algiers,1,civ_}, {Port Barcelona,1,civ_}, {Port Valencia,1,civ_}, {Port Genoa,1,civ_}, {Port Alexandria,1,civ_}, {Port Naples,1,civ_}, {Port Tunis,1,civ_}, {Port Buenos Aires,1,civ_}, {Port Cape Town,1,civ_}, {Port Reykjavik,1,civ_}
