#Iranian ports

[Asaluyeh]
Type=Port //Port automaticaly doesnt snap to terrain and does not flatten terrain around it
Role=Civil
LandUnit=port_pg_asaluyeh
VariantReference=Default
LoadoutVariant=Default
Location=27.4752,52.6134,0
Nation=Iran
Heading=0

[Bandar Abbas]
Type=Port //Port automaticaly doesnt snap to terrain and does not flatten terrain around it
Role=Civil
LandUnit=port_pg_bandar_abbas
VariantReference=Default
LoadoutVariant=Default
Location=27.1422,56.2155,0
Nation=Iran
Heading=0

[Bandar Lengeh]
Type=Port //Port automaticaly doesnt snap to terrain and does not flatten terrain around it
Role=Civil
LandUnit=port_pg_bandar_lengeh
VariantReference=Default
LoadoutVariant=Default
Location=26.5633,54.8913,0
Nation=Iran
Heading=3

[Bushehr]
Type=Port //Port automaticaly doesnt snap to terrain and does not flatten terrain around it
Role=Civil
LandUnit=port_pg_bushehr
VariantReference=Default
LoadoutVariant=Default
Location=28.9846,50.817,0
Nation=Iran
Heading=0

[Bushehr Oil Terminal]
Type=Port //Port automaticaly doesnt snap to terrain and does not flatten terrain around it
Role=Civil
LandUnit=oil_terminal_1
VariantReference=Default
LoadoutVariant=Default
Location=28.9783,50.8683,40
Nation=Iran
Heading=140

[Bushehr Oil Terminal 2]
Type=Port //Port automaticaly doesnt snap to terrain and does not flatten terrain around it
Role=Civil
LandUnit=oil_terminal_3
VariantReference=Default
LoadoutVariant=Default
Location=28.9584,50.8883,40
Nation=Iran
Heading=125

[Fujairah]
Type=Port //Port automaticaly doesnt snap to terrain and does not flatten terrain around it
Role=Civil
LandUnit=port_pg_fujairah
VariantReference=Default
LoadoutVariant=Default
Location=25.1082,56.3537,0
Nation=Oman
Heading=0

[Kharg]
Type=Port //Port automaticaly doesnt snap to terrain and does not flatten terrain around it
Role=Civil
LandUnit=
VariantReference=Default
LoadoutVariant=Default
Location=29.2416, 50.3149
Nation=Iran
Heading=0

[Kish]
Type=Port //Port automaticaly doesnt snap to terrain and does not flatten terrain around it
Role=Civil
LandUnit=port_pg_kish
VariantReference=Default
LoadoutVariant=Default
Location=26.5756,53.9958,0
Nation=Iran
Heading=0

# Iraq
[Umm Quasr ]
Type=Port //Port automaticaly doesnt snap to terrain and does not flatten terrain around it
Role=Civil
LandUnit=port_pg_umm_quasr
VariantReference=Default
LoadoutVariant=Default
Location=29.9382,48.0127,0
Nation=Iraq
Heading=0

# Kuwait

[Kuwait]
Type=Port //Port automaticaly doesnt snap to terrain and does not flatten terrain around it
Role=Civil
LandUnit=port_pg_kuwait
VariantReference=Default
LoadoutVariant=Default
Location=29.362,47.9171,0
Nation=Kuwait
Heading=0

[Minah Al Ahmadi]
Type=Port //Port automaticaly doesnt snap to terrain and does not flatten terrain around it
Role=Civil
LandUnit=port_pg_minah_al_ahmadi
VariantReference=Default
LoadoutVariant=Default
Location=29.0552,48.1563,0
Nation=Kuwait
Heading=0

[Al Ahmadi Oil Terminal 1]
Type=Port //Port automaticaly doesnt snap to terrain and does not flatten terrain around it
Role=Civil
LandUnit=oil_terminal_3
VariantReference=Default
LoadoutVariant=Default
Location=29.0659,48.1564,20
Nation=Kuwait
Heading=150

[Al Ahmadi Oil Terminal 2]
Type=Port //Port automaticaly doesnt snap to terrain and does not flatten terrain around it
Role=Civil
LandUnit=oil_terminal_3
VariantReference=Default
LoadoutVariant=Default
Location=29.0904,48.1456,20
Nation=Kuwait
Heading=165

# Saudi Arabia

[Dammam]
Type=Port //Port automaticaly doesnt snap to terrain and does not flatten terrain around it
Role=Civil
LandUnit=port_pg_dammam
VariantReference=Default
LoadoutVariant=Default
Location=26.5172,50.1935,0
Nation=Saudi Arabia
Heading=0

