[Language_en]
Name=Sukhoi Su-27
Description=

[Language_cn]
Name=苏霍伊 苏-27
Description=

[Compatibility]
;ApproximateVersion is the second check and will override all statements below. This checks MAJOR and MINOR match but will accept higher PATCH.
;Would recommend this as a default case for starters.
ApproximateVersion=0.7.0