[General]
# Otomat MILAS
Type=Missile                             // can be Projectile, Missile, RBU, ASROC, Torpedo
TargetType=ASW                        // can be AAW, ASuW, ASW

Mass=800                               // in kg. Used for aircraft
AmmoPoints=2000                        // For Supply System. Defines "price" of ammunition based on mass, volume, complexity and availability

DefaultCameraDistance=0.6
MinCameraDistanceForeAft=0.29
MinCameraDistanceBroadside=0.29
CameraPivotHeight=0.0

[SensorData]
#Visual
VisualIdentificationRange=4  // at what range in nm this unit can be visually identified
IRSignature=Small
# Radar related (RCS => radar cross section)
RCS=VerySmall
# Sonar related
# Transient
TransientRCS=Small                    // Transient visibility on the radar
TransientVisualIdentificationRange=5  // Transient can be visually detected at this distance in nmi
TransientBaseNoise=200                // In db

[---------- Warhead Data ----------]
############################################################
# Warhead Data
############################################################
#Warhead Types:
#0 = Blast Fragmentation
#1 = Armor Piercing
#2 = HEAT
#3 = Illumination
#4 = Cluster
#5 = Runway Cratering

# Fuze Types: 0 = Impact Fuze, 1 = Proximity Fuze

[WarheadData]
WarheadType=0
ImpactSize=Large                       // Impact size, can be small, medium, large, verylarge
Penetration=Always                      // can be minor, moderate, heavy, always

# optional entry below, allows to switch to a second type of ammunition
# e.g. used for ASROC where a MK46 torpedo is spawned

[Submunition]
Ammunition=mm_mu_90
Offset=0.01,0,0    // offset of submunition to have it perfectly aligned with the "host"
SpawnTime=3

# References to the launchers are just used for positioning relative to the launcher of the missile

[---------- Guidance ----------]
# Guidance Types:
# 0 = None
# 1 = IR Homing
# 2 = Semi-Active Radar Homing
# 3 = Active Radar Homing
# 4 = Anti-Radiation Homing
# 5 = Laser-Homing
# 6 = TV-Homing
# 7 = Active Sonar Homing
# 8 = Passive Sonar Homing
# 9 = Wake Homing

[Guidance]
GuidanceType=0
MidCourseCorrection=0               // 0 = None, 1 = Radio Command, 2 = Wire Guided
InitialFlightPhaseDuration=3.0         // time in seconds where the missile moves straight on without guiding
PerformsSlightBallisticInitialFlight=True  // flag if the missile performs a slight ballistic flight curve during the initial phase (e.g. vessel launched harpoon)
#======================================== Flight Profile ===========================================================
#flight phase 1: loft-----------------------------------------------------------------------------------------------------------------
#1st stage of missile flight - high altitude
#flight phase 2: sea skimming---------------------------------------------------------------------------------------------------------
#2nd stage of missile flight - low altitude
SeaSkimmingAlt=656                     // height in feet for sea skimming
SeaSkimmingSubAlt=656                  // height in feet for sea skimming while using submunition
SeaSkimmingMaxDescentAngle=45.0        // Dive angle whlie going to sea skimming
SeaSkimmingNoseUp=1.0                  // "nose up" angle in degrees for sea skimming, reflecting the aerodynamics
SeaSkimmingStartDistToTarget=1000      // in N. miles.
#flight phase 3: final flight phase (e.g. terminal popup)------------------------------------------------------------------------------
#Pop-Up. Missile climbs to higher altitude before activating the seeker. Or in some cases going even lower
#flight phase 4: terminal approach------------------------------------------------------------------------------------------------------
#Last stage - missile activates seeker and locks on target
TerminalApproachDist=17.0              // in N. miles. Recommended to set this distance slightly less than the seeker range. For SAM must be slightly more than max range
SupportsBanking=True                   // if the missile will bank when turning
#========================================= Launch stats ============================================================
MaxVelocity=602.6                      // Maximum speed in knots
Acceleration=5.0                       // Acceleration factor
MaxTurnRate=15.0                       // Maximum turnrate in degrees per second
MinLaunchRange=5.4                     // Minimum launch range in nautical miles
MaxLaunchRange=29.7                   // Maximum launch range in nautical miles
LaunchReliability=97                   // The lower the value, the greater risk of misfire or accident (0...100)
#========================================     Seeker     ===========================================================
#Homing
#ECCM
#SelfDestruct
SelfDestructDelay=1.0                  // delay in seconds for self destruction

[---------- Mesh definitions----------]
[Models]
############################################################
# AssetBundle related
############################################################
AssetBundleMeshes=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMaterials=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMesh=usn_rim-7
AssetBundleDamagedMesh=
AssetBundleMaterial=usn_rim-7_mat
AssetBundleMeshHullCollider=usn_rim-7_coll
############################################################

############################################################
# Internal Resources folder related
############################################################


ResourcesFolder=assets/models/weapon/ammunition/mm_milas/
ResourcesRoot=mm_milas.obj
ResourcesMesh=Body
ResourcesMaterialFolder=weapons/it_otomat_mk1/
ResourcesMaterial=it_otomat_mk1_mat
#ResourcesMeshForLaunch=it_otomat_mk1_dummy
#ResourcesMeshCanister=it_otomat_mk1_dummy
#ResourcesMeshSwitchTime=0.2  // time in seconds after launch to switch from launch mesh to main mesh
############################################################

# Optional debris related stuff
DebrisProbability=95         // probability for debris to happen
ResourcesMeshForDebris=usn_ugm_84_d // optional debris mesh after destruction
DebrisPosition=0.05          // moves it in front of the warhead to have the trailing effect at correct position
DebrisLifeTime=10.0
DebrisVelocityDampening=0.99
DebrisHeightLossAdd=0.0005   // determines how quickly the debris loses height



[---------- Effects ----------]
# Effects are referenced in /effects/effects.ini when using an effects class
# e.g. either:
# BoosterEffect=effects/weapons/emitters/submarine_torpedo_launch
# or
# BoosterEffectClass=BoosterEffects  // this will be referenced in effects.ini

# possible values (optionally with suffix "Class")
# BoosterEffect, InFligheEffect, UnderwaterTrail, ParachuteEffect, TorpedoSurfaceSplash, HitWaterSplash
# DebrisTrail, DebrisSplash, SmallFireEffect, ModerateFireEffect, SevereFireEffect,
# HitAirExplosion, HitShipExplosion, HitObjectExplosion, HitGroundExplosion, HitDefaultExplosion
[Particles]
BoosterEffect=effects/weapons/emitters/otomat_launch_effect	//sam_small_airlaunch_effect
BoosterEffectPosition=0,0,0
InFlightEffect=effects/weapons/emitters/turbojet_sustainer_small
InFlightEffectPosition=0,0,-0.035
InFlightEffectStartTime=3.0  // in seconds, after that the Inflight Effect will be played if available
UnderwaterTrail=effects/weapons/emitters/aswtorpedo_cavitation_particle
UnderwaterTrailPosition=0,0,-0.045

HitShipExplosionClass=MediumShipHitExplosion
HitAirExplosionClass=MediumMissileExplosions
HitWaterSplashClass=SmallWaterSplashes
HitDefaultExplosionClass=MediumMissileExplosions
#DebrisTrailClass=DefaultMissileFire
DebrisTrail=effects/aircraft/emitters/helicopterfireeffect
DebrisSplashClass=SmallWaterSplashes

[---------- Colliders ----------]
[Colliders]
# creates the hit box for this object
Collider=col_main

[col_main]
Collider=Box
Position=0,0,-0.003
Rotation=0,0,0
Scale=0.005,0.005,0.045