[General]
UnitType=LandUnit
LandUnitSubType=OilRig //Supported values: Airbase,SAM,Installation,MobileUnit,Radar,Port, OilRig
DefaultCameraDistance=2
MinCameraDistanceForeAft=1
MinCameraDistanceBroadside=1
CameraPivotHeight=0.25

GroundOffset=0
AutoFlatten=False
MaskVegetation=False
# Hull armor: None, Minor, Moderate, Heavy
ArmorType=None
DamagePoints=200  //systems damage contribution substracted from this when systems destroyed, when becomes less than zero, the whole unit is considered being destroyed

[Tacview]
Tag=Sea+Watercraft

[AI]
UnitScoreValue=1               // value for calculation of mission score
Role=Target

[SensorData]
#Visual
VisualIdentificationRange=20
IRSignature=VeryLarge
# Radar related (RCS => radar cross section)
RCS=VeryLarge

[---------- Sensor Systems ----------]
[SensorSystems]
NumberOfSensorSystems=1
#---------- Visual ----------
[SensorSystem1] #Visual
Type=Visual
SystemName=Optics
Mount=Dummy
MountPosition=0,0.4,0
ModuleType=Bridge

[---------- HitZones ----------]
[HitZones]
NumberOfHitZones=6
[HitZone1]
SystemName=Spar
Collider=coll_hull
Integrity=400 //the number of hit points substracted from the overall damage points count when the system is destroyed

[HitZone2]
SystemName=Superstructure
Collider=coll_ss_1
Integrity=200 //the number of hit points substracted from the overall damage points count when the system is destroyed

[HitZone3]
SystemName=House
Collider=coll_house
Integrity=80 //the number of hit points substracted from the overall damage points count when the system is destroyed

[HitZone4]
SystemName=HouseDish
Collider=coll_house_dish
Integrity=80 //the number of hit points substracted from the overall damage points count when the system is destroyed

[HitZone5]
SystemName=HouseHelipad
Collider=coll_house_helipad
Integrity=100 //the number of hit points substracted from the overall damage points count when the system is destroyed

[HitZone6]
SystemName=Tower
Collider=coll_ss4
Integrity=50 //the number of hit points substracted from the overall damage points count when the system is destroyed

[--------------------------- Target Points definitions ---------------------------]
[TargetingData]
NumberOfTargetPoints=7

# Spar
TargetPointPosition1=0,0,0
TargetPointAssociatedSystems1=HitZone1
TargetPointPriority1=High
# Superstructure 1
TargetPointPosition2=0.218,0.267,0.189
TargetPointAssociatedSystems2=HitZone2
TargetPointPriority2=High
# Superstructure 2
TargetPointPosition3=-0.2168,0.2368,-0.0937
TargetPointAssociatedSystems3=HitZone2
TargetPointPriority3=High
# House
TargetPointPosition4=0.008,0.35,0.207
TargetPointAssociatedSystems4=HitZone3
TargetPointPriority4=Low
# HouseDish
TargetPointPosition5=0.208,0.35,-0.19
TargetPointAssociatedSystems5=HitZone4
TargetPointPriority5=Medium
# HouseHelipad
TargetPointPosition6=-0.2,0.391,0.167
TargetPointAssociatedSystems6=HitZone5
TargetPointPriority6=High
# Tower
TargetPointPosition7=0,0.48,0
TargetPointAssociatedSystems7=HitZone6
TargetPointPriority7=Low

[--------------------------- Mesh definitions ---------------------------]
[Models]
############################################################
# Internal Resources folder related
############################################################

ResourcesFolder=ground objects/civ_spar_rig/
ResourcesRoot=civ_spar_rig
ResourcesMesh=civ_spar_rig
ResourcesDamagedMesh=civ_spar_rig_d
ResourcesMaterialFolder=ground objects/civ_spar_rig/
ResourcesMaterial=civ_spar_rig_mat
############################################################

[Submodels]

SubModel1=Cables
SubModel2=Parts
SubModel3=Trans
SubModel4=Undersides


[Cables]
Mesh=civ_spar_rig_cables
Material=civ_spar_rig_mat
HideWithActiveDamageModel=True

[Parts]
Mesh=civ_spar_rig_parts
ResourcesMaterialFolder=ships/materials/
Material=modular_parts
#HideWithActiveDamageModel=True

[Trans]
Mesh=civ_spar_rig_trans
ResourcesMaterialFolder=ships/materials/
Material=trans
#HideWithActiveDamageModel=True

[Undersides]
Mesh=civ_spar_rig_undersides
ResourcesMaterialFolder=ships/materials/
Material=underside
#HideWithActiveDamageModel=True


[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=1
AmbientAudioClip=audio/ships/Ship-Turbine-Medium
AmbientAudioPosition=0,0,-0.35
AmbientAudioRollOff=Logarithmic
AmbientAudioDistance=1,20
AmbientAudioPitchRange=1.0,1.6
AmbientAudioVolume=0.0
AmbientAudioAudibility=Above  // layer of sound audibility: Above, Below, AboveAndBelow

[Particles]
SmallFireEffectClass=SmallShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=SmallShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=SmallShipFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffect=effects/explosions/emitters/missile_hit_ship
SecondaryExplosionEffectPosition=0,0,0

[---------- Colliders ----------]
[Colliders]
UseKinematicCollision=False
NumberOfMeshColliders=3
NumberOfColliders=3

MeshCollider1=coll_hull
MeshCollider2=coll_ss_1
MeshCollider3=coll_ss4

MeshCollider4=coll_ss2
MeshCollider5=coll_ss3


Collider1=coll_house
Collider2=coll_house_dish
Collider3=coll_house_helipad

Collider4=coll_tower
Collider5=coll_tower_top
Collider6=coll_superstructure
Collider7=coll_spar

[coll_hull]
Collider=civ_spar_rig_coll_hull
[coll_ss_1]
Collider=civ_spar_rig_coll_ss_1
[coll_ss2]
Collider=civ_spar_rig_coll_ss2
[coll_ss3]
Collider=civ_spar_rig_coll_ss3
[coll_ss4]
Collider=civ_spar_rig_coll_ss4

[coll_house]
Collider=Box
Position=0.0061,0.3599,0.2043
Rotation=0,0,0
Scale=0.15,0.1,0.105

[coll_house_dish]
Collider=Box
Position=0.2054,0.3547,-0.1842
Rotation=0,0,0
Scale=0.11,0.08,0.15

[coll_house_helipad]
Collider=Box
Position=-0.1973,0.3275,0.1526
Rotation=0,0,0
Scale=0.125,0.25,0.215

[coll_tower]
Collider=Box
Position=0,0.342,0
Rotation=0,0,0
Scale=0.09862312,0.2809993,0.114375

[coll_tower_top]
Collider=Box
Position=0,0.683,0
Rotation=0,0,0
Scale=0.04,0.4,0.04

[coll_superstructure]
Collider=Box
Position=0,0.2495,0
Rotation=0,0,0
Scale=0.59,0.12,0.59

[coll_spar]
Collider=Box
Position=0,-0.34,0
Rotation=0,0,0
Scale=0.2,1,0.2

