[General]
UnitType=LandUnit
LandUnitSubType=MobileUnit
IsMobile=True

DefaultCameraDistance=0.8
MinCameraDistanceForeAft=0.3
MinCameraDistanceBroadside=0.3
CameraPivotHeight=0.03

GroundOffset=0
AutoFlatten=False
MaskVegetation=True

Length=6.2                     // in meters
Beam=3.27                       // in meters
Range=202                      // in miles

# Hull armor: None, Minor, Moderate, Heavy
ArmorType=Moderate
DamagePoints=10  //systems damage contribution substracted from this when systems destroyed, when becomes less than zero, the whole unit is considered being destroyed

[Tacview]
Name=T-55-70
Tag=Ground+Vehicle+Armor+Tank

[Physics]
HorsePower=580
Mass=36                        // in tons

MaxForwardVelocity=27          // in knots
MaxBackwardVelocity=5          // in knots
Braking=10                     // knots/sec
TurnRate=20                    // in degrees per second

TurretBlowOffChance=0.65       // Chance to blow off "Turret" submodel.

[AI]
UnitScoreValue=0.5             // value for calculation of mission score
Role=Gun

[ControlSystem]
Collider=coll_hitbox  // makes unit destroyable
Integrity=10

[SensorData]
#Visual
VisualIdentificationRange=2.5  // Camouflaged  (x0.5)
IRSignature=Small
# Radar related (RCS => radar cross section)
RCS=Small

[---------- Sensor Systems ----------]
[SensorSystems]
NumberOfSensorSystems=1

#---------- Visual ----------
[SensorSystem1] #Optics
Type=Visual
SystemName=Optics
MountPosition=0,0.035,0

[---------- Weapon Systems ----------]
[WeaponSystems]
NumberOfWeaponSystems=2

[WeaponSystem1]  #100mm_D-10
Type=Gun
SystemName=100mm_D-10
#Sensors
#Animations
#Mount
Mount=Turret
IsMountRotatable=True
#Containers
ContainerBase=Gun
NumberOfGuns=1
Gun1=Barrel
AreContainersRotatable=True
#Angles
ElevationArc=-4,18
RestAngles=0
#Loading
AssociatedMagazine=WeaponMagazineGun
#Effects
#Other
MaxVelocityToFire=5
VIDIncrease=5  // In miles. Flat base VID increace when firing.

[WeaponSystem2]  #DSHK
Type=CIWS
SystemName=12.7mm_DSHK
#Sensors
#Animations
#Mount
Mount=MachinegunMount
IsMountRotatable=True
#Containers
ContainerBase=Machinegun
Gun=Machinegun
AreContainersRotatable=True
#Angles
ElevationArc=-5,45
RestAngles=0
#Loading
AssociatedMagazine=WeaponMagazineCIWS
#Effects
#Other
MaxVelocityToFire=10
VIDIncrease=3  // In miles. Flat base VID increace when firing.

[---------- WeaponMagazines ----------]
[WeaponMagazineGun]
NumberOfAmmunitionTypes=1
Ammunition1=wp_cal_100mm_d10
Ammunition1_Count=43

[WeaponMagazineCIWS]
NumberOfAmmunitionTypes=1
Ammunition1_Count=2000
Ammunition1=wp_cal_05in
ModuleType=SmallMagazine

[--------------------------- Mesh definitions ---------------------------]
[Models]
LODLevels=0
LOD1Distance=1  // nautical miles

ResourcesFolder=ground objects/wp_t-55_mod1970/
ResourcesRoot=wp_t-55_mod70
ResourcesMesh=wp_t-55_mod70_hull
ResourcesMaterial=wp_t-55_mod70_mat
############################################################

[Submodels]
Turret=Turret
Gun=Gun
Barrel=Barrel
MachinegunMount=MachinegunMount
Machinegun=Machinegun

[Turret]
Mesh=wp_t-55_mod70_turret
Material=wp_t-55_mod70_mat
Position=0,0.0204,0.0029

[Gun]
Mesh=wp_t-55_mod70_gun
Material=wp_t-55_mod70_mat
Parent=Turret
Position=0,0.0034,0.0131

[Barrel]
Mesh=wp_t-55_mod70_barrel
Material=wp_t-55_mod70_mat
Parent=Gun
Position=0,0,0

[MachinegunMount]
Mesh=wp_t-55_mod70_dshk_base
Material=wp_t-55_mod70_mat
Parent=Turret
Position=0.0061,0.0097,-0.0049

[Machinegun]
Mesh=wp_t-55_mod70_dshk_gun
ResourcesMaterialFolder=ships/materials/
Material=modular_parts
Parent=MachinegunMount
Position=0,0.0042,0.0036

[---------- Effects ----------]
[Particles]
SmallFireEffectClass=SmallShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=ModerateShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=SevereShipFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffect=effects/explosions/emitters/missile_hit_ship
SecondaryExplosionEffectPosition=0,0,0

DustEffect=effects/land units/emitters/vehicle_movement_dust
DustEffectPosition=0,0,0

SecondaryPopPrefab=effects/land units/emitters/secondary_pop
TurretCookOffEffect=effects/land units/emitters/turret_cook-off
TurretFireEffect=effects/land units/emitters/turret_fire
TurretFireEffectPosition=0,0.008,0

[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=1
AmbientAudioClip=audio/ships/Ship-Turbine-Small
AmbientAudioPosition=0,0,0
AmbientAudioRollOff=Logarithmic
AmbientAudioDistance=1,20
AmbientAudioPitchRange=1.0,1.6
AmbientAudioVolume=1.0
AmbientAudioAudibility=Above  // layer of sound audibility: Above, Below, AboveAndBelow

[---------- Colliders ----------]
[Colliders]
UseKinematicCollision=False
NumberOfMeshColliders=0
NumberOfColliders=2

Collider1=coll_hitbox
Collider2=coll_collider

[coll_hitbox]
Collider=Box
Position=0,0.0152,0.0005
Rotation=0,0,0
Scale=0.045,0.03,0.09

[coll_collider]
Collider=Box
Position=0,0.0028,-0.0023
Rotation=0,0,0
Scale=0.03,0.005,0.05
Layer=Default
