# AN/TPS-27 radar
[General]
UnitType=LandUnit
LandUnitSubType=Radar //Supported values: Airbase,SAM,Installation,MobileUnit,Radar,Port
DefaultCameraDistance=2.5
MinCameraDistanceForeAft=1.5
MinCameraDistanceBroadside=1.5
CameraPivotHeight=0.1

AutoFlatten=False
MaskVegetation=True
# Hull armor: None, Minor, Moderate, Heavy
ArmorType=Minor
DamagePoints=6  //systems damage contribution substracted from this when systems destroyed, when becomes less than zero, the whole unit is considered being destroyed

[Tacview]
Name=55G6
Tag=Ground+AntiAircraft

[AI]
UnitScoreValue=1               // value for calculation of mission score
Role=Radar

[SensorData]
#Visual
VisualIdentificationRange=6  // Camouflaged  (x0.5)
IRSignature=Small
# Radar related (RCS => radar cross section)
RCS=Small

[---------- Sensor Systems ----------]
############################################################
# Sensor Systems
############################################################
[SensorSystems]
NumberOfSensorSystems=2
#---------- Visual ----------
[SensorSystem1] #Bridge
# Bridge. Does not need сollider because we do not want ship to loose ability to VID targets
Type=Visual
SystemName=Optics
Mount=Dummy
MountPosition=0,0.032,0
ModuleType=Bridge

[SensorSystem2] #Radar
Type=Radar
SystemName=AN/TPS-27
Mount=Dummy
MountPosition=0,0.032,0
Collider=coll_radar,coll_radar_base
Integrity=6

[Models]
LODLevels=2
LOD1Distance=1  // nautical miles
LOD2Distance=2  // nautical miles
############################################################
# Internal Resources folder related
############################################################

ResourcesFolder=ground objects/nato_tps-27_radar/
ResourcesRoot=nato_tps-27_radar
ResourcesMesh=nato_tps-27
ResourcesDamagedMesh=nato_tps-27
ResourcesMaterialFolder=scenery/materials/
ResourcesMaterial=industrial_buildings_ne_us_1
############################################################

[Submodels]
SubModel1=Trans

[Trans]
Mesh=nato_tps-27_trans
ResourcesMaterialFolder=scenery/materials/
Material=trans
HideWithActiveDamageModel=False

[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=1
AmbientAudioClip=audio/ships/Ship-Turbine-Medium
AmbientAudioPosition=0,0.1,0
AmbientAudioRollOff=Logarithmic
AmbientAudioDistance=0.2,2
AmbientAudioPitchRange=1.0,1.6
AmbientAudioVolume=0.0
AmbientAudioAudibility=Above  // layer of sound audibility: Above, Below, AboveAndBelow

[Particles]
SmallFireEffectClass=SmallShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=SmallShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=SmallShipFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffect=effects/explosions/emitters/missile_hit_ship
SecondaryExplosionEffectPosition=0,0,0

[---------- Colliders ----------]
############################################################
# Colliders definition
############################################################
[Colliders]
NumberOfColliders=2
Collider1=coll_radar
Collider2=coll_radar_base

NumberOfMeshColliders=0
#MeshCollider1=coll_1

[coll_radar_base]
Collider=box
Position=0,0,0
Rotation=0,0,0
Scale=0.17,0.17,0.17

[coll_radar]
Collider=sphere
Position=0,0.095,0
Rotation=0,0,0
Scale=0.27,0.27,0.27

#[coll_1]
#Collider=wp_son-9_coll
