[General]
MaskVegetation=False
UnitType=LandUnit
HideIn=Encyclopedia,MissionEditor,Signatures
LandUnitSubType=Port //Supported values: Airbase,SAM,Installation,MobileUnit,Radar,Port
DisplayClassName=Oil Terminal Medium
DefaultCameraDistance=20.0
MinCameraDistanceForeAft=10
MinCameraDistanceBroadside=10
CameraPivotHeight=0.15

# Hull armor: None, Minor, Moderate, Heavy
ArmorType=None
DamagePoints=150	//systems damage contribution substracted from this when systems destroyed, when becomes less than zero, the whole unit is considered being destroyed

[Tacview]
Tag=Ground+Vehicle

[AI]
UnitScoreValue=5               // value for calculation of mission score
Role=Target

[SensorData]
#Visual
VisualIdentificationRange=15.0  // Biggest range in nm at which this unit can be visually identified
IRSignature=Medium
# Radar related (RCS => radar cross section)
RCS=Medium

############################################################
# Animation references (optional)
############################################################
[Animations]
NumberOfAnimationReferences=0
AnimationFile_1=animations_wp_sam_site_sa-5

[ControlSystem]
############################################################
# Control System (CIC)
############################################################
SystemGroup=SG_CIC
Collider=coll_platform_1_command
ModuleType=CIC
Integrity=50 //the number of hit points substracted from the overall damage points count when the system is destroyed
ArmorType=Minor
ResilenceModifier=3.0 //the multiplier that affects the required accumulated damage level for the system to achieve new damage tier. E.g. if this parameter is equal to 2.0 and Severe damage tier value is 15, the actual Severe damage value will be no less than 2 * 15 = 30

[---------- Sensor Systems ----------]
[SensorSystems]
NumberOfSensorSystems=1
#---------- Visual ----------
[SensorSystem1] #Bridge
# Bridge. Does not need SystemGroup and Collider because we do not want ship to loose ability to VID targets
Type=Visual
SystemName=Eyes
Mount=Dummy
MountPosition=0,0.026,0
ModuleType=Bridge
Integrity=0

[---------- Weapon Systems ----------]
############################################################
# Weapon Systems
############################################################
[WeaponSystems]
NumberOfWeaponSystems=0

[---------- HitZones ----------]
[HitZones]
NumberOfHitZones=5

[HitZone1]
#SystemGroup=SG_CIC
Collider=coll_platform_1_command
#ModuleType=HitZone
Integrity=25 //the number of hit points substracted from the overall damage points count when the system is destroyed
#ResilenceModifier=2.0 //the multiplier that affects the required accumulated damage level for the system to achieve new damage tier. E.g. if this parameter is equal to 2.0 and Severe damage tier value is 15, the actual Severe damage value will be no less than 2 * 15 = 30

[HitZone2]
#SystemGroup=SG_Pumping
Collider=coll_platform_main_refinery_pumping
#ModuleType=HitZone
Integrity=25 //the number of hit points substracted from the overall damage points count when the system is destroyed
#ResilenceModifier=3.0 //the multiplier that affects the required accumulated damage level for the system to achieve new damage tier. E.g. if this parameter is equal to 2.0 and Severe damage tier value is 15, the actual Severe damage value will be no less than 2 * 15 = 30

[HitZone3]
#SystemGroup=SG_Refinery
Collider=coll_platform_main_refinery
#ModuleType=HitZone
Integrity=50 //the number of hit points substracted from the overall damage points count when the system is destroyed
#ResilenceModifier=2.0 //the multiplier that affects the required accumulated damage level for the system to achieve new damage tier. E.g. if this parameter is equal to 2.0 and Severe damage tier value is 15, the actual Severe damage value will be no less than 2 * 15 = 30

[HitZone4]
#SystemGroup=SG_Processing
Collider=coll_platform_1_buildings
#ModuleType=HitZone
Integrity=35 //the number of hit points substracted from the overall damage points count when the system is destroyed
#ResilenceModifier=2.0 //the multiplier that affects the required accumulated damage level for the system to achieve new damage tier. E.g. if this parameter is equal to 2.0 and Severe damage tier value is 15, the actual Severe damage value will be no less than 2 * 15 = 30

[HitZone5]
#SystemGroup=SG_Aux_Pumping
Collider=coll_small_piece_1_pumps_building
#ModuleType=HitZone
Integrity=35 //the number of hit points substracted from the overall damage points count when the system is destroyed
#ResilenceModifier=2.0 //the multiplier that affects the required accumulated damage level for the system to achieve new damage tier. E.g. if this parameter is equal to 2.0 and Severe damage tier value is 15, the actual Severe damage value will be no less than 2 * 15 = 30

[---------- WeaponMagazines ----------]
############################################################
# Weapon Magazine Systems
############################################################

#Enemy units will use this local coordinates to aim their attacks to
[TargetingData]
NumberOfTargetPoints=5
TargetPointPosition1=10.288,0.235,-0.519
TargetPointAssociatedSystems1=HitZone1
TargetPointPriority1=High
TargetPointPosition2=1.215,0.0144,-1.54
TargetPointAssociatedSystems2=HitZone2
TargetPointPriority2=High
TargetPointPosition3=0.809,0.219,-2.557
TargetPointAssociatedSystems3=HitZone3
TargetPointPriority3=Medium
TargetPointPosition4=3.123,0.216,-3.483
TargetPointAssociatedSystems4=HitZone4
TargetPointPriority4=Medium
TargetPointPosition5=-0.217,0.213,-4.517
TargetPointAssociatedSystems5=HitZone5
TargetPointPriority5=High

[Models]
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=scenery/offshore_terminals/
ResourcesRoot=offshore_terminals
ResourcesMesh=offshore_terminal_2_piers
ResourcesMaterialFolder=scenery/materials/
ResourcesMaterial=pier_tx
############################################################

[Submodels]
#Offshore Oil Terminal 1 piers buildings etc meshes
Cargo=Cargo
Containers=Containers
Parts=Parts
#Piers=Piers
Piping=Piping
Refinery=Refinery
Trans=Trans
Warehouses=Warehouses


############################################################
# Scenery model parts
############################################################

[Cargo]
Mesh=offshore_terminal_2_cargo
DamagedMesh=offshore_terminal_2_cargo
ResourcesMaterialFolder=scenery/materials/
Material=ms_cargoatlas
Position=0,0,0
Rotation=0,0,0

[Containers]
Mesh=offshore_terminal_2_containers
DamagedMesh=offshore_terminal_2_containers
ResourcesMaterialFolder=scenery/materials/
Material=containers_tiled
Position=0,0,0
Rotation=0,0,0

[Parts]
Mesh=offshore_terminal_2_parts
DamagedMesh=offshore_terminal_2_parts
ResourcesMaterialFolder=ships/materials/
Material=usn_parts
Position=0,0,0
Rotation=0,0,0

[Piping]
Mesh=offshore_terminal_2_piping
DamagedMesh=offshore_terminal_2_piping
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1
Position=0,0,0
Rotation=0,0,0

#[Piers]
#Mesh=offshore_terminal_2_piers
#DamagedMesh=offshore_terminal_2_piers
#ResourcesMaterialFolder=scenery/materials/
#Material=pier_tx
#Position=0,0,0
#Rotation=0,0,0

[Refinery]
Mesh=offshore_terminal_2_refinery
DamagedMesh=offshore_terminal_2_refinery
ResourcesMaterialFolder=scenery/materials/
Material=refinery_main_tx
Position=0,0,0
Rotation=0,0,0

[Trans]
Mesh=offshore_terminal_2_trans
DamagedMesh=offshore_terminal_2_trans
ResourcesMaterialFolder=scenery/materials/
Material=trans
Position=0,0,0
Rotation=0,0,0

[Warehouses]
Mesh=offshore_terminal_2_warehouses
DamagedMesh=offshore_terminal_2_warehouses
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1
Position=0,0,0
Rotation=0,0,0

[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=1

[Particles]
SmallFireEffectClass=ModerateShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=SevereShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=OilTankFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffect=effects/explosions/emitters/bomb_hit_ground_large	//Ammo_ship_explosion_1
SecondaryExplosionEffectPosition=0,0,0

[---------- Colliders ----------]
############################################################
# Colliders definition
############################################################
[Colliders]
NumberOfColliders=28
Collider1=coll_pier_1
Collider2=coll_pier_2
Collider3=coll_platform_1
Collider4=coll_platform_1_command
Collider5=coll_platform_1_containers
Collider6=coll_platform_main
Collider7=coll_platform_1_buildings
Collider8=coll_platform_2
Collider9=coll_platform_2_buildings
Collider10=coll_platform_main_containers
Collider11=coll_platform_main_containers_2
Collider12=coll_platform_main_containers_3
Collider13=coll_platform_main_fueltanks
Collider14=coll_platform_main_refinery
Collider15=coll_platform_main_refinery_pumping
Collider16=coll_platform_main_refinery_stack_1
Collider17=coll_platform_main_refinery_stack_2
Collider18=coll_small_piece_1
Collider19=coll_small_piece_1_pumps_building
Collider20=coll_small_piece_2
Collider21=coll_dock_1
Collider22=coll_dock_end_1
Collider23=coll_dock_2
Collider24=coll_dock_end_2
Collider25=coll_dock_3
Collider26=coll_dock_end_3
Collider27=coll_dock_4
Collider28=coll_dock_end_4
Collider29=coll_dock_end_4

[coll_pier_1]
Collider=Box
Position=5.7,-0.29,0
Rotation=0,0,0
Scale=6.375058,0.6235644,0.575
[coll_pier_2]
Collider=Box
Position=13.9,-0.29,0
Rotation=0,0,0
Scale=6.098737,0.6235644,0.575
[coll_platform_1]
Collider=Box
Position=3.007,-0.29,-3.051
Rotation=0,0,0
Scale=0.5260161,0.6235644,2.036552
[coll_platform_1_command]
Collider=Box
Position=9.848,0.148,-0.583
Rotation=0,0,0
Scale=1.90656,0.2758434,0.2528749
[coll_platform_1_containers]
Collider=Box
Position=9.774,0.104,0.523
Rotation=0,0,0
Scale=1.6225,0.1854895,0.3528691
[coll_platform_main]
Collider=Box
Position=1.12,-0.29,0
Rotation=0,0,0
Scale=3.221277,0.6235644,8.104051
[coll_platform_1_buildings]
Collider=Box
Position=3.058,0.136,-2.989
Rotation=0,0,0
Scale=0.2441043,0.2572807,1.213257
[coll_platform_2]
Collider=Box
Position=3.014,-0.29,3.044
Rotation=0,0,0
Scale=0.5260161,0.6235644,2.036552
[coll_platform_2_buildings]
Collider=Box
Position=2.9919,0.05463542,2.2625
Rotation=0,0,0
Scale=0.2463697,0.08926384,0.2865378
[coll_platform_main_containers]
Collider=Box
Position=1.303,0.103,3.132
Rotation=0,0,0
Scale=0.8920755,0.185,1.631273
[coll_platform_main_containers_2]
Collider=Box
Position=0.335,0.106,2.875
Rotation=0,0,0
Scale=0.4661095,0.185,2.128811
[coll_platform_main_containers_3]
Collider=Box
Position=1.236,0.098,0.267
Rotation=0,0,0
Scale=1.039716,0.185,1.501477
[coll_platform_main_fueltanks]
Collider=Box
Position=2.423,0.183,-1.074
Rotation=0,0,0
Scale=0.1480421,0.3459978,0.3694277
[coll_platform_main_refinery]
Collider=Box
Position=1.521,0.161,-3.033
Rotation=0,0,0
Scale=1.881985,0.3027481,1.643953
[coll_platform_main_refinery_pumping]
Collider=Box
Position=1.865,0.101,-1.678
Rotation=0,0,0
Scale=1.452951,0.1778645,0.3575598
[coll_platform_main_refinery_stack_1]
Collider=Box
Position=1.618,0.452,-3.5972
Rotation=0,0,0
Scale=0.2117233,0.4393632,0.2234749
[coll_platform_main_refinery_stack_2]
Collider=Box
Position=0.6921,0.452,-2.4879
Rotation=0,0,0
Scale=0.2117233,0.4393632,0.2234749
[coll_small_piece_1]
Collider=Box
Position=-0.249,-0.29,-4.573
Rotation=0,0,0
Scale=0.5329648,0.6235644,1.021613
[coll_small_piece_1_pumps_building]
Collider=Box
Position=-0.322,0.154,-4.754
Rotation=0,0,0
Scale=0.2578217,0.2836244,0.5866448
[coll_small_piece_2]
Collider=Box
Position=10.703,-0.29,1.292
Rotation=0,0,0
Scale=0.2437339,0.6235644,0.9604945
[coll_dock_1]
Collider=Box
Position=-1.2911,-0.29,-1.91
Rotation=0,-89.9768,0
Scale=0.249924,0.6235644,1.594664
[coll_dock_end_1]
Collider=Box
Position=-2.140991,-0.29,-1.909359
Rotation=0,-89.9768,0
Scale=3.021081,0.6235644,0.3775426
[coll_dock_2]
Collider=Box
Position=-1.29,-0.29,3.958012
Rotation=0,-89.9768,0
Scale=0.249924,0.6235644,1.594664
[coll_dock_end_2]
Collider=Box
Position=-2.138857,-0.29,3.948647
Rotation=0,-89.9768,0
Scale=3.021081,0.6235644,0.3775426
[coll_dock_3]
Collider=Box
Position=8.003,-0.29,-1.828
Rotation=0,0,0
Scale=0.249924,0.6235644,3.173461
[coll_dock_end_3]
Collider=Box
Position=8.003001,-0.29,-3.368
Rotation=0,0,0
Scale=3.021081,0.6235644,0.3775426
[coll_dock_4]
Collider=Box
Position=8.006,-0.29,1.843
Rotation=0,-179.9997,0
Scale=0.249924,0.6235644,3.173461
[coll_dock_end_4]
Collider=Box
Position=8.016006,-0.29,3.382999
Rotation=0,-179.9997,0
Scale=3.021081,0.6235644,0.3775426
