[General]
MaskVegetation=False
UnitType=LandUnit
HideIn=Encyclopedia,MissionEditor,Signatures
LandUnitSubType=Port
DefaultCameraDistance=18.0
MinCameraDistanceForeAft=18
MinCameraDistanceBroadside=18
CameraPivotHeight=0.15
ArmorType=None
DamagePoints=160

[Tacview]
Tag=Ground+Vehicle

[AI]
UnitScoreValue=10
Role=Port
[SensorData]
VisualIdentificationRange=15.0
IRSignature=Large
RCS=SemiSmall
BaseNoise=150
FlowNoise=1
CavitationNoise=5
[SensorSystems]
NumberOfSensorSystems=1
[SensorSystem1]
Type=Visual
SystemName=Optics
MountPosition=0,0.175,0

# HITZONES AND TARGETPOINTS #####################################################################
[---------- HitZones ----------]
[HitZones]
NumberOfHitZones=5

[HitZone1]
Collider=coll_mil_pt_3_buildings_1
Integrity=40

[HitZone2]
Collider=coll_mil_pt_3_buildings_6
Integrity=40

[HitZone3]
Collider=coll_port_small_fueltanks_4
Integrity=30

[HitZone4]
Collider=coll_port_small_fueltanks_2
Integrity=30

[HitZone5]
Collider=coll_port_small_warehouses_3
Integrity=30

#Enemy units will use this local coordinates to aim their attacks to
[TargetingData]
NumberOfTargetPoints=5
TargetPointPosition1=7.17,0.1,-33.55
TargetPointAssociatedSystems1=HitZone1
TargetPointPriority1=High
TargetPointPosition2=8.82,0.1,-40.99
TargetPointAssociatedSystems2=HitZone2
TargetPointPriority2=High
TargetPointPosition3=6.582,0.1,16.515
TargetPointAssociatedSystems3=HitZone3
TargetPointPriority3=Medium
TargetPointPosition4=8.601,0.1,17.201
TargetPointAssociatedSystems4=HitZone4
TargetPointPriority4=Medium
TargetPointPosition5=4.07,0.1,15.362
TargetPointAssociatedSystems5=HitZone5
TargetPointPriority5=Medium

[Models]
ResourcesFolder=scenery/modular_ports/
ResourcesRoot=modular_ports
ResourcesMesh=False
ResourcesMaterialFolder=scenery/materials/
ResourcesMaterial=pier_tx
[Particles]
SmallFireEffectClass=SmallShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=ModerateShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=SevereShipFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffect=effects/explosions/emitters/missile_hit_ship
SecondaryExplosionEffectPosition=0,0,0
[Sounds]
SoundMode=1

[Submodels]
Submodel0=harbour_small_generic_warehouses
Submodel1=harbour_small_generic_pier
Submodel2=harbour_small_generic_industry
Submodel3=harbour_small_generic_crew
Submodel4=harbour_small_generic_cranes_trans
Submodel5=harbour_small_generic_cranes
Submodel6=harbour_small_generic_concrete
Submodel7=harbour_small_generic_cargo
Submodel8=port_1_cargo
Submodel9=port_1_concrete
Submodel10=port_1_containers
Submodel11=port_1_cranes
Submodel12=port_1_crew
Submodel13=port_1_pier
Submodel14=port_1_trans
Submodel15=port_1_warehouses
Submodel16=container_port_small(Clone)
Submodel17=container_port_small_containers
Submodel18=container_port_small_cranes
Submodel19=container_port_small_cranes_trans
Submodel20=container_port_small_crew
Submodel21=container_port_small_industry
Submodel22=container_port_small_piers
Submodel23=container_port_small_roads
Submodel24=container_port_small_vehicles
Submodel25=military_port_3(Clone)
Submodel26=military_port_3_cranes
Submodel27=military_port_3_decals
Submodel28=military_port_3_piers
Submodel29=military_port_3_spoil_heaps
Submodel30=military_port_3_trans
Submodel31=military_port_3_warehouses

[harbour_small_generic_warehouses]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=harbour_small_generic_warehouses
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1 
Position=2.95,0.1,13.12
Rotation=0,197.24,0
Scale=1,1,1
[harbour_small_generic_pier]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=harbour_small_generic_pier
ResourcesMaterialFolder=scenery/materials/
Material=pier_tx 
Position=2.95,0.1,13.12
Rotation=0,197.24,0
Scale=1,1,1
[harbour_small_generic_industry]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=harbour_small_generic_industry
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1 
Position=2.95,0.1,13.12
Rotation=0,197.24,0
Scale=1,1,1
[harbour_small_generic_crew]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=harbour_small_generic_crew
ResourcesMaterialFolder=scenery/materials/
Material=crew_civ 
Position=2.95,0.1,13.12
Rotation=0,197.24,0
Scale=1,1,1
[harbour_small_generic_cranes_trans]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=harbour_small_generic_cranes_trans
ResourcesMaterialFolder=scenery/materials/
Material=trans 
Position=2.95,0.1,13.12
Rotation=0,197.24,0
Scale=1,1,1
[harbour_small_generic_cranes]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=harbour_small_generic_cranes
ResourcesMaterialFolder=scenery/materials/
Material=harbor_crane_tx 
Position=2.95,0.1,13.12
Rotation=0,197.24,0
Scale=1,1,1
[harbour_small_generic_concrete]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=harbour_small_generic_concrete
ResourcesMaterialFolder=scenery/materials/
Material=concrete 
Position=2.95,0.1,13.12
Rotation=0,197.24,0
Scale=1,1,1
[harbour_small_generic_cargo]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=harbour_small_generic_cargo
ResourcesMaterialFolder=scenery/materials/
Material=ms_cargoatlas 
Position=2.95,0.1,13.12
Rotation=0,197.24,0
Scale=1,1,1
[port_1_cargo]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=port_1_cargo
ResourcesMaterialFolder=scenery/materials/
Material=ms_cargoatlas 
Position=-9.19,0.1,41.31
Rotation=0,312.26,0
Scale=1,1,1
[port_1_concrete]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=port_1_concrete
ResourcesMaterialFolder=scenery/materials/
Material=concrete 
Position=-9.19,0.1,41.31
Rotation=0,312.26,0
Scale=1,1,1
[port_1_containers]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=port_1_containers
ResourcesMaterialFolder=scenery/materials/
Material=containers_tiled 
Position=-9.19,0.1,41.31
Rotation=0,312.26,0
Scale=1,1,1
[port_1_cranes]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=port_1_cranes
ResourcesMaterialFolder=scenery/materials/
Material=harbor_crane_tx 
Position=-9.19,0.1,41.31
Rotation=0,312.26,0
Scale=1,1,1
[port_1_crew]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=port_1_crew
ResourcesMaterialFolder=scenery/materials/
Material=crew_civ 
Position=-9.19,0.1,41.31
Rotation=0,312.26,0
Scale=1,1,1
[port_1_pier]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=port_1_pier
ResourcesMaterialFolder=scenery/materials/
Material=pier_tx 
Position=-9.19,0.1,41.31
Rotation=0,312.26,0
Scale=1,1,1
[port_1_trans]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=port_1_trans
ResourcesMaterialFolder=scenery/materials/
Material=trans 
Position=-9.19,0.1,41.31
Rotation=0,312.26,0
Scale=1,1,1
[port_1_warehouses]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=port_1_warehouses
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1 
Position=-9.19,0.1,41.31
Rotation=0,312.26,0
Scale=1,1,1
[container_port_small(Clone)]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=container_ports
Mesh=container_port_small_concrete
ResourcesMaterialFolder=scenery/materials/
Material=concrete 
Position=1.04,0.1,-9.1
Rotation=0,198.31,0
Scale=1,1,1
[container_port_small_containers]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=container_ports
Mesh=container_port_small_containers
ResourcesMaterialFolder=scenery/materials/
Material=containers_tiled 
Position=1.04,0.1,-9.1
Rotation=0,198.31,0
Scale=1,1,1
[container_port_small_cranes]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=container_ports
Mesh=container_port_small_cranes
ResourcesMaterialFolder=scenery/materials/
Material=harbour_crane 
Position=1.04,0.1,-9.1
Rotation=0,198.31,0
Scale=1,1,1
[container_port_small_cranes_trans]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=container_ports
Mesh=container_port_small_cranes_trans
ResourcesMaterialFolder=scenery/materials/
Material=trans 
Position=1.04,0.1,-9.1
Rotation=0,198.31,0
Scale=1,1,1
[container_port_small_crew]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=container_ports
Mesh=container_port_small_crew
ResourcesMaterialFolder=scenery/materials/
Material=crew_civ 
Position=1.04,0.1,-9.1
Rotation=0,198.31,0
Scale=1,1,1
[container_port_small_industry]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=container_ports
Mesh=container_port_small_industry
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1 
Position=1.04,0.1,-9.1
Rotation=0,198.31,0
Scale=1,1,1
[container_port_small_piers]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=container_ports
Mesh=container_port_small_piers
ResourcesMaterialFolder=scenery/materials/
Material=pier_tx 
Position=1.04,0.1,-9.1
Rotation=0,198.31,0
Scale=1,1,1
[container_port_small_roads]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=container_ports
Mesh=container_port_small_roads
ResourcesMaterialFolder=scenery/materials/
Material=roads 
Position=1.04,0.1,-9.1
Rotation=0,198.31,0
Scale=1,1,1
[container_port_small_vehicles]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=container_ports
Mesh=container_port_small_vehicles
ResourcesMaterialFolder=scenery/materials/
Material=vehicles 
Position=1.04,0.1,-9.1
Rotation=0,198.31,0
Scale=1,1,1
[military_port_3(Clone)]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_3_concrete
ResourcesMaterialFolder=scenery/materials/
Material=concrete 
Position=9.14,0.1,-37.6
Rotation=0,120,0
Scale=1,1,1
[military_port_3_cranes]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_3_cranes
ResourcesMaterialFolder=scenery/materials/
Material=harbour_crane 
Position=9.14,0.1,-37.6
Rotation=0,120,0
Scale=1,1,1
[military_port_3_decals]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_3_decals
ResourcesMaterialFolder=scenery/modular industry/
Material=module_industry_decal 
Position=9.14,0.1,-37.6
Rotation=0,120,0
Scale=1,1,1
[military_port_3_piers]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_3_piers
ResourcesMaterialFolder=scenery/materials/
Material=pier_tx 
Position=9.14,0.1,-37.6
Rotation=0,120,0
Scale=1,1,1
[military_port_3_spoil_heaps]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_3_spoil_heaps
ResourcesMaterialFolder=scenery/modular industry/
Material=module_industry_decal 
Position=9.14,0.1,-37.6
Rotation=0,120,0
Scale=1,1,1
[military_port_3_trans]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_3_trans
ResourcesMaterialFolder=scenery/materials/
Material=trans 
Position=9.14,0.1,-37.6
Rotation=0,120,0
Scale=1,1,1
[military_port_3_warehouses]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_3_warehouses
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1 
Position=9.14,0.1,-37.6
Rotation=0,120,0
Scale=1,1,1

[Colliders]
NumberOfColliders=51
Collider1=coll_port_small_fueltanks_4
Collider2=coll_port_small_fueltanks_3
Collider3=coll_port_small_fueltanks_2
Collider4=coll_port_small_fueltanks_1
Collider5=coll_port_small_warehouses_3
Collider6=coll_port_small_warehouses_2
Collider7=coll_port_small_warehouses_1
Collider8=coll_port_small_main_4
Collider9=coll_port_small_main_3
Collider10=coll_port_small_main_2
Collider11=coll_port_small_main
Collider12=coll_port_1_main
Collider13=coll_port_1_main_2
Collider14=coll_port_1_main_3
Collider15=coll_port_1_main_4
Collider16=coll_port_1_main_5
Collider17=coll_port_1_pier_1
Collider18=coll_port_1_pier_2
Collider19=coll_port_1_pier_3
Collider20=coll_port_1_pier_3b
Collider21=coll_port_1_pier_4
Collider22=coll_port_1_pier_4b
Collider23=coll_con_pt_small_main
Collider24=coll_con_pt_small_main_side
Collider25=coll_con_pt_small_pier_1
Collider26=coll_con_pt_small_pier_2
Collider27=coll_con_pt_small_buildings_1
Collider28=coll_con_pt_small_buildings_2
Collider29=coll_mil_pt_3_main
Collider30=coll_mil_pt_3_main_2
Collider31=coll_mil_pt_3_main_3
Collider32=coll_mil_pt_3_main_4
Collider33=coll_mil_pt_3_main_5
Collider34=coll_mil_pt_3_main_6
Collider35=coll_mil_pt_3_main_7
Collider36=coll_mil_pt_3_main_8
Collider37=coll_mil_pt_3_main_9
Collider38=coll_mil_pt_3_main_10
Collider39=coll_mil_pt_3_main_11
Collider40=coll_mil_pt_3_pier_1
Collider41=coll_mil_pt_3_pier_2
Collider42=coll_mil_pt_3_pier_3
Collider43=coll_mil_pt_3_buildings_1
Collider44=coll_mil_pt_3_buildings_2
Collider45=coll_mil_pt_3_buildings_3
Collider46=coll_mil_pt_3_buildings_4
Collider47=coll_mil_pt_3_buildings_5
Collider48=coll_mil_pt_3_buildings_6
Collider49=coll_mil_pt_3_buildings_7
Collider50=coll_mil_pt_3_buildings_8
Collider51=coll_mil_pt_3_buildings_9

[coll_port_small_fueltanks_4]
Collider=Box
Position=6.52755,0.256,16.53721
Rotation=0,152.2406,0
Scale=0.5964208,0.3151053,0.6321303
[coll_port_small_fueltanks_3]
Collider=Box
Position=7.766174,0.256,18.0082
Rotation=0,-162.7595,0
Scale=0.5964208,0.3151053,0.6321303
[coll_port_small_fueltanks_2]
Collider=Box
Position=8.529579,0.285,17.22577
Rotation=0,-162.7595,0
Scale=0.5075921,0.3653395,1.722279
[coll_port_small_fueltanks_1]
Collider=Box
Position=9.157059,0.285,17.03106
Rotation=0,-162.7595,0
Scale=0.5075921,0.3653395,1.722279
[coll_port_small_warehouses_3]
Collider=Box
Position=4.01548,0.182,15.38602
Rotation=0,-162.7595,0
Scale=0.4805607,0.1183962,1.280207
[coll_port_small_warehouses_2]
Collider=Box
Position=5.547539,0.216,11.41555
Rotation=0,-162.7595,0
Scale=0.4805607,0.1913399,1.280207
[coll_port_small_warehouses_1]
Collider=Box
Position=5.137375,0.216,9.925144
Rotation=0,-162.7595,0
Scale=0.4805607,0.1913399,1.280207
[coll_port_small_main_4]
Collider=Box
Position=2.38205,-0.274,9.85252
Rotation=0,-162.7595,0
Scale=1.537794,0.7625,5.002032
[coll_port_small_main_3]
Collider=Box
Position=4.761124,-0.274,9.114223
Rotation=0,-162.7595,0
Scale=1.537794,0.7625,5.002032
[coll_port_small_main_2]
Collider=Box
Position=8.588058,-0.274,15.83181
Rotation=0,-162.7595,0
Scale=1.782949,0.7625,5.816316
[coll_port_small_main]
Collider=Box
Position=5.468361,-0.274,15.66809
Rotation=0,-162.7595,0
Scale=4.025,0.7625,7.99236
[coll_port_1_main]
Collider=Box
Position=-8.598183,-0.201,41.96126
Rotation=0,-47.7377,0
Scale=4.675,0.6125,9.112501
[coll_port_1_main_2]
Collider=Box
Position=-11.3959,-0.201,45.69269
Rotation=0,-47.7377,0
Scale=2.796235,0.6125,3.303282
[coll_port_1_main_3]
Collider=Box
Position=-4.587212,-0.201,39.50547
Rotation=0,-47.7377,0
Scale=2.796235,0.6125,3.303282
[coll_port_1_main_4]
Collider=Box
Position=-5.629944,-0.201,37.92084
Rotation=0,-92.7377,0
Scale=1.301621,0.6125,2.514953
[coll_port_1_main_5]
Collider=Box
Position=-12.90488,-0.201,44.53177
Rotation=0,-2.7378,0
Scale=1.301621,0.6125,2.514953
[coll_port_1_pier_1]
Collider=Box
Position=-15.03722,-0.201,47.40587
Rotation=0,-47.7377,0
Scale=0.559247,0.6125,4.359299
[coll_port_1_pier_2]
Collider=Box
Position=-10.08778,-0.201,38.10057
Rotation=0,-47.7377,0
Scale=3.090189,0.6125,0.2506647
[coll_port_1_pier_3]
Collider=Box
Position=-14.23812,-0.201,41.87209
Rotation=0,-47.7377,0
Scale=3.090189,0.6125,0.2506647
[coll_port_1_pier_3b]
Collider=Box
Position=-15.34217,-0.201,40.14862
Rotation=0,-82.6964,0
Scale=1.406994,0.6125,0.191375
[coll_port_1_pier_4]
Collider=Box
Position=-8.575249,-0.201,35.57485
Rotation=0,-47.7377,0
Scale=4.751165,0.6125,0.2506647
[coll_port_1_pier_4b]
Collider=Box
Position=-11.61221,-0.201,33.75399
Rotation=0,-2.7435,0
Scale=2.970838,0.6125,0.2506647
[coll_con_pt_small_main]
Collider=Box
Position=2.454475,-0.373,-9.536526
Rotation=0,-161.6879,0
Scale=3.75,1,20.2
[coll_con_pt_small_main_side]
Collider=Box
Position=-0.3043976,-0.373,-20.84856
Rotation=0,-161.6879,0
Scale=1.838574,1,3.019797
[coll_con_pt_small_pier_1]
Collider=Box
Position=-2.466408,-0.373,-19.83494
Rotation=0,-161.6879,0
Scale=2.871608,1,0.4192823
[coll_con_pt_small_pier_2]
Collider=Box
Position=-2.961891,-0.373,-21.33208
Rotation=0,-161.6879,0
Scale=2.871608,1,0.4192823
[coll_con_pt_small_buildings_1]
Collider=Box
Position=-0.6245956,0.18,-21.80014
Rotation=0,-161.6879,0
Scale=1.456982,0.1532713,0.7417367
[coll_con_pt_small_buildings_2]
Collider=Box
Position=0.2334595,0.18,-20.67791
Rotation=0,-161.6879,0
Scale=0.5080513,0.1532713,1.45784
[coll_mil_pt_3_main]
Collider=Box
Position=11.37189,-0.394,-37.21426
Rotation=0,120,0
Scale=3.758907,1,7.4875
[coll_mil_pt_3_main_2]
Collider=Box
Position=6.856018,-0.394,-33.50198
Rotation=0,120,0
Scale=1.852436,1,4.052493
[coll_mil_pt_3_main_3]
Collider=Box
Position=4.094658,-0.394,-31.59478
Rotation=0,120,0
Scale=1.286864,1,2.688784
[coll_mil_pt_3_main_4]
Collider=Box
Position=8.469749,-0.394,-39.95891
Rotation=0,120,0
Scale=3.886456,1,2.352686
[coll_mil_pt_3_main_5]
Collider=Box
Position=11.34407,-0.394,-40.31243
Rotation=0,120,0
Scale=1.934119,1,3.029083
[coll_mil_pt_3_main_6]
Collider=Box
Position=15.85909,-0.394,-38.7842
Rotation=0,120,0
Scale=1.934119,1,2.196085
[coll_mil_pt_3_main_7]
Collider=Box
Position=14.05975,-0.394,-40.27876
Rotation=0,65.7685,0
Scale=1.341621,1,4.901882
[coll_mil_pt_3_main_8]
Collider=Box
Position=4.732826,-0.394,-37.66745
Rotation=0,120,0
Scale=1.146195,1,3.495275
[coll_mil_pt_3_main_9]
Collider=Box
Position=4.956505,-0.394,-39.41202
Rotation=0,120,0
Scale=2.034496,1,1.572874
[coll_mil_pt_3_main_10]
Collider=Box
Position=3.600548,-0.394,-38.10261
Rotation=0,75.0001,0
Scale=3.563214,1,0.5997053
[coll_mil_pt_3_main_11]
Collider=Box
Position=4.412209,-0.394,-38.58277
Rotation=0,120,0
Scale=1.144404,1,1.317282
[coll_mil_pt_3_pier_1]
Collider=Box
Position=6.378433,-0.394,-38.94316
Rotation=0,120,0
Scale=4.260908,1,0.6227267
[coll_mil_pt_3_pier_2]
Collider=Box
Position=4.494034,-0.394,-34.10705
Rotation=0,120,0
Scale=1.627675,1,0.5371017
[coll_mil_pt_3_pier_3]
Collider=Box
Position=3.256531,-0.394,-36.25046
Rotation=0,120,0
Scale=1.220756,1,0.5371017
[coll_mil_pt_3_buildings_1]
Collider=Box
Position=7.040649,0.269,-33.59818
Rotation=0,120,0
Scale=1.824561,0.3514903,2.93049
[coll_mil_pt_3_buildings_2]
Collider=Box
Position=4.971603,0.197,-37.63787
Rotation=0,120,0
Scale=0.7989259,0.1930801,2.536245
[coll_mil_pt_3_buildings_3]
Collider=Box
Position=5.403145,0.178,-40.08442
Rotation=0,30.0002,0
Scale=0.7519304,0.1609001,0.8856379
[coll_mil_pt_3_buildings_4]
Collider=Box
Position=9.974289,0.258,-35.56097
Rotation=0,-150.0002,0
Scale=2.346316,0.3180728,1.45784
[coll_mil_pt_3_buildings_5]
Collider=Box
Position=8.830101,0.2,-36.77676
Rotation=0,120,0
Scale=1.456982,0.2011686,1.454035
[coll_mil_pt_3_buildings_6]
Collider=Box
Position=8.823288,0.145,-40.98055
Rotation=0,120,0
Scale=1.290795,0.09241184,0.488465
[coll_mil_pt_3_buildings_7]
Collider=Box
Position=12.54983,0.145,-41.064
Rotation=0,155,0
Scale=1.290794,0.09241184,0.488465
[coll_mil_pt_3_buildings_8]
Collider=Box
Position=13.80095,0.145,-40.48499
Rotation=0,155,0
Scale=1.290794,0.09241184,0.488465
[coll_mil_pt_3_buildings_9]
Collider=Box
Position=13.27377,0.197,-38.34811
Rotation=0,65.0002,0
Scale=0.7989259,0.1930801,2.536244
