[General]
MaskVegetation=False
UnitType=LandUnit
HideIn=Encyclopedia,MissionEditor,Signatures
LandUnitSubType=Port
DefaultCameraDistance=18.0
MinCameraDistanceForeAft=18
MinCameraDistanceBroadside=18
CameraPivotHeight=0.15
ArmorType=None
DamagePoints=300

[Tacview]
Tag=Ground+Vehicle

[AI]
UnitScoreValue=10
Role=Port
[SensorData]
VisualIdentificationRange=15.0
IRSignature=Large
RCS=SemiSmall
BaseNoise=150
FlowNoise=1
CavitationNoise=5
[SensorSystems]
NumberOfSensorSystems=1
[SensorSystem1]
Type=Visual
SystemName=Optics
MountPosition=0,0.175,0

# HITZONES AND TARGETPOINTS #####################################################################
[---------- HitZones ----------]
[HitZones]
NumberOfHitZones=5

[HitZone1]
Collider=coll_port_1_main
Integrity=60

[HitZone2]
Collider=coll_port_1_main_2
Integrity=60

[HitZone3]
Collider=coll_port_1_main_3
Integrity=60

[HitZone4]
Collider=coll_port_1_main_4
Integrity=60

[HitZone5]
Collider=coll_port_1_main_5
Integrity=60

#Enemy units will use this local coordinates to aim their attacks to
[TargetingData]
NumberOfTargetPoints=5
TargetPointPosition1=-6.93,0.1,1.83
TargetPointAssociatedSystems1=HitZone1
TargetPointPriority1=High
TargetPointPosition2=2.63,0.1,-3.23
TargetPointAssociatedSystems2=HitZone2
TargetPointPriority2=High
TargetPointPosition3=4.15,0.1,-3.58
TargetPointAssociatedSystems3=HitZone3
TargetPointPriority3=Medium
TargetPointPosition4=9.1,0.1,-3.29
TargetPointAssociatedSystems4=HitZone4
TargetPointPriority4=Medium
TargetPointPosition5=10.28,0.1,-3.52
TargetPointAssociatedSystems5=HitZone5
TargetPointPriority5=Medium

######################################################################

[Models]
ResourcesFolder=scenery/modular_ports/
ResourcesRoot=modular_ports
ResourcesMesh=False
ResourcesMaterialFolder=scenery/materials/
ResourcesMaterial=pier_tx
[Particles]
SmallFireEffectClass=ModerateShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=SevereShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=OilTankFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffect=effects/explosions/emitters/missile_hit_ship
SecondaryExplosionEffectPosition=0,0,0
[Sounds]
SoundMode=1

[Submodels]
Submodel0=port_1_warehouses
Submodel1=port_1_trans
Submodel2=port_1_pier
Submodel3=port_1_crew
Submodel4=port_1_cranes
Submodel5=port_1_containers
Submodel6=port_1_concrete
Submodel7=port_1_cargo

[port_1_warehouses]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=port_1_warehouses
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1 
Position=-2.84,0.1,-0.31
Rotation=0,143.37,0
Scale=1,1,1
[port_1_trans]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=port_1_trans
ResourcesMaterialFolder=scenery/materials/
Material=trans 
Position=-2.84,0.1,-0.31
Rotation=0,143.37,0
Scale=1,1,1
[port_1_pier]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=port_1_pier
ResourcesMaterialFolder=scenery/materials/
Material=pier_tx 
Position=-2.84,0.1,-0.31
Rotation=0,143.37,0
Scale=1,1,1
[port_1_crew]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=port_1_crew
ResourcesMaterialFolder=scenery/materials/
Material=crew_civ 
Position=-2.84,0.1,-0.31
Rotation=0,143.37,0
Scale=1,1,1
[port_1_cranes]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=port_1_cranes
ResourcesMaterialFolder=scenery/materials/
Material=harbor_crane_tx 
Position=-2.84,0.1,-0.31
Rotation=0,143.37,0
Scale=1,1,1
[port_1_containers]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=port_1_containers
ResourcesMaterialFolder=scenery/materials/
Material=containers_tiled 
Position=-2.84,0.1,-0.31
Rotation=0,143.37,0
Scale=1,1,1
[port_1_concrete]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=port_1_concrete
ResourcesMaterialFolder=scenery/materials/
Material=concrete 
Position=-2.84,0.1,-0.31
Rotation=0,143.37,0
Scale=1,1,1
[port_1_cargo]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=port_1_cargo
ResourcesMaterialFolder=scenery/materials/
Material=ms_cargoatlas 
Position=-2.84,0.1,-0.31
Rotation=0,143.37,0
Scale=1,1,1

[Colliders]

NumberOfColliders=11
Collider1=coll_port_1_main
Collider2=coll_port_1_main_2
Collider3=coll_port_1_main_3
Collider4=coll_port_1_main_4
Collider5=coll_port_1_main_5
Collider6=coll_port_1_pier_1
Collider7=coll_port_1_pier_2
Collider8=coll_port_1_pier_3
Collider9=coll_port_1_pier_3b
Collider10=coll_port_1_pier_4
Collider11=coll_port_1_pier_4b

[coll_port_1_main]
Collider=Box
Position=-3.546242,-0.201,-0.8349915
Rotation=0,143.3746,0
Scale=4.675,0.6125,9.1125
[coll_port_1_main_2]
Collider=Box
Position=-1.520157,-0.201,-5.035679
Rotation=0,143.3746,0
Scale=2.796235,0.6125,3.303281
[coll_port_1_main_3]
Collider=Box
Position=-7.00869,0.03,2.347816
Rotation=0,143.3746,0
Scale=2.796235,0.6125,3.303281
[coll_port_1_main_4]
Collider=Box
Position=-5.680099,-0.201,3.701759
Rotation=0,98.3747,0
Scale=1.301621,0.6125,2.514953
[coll_port_1_main_5]
Collider=Box
Position=0.1842804,-0.201,-4.187344
Rotation=0,-171.6254,0
Scale=1.301621,0.6125,2.514954
[coll_port_1_pier_1]
Collider=Box
Position=1.722702,-0.201,-7.418545
Rotation=0,143.3746,0
Scale=0.559247,0.6125,4.359299
[coll_port_1_pier_2]
Collider=Box
Position=-1.340477,-0.201,2.666225
Rotation=0,143.3746,0
Scale=3.090189,0.6125,0.2506647
[coll_port_1_pier_3]
Collider=Box
Position=2.005142,-0.201,-1.834496
Rotation=0,143.3746,0
Scale=3.090189,0.6125,0.2506647
[coll_port_1_pier_3b]
Collider=Box
Position=3.420662,-0.201,-0.3561211
Rotation=0,108.416,0
Scale=1.406994,0.6125,0.191375
[coll_port_1_pier_4]
Collider=Box
Position=-2.337868,-0.201,5.436108
Rotation=0,143.3746,0
Scale=4.751165,0.6125,0.2506647
[coll_port_1_pier_4b]
Collider=Box
Position=0.9930954,-0.201,6.637501
Rotation=0,-171.6311,0
Scale=2.970837,0.6125,0.2506646
