[General]
UnitType=LandUnit
HideIn=Encyclopedia,MissionEditor,Signatures
LandUnitSubType=Port
DefaultCameraDistance=18.0
MinCameraDistanceForeAft=18
MinCameraDistanceBroadside=18
CameraPivotHeight=0.15
ArmorType=None
DamagePoints=400

[Tacview]
Tag=Ground+Vehicle

[AI]
UnitScoreValue=10
Role=Port
[SensorData]
VisualIdentificationRange=15.0
IRSignature=Large
RCS=SemiSmall
BaseNoise=150
FlowNoise=1
CavitationNoise=5
[SensorSystems]
NumberOfSensorSystems=1
[SensorSystem1]
Type=Visual
SystemName=Optics
MountPosition=0,0.175,0

# HITZONES AND TARGETPOINTS #####################################################################
[---------- HitZones ----------]
[HitZones]
NumberOfHitZones=5

[HitZone1]
Collider=
Integrity=60

[HitZone2]
Collider=
Integrity=60

[HitZone3]
Collider=
Integrity=60

[HitZone4]
Collider=
Integrity=60

[HitZone5]
Collider=
Integrity=60

#Enemy units will use this local coordinates to aim their attacks to
[TargetingData]
NumberOfTargetPoints=5
TargetPointPosition1=-7.6,0.1,7.772
TargetPointAssociatedSystems1=HitZone1
TargetPointPriority1=High
TargetPointPosition2=-6.36,0.1,6.72
TargetPointAssociatedSystems2=HitZone2
TargetPointPriority2=High
TargetPointPosition3=1.41,0.1,-1.78
TargetPointAssociatedSystems3=HitZone3
TargetPointPriority3=Medium
TargetPointPosition4=0.97,0.1,-6.47
TargetPointAssociatedSystems4=HitZone4
TargetPointPriority4=Medium
TargetPointPosition5=6.47,0.1,-7.83
TargetPointAssociatedSystems5=HitZone5
TargetPointPriority5=Medium

[Models]
ResourcesFolder=scenery/modular_ports/
ResourcesRoot=modular_ports
ResourcesMesh=False
ResourcesMaterialFolder=scenery/materials/
ResourcesMaterial=pier_tx
[Particles]
SmallFireEffectClass=ModerateShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=SevereShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=OilTankFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffect=effects/explosions/emitters/missile_hit_ship
SecondaryExplosionEffectPosition=0,0,0
[Sounds]
SoundMode=1
[Submodels]
Submodel0=pier_wall_2km_2
Submodel1=pier_wall_2km_2 (1)
Submodel2=pier_wall_1km (2)
Submodel3=pier_wall_1km (1)
Submodel4=pier_wall_1km (3)
Submodel5=pier_endpoint_2
Submodel6=pier_chunk_1
Submodel7=pier_chunk_1_cargo
Submodel8=pier_chunk_1_crew
Submodel9=pier_chunk_1_warehouses
Submodel10=pier_chunk_2
Submodel11=pier_chunk_2_cargo
Submodel12=pier_chunk_2_crew
Submodel13=pier_chunk_2_warehouses
Submodel14=pier_chunk_6
Submodel15=pier_chunk_6_cargo
Submodel16=pier_chunk_6_crew
Submodel17=pier_chunk_6_warehouses
Submodel18=pier_3x_short
Submodel19=pier_3x_mixed
Submodel20=pier_3x_mixed (1)
Submodel21=pier_endpoint_1
Submodel22=military_port_2(Clone)
Submodel23=military_port_2_cargo
Submodel24=military_port_2_cranes
Submodel25=military_port_2_piers
Submodel26=military_port_2_trans
Submodel27=military_port_2_warehouses
Submodel28=military_port_3(Clone)
Submodel29=military_port_3_cranes
Submodel30=military_port_3_decals
Submodel31=military_port_3_piers
Submodel32=military_port_3_spoil_heaps
Submodel33=military_port_3_trans
Submodel34=military_port_3_warehouses
Submodel35=harbour_small_generic_cargo
Submodel36=harbour_small_generic_concrete
Submodel37=harbour_small_generic_cranes
Submodel38=harbour_small_generic_cranes_trans
Submodel39=harbour_small_generic_crew
Submodel40=harbour_small_generic_industry
Submodel41=harbour_small_generic_pier
Submodel42=harbour_small_generic_warehouses
Submodel43=container_port_small(Clone)
Submodel44=container_port_small_containers
Submodel45=container_port_small_cranes
Submodel46=container_port_small_cranes_trans
Submodel47=container_port_small_crew
Submodel48=container_port_small_industry
Submodel49=container_port_small_piers
Submodel50=container_port_small_roads
Submodel51=container_port_small_vehicles
[pier_wall_2km_2]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=pier_wall_2km_2
ResourcesMaterialFolder=scenery/materials/
Material=pier_tx 
Position=-10,0,34
Rotation=0,120,0
Scale=1,1,1
[pier_wall_2km_2 (1)]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=pier_wall_2km_2
ResourcesMaterialFolder=scenery/materials/
Material=pier_tx 
Position=7.1531,0.08,-4.96
Rotation=0,90,0
Scale=1,1,1
[pier_wall_1km (2)]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=pier_wall_1km
ResourcesMaterialFolder=scenery/materials/
Material=pier_tx 
Position=-15.68,0.08,-4.96
Rotation=0,90,0
Scale=1,1,1
[pier_wall_1km (1)]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=pier_wall_1km
ResourcesMaterialFolder=scenery/materials/
Material=pier_tx 
Position=-32.2859,0.08,-4.96
Rotation=0,90,0
Scale=1,1,1
[pier_wall_1km (3)]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=pier_wall_1km
ResourcesMaterialFolder=scenery/materials/
Material=pier_tx 
Position=-30.2373,0.0809,6.03
Rotation=0,270,0
Scale=1,1,1
[pier_endpoint_2]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=pier_endpoint_2
ResourcesMaterialFolder=scenery/materials/
Material=pier_tx 
Position=22.223,0.0891,-4.917
Rotation=0,90,0
Scale=1,1,1
[pier_chunk_1]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=pier_chunk_1
ResourcesMaterialFolder=scenery/materials/
Material=pier_tx 
Position=107.98,0.1,-54.41
Rotation=0,165,0
Scale=1,1,1
[pier_chunk_1_cargo]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=pier_chunk_1_cargo
ResourcesMaterialFolder=ships/materials/
Material=ms_cargoatlas 
Position=107.98,0.1,-54.41
Rotation=0,165,0
Scale=1,1,1
[pier_chunk_1_crew]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=pier_chunk_1_crew
ResourcesMaterialFolder=ships/materials/
Material=crew_civ 
Position=107.98,0.1,-54.41
Rotation=0,165,0
Scale=1,1,1
[pier_chunk_1_warehouses]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=pier_chunk_1_warehouses
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1 
Position=107.98,0.1,-54.41
Rotation=0,165,0
Scale=1,1,1
[pier_chunk_2]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=pier_chunk_2
ResourcesMaterialFolder=scenery/materials/
Material=pier_tx 
Position=91.3,0.1,-47.7
Rotation=0,45,0
Scale=1,1,1
[pier_chunk_2_cargo]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=pier_chunk_2_cargo
ResourcesMaterialFolder=ships/materials/
Material=ms_cargoatlas 
Position=91.3,0.1,-47.7
Rotation=0,45,0
Scale=1,1,1
[pier_chunk_2_crew]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=pier_chunk_2_crew
ResourcesMaterialFolder=ships/materials/
Material=crew_civ 
Position=91.3,0.1,-47.7
Rotation=0,45,0
Scale=1,1,1
[pier_chunk_2_warehouses]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=pier_chunk_2_warehouses
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1 
Position=91.3,0.1,-47.7
Rotation=0,45,0
Scale=1,1,1
[pier_chunk_6]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=pier_chunk_6
ResourcesMaterialFolder=scenery/materials/
Material=pier_tx 
Position=176.86,0.1,118.65
Rotation=0,20,0
Scale=1,1,1
[pier_chunk_6_cargo]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=pier_chunk_6_cargo
Position=176.86,0.1,118.65
Rotation=0,20,0
Scale=1,1,1
[pier_chunk_6_crew]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=pier_chunk_6_crew
ResourcesMaterialFolder=ships/materials/
Material=crew_civ 
Position=176.86,0.1,118.65
Rotation=0,20,0
Scale=1,1,1
[pier_chunk_6_warehouses]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=pier_chunk_6_warehouses
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1 
Position=176.86,0.1,118.65
Rotation=0,20,0
Scale=1,1,1
[pier_3x_short]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=pier_3x_short
ResourcesMaterialFolder=scenery/materials/
Material=pier_tx 
Position=182.56,0.1,114.69
Rotation=0,90,0
Scale=1,1,1
[pier_3x_mixed]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=pier_3x_mixed
ResourcesMaterialFolder=scenery/materials/
Material=pier_tx 
Position=89.79,0.1,-48.08
Rotation=0,210,0
Scale=1,1,1
[pier_3x_mixed (1)]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=pier_3x_mixed
ResourcesMaterialFolder=scenery/materials/
Material=pier_tx 
Position=-32.87,0.1,16.74
Rotation=0,180,0
Scale=1,1,1
[pier_endpoint_1]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=pier_endpoint_1
ResourcesMaterialFolder=scenery/materials/
Material=pier_tx 
Position=-6.24,0.09,7.25
Rotation=0,90,0
Scale=1,1,1
[military_port_2(Clone)]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_2_concrete
ResourcesMaterialFolder=scenery/materials/
Material=concrete 
Position=-13.5076,0.1,3.5
Rotation=0,90,0
Scale=1,1,1
[military_port_2_cargo]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_2_cargo
ResourcesMaterialFolder=scenery/materials/
Material=ms_cargoatlas 
Position=-13.5076,0.1,3.5
Rotation=0,90,0
Scale=1,1,1
[military_port_2_cranes]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_2_cranes
ResourcesMaterialFolder=scenery/materials/
Material=harbour_crane 
Position=-13.5076,0.1,3.5
Rotation=0,90,0
Scale=1,1,1
[military_port_2_piers]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_2_piers
ResourcesMaterialFolder=scenery/materials/
Material=pier_tx 
Position=-13.5076,0.1,3.5
Rotation=0,90,0
Scale=1,1,1
[military_port_2_trans]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_2_trans
ResourcesMaterialFolder=scenery/materials/
Material=trans 
Position=-13.5076,0.1,3.5
Rotation=0,90,0
Scale=1,1,1
[military_port_2_warehouses]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_2_warehouses
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1 
Position=-13.5076,0.1,3.5
Rotation=0,90,0
Scale=1,1,1
[military_port_3(Clone)]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_3_concrete
ResourcesMaterialFolder=scenery/materials/
Material=concrete 
Position=-24.2841,0.1,-10.24
Rotation=0,90,0
Scale=1,1,1
[military_port_3_cranes]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_3_cranes
ResourcesMaterialFolder=scenery/materials/
Material=harbour_crane 
Position=-24.2841,0.1,-10.24
Rotation=0,90,0
Scale=1,1,1
[military_port_3_decals]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_3_decals
ResourcesMaterialFolder=scenery/modular industry/
Material=module_industry_decal 
Position=-24.2841,0.1,-10.24
Rotation=0,90,0
Scale=1,1,1
[military_port_3_piers]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_3_piers
ResourcesMaterialFolder=scenery/materials/
Material=pier_tx 
Position=-24.2841,0.1,-10.24
Rotation=0,90,0
Scale=1,1,1
[military_port_3_spoil_heaps]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_3_spoil_heaps
ResourcesMaterialFolder=scenery/modular industry/
Material=module_industry_decal 
Position=-24.2841,0.1,-10.24
Rotation=0,90,0
Scale=1,1,1
[military_port_3_trans]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_3_trans
ResourcesMaterialFolder=scenery/materials/
Material=trans 
Position=-24.2841,0.1,-10.24
Rotation=0,90,0
Scale=1,1,1
[military_port_3_warehouses]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_3_warehouses
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1 
Position=-24.2841,0.1,-10.24
Rotation=0,90,0
Scale=1,1,1
[harbour_small_generic_cargo]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=harbour_small_generic_cargo
ResourcesMaterialFolder=scenery/materials/
Material=ms_cargoatlas 
Position=-7.96,0.1,-12.4073
Rotation=0,90,0
Scale=1,1,1
[harbour_small_generic_concrete]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=harbour_small_generic_concrete
ResourcesMaterialFolder=scenery/materials/
Material=concrete 
Position=-7.96,0.1,-12.4073
Rotation=0,90,0
Scale=1,1,1
[harbour_small_generic_cranes]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=harbour_small_generic_cranes
ResourcesMaterialFolder=scenery/materials/
Material=harbor_crane_tx 
Position=-7.96,0.1,-12.4073
Rotation=0,90,0
Scale=1,1,1
[harbour_small_generic_cranes_trans]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=harbour_small_generic_cranes_trans
ResourcesMaterialFolder=scenery/materials/
Material=trans 
Position=-7.96,0.1,-12.4073
Rotation=0,90,0
Scale=1,1,1
[harbour_small_generic_crew]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=harbour_small_generic_crew
ResourcesMaterialFolder=scenery/materials/
Material=crew_civ 
Position=-7.96,0.1,-12.4073
Rotation=0,90,0
Scale=1,1,1
[harbour_small_generic_industry]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=harbour_small_generic_industry
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1 
Position=-7.96,0.1,-12.4073
Rotation=0,90,0
Scale=1,1,1
[harbour_small_generic_pier]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=harbour_small_generic_pier
ResourcesMaterialFolder=scenery/materials/
Material=pier_tx 
Position=-7.96,0.1,-12.4073
Rotation=0,90,0
Scale=1,1,1
[harbour_small_generic_warehouses]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=harbour_small_generic_warehouses
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1 
Position=-7.96,0.1,-12.4073
Rotation=0,90,0
Scale=1,1,1
[container_port_small(Clone)]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=container_ports
Mesh=container_port_small_concrete
ResourcesMaterialFolder=scenery/materials/
Material=concrete 
Position=-14.65,0.08,11.63
Rotation=0,270,0
Scale=1,1,1
[container_port_small_containers]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=container_ports
Mesh=container_port_small_containers
ResourcesMaterialFolder=scenery/materials/
Material=containers_tiled 
Position=-14.65,0.08,11.63
Rotation=0,270,0
Scale=1,1,1
[container_port_small_cranes]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=container_ports
Mesh=container_port_small_cranes
ResourcesMaterialFolder=scenery/materials/
Material=harbour_crane 
Position=-14.65,0.08,11.63
Rotation=0,270,0
Scale=1,1,1
[container_port_small_cranes_trans]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=container_ports
Mesh=container_port_small_cranes_trans
ResourcesMaterialFolder=scenery/materials/
Material=trans 
Position=-14.65,0.08,11.63
Rotation=0,270,0
Scale=1,1,1
[container_port_small_crew]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=container_ports
Mesh=container_port_small_crew
ResourcesMaterialFolder=scenery/materials/
Material=crew_civ 
Position=-14.65,0.08,11.63
Rotation=0,270,0
Scale=1,1,1
[container_port_small_industry]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=container_ports
Mesh=container_port_small_industry
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1 
Position=-14.65,0.08,11.63
Rotation=0,270,0
Scale=1,1,1
[container_port_small_piers]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=container_ports
Mesh=container_port_small_piers
ResourcesMaterialFolder=scenery/materials/
Material=pier_tx 
Position=-14.65,0.08,11.63
Rotation=0,270,0
Scale=1,1,1
[container_port_small_roads]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=container_ports
Mesh=container_port_small_roads
ResourcesMaterialFolder=scenery/materials/
Material=roads 
Position=-14.65,0.08,11.63
Rotation=0,270,0
Scale=1,1,1
[container_port_small_vehicles]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=container_ports
Mesh=container_port_small_vehicles
ResourcesMaterialFolder=scenery/materials/
Material=vehicles 
Position=-14.65,0.08,11.63
Rotation=0,270,0
Scale=1,1,1
