[General]
MaskVegetation=False
UnitType=LandUnit
HideIn=Encyclopedia,MissionEditor,Signatures
LandUnitSubType=Port
DefaultCameraDistance=18.0
MinCameraDistanceForeAft=18
MinCameraDistanceBroadside=18
CameraPivotHeight=0.15
ArmorType=None
DamagePoints=300

[Tacview]
Tag=Ground+Vehicle

[AI]
UnitScoreValue=10
Role=Port
[SensorData]
VisualIdentificationRange=15.0
IRSignature=Large
RCS=SemiSmall
BaseNoise=150
FlowNoise=1
CavitationNoise=5
[SensorSystems]
NumberOfSensorSystems=1
[SensorSystem1]
Type=Visual
SystemName=Optics
MountPosition=0,0.175,0

# HITZONES AND TARGETPOINTS #####################################################################
[---------- HitZones ----------]
[HitZones]
NumberOfHitZones=5

[HitZone1]
Collider=coll_port_small_fueltanks_2
Integrity=60

[HitZone2]
Collider=coll_port_small_warehouses_2
Integrity=60

[HitZone3]
Collider=coll_port_small_warehouses_3
Integrity=60

[HitZone4]
Collider=coll_port_small_fueltanks_4
Integrity=60

[HitZone5]
Collider=coll_port_small_warehouses_2 (1)
Integrity=60

#Enemy units will use this local coordinates to aim their attacks to
[TargetingData]
NumberOfTargetPoints=5
TargetPointPosition1=-3.949,0.1,-10.198
TargetPointAssociatedSystems1=HitZone1
TargetPointPriority1=High
TargetPointPosition2=-10.42,0.1,-8.46
TargetPointAssociatedSystems2=HitZone2
TargetPointPriority2=High
TargetPointPosition3=-6.79,0.1,-6.01
TargetPointAssociatedSystems3=HitZone3
TargetPointPriority3=Medium
TargetPointPosition4=-5.09,0.1,-8.37
TargetPointAssociatedSystems4=HitZone4
TargetPointPriority4=Medium
TargetPointPosition5=10.74,0.1,-9.65
TargetPointAssociatedSystems5=HitZone5
TargetPointPriority5=Medium

######################################################################

[Models]
ResourcesFolder=scenery/modular_ports/
ResourcesRoot=modular_ports
ResourcesMesh=False
ResourcesMaterialFolder=scenery/materials/
ResourcesMaterial=pier_tx
[Particles]
SmallFireEffectClass=ModerateShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=SevereShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=OilTankFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffect=effects/explosions/emitters/missile_hit_ship
SecondaryExplosionEffectPosition=0,0,0
[Sounds]
SoundMode=1
[Submodels]
Submodel0=port_1_warehouses
Submodel1=port_1_trans
Submodel2=port_1_pier
Submodel3=port_1_crew
Submodel4=port_1_cranes
Submodel5=port_1_containers
Submodel6=port_1_concrete
Submodel7=port_1_cargo
Submodel8=harbour_small_generic_cargo
Submodel9=harbour_small_generic_concrete
Submodel10=harbour_small_generic_cranes
Submodel11=harbour_small_generic_cranes_trans
Submodel12=harbour_small_generic_crew
Submodel13=harbour_small_generic_industry
Submodel14=harbour_small_generic_pier
Submodel15=harbour_small_generic_warehouses

[port_1_warehouses]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=port_1_warehouses
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1 
Position=6.08,0.1,-9.12
Rotation=0,95,0
Scale=1,1,1
[port_1_trans]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=port_1_trans
ResourcesMaterialFolder=scenery/materials/
Material=trans 
Position=6.08,0.1,-9.12
Rotation=0,95,0
Scale=1,1,1
[port_1_pier]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=port_1_pier
ResourcesMaterialFolder=scenery/materials/
Material=pier_tx 
Position=6.08,0.1,-9.12
Rotation=0,95,0
Scale=1,1,1
[port_1_crew]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=port_1_crew
ResourcesMaterialFolder=scenery/materials/
Material=crew_civ 
Position=6.08,0.1,-9.12
Rotation=0,95,0
Scale=1,1,1
[port_1_cranes]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=port_1_cranes
ResourcesMaterialFolder=scenery/materials/
Material=harbor_crane_tx 
Position=6.08,0.1,-9.12
Rotation=0,95,0
Scale=1,1,1
[port_1_containers]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=port_1_containers
ResourcesMaterialFolder=scenery/materials/
Material=containers_tiled 
Position=6.08,0.1,-9.12
Rotation=0,95,0
Scale=1,1,1
[port_1_concrete]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=port_1_concrete
ResourcesMaterialFolder=scenery/materials/
Material=concrete 
Position=6.08,0.1,-9.12
Rotation=0,95,0
Scale=1,1,1
[port_1_cargo]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=port_1_cargo
ResourcesMaterialFolder=scenery/materials/
Material=ms_cargoatlas 
Position=6.08,0.1,-9.12
Rotation=0,95,0
Scale=1,1,1
[harbour_small_generic_cargo]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=harbour_small_generic_cargo
ResourcesMaterialFolder=scenery/materials/
Material=ms_cargoatlas 
Position=-9.13,0.1,-5.49
Rotation=0,275,0
Scale=1,1,1
[harbour_small_generic_concrete]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=harbour_small_generic_concrete
ResourcesMaterialFolder=scenery/materials/
Material=concrete 
Position=-9.13,0.1,-5.49
Rotation=0,275,0
Scale=1,1,1
[harbour_small_generic_cranes]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=harbour_small_generic_cranes
ResourcesMaterialFolder=scenery/materials/
Material=harbor_crane_tx 
Position=-9.13,0.1,-5.49
Rotation=0,275,0
Scale=1,1,1
[harbour_small_generic_cranes_trans]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=harbour_small_generic_cranes_trans
ResourcesMaterialFolder=scenery/materials/
Material=trans 
Position=-9.13,0.1,-5.49
Rotation=0,275,0
Scale=1,1,1
[harbour_small_generic_crew]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=harbour_small_generic_crew
ResourcesMaterialFolder=scenery/materials/
Material=crew_civ 
Position=-9.13,0.1,-5.49
Rotation=0,275,0
Scale=1,1,1
[harbour_small_generic_industry]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=harbour_small_generic_industry
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1 
Position=-9.13,0.1,-5.49
Rotation=0,275,0
Scale=1,1,1
[harbour_small_generic_pier]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=harbour_small_generic_pier
ResourcesMaterialFolder=scenery/materials/
Material=pier_tx 
Position=-9.13,0.1,-5.49
Rotation=0,275,0
Scale=1,1,1
[harbour_small_generic_warehouses]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=modular_ports
Mesh=harbour_small_generic_warehouses
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1 
Position=-9.13,0.1,-5.49
Rotation=0,275,0
Scale=1,1,1

[Colliders]
NumberOfColliders=23
Collider1=coll_port_small_fueltanks_4
Collider2=coll_port_small_fueltanks_3
Collider3=coll_port_small_fueltanks_2
Collider4=coll_port_small_fueltanks_1
Collider5=coll_port_small_warehouses_3
Collider6=coll_port_small_warehouses_2
Collider7=coll_port_small_warehouses_2 (1)
Collider8=coll_port_small_warehouses_1
Collider9=coll_port_small_main_4
Collider10=coll_port_small_main_3
Collider11=coll_port_small_main_2
Collider12=coll_port_small_main
Collider13=coll_port_1_pier_4b
Collider14=coll_port_1_pier_4
Collider15=coll_port_1_pier_3b
Collider16=coll_port_1_pier_3
Collider17=coll_port_1_pier_2
Collider18=coll_port_1_pier_1
Collider19=coll_port_1_main_5
Collider20=coll_port_1_main_4
Collider21=coll_port_1_main_3
Collider22=coll_port_1_main_2
Collider23=coll_port_1_main

[coll_port_small_fueltanks_4]
Collider=Box
Position=-5.031982,0.256,-8.261719
Rotation=0,-130,0
Scale=0.5964206,0.3151053,0.6321301
[coll_port_small_fueltanks_3]
Collider=Box
Position=-3.331833,0.256,-9.160309
Rotation=0,-85,0
Scale=0.5964208,0.3151053,0.6321303
[coll_port_small_fueltanks_2]
Collider=Box
Position=-3.934601,0.285,-10.07225
Rotation=0,-85,0
Scale=0.5075921,0.3653395,1.722279
[coll_port_small_fueltanks_1]
Collider=Box
Position=-3.991867,0.285,-10.72675
Rotation=0,-85,0
Scale=0.5075921,0.3653395,1.722279
[coll_port_small_warehouses_3]
Collider=Box
Position=-6.689606,0.182,-6.050842
Rotation=0,-85,0
Scale=0.4805606,0.1183962,1.280207
[coll_port_small_warehouses_2]
Collider=Box
Position=-10.245,0.216,-8.389862
Rotation=0,-85,0
Scale=0.4805606,0.1913399,1.280207
[coll_port_small_warehouses_2 (1)]
Collider=Box
Position=10.799,0.199,-9.592
Rotation=0,-40.0001,0
Scale=0.4805606,0.1913399,1.280207
[coll_port_small_warehouses_1]
Collider=Box
Position=-11.78847,0.216,-8.305023
Rotation=0,-85,0
Scale=0.4805606,0.1913399,1.280207
[coll_port_small_main_4]
Collider=Box
Position=-12.44362,-0.274,-5.627731
Rotation=0,-85,0
Scale=1.537794,0.7625,5.002031
[coll_port_small_main_3]
Collider=Box
Position=-12.66072,-0.274,-8.109253
Rotation=0,-85,0
Scale=1.537794,0.7625,5.002031
[coll_port_small_main_2]
Collider=Box
Position=-5.284485,-0.274,-10.42494
Rotation=0,-85,0
Scale=1.782949,0.7625,5.816315
[coll_port_small_main]
Collider=Box
Position=-6.105911,-0.274,-7.410889
Rotation=0,-85,0
Scale=4.025,0.7625,7.992361
[coll_port_1_pier_4b]
Collider=Box
Position=3.432861,-0.201,-1.639816
Rotation=0,139.9942,0
Scale=2.970838,0.6125,0.2506647
[coll_port_1_pier_4]
Collider=Box
Position=2.118301,-0.201,-4.927765
Rotation=0,95,0
Scale=4.751166,0.6125,0.2506647
[coll_port_1_pier_3b]
Collider=Box
Position=10.27316,-0.201,-4.470764
Rotation=0,60.0414,0
Scale=1.406994,0.6125,0.191375
[coll_port_1_pier_3]
Collider=Box
Position=10.43799,-0.201,-6.510895
Rotation=0,95,0
Scale=3.090189,0.6125,0.2506647
[coll_port_1_pier_2]
Collider=Box
Position=4.851318,-0.201,-6.022125
Rotation=0,95,0
Scale=3.090189,0.6125,0.2506647
[coll_port_1_pier_1]
Collider=Box
Position=14.42447,-0.201,-10.43126
Rotation=0,95,0
Scale=0.559247,0.6125,4.3593
[coll_port_1_main_5]
Collider=Box
Position=10.98723,-0.201,-9.434891
Rotation=0,140,0
Scale=1.301621,0.6125,2.514953
[coll_port_1_main_4]
Collider=Box
Position=1.194641,-0.201,-8.57814
Rotation=0,50,0
Scale=1.301621,0.6125,2.514953
[coll_port_1_main_3]
Collider=Box
Position=1.324188,-0.201,-10.47064
Rotation=0,95,0
Scale=2.796235,0.6125,3.303282
[coll_port_1_main_2]
Collider=Box
Position=10.48918,-0.201,-11.27247
Rotation=0,95,0
Scale=2.796235,0.6125,3.303282
[coll_port_1_main]
Collider=Box
Position=6.003311,-0.201,-9.996643
Rotation=0,95,0
Scale=4.675,0.6125,9.1125
