[General]
UnitType=LandUnit
HideIn=Encyclopedia,MissionEditor,Signatures
LandUnitSubType=Port
DefaultCameraDistance=18.0
MinCameraDistanceForeAft=18
MinCameraDistanceBroadside=18
CameraPivotHeight=0.15
ArmorType=None
DamagePoints=300

[Tacview]
Tag=Ground+Vehicle

[AI]
UnitScoreValue=10
Role=Port
[SensorData]
VisualIdentificationRange=15.0
IRSignature=Large
RCS=SemiSmall
BaseNoise=150
FlowNoise=1
CavitationNoise=5
[SensorSystems]
NumberOfSensorSystems=1
[SensorSystem1]
Type=Visual
SystemName=Optics
MountPosition=0,0.175,0

# HITZONES AND TARGETPOINTS #####################################################################
[---------- HitZones ----------]
[HitZones]
NumberOfHitZones=5

[HitZone1]
Collider=coll_mil_pt_2_buildings_5
Integrity=60

[HitZone2]
Collider=coll_mil_pt_2_buildings_1
Integrity=60

[HitZone3]
Collider=coll_mil_pt_2_buildings_7
Integrity=60

[HitZone4]
Collider=coll_mil_pt_3_buildings_1
Integrity=60

[HitZone5]
Collider=coll_mil_pt_3_buildings_7
Integrity=60

#Enemy units will use this local coordinates to aim their attacks to
[TargetingData]
NumberOfTargetPoints=5
TargetPointPosition1=-10.8,0.1,11.93
TargetPointAssociatedSystems1=HitZone1
TargetPointPriority1=High
TargetPointPosition2=0.38,0.1,11.6
TargetPointAssociatedSystems2=HitZone2
TargetPointPriority2=High
TargetPointPosition3=2.3,0.1,9.01
TargetPointAssociatedSystems3=HitZone3
TargetPointPriority3=Medium
TargetPointPosition4=11.17,0.1,11.41
TargetPointAssociatedSystems4=HitZone4
TargetPointPriority4=Medium
TargetPointPosition5=14.523,0.1,2.814
TargetPointAssociatedSystems5=HitZone5
TargetPointPriority5=Medium

[Models]
ResourcesFolder=scenery/modular_ports/
ResourcesRoot=modular_ports
ResourcesMesh=False
ResourcesMaterialFolder=scenery/materials/
ResourcesMaterial=pier_tx
[Particles]
SmallFireEffectClass=ModerateShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=SevereShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=OilTankFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffect=effects/explosions/emitters/missile_hit_ship
SecondaryExplosionEffectPosition=0,0,0
[Sounds]
SoundMode=1

[Submodels]
Submodel0=military_port_2(Clone)
Submodel1=military_port_2_warehouses
Submodel2=military_port_2_trans
Submodel3=military_port_2_piers
Submodel4=military_port_2_cranes
Submodel5=military_port_2_cargo
Submodel6=military_port_3(Clone)
Submodel7=military_port_3_cranes
Submodel8=military_port_3_decals
Submodel9=military_port_3_piers
Submodel10=military_port_3_spoil_heaps
Submodel11=military_port_3_trans
Submodel12=military_port_3_warehouses

[military_port_2(Clone)]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_2_concrete
ResourcesMaterialFolder=scenery/materials/
Material=concrete 
Position=-3.5749,0.1,9.5802
Rotation=0,90,0
Scale=1,1,1
[military_port_2_warehouses]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_2_warehouses
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1 
Position=-3.5749,0.1,9.5802
Rotation=0,90,0
Scale=1,1,1
[military_port_2_trans]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_2_trans
ResourcesMaterialFolder=scenery/materials/
Material=trans 
Position=-3.5749,0.1,9.5802
Rotation=0,90,0
Scale=1,1,1
[military_port_2_piers]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_2_piers
ResourcesMaterialFolder=scenery/materials/
Material=pier_tx 
Position=-3.5749,0.1,9.5802
Rotation=0,90,0
Scale=1,1,1
[military_port_2_cranes]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_2_cranes
ResourcesMaterialFolder=scenery/materials/
Material=harbour_crane 
Position=-3.5749,0.1,9.5802
Rotation=0,90,0
Scale=1,1,1
[military_port_2_cargo]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_2_cargo
ResourcesMaterialFolder=scenery/materials/
Material=ms_cargoatlas 
Position=-3.5749,0.1,9.5802
Rotation=0,90,0
Scale=1,1,1
[military_port_3(Clone)]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_3_concrete
ResourcesMaterialFolder=scenery/materials/
Material=concrete 
Position=12.14,0.1,6.97
Rotation=0,135,0
Scale=1,1,1
[military_port_3_cranes]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_3_cranes
ResourcesMaterialFolder=scenery/materials/
Material=harbour_crane 
Position=12.14,0.1,6.97
Rotation=0,135,0
Scale=1,1,1
[military_port_3_decals]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_3_decals
ResourcesMaterialFolder=scenery/modular industry/
Material=module_industry_decal 
Position=12.14,0.1,6.97
Rotation=0,135,0
Scale=1,1,1
[military_port_3_piers]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_3_piers
ResourcesMaterialFolder=scenery/materials/
Material=pier_tx 
Position=12.14,0.1,6.97
Rotation=0,135,0
Scale=1,1,1
[military_port_3_spoil_heaps]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_3_spoil_heaps
ResourcesMaterialFolder=scenery/modular industry/
Material=module_industry_decal 
Position=12.14,0.1,6.97
Rotation=0,135,0
Scale=1,1,1
[military_port_3_trans]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_3_trans
ResourcesMaterialFolder=scenery/materials/
Material=trans 
Position=12.14,0.1,6.97
Rotation=0,135,0
Scale=1,1,1
[military_port_3_warehouses]
ResourcesMeshFolder=scenery/modular_ports/
RootMesh=military_ports
Mesh=military_port_3_warehouses
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1 
Position=12.14,0.1,6.97
Rotation=0,135,0
Scale=1,1,1

[Colliders]
NumberOfColliders=46
Collider1=coll_mil_pt_3_buildings_9
Collider2=coll_mil_pt_3_buildings_8
Collider3=coll_mil_pt_3_buildings_7
Collider4=coll_mil_pt_3_buildings_6
Collider5=coll_mil_pt_3_buildings_5
Collider6=coll_mil_pt_3_buildings_4
Collider7=coll_mil_pt_3_buildings_3
Collider8=coll_mil_pt_3_buildings_2
Collider9=coll_mil_pt_3_buildings_1
Collider10=coll_mil_pt_3_pier_3
Collider11=coll_mil_pt_3_pier_2
Collider12=coll_mil_pt_3_pier_1
Collider13=coll_mil_pt_3_main_11
Collider14=coll_mil_pt_3_main_10
Collider15=coll_mil_pt_3_main_9
Collider16=coll_mil_pt_3_main_8
Collider17=coll_mil_pt_3_main_7
Collider18=coll_mil_pt_3_main_6
Collider19=coll_mil_pt_3_main_5
Collider20=coll_mil_pt_3_main_4
Collider21=coll_mil_pt_3_main_3
Collider22=coll_mil_pt_3_main_2
Collider23=coll_mil_pt_3_main
Collider24=coll_mil_pt_2_main_1
Collider25=coll_mil_pt_2_main_2
Collider26=coll_mil_pt_2_main_2b
Collider27=coll_mil_pt_2_main_3
Collider28=coll_mil_pt_2_pier_1
Collider29=coll_mil_pt_2_pier_2
Collider30=coll_mil_pt_2_pier_3
Collider31=coll_mil_pt_2_pier_4
Collider32=coll_mil_pt_2_pier_5
Collider33=coll_mil_pt_2_pier_6
Collider34=coll_mil_pt_2_pier_7
Collider35=coll_mil_pt_2_pier_8
Collider36=coll_mil_pt_2_pier_9
Collider37=coll_mil_pt_2_pier_10
Collider38=coll_mil_pt_2_pier_11
Collider39=coll_mil_pt_2_buildings_1
Collider40=coll_mil_pt_2_buildings_2
Collider41=coll_mil_pt_2_buildings_3
Collider42=coll_mil_pt_2_buildings_4
Collider43=coll_mil_pt_2_buildings_5
Collider44=coll_mil_pt_2_buildings_6
Collider45=coll_mil_pt_2_buildings_7
Collider46=coll_mil_pt_2_buildings_8

[coll_mil_pt_3_buildings_9]
Collider=Box
Position=15.93929,0.197,5.177483
Rotation=0,80.0002,0
Scale=0.7989259,0.1930801,2.536245
[coll_mil_pt_3_buildings_8]
Collider=Box
Position=15.89545,0.145,2.976967
Rotation=0,170,0
Scale=1.290795,0.09241184,0.4884652
[coll_mil_pt_3_buildings_7]
Collider=Box
Position=14.53709,0.145,2.741499
Rotation=0,170,0
Scale=1.290795,0.09241184,0.4884652
[coll_mil_pt_3_buildings_6]
Collider=Box
Position=10.95913,0.145,3.786604
Rotation=0,135,0
Scale=1.290795,0.09241184,0.4884651
[coll_mil_pt_3_buildings_5]
Collider=Box
Position=12.05373,0.2,7.845398
Rotation=0,135,0
Scale=1.456982,0.2011686,1.454035
[coll_mil_pt_3_buildings_4]
Collider=Box
Position=13.4736,0.258,8.723623
Rotation=0,-135.0002,0
Scale=2.346316,0.3180728,1.457839
[coll_mil_pt_3_buildings_3]
Collider=Box
Position=7.887459,0.178,5.537401
Rotation=0,45.0002,0
Scale=0.7519305,0.1609001,0.8856379
[coll_mil_pt_3_buildings_2]
Collider=Box
Position=8.103836,0.197,8.012276
Rotation=0,135,0
Scale=0.7989259,0.1930801,2.536245
[coll_mil_pt_3_buildings_1]
Collider=Box
Position=11.14793,0.269,11.37881
Rotation=0,135,0
Scale=1.824561,0.3514903,2.93049
[coll_mil_pt_3_pier_3]
Collider=Box
Position=6.80629,-0.394,9.796307
Rotation=0,135,0
Scale=1.220757,1,0.5371017
[coll_mil_pt_3_pier_2]
Collider=Box
Position=8.556381,-0.394,11.5464
Rotation=0,135,0
Scale=1.627675,1,0.5371017
[coll_mil_pt_3_pier_1]
Collider=Box
Position=9.124893,-0.394,6.387342
Rotation=0,135,0
Scale=4.260908,1,0.6227267
[coll_mil_pt_3_main_11]
Collider=Box
Position=7.318947,-0.394,7.244356
Rotation=0,135,0
Scale=1.144404,1,1.317282
[coll_mil_pt_3_main_10]
Collider=Box
Position=6.659218,-0.394,7.91823
Rotation=0,90.0001,0
Scale=3.563214,1,0.5997053
[coll_mil_pt_3_main_9]
Collider=Box
Position=7.630074,-0.394,6.30249
Rotation=0,135,0
Scale=2.034496,1,1.572874
[coll_mil_pt_3_main_8]
Collider=Box
Position=7.86554,-0.394,8.045509
Rotation=0,135,0
Scale=1.146195,1,3.495275
[coll_mil_pt_3_main_7]
Collider=Box
Position=16.19879,-0.394,3.109194
Rotation=0,80.7685,0
Scale=1.341621,1,4.901883
[coll_mil_pt_3_main_6]
Collider=Box
Position=18.32365,-0.394,4.087124
Rotation=0,135,0
Scale=1.934119,1,2.196085
[coll_mil_pt_3_main_5]
Collider=Box
Position=13.56694,-0.394,3.779533
Rotation=0,135,0
Scale=1.934119,1,3.029083
[coll_mil_pt_3_main_4]
Collider=Box
Position=10.88206,-0.394,4.864943
Rotation=0,135,0
Scale=3.886456,1,2.352686
[coll_mil_pt_3_main_3]
Collider=Box
Position=8.820839,-0.394,14.07642
Rotation=0,135,0
Scale=1.286864,1,2.688784
[coll_mil_pt_3_main_2]
Collider=Box
Position=10.99448,-0.394,11.51953
Rotation=0,135,0
Scale=1.852436,1,4.052493
[coll_mil_pt_3_main]
Collider=Box
Position=14.39567,-0.394,6.764938
Rotation=0,135,0
Scale=3.758907,1,7.487501
[coll_mil_pt_2_main_1]
Collider=Box
Position=-4.0429,-0.403,11.3902
Rotation=0,90,0
Scale=2.8,1,5.9675
[coll_mil_pt_2_main_2]
Collider=Box
Position=2.139107,-0.403,11.8002
Rotation=0,90,0
Scale=1.99809,1,6.415063
[coll_mil_pt_2_main_2b]
Collider=Box
Position=3.648102,-0.403,10.4622
Rotation=0,90,0
Scale=0.8438808,1,3.41101
[coll_mil_pt_2_main_3]
Collider=Box
Position=-9.489899,-0.403,11.8502
Rotation=0,90,0
Scale=1.898185,1,5.051862
[coll_mil_pt_2_pier_1]
Collider=Box
Position=-11.6029,-0.403,8.461201
Rotation=0,90,0
Scale=4.898801,1,0.8067193
[coll_mil_pt_2_pier_2]
Collider=Box
Position=-6.756897,-0.403,7.6702
Rotation=0,90,0
Scale=4.898801,1,0.5041995
[coll_mil_pt_2_pier_3]
Collider=Box
Position=-1.324898,-0.403,8.173201
Rotation=0,90,0
Scale=3.761763,1,0.5041995
[coll_mil_pt_2_pier_4]
Collider=Box
Position=2.4151,-0.403,8.173201
Rotation=0,90,0
Scale=3.761763,1,0.9075591
[coll_mil_pt_2_pier_5]
Collider=Box
Position=3.904106,-0.403,8.173199
Rotation=0,90,0
Scale=3.761763,1,0.5672244
[coll_mil_pt_2_pier_6]
Collider=Box
Position=5.114105,-0.403,8.173199
Rotation=0,90,0
Scale=3.761763,1,0.4750504
[coll_mil_pt_2_pier_7]
Collider=Box
Position=-0.6568985,-0.403,6.5812
Rotation=0,90,0
Scale=0.5501578,1,3.195457
[coll_mil_pt_2_pier_8]
Collider=Box
Position=2.147102,-0.403,6.5812
Rotation=0,90,0
Scale=0.5501578,1,1.048509
[coll_mil_pt_2_pier_9]
Collider=Box
Position=-4.794899,-0.403,6.5802
Rotation=0,90,0
Scale=0.5501578,1,3.714718
[coll_mil_pt_2_pier_10]
Collider=Box
Position=-6.309898,-0.403,5.3592
Rotation=0,95.0311,0
Scale=0.3859633,1,3.857735
[coll_mil_pt_2_pier_11]
Collider=Box
Position=-11.2659,-0.403,5.864201
Rotation=0,95.0311,0
Scale=0.480598,1,3.469223
[coll_mil_pt_2_buildings_1]
Collider=Box
Position=0.4341049,0.269,11.8492
Rotation=0,90,0
Scale=1.824561,0.3514903,2.93049
[coll_mil_pt_2_buildings_2]
Collider=Box
Position=-6.524895,0.197,11.3742
Rotation=0,0.0002,0
Scale=0.798926,0.1930801,2.536245
[coll_mil_pt_2_buildings_3]
Collider=Box
Position=4.520103,0.178,10.7842
Rotation=0,0.0002,0
Scale=0.7519304,0.1609001,0.8856379
[coll_mil_pt_2_buildings_4]
Collider=Box
Position=-8.539894,0.258,11.7422
Rotation=0,179.9998,0
Scale=2.346316,0.3180728,1.45784
[coll_mil_pt_2_buildings_5]
Collider=Box
Position=-10.8509,0.2,11.7442
Rotation=0,90,0
Scale=1.456982,0.2011686,1.454035
[coll_mil_pt_2_buildings_6]
Collider=Box
Position=3.907104,0.145,8.776199
Rotation=0,90,0
Scale=1.290795,0.09241184,0.488465
[coll_mil_pt_2_buildings_7]
Collider=Box
Position=2.237099,0.145,8.9072
Rotation=0,90,0
Scale=1.290795,0.09241184,0.488465
[coll_mil_pt_2_buildings_8]
Collider=Box
Position=2.237099,0.145,7.531199
Rotation=0,90,0
Scale=1.290795,0.09241184,0.488465
