[General]
UnitType=LandUnit
LandUnitSubType=Installation //Supported values: Airbase,SAM,Installation,MobileUnit,Radar,Port
DisplayClassName=Fueltanks
DefaultCameraDistance=10.0
MinCameraDistanceForeAft=5
MinCameraDistanceBroadside=5
CameraPivotHeight=0.15

# Hull armor: None, Minor, Moderate, Heavy
ArmorType=Minor
DamagePoints=50  //systems damage contribution substracted from this when systems destroyed, when becomes less than zero, the whole unit is considered being destroyed

[Tacview]
Tag=Ground+Vehicle

[AI]
UnitScoreValue=5               // value for calculation of mission score
Role=Target

[SensorData]
#Visual
VisualIdentificationRange=20.0
IRSignature=Large
# Radar related (RCS => radar cross section)
RCS=Large

############################################################
# Animation references (optional)
############################################################
[Animations]
NumberOfAnimationReferences=0
AnimationFile_1=animations_wp_sam_site_sa-5

[ControlSystem]
############################################################
# Control System (CIC)
############################################################
SystemGroup=SG_CIC
Collider=coll_fueltanks_1
ModuleType=CIC
Integrity=60 //the number of hit points substracted from the overall damage points count when the system is destroyed
ArmorType=Minor
ResilenceModifier=3.0 //the multiplier that affects the required accumulated damage level for the system to achieve new damage tier. E.g. if this parameter is equal to 2.0 and Severe damage tier value is 15, the actual Severe damage value will be no less than 2 * 15 = 30

[---------- Sensor Systems ----------]
[SensorSystems]
NumberOfSensorSystems=1
#---------- Visual ----------
[SensorSystem1] #Bridge
# Bridge. Does not need SystemGroup and Collider because we do not want ship to loose ability to VID targets
Type=Visual
SystemName=Eyes
Mount=Dummy
MountPosition=0,0.026,0 #Crew on ground level
ModuleType=Bridge
Integrity=0

[---------- Weapon Systems ----------]
############################################################
# Weapon Systems
############################################################
[WeaponSystems]
NumberOfWeaponSystems=0

[---------- HitZones ----------]
[HitZones]
NumberOfHitZones=6

[HitZone1]
SystemGroup=SG_Tanks_1
Collider=coll_fueltanks_1
ModuleType=HitZone
Integrity=20 //the number of hit points substracted from the overall damage points count when the system is destroyed
ResilenceModifier=2.0 //the multiplier that affects the required accumulated damage level for the system to achieve new damage tier. E.g. if this parameter is equal to 2.0 and Severe damage tier value is 15, the actual Severe damage value will be no less than 2 * 15 = 30

[HitZone2]
SystemGroup=SG_Tanks_2
Collider=coll_fueltanks_2
ModuleType=HitZone
Integrity=20 //the number of hit points substracted from the overall damage points count when the system is destroyed
ResilenceModifier=3.0 //the multiplier that affects the required accumulated damage level for the system to achieve new damage tier. E.g. if this parameter is equal to 2.0 and Severe damage tier value is 15, the actual Severe damage value will be no less than 2 * 15 = 30

[HitZone3]
SystemGroup=SG_Tanks_3
Collider=coll_fueltanks_3
ModuleType=HitZone
Integrity=20 //the number of hit points substracted from the overall damage points count when the system is destroyed
ResilenceModifier=2.0 //the multiplier that affects the required accumulated damage level for the system to achieve new damage tier. E.g. if this parameter is equal to 2.0 and Severe damage tier value is 15, the actual Severe damage value will be no less than 2 * 15 = 30

[HitZone4]
SystemGroup=SG_Tanks_4
Collider=coll_fueltanks_4
ModuleType=HitZone
Integrity=20 //the number of hit points substracted from the overall damage points count when the system is destroyed
ResilenceModifier=2.0 //the multiplier that affects the required accumulated damage level for the system to achieve new damage tier. E.g. if this parameter is equal to 2.0 and Severe damage tier value is 15, the actual Severe damage value will be no less than 2 * 15 = 30

[HitZone5]
SystemGroup=SG_Tanks_5
Collider=coll_fueltanks_5
ModuleType=HitZone
Integrity=20 //the number of hit points substracted from the overall damage points count when the system is destroyed
ResilenceModifier=3.0 //the multiplier that affects the required accumulated damage level for the system to achieve new damage tier. E.g. if this parameter is equal to 2.0 and Severe damage tier value is 15, the actual Severe damage value will be no less than 2 * 15 = 30

[HitZone6]
SystemGroup=SG_Tanks_6
Collider=coll_fueltanks_6
ModuleType=HitZone
Integrity=20 //the number of hit points substracted from the overall damage points count when the system is destroyed
ResilenceModifier=2.0 //the multiplier that affects the required accumulated damage level for the system to achieve new damage tier. E.g. if this parameter is equal to 2.0 and Severe damage tier value is 15, the actual Severe damage value will be no less than 2 * 15 = 30

[---------- WeaponMagazines ----------]
############################################################
# Weapon Magazine Systems
############################################################

#Enemy units will use this local coordinates to aim their attacks to

[TargetingData]
NumberOfTargetPoints=6
TargetPointPosition1=-1.02,0.3,-2.785
TargetPointAssociatedSystems1=HitZone1
TargetPointPriority1=High
TargetPointPosition2=-1.02,0.3,-1.767
TargetPointAssociatedSystems2=HitZone2
TargetPointPriority2=High
TargetPointPosition3=0.412,0.3,-0.987
TargetPointAssociatedSystems3=HitZone3
TargetPointPriority3=Medium
//
TargetPointPosition4=1.01,0.3,0.784
TargetPointAssociatedSystems4=HitZone4
TargetPointPriority4=Medium
TargetPointPosition5=-0.312,0.2,1.61
TargetPointAssociatedSystems5=HitZone5
TargetPointPriority5=High
TargetPointPosition6=0.769,0.2,-2.313
TargetPointAssociatedSystems6=HitZone6
TargetPointPriority6=Low


[Models]

############################################################
# Internal Resources folder related
############################################################

#ResourcesFolder=ground objects/watchtower/
#ResourcesRoot=watchtower
#ResourcesMesh=watchtower
#ResourcesDamagedMesh=watchtower_d
#ResourcesMaterialFolder=ground objects/watchtower/
#ResourcesMaterial=watchtower_mat

ResourcesFolder=scenery/modular industry/
ResourcesRoot=module_industry_tanks_large_brown
ResourcesMesh=module_industry_tanks_large_brown_decal
ResourcesMaterial=module_industry_decal
############################################################

NumberOfSubModels=1

SubModel1=Tanks

############################################################
# Scenery model parts
############################################################

[Tanks]
Mesh=module_industry_tanks_large_brown
DamagedMesh=module_industry_tanks_large_brown
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1

[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=1
AmbientAudioClip=audio/ships/Ship-Turbine-Medium
AmbientAudioPosition=0,0,-0.35
AmbientAudioRollOff=Logarithmic
AmbientAudioDistance=1,20
AmbientAudioPitchRange=1.0,1.6
AmbientAudioVolume=0.5
AmbientAudioAudibility=AboveAndBelow  // layer of sound audibility: Above, Below, AboveAndBelow

[Particles]
SmallFireEffectClass=ModerateShipFire	//SmallShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=SevereShipFire	//ModerateShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=SevereShipFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffect=effects/explosions/emitters/missile_hit_ship
SecondaryExplosionEffectPosition=0,0,0

[---------- Colliders ----------]
############################################################
# Colliders definition
############################################################
[Colliders]
NumberOfColliders=6
NumberOfMeshColliders=0
UseKinematicCollision=true
Collider1=coll_fueltanks_1
Collider2=coll_fueltanks_2
Collider3=coll_fueltanks_3
Collider4=coll_fueltanks_4
Collider5=coll_fueltanks_5
Collider6=coll_fueltanks_6

#MeshCollider1=coll_decal

[coll_fueltanks_1]
Collider=box
Position=-1.02,0,-2.785
Rotation=0,0,0
Scale=1,1,1

[coll_fueltanks_2]
Collider=box
Position=-1.02,0,-1.767
Rotation=0,0,0
Scale=1,1,1

[coll_fueltanks_3]
Collider=box
Position=0.412,0,-0.987
Rotation=0,0,0
Scale=1.2,1,1.1

[coll_fueltanks_4]
Collider=box
Position=1.01,0,0.784
Rotation=0,56,0
Scale=1.1,1,1.1

[coll_fueltanks_5]
Collider=box
Position=-0.312,0,1.61
Rotation=0,38,0
Scale=1.36,1,2.25

[coll_fueltanks_6]
Collider=box
Position=0.769,0,-2.313
Rotation=0,0,0
Scale=0.264,0.595,1.125