[General]
UnitType=LandUnit
LandUnitSubType=Installation //Supported values: Airbase,SAM,Installation,MobileUnit,Radar,Port
DisplayClassName=Industrial_buildings_2
DefaultCameraDistance=2.0
MinCameraDistanceForeAft=1
MinCameraDistanceBroadside=1
CameraPivotHeight=0.15

# Hull armor: None, Minor, Moderate, Heavy
ArmorType=Minor
DamagePoints=50  //systems damage contribution substracted from this when systems destroyed, when becomes less than zero, the whole unit is considered being destroyed

[Tacview]
Tag=Ground+Vehicle

[AI]
UnitScoreValue=5               // value for calculation of mission score
Role=Target

[SensorData]
#Visual
VisualIdentificationRange=15.0
IRSignature=Medium
# Radar related (RCS => radar cross section)
RCS=SemiSmall

############################################################
# Animation references (optional)
############################################################
[Animations]
NumberOfAnimationReferences=0
AnimationFile_1=none

[ControlSystem]
############################################################
# Control System (CIC)
############################################################
SystemGroup=SG_CIC
Collider=coll_industry_buildings_2_1
ModuleType=CIC
Integrity=50 //the number of hit points substracted from the overall damage points count when the system is destroyed
ArmorType=Minor
ResilenceModifier=3.0 //the multiplier that affects the required accumulated damage level for the system to achieve new damage tier. E.g. if this parameter is equal to 2.0 and Severe damage tier value is 15, the actual Severe damage value will be no less than 2 * 15 = 30

[---------- Sensor Systems ----------]
[SensorSystems]
NumberOfSensorSystems=1
#---------- Visual ----------
[SensorSystem1] #Bridge
# Bridge. Does not need SystemGroup and Collider because we do not want ship to loose ability to VID targets
Type=Visual
SystemName=Eyes
Mount=Dummy
MountPosition=0,0.026,0 #Crew on ground level
ModuleType=Bridge
Integrity=0

[---------- Weapon Systems ----------]
############################################################
# Weapon Systems
############################################################
[WeaponSystems]
NumberOfWeaponSystems=0

[---------- HitZones ----------]
[HitZones]
NumberOfHitZones=3

[HitZone1]
SystemGroup=SG_Industry_1
Collider=coll_industry_buildings_2_1
ModuleType=HitZone
Integrity=20 //the number of hit points substracted from the overall damage points count when the system is destroyed
ResilenceModifier=2.0 //the multiplier that affects the required accumulated damage level for the system to achieve new damage tier. E.g. if this parameter is equal to 2.0 and Severe damage tier value is 15, the actual Severe damage value will be no less than 2 * 15 = 30

[HitZone2]
SystemGroup=SG_Industry_2
Collider=coll_industry_buildings_2_2
ModuleType=HitZone
Integrity=20 //the number of hit points substracted from the overall damage points count when the system is destroyed
ResilenceModifier=3.0 //the multiplier that affects the required accumulated damage level for the system to achieve new damage tier. E.g. if this parameter is equal to 2.0 and Severe damage tier value is 15, the actual Severe damage value will be no less than 2 * 15 = 30

[HitZone3]
SystemGroup=SG_Industry_3
Collider=coll_industry_buildings_2_3
ModuleType=HitZone
Integrity=20 //the number of hit points substracted from the overall damage points count when the system is destroyed
ResilenceModifier=2.0 //the multiplier that affects the required accumulated damage level for the system to achieve new damage tier. E.g. if this parameter is equal to 2.0 and Severe damage tier value is 15, the actual Severe damage value will be no less than 2 * 15 = 30

[---------- WeaponMagazines ----------]
############################################################
# Weapon Magazine Systems
############################################################

#Enemy units will use this local coordinates to aim their attacks to

[TargetingData]
NumberOfTargetPoints=3
TargetPointPosition1=-0.25,0.2,-0.343
TargetPointAssociatedSystems1=HitZone1
TargetPointPriority1=High
TargetPointPosition2=0.2,0.2,0.325
TargetPointAssociatedSystems2=HitZone2
TargetPointPriority2=High
TargetPointPosition3=1.178,0.2,-0.24
TargetPointAssociatedSystems3=HitZone3
TargetPointPriority3=Medium

[Models]

############################################################
# Internal Resources folder related
############################################################

#ResourcesFolder=ground objects/watchtower/
#ResourcesRoot=watchtower
#ResourcesMesh=watchtower
#ResourcesDamagedMesh=watchtower_d
#ResourcesMaterialFolder=ground objects/watchtower/
#ResourcesMaterial=watchtower_mat

ResourcesFolder=scenery/modular industry/
ResourcesRoot=module_industry_buildings_2
ResourcesMesh=module_industry_buildings_2_decal
ResourcesMaterial=module_industry_decal
############################################################

NumberOfSubModels=1
SubModel1=Industry

############################################################
# Scenery model parts
############################################################

[Industry]
Mesh=module_industry_buildings_2
DamagedMesh=module_industry_buildings_2
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1

[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=1
AmbientAudioClip=audio/ships/Ship-Turbine-Medium
AmbientAudioPosition=0,0,-0.35
AmbientAudioRollOff=Logarithmic
AmbientAudioDistance=1,20
AmbientAudioPitchRange=1.0,1.6
AmbientAudioVolume=0.5
AmbientAudioAudibility=AboveAndBelow  // layer of sound audibility: Above, Below, AboveAndBelow

[Particles]
SmallFireEffectClass=SmallShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=ModerateShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=SevereShipFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffect=effects/explosions/emitters/missile_hit_ship
SecondaryExplosionEffectPosition=0,0,0

[---------- Colliders ----------]
############################################################
# Colliders definition
############################################################
[Colliders]
NumberOfColliders=3
NumberOfMeshColliders=0
UseKinematicCollision=true
Collider1=coll_industry_buildings_2_1
Collider2=coll_industry_buildings_2_2
Collider3=coll_industry_buildings_2_3

#MeshCollider1=coll_decal

[coll_industry_buildings_2_1]
Collider=box
Position=0,0,-0.343
Rotation=0,0,0
Scale=1.468,0.39,0.382

[coll_industry_buildings_2_2]
Collider=box
Position=0,0,0.325
Rotation=0,0,0
Scale=1.468,0.39,0.382

[coll_industry_buildings_2_3]
Collider=box
Position=1.178,0,-0.091
Rotation=0,90,0
Scale=1.1,0.6,0.3