[General]
UnitType=LandUnit
LandUnitSubType=Installation //Supported values: Airbase,SAM,Installation,MobileUnit,Radar,Port
DisplayClassName=Industrial_buildings_3
DefaultCameraDistance=2.0
MinCameraDistanceForeAft=1
MinCameraDistanceBroadside=1
CameraPivotHeight=0.15

# Hull armor: None, Minor, Moderate, Heavy
ArmorType=Minor
DamagePoints=50  //systems damage contribution substracted from this when systems destroyed, when becomes less than zero, the whole unit is considered being destroyed

[Tacview]
Tag=Ground+Vehicle

[AI]
UnitScoreValue=5               // value for calculation of mission score
Role=Target

[SensorData]
#Visual
VisualIdentificationRange=15.0
IRSignature=Medium
# Radar related (RCS => radar cross section)
RCS=SemiSmall

############################################################
# Animation references (optional)
############################################################
[Animations]
NumberOfAnimationReferences=0
AnimationFile_1=none

[ControlSystem]
############################################################
# Control System (CIC)
############################################################
SystemGroup=SG_CIC
Collider=coll_industry_buildings_3_1
ModuleType=CIC
Integrity=100 //the number of hit points substracted from the overall damage points count when the system is destroyed
ArmorType=Minor
ResilenceModifier=3.0 //the multiplier that affects the required accumulated damage level for the system to achieve new damage tier. E.g. if this parameter is equal to 2.0 and Severe damage tier value is 15, the actual Severe damage value will be no less than 2 * 15 = 30

[---------- Sensor Systems ----------]
[SensorSystems]
NumberOfSensorSystems=1
#---------- Visual ----------
[SensorSystem1] #Bridge
# Bridge. Does not need SystemGroup and Collider because we do not want ship to loose ability to VID targets
Type=Visual
SystemName=Eyes
Mount=Dummy
MountPosition=0,0.026,0 #Crew on ground level
ModuleType=Bridge
Integrity=0

[---------- Weapon Systems ----------]
############################################################
# Weapon Systems
############################################################
[WeaponSystems]
NumberOfWeaponSystems=0

[---------- HitZones ----------]
[HitZones]
NumberOfHitZones=6

[HitZone1]
SystemGroup=SG_Industry_1
Collider=coll_industry_buildings_3_1
ModuleType=HitZone
Integrity=20 //the number of hit points substracted from the overall damage points count when the system is destroyed
ResilenceModifier=2.0 //the multiplier that affects the required accumulated damage level for the system to achieve new damage tier. E.g. if this parameter is equal to 2.0 and Severe damage tier value is 15, the actual Severe damage value will be no less than 2 * 15 = 30

[HitZone2]
SystemGroup=SG_Industry_2
Collider=coll_industry_buildings_3_2
ModuleType=HitZone
Integrity=20 //the number of hit points substracted from the overall damage points count when the system is destroyed
ResilenceModifier=3.0 //the multiplier that affects the required accumulated damage level for the system to achieve new damage tier. E.g. if this parameter is equal to 2.0 and Severe damage tier value is 15, the actual Severe damage value will be no less than 2 * 15 = 30

[HitZone3]
SystemGroup=SG_Industry_3
Collider=coll_industry_buildings_3_3
ModuleType=HitZone
Integrity=20 //the number of hit points substracted from the overall damage points count when the system is destroyed
ResilenceModifier=2.0 //the multiplier that affects the required accumulated damage level for the system to achieve new damage tier. E.g. if this parameter is equal to 2.0 and Severe damage tier value is 15, the actual Severe damage value will be no less than 2 * 15 = 30

[HitZone4]
SystemGroup=SG_Industry_1
Collider=coll_industry_buildings_3_4
ModuleType=HitZone
Integrity=20 //the number of hit points substracted from the overall damage points count when the system is destroyed
ResilenceModifier=2.0 //the multiplier that affects the required accumulated damage level for the system to achieve new damage tier. E.g. if this parameter is equal to 2.0 and Severe damage tier value is 15, the actual Severe damage value will be no less than 2 * 15 = 30

[HitZone5]
SystemGroup=SG_Industry_2
Collider=coll_industry_buildings_3_5
ModuleType=HitZone
Integrity=20 //the number of hit points substracted from the overall damage points count when the system is destroyed
ResilenceModifier=3.0 //the multiplier that affects the required accumulated damage level for the system to achieve new damage tier. E.g. if this parameter is equal to 2.0 and Severe damage tier value is 15, the actual Severe damage value will be no less than 2 * 15 = 30

[HitZone6]
SystemGroup=SG_Industry_3
Collider=coll_industry_buildings_3_6
ModuleType=HitZone
Integrity=20 //the number of hit points substracted from the overall damage points count when the system is destroyed
ResilenceModifier=2.0 //the multiplier that affects the required accumulated damage level for the system to achieve new damage tier. E.g. if this parameter is equal to 2.0 and Severe damage tier value is 15, the actual Severe damage value will be no less than 2 * 15 = 30


[---------- WeaponMagazines ----------]
############################################################
# Weapon Magazine Systems
############################################################

#Enemy units will use this local coordinates to aim their attacks to

[TargetingData]
NumberOfTargetPoints=6
TargetPointPosition1=1.378,0.102,-0.487
TargetPointAssociatedSystems1=HitZone1
TargetPointPriority1=High
TargetPointPosition2=-1.41,0.102,-1.028
TargetPointAssociatedSystems2=HitZone2
TargetPointPriority2=High
TargetPointPosition3=-1.8,0.102,1.154
TargetPointAssociatedSystems3=HitZone3
TargetPointPriority3=Medium
TargetPointPosition4=0.137,0.102,0.761
TargetPointAssociatedSystems4=HitZone4
TargetPointPriority4=Medium
TargetPointPosition5=2.502,0.102,-0.581
TargetPointAssociatedSystems5=HitZone5
TargetPointPriority5=Medium
TargetPointPosition6=1.486,0.33,1.213
TargetPointAssociatedSystems6=HitZone6
TargetPointPriority6=Medium

[Models]

############################################################
# Internal Resources folder related
############################################################

#ResourcesFolder=ground objects/watchtower/
#ResourcesRoot=watchtower
#ResourcesMesh=watchtower
#ResourcesDamagedMesh=watchtower_d
#ResourcesMaterialFolder=ground objects/watchtower/
#ResourcesMaterial=watchtower_mat

ResourcesFolder=scenery/modular industry/
ResourcesRoot=module_industry_buildings_3
ResourcesMesh=module_industry_buildings_3_decal
ResourcesMaterial=module_industry_decal
############################################################

NumberOfSubModels=2
SubModel1=Industry
SubModel2=Refinery

############################################################
# Scenery model parts
############################################################

[Industry]
Mesh=module_industry_buildings_3
DamagedMesh=module_industry_buildings_3
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1

[Refinery]
Mesh=module_industry_buildings_3_refinery
DamagedMesh=module_industry_buildings_3_refinery
ResourcesMaterialFolder=scenery/materials/
Material=refinery_main_tx

[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=1
AmbientAudioClip=audio/ships/Ship-Turbine-Medium
AmbientAudioPosition=0,0,-0.35
AmbientAudioRollOff=Logarithmic
AmbientAudioDistance=1,20
AmbientAudioPitchRange=1.0,1.6
AmbientAudioVolume=0.5
AmbientAudioAudibility=AboveAndBelow  // layer of sound audibility: Above, Below, AboveAndBelow

[Particles]
SmallFireEffectClass=SmallShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=ModerateShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=SevereShipFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffect=effects/explosions/emitters/missile_hit_ship
SecondaryExplosionEffectPosition=0,0,0

[---------- Colliders ----------]
############################################################
# Colliders definition
############################################################
[Colliders]
NumberOfColliders=6
NumberOfMeshColliders=0
UseKinematicCollision=true
Collider1=coll_industry_buildings_3_1
Collider2=coll_industry_buildings_3_2
Collider3=coll_industry_buildings_3_3
Collider4=coll_industry_buildings_3_4
Collider5=coll_industry_buildings_3_5
Collider6=coll_industry_buildings_3_6

[coll_industry_buildings_3_1]
Collider=Box
Position=-1.152,0.085,-1.153
Rotation=0,0,0
Scale=1.813274,0.39,1.185422

[coll_industry_buildings_3_2]
Collider=Box
Position=1.42,0.085,-0.639
Rotation=0,270,0
Scale=1.132357,0.39,0.8104511

[coll_industry_buildings_3_3]
Collider=Box
Position=2.79,0.055,-0.454
Rotation=0,135.0001,0
Scale=1.1,0.2010981,1.027961

[coll_industry_buildings_3_4]
Collider=Box
Position=-1.796,0.078,1.081
Rotation=0,0,0
Scale=0.68181,0.2403244,0.68181

[coll_industry_buildings_3_5]
Collider=Box
Position=0.027,0.064,0.833
Rotation=0,0,0
Scale=0.8660989,0.1521902,1.243893

[coll_industry_buildings_3_6]
Collider=Box
Position=1.441,0.229,1.203
Rotation=0,0,0
Scale=0.2,0.43,0.2
