[General]
UnitType=LandUnit
LandUnitSubType=Port //Supported values: Airbase,SAM,Installation,MobileUnit,Radar,Port
DefaultCameraDistance=12.0
MinCameraDistanceForeAft=5.8
MinCameraDistanceBroadside=5.8
CameraPivotHeight=0.3
Length=352.1

# Hull armor: None, Minor, Moderate, Heavy
ArmorType=Minor
DamagePoints=350  //systems damage contribution substracted from this when systems destroyed, when becomes less than zero, the whole unit is considered being destroyed

[Tacview]
Tag=Ground+Vehicle

[AI]
UnitScoreValue=10              // value for calculation of mission score
Role=Target

[SensorData]
#Visual
VisualIdentificationRange=10  // Camouflaged  (x0.5)
IRSignature=Medium
# Radar related (RCS => radar cross section)
RCS=Small

[---------- Sensor Systems ----------]
############################################################
# Sensor Systems
############################################################
[SensorSystems]
NumberOfSensorSystems=1
#---------- Visual ----------
[SensorSystem1] #Bridge
# Bridge. Does not need SystemGroup and Collider because we do not want ship to loose ability to VID targets
Type=Visual
SystemName=Optics
Mount=Dummy
MountPosition=0,0.375,0
ModuleType=Bridge
Collider=coll_hangar_1
Integrity=20
[---------- HitZones ----------]
[HitZones]
NumberOfHitZones=6
[HitZone1]
SystemName=Hangar 1
Collider=coll_hangar_1
Integrity=100 //the number of hit points substracted from the overall damage points count when the system is destroyed

[HitZone2]
SystemName=Small Hangar 1
Collider=coll_small_hangar_1
Integrity=80 //the number of hit points substracted from the overall damage points count when the system is destroyed

[HitZone3]
SystemName=Warehouse 2
Collider=coll_warehouses_1
Integrity=100 //the number of hit points substracted from the overall damage points count when the system is destroyed

[HitZone4]
SystemName=Storage building 1
Collider=coll_storage_1
Integrity=80 //the number of hit points substracted from the overall damage points count when the system is destroyed

[HitZone5]
SystemName=Small warehouse 1
Collider=coll_small_warehouses
Integrity=80 //the number of hit points substracted from the overall damage points count when the system is destroyed

[HitZone6]
SystemName=Small warehouses 4
Collider=coll_small_warehouses_4
Integrity=80 //the number of hit points substracted from the overall damage points count when the system is destroyed


[--------------------------- Target Points definitions ---------------------------]
[TargetingData]
NumberOfTargetPoints=6

#Hangar 1
TargetPointPosition1=-0.99,0.05,4.13
TargetPointAssociatedSystems1=HitZone1
TargetPointPriority1=Medium
#Small Hangar 1
TargetPointPosition2=1.74,0.041,-0.95
TargetPointAssociatedSystems2=HitZone2
TargetPointPriority2=Low
#Warehouses 2
TargetPointPosition3=-2.06,-0.026,-2.31
TargetPointAssociatedSystems3=HitZone3
TargetPointPriority3=High
#Storage 1
TargetPointPosition4=-0.24,0.052,-2.69
TargetPointAssociatedSystems4=HitZone4
TargetPointPriority4=Medium
#Small warehouses
TargetPointPosition5=-4.97,0.052,2.83
TargetPointAssociatedSystems5=HitZone5
TargetPointPriority5=Medium
#Small warehouses 4
TargetPointPosition6=3.86,0.052,-4.25
TargetPointAssociatedSystems6=TODO
TargetPointPriority6=Medium
[--------------------------- Mesh definitions ---------------------------]
[Models]
############################################################
# Internal Resources folder related
############################################################

ResourcesFolder=scenery/warehouse_2/
ResourcesRoot=warehouses_2
ResourcesMesh=warehouses_2_buildings
ResourcesDamagedMesh=warehouses_2_d
ResourcesMaterialFolder=scenery/materials/
ResourcesMaterial=industrial_buildings_ne_us_1
############################################################

[Submodels]

SubModel1=Concrete
SubModel2=Cargo
SubModel3=Containers
SubModel4=Fences
SubModel6=Lampposts
SubModel7=Roads
SubModel8=Tanks

[Concrete]
Mesh=warehouses_2_concrete
ResourcesMaterialFolder=scenery/materials/
Material=concrete_bm
HideWithActiveDamageModel=False

[Cargo]
Mesh=warehouses_2_cargo
ResourcesMaterialFolder=scenery/materials/
Material=ms_cargoatlas
HideWithActiveDamageModel=False

[Containers]
Mesh=warehouses_2_containers
ResourcesMaterialFolder=scenery/materials/
Material=containers_tiled
HideWithActiveDamageModel=False

[Fences]
Mesh=warehouses_2_fences
ResourcesMaterialFolder=scenery/materials/
Material=airbase_fence
HideWithActiveDamageModel=False

[Lampposts]
Mesh=warehouses_2_lampposts
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1
HideWithActiveDamageModel=False

[Roads]
Mesh=warehouses_2_roads
ResourcesMaterialFolder=scenery/materials/
Material=roads
HideWithActiveDamageModel=False

[Tanks]
Mesh=warehouses_2_tanks
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1
HideWithActiveDamageModel=False

#[Boat_Hangars_Flags]
#Mesh=warehouses_2_boat_hangars_flags
#ResourcesMaterialFolder=ships/materials/
#Material=flag_vietnam
#HideWithActiveDamageModel=True

[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=1
AmbientAudioClip=audio/ships/Ship-Turbine-Medium
AmbientAudioPosition=0,0,-0.35
AmbientAudioRollOff=Logarithmic
AmbientAudioDistance=1,20
AmbientAudioPitchRange=1.0,1.6
AmbientAudioVolume=0.0
AmbientAudioAudibility=Above  // layer of sound audibility: Above, Below, AboveAndBelow

[Particles]
SmallFireEffectClass=SmallShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=SmallShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=SmallShipFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffect=effects/explosions/emitters/missile_hit_ship
SecondaryExplosionEffectPosition=0,0,0

[---------- Colliders ----------]
############################################################
# Colliders definition
############################################################
[Colliders]
NumberOfColliders=18
Collider1=coll_hangar_1
Collider2=coll_hangar_2
Collider3=coll_hangar_3
Collider4=coll_small_hangar_1
Collider5=coll_small_hangar_2
Collider6=coll_small_hangar_3
Collider7=coll_small_hangar_4
Collider8=coll_small_hangar_5
Collider9=coll_warehouses_1
Collider10=coll_warehouses_2
Collider11=coll_storage_1
Collider12=coll_storage_2
Collider13=coll_storage_3
Collider14=coll_storage_4
Collider15=coll_small_warehouses
Collider16=coll_small_warehouses_2
Collider17=coll_small_warehouses_3
Collider18=coll_small_warehouses_4
[coll_hangar_1]
Collider=Box
Position=-0.252,0.102,4.474
Rotation=0,-48.7111,0
Scale=2.663616,0.20625,1.559763
[coll_hangar_2]
Collider=Box
Position=2.509,0.102,3.701
Rotation=0,-48.5813,0
Scale=2.981387,0.20625,0.700312
[coll_hangar_3]
Collider=Box
Position=4.054,0.102,2.579
Rotation=0,-49.9291,0
Scale=0.8030051,0.20625,0.70004
[coll_small_hangar_1]
Collider=Box
Position=1.79,0.08200002,-0.81
Rotation=0,0,0
Scale=0.6791524,0.1552676,0.8
[coll_small_hangar_2]
Collider=Box
Position=1.78,0.14,-2.24
Rotation=0,0,0
Scale=0.6791524,0.2826914,0.8
[coll_small_hangar_3]
Collider=Box
Position=1.74,0.14,-4.06
Rotation=0,0,0
Scale=0.6791524,0.2826914,0.8
[coll_small_hangar_4]
Collider=Box
Position=6.561,0.082,-5.631
Rotation=0,-49.8384,0
Scale=0.6900868,0.1552676,0.8
[coll_small_hangar_5]
Collider=Box
Position=-5.67,0.102,6.35
Rotation=0,-34.6291,0
Scale=0.6791524,0.20625,0.8
[coll_warehouses_1]
Collider=Box
Position=-2.092,0.076,-1.786
Rotation=0,-89.9998,0
Scale=2.327377,0.1353516,0.40625
[coll_warehouses_2]
Collider=Box
Position=-2.08,0.07599998,-4.53
Rotation=0,-90,0
Scale=2.327377,0.1353516,0.40625
[coll_storage_1]
Collider=Box
Position=-0.429,0.098,-2.658
Rotation=0,0.0002,0
Scale=1.290717,0.1890088,0.4764375
[coll_storage_2]
Collider=Box
Position=-0.429,0.098,-3.659
Rotation=0,0.0002,0
Scale=1.290717,0.1890088,0.4764375
[coll_storage_3]
Collider=Box
Position=-0.429,0.098,-4.639
Rotation=0,0.0002,0
Scale=1.290717,0.1890088,0.4764375
[coll_storage_4]
Collider=Box
Position=-0.429,0.098,-5.615
Rotation=0,0.0002,0
Scale=1.290717,0.1890088,0.4764375
[coll_small_warehouses]
Collider=Box
Position=-5.039,0.045,2.978
Rotation=0,-89.9998,0
Scale=1.265888,0.08585156,0.4704219
[coll_small_warehouses_2]
Collider=Box
Position=-5.039,0.04500002,1.47
Rotation=0,-89.9998,0
Scale=1.265888,0.08585156,0.4704219
[coll_small_warehouses_3]
Collider=Box
Position=-5.039,0.04500002,-1.61
Rotation=0,-89.9998,0
Scale=1.265888,0.08585156,0.4704219
[coll_small_warehouses_4]
Collider=Box
Position=3.376,0.04500002,-4.224
Rotation=0,0,0
Scale=1.265888,0.08585156,0.4704219
