[General]
UnitType=LandUnit
LandUnitSubType=MissileSite
#IsMobile=True

DefaultCameraDistance=0.8
MinCameraDistanceForeAft=0.3
MinCameraDistanceBroadside=0.3
CameraPivotHeight=0.03

GroundOffset=0
AutoFlatten=False
MaskVegetation=True

Length=13.6                     // in meters
Beam=2.8                        // in meters
Range=270                       // in miles

# Hull armor: None, Minor, Moderate, Heavy
ArmorType=None
DamagePoints=3  //systems damage contribution substracted from this when systems destroyed, when becomes less than zero, the whole unit is considered being destroyed

[Tacview]
Name=ASC Redut
Tag=Ground+AntiShip

[Physics]
HorsePower=525
Mass=21                        // in tons

MaxForwardVelocity=21.6        // in knots
MaxBackwardVelocity=5.5        // in knots
Braking=8                      // knots/sec
TurnRate=8                     // in degrees per second

[AI]
UnitScoreValue=0.3             // value for calculation of mission score
Role=ASuW,ASM

[ControlSystem]
Collider=coll_hitbox  // makes unit destroyable
Integrity=4

[SensorData]
#Visual
VisualIdentificationRange=2.5  // Camouflaged  (x0.5)
IRSignature=Small
# Radar related (RCS => radar cross section)
RCS=Small

[Animations]
NumberOfAnimationReferences=1
AnimationFile_1=animations_redut_launcher

[---------- Sensor Systems ----------]
[SensorSystems]
NumberOfSensorSystems=2

#---------- Visual ----------
[SensorSystem1] #Bridge
# Bridge. Does not need SystemGroup and Collider because we do not want ship to loose ability to VID targets
Type=Visual
SystemName=Optics
Mount=Dummy
MountPosition=0,0.024,0.05
ModuleType=Bridge
Integrity=0

[SensorSystem2]  #Plinth_Net
#"Uspeh-U": P-35 Missile tracking and control. Not present IRL, external guidance control is used.
Type=Radar
SystemName=Plinth_Net
Mount=Dummy

[---------- Weapon Systems ----------]
[WeaponSystems]
NumberOfWeaponSystems=1

[WeaponSystem1]
#Launcher canister
Type=Missile
SystemName=SS-N-3_Redut	//SS-N-3
#Sensors
AssociatedSensors=SensorSystem2
#Animations
OpenSystemAnimation=LauncherElevate
CloseSystemAnimation=LauncherLower
#Mount
Mount=Dummy
IsMountRotatable=False
#Containers
ContainerBase=Launcher
AreContainersRotatable=False
NumberOfContainers=1
NumberOfHatchesPerContainer=1  // optional
Container1=Dummy               // when there is no real container, use this as a placeholder
Container1_Position=0,0.0217,0.0471     // must be given when there is no real container for the missile
Container1_Rotation=0,0,0      // must be given when there is no real container for the missile
Container1_Hatch1=Hatch_Front
Container1_OpenHatchAnimation=HatchOpenAnim
Container1_CloseHatchAnimation=HatchCloseAnim
#Angles
FixVerticalLaunchAngle=20
PreferredArcs=-85,85
ElevationArc=0,20
RestAngles=0,0
LoadAngles=0,0
#Loading
AssociatedMagazine=WeaponMagazineMissile
PreloadAmmunition=True
ForceMoveToLoadPosition=True
#Effects
HatchAudioClip=audio/weapons/missileHatchOpen
#Other

[---------- WeaponMagazines ----------]
[WeaponMagazineMissile]
NumberOfAmmunitionTypes=1
Ammunition1=wp_ss-n-3b
Ammunition1_Count=1 //1 - launcher + 1 - loading vehicles
ModuleType=WeaponMagazine

[--------------------------- Mesh definitions ---------------------------]
[Models]
############################################################
# Internal Resources folder related
############################################################

ResourcesFolder=ground objects/wp_4k44_redut/
ResourcesRoot=wp_4k44_redut
ResourcesMesh=wp_redut_trailer
ResourcesMaterial=wp_4k44_redut_mat
############################################################

[Submodels]
Weapons_1=Launcher
Weapons_2=Hatch_Hinges_Front
Weapons_3=Hatch_Hinges_Rear
Weapons_4=Hatch_Front
Weapons_5=Hatch_Rear
Weapons_6=Launcher_Hinges

[Launcher]
Mesh=wp_redut_canister
Material=wp_4k44_redut_mat
Position=0,0.0227,-0.0729

[Launcher_Hinges]
Mesh=wp_redut_hinges
Material=wp_4k44_redut_mat
Position=0,0.02405,-0.0013
Rotation=0,0,0

[Hatch_Hinges_Front]
Mesh=wp_redut_hinges_front
Material=wp_4k44_redut_mat
Parent=Launcher
Position=0,0.0168,0.11126
Rotation=0,0,0

[Hatch_Hinges_Rear]
Mesh=wp_redut_hinges_rear
Material=wp_4k44_redut_mat
Parent=Launcher
Position=0,0.0168,-0.01645
Rotation=0,0,0

[Hatch_Front]
Mesh=wp_redut_hatch_front
Material=wp_4k44_redut_mat
Parent=Hatch_Hinges_Front
Position=0,0,0

[Hatch_Rear]
Mesh=wp_redut_hatch_rear
Material=wp_4k44_redut_mat
Parent=Hatch_Hinges_Rear
Position=0,0,0

[---------- Effects ----------]
[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=1
AmbientAudioClip=audio/ships/Ship-Turbine-Medium
AmbientAudioPosition=0,0,-0.35
AmbientAudioRollOff=Logarithmic
AmbientAudioDistance=1,20
AmbientAudioPitchRange=1.0,1.6
AmbientAudioVolume=1.0
AmbientAudioAudibility=Above  // layer of sound audibility: Above, Below, AboveAndBelow

[Particles]
SmallFireEffectClass=SmallShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=ModerateShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=SevereShipFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffect=effects/explosions/emitters/missile_hit_ship
SecondaryExplosionEffectPosition=0,0,0

DustEffect=effects/land units/emitters/vehicle_movement_dust
DustEffectPosition=0,0,0

[---------- Colliders ----------]
############################################################
# Colliders definition
############################################################
[Colliders]
UseKinematicCollision=False
NumberOfMeshColliders=0
NumberOfColliders=2

Collider1=coll_hitbox
Collider2=coll_collider

[coll_hitbox]
Collider=Box
Position=0,0.0299,0.0103
Rotation=0,0,0
Scale=0.04,0.06,0.17

[coll_collider]
Collider=Box
Position=0,0.0028,-0.0023
Rotation=0,0,0
Scale=0.03,0.005,0.05
Layer=Default
