#P-18 Spoon Rest radar on truck
[General]
UnitType=LandUnit
LandUnitSubType=Radar //Supported values: Airbase,SAM,Installation,MobileUnit,Radar,Port
IsMobile=True

DefaultCameraDistance=0.8
MinCameraDistanceForeAft=0.3
MinCameraDistanceBroadside=0.3
CameraPivotHeight=0.03

AutoFlatten=False
MaskVegetation=True
# Hull armor: None, Minor, Moderate, Heavy
ArmorType=None
DamagePoints=3  //systems damage contribution substracted from this when systems destroyed, when becomes less than zero, the whole unit is considered being destroyed

[Tacview]
Name=P-18 Radar
Tag=Ground+AntiAircraft

[Physics]
HorsePower=240
Mass=7.9                       // in tons

MaxForwardVelocity=43.2        // in knots
MaxBackwardVelocity=5.4        // in knots
Braking=16                     // knots/sec
TurnRate=44                    // in degrees per second

[AI]
UnitScoreValue=0.4             // value for calculation of mission score
Role=Radar,ESM

[ControlSystem]
Collider=coll_hitbox,coll_radar  // makes unit destructable
Integrity=3

[SensorData]
#Visual
VisualIdentificationRange=4  // Camouflaged  (x0.5)
IRSignature=Small
# Radar related (RCS => radar cross section)
RCS=Small

[---------- Sensor Systems ----------]
[SensorSystems]
NumberOfSensorSystems=3
#---------- Visual ----------
[SensorSystem1] #Bridge
# Bridge. Does not need SystemGroup and Collider because we do not want ship to loose ability to VID targets
Type=Visual
SystemName=Optics
Mount=Dummy
MountPosition=0,0.03,0.025
ModuleType=Bridge

[SensorSystem2] #ESM
#IFF Interrogator
Type=ESM
SystemName=VesselESM
Mount=Dummy
MountPosition=0,0.1067,-0.0259

[SensorSystem3] #Spoon_Rest / P-18 Terek 2D air search radar
Type=Radar
SystemName=Spoon_Rest
Mount=Radar

[--------------------------- Mesh definitions ---------------------------]
[Models]
ResourcesFolder=ground objects/wp_radars/
ResourcesRoot=wp_radars_trailers
ResourcesMesh=wp_p-18_chassis
ResourcesDamagedMesh=wp_500kw_generator_d
ResourcesMaterialFolder=ground objects/wp_radars/
ResourcesMaterial=wp_urals_mat
############################################################

[Submodels]
SubModel1=Radar
SubModel2=Radar_trans
SubModel3=Trans

[Radar]
Mesh=wp_p-18_radar
Material=wp_urals_mat
Position=0,0.1067,-0.0259
HideWithActiveDamageModel=True

[Radar_trans]
Mesh=wp_p-18_radar_trans
Material=wp_radars_trans_mat
Parent=Radar
Position=0,0,0
HideWithActiveDamageModel=True

[Trans]
Mesh=wp_p-18_trans
Material=wp_radars_trans_mat
HideWithActiveDamageModel=True

[---------- Effects ----------]
[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=1
AmbientAudioClip=audio/ships/Ship-Turbine-Small
AmbientAudioPosition=0,0,0
AmbientAudioRollOff=Logarithmic
AmbientAudioDistance=0.2,2
AmbientAudioPitchRange=1.0,1.6
AmbientAudioVolume=0.0
AmbientAudioAudibility=Above  // layer of sound audibility: Above, Below, AboveAndBelow

[Particles]
SmallFireEffectClass=SmallShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=SmallShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=SmallShipFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffect=effects/explosions/emitters/missile_hit_ship
SecondaryExplosionEffectPosition=0,0,0

DustEffect=effects/land units/emitters/vehicle_movement_dust
DustEffectPosition=0,0,0

[---------- Colliders ----------]
[Colliders]
UseKinematicCollision=False
NumberOfMeshColliders=0
NumberOfColliders=3

Collider1=coll_hitbox
Collider2=coll_radar
Collider3=coll_collider

[coll_hitbox]
Collider=Box
Position=0,0.027,0
Rotation=0,0,0
Scale=0.04,0.055,0.115

[coll_radar]
Collider=Box
Position=0,0.1067,-0.026
Rotation=0,0,0
Scale=0.2,0.04,0.2

[coll_collider]
Collider=Box
Position=0,0.0028,-0.0023
Rotation=0,0,0
Scale=0.03,0.005,0.05
Layer=Default