#P-35 Barlock radar on trailer
[General]
UnitType=LandUnit
LandUnitSubType=Radar //Supported values: Airbase,SAM,Installation,MobileUnit,Radar,Port
DefaultCameraDistance=1.5
MinCameraDistanceForeAft=0.8
MinCameraDistanceBroadside=0.8
CameraPivotHeight=0.1

AutoFlatten=False
MaskVegetation=True
# Hull armor: None, Minor, Moderate, Heavy
ArmorType=None
DamagePoints=3  //systems damage contribution substracted from this when systems destroyed, when becomes less than zero, the whole unit is considered being destroyed

[Tacview]
Name=1L13
Tag=Ground+AntiAircraft

[AI]
UnitScoreValue=1              // value for calculation of mission score
Role=Radar,ESM

[ControlSystem]
Collider=coll_hitbox  // makes unit destro
Integrity=3

[SensorData]
#Visual
VisualIdentificationRange=4  // Camouflaged  (x0.5)
IRSignature=Small
# Radar related (RCS => radar cross section)
RCS=Small

[---------- Sensor Systems ----------]
############################################################
# Sensor Systems
############################################################
[SensorSystems]
NumberOfSensorSystems=3
#---------- Visual ----------
[SensorSystem1] #Bridge
# Bridge. Does not need SystemGroup and Collider because we do not want ship to loose ability to VID targets
Type=Visual
SystemName=Optics
Mount=Dummy
MountPosition=0,0.026,0

[SensorSystem2] #ESM
#IFF Interrogator
Type=ESM
SystemName=VesselESM
Mount=Dummy
MountPosition=0,0.1,0

[SensorSystem3] #NavRadar
Type=Radar
SystemName=Bar_Lock
Mount=Radar_trailer

[Models]
ResourcesFolder=ground objects/wp_radars/
ResourcesRoot=wp_radars_trailers
ResourcesMesh=wp_p-35_chassis
ResourcesDamagedMesh=wp_p-35_chassis_d
ResourcesMaterialFolder=ground objects/wp_radars/
ResourcesMaterial=wp_radars_trailers_mat
############################################################

[Submodels]
SubModel1=Radar_trailer
SubModel2=Trans

[Radar_trailer]
Mesh=wp_p-35_trailer
Material=wp_radars_trailers_mat
Position=0,0,0
HideWithActiveDamageModel=True

[Trans]
Mesh=wp_p-35_trans
Material=wp_radars_trans_mat
Parent=Radar_trailer
Position=0,0,0
HideWithActiveDamageModel=True

[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=1


[Particles]
SmallFireEffectClass=SmallShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=SmallShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=SmallShipFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffect=effects/explosions/emitters/missile_hit_ship
SecondaryExplosionEffectPosition=0,0,0

[---------- Colliders ----------]
[Colliders]
NumberOfColliders=1
NumberOfMeshColliders=0
UseKinematicCollision=False

Collider1=coll_hitbox

[coll_hitbox]
Collider=Box
Position=0,0.059,0
Rotation=0,0,0
Scale=0.17,0.12,0.17