[General]
#AllVariantsAreOfSameNation=False //Speeds up nation sorting. Only needed if there is more then 1 nation variants. Default is 'true'
NumberOfVariants=8

[Default]
Nation=Soviet

[Variant1]
Nation=Soviet

[Variant2]
Nation=DDR

[Variant3]
Nation=Czech

[Variant4]
Nation=Poland

[Variant5]
Nation=Vietnam

[Variant6]
Nation=India

[Variant7]
Nation=Iraq
ResourcesLiveryFolder=ground objects/wp_sa-3_goa/desert/
LiveryTexture=wp_sa-3_tx

[Variant8]
Nation=Egypt
ResourcesLiveryFolder=ground objects/wp_sa-3_goa/desert/
LiveryTexture=wp_sa-3_tx