[General]
UnitType=LandUnit
LandUnitSubType=SAM

HideIn=Encyclopedia,MissionEditor,Signatures

DefaultCameraDistance=0.8
MinCameraDistanceForeAft=0.3
MinCameraDistanceBroadside=0.3
CameraPivotHeight=0.05

GroundOffset=0
AutoFlatten=False
MaskVegetation=True

# Hull armor: None, Minor, Moderate, Heavy
ArmorType=None
DamagePoints=3  //systems damage contribution substracted from this when systems destroyed, when becomes less than zero, the whole unit is considered being destroyed

[Tacview]
Name=SA-3
Tag=Ground+Vehicle+SAM

[AI]
UnitScoreValue=1              // value for calculation of mission score
Role=AAW,SAM

[SensorData]
#Visual
VisualIdentificationRange=7  // Camouflaged  (x0.5)
IRSignature=Small
# Radar related (RCS => radar cross section)
RCS=Small

[---------- Sensor Systems ----------]
############################################################
# Sensor Systems
############################################################
[SensorSystems]
NumberOfSensorSystems=3
#---------- Visual ----------
[SensorSystem1] #Bridge
# Bridge. Does not need SystemGroup and Collider because we do not want ship to loose ability to VID targets
Type=Visual
SystemName=Optics
Mount=Dummy
MountPosition=0,0.026,0
ModuleType=Bridge
Integrity=0

[SensorSystem2]  #Pop_Group_Search
Type=Radar
SystemName=Pop_Group_Search
Mount=Dummy	//Radar
ModuleType=Sensor

[SensorSystem3]  #Pop_Group
Type=Radar
SystemName=Pop_Group
Mount=Dummy
MountPosition=0,0.17,0
ModuleType=Sensor

[---------- Weapon Systems ----------]
############################################################
# Weapon Systems
############################################################
[WeaponSystems]
NumberOfWeaponSystems=1

[WeaponSystem1] #SA-3 Goa
Type=Missile
SystemName=SA-3
#Sensors
AssociatedSensors=SensorSystem2
#Animations
#Mount
Mount=Launcher
IsMountRotatable=True
#Containers
NumberOfContainers=1
ContainerBase=Rails
NumberOfContainers=1
Container1=Rails
AreContainersRotatable=True
Container1_Position=0,0.0164,-0.019
Container1_Rotation=0,0,0
#Angles
ElevationArc=0,45
RestAngles=0,0
LoadAngles=0,0
#Loading
AssociatedMagazine=WeaponMagazineMissile
PreloadAmmunition=True
ForceMoveToLoadPosition=True
#Effects
#Other
DisplayWeaponsOnSystem=True
ModuleType=Weapon
Collider=coll_hitbox
Integrity=3
VIDIncrease=15  // In miles. Flat base VID increace when firing.

[---------- WeaponMagazines ----------]
[WeaponMagazineMissile]
NumberOfAmmunitionTypes=1
Ammunition1=wp_sa-3
Ammunition1_Count=4
ModuleType=WeaponMagazine

[Models]
############################################################
# Internal Resources folder related
############################################################

ResourcesFolder=ground objects/wp_sa-3_goa/
ResourcesRoot=wp_sa-3_goa
ResourcesMesh=wp_sa-3_base
ResourcesMaterial=wp_sa-3_goa_mat
############################################################

[Submodels]
Launcher=Launcher
Rails=Rails

#[Base]
#Mesh=wp_sa-2_base
#Material=wp_sa-2_guideline_mat
#Position=0,0,0

[Launcher]
Mesh=wp_sa-3_launcher
Material=wp_sa-3_goa_mat
#Parent=Base
Position=0,0,0

[Rails]
Mesh=wp_sa-3_rails
Material=wp_sa-3_goa_mat
Parent=Launcher
Position=0,0.0184,0.0266

[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=1
AmbientAudioClip=audio/ships/Ship-Turbine-Medium
AmbientAudioPosition=0,0,-0.35
AmbientAudioRollOff=Logarithmic
AmbientAudioDistance=1,20
AmbientAudioPitchRange=1.0,1.6
AmbientAudioVolume=1.0
AmbientAudioAudibility=Above  // layer of sound audibility: Above, Below, AboveAndBelow

[Particles]
SmallFireEffectClass=SmallShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=ModerateShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=ModerateShipFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffect=effects/explosions/emitters/missile_hit_ship
SecondaryExplosionEffectPosition=0,0,0

[---------- Colliders ----------]
############################################################
# Colliders definition
############################################################
[Colliders]
NumberOfColliders=1
NumberOfMeshColliders=0
UseKinematicCollision=False

Collider1=coll_hitbox

[coll_hitbox]
Collider=Box
Position=0,0.026,0
Rotation=0,0,0
Scale=0.04,0.05,0.1
