[SystemNames]

#---------------------------------------- ESM ----------------------------------------
LJQ-366_Passive_ESM=ESM for LJQ-366 radar|H/LJQ-366雷达是一种水面搜索雷达，衍生自90年代自俄罗斯引进的'矿石-ME'雷达。该雷达具备主动和被动工作模式，能够在5个不同的波段工作，在被动模式下利用大气波导效应时具备一定的超视距探测能力。

RJZ-751_ESM=H/RJZ-751 ESM|H/RJZ-751舰载有源电子战系统是人民海军装备的第二代舰载电子战系统，装备054A型导弹护卫舰，包括电子支援设备（ESM），雷达告警设备（RWR），主被动有源电子干扰设备（ECM）和无源电子干扰发射器。系统能够根据作战指挥系统传递的威胁目标信息全自动分配干扰频段和干扰类型，有效干扰来袭目标的传感器设备。

RJL-928_ESM=H/RJL-928 ESM|H/RJZ-826舰载综合电子战系统是人民海军装备的第二代舰载电子战系统，主要装备052型导弹驱逐舰，包括RJL-928雷达侦察机（ESM），RJZ-984主被动有源电子干扰设备（ECM），雷达告警设备（RWR），和946无源电子干扰发射器。系统能够根据作战指挥系统传递的威胁目标信息全自动分配干扰频段和干扰类型，干扰来袭目标的传感器设备。

RJZ-726_ESM=H/RJZ-726 ESM|H/RJZ-726舰载电子战系统是人民海军装备的第三代舰载组合式综合电子战设备，包括电子支援设备（ESM），雷达告警设备（RWR），有源电子干扰设备（ECM）和无源电子干扰发射器。系统能够根据作战指挥系统传递的威胁目标信息全自动分配干扰频段和干扰类型，有效干扰来袭目标的传感器设备。

RJZ-728_ESM=H/RJZ-728 ESM|H/RJZ-728舰载电子战系统是人民海军装备的第三代舰载组合式综合电子战设备，适用于小型水面作战舰艇。

RJL-XXX_OTH_ESM=H/RJL-XXX ESM|H/RJZ-XXX舰载电子战系统是人民海军装备的第四代舰载组合式综合电子战设备，包括电子支援设备（ESM），雷达告警设备（RWR），主被动有源电子干扰设备（ECM）和无源电子干扰发射器。系统能够根据作战指挥系统传递的威胁目标信息全自动分配干扰频段和干扰类型，有效干扰来袭目标的传感器设备。其中电子支援设备具备超视距被动探测能力。

RJL-XXX_ESM=H/RJL-XXX ESM|H/RJZ-XXX舰载电子战系统是人民海军装备的第四代舰载组合式综合电子战设备，包括电子支援设备（ESM），雷达告警设备（RWR），主被动有源电子干扰设备（ECM）和无源电子干扰发射器。系统能够根据作战指挥系统传递的威胁目标信息全自动分配干扰频段和干扰类型，有效干扰来袭目标的传感器设备。

#---------------------------------------- RWR ----------------------------------------
RJZ-751_RWR=H/RJZ-751 RWR|H/RJZ-751舰载有源电子战系统是人民海军装备的第二代舰载电子战系统，装备054A型导弹护卫舰，包括电子支援设备（ESM），雷达告警设备（RWR），主被动有源电子干扰设备（ECM）和无源电子干扰发射器。系统能够根据作战指挥系统传递的威胁目标信息全自动分配干扰频段和干扰类型，有效干扰来袭目标的传感器设备。

RJZ-984_RWR=H/RJZ-984 RWR|H/RJZ-826舰载综合电子战系统是人民海军装备的第二代舰载电子战系统，主要装备052型导弹驱逐舰，包括RJL-928雷达侦察机（ESM），RJZ-984主被动有源电子干扰设备（ECM）雷达告警设备（RWR），和946无源电子干扰发射器。系统能够根据作战指挥系统传递的威胁目标信息全自动分配干扰频段和干扰类型，干扰来袭目标的传感器设备。

RJZ-726_RWR=H/RJZ-726 RWR|H/RJZ-726舰载电子战系统是人民海军装备的第三代舰载组合式综合电子战设备，包括电子支援设备（ESM），雷达告警设备（RWR），有源电子干扰设备（ECM）和无源电子干扰发射器。系统能够根据作战指挥系统传递的威胁目标信息全自动分配干扰频段和干扰类型，有效干扰来袭目标的传感器设备。

RJZ-728_RWR=H/RJZ-728 RWR|H/RJZ-728舰载电子战系统是人民海军装备的第三代舰载组合式综合电子战设备，适用于小型水面作战舰艇。

RJZ-XXX_RWR=H/RJZ-XXX RWR|H/RJZ-XXX舰载电子战系统是人民海军装备的第四代舰载组合式综合电子战设备，包括电子支援设备（ESM），雷达告警设备（RWR），主被动有源电子干扰设备（ECM）和无源电子干扰发射器。系统能够根据作战指挥系统传递的威胁目标信息全自动分配干扰频段和干扰类型，有效干扰来袭目标的传感器设备。

#---------------------------------------- ECM ----------------------------------------
RJZ-726_ECM=H/RJZ-726 ECM|H/RJZ-726舰载电子战系统是人民海军装备的第三代舰载组合式综合电子战设备，包括电子支援设备（ESM），雷达告警设备（RWR），有源电子干扰设备（ECM）和无源电子干扰发射器。系统能够根据作战指挥系统传递的威胁目标信息全自动分配干扰频段和干扰类型，有效干扰来袭目标的传感器设备。

RJZ-728_ECM=H/RJZ-728 ECM|H/RJZ-728舰载电子战系统是人民海军装备的第三代舰载组合式综合电子战设备，适用于小型水面作战舰艇。

RJZ-751_ECM=H/RJZ-751 ECM|H/RJZ-751舰载有源电子战系统是人民海军装备的第二代舰载电子战系统，装备054A型导弹护卫舰，包括电子支援设备（ESM），雷达告警设备（RWR），主被动有源电子干扰设备（ECM）和无源电子干扰发射器。系统能够根据作战指挥系统传递的威胁目标信息全自动分配干扰频段和干扰类型，有效干扰来袭目标的传感器设备。

RJZ-751A_ECM=H/RJZ-751A ECM|H/RJZ-751A舰载有源电子战系统是人民海军装备的第三代舰载电子战系统，装备054A后期型导弹护卫舰，包括电子支援设备（ESM），雷达告警设备（RWR），主被动有源电子干扰设备（ECM）和无源电子干扰发射器。系统能够根据作战指挥系统传递的威胁目标信息全自动分配干扰频段和干扰类型，有效干扰来袭目标的传感器设备。

RJZ-984_ECM=H/RJZ-984 ECM|H/RJZ-826舰载综合电子战系统是人民海军装备的第二代舰载电子战系统，主要装备052型导弹驱逐舰，包括RJL-928雷达侦察机（ESM），雷达告警设备（RWR），RJZ-984主被动有源电子干扰设备（ECM）和946无源电子干扰发射器。系统能够根据作战指挥系统传递的威胁目标信息全自动分配干扰频段和干扰类型，干扰来袭目标的传感器设备。

RJZ-726_ECM=H/RJZ-726 ECM|H/RJZ-726舰载电子战系统是人民海军装备的第三代舰载组合式综合电子战设备，包括电子支援设备（ESM），雷达告警设备（RWR），有源电子干扰设备（ECM）和无源电子干扰发射器。系统能够根据作战指挥系统传递的威胁目标信息全自动分配干扰频段和干扰类型，有效干扰来袭目标的传感器设备。

RJZ-XXX_ECM=H/RJZ-XXX ECM|H/RJZ-XXX舰载电子战系统是人民海军装备的第四代舰载组合式综合电子战设备，包括电子支援设备（ESM），雷达告警设备（RWR），主被动有源电子干扰设备（ECM）和无源电子干扰发射器。系统能够根据作战指挥系统传递的威胁目标信息全自动分配干扰频段和干扰类型，有效干扰来袭目标的传感器设备。

#---------------------------------------- MAD ----------------------------------------

#---------------------------------------- Laser Designator ---------------------------

#======================================== Soviet Union ========================================
#---------------------------------------- Radar ----------------------------------------
#---------- Surface ships ----------
#---Air/Air&Surface---
LJQ-381A=H/LJQ-381A|H/LJQ-381A雷达是中国自主研制的三坐标远程对空搜索雷达，在中国第一型对空三坐标雷达LJQ-381雷达基础上改进而来。

LJQ-382=H/LJQ-382 radar|H/LJQ-382雷达是中国在俄罗斯MR-750MA雷达基础上改进的三坐标对空搜索雷达，是中国海军护卫舰和大型水面舰艇的主要对空搜索警戒雷达。雷达采用相控阵天线和机械扫描相结合的运作方式，探测和跟踪能力满足区域防空需求，能够有效抑制海杂波及电子干扰，并能快速为舰载防空系统提供精确目标指示。

LJQ-362=H/LJQ-362 radar|H/LJQ-362雷达是一种2D超低空搜索/水面搜索雷达，工作在X波段。该雷达是人民海军第一款超低空快速反应雷达，原名347S搜索雷达，与PJ-76A双联37毫米自动舰炮的火控雷达347G雷达一同组成347低空快速反应雷达系统。该雷达可有效探测超低空突防目标和掠海反舰巡航导弹，并为近防武器系统提供火控参数，但作用距离较短。

LJQ-364=H/LJQ-364 radar|H/LJQ-364雷达是一种2D双波段超低空搜索/水面搜索雷达，工作在X波段（超低空搜索）和I波段（水面搜索）。该雷达广泛装备于人民海军的中大型水面舰艇，在054A型护卫舰上主要用于填补H/LJQ-382雷达在近距离探测超低空掠海目标时产生的盲区。该雷达也可为近防武器系统提供目标参数。

LJQ-360=H/LJQ-360 radar|H/LJQ-360雷达是中国制造的一种2D对空/对面多用途搜索雷达，是上世纪80年代中国引进法国汤姆森-TSF TSR 3004 "海虎"雷达后进行国产化的版本。该雷达主要装备于上世纪90年代和00年代人民海军导弹驱逐舰，负责中近距离对空和对面搜索，并为海红旗-7/海响尾蛇舰空导弹系统提供目标指引

LJQ-361A=H/LJQ-361A|H/LJQ-361A雷达是一种2D对海/对空搜索雷达，主要装备056A型护卫舰等小型水面舰艇。

LJQ-517A=H/LJQ-517A|H/LJQ-517A雷达是一种2D远程对空搜索雷达，工作在VHF波段，主要承担中高空远程警戒任务，可接入作战指挥系统，具有干扰分析自适应频率捷变能力。

LJQ-518=H/LJQ-518|H/LJQ-518雷达是一种2D远程对空警戒雷达，工作在L波段。由于LJQ-381三坐标远程对空警戒雷达性能差强人意，海军选择利用现有的陆基远程警戒雷达改进为舰载雷达装备052型导弹驱逐舰，LJQ-518雷达应运而生。相较于当时人民海军装备的米波对空警戒雷达，该雷达探测在保证探测距离的同时提升了探测精度，可通过舰载作战指挥系统和数据链传递空情信息，但该雷达由于天线尺寸较大，作用距离也仅能勉强满足需求，仅作为过渡方案装备了两艘052型导弹驱逐舰。

LJQ-517B=H/LJQ-517B|H/LJQ-517B雷达是一种双坐标远程对空搜索雷达，工作在VHF波段，主要承担中高空远程警戒任务，可接入作战指挥系统，具有干扰分析自适应频率捷变能力。052C驱逐舰的517B雷达主要用于在346雷达主阵面低功率运行时提供远程空中目标的预警信息

LJQ-520=H/LJQ-520|H/LJQ-520雷达是一种三坐标远程对空搜索雷达，工作在VHF波段，主要承担中高空远程警戒任务。相较于传统米波雷达，该雷达采用超分辨率技术，拥有较高的探测精度。

LJG-346=H/LJG-346|H/LJG-346'海之星'雷达是中国海军装备的第一种大型双波段主动有源相控阵（AESA）雷达，工作在S波段（搜索/跟踪）和C波段（制导）。052C型驱逐舰上共安装有4个雷达阵面，由静压通风冷却，单个雷达阵面由中央的S波段阵面和上下两侧的长条形C波段阵面组成，单个S波段阵面T/R组件数量超过5000个，最大搜索距离约450公里。配合H/ZKJ-5数字化自动指挥控制系统，雷达能够同时跟踪上百个空中目标，自动识别和判断威胁等级并给出攻击指令，引导海红旗-9B舰空导弹攻击威胁等级最高的目标。

LJQ-368=H/LJQ-368|H/LJQ-368雷达是有源相控阵体制的超低空搜索/水面搜索雷达，装备人民海军大中型水面舰艇，有效提升了针对超低空掠海目标的发现距离，缩短了舰载防空系统传感器反应时间。

LJQ-36X=H/LJQ-36X radar|H/LJQ-36X雷达是一种采用AESA体制的新型双波段超低空搜索/水面搜索雷达，工作在X波段（超低空搜索）和I波段（水面搜索）。主要用于填补H/LJG-346A雷达在近距离探测超低空掠海目标时产生的盲区，安装于综合射频桅杆内，该雷达也可为近防武器系统提供目标参数。

LJG-346A=H/LJG-346A|H/LJG-346'海之星'雷达是中国海军装备的第一种大型双波段主动有源相控阵（AESA）雷达，工作在S波段（搜索/跟踪）和C波段（制导）。H/LJG-346A型雷达是提升探测能力，加强散热性能的改进型。系统共有4个雷达阵面，由液冷管路冷却，单个雷达阵面由中央的S波段阵面和上下两侧的长条形C波段阵面组成，单个S波段阵面T/R组件数量超过5000个，最大搜索距离大于500公里。配合新一代数字化自动指挥控制系统，雷达能够同时跟踪上百个空中目标，自动识别和判断威胁等级并给出攻击指令，引导海红旗-9系列舰空导弹攻击威胁等级最高的目标。

#---Surface only---
LJQ-366=H/LJQ-366 radar|H/LJQ-366雷达是一种水面搜索雷达，衍生自90年代自俄罗斯引进的'矿石-ME'雷达。该雷达具备主动和被动工作模式，能够在5个不同的波段工作，在利用大气波导效应时具备一定的超视距探测能力。在054A型护卫舰上该雷达主要用于为鹰击-83反舰导弹提供目标参数，并通过双向数据链与其他作战单位共享。

LJQ-366_Passive_ESM=ESM for Type366 radar|H/LJQ-366雷达是一种水面搜索雷达，衍生自90年代自俄罗斯引进的'矿石-ME'雷达。该雷达具备主动和被动工作模式，能够在5个不同的波段工作，在利用大气波导效应时具备一定的超视距探测能力。在052C型驱逐舰上该雷达主要用于为鹰击-62反舰导弹提供目标参数，并通过双向数据链与其他作战单位共享。

LJQ-366=H/LJQ-366 radar|H/LJQ-366雷达是一种水面搜索雷达，衍生自90年代自俄罗斯引进的'矿石-ME'雷达。该雷达具备主动和被动工作模式，能够在5个不同的波段工作，在利用大气波导效应时具备一定的超视距探测能力。在052C型驱逐舰上该雷达主要用于为鹰击-62反舰导弹提供目标参数，并通过双向数据链与其他作战单位共享。

LJQ-3XX=H/LJQ-3XX radar|H/LJQ-3XX雷达是一种新型L波段水面搜索雷达，具备主被动工作模式，为舰载反舰导弹提供目标指示。

Navigation_radar=导航雷达|导航雷达

OFD-630_IRS=OFD-630|OFD-630舰载全向红外/光电警戒设备。

IR-17_IRS=IR-17|IR-17舰载全向红外/光电警戒设备。

IR-XX_IRS=IR-XX|IR-XX舰载全向红外/光电警戒设备。

LJP-345_IRA=LJP-345 IRA|LJP-345火控雷达光电观瞄设备。

#---Fire Control---
#LJG-316 SAM
LJG-316=H/LJG-316 FCR|H/LJG-316（虚构代号）是中国基于俄罗斯MR-90火控雷达改进而来的舰空导弹火控雷达，是红旗-16舰空导弹系统的制导雷达，单台雷达可同时引导2发导弹攻击1个目标。

LJG-316A=H/LJG-316A FCR|H/LJG-316A（虚构代号）是红旗-16舰空导弹系统使用的新一代X波段有源相控阵（AESA）火控雷达，装备后期型054A导弹护卫舰，单个阵面可同时引导6发导弹攻击3个目标。

#Guns
LJP-344=H/LJP-344 FCR|H/LJP-344是中国研制的舰载主炮火控雷达，主要装备于90年代后建造的各型导弹驱逐舰，是H/PJ-87，H/PJ-33和H/PJ-45等舰炮的火控雷达。

LJP-344A=H/LJP-344A|H/LJP-344A雷达是舰上主炮的火控雷达

LJP-345=H/LJP-345 FCR|H/LJP-345是海红旗-7舰空导弹系统的火控雷达，是中国引进法国Castor-II综合火控雷达后进行国产化改进的版本。该雷达配备共轴红外和电视观瞄设备，可同时引导2发导弹攻击1个目标。

LJP-347=H/LJP-347 FCR|H/LJP-347是双联37毫米PJ-76A速射舰炮的火控雷达。

30N6E1_FCR=30N6E1 FCR|30N6E1雷达是俄罗斯30N6多用途相控阵火控雷达的外贸版本，是S-300PMU1和"里夫-M"舰空导弹系统的火控雷达。雷达采用单面旋转无源相控阵体制，TVM制导，可同时引导12枚导弹攻击6个目标。

#CIWS
LJP-349A=H/LJP-349A|H/LJP-349A雷达是H/PJ-26 76毫米主炮的火控雷达，也是H/PJ-11 11管30毫米近防系统的火控雷达

LJP-349=H/LJP-349|H/PJ-12 7管30毫米近防系统的火控雷达

LJP-3XX=H/LJP-3XX|H/LJP-3XX雷达是舰上主炮的火控雷达

#---------------------------------------- Sonar ----------------------------------------
DE-1160=DE-1160|DE-1160数字式综合声呐系统是美国AN/SQS-56综合声呐系统的出口版本，在美国海军作战舰艇中主要装备佩里级导弹护卫舰。中国于上世纪80年代初自意大利进口了两套该型声呐系统，装备052型导弹驱逐舰哈尔滨舰和051G型导弹驱逐舰珠海舰。是人民海军首次拥有数字式综合舰壳声呐系统。

SJD-7=H/SJD-7|H/SJD-7声呐是中国第一型数字式中频舰壳声呐，主要装备于90年代末，00年代初人民海军大型水面作战舰艇

SJD-9=H/SJD-9|H/SJD-9声呐是人民海军主力驱逐舰和护卫舰装备的通用中低频综合舰壳声呐，采用全数字信号处理体制，传感器信息可通过作战指挥系统和数据链与其他单位共享。由于该声呐追求通用性设计，必须同时兼容轻型护卫舰至导弹驱逐舰等尺寸不一的舰体，因此声呐基阵尺寸受到限制，作用距离并不优秀。


DE-1164=DE-1164 VDS|DE-1164拖曳式变深声呐可搭配DE-1160综合声呐系统使用，具备主被动工作模式，可探测温跃层下的水下目标。中国于上世纪80年代初自意大利进口了该型声呐，装备052型导弹驱逐舰和051G型导弹驱逐舰珠海舰。

SJG-206=H/SJG-206|H/SJG-206被动拖曳线列声呐是人民海军第二代被动拖曳线列声呐。

SJG-311=H/SJG-311|H/SJG-311是人民海军装备的通用主被动复合可变深度拖曳声呐（VDS）

SJD-XX=H/SJD-XX|H/SJD-XX声呐是人民海军新一代通用中低频综合舰壳声呐，采用全数字信号处理体制，传感器信息可通过作战指挥系统和数据链与其他单位共享。

# ------------------ Guns -----------------

PJ-17A=H/PJ-17A Gun|30mm|H/PJ-17A型单管30毫米舰炮是一款轻型自卫舰载武器，装备于各类舰队辅助船，海警船和轻型护卫舰，主要用于自卫和反恐执法行动。

PJ-26=H/PJ-26 Gun|76mm|H/PJ-26型单管76毫米舰炮是中国在俄罗斯AK-176M舰炮基础上研制的中口径舰载主炮，是人民海军护卫舰广泛装备的多用途火炮系统，具备自动化程度高，射速快的特点，兼容多种弹药，能有效执行防空反导、水面打击及岸轰支援等任务。

PJ-33B=H/PJ-33B Gun|100mm|H/PJ-33B 100毫米舰炮是中国自主研制的双联100毫米自动舰炮，其改进自79式双联装100毫米舰炮，采用隐身外壳，全自动供弹，计算机控制，大幅提升使用可靠性和射击精度；但是该炮射速较慢，对空中目标抗击效果不理想。

PJ-87=H/PJ-87 Gun|100mm|H/PJ-87 100毫米舰炮衍生自法国'100毫米紧凑型舰炮'（T100C）。1980年代初中国从法国引进了T100C舰炮的原型样炮，并曾经装载在053H1Q型护卫舰四平舰上测试。在完善舰炮可靠性，依据中国海军舰艇电子设备修改舰炮电路和数控设备设计，并换装隐身设计的外壳后，以H/PJ-87的型号定型量产。该炮全自动运作，能够对空、对海目标射击，最高射速90发/分。该炮还装备052B型驱逐舰、051C型驱逐舰和054型护卫舰。

PJ-87_051C=H/PJ-87 Gun|100mm|H/PJ-87 100毫米舰炮衍生自法国'100毫米紧凑型舰炮'（T100C）。1980年代初中国从法国引进了T100C舰炮的原型样炮，并曾经装载在053H1Q型护卫舰四平舰上测试。在完善舰炮可靠性，依据中国海军舰艇电子设备修改舰炮电路和数控设备设计，并换装隐身设计的外壳后，以H/PJ-87的型号定型量产。该炮全自动运作，能够对空、对海目标射击，最高射速90发/分。该炮还装备052B型驱逐舰、051C型驱逐舰和054型护卫舰。

PJ-45A=H/PJ-45A Gun|130mm|H/PJ-45A 130毫米舰炮是人民海军新一代驱逐舰通用舰炮，装备052D型导弹驱逐舰。PJ-45A型舰炮为缩小尺寸和重量缩减了双流供弹功能。

PJ-45=H/PJ-45 Gun|130mm|H/PJ-45 130毫米舰炮是人民海军新一代驱逐舰通用舰炮，其改型装备052D、055型导弹驱逐舰。055型驱逐舰装备的H/PJ-45舰炮采用全自动运作，双路供弹，具有射速快，反应时间短，威力大，通用性强的特点。

# ------------------ CIWS -----------------
PJ-13A=H/PJ-13A CIWS|H/PJ-13A|PJ-13A近防系统是中国海军引进俄罗斯AK630六管三十毫米近防系统后国产化的一型近防武器，采用隐身外壳并采用中国制造的火控雷达和观瞄系统

PJ-13B=H/PJ-13B CIWS|H/PJ-13B|PJ-13B近防系统是中国海军引进俄罗斯AK630六管三十毫米近防系统后国产化的一型近防武器。PJ-13B升级了继承自AK630的弹链供弹系统，改为弹鼓供弹，在增强可靠性的同时增加了备弹容量。

Type_730=Type 730 CIWS|H/PJ-12|人民海军装备的7管30毫米自动近防系统（CIWS），装备于人民海军主力水面作战舰艇。该系统核心是一门7管30毫米机炮，发射脱壳尾翼稳定穿甲弹（APFSDS），射速约5800发/分，备弹1000发。炮座可以约80度/秒的速度快速旋转，配备独立的红外/光电传感器和激光测距仪，每个炮座还配备独立的H/LJP-349火控雷达提供火控参数。该系统能够有效抗击来袭的超音速掠海导弹，也可打击固定翼、旋翼飞行器、船舰及其他小艇、近岸目标及浮型水雷。

Type_730_H=Type 730 CIWS|H/PJ-12|人民海军装备的7管30毫米自动近防系统（CIWS），装备于人民海军主力水面作战舰艇。该系统核心是一门7管30毫米机炮，发射脱壳尾翼稳定穿甲弹（APFSDS），射速约5800发/分，备弹1000发。炮座可以约80度/秒的速度快速旋转，配备独立的红外/光电传感器和激光测距仪，每个炮座还配备独立的H/LJP-349火控雷达提供火控参数。该系统能够有效抗击来袭的超音速掠海导弹，也可打击固定翼、旋翼飞行器、船舰及其他小艇、近岸目标及浮型水雷。

Type_1130_L=Type 1130 CIWS|H/PJ-11|人民海军装备的11管30毫米自动近防系统（CIWS），装备于人民海军主力水面作战舰艇。该系统核心是一门11管30毫米机炮，发射脱壳尾翼稳定穿甲弹（APFSDS），射速约10000发/分。炮座可以约90度/秒的速度快速旋转，配备独立的红外/光电传感器和激光测距仪，每个炮座还配备独立的H/LJP-349火控雷达提供火控参数。该系统能够有效抗击来袭的超音速掠海导弹，也可打击固定翼、旋翼飞行器、船舰及其他小艇、近岸目标及浮型水雷。

Type_1130=Type 1130 CIWS|H/PJ-11|人民海军装备的11管30毫米自动近防系统（CIWS），装备于人民海军主力水面作战舰艇。该系统核心是一门11管30毫米机炮，发射脱壳尾翼稳定穿甲弹（APFSDS），射速约10000发/分。炮座可以约90度/秒的速度快速旋转，配备独立的红外/光电传感器和激光测距仪，每个炮座还配备独立的H/LJP-349火控雷达提供火控参数。该系统能够有效抗击来袭的超音速掠海导弹，也可打击固定翼、旋翼飞行器、船舰及其他小艇、近岸目标及浮型水雷。

Type_1130_L=Type 1130 CIWS|H/PJ-11|人民海军装备的11管30毫米自动近防系统（CIWS），装备于人民海军主力水面作战舰艇。该系统核心是一门11管30毫米机炮，发射脱壳尾翼稳定穿甲弹（APFSDS），射速约10000发/分。炮座可以约90度/秒的速度快速旋转，配备独立的红外/光电传感器和激光测距仪，每个炮座还配备独立的H/LJP-349火控雷达提供火控参数。该系统能够有效抗击来袭的超音速掠海导弹，也可打击固定翼、旋翼飞行器、船舰及其他小艇、近岸目标及浮型水雷。

PJ-76A=H/PJ-76A AAA|37mm|H/PJ-76A型双联装37毫米自动舰炮是中国在上世纪70年代基于76式双联37毫米舰炮研发的全自动速射舰炮。该型舰炮取消人员操作席位，采用自动供弹和计算机控制技术。由于技术基础依然是二战时期的37毫米防空炮，因此该武器系统仅能打击低空飞行的飞机，对各类导弹目标无显著拦截效果。

CIWS_Magazine=CIWS Magazine

# ----------- Noisemakers/Chaff -----------
NoisemakerMagazine=Noisemaker Magazine

###########################################################

#---------------------------- Heli ------------------------------

###########################################################
E-801E=E-801E|E-801E雷达由下诺夫哥罗德无线电工程研究所研发。该雷达天线面积为6平方米，采用无源相控阵体制，可折叠于卡-31直升机机腹，该雷达具有360°搜索能力，对战斗机大小目标的监视距离可达110公里。对水面舰艇的监视范围通常为100-200公里。该雷达能够同时跟踪40个目标。

SKD-143=H/SKD-143|H/SKD-143吊放声呐是人民海军舰载直升机装备的第三代机载吊放声呐，装备直-9C直升机。

SKD-144=H/SKD-144|H/SKD-144吊放声呐是人民海军舰载直升机装备的第四代机载吊放声呐，装备直-9F直升机。

SKD-144A=H/SKD-144A|H/SKD-144A吊放声呐是人民海军舰载直升机装备的第四代机载吊放声呐，装备直-18FA直升机。

SKD-20=H/SKD-20|H/SKD-20吊放声呐（虚构代号）是人民海军舰载直升机装备的第五代机载吊放声呐，装备直-20F直升机。

KLC-1=H/KLC-1|KLC-1雷达是直-9C直升机装备的水面搜索雷达，可搜索和跟踪水面舰艇目标，并通过数据链为反舰导弹提供中继制导，装备直-9C直升机。

KLC-3B=H/KLC-3B|KLC-3B雷达是采用平板缝隙天线的新一代X波段多用途直升机机载搜索雷达，具有优异的海面/低空搜索和侦察能力，通过机载数据链可将雷达探测到的海面战术态势和目标的信息传送给地面或舰上的指挥所。中近程探测和抗干扰性能强，装备直-9D直升机。

KLC-3C=H/KLC-3C|KLC-3C雷达是采用有源相控阵体制的X波段多用途直升机机载搜索雷达，具有优异的海面/低空搜索和侦察能力，作用距离远，分辨率高，可通过数据链传递战场态势感知信息，装备直-9F直升机。

KLC-20=H/KLC-20|KLC-20雷达（虚构代号）是新一代有源相控阵多用途直升机机载搜索雷达，装备直-20F直升机。

RKL-9_RWR=H/RKL-9|RKL-9雷达告警接收器

RKL-9A_RWR=H/RKL-9A|RKL-9A雷达告警接收器

RKL-20_ESM=H/RKL-20 ESM|RKL-20电子支援装置（虚构代号）是直-20F直升机搭载的舰机联合电子支援系统

RKL-20_RWR=H/RKL-20 RWR|RKL-20雷达告警接收器

Z-20_laser=机载综合光电激光器|直-20直升机综合光电系统搭载的激光器。

###########################################################

#---------------------------- Sub ------------------------------

###########################################################

#---------------------------------------- Visual ----------------------------------------
ZQQ-5A=ZQQ-5A|加装红外光电设备（FLIR）的数字光电桅杆。
#---------------------------------------- Radar ----------------------------------------
LQK-359A=LQK-359A|潜艇用雷达桅杆，具备有限对空搜索能力。
#---------------------------------------- ESM ----------------------------------------
RQL-927A_ESM=RQL-927A|潜艇用电子支援系统桅杆，具备有限超地平线探测能力
#---------------------------------------- Sonar ----------------------------------------
SQZ-265A=SQZ-265A|SQZ-265A是中国研制的第三代潜艇数字式低频综合声呐，自动化程度高，信号处理能力强，性能相当于美国海军AN/BQQ-5D声呐
SQG-207=SQG-207|SQG-207是中国研制的低频多线阵舷侧声呐，具备远程被动探测和测距能力，能够为鱼雷攻击提供可靠火控参数。
SQZ-265A_Interceptor=SQZ-265A附属侦察声呐|SQZ-265A综合声呐系统搭载的侦察声呐功能，能够对主动声呐信号进行侦听和测向。

###########################################################

#---------------------------- Aircraft ------------------------------

###########################################################

#---------------------------------------- Visual ----------------------------------------
3rd_Gen_FLIR=FLIR|机载综合红外光电系统
#---------------------------------------- ESM ----------------------------------------
RKL-500_ESM=K/RKL-500 ESM|K/RKL-500（虚构代号）是人民空军新一代特种飞机装备的综合电子支援和侦查分析设备，具备电磁辐射信号，通讯信号拦截和电子情报分析功能
RKL-500B_OTH_ESM=K/RKL-500B ESM|K/RKL-500B（虚构代号）是人民空军运-9电子侦察机装备的大孔径综合电子支援设备，具备超地平线辐射探测和跟踪能力，采用大孔径共形天线。
RKL-500_RWR=RWR|雷达告警设备 
#---------------------------------------- ECM ----------------------------------------
RKZ-500_ECM=K/RKZ-500 ECM|K/RKZ-500（虚构代号）是人民空军新一代特种飞机装备的自卫型机载电子干扰设备。
RKZ-1000_ECM=K/RKZ-1000 ECM|K/RKZ-1000（虚构代号）是运-9雷达干扰机装备的进攻型机载电子干扰设备，具有功率大，作用距离远的特点，具备综合射频能力。
#---------------------------------------- MAD ----------------------------------------
KQT-8=KQT-8 磁异探测器|KQT-8磁异探测器（虚构代号）是运-8和运-9反潜巡逻机使用的磁异探测器
#---------------------------------------- Laser Designator ---------------------------

#======================================== Soviet Union ========================================
#---------------------------------------- Radar ----------------------------------------
Y-9DZ_SAR_L=合成孔径雷达（左）|合成孔径雷达吊舱（左侧）
Y-9DZ_SAR_R=合成孔径雷达（右）|合成孔径雷达吊舱（右侧）

#---------- Surface ships ----------]
#---Air/Air&Surface---
KLC-500=KLC-500 雷达|KLC-500雷达（虚构代号）是一种主动电子扫描数字阵列雷达（DAR），装备人民空军空警-500预警机。雷达采用固定三面阵布局，在雷达天线重量和尺寸都较小的情况下，探测作用距离和E-3C预警机的AN/APY-2雷达相当，具备强大的多目标跟踪处理能力。雷达能够在约100公里的距离上发现并跟踪迎头姿态的隐身目标，并能通过卫星数据链向其他单位更新区域内空情态势信息。

KLC-8=KLC-8 雷达|KLC-8雷达（虚构代号）是运-8FQ反潜巡逻机使用的水面搜索雷达，安装于机鼻下方，可360度探测水面目标，包括潜望镜和通气桅杆等。
KLC-8A=KLC-8A 雷达|KLC-8A雷达（虚构代号）是运-9FQ反潜巡逻机使用的水面搜索雷达，采用有源相控阵天线，可探测前半球水面目标，包括潜望镜和通气桅杆等。
# ----------- Noisemakers/Chaff -----------










