[ -------------------- Missile Launchers -------------------- ]

[Mugin5FPV]
NumberOfAttachments=1
AttachmentPosition1=0.077896,0.016445,-0.028958
#HorizontalDegreesPerSecond=40   // rotation speed horizontally
VerticalDegreesPerSecond=5     // rotation speed vertically
MoveToRestPositionTime=10.0      // time in seconds the weapon goes back to rest position if not used
ReloadTime=120.0                   // time in seconds after firing until launcher is reloaded
FireRate=1
#SmokeEffect=effects/weapons/emitters/LauncherSmoke
#SmokeEffectPosition=0,0.045,-0.14
PreLaunchDelay=5
ModuleType=SmallLauncher


