#Author: MitcheLL600-Euromod
[Animations]
NumberOfAnimations=2
# Keep this value!
Animation1=WellDoors_Open
# Keep this value!
Animation2=WellDoors_Close

[WellDoors_Open]
# Keep this value!
NumberOfSequencesToPlay=1
# Keep this value!
Sequence1=WellDoors_Open_Sequence
# Change the sequence model name to your ramp door name
Sequence1_Model=rnn_lpd_johan_ramp_outside

[WellDoors_Close]
# Keep this value!
NumberOfSequencesToPlay=1
# Keep this value!
Sequence1=WellDoors_Close_Sequence
# Change the sequence model name to your ramp door name
Sequence1_Model=rnn_lpd_johan_ramp_outside

[WellDoors_Open_Sequence]
NumberOfSteps=2
Time1=0
# Alter this angle depending on the angle of your ramp door
RotationX1=75
Smoothness1=EaseInOut
# Alter the time of the door opening to your pleasing
Time2=10
RotationX2=0
Smoothness2=EaseInOut

[WellDoors_Close_Sequence]
NumberOfSteps=2
Time1=0
RotationX1=0
Smoothness1=EaseInOut
# Alter the time of the door opening to your pleasing
Time2=10
# Alter this angle depending on the angle of your ramp door
RotationX2=75
Smoothness2=EaseInOut