#Author: MitcheLL600-Euromod
[---------- General Data ----------]
[General]


[WellDeck]
# Adjust this for Landing ships or none. true=flooding buttons false=no buttons
WellDeck=true

# Tune this per ship.
MaxFloodingPercent=25

# Percent per second.
FloodRatePercentPerSecond=5
PumpRatePercentPerSecond=8

# Prevent Auto Damage Control(DC) from immediately pumping intentional ballast out.
DisableAutoDCWhileOperating=true

# Optional AnchorChain/Sea Power code animations.
FloodAnimation=WellDoors_Open
PumpAnimation=WellDoors_Close

[Physics]


[Buoyancy]


[Animations]
NumberOfAnimationReferences=1
AnimationFile_1=animations_example_welldeck
