[General]
HullnumberReference=Hullnumber
EmblemReference=Emblem
NationFlagReference=Flag1
AllVariantsAreOfSameNation=True //Speeds up nation sorting. Only needed if there is more then 1 nation variants. Default is 'true'
NumberOfVariants=4

[Default]
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_it
Nation=Italy
ServiceDate=1978|2002

[Variant1]
ResourcesHullnumberFolder=ships/materials/hullnumbers/pns_ss_han1
HullnumberTexture=transparent
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=ae-26
#ResourcesLiveryFolder=ships/rn_dd_c-class/
#LiveryTexture=usn_ae_kilauea_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_it
Nation=Italy
ServiceDate=1978|1996

[Variant2]
ResourcesHullnumberFolder=ships/materials/hullnumbers/pns_ss_han1
HullnumberTexture=transparent
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=ae-26
#ResourcesLiveryFolder=ships/rn_dd_c-class/
#LiveryTexture=usn_ae_kilauea_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_it
Nation=Italy
ServiceDate=1978|2002

[Variant3]
ResourcesHullnumberFolder=ships/materials/hullnumbers/pns_ss_han1
HullnumberTexture=transparent
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=ae-26
#ResourcesLiveryFolder=ships/rn_dd_c-class/
#LiveryTexture=usn_ae_kilauea_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_it
Nation=Italy
ServiceDate=1978|1998

[Variant4]
ResourcesHullnumberFolder=ships/materials/hullnumbers/pns_ss_han1
HullnumberTexture=transparent
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=ae-26
#ResourcesLiveryFolder=ships/rn_dd_c-class/
#LiveryTexture=usn_ae_kilauea_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_it
Nation=Italy
ServiceDate=1978|2002