[ ========================================= General ========================================== ]



[======================================== Soviet Union ========================================]
############################################################
# Soviet Union
############################################################

[ ---------------------------- Radars ----------------------------- ]
[---------- Surface ships ----------]
[---Air/Air&Surface---]


[---Surface only---]


[---Fire Control---] + search radars linked to FC radars


[---------- Submarines ----------]


[---------- Land units ----------]
[---Air/Air&Surface---]

[36H6]
#36H6 regiment-level air search radar for S-400 SAM system
Kind=Radar
Type=Search            // Classes can be "Search", "Targeting"
HasDataLink=True       // true means the sensor data will be used for the entire task force via data link, false local use only
Role=Air               // Role can be "Surface", "Air", "AirAndSurface"
Mode=Illuminate        // Can be "Illuminate", "RadioCommand"
TargetChannels=85       // if applicable number of targets it can track simultaneously
WeaponChannels=48      // if applicable number of weapons (missiles) it can guide simultaneously
RotationDirection=1    // -1 means left, 1 means right
RPM=12                 // revolutions per minute
MinRange=0.5           // min range in km
MaxRange=600.0         // max range in km
MinAltitude=0          // min altitude in meters, relevant for air, unused for surface
MaxAltitude=147000     // max altitude in meters, relevant for air, unused for surface
RangeResolution=185.0  // defines the minimum range where two targets behind can be recognized as two; in meters
BeamWidth=0.5          // defines the beam width in degrees for BearingResolution >= 2*Dist*sin(BeamWidth/2)
Gain=50.0              // gain in dB on the sensor
Frequency=S-Band       // frequency band
PeakPower=4500.0       // output peak power in kW


[ ------------------------ Aircraft Radars ------------------------- ]
[---Air/Air&Surface---]

[---Surface only---]


[ ---------------------------- Sonars ----------------------------- ]


[---------- Surface ships ----------]


[----- Towed/VDS -----]


[---------- Submarines ----------]


# -------------------- Towed --------------------


[---------- Aircraft ----------]


[---------- Sonobuoys ----------]


[ ------------------------ Visual/Infared ------------------------- ]


[---------------------------------------- ESM ----------------------------------------]


[ ------------------------------ ECM ------------------------------ ]


[---------------------------------------- MAD ----------------------------------------]


[---------------------------------------- Laser Designator ---------------------------]

