[Language_en]
Name=Type 003 CV / future Type 004 CVN aircraft carriers
Description=This mod adds the Type 003 CV and Type 004 CVN of the PLAN.

[Compatibility]
;ApproximateVersion is the second check and will override all statements below. This checks MAJOR and MINOR match but will accept higher PATCH.
;Would recommend this as a default case for starters.
ApproximateVersion=0.8.0