# ver. 20260714
#
[General]
DefaultSquadronShortName=N/A
[********************** Civilian *********************]
[---------------------- Aircraft ---------------------]

[spa_ab212]
Type=Helicóptero ASW
Default=AB-212 ASW,AB-212
DefaultDescription=El AB-212 es una versión bimotor derivado del Bell UH-1 Huey fabricado bajo licencia por la empresa italiana Agusta con destino la Armada Italiana realizando diversos cometidos. Se inició la producción a mediados de los años 70. En 1974, la Flotilla de Aeronaves (FLOAN) de la Armada Española comenzó a recibir las primeras unidades de un total de 14 helicópteros, reemplazando gradualmente a los obsoletos helicópteros antisubmarinos AB-204. El 30 de julio de 2024 fueron dados de baja los diez helicópteros que aún permanecían en servicio. Tuvieron su base en la base naval de Rota (Cádiz) formando la 3ª Escuadrilla, y operaron tanto desde buques del grupo anfibio como de los portaaeronaves Dédalo y Príncipe de Asturias.
Squadron1=3ª Escuadrilla camuflaje azul
Squadron2=3ª Escuadrilla camuflaje gris
Callsigns=Squadron1,Gato|Squadron2,Gato

[spa_ah-1g]
Type=Helicóptero de Ataque
Default=AH-1G,AH-1G
DefaultDescription=El AH-1 Cobra es un helicóptero de ataque que se desplegó por primera vez durante la Guerra de Vietnam.  En España la 7ª Escuadrilla de la Flotilla de Aeronaves (FLOAN) de la Armada Española estuvo activa entre 1972 y 1984 operando hasta 8 unidades del AH-1 Cobra. 
Squadron1=AH-1G 7ªEscuadrilla, AH-1G
Callsigns=Squadron1,Cobra

[spa_av-8a]
Type=Caza
Default=AV-8S, AV-8S Matador
DefaultDescription=La 8ª Escuadrilla de Aeronaves de la Armada Española fue pionera en el uso de aviones V/STOL (despegue y aterrizaje vertical/corto) en España, operando los Harrier AV-8A/S "Matador" desde 1976 hasta 1996. Basada en Rota y embarcada en el portaaeronaves "Dédalo", fue fundamental para la aviación de caza naval española antes de ser disuelta y sus efectivos integrados en la 9ª Escuadrilla.
Squadron1=AV-8S 8ª Escuadrilla,AV-8S
Callsigns=Squadron1,Matador

[spa_f1c]
Type=Caza
Default=Mirage F1CE,F1CE
DefaultDescription=El Mirage F1CE representa la principal variante interceptora del Ejército del Aire español durante la última etapa de la Guerra Fría. Optimizado para la defensa aérea de alta velocidad, este modelo 'C' está equipado con el radar Cyrano IV y armado con misiles Matra Magic y, posteriormente, Super 530. En el teatro de operaciones español, estos 'Abuelas' constituyeron la columna vertebral de la Fuerza de Alerta de Reacción Rápida (QRA), defendiendo la Península Ibérica y las Islas Canarias con una eficacia en operaciones scramble sin parangón.
Squadron1=Escuadron 141,F1CE
Squadron2=Escuadron 142,F1CE
Callsigns=Squadron1,Chico|Squadron2,Dardo

[spa_f1e]
Type=Caza
Default=Mirage F1EE,F1EE
DefaultDescription=El Mirage F1EE es la versión polivalente mejorada de la flota española de F1. Distinguido por su sonda de reabastecimiento fija para un mayor alcance, la variante «EE» cuenta con un sistema de navegación inercial (INS) mejorado y capacidades especializadas aire-tierra. En el contexto español, estos aviones proporcionaron una sofisticada plataforma de ataque y asalto marítimo, capaz de proyectar poderío sobre el Mediterráneo y el Atlántico, manteniendo al mismo tiempo una letal capacidad aire-aire.
Squadron1=Escuadron 462,F1EE
Callsigns=Squadron1,Alcon

[spa_f-4c]
Type=Caza
Default=F-4C,F-4C
DefaultDescription=El Ala 12, con base en Torrejón de Ardoz (Madrid), fue la unidad encargada de operar el mítico McDonnell Douglas F-4C Phantom II (denominado C.12) en España.  Llegaron en 1971 de excedentes USAF, un total de 36 unidades.  Operativos hasta 1989 en su variante de caza.
Squadron1=F-4C Escuadron 121,F-4C
Squadron2=F-4C Escuadron 122,F-4C
Callsigns=Squadron1,Poker|Squadron2,Tenis

[spa_f104g]
Type=Caza
Default=F-104G,F-104G
DefaultDescription=El F-104 Starfighter es un interceptor supersónico fabricado en Estados Unidos como parte de la serie de cazas "Century Series" y uno de los aviones a reacción más reconocibles de la historia de la aviación. Construido en la década de 1960, fue diseñado con una estructura lo más pequeña y sencilla posible, a la vez que alcanzaba la máxima altitud y capacidad de ascenso. El F-104G es una variante mejorada de cazabombardero del Starfighter, desarrollada a petición de varios operadores extranjeros. Cuenta con un fuselaje y alas reforzados, el nuevo radar NASARR F-15A y un sistema de navegación inercial Litton LN-3 (el primero en un caza de producción). Es la variante más producida del F-104 y la más utilizada por operadores europeos como Italia y Alemania Occidental.
Squadron1=F-104G Escuadron 61,F-104G
Callsigns=Squadron1,Dardo

[spa_mirage_iii]
Type=Caza
Default=Mirage IIIEE,M.IIIEE
DefaultDescription=El Mirage IIIEE es la variante de ataque a tierra y polivalente para el Ejército del Aire del Mirage III. Se distingue por su fuselaje más largo para albergar aviónica avanzada y cuenta con un radar de navegación mejorado y capacidades especializadas de ataque a tierra en cualquier condición meteorológica. En el contexto español, estos aviones proporcionaron al Ejército del Aire su primer interceptor y cazabombardero supersónico todo tiempo, constituyendo un pilar fundamental de la defensa aérea y la capacidad de ataque táctico de España durante la guerra fría.
Squadron1=Escuadron 111 (Early),Mirage IIIEE
Squadron2=Escuadron 111 (Late),Mirage IIIEE
Callsigns=Squadron1,Dolar|Squadron2,Dolar

[spa_md500]
Type=Helicóptero ASW
Default=MD500,MD500
DefaultDescription=Los primeros MD500 se entregaron en 1972. Al igual que otros helicópteros de la flota, el Hughes prestó servicio inicialmente como plataforma antisubmarina, capaz de transportar un detector de anomalías magnéticas (MAD) y torpedos MK-44/46, antes de pasar a su misión principal de entrenamiento de vuelo.  Encuadrados en la 6ª Escuadrilla con base en Rota.
Squadron1=MD500 6ªEscuadrilla camuflaje azul, MD500
Squadron2=MD500 6ªEscuadrilla camuflaje gris, MD500
Callsigns=Squadron1,Argo|Squadron2,Argo

[spa_p-3a]
Type=Patrulla Marítima,MPA
Default=P-3A,P-3A
DefaultDescription=Desarrollado a partir del avión de pasajeros Electra, el P-3 es un avión de vigilancia marítima y antisubmarina increíblemente popular, desarrollado para la Armada de los Estados Unidos. A lo largo de los años, el P-3 ha experimentado numerosas mejoras de diseño, sobre todo en sus sistemas electrónicos. Numerosas armadas y fuerzas aéreas de todo el mundo siguen utilizando este modelo, principalmente para patrulla marítima, reconocimiento, guerra antisuperficie y guerra antisubmarina. Se han construido un total de 757 P-3. El P-3 Orion en España fue operado por el 221 Escuadrón del Grupo 22 (Ala 11), con base en Morón de la Frontera (Sevilla). Entró en servicio en 1973 y se retiró oficialmente en diciembre de 2022 tras casi 50 años de servicio en misiones de patrulla marítima, lucha antisubmarina y vigilancia (Atalanta)
Squadron1=P-3A Grupo 22,P-3A
Callsigns=Squadron1,Cisne

[spa_sh-3d]
Type=Helicóptero ASW
Default=SH-3D,SH-3D
DefaultDescription=Desarrollado para contrarrestar la creciente amenaza de los submarinos soviéticos, el SH-3D es una plataforma de guerra antisubmarina muy eficaz, ampliamente utilizada en la OTAN. Existen numerosas subvariantes de la aeronave, que ofrecen capacidades que van desde búsqueda y rescate (SAR) hasta alerta temprana aerotransportada (AEW). El SH-3D, en su versión civil, también es operado por varias aerolíneas, especialmente en los yacimientos petrolíferos del Mar del Norte.  En España formaron parte de la 5ª Escuadrilla desde 1966 hasta 2022, cuando fueron sustituidos por el SH-60F.
Squadron1=SH-3D 5ª Escuadrilla camuflaje azul,SH-3H
Squadron1=SH-3D 5ª Escuadrilla camuflaje gris,SH-3H
Callsigns=Squadron1,Morsa|Squadron2,Morsa

[spa_sh-3d_AEW]
Type=AEW Helicopter
Default=SH-3D AEW,SH-3D AEW
DefaultDescription=El SH-3D AEW es una variante especializada de alerta temprana aerotransportada del icónico helicóptero Sikorsky Sea King, adaptada principalmente para la Armada Española para proporcionar vigilancia marítima y protección aérea a sus grupos de combate
Squadron1=SH-3D 5ª AEW Escuadrilla,SH-3D AEW
Callsigns=Squadron1,Morsa