# ver. 20260816
#
[LoadoutNames]
AB212=AB212 Helicopter
Seaking=SH-3D Helicopter
# Superpuma=AS332B SuperPuma FAMET

CASLongRange=Apoyo Aéreo Cercano a larga distancia		// Same as CAS but less weapons, more fuel

Amphib=Desembarco anfíbio
Deck2=Aviones en cubierta
noDeck2=Sin aviones en cubierta
Legion=Legionarios

ULQ6=AN/ULQ-6 ECM