# ver. 20260816
#
[ae_ao_teide]
Type=AO,Petrolero de flota
Default=Clase Teide,Teide
DefaultDescription=Proyectado en 1952 y construido por la Empresa Nacional Bazán en Cartagena, el Teide fue un petrolero de flota que sirvió en la Armada Española entre 1956 y 1988. Basado en un diseño de buque civil, fue adaptado para proporcionar aprovisionamiento de combustible en alta mar, convirtiéndose durante más de tres décadas en la principal unidad de apoyo logístico y suministro para la flota militar española.
Variant1=BP11 Teide,Teide

[ae_cvl_dedalo]
Type=CVL,Portaaviones
Default=Clase Dedalo (Inicial),Dedalo
DefaultDescription=El Dédalo (1967) en su configuración inicial sirvió como el buque insignia de la Armada Española y núcleo de su capacidad de guerra antisubmarina (ASW). Cedido inicialmente por los EE. UU. tras reactivarlo de la reserva, el ex-USS Cabot operaba en esta época exclusivamente como un portahelicópteros, desplegando aeronaves SH-3 Sea King y AB-204/212 para localizar amenazas submarinas. En este periodo inicial, el buque aún conservaba su electrónica original de la Segunda Guerra Mundial y Guerra Fría temprana, y su defensa descansaba en los tradicionales montajes de cañones Bofors de 40 mm, siendo una plataforma vital para la proyección aeronaval antes de la incorporación de la aviación de ala fija.
Variant1=R01 Dedalo,Dedalo

[ae_cvl_dedalo_late]
Type=CVL,Portaaviones
Default=Clase Dedalo (Modernizado),Dedalo
DefaultDescription=Tras una serie de modificaciones pioneras a mediados de los setenta, que incluyeron el refuerzo metálico de la popa de su cubierta de vuelo para resistir el calor, el Dédalo se convirtió en el primer portaaviones del mundo en operar de forma regular cazas STOVL AV-8S Matador (Harrier). Esta profunda actualización transformó al veterano buque de un portahelicópteros ASW a una plataforma de superioridad aérea y ataque ligero, incorporando nuevos radares de exploración aérea, sistemas de comunicaciones modernos y una suite electrónica actualizada que lo mantuvo como el eje de la Fuerza Operativa Alfa en el Mediterráneo hasta su baja en 1989. Fue reemplazado por el R-11 Príncipe de Asturias.
Variant1=R01 Dedalo,Dedalo

[ae_cvl_principe_asturias]
Type=CVL,Portaaviones
Default=Clase Principe de Asturias,R11
DefaultDescription=El Príncipe de Asturias, originalmente llamado Almirante Carrero Blanco, fue un portaaeronaves y buque insignia de la Armada Española. Fue construido en los astilleros de Bazán en Ferrol y entregado a la Armada Española el 30 de mayo de 1988. El anterior portaaeronaves, Dedalo, fue reemplazado como buque insignia de la flota por el Príncipe de Asturias. El buque estuvo asignado permanentemente al Grupo Alfa, compuesto por el portaaeronaves y seis fragatas de la clase Santa María (una versión Española de la clase Oliver Hazard Perry de la Armada de los Estados Unidos). Otros buques, como buques logísticos, petroleros y corbetas, se asignan frecuentemente al Grupo cuando es necesario. El Príncipe de Asturias y el Grupo Alfa participaron en operaciones de mantenimiento de la paz en el mar Adriático. El buque fue víctima de los recortes en defensa, siendo dado de baja oficialmente el 6 de febrero de 2013.
Variant1=R11 Principe de Asturias,Principe de Asturias

[ae_dd_churruca_fram_i]
Type=DD,Destructor
Default=Clase ChurrucaFRAM I,Gearing
DefaultDescription=La clase Churruca fue una serie de cinco buques de la Armada Española que derivaron de los destructores de la clase Gearing de la Armada estadounidense. Todos ellos fueron adquiridos en la década de 1970 con la configuración FRAM I.
Variant1=D61 Churruca,Churruca
Variant2=D62 Gravina,Gravina
Variant3=D63 Mendez Nunez,Mendez Núñez
Variant4=D64 Langara,Langara

[ae_dd_churruca_fram_ib]
Type=DD,Destructor
Default=Clase Churruca FRAM II,Gearing
DefaultDescription=El último de los destructores españoles de la clase Gearing, el «Blas de Lezo», junto con otros buques, formaba parte de una variante del programa FRAM-I que consistía en retirar la tercera torreta —situada en la popa— en lugar de la segunda, lo que supuso el cambio de ubicación de los tubos antisubmarinos, que originalmente se encontraban allí, detrás del lanzador ASROC.
Variant1=D65 Blas de Lezo,Blas de Lezo

[ae_ffg_baleares]
Type=FFG,Fragata
Default=Clase Baleares (Inicial),Baleares
DefaultDescription=Esta clase fue fruto de una estrecha colaboración entre España y Estados Unidos, y en líneas generales es similar a la clase Knox de la Armada de los Estados Unidos, aunque difiere en el sistema de misiles, los tubos lanzatorpedos y la ausencia de instalaciones para helicópteros. Todos tenían su base en Ferrol, donde formaban la Escuadra 31, y prestaron servicio en la Armada Española desde septiembre de 1983 hasta 1988, cuando se llevó a cabo la modernización (MLU).
Variant1=F71 Baleares,Baleares
Variant2=F72 Andalucia,Andalucia
Variant3=F73 Cataluna,Cataluna
Variant4=F74 Asturias,Asturias
Variant5=F75 Extremadura,Extremadura

[ae_ffg_baleares_late]
Type=FFG,Fragata
Default=Clase Baleares (Modernizada),Baleares
DefaultDescription=El programa de actualización a mitad de vida útil (MLU) se puso en marcha en 1988; entre las modificaciones realizadas se incluían la instalación de dos sistemas CIWS Meroka de 20 mm, el sistema Link 11, nuevos sistemas de guerra electrónica, dos lanzadores cuádruples Mk 141 Harpoon, cuatro lanzadores de chaff Mk 36 SRBOC y la sustitución del sonar SQS 23 por el DE 1160 (SQS-56). Todos ellos tenían su base en Ferrol, donde formaban la Escuadra 31, y prestaron servicio en la Armada Española desde 1988 hasta 2009.
Variant1=F71 Baleares,Baleares
Variant2=F72 Andalucia,Andalucia
Variant3=F73 Cataluna,Cataluna
Variant4=F74 Asturias,Asturias
Variant5=F75 Extremadura,Extremadura

[ae_ffg_descubierta]
Type=FS,Corbeta
Default=Clase Descubierta (Inicial),Descubierta
DefaultDescription=Oficialmente clasificadas como corbetas, basadas en el diseño original portugués «Joao Coutinho» y considerablemente modificadas por Bazan. Incluían el uso de una chimenea en forma de Y y un armamento pesado para su tonelaje. Las medidas de reducción de ruido incluían un enmascarador y un generador de turbina de gas auxiliar para realizar búsquedas antisubmarinas silenciosas. Todas estaban basadas en Cartagena, formando el Escuadrón 21. La primera de su clase entró en servicio en noviembre de 1978 y sirvieron como corbetas hasta el año 2000, cuando fueron convertidas en patrulleras. También se les llamaba Hormiga Atómica por la cantidad de armamento concentrado en tan poco espacio.
Variant1=F31 Descubierta,Descubierta
Variant2=F32 Diana,Diana
Variant3=F33 Infanta Elena,Infanta Elena
Variant4=F34 Infanta Cristina,Infanta Cristina
Variant5=F35 Cazadora,Cazadora
Variant6=F36 Vencedora,Vencedora
Variant7=F946 El Suez,El Suez
Variant8=F941 Abu Qir,Abu Qir
Variant9=F501 Errhamani,Lieutenant Colonel Errhamani

[ae_ffg_descubierta_late]
Type=FS,Corbeta
Default=Clase Descubierta (Modernizada),Descubierta
DefaultDescription=A partir de 1986, la Armada Española modernizó la clase para subsanar las primeras limitaciones en materia de guerra electrónica y defensa aérea. El obsoleto sistema italiano Beta 1000 fue sustituido por el procesador ESM nacional CESELSA Deneb, estrechamente integrado con los inhibidores activos de ECM Canopus y los lanzadores automatizados de señuelos Mk-36 SRBOC. Las capacidades de combate se perfeccionaron aún más mediante el sistema de mando TRITAN, que permitía un mejor intercambio de datos a través del Link dentro de la Flota, y la estandarización del sistema SAM Albatros/Aspide para mejorar la resistencia a las interferencias. Conservaron estas características de combate de alta intensidad hasta su reconversión en lanchas patrulleras a partir del año 2000.
Variant1=F31 Descubierta,Descubierta
Variant2=F32 Diana,Diana
Variant3=F33 Infanta Elena,Infanta Elena
Variant4=F34 Infanta Cristina,Infanta Cristina
Variant5=F35 Cazadora,Cazadora
Variant6=F36 Vencedora,Vencedora

[ae_ffg_santa_maria]
Type=FFG,Fragata
Default=Clase Santa Maria (Inicial),Santa Maria
DefaultDescription=La clase Santa María de fragatas de misiles guiados es la designación de la Armada Española para seis buques de guerra basados ​​en las fragatas estadounidenses de la clase Oliver Hazard Perry. Los buques españoles tienen una manga ligeramente mayor y fueron construidos con una mayor reserva de peso para futuras mejoras. Otras modificaciones respecto al modelo básico incluyen la sustitución del sistema Phalanx por el Meroka y un radar de búsqueda aérea RAN-12L para proporcionar cobertura a baja altitud contra misiles antibuque que activan el sistema CIWS Meroka. Todos ellos con base en Rota, conformando el 41.er Escuadrón, prestan servicio en la Armada Española desde octubre de 1986.
Variant1=F81 Santa María,Santa María
Variant2=F82 Victoria,Victoria
Variant3=F83 Numancia,Numancia
Variant4=F84 Reina Sofía,Reina Sofía
Variant5=F85 Navarra,Navarra
Variant6=F86 Canarias,Canarias

[ae_ffg_santa_maria_late]
Type=FFG,Frigate
Default=Clase Santa Maria (Modernizada),Santa Maria
DefaultDescription=En 2005 se inició la modernización (MLU) de las fragatas F80, durante la cual se instalaron nuevos equipos: sensores SVO/IR, un nuevo radar RAN-30XL, el sistema ESM Rigel, SATCOM, compatibilidad con el SH-60B Bloque 1 y los misiles SM-1 VIB; además, hubo que retirar el TACTASS, ya que la Armada lo consideraba ineficaz frente a las amenazas actuales e inadecuado para operar en aguas poco profundas.
Variant1=F81 Santa María,Santa María
Variant2=F82 Victoria,Victoria
Variant3=F83 Numancia,Numancia
Variant4=F84 Reina Sofía,Reina Sofía
Variant5=F85 Navarra,Navarra
Variant6=F86 Canarias,Canarias

[ae_lpa_castilla]
Type=LPA,Buque de Desembarco Anfibio
Default=Clase Castilla,Paul Revere
DefaultDescription=Ambos buques, antiguos transportes anfibios de ataque de la clase Paul Revere, entraron en servicio a mediados de 1980 y estuvieron en servicio hasta 1998 (L21) y 2000 (L22).
Variant1=L21 Castilla,Castilla
Variant2=L22 Aragón,Aragón

[ae_lsd_galicia]
Type=LSD,Buque de Desembarco Anfibio
Default=Clase Galicia,Casa Grande
DefaultDescription=Denominación en la Armada Española para el buque dique de desembarco (LSD) de la clase Casa Grande de la US Navy.\n\nComisionado originalmente como USS San Marcos (LSD-25) en 1945, fue transferido a España el 1 de julio de 1971 prestando servicio como Galicia (inicialmente TA-31 y posteriormente L-31).\n\nA lo largo de su vida operativa participó en misiones destacadas como el apoyo durante la Marcha Verde en 1975. Armado con cañones Bofors de 40 mm y equipado con cubierta de vuelo para hasta tres helicópteros AB-212, causó baja a principios de 1988.
Variant1=L31 Galicia,Galicia

[ae_lst_hernan_cortes]
Type=LST,Buque de Desembarco Anfibio
Default=Clase Hernan Cortes-class,Newport
DefaultDescription=Clase Newport de la USN. El primero fue transferido desde EE. UU. como L41 en agosto de 1994 y dada de baja en 2009, el segundo, transferido en abril de 1995 como L42 y dada de baja en 2012. Todo el armamento original fue desmantelado para su transferencia, por lo que el Phalanx no estaba operativo. Tenían su base en Rota.
Variant1=L41 Hernan Cortes,Hernan Cortes
Variant2=L42 Pizarro,Pizarro

[ae_mso_guadalete]
Type=MSO,Dragaminas
Default=Clase Guadalete,Aggressive
DefaultDescription=Los tres primeros buques de la clase Aggressive de la Armada de los Estados Unidos fueron transferidos y puestos en servicio en julio de 1971, y el cuarto fue entregado en abril de 1972. Entre 1984 y 1986 se llevó a cabo una modernización para extender su vida útil hasta 1992, cuando fueron reemplazados por los MCMV de la clase Segura.
Variant1=M41 Guadalete,Guadalete
Variant2=M42 Guadalmedina,Guadalmedina
Variant3=M43 Guadalquivir,Guadalquivir
Variant4=M44 Guadiana,Guadiana

[ae_msc_jucar]
Type=MSC,Dragaminas
Default=Clase Jucar,Adjutant
DefaultDescription=Principalmente cedidos en préstamo en el marco del pacto de asistencia para la defensa militar, se construyeron más de 200 de estos pequeños dragaminas durante las décadas de 1950 y 1960. Estos buques, ampliamente exportados, prestaron servicio en más de 25 países, utilizando sus cascos de madera para evadir las minas magnéticas.
Variant1=M21 Jucar,Jucar
Variant2=M22 Ebro,Ebro
Variant3=M23 Duero,Duero
Variant4=M24 Tajo,Tajo
Variant5=M25 Genil,Genil
Variant6=M26 Odiel,Odiel
Variant7=M27 Sil,Sil
Variant8=M28 Miño,Miño

[ae_ptg_lazaga]
Type=PFG,Buque de Ataque Rápido
Default=Clase Lazaga,Lazaga
DefaultDescription=Basados en el Lürssen Albatros Tipo 143, pero con sólo dos motores, fueron encargados en 1972 principalmente para tareas de protección pesquera, aunque puede equiparse con misiles ESM, SSM y tubos lanzatorpedos si es necesario. Prestó servicio en la Armada Española desde julio de 1975 hasta junio de 1993.
Variant1=P01 Lazaga,Lazaga
Variant2=P02 Alsedo,Alsedo
Variant3=P03 Cadarso,Cadarso
Variant4=P04 Villaamil,Villaamil
Variant5=P05 Bonifaz,Bonifaz
Variant6=P06 Recalde,Recalde

[ae_ptm_lazaga]
Type=PTM,Lancha Portamisiles
Default=Lazaga-class,Lazaga
DefaultDescription=Basados en el Lürssen Albatros Tipo 143, pero con sólo dos motores, fueron encargados en 1972 principalmente para tareas de protección pesquera, aunque puede equiparse con misiles SSM, ESM y tubos lanzatorpedos si es necesario. Prestó servicio en la Armada Española desde julio de 1975 hasta junio de 1993.
Variant1=P03 Cadarso,Cadarso
Variant2=P04 Villaamil,Villaamil
Variant3=P05 Bonifaz,Bonifaz
Variant4=P06 Recalde,Recalde

[ae_sa_tiburon]
Type=SS,Submarino de Bolsillo
Default=Clase Tiburón,Tiburón
DefaultDescription=La clase Tiburón fue una serie de submarinos de bolsillo españoles desarrollada en la década de 1960 para operaciones de asalto en aguas poco profundas y de fuerzas especiales. Con un desplazamiento sumergido de unas 78 toneladas, estas embarcaciones en miniatura estaban armadas con dos tubos lanzatorpedos de 533 mm y optimizadas para el reconocimiento sigiloso. Solo se construyeron dos unidades experimentales (SA-51 y SA-52). Aunque nunca entraron en servicio activo en la flota, sirvieron como importantes bancos de pruebas para los conceptos de propulsión silenciosa de España.
Variant1=SA51 Tiburón I,SA-51
Variant2=SA52 Tiburón II,SA-52

[ae_ssk_delfin]
Type=SS,SS
Default=Clase Delfín,Delfín
DefaultDescription=Basados ​​en la clase Daphné francesa, el primero fue comisionado en 1973 y el último en 1975, con base en Cartagena.
Variant1=S61 Delfín,Delfín
Variant2=S62 Tonina,Tonina
Variant3=S63 Marsopa,Marsopa
Variant4=S64 Narval,Narval

[ae_ssk_galerna]
Type=SS,SS
Default=Clase Galerna (Inicial),Agosta
DefaultDescription=Basado en la clase Agosta francesa, el primero fue comisionado en enero de 1983 y el último en enero de 1986, actualmente en servicio, con base en Cartagena.
Variant1=S71 Galerna,Galerna
Variant2=S72 Siroco,Siroco
Variant3=S73 Mistral,Mistral
Variant4=S74 Tramontana,Tramontana

[ae_ssk_galerna_mod]
Type=SS,SS
Default=Clase Galerna (Modernizada),Agosta
DefaultDescription=Modernizados con un sistema mejorado de control de tiro de torpedos, nuevos periscopios ESM e infrarrojos. Se instalaron nuevas baterías principales con sistema de control centralizado. La gran carena del Galerna comenzó en abril de 1993 y finalizó a finales de 1994, la del Siroco, a mediados de 1995; la del Tramontana, a principios de 1997, y la del Mistral, en 2000. Se instalaron paneles solares remolcados Solarsub en todos los buques de la clase durante las revisiones.
Variant1=S71 Galerna,Galerna
Variant2=S72 Siroco,Siroco
Variant3=S73 Mistral,Mistral
Variant4=S74 Tramontana,Tramontana
