#!/usr/bin/env python3
"""Build SEST Collection Fixes: the surgical overrides from the collection audit.

docs/collection-interop-audit.md examined every contested file across the 133
mods. Eleven of its findings were fixed by measured load-order moves (see
data/load-order.tokens.txt); the rest are value-level defects where no order
can win — the right stats are split across two mods, or every shipped copy has
the same bug. Those become overrides here, at the top of the order where the
SEST invariant guarantees they win.

Every file is a clone of one proven donor with the minimum deltas, each guarded
so an upstream change to the donor fails the build loudly instead of silently
shipping a stale merge. The audit cohort that justifies each fix is cited
inline — the full evidence (what each mod shipped, what was measured, what the
alternatives cost) lives in docs/collection-interop-audit.md.

Usage (repo root):  python3 integration/collection-fixes/build_patch.py
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MODS = ROOT / "mods-source"
OUT = Path(__file__).resolve().parent / "SEST_Collection_Fixes"

INFO_INI = """\
[Language_en]
Name=SEST Collection Fixes
Description=Value-level corrections from the collection-wide override audit: \
restores the vanilla-fidelity AGM-88 HARM the F-16 fleet was authored against, \
opens the GBU-53/B StormBreaker's 200-ft release window to 500-45000 ft, \
returns the GBU-12D and GBU-24 to conventional Paveway behaviour, gives the \
ESSM its only ECCM bonuses, re-unites the AC-130's 30mm definition with \
Euromod's ballistics, lifts the Hellfire's 2000-ft launch ceiling for the \
gunship, fixes AIM-9L/M impact size and speed-penalty keys, raises the \
AIM-9X turn rate, sharpens the GBU-39 SDB to its author's 1.5 m CEP, gives \
the KD-88 its 108 nm range and the AKF-98A its active-radar seeker, restores \
the eight Nimitz Expanded carriers with the CVN-70 typo fixed, and repairs \
the MH-60R's dangling Penguin seat reference. Generated by \
integration/collection-fixes/build_patch.py; must load above every workshop mod.

[Compatibility]
ApproximateVersion=0.8.2
"""


def read(mod, rel):
    src = MODS / mod / rel
    if not src.exists():
        sys.exit(f"donor missing (re-export {mod}?): {src}")
    return src.read_text(encoding="utf-8-sig", errors="replace")


def write(rel, text, header):
    dst = OUT / rel
    dst.parent.mkdir(parents=True, exist_ok=True)
    banner = "".join(f"# {line}\n" for line in header.splitlines())
    dst.write_text(banner + text, encoding="utf-8")


def edit(text, pattern, repl, expect, ctx):
    """Regex-sub with an exact match-count guard (the SEAD260 lesson: never
    splice against a file you have not just re-verified)."""
    out, n = re.subn(pattern, repl, text, flags=re.M)
    if n != expect:
        sys.exit(f"{ctx}: pattern {pattern!r} matched {n} times, expected {expect} "
                 "- donor changed upstream, rebase this fix")
    return out


def main():
    built = []

    # ------------------------------------------------------------------ ammo
    # usn_agm-88 [audit: usn_agm-88 cohort]. Murder Hornet (3430135740) ships
    # an AGM-45 Shrike under this id and never fires it - its own airframes all
    # use usn_agm-88g. Every actual consumer is an F-16 from 3758320372 (plus
    # SEST F-16CM JATM), authored against this vanilla-fidelity HARM copy.
    # Shipped verbatim: the audit diffed it against vanilla usn_agm-88a.ini.
    t = read("3758320372", "ammunition/usn_agm-88.ini")
    if "AGM-88A HARM" not in t:
        sys.exit("usn_agm-88: donor no longer labelled AGM-88A HARM - re-verify")
    write("ammunition/usn_agm-88.ini", t,
          "SEST Collection Fixes - restores the AGM-88A HARM (3758320372's vanilla-\n"
          "fidelity copy). The prior winner was an AGM-45 Shrike under this id: 50 nm\n"
          "range, 25 nm seeker, no loft, which nothing in the collection ever fired.")
    built.append("usn_agm-88")

    # usn_aim-9l / usn_aim-9m [audit: usn_aim-9l/9m cohort]. The deprecated
    # Super Hornet's winning copies carry ImpactSize=5 - a numeric non-enum
    # value used nowhere else (372x Medium / 350x Large / 167x VerySmall
    # repo-wide, zero numeric) - and dropped InterceptSpeedPenaltyMultiplier
    # that vanilla and the live successor both carry. Everything else kept.
    ispm = ("InterceptSpeedPenaltyMultiplier=0.75                  "
            "// multiplier to the severity of the speed penalty, 0.75 for good, "
            "1.0 for average, 1.25 for poor")
    for name, kp in (("usn_aim-9l", "0.80"), ("usn_aim-9m", "0.85")):
        t = read("3426791311", f"ammunition/{name}.ini")
        t = edit(t, r"^ImpactSize=5(\s)", r"ImpactSize=VerySmall\1", 1, name)
        if "InterceptSpeedPenaltyMultiplier" in t:
            sys.exit(f"{name}: donor now defines InterceptSpeedPenaltyMultiplier - rebase")
        t = edit(t, rf"^(KillProbability={re.escape(kp)})", ispm + "\n\\1", 1, name)
        write(f"ammunition/{name}.ini", t,
              "SEST Collection Fixes - base: 3426791311's file. Two deltas back to\n"
              "vanilla convention: ImpactSize 5 (non-enum) -> VerySmall, and the\n"
              "dropped InterceptSpeedPenaltyMultiplier=0.75 restored.")
        built.append(name)

    # usn_aim-9x [audit: usn_aim-9x cohort]. The 2027-mod winner is the right
    # era anchor (full kinematics, 19.4 nm reach, best ECCM) but its
    # MaxTurnRate=45 is the lowest of five authors by a wide margin (70 / 80 /
    # 150 / 180 elsewhere) on a thrust-vectoring dogfight missile. Raised to
    # 70, matching the maintained US Naval Aviation value; everything else is
    # the winner's tuning untouched.
    t = read("3606774881", "ammunition/usn_aim-9x.ini")
    t = edit(t, r"^MaxTurnRate=45(\s)", r"MaxTurnRate=70\1", 1, "usn_aim-9x")
    write("ammunition/usn_aim-9x.ini", t,
          "SEST Collection Fixes - base: 3606774881's kinematic rewrite. One delta:\n"
          "MaxTurnRate 45 -> 70 deg/s (the other four authors wrote 70/80/150/180;\n"
          "45 was the outlier on a thrust-vectoring HOBS missile).")
    built.append("usn_aim-9x")

    # usn_gbu-39 [audit: usn_gbu-39 cohort]. USNA's winning SDB keeps the
    # correct glide kinematics but carries CircularErrorRadius=15 m - an order
    # of magnitude off the F-22 author's 1.5 m for a weapon whose entire point
    # is precision - plus the weaker warhead block. Audit call: winner's
    # kinematics + loser's CEP/Power/ImpactSize/TargetMemory.
    t = read("3737267013", "ammunition/usn_gbu-39.ini")
    t = edit(t, r"^Power=12$", "Power=27", 1, "usn_gbu-39")
    t = edit(t, r"^ImpactSize=Medium(\s)", r"ImpactSize=Large\1", 1, "usn_gbu-39")
    t = edit(t, r"^CircularErrorRadius=15(\s)", r"CircularErrorRadius=1.5\1", 1, "usn_gbu-39")
    if "TargetMemory" in t:
        sys.exit("usn_gbu-39: donor now defines TargetMemory - rebase")
    t = edit(t, r"^(CircularErrorRadius=1\.5.*)$", "\\1\n#Homing\nTargetMemory=True",
             1, "usn_gbu-39")
    write("ammunition/usn_gbu-39.ini", t,
          "SEST Collection Fixes - base: 3737267013's glide kinematics; CEP 15 ->\n"
          "1.5 m, Power 12 -> 27, ImpactSize Medium -> Large, TargetMemory=True\n"
          "taken from the F-22 author's copy (3418252667) per the audit.")
    built.append("usn_gbu-39")

    # usn_gbu-53 [audit: usn_f-35c/usn_gbu-53 cohort - the launch-envelope
    # trap]. The winning StormBreaker's release window is MinLaunchAltitude
    # 9900 / MaxLaunchAltitude 10100 - a 200-foot band that reads like a
    # hand-tuned test value. 34 mission F-35Cs and 24 Block IIIs carry it.
    # Seeker, ReattackMode, 47 nm reach and the 93 kg-appropriate warhead all
    # kept; only the envelope opens to the losers' 500-45000 ft.
    t = read("3607989779", "ammunition/usn_gbu-53.ini")
    t = edit(t, r"^MinLaunchAltitude=9900(\s)", r"MinLaunchAltitude=500\1", 1, "usn_gbu-53")
    t = edit(t, r"^MaxLaunchAltitude=10100(\s)", r"MaxLaunchAltitude=45000\1", 1, "usn_gbu-53")
    write("ammunition/usn_gbu-53.ini", t,
          "SEST Collection Fixes - base: 3607989779's radar-seeking StormBreaker.\n"
          "One fix: the 9900-10100 ft release window (a 200-ft band no aircraft\n"
          "holds) opened to 500-45000 ft. Warhead stays 13/Small/Moderate - the\n"
          "defensible figure for a 93 kg SDB II.")
    built.append("usn_gbu-53")

    # usn_gbu-12d [audit: usn_gbu-12d cohort]. The winner re-roled the GBU-12
    # as an armour-piercing penetrator with a 2000 ft floor, applied to every
    # carrier in the collection (mission Super Hornets included). The three
    # losers agree on the conventional blast-frag Paveway II; USNA's copy is
    # the maintained one. Its Mass=363 is a GBU-16 figure - the audit endorses
    # the winner's 275 kg for a 500 lb Paveway II, so that one value is kept.
    t = read("3737267013", "ammunition/usn_gbu-12d.ini")
    t = edit(t, r"^Mass=363(\s)", r"Mass=275\1", 1, "usn_gbu-12d")
    write("ammunition/usn_gbu-12d.ini", t,
          "SEST Collection Fixes - base: 3737267013's conventional Paveway II\n"
          "(blast-frag Power 32, 500 ft floor, vanilla 10 nm seeker convention).\n"
          "One delta: Mass 363 -> 275 kg, the accurate 500 lb figure.")
    built.append("usn_gbu-12d")

    # usn_gbu-24 [audit: usn_gbu-24 cohort]. The winning copy is a 363 kg
    # GBU-27 substituted under the GBU-24's id; the only consumer anywhere is
    # the vanilla A-6E. Vanilla body verbatim: guaranteed assets, and exactly
    # what that consumer was authored against.
    t = read("_vanilla/original", "ammunition/usn_gbu-24.ini")
    if "Mass=1050" not in t:
        sys.exit("usn_gbu-24: vanilla export changed - re-verify")
    write("ammunition/usn_gbu-24.ini", t,
          "SEST Collection Fixes - the vanilla GBU-24 Paveway III, verbatim. The\n"
          "prior winner shipped a 363 kg GBU-27 under this id; the only consumer\n"
          "(vanilla A-6E) expects this file.")
    built.append("usn_gbu-24")

    # usa_agm-114k [audit: usa_agm-114k cohort]. The French Helicopter
    # Package's winning Hellfire has the better kinematics (13 deg/s, 5.94 nm,
    # Power 21) but a 2000 ft launch ceiling - one tenth of the mission
    # AC-130J's cruise altitude, gating its only precision weapon. Ceiling
    # raised to 20000 ft; the AC-130 pack's supply cost restored.
    t = read("3567228449", "ammunition/usa_agm-114k.ini")
    t = edit(t, r"^MaxLaunchAltitude=2000(\s)", r"MaxLaunchAltitude=20000\1", 1, "usa_agm-114k")
    if "AmmoPoints" in t:
        sys.exit("usa_agm-114k: donor now defines AmmoPoints - rebase")
    t = edit(t, r"^(Mass=45\.7.*)$",
             "\\1\nAmmoPoints=65                          // For Supply System. "
             'Defines "price" of ammunition based on mass, volume, complexity and availability',
             1, "usa_agm-114k")
    write("ammunition/usa_agm-114k.ini", t,
          "SEST Collection Fixes - base: 3567228449's agile Hellfire (kept for the\n"
          "whole helicopter fleet). Two deltas: MaxLaunchAltitude 2000 -> 20000 ft\n"
          "so the AC-130J can fire from orbit altitude, and the AC-130 pack's\n"
          "AmmoPoints=65 supply cost restored.")
    built.append("usa_agm-114k")

    # usn_cal_30mm [audit: usn_cal_30mm cohort]. Euromod's winning definition
    # is a stripped file: no Mass/AmmoPoints, no GravityFactor, no proximity
    # fuze, no intercept probability, no [Models] block - all authored by the
    # AC-130 pack and silently dropped by the whole-file override. Composed:
    # Euromod's ballistics (1109 m/s, 4000 m, CEP 12) + the AC-130 pack's
    # missing keys and shell mesh. Live on the gunship's gun and the
    # Zumwalt's 30mm mount.
    euro = read("3629144864", "ammunition/usn_cal_30mm.ini")
    ac130 = read("3559495372", "ammunition/usn_cal_30mm.ini")
    for needle, where in (("MuzzleVelocity=1109", euro), ("CircularErrorProbable=12", euro),
                          ("FuzeProximityDistance=25", ac130), ("KillProbability=0.0002", ac130),
                          ("ResourcesRoot=shell_small", ac130), ("GravityFactor=4", ac130)):
        if needle not in where:
            sys.exit(f"usn_cal_30mm: donor lost {needle!r} - rebase this merge")
    write("ammunition/usn_cal_30mm.ini", COMPOSED_CAL_30MM,
          "SEST Collection Fixes - merge of both authors: Euromod's ballistics\n"
          "(1109 m/s, 4000 m, CEP 12) + the AC-130 pack's Mass/AmmoPoints,\n"
          "GravityFactor, 25 m proximity fuze, intercept KillProbability and\n"
          "shell-mesh [Models] block that the override was silently dropping.")
    built.append("usn_cal_30mm")

    # usn_rim-162 [audit: usn_rim-116/162 cohort]. Both shippers carry the
    # dead legacy ECCM pair (CounterMeasuresRejection - zero occurrences in
    # vanilla 0.8.2); only Mogami's losing copy adds the live keys. The
    # mission's entire air-defence line fires ESSM against dedicated PLA
    # jamming aircraft, so AntiJammerBonus is not cosmetic.
    t = read("3461044389", "ammunition/usn_rim-162.ini")
    if "AntiCountermeasuresBonus" in t:
        sys.exit("usn_rim-162: donor now defines AntiCountermeasuresBonus - rebase")
    t = edit(t, r"^(NoiseRejection=60.*)$",
             "\\1\n#ECCM\n"
             "AntiCountermeasuresBonus=0.4          // This value substracted from "
             "probability of spoofing by countermeasures (0...1)\n"
             "AntiJammerBonus=0.2                   // This value substracted from "
             "probability of being jammed  (0...1)",
             1, "usn_rim-162")
    write("ammunition/usn_rim-162.ini", t,
          "SEST Collection Fixes - base: 3461044389's ESSM. One addition, from the\n"
          "Mogami mod's copy: AntiCountermeasuresBonus=0.4 / AntiJammerBonus=0.2 -\n"
          "the only live-schema ECCM values any mod defines for RIM-162.")
    built.append("usn_rim-162")

    # plaaf_kd-88 [audit: plaaf_kd-88 cohort]. After the load-order move the
    # CV-18 mod's KD-88 wins: LandAttackCapability=All, sea-skimming terminal,
    # real KD-88 mesh - everything the audit wanted except the Fujian mod's
    # 108 nm range figure. This override is that merge, pinned above future
    # reorders.
    t = read("3663564190", "ammunition/plaaf_kd-88.ini")
    if "LandAttackCapability" not in t:
        sys.exit("plaaf_kd-88: donor lost LandAttackCapability - rebase")
    t = edit(t, r"^MaxLaunchRange=97(\s)", r"MaxLaunchRange=108\1", 1, "plaaf_kd-88")
    write("ammunition/plaaf_kd-88.ini", t,
          "SEST Collection Fixes - base: 3663564190's KD-88 (land attack, 200 ft\n"
          "sea-skimming, real mesh, supply cost). One delta: MaxLaunchRange 97 ->\n"
          "108 nm, the higher of the two carrier mods' figures per the audit.")
    built.append("plaaf_kd-88")

    # plaaf_akf-98a [audit: plaaf_akf-98a cohort]. The winning copy sets
    # GuidanceType=4 (anti-radiation) on a stat block written for an active
    # seeker: SeekerActiveRange=50, Ku-band, 35 kW, and a Secondary PASSIVE
    # guidance key whose own comment says it is for active/semi-active
    # seekers. =3 makes the file coherent and the 320 nm ASuW round able to
    # engage non-emitting targets.
    t = read("3663564190", "ammunition/plaaf_akf-98a.ini")
    t = edit(t, r"^GuidanceType=4$", "GuidanceType=3", 1, "plaaf_akf-98a")
    write("ammunition/plaaf_akf-98a.ini", t,
          "SEST Collection Fixes - base: 3663564190's AKF-98A. One delta:\n"
          "GuidanceType 4 -> 3 (active radar). The file's own seeker block\n"
          "(SeekerActiveRange=50, Ku-band 35 kW, SecondaryPassiveRadarGuidanceType)\n"
          "is written for an active seeker; as an ARM it could only ever engage\n"
          "emitting targets.")
    built.append("plaaf_akf-98a")

    # usn_rgm_184a [NSM investigation, secondary finding]. The RAN's NSM carries
    # MinAttackAltitude=55 - "minimum altitude of a TARGET, in feet. Outside
    # Min/Max altitude missile deviation is greatly increaced". Its targets are
    # ships, at ~0 ft, so every shot this round ever takes is outside its own
    # band. This is NOT why the Anzacs held fire (that was the missing
    # datalink provider, fixed in integration/ran-fleet/build_fleet.py) - the
    # key degrades accuracy, it does not veto launch, confirmed against the 74
    # vanilla files that carry it. But no ship-launched anti-ship round should
    # have it at all: all 74 vanilla carriers are AAW missiles, and none of the
    # three comparison NSMs (Euromod's knm_nsm_1a, the Type 23's rn_nsm,
    # vanilla's usn_rgm-84d Harpoon) declares an attack-altitude floor.
    # Deliberately NOT touched: TerminalApproachDist=25 against a 20 nm seeker.
    # It looks wrong, but it is Red Storm Arsenal's house style across its whole
    # arsenal (plan_yj18 19.5 vs 14, wp_ss_n_19a 30 vs 14) and vanilla ships the
    # same shape on the Charlie-I's SS-N-7, so it is proven not to break launch
    # or flight - and TargetMemory=True carries the round through the gap.
    t = read("3413868677", "ammunition/usn_rgm_184a.ini")
    t = edit(t, r"^MinAttackAltitude=55[^\n]*\n", "", 1, "usn_rgm_184a")
    write("ammunition/usn_rgm_184a.ini", t,
          "SEST Collection Fixes - base: 3413868677's NSM (RGM-184A), the round the\n"
          "RAN Anzacs and Hobarts fire. One delta: MinAttackAltitude=55 removed. It\n"
          "put every sea-level target outside the round's own engagement band, where\n"
          "the engine 'greatly increases' missile deviation; no vanilla anti-ship\n"
          "round declares the key and no other NSM in the collection does either.")
    built.append("usn_rgm_184a")

    # -------------------------------------------------------------- vessels
    # usn_cvn_nimitz_variants [audit: usn_cvn_nimitz_variants cohort]. Flight
    # Deck Ops' 2-variant file was discarding Nimitz Expanded's other eight
    # carriers (CVN-70..77, each with hull numbers and period air wings).
    # Shipping the 10-variant file here composes the two mods instead of
    # reordering 20 slots: FDO keeps the hull and all deck-ops animation.
    # One fix: Variant3's 'sn_s-3a' dangling id -> usn_s-3a, so Vinson's
    # Vikings actually spawn.
    t = read("3432592449", "vessels/usn_cvn_nimitz_variants.ini")
    if "NumberOfVariants=10" not in t:
        sys.exit("usn_cvn_nimitz_variants: donor no longer 10 variants - rebase")
    t = edit(t, r"^sn_s-3a=Squadron8,10$", "usn_s-3a=Squadron8,10", 1, "usn_cvn_nimitz_variants")
    write("vessels/usn_cvn_nimitz_variants.ini", t,
          "SEST Collection Fixes - base: 3432592449's 10-variant table (CVN-68..77\n"
          "with per-hull numbers, emblems and period air wings), which Flight Deck\n"
          "Ops' 2-variant file was overriding away. One delta: Variant3's dangling\n"
          "'sn_s-3a' corrected to usn_s-3a. The FDO hull and animations still win.")
    built.append("usn_cvn_nimitz_variants")

    # ------------------------------------------------------------- aircraft
    # usn_mh-60r [audit: usn_mh-60r cohorts]. The winning U.S. Navy 2027 unit
    # file's AntiShip fit seats its Penguin on '|MK46' - a position group the
    # file does not define (only MK54/MK54L/Sonobuoys* exist), left over from
    # the torpedo donor. Station10's bare form is the file's own idiom and
    # Station9 already carries the Penguin hardpoint coordinates.
    t = read("3606774881", "aircraft/usn_mh-60r.ini")
    if re.search(r"^MK46Positions=", t, re.M):
        sys.exit("usn_mh-60r: donor now defines MK46Positions - drop this fix")
    t = edit(t, r"^Station9=knm_penguin_mk2\|MK46$", "Station9=knm_penguin_mk2",
             1, "usn_mh-60r")
    write("aircraft/usn_mh-60r.ini", t,
          "SEST Collection Fixes - base: 3606774881's MH-60R (the 2026-correct\n"
          "Mk54/SSQ-53H fit, unchanged). One delta: the AntiShip Penguin's dangling\n"
          "'|MK46' seat reference removed - no MK46Positions group exists in the\n"
          "file; the round now uses Station9's own Penguin hardpoint coordinates.")
    built.append("usn_mh-60r")

    added = build_missing_sensors()
    named = build_missing_loadout_names()

    (OUT / "_info.ini").write_text(INFO_INI, encoding="utf-8")
    print(f"built {OUT.relative_to(ROOT)}: {len(built)} overrides - {', '.join(built)}")
    print(f"  + {len(added)} sensor definitions no mod supplied: {', '.join(added)}")
    print(f"  + {len(named)} loadout display names: {', '.join(named)}")


# Sensor types that units mount but NO mod defines, so the sensor is inert.
# systems/ merges section-by-section, so supplying the missing definition adds
# capability without overriding anybody. Each is CLONED from the closest
# same-class, same-era definition rather than invented - donor named per entry.
#
#   new type          donor                       who mounts it (mission units)
MISSING_SENSORS = {
    "Side_Globe": ("_vanilla/original", "Start_ECM",
                   "Soviet shipboard defensive jammer. Donor is vanilla's own "
                   "Soviet ship ECM (Sovremenny, Udaloy, Krivak). Mounted by "
                   "ru_cv_varyag and wp_rkr_kirov_improved, both fielded."),
    "Rum_Tub": ("_vanilla/original", "Start_ESM",
                "Soviet shipboard ESM array, the receive half of the same suite "
                "as Side Globe. Mounted by wp_rkr_kirov_improved."),
    "J/OPS-20": ("3629144864", "eu_nav_radar",
                 "JMSDF navigation radar. Donor is Euromod's modern naval "
                 "navigation radar. Mounted by jmsdf_ddg_maya, fielded."),
    "pla_pod_kg-800": ("_vanilla/original", "Azaliya_OECM",
                       "PLAN escort jamming pod on the J-15D, the type's whole "
                       "reason to exist. Donor is vanilla's Soviet EW-aircraft "
                       "jammer at 5 kW - deliberately a fraction of the NGJ's "
                       "75 kW in SEST_Growler_NGJ_MALICE, so red gets a working "
                       "jammer rather than a Growler. 8 airframes fielded."),
    "4th_Gen_FLIR": ("_vanilla/original", "AdvancedOptics",
                     "EO/IR turret on the Z-9D. Donor is vanilla's advanced "
                     "optical sight."),
}


def build_missing_sensors():
    """Supply definitions for sensor types every mod references and none defines."""
    out, blocks = [], []
    for name, (donor_mod, donor_sec, why) in MISSING_SENSORS.items():
        # If anyone starts defining it, ours would shadow theirs - stop instead.
        for f in (ROOT / "mods-source").rglob("systems/sensors.ini"):
            if re.search(rf"^\[{re.escape(name)}\]", read_file(f), re.M):
                sys.exit(f"{name} is now defined by {f.parts[-3]} - drop it from "
                         "MISSING_SENSORS rather than shadowing upstream")
        src = read_file(MODS / donor_mod / "systems" / "sensors.ini")
        m = re.search(rf"^\[{re.escape(donor_sec)}\]\n(.*?)(?=^\[|\Z)", src, re.S | re.M)
        if not m:
            sys.exit(f"donor sensor [{donor_sec}] missing from {donor_mod} - rebase")
        body = "\n".join(l for l in m.group(1).strip().splitlines()
                         if not l.strip().startswith("#Users:"))
        blocks.append(f"# {name}: {why}\n"
                      f"# Cloned from [{donor_sec}] in {donor_mod}.\n"
                      f"[{name}]\n{body}\n")
        out.append(name)
    if blocks:
        (OUT / "systems").mkdir(parents=True, exist_ok=True)
        (OUT / "systems" / "sensors.ini").write_text(
            "# SEST Collection Fixes - sensor types that units mount but no mod\n"
            "# defines, so the sensor does nothing at all. systems/ files merge\n"
            "# section-by-section, so these ADD the missing definitions without\n"
            "# overriding anything. Every one is cloned from the closest\n"
            "# same-class, same-era definition; none is invented.\n\n"
            + "\n".join(blocks), encoding="utf-8")
    return out


# Loadout keys offered in a picker with no display name anywhere, so the UI
# shows the raw key. language_*/ merges key-by-key, so these are additive.
MISSING_LOADOUT_NAMES = {
    "Strike158": "Strike (AGM-158 JASSM)",
    "Strike86": "Strike (AGM-86 ALCM)",
    "StrikeNuke": "Strike (nuclear)",
    "CAS1": "Close Air Support (alt)",
    "StrikePrecision1": "Strike Precision (alt)",
    "StrikeLowAltitude": "Strike Low Altitude",
    # upstream typo: vanilla's key is AirToAirLongRange with a capital R, so the
    # Su-35's lowercase spelling matches nothing and shows raw in the picker
    "AirToAirLongrange": "Air To Air Long Range",
}


def build_missing_loadout_names():
    src = read_file(MODS / "_vanilla/original" / "language_en" / "loadout_names.ini")
    clash = [k for k in MISSING_LOADOUT_NAMES if re.search(rf"^{re.escape(k)}=", src, re.M)]
    if clash:
        sys.exit(f"vanilla now names these loadouts: {clash} - drop them here")
    body = ("# SEST Collection Fixes - display names for loadout keys that no mod\n"
            "# names, which the picker would otherwise show as the raw key.\n"
            "# language_*/ merges key-by-key, so nothing upstream is replaced.\n"
            "[LoadoutNames]\n"
            + "".join(f"{k}={v}\n" for k, v in MISSING_LOADOUT_NAMES.items()))
    (OUT / "language_en").mkdir(parents=True, exist_ok=True)
    (OUT / "language_en" / "loadout_names.ini").write_text(body, encoding="utf-8")
    return list(MISSING_LOADOUT_NAMES)


def read_file(p):
    return Path(p).read_text(encoding="utf-8-sig", errors="replace")


COMPOSED_CAL_30MM = """\
[General]
#30mm HE / HEI
Type=Projectile            // can be Projectile, Missile, Torpedo
TargetType=AAW             // can be AAW, ASuW, ASW
SecondaryTargetType=ASuW

Mass=4.5                               // in kg. Used for aircraft
AmmoPoints=4.5                         // For Supply System. Defines "price" of ammunition based on mass, volume, complexity and availability

DecalClass=GunImpacts      // referenced in effects/decals.ini

[Physics]
MuzzleVelocity=1109         // meter per second
MaxRange=4000              // in m
GravityFactor=4
CircularErrorProbable=12   // radius in meters at max range for shells to impact

[---------- Warhead Data ----------]
[WarheadData]
Power=0.85
ImpactSize=Tiny           // Impact size, can be small, medium, large, verylarge
Penetration=Minor         // can be minor, moderate, heavy, always
FuzeProximityDistance=25              // In meters
KillProbability=0.0002                // Chance to intercept missile. Relevant for Guns, irrelevant for CIWS

[---------- Mesh definitions----------]
[Models]
ResourcesFolder=weapons/shells/
ResourcesRoot=shell_small
ResourcesMesh=shell_small
ResourcesMaterial=shell_mat

[---------- Effects ----------]
[Particles]
TrailEffect=
HitShipExplosion=effects/Particle Emitters/impact_small_shell_multi
HitAirExplosionClass=SmallFlakExplosions
HitDefaultExplosion=effects/Particle Emitters/impact_small_shell
HitWaterSplashClass=TinyWaterSplashes
"""


if __name__ == "__main__":
    main()
