[Object0]
Name=Grass
# LOD 0
NameLod0=GrassLod0
ShadowCastingModeLod0=Off
ReceiveShadowsLod0=True

# MeshPrefabPathLod0=Assets/Resources/Autogen/Resources/Staging/Trees/Corner.DAE
# MeshNameLod0=Corner_Grass
# MaterialPathLod0=Assets/Resources/scenery/autogen/ProceduralMaterials/Vegetation/Grass/autogen_mesh_grass_taiga_[SEASON].mat

# MeshPrefabPathLod0=Assets/Resources/Autogen/Resources/Staging/Grass/LPW_Grass_A1_50cm_01.fbx
# MeshNameLod0=LPW_Grass_A1_50cm_01
# MaterialPathLod0=Assets/Resources/scenery/autogen/ProceduralMaterials/Vegetation/Grass/autogen_mesh_grass_taiga_[SEASON].mat

MeshPrefabPathLod0=Assets/Resources/terrain/grass_meshes.FBX
MeshNameLod0=grass_small
MaterialPathLod0=Assets/Resources/scenery/autogen/ProceduralMaterials/Vegetation/Grass/autogen_billboard_grass_taiga_[SEASON].mat

## LOD 1
## NameLod1=GrassLod1 # no name for LOD 1 Autogen will skip it
#ShadowCastingModeLod1=Off
#ReceiveShadowsLod1=True
#MeshPrefabPathLod1=Assets/Resources/terrain/grass_3d.FBX
#MeshNameLod1=grass_small_3d_lod1
#MaterialPathLod1=Assets/Resources/scenery/autogen/ProceduralMaterials/Vegetation/Grass/autogen_mesh_grass_taiga_[SEASON].mat

[Object1]
Name=Flowers
# LOD 0
NameLod0=FlowerLod0
ShadowCastingModeLod0=Off
ReceiveShadowsLod0=True
MeshPrefabPathLod0=Assets/Resources/terrain/bush_meshes.FBX
MeshNameLod0=bush_small	//bush_small_quad
MaterialPathLod0=Assets/Resources/scenery/autogen/ProceduralMaterials/Vegetation/Grass/autogen_billboard_flower_taiga_[SEASON].mat

[Object2]
Name=Trees
# Billboard Trees LOD0
NameLod0=Trees
ReceiveShadowsLod0=False
MeshPrefabPathLod0=Assets/Resources/Autogen/Resources/Staging/Trees/tree_quad.FBX
MeshNameLod0=tree_quad
MaterialPathLod0=Assets/Resources/scenery/autogen/ProceduralMaterials/Vegetation/Trees/Taiga/autogen_billboard_trees_taiga_lod0_[SEASON].mat

# Billboard Trees
NameLod1=Trees
ReceiveShadowsLod1=True
MeshPrefabPathLod1=Assets/Resources/Autogen/Resources/Staging/Trees/tree_quad.FBX
MeshNameLod1=tree_quad
MaterialPathLod1=Assets/Resources/scenery/autogen/ProceduralMaterials/Vegetation/Trees/Taiga/autogen_billboard_trees_taiga_[SEASON].mat

[Object3]
Name=Boulders
NameLod0=Boulders
ShadowCastingModeLod0=On
ReceiveShadowsLod0=True
MeshPrefabPathLod0=Assets/Resources/Autogen/Resources/Staging/Coral/CoralRocks.FBX
MeshNameLod0=CoralRock3
MaterialPathLod0=Assets/Resources/scenery/autogen/ProceduralMaterials/Vegetation/Underwater/CoralRocks.mat

[Object4]
Name=Seaweeds
NameLod0=Seaweeds
# ShadowCastingModeLod0=Off
MeshPrefabPathLod0=Assets/Resources/Autogen/Resources/Staging/Trees/tree_quad.FBX
MeshNameLod0=tree_quad
MaterialPathLod0=Assets/Resources/scenery/autogen/ProceduralMaterials/Vegetation/Underwater/autogen_billboard_underwater_kelp.mat

[Object5]
Name=Seaweeds OceanDepth
# Seaweeds OceanDepth Pass
NameLod0=SeaweedOceanDepth
ShadowCastingModeLod0=Off
ReceiveShadowsLod0=False
MeshPrefabPathLod0=Assets/Resources/Autogen/Resources/Staging/Trees/tree_quad.FBX
MeshNameLod0=tree_quad
MaterialPathLod0=Assets/Resources/scenery/autogen/ProceduralMaterials/Vegetation/Underwater/autogen_billboard_underwater_ocean_depth.mat

[Object6]
Name=Corals
NameLod0=Corals
ReceiveShadowsLod0=True
MeshPrefabPathLod0=Assets/Resources/Autogen/Resources/Staging/Coral/CoralRocks.FBX
MeshNameLod0=CoralRock2
MaterialPathLod0=Assets/Resources/scenery/autogen/ProceduralMaterials/Vegetation/Underwater/CoralRocks.mat

[Object7]
Name=Corals OceanDepth
# Corals OceanDepth Pass
NameLod0=CoralOceanDepth
ShadowCastingModeLod0=Off
ReceiveShadowsLod0=False
MeshPrefabPathLod0=Assets/Resources/Autogen/Resources/Staging/Coral/CoralRocks.FBX
MeshNameLod0=CoralRock2
MaterialPathLod0=Assets/Resources/scenery/autogen/ProceduralMaterials/Vegetation/Underwater/autogen_mesh_underwater_ocean_depth.mat

[Meta]
TotalUniqueObjects=8
MaxLodLevel=1
MeshNameLodPrefix=_lod_
ShadowCastingMode=On
ReceiveShadows=False