[Language_cn]
Name=伊斯坎德尔
Description=由misaka制作

[Language_en]
Name=Iskander
Description=by misaka

[Compatibility]
;ApproximateVersion is the second check and will override all statements below. This checks MAJOR and MINOR match but will accept higher PATCH.
;Would recommend this as a default case for starters.
GreaterThanEqualToVersion=0.7.0