[General]
SerialnumberReferences=Modex
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfSquadrons=17

[Default]
ResourcesSerialnumberFolder=aircraft/usmc_ch-46e/hmmt-164/modex/
SerialNumberPrefix=
SerialnumberTextures=1.png,2.png,3.png,4.png,5.png,6.png,7.png,8.png,13.png,14.png,16.png,17.png
ResourcesLiveryFolder=aircraft/usmc_ch-46e/hmmt-164/
LiveryTexture=hmmt-164_tps.png
Nation=US

[Squadron1] HMM-161 (YR) 
ResourcesSerialnumberFolder=aircraft/usmc_ch-46e/hmm-161/modex/
SerialNumberPrefix=
SerialnumberTextures=1.png,2.png,3.png,4.png,5.png,6.png,7.png,9.png,10.png,12.png,14.png,16.png
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/usmc_ch-46e/hmm-161/
LiveryTexture=hmm-161_tps.png
Nation=US

[Squadron2] HMM-162 (YS) Bataan
ResourcesSerialnumberFolder=aircraft/usmc_ch-46e/hmm-162/modex/
SerialNumberPrefix=
SerialnumberTextures=1.png,2.png,3.png,4.png,5.png,6.png,7.png,9.png,10.png,12.png,14.png,16.png
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/usmc_ch-46e/hmm-162/
LiveryTexture=hmm-162_tps.png
# nations are referenced in the layout.ini file:
Nation=US

[Squadron3] HMM-163 (YP) 
ResourcesSerialnumberFolder=aircraft/usmc_ch-46e/hmm-163/modex/
SerialNumberPrefix=
SerialnumberTextures=1.png,2.png,3.png,4.png,5.png,6.png,7.png,9.png,10.png,12.png,14.png,16.png
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/usmc_ch-46e/hmm-163/
LiveryTexture=hmm-163_tps.png
# nations are referenced in the layout.ini file:
Nation=US

[Squadron4] HMM-165 (YW) 
ResourcesSerialnumberFolder=aircraft/usmc_ch-46e/hmm-165/modex/
SerialNumberPrefix=
SerialnumberTextures=1.png,2.png,3.png,4.png,5.png,6.png,7.png,9.png,10.png,12.png,14.png,16.png
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/usmc_ch-46e/hmm-165/
LiveryTexture=hmm-165_tps.png
# nations are referenced in the layout.ini file:
Nation=US

[Squadron5] HMM-166 (YX) Essex
ResourcesSerialnumberFolder=aircraft/usmc_ch-46e/hmm-166/modex/
SerialNumberPrefix=
SerialnumberTextures=1.png,2.png,3.png,4.png,5.png,6.png,7.png,9.png,10.png,12.png,14.png,16.png
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/usmc_ch-46e/hmm-166/
LiveryTexture=hmm-166_tps.png
# nations are referenced in the layout.ini file:
Nation=US

[Squadron6] HMM-261 (EM) Iwo Jima
ResourcesSerialnumberFolder=aircraft/usmc_ch-46e/hmm-261/modex/
SerialNumberPrefix=
SerialnumberTextures=1.png,2.png,3.png,4.png,5.png,6.png,7.png,9.png,10.png,12.png,14.png,16.png
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/usmc_ch-46e/hmm-261/
LiveryTexture=hmm-261_tps.png
# nations are referenced in the layout.ini file:
Nation=US

[Squadron7] HMM-262 (ET) 
ResourcesSerialnumberFolder=aircraft/usmc_ch-46e/hmm-262/modex/
SerialNumberPrefix=
SerialnumberTextures=01.png,02.png,03.png,04.png,05.png,06.png,07.png,08.png,09.png,10.png,11.png,12.png
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/usmc_ch-46e/hmm-262/
LiveryTexture=hmm-262_tps.png
Nation=US

[Squadron8] HMM-263 (EG) Wasp
ResourcesSerialnumberFolder=aircraft/usmc_ch-46e/hmm-263/modex/
SerialNumberPrefix=
SerialnumberTextures=1.png,2.png,3.png,4.png,5.png,6.png,7.png,8.png,9.png,10.png,11.png,12.png
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/usmc_ch-46e/hmm-263/
LiveryTexture=hmm-263_tps.png
Nation=US

[Squadron9] HMM-264 (EH) 
ResourcesSerialnumberFolder=aircraft/usmc_ch-46e/hmm-264/modex/
SerialNumberPrefix=
SerialnumberTextures=1.png,2.png,3.png,4.png,5.png,6.png,7.png,8.png,13.png,14.png,16.png,17.png
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/usmc_ch-46e/hmm-264/
LiveryTexture=hmm-264_tps.png
Nation=US

[Squadron10] HMM-265 (EP) Bonhomme Richard
ResourcesSerialnumberFolder=aircraft/usmc_ch-46e/hmm-265/modex/
SerialNumberPrefix=
SerialnumberTextures=1.png,2.png,3.png,4.png,5.png,6.png,8.png,10.png,12.png,13.png,17.png,18.png
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/usmc_ch-46e/hmm-265/
LiveryTexture=hmm-265_tps.png
Nation=US

[Squadron11] HMM-266 (ES) Kearsarge
ResourcesSerialnumberFolder=aircraft/usmc_ch-46e/hmm-266/modex/
SerialNumberPrefix=
SerialnumberTextures=1.png,2.png,3.png,4.png,5.png,6.png,8.png,10.png,12.png,13.png,17.png,18.png
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/usmc_ch-46e/hmm-266/
LiveryTexture=hmm-266_tps.png
Nation=US

[Squadron12] HMM-268 (YQ) 
ResourcesSerialnumberFolder=aircraft/usmc_ch-46e/hmm-268/modex/
SerialNumberPrefix=
SerialnumberTextures=1.png,2.png,3.png,4.png,5.png,6.png,7.png,8.png,13.png,14.png,16.png,17.png
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/usmc_ch-46e/hmm-268/
LiveryTexture=hmm-268_tps.png
Nation=US

[Squadron13] HMM-364 (PF) Boxer
ResourcesSerialnumberFolder=aircraft/usmc_ch-46e/hmm-364/modex/
SerialNumberPrefix=
SerialnumberTextures=1.png,2.png,3.png,4.png,5.png,6.png,7.png,8.png,13.png,14.png,16.png,17.png
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/usmc_ch-46e/hmm-364/
LiveryTexture=hmm-364_tps.png
Nation=US

[Squadron14] HMM-365 (YM) 
ResourcesSerialnumberFolder=aircraft/usmc_ch-46e/hmm-365/modex/
SerialNumberPrefix=
SerialnumberTextures=1.png,2.png,3.png,4.png,5.png,6.png,8.png,10.png,12.png,13.png,17.png,18.png
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/usmc_ch-46e/hmm-365/
LiveryTexture=hmm-365_tps.png
Nation=US

[Squadron15] HMM-561 (PH) 
ResourcesSerialnumberFolder=aircraft/usmc_ch-46e/hmm-561/modex/
SerialNumberPrefix=
SerialnumberTextures=1.png,2.png,3.png,4.png,5.png,6.png,7.png,9.png,10.png,12.png,14.png,16.png
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/usmc_ch-46e/hmm-561/
LiveryTexture=hmm-561_tps.png
Nation=US

[Squadron16] HMM-764 (ML) USMC/R
ResourcesSerialnumberFolder=aircraft/usmc_ch-46e/hmm-764/modex/
SerialNumberPrefix=
SerialnumberTextures=1.png,2.png,3.png,4.png,5.png,6.png,7.png,8.png,9.png,10.png,11.png,12.png
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/usmc_ch-46e/hmm-764/
LiveryTexture=hmm-764_tps.png
Nation=US

[Squadron17] HMM-774 (MQ) USMC/R
ResourcesSerialnumberFolder=aircraft/usmc_ch-46e/hmm-774/modex/
SerialNumberPrefix=
SerialnumberTextures=1.png,2.png,3.png,4.png,5.png,6.png,8.png,10.png,12.png,13.png,17.png,18.png
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/usmc_ch-46e/hmm-774/
LiveryTexture=hmm-774_tps.png
Nation=US