[General]
SerialnumberReferences=Modex
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfSquadrons=2

[Default]
ResourcesSerialnumberFolder=aircraft/usn_p-3c/vq-1/modex/
SerialnumberTextures=33.png
ResourcesEmblemFolder=aircraft/materials/emblem/
ResourcesLiveryFolder=aircraft/usn_p-3c/vq-1/
LiveryTexture=vq-1.png
SpecularTexture=usn_ep-3e_spec.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
# nations are referenced in the layout.ini file:
Nation=US

[Squadron1]  #VQ-1 World Watcher
ResourcesSerialnumberFolder=aircraft/usn_p-3c/vq-1/modex/
SerialnumberTextures=33.png
ResourcesEmblemFolder=aircraft/materials/emblem/
ResourcesLiveryFolder=aircraft/usn_p-3c/vq-1/
LiveryTexture=vq-1.png
SpecularTexture=usn_ep-3e_spec.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
Nation=US

[Squadron2]  #VQ-2
ResourcesSerialnumberFolder=aircraft/usn_p-3c/vq-2/modex/
SerialnumberTextures=21.png
ResourcesLiveryFolder=aircraft/usn_p-3c/vq-2/
LiveryTexture=vq-2.png
SpecularTexture=usn_ep-3e_spec.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
Nation=US
