[General]
SerialnumberReferences=Modex
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfSquadrons=6

[Default]
Nation=US

[Squadron1] HC-3 Pack Rats SA
ResourcesSerialnumberFolder=aircraft/usn_ch-46d/hc-3/modex/
SerialNumberPrefix=
SerialnumberTextures=46.png,60,png,62.png,63.png,64.png,65.png,72.png,75.png
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/usn_ch-46d/hc-3/
LiveryTexture=blu_hc-3.png
# nations are referenced in the layout.ini file:
Nation=US

[Squadron2] HC-5 Providers RB
ResourcesSerialnumberFolder=aircraft/usn_ch-46d/hc-5/modex/
SerialNumberPrefix=
SerialnumberTextures=46.png,60,png,62.png,63.png,64.png,65.png,72.png,75.png
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/usn_ch-46d/hc-5/
LiveryTexture=blu_hc-5.png
# nations are referenced in the layout.ini file:
Nation=US

[Squadron3] HC-6 Chargers HW
ResourcesSerialnumberFolder=aircraft/usn_ch-46d/hc-6/modex/
SerialNumberPrefix=
SerialnumberTextures=46.png,60,png,62.png,63.png,64.png,65.png,72.png,75.png
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/usn_ch-46d/hc-6/
LiveryTexture=blu_hc-6.png
# nations are referenced in the layout.ini file:
Nation=US

[Squadron4] HC-8 Dragon Whales BR
ResourcesSerialnumberFolder=aircraft/usn_ch-46d/hc-8/modex/
SerialNumberPrefix=
SerialnumberTextures=46.png,60,png,62.png,63.png,64.png,65.png,72.png,75.png
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/usn_ch-46d/hc-8/
LiveryTexture=blu_hc-8.png
# nations are referenced in the layout.ini file:
Nation=US

[Squadron5] HC-11 Gunbearers VR
ResourcesSerialnumberFolder=aircraft/usn_ch-46/hc-11/modex/
SerialNumberPrefix=
SerialnumberTextures=46,60,62,63,64,65,72,75
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/usn_ch-46d/hc-11/
LiveryTexture=blu_hc-11.png
# nations are referenced in the layout.ini file:
Nation=US

[Squadron6] HC-16 Bull Frogs BF
ResourcesSerialnumberFolder=aircraft/usn_ch-46d/hc-16/modex/
SerialNumberPrefix=
SerialnumberTextures=46.png,60,png,62.png,63.png,64.png,65.png,72.png,75.png
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/usn_ch-46d/hc-16/
LiveryTexture=blu_hc-16.png
# nations are referenced in the layout.ini file:
Nation=US