# ver. 20260816
#
[LoadoutNames]
Default=Default

AB212=AB212 Helicopter
Seaking=SH-3D Helicopter
# Superpuma=AS332B SuperPuma FAMET

CASLongRange=Close Air Support			// Same as CAS but less weapons, more fuel

Amphib=Amphibious landing
Deck2=Aircrafts on deck
noDeck2=Empty deck
Legion=Legionarios

ULQ6=AN/ULQ-6 ECM


