[ ========================================= Air Search ========================================== ]
[MR650]
#MR-650 «Podberezovik-M1»
Kind=Radar
Type=Search            // Classes can be "Search", "Targeting"
HasDataLink=True       // true means the sensor data will be used for the entire task force via data link, false local use only
Role=AirAndSurface               // Role can be "Surface", "Air", "AirAndSurface"
Mode=Illuminate        // Can be "Illuminate", "RadioCommand"
TargetChannels=1       // if applicable number of targets it can track simultaneously
WeaponChannels=1       // if applicable number of weapons (missiles) it can guide simultaneously
RotationDirection=1    // -1 means left, 1 means right
RPM=6                 // revolutions per minute
MinRange=5           // min range in km
MaxRange=600.0         // max range in km
MinAltitude=10        // min altitude in meters, relevant for air, unused for surface
MaxAltitude=60000      // max altitude in meters, relevant for air, unused for surface
RangeResolution=5.0  // defines the minimum range where two targets behind can be recognized as two; in meters
BeamWidth=0.4          // defines the beam width in degrees for BearingResolution >= 2Distsin(BeamWidth/2)
Gain=45.0              // gain in dB on the sensor
Frequency=S-Band       // frequency band
PeakPower=5000.0        // output peak power in kW
ModuleType=BigSensor 

[Top_Plate]
Kind=Radar
Type=Search            // Classes can be "Search", "Targeting"
HasDataLink=True       // true means the sensor data will be used for the entire task force via data link, false local use only
Role=AirAndSurface               // Role can be "Surface", "Air", "AirAndSurface"
Mode=Illuminate        // Can be "Illuminate", "RadioCommand"
TargetChannels=1       // if applicable number of targets it can track simultaneously
WeaponChannels=1       // if applicable number of weapons (missiles) it can guide simultaneously
RotationDirection=1    // -1 means left, 1 means right
RPM=12                 // revolutions per minute
MinRange=2           // min range in km
MaxRange=300.0         // max range in km
MinAltitude=2        // min altitude in meters, relevant for air, unused for surface
MaxAltitude=30000      // max altitude in meters, relevant for air, unused for surface
RangeResolution=5.0  // defines the minimum range where two targets behind can be recognized as two; in meters
BeamWidth=0.4          // defines the beam width in degrees for BearingResolution >= 2Distsin(BeamWidth/2)
Gain=45.0              // gain in dB on the sensor
Frequency=S-Band       // frequency band
PeakPower=3000.0        // output peak power in kW
ModuleType=MediumSensor 

[ ========================================= Fire Control ========================================== ]
[Gravestone]
#*2N6 «Gravestone»     FC for S-300 SAM
Kind=Radar
Type=Targeting         // Classes can be "Search", "Targeting"
HasDataLink=False      // true means the sensor data will be used for the entire task force via data link, false local use only
Role=Air               // Role can be "Surface", "Air", "AirAndSurface"
Mode=Illuminate        // Can be "Illuminate", "RadioCommand"
TargetChannels=24       // if applicable number of targets it can track simultaneously
WeaponChannels=12       // if applicable number of weapons (missiles) it can guide simultaneously
RPM=60                 // revolutions per minute
MinRange=0.2           // min range in km
MaxRange=400.0         // max range in km
MinAltitude=0          // min altitude in meters, relevant for air, unused for surface
MaxAltitude=30000      // max altitude in meters, relevant for air, unused for surface
RangeResolution=50.0  // defines the minimum range where two targets behind can be recognized as two; in meters
BeamWidth=0.3          // defines the beam width in degrees for BearingResolution >= 2*Dist*sin(BeamWidth/2)
Gain=65              // gain in dB on the sensor
Frequency=X-Band      // frequency band
PeakPower=1000.0       // output peak power in kW
ModuleType=BigSensor

[Hot_Shot]
#1RS2-1 «Shlem»   FC for Pantsir-M
#Users: wp_rkr_lider
Kind=Radar
Type=Targeting         // Classes can be "Search", "Targeting"
HasDataLink=True       // true means the sensor data will be used for the entire task force via data link, false local use only
Role=AirAndSurface     // Role can be "Surface", "Air", "AirAndSurface"
Mode=Illuminate        // Can be "Illuminate", "RadioCommand"
TargetChannels=4       // if applicable number of targets it can track simultaneously
WeaponChannels=8       // if applicable number of weapons (missiles) it can guide simultaneously
RPM=0                  // TODO revolutions per minute
MinRange=0.1           // min range in km
MaxRange=28            // max range in km
MinAltitude=0          // min altitude in meters, relevant for air, unused for surface
MaxAltitude=30480      // max altitude in meters, relevant for air, unused for surface
RangeResolution=30.0   // defines the minimum range where two targets behind can be recognized as two; in meters
BeamWidth=0.6          // defines the beam width in degrees for BearingResolution >= 2*Dist*sin(BeamWidth/2)
Gain=45.0              // gain in dB on the sensor
Frequency=X-Band       // frequency band
PeakPower=100.0        // output peak power in kW
ModuleType=SmallSensor