#---------- Air and Air&Surface search radars ----------
[SensorSystem2] #RAN20S
Type=Radar
SystemName=eu_RAN20S
Mount=eu_RAN20S_radar
Collider=coll_RAN20S



RAN20S_base=eu_RAN20S_base
RAN20S_radar=eu_RAN20S_radar


[eu_RAN20S_base]
ResourcesMeshFolder=assets/europack/models/
RootMesh=sensors.obj
Mesh=eu_RAN20S_base
ResourcesMaterialFolder=ships/materials/
Material=usn_parts
Position=0,0.250823 ,0.023749

[eu_RAN20S_radar]
ResourcesMeshFolder=assets/europack/models/
RootMesh=sensors.obj
Mesh=eu_RAN20S_radar
ResourcesMaterialFolder=assets/europack/materials/eu_RAN20S/
Material=eu_RAN20S_mat.ini
Parent=eu_RAN20S_base
Position=0,0.034531 ,0