[Animations]
NumberOfAnimations=14 

Animation1=Flaps_Takeoff
Animation2=Flaps_Takeoff_Retract
Animation3=Flaps_Landing
Animation4=Flaps_Landing_Retract
Animation5=Gear_Extend
Animation6=Gear_Retract
Animation7=Refueling_Extend
Animation8=Refueling_Retract
Animation9=Hose_Extend_Right
Animation10=Hose_Retract_Right
Animation11=Hose_Extend_Left
Animation12=Hose_Retract_Left
Animation13=Hose_Extend_Both
Animation14=Hose_Retract_Both

[Flaps_Takeoff]
NumberOfSequencesToPlay=4
Sequence1=Flap_Down
Sequence1_Model=Inner_Flaps_L
Sequence2=Flap_Down
Sequence2_Model=Inner_Flaps_R
Sequence3=Outer_Flaps_L_Down
Sequence3_Model=Outer_Flaps_L
Sequence4=Outer_Flaps_R_Down
Sequence4_Model=Outer_Flaps_R

[Flaps_Takeoff_Retract]
NumberOfSequencesToPlay=4
Sequence1=Flap_Up
Sequence1_Model=Inner_Flaps_L
Sequence2=Flap_Up
Sequence2_Model=Inner_Flaps_R
Sequence3=Outer_Flaps_L_Up
Sequence3_Model=Outer_Flaps_L
Sequence4=Outer_Flaps_R_Up
Sequence4_Model=Outer_Flaps_R

[Flaps_Landing]
NumberOfSequencesToPlay=4
Sequence1=Flap_Down
Sequence1_Model=Inner_Flaps_L
Sequence2=Flap_Down
Sequence2_Model=Inner_Flaps_R
Sequence3=Outer_Flaps_L_Down
Sequence3_Model=Outer_Flaps_L
Sequence4=Outer_Flaps_R_Down
Sequence4_Model=Outer_Flaps_R

[Flaps_Landing_Retract]
NumberOfSequencesToPlay=4
Sequence1=Flap_Up
Sequence1_Model=Inner_Flaps_L
Sequence2=Flap_Up
Sequence2_Model=Inner_Flaps_R
Sequence3=Outer_Flaps_L_Up
Sequence3_Model=Outer_Flaps_L
Sequence4=Outer_Flaps_R_Up
Sequence4_Model=Outer_Flaps_R

[Gear_Extend]
NumberOfSequencesToPlay=15
Sequence1=Nose_Gear_Down
Sequence1_Model=nose_gear


Sequence4=Nose_Gear_Hatch_Down1
Sequence4_Model=nose_gear_door_L
Sequence5=Nose_Gear_Hatch_Down2
Sequence5_Model=nose_gear_door_L_small
Sequence6=Nose_Gear_Hatch_Down3
Sequence6_Model=nose_gear_door_R
Sequence7=Nose_Gear_Hatch_Down4
Sequence7_Model=nose_gear_door_R_small

Sequence8=Left_Gear_Down
Sequence8_Model=gear_l
Sequence9=Left_Gear_Down2
Sequence9_Model=wheel_l
Sequence10=Left_Door_Down1
Sequence10_Model=mid_door_L_small
Sequence11=Left_Door_Down2
Sequence11_Model=mid_door_L

Sequence12=Right_Gear_Down
Sequence12_Model=gear_r
Sequence13=Right_Gear_Down2
Sequence13_Model=wheel_r
Sequence14=Right_Door_Down1
Sequence14_Model=mid_door_R_small
Sequence15=Right_Door_Down2
Sequence15_Model=mid_door_R

[Gear_Retract]
NumberOfSequencesToPlay=15
Sequence1=Nose_Gear_Up
Sequence1_Model=nose_gear

Sequence4=Nose_Gear_Hatch_Up1
Sequence4_Model=nose_gear_door_L
Sequence5=Nose_Gear_Hatch_Up2
Sequence5_Model=nose_gear_door_L_small
Sequence6=Nose_Gear_Hatch_Up3
Sequence6_Model=nose_gear_door_R
Sequence7=Nose_Gear_Hatch_Up4
Sequence7_Model=nose_gear_door_R_small

Sequence8=Left_Gear_Up
Sequence8_Model=gear_l
Sequence9=Left_Gear_Up2
Sequence9_Model=wheel_l
Sequence10=Left_Door_Up1
Sequence10_Model=mid_door_L_small
Sequence11=Left_Door_Up2
Sequence11_Model=mid_door_L

Sequence12=Right_Gear_Up
Sequence12_Model=gear_r
Sequence13=Right_Gear_Up2
Sequence13_Model=wheel_r
Sequence14=Right_Door_Up1
Sequence14_Model=mid_door_R_small
Sequence15=Right_Door_Up2
Sequence15_Model=mid_door_R

[Refueling_Extend]
NumberOfSequencesToPlay=2
Sequence1=Refueling_Down
Sequence1_Model=pipe
Sequence2=Refueling_Down_2
Sequence2_Model=pipe_2

[Refueling_Retract]
NumberOfSequencesToPlay=2
Sequence1=Refueling_Up
Sequence1_Model=pipe
Sequence2=Refueling_Up_2
Sequence2_Model=pipe_2

[Hose_Extend_Right]
NumberOfSequencesToPlay=4
Sequence1=Hose_Seg1_L_Down
Sequence1_Model=Hose_Seg1_L
Sequence2=Hose_Seg2_L_Down
Sequence2_Model=Hose_Seg2_L
Sequence3=Hose_Seg3_L_Down
Sequence3_Model=Hose_Seg3_L
Sequence4=Hose_Seg4_L_Down
Sequence4_Model=Hose_Seg4_L

[Hose_Retract_Right]
NumberOfSequencesToPlay=4
Sequence1=Hose_Seg1_L_up
Sequence1_Model=Hose_Seg1_L
Sequence2=Hose_Seg2_L_up
Sequence2_Model=Hose_Seg2_L
Sequence3=Hose_Seg3_L_up
Sequence3_Model=Hose_Seg3_L
Sequence4=Hose_Seg4_L_up
Sequence4_Model=Hose_Seg4_L

[Hose_Extend_Left]
NumberOfSequencesToPlay=4
Sequence1=Hose_Seg1_R_Down
Sequence1_Model=Hose_Seg1_R
Sequence2=Hose_Seg2_R_Down
Sequence2_Model=Hose_Seg2_R
Sequence3=Hose_Seg3_R_Down
Sequence3_Model=Hose_Seg3_R
Sequence4=Hose_Seg4_R_Down
Sequence4_Model=Hose_Seg4_R

[Hose_Retract_Left]
NumberOfSequencesToPlay=4
Sequence1=Hose_Seg1_R_up
Sequence1_Model=Hose_Seg1_R
Sequence2=Hose_Seg2_R_up
Sequence2_Model=Hose_Seg2_R
Sequence3=Hose_Seg3_R_up
Sequence3_Model=Hose_Seg3_R
Sequence4=Hose_Seg4_R_up
Sequence4_Model=Hose_Seg4_R

[Hose_Extend_Both]
NumberOfSequencesToPlay=8
Sequence1=Hose_Seg1_R_Down
Sequence1_Model=Hose_Seg1_R
Sequence2=Hose_Seg2_R_Down
Sequence2_Model=Hose_Seg2_R
Sequence3=Hose_Seg3_R_Down
Sequence3_Model=Hose_Seg3_R
Sequence4=Hose_Seg4_R_Down
Sequence4_Model=Hose_Seg4_R
Sequence5=Hose_Seg1_L_Down
Sequence5_Model=Hose_Seg1_L
Sequence6=Hose_Seg2_L_Down
Sequence6_Model=Hose_Seg2_L
Sequence7=Hose_Seg3_L_Down
Sequence7_Model=Hose_Seg3_L
Sequence8=Hose_Seg4_L_Down
Sequence8_Model=Hose_Seg4_L

[Hose_Retract_Both]
NumberOfSequencesToPlay=8
Sequence1=Hose_Seg1_R_up
Sequence1_Model=Hose_Seg1_R
Sequence2=Hose_Seg2_R_up
Sequence2_Model=Hose_Seg2_R
Sequence3=Hose_Seg3_R_up
Sequence3_Model=Hose_Seg3_R
Sequence4=Hose_Seg4_R_up
Sequence4_Model=Hose_Seg4_R
Sequence5=Hose_Seg1_L_up
Sequence5_Model=Hose_Seg1_L
Sequence6=Hose_Seg2_L_up
Sequence6_Model=Hose_Seg2_L
Sequence7=Hose_Seg3_L_up
Sequence7_Model=Hose_Seg3_L
Sequence8=Hose_Seg4_L_up
Sequence8_Model=Hose_Seg4_L
#############################################################

[Flap_Down]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=5 
RotationX2=-15
Smoothness2=EaseInOut

[Flap_Up]
NumberOfSteps=2
Time1=0 
RotationX1=-15
Smoothness1=EaseInOut
Time2=5 
RotationX2=0
Smoothness2=EaseInOut

[Outer_Flaps_L_Down]
NumberOfSteps=2
Step1=0|x,y,z|0,y,0|Linear
Step2=5|x,y,z|-15,y,6|Linear

[Outer_Flaps_L_Up]
NumberOfSteps=2
Step1=0|x,y,z|-15,y,6|Linear
Step2=5|x,y,z|0,y,0|Linear

[Outer_Flaps_R_Down]
NumberOfSteps=2
Step1=0|x,y,z|0,y,0|Linear
Step2=5|x,y,z|-15,y,-6|Linear

[Outer_Flaps_R_Up]
NumberOfSteps=2
Step1=0|x,y,z|-15,y,-6|Linear
Step2=5|x,y,z|0,y,0|Linear

#############################################################

[Nose_Gear_Down]
NumberOfSteps=2
Step1=4|x,y,z|-75,y,z|Linear
Step2=8|x,y,z|0,y,z|Linear


[Nose_Gear_Hatch_Down1]
NumberOfSteps=4
Step1=0|x,y,z|0,0,0|Linear
Step2=4|x,y,z|-9,-12,-90|Linear
Step3=8|x,y,z|-9,-12,-90|Linear
Step4=12|x,y,z|0,0,0|Linear

[Nose_Gear_Hatch_Down2]
NumberOfSteps=2
Step1=0|x,y,z|-12,1,85|Linear
Step2=4|x,y,z|0,0,0|Linear

[Nose_Gear_Hatch_Down3]
NumberOfSteps=4
Step1=0|x,y,z|0,0,0|Linear
Step2=4|x,y,z|-9,12,90|Linear
Step3=8|x,y,z|-9,12,90|Linear
Step4=12|x,y,z|0,0,0|Linear

[Nose_Gear_Hatch_Down4]
NumberOfSteps=2
Step1=0|x,y,z|-12,-1,-85|Linear
Step2=4|x,y,z|0,0,0|Linear

[Left_Gear_Down]
NumberOfSteps=2
Step1=4|x,y,z|x,-14,90|Linear
Step2=8|x,y,z|x,0,0|Linear

[Left_Gear_Down2]
NumberOfSteps=2
Step1=4|x,0,z|x,y,z|Linear
Step2=8|x,0.008954,0.001|x,y,z|Linear

[Left_Door_Down1]
NumberOfSteps=2
Step1=4|x,y,z|x,y,-80|Linear
Step2=8|x,y,z|x,y,0|Linear

[Left_Door_Down2]
NumberOfSteps=4
Step1=0|x,y,z|x,y,0|Linear
Step2=4|x,y,z|x,y,-85|Linear
Step3=6|x,y,z|x,y,-85|Linear
Step4=10|x,y,z|x,y,0|Linear

[Right_Gear_Down]
NumberOfSteps=2
Step1=4|x,y,z|x,14,-90|Linear
Step2=8|x,y,z|x,0,0|Linear

[Right_Gear_Down2]
NumberOfSteps=2
Step1=4|x,0,z|x,y,z|Linear
Step2=8|x,0.008954,0.001|x,y,z|Linear

[Right_Door_Down1]
NumberOfSteps=2
Step1=4|x,y,z|x,y,80|Linear
Step2=8|x,y,z|x,y,0|Linear

[Right_Door_Down2]
NumberOfSteps=4
Step1=0|x,y,z|x,y,0|Linear
Step2=4|x,y,z|x,y,85|Linear
Step3=6|x,y,z|x,y,85|Linear
Step4=10|x,y,z|x,y,0|Linear

#############################################################

[Nose_Gear_Up]
NumberOfSteps=2
Step1=4|x,y,z|0,y,z|Linear
Step2=8|x,y,z|-75,y,z|Linear


[Nose_Gear_Hatch_Up1]
NumberOfSteps=4
Step1=0|x,y,z|0,0,0|Linear
Step2=4|x,y,z|-9,-12,-90|Linear
Step3=8|x,y,z|-9,-12,-90|Linear
Step4=12|x,y,z|0,0,0|Linear

[Nose_Gear_Hatch_Up2]
NumberOfSteps=2
Step1=8|x,y,z|0,0,0|Linear
Step2=12|x,y,z|-12,1,85|Linear

[Nose_Gear_Hatch_Up3]
NumberOfSteps=4
Step1=0|x,y,z|0,0,0|Linear
Step2=4|x,y,z|-9,12,90|Linear
Step3=8|x,y,z|-9,12,90|Linear
Step4=12|x,y,z|0,0,0|Linear

[Nose_Gear_Hatch_Up4]
NumberOfSteps=2
Step1=8|x,y,z|0,0,0|Linear
Step2=12|x,y,z|-12,-1,-85|Linear

[Left_Gear_Up]
NumberOfSteps=2
Step1=4|x,y,z|x,y,0|Linear
Step2=8|x,y,z|x,-14,90|Linear

[Left_Gear_Up2]
NumberOfSteps=2
Step1=4|x,0.008954,0.001|x,y,z|Linear
Step2=8|x,0,z|x,y,z|Linear

[Left_Door_Up1]
NumberOfSteps=2
Step1=4|x,y,z|x,y,0|Linear
Step2=8|x,y,z|x,y,-80|Linear

[Left_Door_Up2]
NumberOfSteps=4
Step1=0|x,y,z|x,y,0|Linear
Step2=4|x,y,z|x,y,-85|Linear
Step3=6|x,y,z|x,y,-85|Linear
Step4=10|x,y,z|x,y,0|Linear

[Right_Gear_Up]
NumberOfSteps=2
Step1=4|x,y,z|x,y,0|Linear
Step2=8|x,y,z|x,14,-90|Linear

[Right_Gear_Up2]
NumberOfSteps=2
Step1=4|x,0.008954,0.001|x,y,z|Linear
Step2=8|x,0,z|x,y,z|Linear

[Right_Door_Up1]
NumberOfSteps=2
Step1=4|x,y,z|x,y,0|Linear
Step2=8|x,y,z|x,y,80|Linear

[Right_Door_Up2]
NumberOfSteps=4
Step1=0|x,y,z|x,y,0|Linear
Step2=4|x,y,z|x,y,85|Linear
Step3=6|x,y,z|x,y,85|Linear
Step4=10|x,y,z|x,y,0|Linear

#############################################################
[Refueling_Down]
NumberOfSteps=2
Step1=0|x,y,z|x,y,z|Linear
Step2=4|x,y,z|-35,y,z|Linear

[Refueling_Down_2]
NumberOfSteps=2
Step1=4|x,0,0|x,y,z|Linear
Step2=8|x,0.011806,-0.058813|x,y,z|Linear

[Refueling_Up]
NumberOfSteps=2
Step1=4|x,y,z|-35,y,z|Linear
Step2=8|x,y,z|0,y,z|Linear

[Refueling_Up_2]
NumberOfSteps=2
Step1=0|x,0.011806,-0.058813|x,y,z|Linear
Step2=4|x,0,0|x,y,z|Linear

# =============================================================
#(Right Pod)
# =============================================================

[Hose_Seg1_L_Down]
NumberOfSteps=2
Step1=0|0.289406,0.005,-0.05527|15.32,z,y|Linear
Step2=5|0.289406,0.003,-0.104|0,z,y|Linear

[Hose_Seg2_L_Down]
NumberOfSteps=3
Step1=0|0,0.003759,0.006317|5.37,z,y|Linear
Step2=3|0,-0.01161,-0.033961|0,z,y|Linear

[Hose_Seg3_L_Down]
NumberOfSteps=2
Step1=0|0,-0.003412,-0.000837|-6.30,z,y|Linear
Step2=4|0,-0.025312,-0.047837|0,z,y|Linear

[Hose_Seg4_L_Down]
NumberOfSteps=2
Step1=0|0,-0.002749,-0.002029|-4.91,z,y|Linear
Step2=4|0,-0.017149,-0.052229|0,z,y|Linear

[Hose_Seg1_L_up]
NumberOfSteps=2
Step1=0|0.289406,0.003,-0.104|0,z,y|Linear
Step2=3|0.289406,0.005,-0.05527|15.32,z,y|Linear

[Hose_Seg2_L_up]
NumberOfSteps=2
Step1=0|0,-0.01161,-0.033961|0,z,y|Linear
Step2=5|0,0.003759,0.006317|5.37,z,y|Linear

[Hose_Seg3_L_up]
NumberOfSteps=2
Step1=0|0,-0.025312,-0.047837|0,z,y|Linear
Step2=5|0,-0.003412,-0.000837|-6.30,z,y|Linear

[Hose_Seg4_L_up]
NumberOfSteps=2
Step1=0|0,-0.017149,-0.052229|0,z,y|Linear
Step2=5|0,-0.002749,-0.002029|-4.91,z,y|Linear

# =============================================================
#(Left Pod)
# =============================================================

[Hose_Seg1_R_Down]
NumberOfSteps=2
Step1=0|-0.289406,0.005,-0.05527|15.32,z,y|Linear
Step2=5|-0.289406,0.003,-0.104|0,z,y|Linear

[Hose_Seg2_R_Down]
NumberOfSteps=3
Step1=0|0,0.003759,0.006317|5.37,z,y|Linear
Step2=3|0,-0.01161,-0.033961|0,z,y|Linear

[Hose_Seg3_R_Down]
NumberOfSteps=2
Step1=0|0,-0.003412,-0.000837|-6.30,z,y|Linear
Step2=4|0,-0.025312,-0.047837|0,z,y|Linear

[Hose_Seg4_R_Down]
NumberOfSteps=2
Step1=0|0,-0.002749,-0.002029|-4.91,z,y|Linear
Step2=4|0,-0.017149,-0.052229|0,z,y|Linear


[Hose_Seg1_R_up]
NumberOfSteps=2
Step1=0|-0.289406,0.003,-0.104|0,z,y|Linear
Step2=3|-0.289406,0.005,-0.05527|15.32,z,y|Linear

[Hose_Seg2_R_up]
NumberOfSteps=2
Step1=0|0,-0.01161,-0.033961|0,z,y|Linear
Step2=5|0,0.003759,0.006317|5.37,z,y|Linear

[Hose_Seg3_R_up]
NumberOfSteps=2
Step1=0|0,-0.025312,-0.047837|0,z,y|Linear
Step2=5|0,-0.003412,-0.000837|-6.30,z,y|Linear

[Hose_Seg4_R_up]
NumberOfSteps=2
Step1=0|0,-0.017149,-0.052229|0,z,y|Linear
Step2=5|0,-0.002749,-0.002029|-4.91,z,y|Linear