[General]
HullnumberReference=Hullnumber
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfVariants=1

[Default]
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

CustomAirGroup=True
usn_f-14e=Squadron9,8|Squadron8,8
usn_fa_18e_rsa=Squadron4,14|Squadron1,14
usn_fa_18f_rsa=Squadron5,14
usn_fa_xx=Squadron1,14
usn_e-2d=Squadron6,6
usn_ea-6b_late=Squadron6,2
usn_ea_18g_rsa=Squadron6,3
#usn_s-3b=Squadron6,8
usn_sh-3j=Squadron1,8

[Variant1]  # USS Enterprise CVN-80
ResourcesHullnumberFolder=assets/ships/materials/
HullnumberTexture=usn_cvn_080.png
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=cv-66
ResourcesAircraftEmblemFolder=assets/ships/materials/
AircraftEmblemTexture=usn_cvn_80_aircraft.png
ResourcesLiveryFolder=ships/usn_cvn_nimitz/
LiveryTexture=usn_cvn_nimitz_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

#90
CustomAirGroup=True
usn_f-14e=Squadron9,8|Squadron8,8
usn_fa_18e_rsa=Squadron4,14|Squadron1,14
usn_fa_18f_rsa=Squadron5,14
usn_fa_xx=Squadron1,14
usn_e-2d=Squadron6,6
usn_ea-6b_late=Squadron6,2
usn_ea_18g_rsa=Squadron6,3
#usn_s-3b=Squadron6,8
usn_sh-3j=Squadron1,8
