[General]
HullnumberReference=Hullnumber
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfVariants=30

[Default]
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

[Variant1]
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_phm-1
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=desron_26
ResourcesLiveryFolder=ships/usn_phm_pegasus/
LiveryTexture=usn_phm_pegasus_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

[Variant2]
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_phm-2
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=desron_7
ResourcesLiveryFolder=ships/usn_phm_pegasus/
LiveryTexture=usn_phm_pegasus_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

[Variant3]
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_phm-3
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=desron_10
ResourcesLiveryFolder=ships/usn_phm_pegasus/
LiveryTexture=usn_phm_pegasus_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

[Variant4]
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_phm-4
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=desron_7
ResourcesLiveryFolder=ships/usn_phm_pegasus/
LiveryTexture=usn_phm_pegasus_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

[Variant5]
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_phm-5
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=desron_10
ResourcesLiveryFolder=ships/usn_phm_pegasus/
LiveryTexture=usn_phm_pegasus_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

[Variant6]
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_phm-6
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=desron_7
ResourcesLiveryFolder=ships/usn_phm_pegasus/
LiveryTexture=usn_phm_pegasus_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

[Variant7]
#ResourcesHullnumberFolder=ships/materials/hullnumbers/
#HullnumberTexture=usn_phm-6
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=desron_7
ResourcesLiveryFolder=ships/usn_phm_pegasus/
LiveryTexture=usn_phm_pegasus_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

[Variant8]
#ResourcesHullnumberFolder=ships/materials/hullnumbers/
#HullnumberTexture=usn_phm-6
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=desron_7
ResourcesLiveryFolder=ships/usn_phm_pegasus/
LiveryTexture=usn_phm_pegasus_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

[Variant9]
#ResourcesHullnumberFolder=ships/materials/hullnumbers/
#HullnumberTexture=usn_phm-6
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=desron_7
ResourcesLiveryFolder=ships/usn_phm_pegasus/
LiveryTexture=usn_phm_pegasus_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

[Variant10]
#ResourcesHullnumberFolder=ships/materials/hullnumbers/
#HullnumberTexture=usn_phm-6
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=desron_7
ResourcesLiveryFolder=ships/usn_phm_pegasus/
LiveryTexture=usn_phm_pegasus_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

[Variant11]
#ResourcesHullnumberFolder=ships/materials/hullnumbers/
#HullnumberTexture=usn_phm-6
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=desron_7
ResourcesLiveryFolder=ships/usn_phm_pegasus/
LiveryTexture=usn_phm_pegasus_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

[Variant12]
#ResourcesHullnumberFolder=ships/materials/hullnumbers/
#HullnumberTexture=usn_phm-6
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=desron_7
ResourcesLiveryFolder=ships/usn_phm_pegasus/
LiveryTexture=usn_phm_pegasus_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

[Variant13]
#ResourcesHullnumberFolder=ships/materials/hullnumbers/
#HullnumberTexture=usn_phm-6
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=desron_7
ResourcesLiveryFolder=ships/usn_phm_pegasus/
LiveryTexture=usn_phm_pegasus_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

[Variant14]
#ResourcesHullnumberFolder=ships/materials/hullnumbers/
#HullnumberTexture=usn_phm-6
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=desron_7
ResourcesLiveryFolder=ships/usn_phm_pegasus/
LiveryTexture=usn_phm_pegasus_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

[Variant15]
#ResourcesHullnumberFolder=ships/materials/hullnumbers/
#HullnumberTexture=usn_phm-6
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=desron_7
ResourcesLiveryFolder=ships/usn_phm_pegasus/
LiveryTexture=usn_phm_pegasus_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

[Variant16]
#ResourcesHullnumberFolder=ships/materials/hullnumbers/
#HullnumberTexture=usn_phm-6
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=desron_7
ResourcesLiveryFolder=ships/usn_phm_pegasus/
LiveryTexture=usn_phm_pegasus_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

[Variant17]
#ResourcesHullnumberFolder=ships/materials/hullnumbers/
#HullnumberTexture=usn_phm-6
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=desron_7
ResourcesLiveryFolder=ships/usn_phm_pegasus/
LiveryTexture=usn_phm_pegasus_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

[Variant18]
#ResourcesHullnumberFolder=ships/materials/hullnumbers/
#HullnumberTexture=usn_phm-6
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=desron_7
ResourcesLiveryFolder=ships/usn_phm_pegasus/
LiveryTexture=usn_phm_pegasus_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

[Variant19]
#ResourcesHullnumberFolder=ships/materials/hullnumbers/
#HullnumberTexture=usn_phm-6
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=desron_7
ResourcesLiveryFolder=ships/usn_phm_pegasus/
LiveryTexture=usn_phm_pegasus_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

[Variant20]
#ResourcesHullnumberFolder=ships/materials/hullnumbers/
#HullnumberTexture=usn_phm-6
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=desron_7
ResourcesLiveryFolder=ships/usn_phm_pegasus/
LiveryTexture=usn_phm_pegasus_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

[Variant21]
#ResourcesHullnumberFolder=ships/materials/hullnumbers/
#HullnumberTexture=usn_phm-6
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=desron_7
ResourcesLiveryFolder=ships/usn_phm_pegasus/
LiveryTexture=usn_phm_pegasus_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

[Variant22]
#ResourcesHullnumberFolder=ships/materials/hullnumbers/
#HullnumberTexture=usn_phm-6
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=desron_7
ResourcesLiveryFolder=ships/usn_phm_pegasus/
LiveryTexture=usn_phm_pegasus_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

[Variant23]
#ResourcesHullnumberFolder=ships/materials/hullnumbers/
#HullnumberTexture=usn_phm-6
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=desron_7
ResourcesLiveryFolder=ships/usn_phm_pegasus/
LiveryTexture=usn_phm_pegasus_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

[Variant24]
#ResourcesHullnumberFolder=ships/materials/hullnumbers/
#HullnumberTexture=usn_phm-6
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=desron_7
ResourcesLiveryFolder=ships/usn_phm_pegasus/
LiveryTexture=usn_phm_pegasus_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

[Variant25]
#ResourcesHullnumberFolder=ships/materials/hullnumbers/
#HullnumberTexture=usn_phm-6
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=desron_7
ResourcesLiveryFolder=ships/usn_phm_pegasus/
LiveryTexture=usn_phm_pegasus_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

[Variant26]
#ResourcesHullnumberFolder=ships/materials/hullnumbers/
#HullnumberTexture=usn_phm-6
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=desron_7
ResourcesLiveryFolder=ships/usn_phm_pegasus/
LiveryTexture=usn_phm_pegasus_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

[Variant27]
#ResourcesHullnumberFolder=ships/materials/hullnumbers/
#HullnumberTexture=usn_phm-6
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=desron_7
ResourcesLiveryFolder=ships/usn_phm_pegasus/
LiveryTexture=usn_phm_pegasus_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

[Variant28]
#ResourcesHullnumberFolder=ships/materials/hullnumbers/
#HullnumberTexture=usn_phm-6
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=desron_7
ResourcesLiveryFolder=ships/usn_phm_pegasus/
LiveryTexture=usn_phm_pegasus_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

[Variant29]
#ResourcesHullnumberFolder=ships/materials/hullnumbers/
#HullnumberTexture=usn_phm-6
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=desron_7
ResourcesLiveryFolder=ships/usn_phm_pegasus/
LiveryTexture=usn_phm_pegasus_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US

[Variant30]
#ResourcesHullnumberFolder=ships/materials/hullnumbers/
#HullnumberTexture=usn_phm-6
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=desron_7
ResourcesLiveryFolder=ships/usn_phm_pegasus/
LiveryTexture=usn_phm_pegasus_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US