
[Shader]
Path=Marmoset/Bumped Specular IBL
[Properties]
_Color=Color,{*}808080ff
_SpecColor=Color,{*}ffffffff
_SpecInt=Float,1.0
_Shininess=Float,2.5
_Fresnel=Float,0.75

[Textures]

_MainTex=aircraft/wp_mig-23a/plan_j9_white.png
#_SpecTex=aircraft/wp_mig-23a/usn_sh-2f_spec.png
#_BumpMap=aircraft/wp_mig-23a/usn_sh-2f_nm.png