[AmmunitionNames]
# ------------------ AAM ------------------

# ------------------ SAM ------------------

usa_mim-104b_mi=MIM-104B,Patriot,SAM,Еще одним усовершенствованием системы стало внедрение другого типа ракет, получившего обозначение MIM-104B и получившего в армии название "система постановки помех" (ASOJ). Этот вариант предназначен для того, чтобы помочь Patriot поражать самолеты с дистанционным управлением на дальних дистанциях. Он работает аналогично противорадиационной ракете в том смысле, что летит по сильно заданной траектории, а затем обнаруживает, нацеливается и уничтожает наиболее значительный источник излучения в зоне, указанной оператором.

usa_mim-104c_mi=MIM-104C,Patriot,SAM,Эта ракета была оптимизирована для борьбы с баллистическими ракетами. Основными изменениями в ракете MIM-100C стали размер заряда в ее осколочно-фугасной боевой части, который был изменен с примерно 2 граммов до примерно 45 граммов, и время срабатывания импульсно-доплеровского радиолокационного взрывателя, который был оптимизирован для высокоскоростных целей, хотя и сохранил свой старый алгоритм для воздушных боев при необходимости.

usa_mim-104d_mi=MIM-104D,Patriot,SAM,Основным усовершенствованием оригинальной ракеты MIM-104D стала новая, более быстрая боеголовка с неконтактным взрывателем. Испытания показали, что взрыватели на оригинальных ракетах PAC-2 (MIM-104C) приводили в действие свои боеголовки слишком поздно при попадании в баллистические ракеты с чрезвычайно крутым заходом на цель, и поэтому было необходимо сократить задержку срабатывания взрывателя. Ракета MIM-104D получила новую головку самонаведения с низким уровнем шума, предназначенную для уменьшения помех перед радиолокационной головкой самонаведения ракеты, и головку самонаведения с более высокими характеристиками, предназначенную для лучшего обнаружения целей с низким радиолокационным сечением.

usa_mim-104e_mi=MIM-104E,Patriot,SAM,В рамках этой программы модернизации были созданa ракетa, известные как MIM-104E. Ракеты получили совершенно новую носовую часть, которая была разработана специально для того, чтобы быть более эффективной против целей с низкой радиолокационной следом на малой высоте, таких как крылатые ракеты. MIM-104E получил новый взрыватель, который был дополнительно оптимизирован для защиты от баллистических ракет, и новый генератор с низким уровнем шума, который повышает чувствительность головки самонаведения к целям с малым радиолокационным силуэтом. MIM-104E - модернизированная версия PAC-2.

usa_mim-104f_mi=MIM-104F,Patriot,SAM,Ракета MIM-104F более маневренна, чем предыдущие варианты, благодаря 180 крошечным импульсным ракетным двигателям на твердом топливе, установленным в носовой части ракеты, которые называются двигателями управления ориентацией, или ACMS, которые служат для точного выравнивания траектории ракеты с целью для достижения возможности поражения цели.

# ---------- Anti-radar Missiles ---------

# ---------- Anti-ship Missiles ----------

#-----------Land Strike only missiles---------

# ---------- Anti-sub  Missilies ----------

# ------------------ RBU ------------------

# --------------- Torpedoes ---------------

# ------------------ Bombs -----------------

# ---------------- Sonobuoys ---------------

# ------------------ FFAR -----------------

# ------------------ MLRS -----------------

# ------------------ Guns -----------------

# ------------------ CIWS -----------------

# ----------- Noisemakers/Chaff -----------

# ----------------- Decoys ----------------

# ----------------- Special ----------------

# Depth charge

# ----------------- Fueltanks ----------------


