[General]
UnitType=LandUnit
LandUnitSubType=MobileUnit
IsMobile=True

DefaultCameraDistance=0.8
MinCameraDistanceForeAft=0.3
MinCameraDistanceBroadside=0.3
CameraPivotHeight=0.03

GroundOffset=0
AutoFlatten=False
MaskVegetation=True

Length=4.5                  // in meters
Beam=1.9                       // in meters
Range=800                      // in miles

# Hull armor: None, Minor, Moderate, Heavy
ArmorType=Moderate
DamagePoints=5  //systems damage contribution substracted from this when systems destroyed, when becomes less than zero, the whole unit is considered being destroyed

[Tacview]
Name=Jaguar
Tag=Ground+Vehicle

[Physics]
HorsePower=200
Mass=2.8                     // in tons

MaxForwardVelocity=43.2        // in knots
MaxBackwardVelocity=7          // in knots
Braking=12                     // knots/sec
TurnRate=25                    // in degrees per second


[Animations]
NumberOfAnimationReferences=0
AnimationFile_1=


[AI]
UnitScoreValue=0.5             // value for calculation of mission score
Role=Gun

[ControlSystem]
Collider=coll_hitbox  // makes unit destroyable
Integrity=5

[SensorData]
#Visual
VisualIdentificationRange=2.5  // Camouflaged  (x0.5)
IRSignature=Small
# Radar related (RCS => radar cross section)
RCS=Small

[---------- Sensor Systems ----------]
[SensorSystems]
NumberOfSensorSystems=1
#---------- Visual ----------
[SensorSystem1] #Optics
Type=Visual
SystemName=Optics
MountPosition=0,0.04,0


[---------- Weapon Systems ----------]
############################################################
# Weapon Systems
############################################################
[WeaponSystems]
NumberOfWeaponSystems=2

[WeaponSystem1]  #M2 turret
Type=CIWS
SystemName=M2
#Sensors
#Animations
#Mount
Mount=12.7_base
IsMountRotatable=True
#Containers
ContainerBase=12.7_gun
Gun=12.7_gun
AreContainersRotatable=True
#Angles
ElevationArc=-10,80
RestAngles=0
#Loading
AssociatedMagazine=WeaponMagazineGun1
#Effects
#Other
MaxReactiontime=2.5
MaxVelocityToFire=50
WorksStandalone=True
VIDIncrease=2.5  // In miles. Flat base VID increace when firing.
TargetAcquisitionTime=0.7

[WeaponSystem2] #Minimi
Type=CIWS
SystemName=FN_Minimi
#Sensors
#Animations
#Mount
Mount=Minimi_base
IsMountRotatable=True
#Containers
ContainerBase=Minimi_gun
Gun=Minimi_gun
AreContainersRotatable=True
#Angles
ElevationArc=-10,60
FiringArcs=-22.5,22.5
RestAngles=0
#Loading
AssociatedMagazine=WeaponMagazineGun2
#Effects
#Other
MaxReactiontime=2.5
MaxVelocityToFire=50
WorksStandalone=True
VIDIncrease=2.5  // In miles. Flat base VID increace when firing.
TargetAcquisitionTime=0.7

[---------- WeaponMagazines ----------]
[WeaponMagazineGun1]
NumberOfAmmunitionTypes=1
Ammunition1=fr_cal_127x99mm
Ammunition1_Count=2000
ModuleType=SmallMagazine

[WeaponMagazineGun2]
NumberOfAmmunitionTypes=1
Ammunition1=fr_cal_762x51mm
Ammunition1_Count=2000
ModuleType=SmallMagazine

[--------------------------- Mesh definitions ---------------------------]
[Models]
LODLevels=0
LOD1Distance=1.0  // nautical miles

ResourcesFolder=assets\models\land_units\vlfs/
ResourcesRoot=vlfs.obj
ResourcesMesh=Body
ResourcesMaterial=body1_mat.ini

******************************************************
[Submodels]


SubModel1=Body_2
SubModel2=Crew
SubModel3=Glass
SubModel4=Interieur
SubModel5=Seat
SubModel6=Roues
SubModel7=12.7_base
SubModel8=12.7_gun
SubModel9=Gunner
SubModel10=Minimi_base
SubModel11=Minimi_gun
SubModel12=Gunner_av

############################################################

[Body_2]
Mesh=Body_2
Material=body2_mat.ini

[Crew]
Mesh=Crew
Material=sof_bme_mat.ini

[Glass]
Mesh=Glass
ResourcesMaterialFolder=aircraft/materials/
Material=cockpit_glass


[Interieur]
Mesh=Interieur
Material=Interieur_mat.ini

[Seat]
Mesh=Seat
Material=Interieur_mat.ini

[Roues]
Mesh=Roues
ResourcesMaterialFolder=assets\models\land_units\griffon/
Material=griffon_mat.ini

[12.7_base]
Mesh=12.7_base
Material=body2_mat.ini
Position=0.000679,0.03,-0.0123

[12.7_gun]
Mesh=12.7_gun
Material=armes_mat.ini
Parent=12.7_base
Position=-0.000479,0.00694,0.0122

[Gunner]
Mesh=Gunner
Material=sof_bme_mat.ini
Parent=12.7_gun
Position=0.000541,-0.0042,-0.0114

[Minimi_base]
Mesh=Minimi_base
Material=body1_mat.ini
Position=0.0124,0.0205,0.017

[Minimi_gun]
Mesh=Minimi_gun
Material=armes_mat.ini
Parent=Minimi_base
Position=-0.000932,0.003255,-0.000732

[Gunner_av]
Mesh=Gunner_av
Material=sof_bme_mat.ini
Parent=Minimi_gun
Position=-0.000537,-0.00191,-0.00908


*************************************************************
[---------- Effects ----------]
[Particles]
SmallFireEffectClass=SmallShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=ModerateShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=SevereShipFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffect=effects/explosions/emitters/missile_hit_ship
SecondaryExplosionEffectPosition=0,0,0

DustEffect=effects/land units/emitters/vehicle_movement_dust
DustEffectPosition=0,0,0

[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=1
AmbientAudioClip=audio/ships/Ship-Turbine-Small
AmbientAudioPosition=0,0,0
AmbientAudioRollOff=Logarithmic
AmbientAudioDistance=1,20
AmbientAudioPitchRange=1.0,1.6
AmbientAudioVolume=1.0
AmbientAudioAudibility=Above  // layer of sound audibility: Above, Below, AboveAndBelow

[---------- Colliders ----------]
[Colliders]
UseKinematicCollision=False
NumberOfMeshColliders=0
NumberOfColliders=2

Collider1=coll_hitbox
Collider2=coll_collider

[coll_hitbox]
Collider=Box
Position=0,0.0197,0
Rotation=0,0,0
Scale=0.045,0.04,0.1

[coll_collider]
Collider=Box
Position=0,0.0028,-0.0023
Rotation=0,0,0
Scale=0.03,0.005,0.05
Layer=Default
