[ ------------------------ Visual/Infared ------------------------- ]

[A-10_IR]
Kind=Visual
#Infrared
VIDRangeMultiplier=1.8           // Target VID range multiplied by this for identification check. 0 means it cannot identify
MaxRangeMultiplier=3.2           // Target VID range multiplied by this for detection check. Can not be less then VID multiplier
LookDownMultiplier=0.7             // Final VID/Detection range is multiplied by this in case when target observed on surface background
NightVisionLevel=1             // the portion of full daylight added to the visibility level where 1 is roughly a mid-day


[---------------------------------------- Laser Designator ---------------------------]
