[General]
SerialnumberReferences=Modex
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfSquadrons=1

[Default]
ResourcesSerialnumberFolder=
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=assets/models/aircraft/j15/textures/
EmblemTexture=plan_j15t_MainTex.png
ResourcesLiveryFolder=
LiveryTexture=
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_china
# nations are referenced in the layout.ini file:
Nation=China

[Squadron1]
ResourcesSerialnumberFolder=assets/models/aircraft/j15/numbers/
SerialnumberTextures=T01.png,T02.png,T03.png,T04.png,T05.png,T06.png,T07.png,T08.png,T09.png,T10.png,T11.png,T12.png,T13.png,T14.png,T15.png,T16.png,T17.png,T18.png,T19.png,T20.png,T21.png,T22.png,T23.png,T24.png,T25.png,T26.png,T27.png,T28.png,T29.png,T30.png
SerialNumberPrefix=
ResourcesEmblemFolder=assets/models/aircraft/j15/fw001/
EmblemTexture=plan_j15t_tx
ResourcesLiveryFolder=
LiveryTexture=
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_china
Nation=China