[General]
SerialnumberReferences=Number
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfSquadrons=1

[Default]
#ResourcesLiveryFolder=assets/textures/j-20a/
#LiveryTexture=1.png
Nation=China

[Squadron1]
#ResourcesLiveryFolder=assets/textures/j-20a/
#LiveryTexture=1.png
Nation=China

