[LoadoutNames]
#------------------------------------------ New system ------------------------------------------
# - LongRange means operating range of aircraft, not the weapons range
# ---------- Mandatory loadouts ----------
# ---------- Anti Air loadouts ----------
# ---------- Anti Surface loadouts ----------
StandoffNuclear=Standoff (Nuclear)
StandoffLongRange=Standoff Long Range
StandoffNuclearLongRange=Standoff Long Range (Nuclear)
# ---------- Anti Ship loadouts ----------
AntiShipNuclear=Anti Ship (Nuclear)
AntiShipHeavyLongRange=Anti Ship Heavy Long Range             
AntiShipNuclearLongRange=Anti Ship Long Range (Nuclear)
# ---------- Anti Sub loadouts ----------
# ---------- Special loadouts ----------