[Shader]
Path=Marmoset/Bumped Specular IBL

 #[Properties]
 #_Color=Color,{}808080ff
 #_SpecColor=Color,{}ffffffff
 #_SpecInt=Float,1.0
 #_Shininess=Float,6.5
 #_Fresnel=Float,0.75

[Textures]
_MainTex=assets/ships/ita_ssk_todaro_batch1/todaro_hull/todaro_diff.png
_SpecTex=assets/ships/ita_ssk_todaro_batch1/todaro_hull/212_gloss.png
_BumpMap=assets/ships/ita_ssk_todaro_batch1/todaro_hull/212_normal.png