[AmmunitionNames]
# ------------------ AAM ------------------
# ------------------ SAM ------------------

# ---------- Anti-radar Missiles ---------


# ---------- Anti-ship Missiles ----------
wp_ss-n-26a=P-800,Oniks,ASM,The SS-N-26 Strobile (3M55 Oniks) is a Soviet high performance supersonic standoff anti-ship weapon. Similar to the 3M82 Moskit and 3M45 Granit missiles in concept, Oniks is the lightweight model of a pair of new generation anti ship missiles. Utilizing its reduced footprint to allow carriage on smaller platforms like aircraft or missile boats and older ships/subs, Oniks is an extremely potent missile for its size, using the Granit-Elektron seeker developed from P-700 Granit and miniaturized to fit inside of Oniks, and has an extremely fast flight profile at high altitude and at sea level. All of this, combined with a new generation deceptive jammer, terminal maneuvers, and auxillary land attack capability, makes Oniks a truly terrifying weapon.

wp_ss-n-27a=3M54K,Kalibr,ASM,The SS-N-27A (Kalibr 3M54K) is a Russian anti ship cruise missile, with subsonic speed and long range, and an extremely high speed terminal 'dart' as a warhead, approaching a maximum speed of Mach 3.0. This poses an extreme threat to even modern air defense systems, and can be considered as one of the most dangerous anti-ship missile threats if you let it get to its terminal phase. Outside of the terminal phase, this missile has identical characteristics to other subsonic cruise missiles, making an easy target if detected and engaged in time.


#-----------Land Strike only missiles---------
wp_rsm-56=RSM-56,Bulava,ASM,The RSM-56 Bulava (NATO reporting names SS-N-30 / SS-NX-32) is a submarine-launched ballistic missile (SLBM) developed for the Russian Navy and deployed in 2019 on the new Borei class of ballistic missile nuclear submarines.

wp_r-39=R-39,SS-N-20 Sturgeon,SLBM,The R-39 Rif (NATO: SS-N-20 Sturgeon) is a Soviet submarine-launched ballistic missile carried by the Project 941 Typhoon-class SSBN. It is a large three-stage solid-fuel missile carrying multiple independently targetable reentry vehicles.

# ---------- Anti-sub  Missilies ----------

# ------------------ RBU ------------------

# --------------- Torpedoes ---------------
wp_fizik-2=Fizik-2,Futlyar,Torpedo,The Futlyar (Fizik-2) is a Russian deep-water homing torpedo that entered service with the Russian Navy in 2017, replacing the UGST (Fizik-1). Futlyar is a wire-guided torpedo with a top speed about 50 knots and a maximum depth capability of more than 500 m (1,600 ft).

# ------------------ Bombs -----------------

wp_r-29rmu=R-29RMU
# ---------------- Sonobuoys ---------------


# ------------------ FFAR -----------------


# ------------------ MLRS -----------------

# ------------------ Guns -----------------

# ------------------ CIWS -----------------


# ----------- Noisemakers/Chaff -----------


# ----------------- Decoys ----------------

# ----------------- Special ----------------


# ----------------- Fueltanks ----------------
