[Shader]
Path=Marmoset/Bumped Specular IBL

 #[Properties]
 #_Color=Color,{}808080ff
 #_SpecColor=Color,{}ffffffff
 #_SpecInt=Float,1.0
 #_Shininess=Float,6.5
 #_Fresnel=Float,0.75

[Textures]
_MainTex=assets/ships/ger_F123_brandenburg/SMARTS_textures/SMARTS_texture.png
_SpecTex=assets/ships/ger_F123_brandenburg/SMARTS_textures/SMARTS_spec.png
_BumpMap=assets/ships/ger_F123_brandenburg/SMARTS_textures/SMARTS_normal.png