[ ========================================= General ========================================== ]
[General]
DataLinkUpdateRate=1             // every x seconds there will be an update for the overall sensor image for the minimap
PassiveSensorUpdateRate=1.0        // every x seconds the passive contacts will be re-evaluated
LostPassiveContactTimeToDisable=5  // time in seconds after which a lost passive contact bearing line will be greyed out
LostContactTimeToRemove=30         // time in seconds after which a lost contact will be removed from the map


[======================================== United States ========================================]
[ ------------------------ Visual/Infared ------------------------- ]


[ ---------------------------- Radars ----------------------------- ]
[ ------------------------ Aircraft Radars ------------------------- ]
[AN/APY-9]
#Users: usaf_e-2d
Kind=Radar
Type=Search            // Classes can be "DirectedSearch", "Search", "Targeting"
HasDataLink=True       // true means the sensor data will be used for the entire task force via data link, false local use only
Role=AirAndSurface     // Role can be "Surface", "Air", "AirAndSurface"
Mode=Illuminate        // Can be "Illuminate", "RadioCommand"
RotationDirection=1    // -1 means left, 1 means right
RPM=12                 // revolutions per minute
MinRange=0.2           // min range in km
MaxRange=550.0         // max range in km
MinAltitude=0          // min altitude in meters, relevant for air, unused for surface
MaxAltitude=30480      // max altitude in meters, relevant for air, unused for surface
RangeResolution=30.0  // defines the minimum range where two targets behind can be recognized as two; in meters
BeamWidth=2.0          // defines the beam width in degrees for BearingResolution >= 2*Dist*sin(BeamWidth/2)
Gain=55                // gain in dB on the sensor
Frequency=UHF-Band     // frequency band
PeakPower=400.0       // output peak power in kW

[ ------------------------ Visual/Infared ------------------------- ]
[AN/AAQ-37] #Advanced Hawkeye Electro-Optical System
Kind=Visual
VIDRangeMultiplier=3.0           // Target VID range multiplied by this for identification check
MaxRangeMultiplier=4.0           // Target VID range multiplied by this for detection check. Can not be less then VID multiplier
LookDownMultiplier=0.95          // Final VID/Detection range is multiplied by this in case when target observed on surface background
NightVisionLevel=0.6             // the portion of full daylight added to the visibility level where 1 is roughly a mid-day
Recon=True                       // Indicates that this system can photograph stationary land targets and after aircraft carrying this system lands, a bonus against those targets will be applied.

[ ---------- ELINT ---------- ]
[AN/ALQ-217]
Kind=ESM
Gain=15                             // gain of sensor in dB
HasDataLink=True                    // true means the sensor data will be used for the entire task force via data link, false local use only
AngularResolution=5.0              // in degrees
Frequencies=All                     // Frequencies that current ESM system can detect

[---------- Surface ships ----------]
[---Air/Air&Surface---]
[SPY-4]
#Users:usn_cvn_ford
Kind=Radar
Type=DirectedSearch    // Classes can be "Search", "Targeting"
HasDataLink=True       // true means the sensor data will be used for the entire task force via data link, false local use only
Role=Air               // Role can be "Surface", "Air", "AirAndSurface"
Mode=Illuminate        // Can be "Illuminate", "RadioCommand"
RotationDirection=1    // -1 means left, 1 means right
TargetChannels=1000      // if applicable number of targets it can track simultaneously
WeaponChannels=24      // if applicable number of weapons (missiles) it can guide simultaneously
RPM=0                  // revolutions per minute
MinRange=0.2           // min range in km
MaxRange=700.0         // max range in km
MinAltitude=10         // min altitude in meters, relevant for air, unused for surface
MaxAltitude=60960      // max altitude in meters, relevant for air, unused for surface
RangeResolution=5.0   // defines the minimum range where two targets behind can be recognized as two; in meters
BeamWidth=1.2          // defines the beam width in degrees for BearingResolution >= 2*Dist*sin(BeamWidth/2)
Gain=47.0              // gain in dB on the sensor
Frequency=S-Band       // frequency band
PeakPower=6200.0       // output peak power in kW
ModuleType=BigSensor

[---Surface only---]

[---Fire Control---] + search radars linked to FC radars
[SPY-3]
#Users:usn_cvn_ford
Kind=Radar
Type=Targeting         // Classes can be "Search", "Targeting"
HasDataLink=True      // true means the sensor data will be used for the entire task force via data link, false local use only
Role=AirAndSurface     // Role can be "Surface", "Air", "AirAndSurface"
Mode=Illuminate        // Can be "Illuminate", "RadioCommand"
TargetChannels=250      // if applicable number of targets it can track simultaneously
WeaponChannels=24       // if applicable number of weapons (missiles) it can guide simultaneously
RPM=0                 // revolutions per minute
MinRange=0.1           // min range in km
MaxRange=320.0         // max range in km
MinAltitude=0          // min altitude in meters, relevant for air, unused for surface
MaxAltitude=100000      // max altitude in meters, relevant for air, unused for surface
RangeResolution=2.0   // defines the minimum range where two targets behind can be recognized as two; in meters
BeamWidth=0.7          // defines the beam width in degrees for BearingResolution >= 2*Dist*sin(BeamWidth/2)
Gain=50.0              // gain in dB on the sensor
Frequency=X-Band       // frequency band
PeakPower=1100.0       // output peak power in kW
ModuleType=SmallSensor


[ ---------------------------- Sonars ----------------------------- ]
[---------- Sonobuoys ----------]
