[AmmunitionNames]
# ------------------ AAM ------------------
# ------------------ SAM ------------------
# ---------- Anti-radar Missiles ---------

# ---------- Anti-ship Missiles ----------
3M22=3M22 Zircon,,Zircon,3M22 Zircon or SS-N-33 is a mobile anti-ship hypersonic cruise missile developed by Russia. The estimated range of Zircon is 500 km at low altitude and up to 750 km in a semi-ballistic trajectory, but Russian state media reports a range of 1000 km. It is a two-stage missile, with a solid fuel first stage and a scramjet second stage. The missile will be incorporated into the Kirov-class battlecruiser Admiral Nakhimov this year and Peter the Great in 2022. The 3M22 Zircon was first used in combat in February 2023, as reports from Ukraine found debris pointing to the use of a hypersonic weapon.
#-----------Land Strike only missiles---------
KH-55=Kh-55,,ALCM,The Kh-55 cruise missile is a long-range subsonic air-launched nuclear cruise missile developed by the Soviet Rainbow Design Bureau in 1968 and officially entered service in 1983. The missile uses a composite guidance system of inertial guidance and terrain tracking, with a maximum range of 2,500 kilometers. It can carry nuclear warheads and is mainly carried by Tu-95MS and Tu-160 strategic bombers. Its appearance and performance are similar to the US "Tomahawk" cruise missile, so it is called "Tomahawksky".
KH-55SM=KH-55SM,,ALCM,The KH-55SM cruise missile is an upgraded version of the Kh-55 cruise missile, further expanding its range and strike area.
KH-555=KH-555,,ALCM,KH-555 is an air-launched cruise missile developed by the Russian Tactical Missile Weapons Company based on the Kh-55 nuclear cruise missile. The missile has a maximum range of 3,500 kilometers, uses an inertial navigation and GLONASS satellite composite guidance system, and has a terminal accuracy error of less than 20 meters. It can carry a 500-kilogram conventional warhead or a nuclear warhead. It has been deployed on Tu-160 and Tu-95MS strategic bombers since 2004, and was put into actual combat for the first time in Syria in 2015,becoming an important part of the Russian militarys air-based nuclear deterrence system.
KH-555S=KH-555S,,ALASCM,The KH-555S cruise missile is an anti-ship version of the Kh-555 cruise missile, equipped with an active radar seeker.

KH-101=KH-101,,ALCM,Kh-101 cruise missile is an air launched cruise missile developed by Russias "Rainbow" Design Bureau in 1991 and officially commissioned in 2013. The missile has a length of 7.45 meters, a launch mass of 2300 kg, a conventional Warhead weight of 400 kg, a range of more than 4000 km, and a circular probability error of 10 to 20 meters. The derivative models include a nuclear Warhead Kh-102 and a Kh-50 medium range missile using the same guidance system. It uses radar absorbing materials and a new shape design to reduce the detectability, and carries digital scene image matching correction system and satellite positioning system.

# ---------- Anti-sub  Missilies ----------
# ------------------ RBU ------------------


# --------------- Torpedoes ---------------
# ------------------ Bombs -----------------
su_kab-1500kr=KAB-1500KR,,AGM,Tactical Missiles Corporation KAB-1500KR is a Russian TV-guided bomb, similar to the American GBU-8/15 guided bomb, but the KAB-1500KR has better performance.

# ---------------- Sonobuoys ---------------


# ------------------ FFAR -----------------


# ------------------ MLRS -----------------

# ------------------ Guns -----------------
# ------------------ CIWS -----------------


# ----------- Noisemakers/Chaff -----------


# ----------------- Decoys ----------------

# ----------------- Special ----------------


# ----------------- Fueltanks ----------------
