#!alias aircraft/usn_p-3c.ini
#No Loadout con Harpoon ya que los aviones españoles no lo soportaron
# ver. 20260502
#

[General]
Length=35.61							// In meters

[WeaponSystems]
NumberOfWeaponSystems=3
AvailableLoadouts=Ferry,ASW,AntiShip,Strike,Recon

DateBased_Torpedo=0,usn_mk44_air|1975,usn_mk46_air
DateBased_Racimo=0,usn_rockeye|1985,spa_bme-330|1992,spa_bmep-330

[WeaponSystem1Default] # Default is standard ASW loadout - no bombs
Station1=DateBased_Torpedo
Station2=DateBased_Torpedo
Station3=DateBased_Torpedo
Station4=DateBased_Torpedo
Station5=DateBased_Torpedo
Station6=DateBased_Torpedo
Station7=DateBased_Torpedo
Station8=DateBased_Torpedo

[WeaponSystem1ASW] # ASW multirole loadout - bombs, buoys, torpedoes
Station1=DateBased_Torpedo
Station2=DateBased_Torpedo
Station3=DateBased_Torpedo
Station4=DateBased_Torpedo
Station5=DateBased_Torpedo
Station6=DateBased_Torpedo
Station7=DateBased_Torpedo
Station8=DateBased_Torpedo

[WeaponSystem1AntiShip]
Station1=spa_br-250
Station2=spa_br-250
Station3=spa_br-250
Station4=spa_br-250
Station5=spa_br-250
Station6=spa_br-250
Station7=spa_br-250
Station8=spa_br-250

SalvoFireAmount=spa_br-250,4

[WeaponSystem2AntiShip]
SubModelsToHide=IRM_rails
Station1=usn_lau-10a
Station2=usn_lau-10a
Station3=usn_lau-10a
Station4=usn_lau-10a
station5=
station6=
Station7=DateBased_Racimo
Station8=DateBased_Racimo
Station9=DateBased_Racimo
Station10=DateBased_Racimo

SalvoFireAmount=usn_rockeye,2|spa_bme-330,2|spa_bmep-330,2

[WeaponSystem1Recon] # Light recon loadout for long range MPRA duties 
Station5=DateBased_Torpedo
Station6=DateBased_Torpedo
Station7=DateBased_Torpedo
Station8=DateBased_Torpedo

[WeaponSystem2Recon]
Station2=
Station3=

[Modex]
ResourcesMeshFolder=aircraft/spa_p3a/
RootMesh=spa_p3a_modex.obj
Mesh=Modex
ResourcesMaterialFolder=aircraft/materials/numbers/
Material=numbers
