# ver. 20260413
#
[General]
SerialnumberReferences=Serial
EmblemReference=
NationFlagReference=Flag1
NumberOfSquadrons=1

[Default]
ResourcesLiveryFolder=aircraft/fr_f1/es_ala46/
LiveryTexture=fr_f1_tx
ResourcesEmblemFolder=textures/Misc/
EmblemTexture=transparent
Nation=Spain
ServiceDate=1982|2013

[Squadron1]  #462 Sqn
ResourcesSerialnumberFolder=aircraft/fr_f1/es_ala46/serial/
SerialNumberPrefix=
SerialnumberTextures=01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16,17,18,19,20
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=aircraft/fr_f1/es_ala46/
LiveryTexture=fr_f1_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=Spain