# ver. 20260509
#
[General]
SerialnumberReferences=Modex2,Modex3
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfSquadrons=1

[Default]
# ResourcesSerialnumberFolder=
# SerialNumberPrefix=
# SerialnumberTextures=
# ResourcesEmblemFolder=
# EmblemTexture=
ResourcesLiveryFolder=aircraft/spa_sh-3/textures/
LiveryTexture=spa_sh-3_tx_1.png
SpecularTexture=usn_sh-3h_spec.png
NormalTexture=usn_sh-3h_nm_blur.png
# ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_spain
# # nations are referenced in the layout.ini file:
Nation=Spain


[Squadron1]
ResourcesSerialnumberFolder=aircraft/spa_sh-3/modex/
SerialNumberPrefix=
SerialnumberTextures=509.png,511.png,512.png
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/spa_sh-3/textures/
LiveryTexture=spa_sh-3_tx_1.png
SpecularTexture=usn_sh-3h_spec.png
NormalTexture=usn_sh-3h_nm_blur.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_spain
# nations are referenced in the layout.ini file:
Nation=Spain
ServiceDate=1987|2016