# ver. 20260510
#
[General]
SerialnumberReferences=Modex
EmblemReference=CarrierName
NationFlagReference=Flag1
NumberOfSquadrons=1

[Default]
ResourcesSerialnumberFolder=aircraft/spa_av-8a/modex/
SerialNumberPrefix=
SerialnumberTextures=01814.png
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/spa_av-8a/textures/
LiveryTexture=spa_av-8a_tx.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_spain
# nations are referenced in the layout.ini file:
Nation=Spain
ServiceDate=1976|1990

[Squadron1]
ResourcesSerialnumberFolder=aircraft/spa_av-8a/modex/
SerialNumberPrefix=
SerialnumberTextures=01814.png
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/spa_av-8a/textures/
LiveryTexture=spa_av-8a_tx.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_spain
# nations are referenced in the layout.ini file:
Nation=Spain