#!alias aircraft/usmc_ah-1t.ini
# Modificado loadouts para eliminar aim-9 Sidewinder y Tows
# Falta nuevo obj minigun 7.62mm + lanzagranadas 40mm
# Pendiente verificar 20mm pod M35 y 7.62mm pod M18
# ver. 20260805
#
[General]
Length=16.20							// In meters - with the rotors running
# GroundPivot=0.03,-0.0197,0.02 		// Defines the relative location of the landing gear
OnDeckPositionOffset=0.013,0,-0.035

[Physics]
MaxSpeedAtSeaLevel=14					// In knots
Ceiling=11400							// Ceiling in feet
EmptyMass=2630							// In kg

[WeaponSystems]
AvailableLoadouts=CAS,AntiArmor

[WeaponSystem1Default]
SubModelsToHide=Rails,TOW_outer_left,TOW_outer_right
Station1=usn_lau-68
Station2=usn_lau-68
Station3=usn_lau-10a|LAU-10
Station4=usn_lau-10a|LAU-10

[WeaponSystem1AntiArmor]
SubModelsToHide=Rails,TOW_outer_left,TOW_outer_right
Station1=usn_lau-10a|LAU-10
Station2=usn_lau-10a|LAU-10
Station3=usn_lau-10a|LAU-10
Station4=usn_lau-10a|LAU-10

[Submodels]
General_4=Modex

[Modex]
ResourcesMeshFolder=aircraft/spa_ah-1g/
RootMesh=spa_ah-1g_modex.obj
Mesh=Modex
ResourcesMaterialFolder=aircraft/materials/numbers/
Material=numbers
