[AmmunitionNames]
# ------------------ AAM ------------------
=

# ------------------ SAM ------------------

# ---------- Anti-radar Missiles ---------

# ---------- Anti-ship Missiles ----------

#-----------Land Strike only missiles---------

# ---------- Anti-sub  Missilies ----------

wp_9m17m=9M17M,方阵M,对地攻击,

# ------------------ RBU ------------------

# --------------- Torpedoes ---------------

# ------------------ Bombs -----------------

# ---------------- Sonobuoys ---------------

# ------------------ FFAR -----------------

=

# ------------------ MLRS -----------------

# ------------------ Guns -----------------

# ------------------ CIWS -----------------

wp_cal_12.7mm=12.7重机枪,,

# ----------- Noisemakers/Chaff -----------

# ----------------- Decoys ----------------

# ----------------- Special ----------------

# Depth charge

# ----------------- Fueltanks ----------------


