#!extend language_en/ui.ini, language_de/ui.ini, language_cn/ui.ini, language_es/ui.ini, language_fr/ui.ini, language_ja/ui.ini, language_ko/ui.ini, language_ru/ui.ini, language_vn/ui.ini

[MidCourseCorrection]
SATCOM=Satellite communication (SATCOM)