[ ========================================= General ========================================== ]
[General]
DataLinkUpdateRate=1             // every x seconds there will be an update for the overall sensor image for the minimap
PassiveSensorUpdateRate=1.0        // every x seconds the passive contacts will be re-evaluated
LostPassiveContactTimeToDisable=5  // time in seconds after which a lost passive contact bearing line will be greyed out
LostContactTimeToRemove=30         // time in seconds after which a lost contact will be removed from the map

[ ---------------------------- Surface Search Radar ----------------------------- ]

[ ---------------------------- Sonars ----------------------------- ]
[BQQ-10]
#Users: usn_ssn_virginia, usn_ssn_seawolf
Kind=Sonar
HasDataLink=False       // true means the sensor data will be used for the entire task force via data link, false local use only
AngularResolution=2.0   // TODO in degrees
RangeResolution=50.0   // TODO defines the minimum range where two targets behind can be recognized as two; in meters
ActiveRange=56          // in km
PassiveRange=180         // in km
ActiveGain=45
Gain=50                 // in db, gain of the sensor
OutputPower=235         // Active sensor output power in dB, unused for passive ones
Type=Hull				//Hull: hull mounted sonar, Towed: towed passive sonar, VDS: variable depth active sonar, Dipping: dipping sonar
SonarFrequency=LF
IsTowedSonar=False
ModuleType=SonarSensor

[BQG-5A]
#Users: usn_ssn_virginia, usn_ssn_seawolf
Kind=Sonar
HasDataLink=False       // true means the sensor data will be used for the entire task force via data link, false local use only
AngularResolution=4.0   // TODO in degrees
RangeResolution=600.0   // TODO defines the minimum range where two targets behind can be recognized as two; in meters
PassiveRange=180         // in km
PseudorangeResolution=15.0 // relative, default is 1.0, smaller is better
Gain=56                 // in db, gain of the sensor
OutputPower=235         // Active sensor output power in dB, unused for passive ones
Type=Hull				//Hull: hull mounted sonar, Towed: towed passive sonar, VDS: variable depth active sonar, Dipping: dipping sonar
SonarFrequency=LF
IsTowedSonar=False
ModuleType=SonarSensor

[TB-29]
#Users: usn_ssn_virginia, usn_ssn_seawolf
Kind=Sonar
HasDataLink=False        // true means the sensor data will be used for the entire task force via data link, false local use only
AngularResolution=3.0    // in degrees
RangeResolution=100.0    // TODO defines the minimum range where two targets behind can be recognized as two; in meters
PassiveRange=40          // in km
Gain=48                  // in db, gain of the sensor
Type=Towed               //Hull: hull mounted sonar, Towed: towed passive sonar, VDS: variable depth active sonar, Dipping: dipping sonar
SonarFrequency=LF 
ModuleType=SonarSensor

[TB-29A]
#Users: 00s virginia and seawolf
Kind=Sonar
HasDataLink=False        // true means the sensor data will be used for the entire task force via data link, false local use only
AngularResolution=23    // in degrees
RangeResolution=2750.0    // TODO defines the minimum range where two targets behind can be recognized as two; in meters
PseudorangeResolution=30.0 // relative, default is 1.0, smaller is better
PassiveRange=270          // in km
Gain=64                  // in db, gain of the sensor
Type=Towed               //Hull: hull mounted sonar, Towed: towed passive sonar, VDS: variable depth active sonar, Dipping: dipping sonar
SonarFrequency=LF 
ModuleType=SonarSensor

[TB-34] #BSY-2
#Users: seawolf and virginia post 2007
Kind=Sonar
HasDataLink=False        // true means the sensor data will be used for the entire task force via data link, false local use only
AngularResolution=11    // in degrees
RangeResolution=600.0    // TODO defines the minimum range where two targets behind can be recognized as two; in meters
PseudorangeResolution=12.0 // relative, default is 1.0, smaller is better
PassiveRange=185          // in km
Gain=56                  // in db, gain of the sensor
Type=Towed               //Hull: hull mounted sonar, Towed: towed passive sonar, VDS: variable depth active sonar, Dipping: dipping sonar
SonarFrequency=LF 
ModuleType=SonarSensor

[BPS-16] #LPI mode
Kind=Radar
Type=Search            // Classes can be "Search", "Targeting"
HasDataLink=True       // true means the sensor data will be used for the entire task force via data link, false local use only
Role=AirAndSurface           // Role can be "Surface", "Air", "AirAndSurface"
Mode=Illuminate        // Can be "Illuminate", "RadioCommand"
TargetChannels=1       // if applicable number of targets it can track simultaneously
WeaponChannels=1       // if applicable number of weapons (missiles) it can guide simultaneously
RotationDirection=1    // -1 means left, 1 means right
RPM=10                 // revolutions per minute
MinRange=0.2           // min range in km
MaxRange=80.0          // max range in km
MinAltitude=0          // min altitude in meters, relevant for air, unused for surface
MaxAltitude=500          // max altitude in meters, relevant for air, unused for surface
RangeResolution=30.0  // defines the minimum range where two targets behind can be recognized as two; in meters
BeamWidth=1            // defines the beam width in degrees for BearingResolution >= 2*Dist*sin(BeamWidth/2)
Gain=90.0              // gain in dB on the sensor
Frequency=Ka-Band       // frequency band
PeakPower=0.00001         // output peak power in kW
ModuleType=SmallSensor

[ROV_Dummy] #ROV Dummy
#Users: Jimmy Carter
Kind=Sonar
HasDataLink=False        // true means the sensor data will be used for the entire task force via data link, false local use only
AngularResolution=11     // in degrees
RangeResolution=600.0    // TODO defines the minimum range where two targets behind can be recognized as two; in meters
PassiveRange=0           // in km
Gain=0                   // in db, gain of the sensor
Type=Towed               //Hull: hull mounted sonar, Towed: towed passive sonar, VDS: variable depth active sonar, Dipping: dipping sonar
SonarFrequency=MF 
ModuleType=SonarSensor

[---------- Visual ----------]
[Optitronics_FLIR_Mast]
#00s/10s FLIR mast for submarines
Kind=Visual
#Infrared
UseIRValues=True                 // Affects only Encyclopedia. For correct type display
VIDRangeMultiplier=5.0           // Target VID range multiplied by this for identification check
MaxRangeMultiplier=8.0           // Target VID range multiplied by this for detection check. Can not be less then VID multiplier
LookDownMultiplier=0.9          // Final VID/Detection range is multiplied by this in case when target observed on surface background

[FLIR_Periscope]
#80s/90s FLIR mast for submarines
Kind=Visual
#Infrared
UseIRValues=True                 // Affects only Encyclopedia. For correct type display
VIDRangeMultiplier=3.5           // Target VID range multiplied by this for identification check
MaxRangeMultiplier=5.0           // Target VID range multiplied by this for detection check. Can not be less then VID multiplier
LookDownMultiplier=0.9          // Final VID/Detection range is multiplied by this in case when target observed on surface background

[---------- ESM ----------]
[AN/BLQ-10]
#seawolf and virginia
Kind=ESM
Gain=24                              //gain of sensor in dB
HasDataLink=True                    // true means the sensor data will be used for the entire task force via data link, false local use only
AngularResolution=1.5              // in degrees
Frequencies=VHF-Band,UHF-Band,L-Band,S-Band,C-Band,X-Band,Ku-Band,K-Band,Ka-Band                     //Frequencies that current ESM system can detect
#Frequencies=VHF-Band,UHF-Band,L-Band,S-Band,C-Band,X-Band,Ku-Band,K-Band
OverHorizonMultiplier=18           // The multiplier for ESM horizon for over horison (OTH) passive detection capability
IdentificationRate=1.4
ModuleType=SmallSensor