[General]
DisplayName=AN/AAS-38 Wide
OverlayTexture=ui/hud/eo_station_aircraft_modern_wide
FOVs=12.0
Labels=EO WIDE
RotationDamping=0.35,0.15
; PostProcessFilters=ROS - TV,ROS - WHOT,ROS - BHOT,LLLTV
; DefaultFilter=ROS - TV
PostProcessFilters=ROS - TV,ROS - BHOT,ROS - WHOT
DefaultFilter=ROS - BHOT
AllowFilterCycle=True
