[General]
DisplayName=AN/AVQ-23 Narrow
OverlayTexture=ui/hud/eo_station_pave_spike_narrow.png
FOVs=5.0
Labels= 
RotationDamping=0.35,0.15
; PostProcessFilters=ROS - TV,ROS - WHOT,ROS - BHOT,LLLTV
; DefaultFilter=ROS - TV
PostProcessFilters=LLLTV
DefaultFilter=LLLTV
; AllowFilterCycle=True
