[Animations]
NumberOfAnimations=10

Animation1=Canopy_Extend
Animation2=Canopy_Retract
Animation3=Flaps_Takeoff
Animation4=Flaps_Takeoff_Retract
Animation5=Flaps_Landing
Animation6=Flaps_Landing_Retract
Animation7=Gear_Extend
Animation8=Gear_Retract
Animation9=Hook_Deploy
Animation10=Hook_Retrieve





[Canopy_Extend]
NumberOfSequencesToPlay=1
Sequence1=Canopy_Open
Sequence1_Model=hatch

[Canopy_Retract]
NumberOfSequencesToPlay=1
Sequence1=Canopy_Close
Sequence1_Model=hatch

[Flaps_Takeoff]
NumberOfSequencesToPlay=2
Sequence1=Flap_Takeoff
Sequence1_Model=flap_l
Sequence2=Flap_Takeoff
Sequence2_Model=flap_r

[Flaps_Takeoff_Retract]
NumberOfSequencesToPlay=2
Sequence1=Flap_Takeoff_Retract
Sequence1_Model=flap_l
Sequence2=Flap_Takeoff_Retract
Sequence2_Model=flap_r

[Flaps_Landing]
NumberOfSequencesToPlay=2
Sequence1=Flap_Landing
Sequence1_Model=flap_l
Sequence2=Flap_Landing
Sequence2_Model=flap_r

[Flaps_Landing_Retract]
NumberOfSequencesToPlay=2
Sequence1=Flap_Landing_Retract
Sequence1_Model=flap_l
Sequence2=Flap_Landing_Retract
Sequence2_Model=flap_r


[Gear_Extend]
NumberOfSequencesToPlay=26
#---------- Nose Gear ----------
Sequence1=nose_gear_up_Down
Sequence1_Model=nose_gear_up
Sequence2=nose_gear_down_Down
Sequence2_Model=nose_gear_down
Sequence3=nose_hatch_for_Down
Sequence3_Model=nose_hatch_for
Sequence4=nose_hatch_right_Down
Sequence4_Model=nose_hatch_right
Sequence5=nose_hatch_left_Down
Sequence5_Model=nose_hatch_left
Sequence6=nose_rod_Down
Sequence6_Model=nose_rod
#---------- Left Gear ----------
Sequence7=left_gear_Down
Sequence7_Model=left_gear
Sequence8=left_hatch_aft_Down
Sequence8_Model=left_hatch_aft
Sequence9=left_hatch_mid_Down
Sequence9_Model=left_hatch_mid
Sequence10=left_hatch_for_Down
Sequence10_Model=left_hatch_for
#---------- Right Gear ----------
Sequence11=right_gear_Down
Sequence11_Model=right_gear
Sequence12=right_hatch_aft_Down
Sequence12_Model=right_hatch_aft
Sequence13=right_hatch_mid_Down
Sequence13_Model=right_hatch_mid
Sequence14=right_hatch_for_Down
Sequence14_Model=right_hatch_for
#---------- Air Inlet ----------
Sequence15=air_main_Down
Sequence15_Model=left_air_main
Sequence16=air_main_Down
Sequence16_Model=right_air_main
Sequence17=air_Down
Sequence17_Model=left_air_1
Sequence18=air_Down
Sequence18_Model=right_air_1
Sequence19=air_Down
Sequence19_Model=left_air_2
Sequence20=air_Down
Sequence20_Model=right_air_2
Sequence21=air_Down
Sequence21_Model=left_air_3
Sequence22=air_Down
Sequence22_Model=right_air_3
Sequence23=air_Down
Sequence23_Model=left_air_4
Sequence24=air_Down
Sequence24_Model=right_air_4
Sequence25=air_Down
Sequence25_Model=left_air_5
Sequence26=air_Down
Sequence26_Model=right_air_5




[Gear_Retract]
NumberOfSequencesToPlay=26
#---------- Nose Gear ----------
Sequence1=nose_gear_up_Up
Sequence1_Model=nose_gear_up
Sequence2=nose_gear_down_Up
Sequence2_Model=nose_gear_down
Sequence3=nose_hatch_for_Up
Sequence3_Model=nose_hatch_for
Sequence4=nose_hatch_right_Up
Sequence4_Model=nose_hatch_right
Sequence5=nose_hatch_left_Up
Sequence5_Model=nose_hatch_left
Sequence6=nose_rod_Up
Sequence6_Model=nose_rod
#---------- Left Gear ----------
Sequence7=left_gear_Up
Sequence7_Model=left_gear
Sequence8=left_hatch_aft_Up
Sequence8_Model=left_hatch_aft
Sequence9=left_hatch_mid_Up
Sequence9_Model=left_hatch_mid
Sequence10=left_hatch_for_Up
Sequence10_Model=left_hatch_for
#---------- Right Gear ----------
Sequence11=right_gear_Up
Sequence11_Model=right_gear
Sequence12=right_hatch_aft_Up
Sequence12_Model=right_hatch_aft
Sequence13=right_hatch_mid_Up
Sequence13_Model=right_hatch_mid
Sequence14=right_hatch_for_Up
Sequence14_Model=right_hatch_for
#---------- Air Inlet ----------
Sequence15=air_main_Up
Sequence15_Model=left_air_main
Sequence16=air_main_Up
Sequence16_Model=right_air_main
Sequence17=air_Up
Sequence17_Model=left_air_1
Sequence18=air_Up
Sequence18_Model=right_air_1
Sequence19=air_Up
Sequence19_Model=left_air_2
Sequence20=air_Up
Sequence20_Model=right_air_2
Sequence21=air_Up
Sequence21_Model=left_air_3
Sequence22=air_Up
Sequence22_Model=right_air_3
Sequence23=air_Up
Sequence23_Model=left_air_4
Sequence24=air_Up
Sequence24_Model=right_air_4
Sequence25=air_Up
Sequence25_Model=left_air_5
Sequence26=air_Up
Sequence26_Model=right_air_5


[Canopy_Open]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=5 
RotationX2=-30
Smoothness2=EaseInOut

[Canopy_Close]
NumberOfSteps=2
Time1=0 
RotationX1=-30
Smoothness1=EaseInOut
Time2=5 
RotationX2=0
Smoothness2=EaseInOut

[Flap_Takeoff]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=1
RotationX2=-10
Smoothness2=EaseInOut

[Flap_Takeoff_Retract]
NumberOfSteps=2
Time1=0 
RotationX1=-10	
Smoothness1=EaseInOut
Time2=1 
RotationX2=0
Smoothness2=EaseInOut

[Flap_Landing]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=2
RotationX2=-20
Smoothness2=EaseInOut

[Flap_Landing_Retract]
NumberOfSteps=2
Time1=0 
RotationX1=-20	
Smoothness1=EaseInOut
Time2=2 
RotationX2=0
Smoothness2=EaseInOut

[nose_gear_up_Down]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=6
RotationX2=-80
Smoothness2=EaseInOut

[nose_gear_up_Up]
NumberOfSteps=2
Time1=0 
RotationX1=-80
Smoothness1=EaseInOut
Time2=6 
RotationX2=0
Smoothness2=EaseInOut

[nose_gear_down_Down]
NumberOfSteps=2
Time1=2 
RotationX1=0
Smoothness1=EaseInOut
Time2=6
RotationX2=-40
Smoothness2=EaseInOut

[nose_gear_down_Up]
NumberOfSteps=2
Time1=0 
RotationX1=-40
Smoothness1=EaseInOut
Time2=4 
RotationX2=0
Smoothness2=EaseInOut

[nose_hatch_for_Down]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=6
RotationX2=-25.5
Smoothness2=EaseInOut

[nose_hatch_for_Up]
NumberOfSteps=2
Time1=0 
RotationX1=-25.5
Smoothness1=EaseInOut
Time2=6 
RotationX2=0
Smoothness2=EaseInOut

[nose_rod_Down]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=6
RotationX2=56
Smoothness2=EaseInOut

[nose_rod_Up]
NumberOfSteps=2
Time1=0 
RotationX1=56
Smoothness1=EaseInOut
Time2=6 
RotationX2=0
Smoothness2=EaseInOut

[nose_hatch_right_Down]
NumberOfSteps=2
Time1=0
RotationZ1=0
Smoothness1=EaseInOut
Time2=3
RotationZ2=70.97
Smoothness2=EaseInOut

[nose_hatch_right_Up]
NumberOfSteps=2
Time1=4 
RotationZ1=70.97
Smoothness1=EaseInOut
Time2=7 
RotationZ2=0
Smoothness2=EaseInOut

[nose_hatch_left_Down]
NumberOfSteps=2
Time1=0
RotationZ1=0
Smoothness1=EaseInOut
Time2=3
RotationZ2=-70.0942
Smoothness2=EaseInOut

[nose_hatch_left_Up]
NumberOfSteps=2
Time1=4
RotationZ1=-70.0942
Smoothness1=EaseInOut
Time2=7
RotationZ2=0
Smoothness2=EaseInOut

[left_gear_Down]
NumberOfSteps=2
Time1=2
RotationX1=0
RotationY1=0
RotationZ1=0
Smoothness1=EaseInOut
Time2=6
RotationX2=86.83
RotationY2=-84.74
RotationZ2=0.241749
Smoothness2=EaseInOut

[left_gear_Up]
NumberOfSteps=2
Time1=0 
RotationX1=86.83
RotationY1=-84.74
RotationZ1=0.241749
Smoothness1=EaseInOut
Time2=4
RotationX2=0
RotationY2=0
RotationZ2=0
Smoothness2=EaseInOut

[left_hatch_aft_Down]
NumberOfSteps=2
Time1=0
RotationX1=0
Smoothness1=EaseInOut
Time2=6
RotationX2=22
Smoothness2=EaseInOut

[left_hatch_aft_Up]
NumberOfSteps=2
Time1=0 
RotationX1=22
Smoothness1=EaseInOut
Time2=6
RotationX2=0
Smoothness2=EaseInOut

[left_hatch_mid_Down]
NumberOfSteps=2
Time1=0
RotationZ1=0
Smoothness1=EaseInOut
Time2=3
RotationZ2=-70.0942
Smoothness2=EaseInOut

[left_hatch_mid_Up]
NumberOfSteps=2
Time1=3
RotationZ1=-70.0942
Smoothness1=EaseInOut
Time2=6
RotationZ2=0
Smoothness2=EaseInOut

[left_hatch_for_Down]
NumberOfSteps=2
Time1=0
RotationZ1=0
Smoothness1=EaseInOut
Time2=4
RotationZ2=140
Smoothness2=EaseInOut

[left_hatch_for_Up]
NumberOfSteps=2
Time1=2 
RotationZ1=140
Smoothness1=EaseInOut
Time2=6
RotationZ2=0
Smoothness2=EaseInOut

[right_gear_Down]
NumberOfSteps=2
Time1=2
RotationX1=0
RotationY1=0
RotationZ1=0
Smoothness1=EaseInOut
Time2=6
RotationX2=86.83
RotationY2=84.74
RotationZ2=0.241749
Smoothness2=EaseInOut

[right_gear_Up]
NumberOfSteps=2
Time1=0 
RotationX1=86.83
RotationY1=84.74
RotationZ1=0.241749
Smoothness1=EaseInOut
Time2=4
RotationX2=0
RotationY2=0
RotationZ2=0
Smoothness2=EaseInOut

[right_hatch_aft_Down]
NumberOfSteps=2
Time1=0
RotationX1=0
Smoothness1=EaseInOut
Time2=6
RotationX2=22
Smoothness2=EaseInOut

[right_hatch_aft_Up]
NumberOfSteps=2
Time1=0 
RotationX1=22
Smoothness1=EaseInOut
Time2=6
RotationX2=0
Smoothness2=EaseInOut

[right_hatch_mid_Down]
NumberOfSteps=2
Time1=0
RotationZ1=0
Smoothness1=EaseInOut
Time2=4
RotationZ2=70.0942
Smoothness2=EaseInOut

[right_hatch_mid_Up]
NumberOfSteps=2
Time1=2 
RotationZ1=70.0942
Smoothness1=EaseInOut
Time2=6 
RotationZ2=0
Smoothness2=EaseInOut

[right_hatch_for_Down]
NumberOfSteps=2
Time1=0
RotationZ1=0
Smoothness1=EaseInOut
Time2=4
RotationZ2=-140
Smoothness2=EaseInOut

[right_hatch_for_Up]
NumberOfSteps=2
Time1=2
RotationZ1=-140
Smoothness1=EaseInOut
Time2=6
RotationZ2=0
Smoothness2=EaseInOut

[air_main_Down]
NumberOfSteps=2
Time1=0 
RotationX1=39
Smoothness1=EaseInOut
Time2=4
RotationX2=0
Smoothness2=EaseInOut

[air_main_Up]
NumberOfSteps=2
Time1=0 
RotationX1=0	
Smoothness1=EaseInOut
Time2=4 
RotationX2=39
Smoothness2=EaseInOut

[air_Down]
NumberOfSteps=2
Time1=0 
RotationX1=20
Smoothness1=EaseInOut
Time2=2
RotationX2=0
Smoothness2=EaseInOut

[air_Up]
NumberOfSteps=2
Time1=4 
RotationX1=0	
Smoothness1=EaseInOut
Time2=6 
RotationX2=20
Smoothness2=EaseInOut