[General]
SerialnumberReferences=
EmblemReference=Emblem
NationFlagReference=Flag19
NumberOfSquadrons=2

[Default]
Nation=UK
ServiceDate=2015|2022

[Squadron1] #845 Naval Air Squadron
ResourcesSerialnumberFolder=/aircraft/materials/numbers/
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=
LiveryTexture=
ResourcesFlagFolder=
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=UK
ServiceDate=2015|2022

[Squadron2] #846 Naval Air Squadron
ResourcesSerialnumberFolder=/aircraft/materials/numbers/
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=
LiveryTexture=
ResourcesFlagFolder=
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=UK
ServiceDate=2015|2022