[General]
SerialnumberReferences=
EmblemReference=Emblem
NationFlagReference=Flag19
NumberOfSquadrons=7

[Default]
Nation=UK
ServiceDate=1980|2008

[Squadron1] #651 Squadron
ResourcesSerialnumberFolder=/aircraft/materials/numbers/
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=
LiveryTexture=
ResourcesFlagFolder=
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=UK
ServiceDate=1990|2008

[Squadron2] #655 Squadron
ResourcesSerialnumberFolder=/aircraft/materials/numbers/
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=
LiveryTexture=
ResourcesFlagFolder=
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=UK
ServiceDate=1991|2007

[Squadron3] #656 Squadron
ResourcesSerialnumberFolder=/aircraft/materials/numbers/
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=
LiveryTexture=
ResourcesFlagFolder=
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=UK
ServiceDate=1985|2004

[Squadron4] #661 Squadron
ResourcesSerialnumberFolder=/aircraft/materials/numbers/
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=
LiveryTexture=
ResourcesFlagFolder=
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=UK
ServiceDate=1993|2005

[Squadron5] #662 Squadron
ResourcesSerialnumberFolder=/aircraft/materials/numbers/
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=
LiveryTexture=
ResourcesFlagFolder=
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=UK
ServiceDate=1980|2004

[Squadron6] #672 Squadron
ResourcesSerialnumberFolder=/aircraft/materials/numbers/
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=
LiveryTexture=
ResourcesFlagFolder=
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=UK
ServiceDate=2001|2004

[Squadron7] #847 Squadron (Royal Marines)
ResourcesSerialnumberFolder=/aircraft/materials/numbers/
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=
LiveryTexture=
ResourcesFlagFolder=
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=UK
ServiceDate=1995|2012