[General]
SerialnumberReferences=Modex
EmblemReference=Emblem
NationFlagReference=Flag19
NumberOfSquadrons=2

[Default]
Nation=UK
ServiceDate=1981|2017

[Squadron1] #815 Squadron
ResourcesSerialnumberFolder=/aircraft/materials/numbers/
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=
LiveryTexture=
ResourcesFlagFolder=
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=UK
ServiceDate=1981|2017

