# animations_ae_lpd_galicia.ini
# ver. 20260417
#

[Animations]
NumberOfAnimations=2
Animation1=HangarOpenAnim
Animation2=HangarCloseAnim

# --- DEFINICION DE ANIMACIONES ---

[HangarOpenAnim]
NumberOfSequencesToPlay=2
Sequence1=HangarOpenL_Seq
Sequence1_Model=Hangar_door_inner_left
Sequence2=HangarOpenR_Seq
Sequence2_Model=Hangar_door_inner_right

[HangarCloseAnim]
NumberOfSequencesToPlay=2
Sequence1=HangarCloseL_Seq
Sequence1_Model=Hangar_door_inner_left
Sequence2=HangarCloseR_Seq
Sequence2_Model=Hangar_door_inner_right

# --- SECUENCIAS HANGAR OPEN (Eje Y Vertical) ---

[HangarOpenL_Seq]
NumberOfSteps=2
Time1=0
PositionX1=0
Time2=9
PositionX2=-0.055
Smoothness2=Linear

[HangarOpenR_Seq]
NumberOfSteps=2
Time1=0
PositionX1=0
Time2=9
PositionX2=0.055
Smoothness2=Linear

# --- SECUENCIAS HANGAR CLOSE ---

[HangarCloseL_Seq]
NumberOfSteps=2
Time1=0
PositionX1=-0.055
Time2=9
PositionX2=0
Smoothness2=Linear

[HangarCloseR_Seq]
NumberOfSteps=2
Time1=0
PositionX1=0.055
Time2=9
PositionX2=0
Smoothness2=Linear
