# ver. 20260803
#
[ae_ffg_alvaro_bazan]
Type=FFG,Fragata
Default=Clase Alvaro de Bazan (Inicial),F-100
DefaultDescription=La clase F-100 es el primer buque europeo en utilizar el Sistema de Combate Aegis.\n\nDiseñada como una potente plataforma multipropósito, su principal fortaleza reside en sus avanzadas capacidades de guerra antiaérea, proporcionadas por el radar SPY-1D y los sistemas de lanzamiento vertical (VLS).\n\nEstas fragatas de fabricación española ofrecen una formidable defensa de área para los grupos de ataque de portaaviones, manteniendo al mismo tiempo una sólida letalidad antisubmarina y antisuperficie.\n\nCon base en Ferrol.
Variant1=F101 Alvaro de Bazan,Bazan
Variant2=F102 Almirante Juan de Borbon,Borbon
Variant3=F103 Blas de Lezo,Lezo
Variant4=F104 Mendez Nuñez,Mendez Nuñez

[ae_ffg_bonifaz]
Type=FFG,Fragata
Default=Clase Bonifaz,F-110
DefaultDescription=La fragata de clase F-110 Bonifaz es una plataforma multimisión de última generación optimizada para la guerra antisubmarina (ASW) y operaciones en entornos de alta intensidad.\n\nCuenta con un mástil integrado avanzado que alberga radares AESA (escaneo electrónico activo), una bahía multimisión flexible para el despliegue de sistemas no tripulados y un sistema de combate nacional SCOMBA integrado con la suite estadounidense AEGIS.\n\nCon base en Ferrol.
Variant1=F111 Bonifaz,F111 Bonifaz
Variant2=F112 Roger de Lauria,F112 Lauria
Variant3=F113 Menendez de Avilés,F113 Avilés
Variant4=F114 Luis de Cordova,F114 Cordova
Variant5=F115 Barceló,F115 Barceló

[ae_ffg_cristobal_colon]
Type=FFG,Fragata
Default=Clase Alvaro de Bazan-class (Modernizada),F-105
DefaultDescription=La F-105 Cristóbal Colón incorpora motores LM2500+G4 mejorados para mayor potencia y un sistema Aegis Baseline 7 optimizado.\n\nAdemás, integra un mástil pesado rediseñado para una mayor discreción y un nuevo puente de mando para mejorar la coordinación de la flota en comparación con las unidades F-101 a F-104 anteriores.\n\nCon base en Ferrol.
Variant1=F105 Cristobal Colon,Colon

[ae_lhd_juan_carlos]
Type=LHD,Buque Anfibio Portaeronaves
Default=Clase Juan Carlos I,Juan Carlos I
DefaultDescription=Diseñado como un buque de asalto anfibio multipropósito y portaaviones para proyectar poder y proporcionar apoyo aéreo a la Armada Española.\n\nCuenta con una cubierta de vuelo continua con un ski-jump de 12 grados, optimizada para operaciones STOVL con el AV-8B Harrier II y el F-35B, además de una gran capacidad para helicópteros. También dispone de una cubierta de dique inundable capaz de desplegar lanchas de desembarco y equipos mecanizados.\n\nEquipado con amplias instalaciones médicas y centros de mando, el buque es altamente versátil, capaz de actuar como buque insignia alternativo, apoyar la ayuda humanitaria y liderar fuerzas de tarea multinacionales.\n\nCon base en Rota.
Variant1=L61 Juan Carlos I,Juan Carlos I

[ae_lpd_galicia]
Type=LPD,Buque de Desembarco Anfibio
Default=Clase Galicia,Galicia
DefaultDescription=Originalmente concebido como un proyecto nacional por los Países Bajos, en 1990 el ATS se consideró una posible solución para satisfacer las necesidades españolas de un nuevo LPD.\n\nCapaz de transportar un batallón de infantes de marina completamente equipado, cuenta con un dique integrado para lanchas de desembarco y una plataforma de vuelo para helicópteros para el desembarco en alta mar.\n\nEl L52 Castilla dispone de instalaciones de mando y control mejoradas con dos centros de operaciones, uno para operaciones anfibias y otro para un grupo de combate.\n\nTambién puede utilizarse para apoyo logístico general en operaciones militares y civiles, incluyendo tareas medioambientales y de ayuda en casos de desastre.\n\nCon base en Rota.
Variant1=L51 Galicia,Galicia
Variant2=L52 Castilla,Castilla

[ae_opv_meteoro]
Type=OPV,Patrullero oceánico
Default=Clase Meteoro,BAM
DefaultDescription=Desarrollado por Navantia como una solución altamente versátil y rentable para la acción marítima. Diseñado para conflictos de baja intensidad, lucha contra la piratería y operaciones humanitarias en aguas abiertas.\n\nCuenta con un alto grado de automatización que permite una dotación drásticamente reducida. Equipado con una cubierta de vuelo para helicópteros y un hangar capaz de operar un NH90, además de rampas de lanzamiento rápido para dos embarcaciones semirrígidas para intercepción rápida.\n\nOptimizado para patrullas oceánicas de gran autonomía, protección medioambiental y misiones de búsqueda y rescate. Puede adaptarse fácilmente con contenedores de misión modulares para apoyo logístico especializado y asistencia médica.\n\nCon base en Las Palmas y Cartagena.
Variant1=P41 Meteoro,Meteoro
Variant2=P42 Rayo,Rayo
Variant3=P43 Relámpago,Relámpago
Variant4=P44 Tornado,Tornado
Variant5=P45 Audaz,Audaz
Variant6=P46 Furor,Furor

[ae_ssk_s80]
Type=SSK,Submarino de Patrulla
Default=Clase S-80,S-80
DefaultDescription=El S-80 en su versión inicial representa las primeras unidades basadas en la clase Scorpene francesa construidas con el casco alargado a 80,8 metros pero sin el módulo AIP instalado en origen (preparados para su integración posterior).\n\nAunque comparte el volumen, baja firma acústica y sistemas de combate automatizados de la variante Plus, depende únicamente de propulsión diésel-eléctrica convencional, requiriendo periodos periódicos de snorkel para recargar sus baterías.\n\nCon base en Cartagena.
Variant1=S81 Isaac Peral (Inicial),S81 Peral				// 2023-2034
Variant2=S82 Narciso Monturiol (Inicial),S82 Monturiol		// 2026-2035

[ae_ssk_s80_plus]
Type=SSK,Submarino de Patrulla
Default=Clase S-80 Plus,S-80 Plus
DefaultDescription=La clase S-80 Plus (clase Isaac Peral) comprende avanzados submarinos de ataque convencionales oceánicos construidos por Navantia para la Armada Española.\n\nCon un casco ampliado a 80,8 metros, esta versión integra el sistema BEST-AIP (por bioetanol) para operar sumergido hasta tres semanas sin usar snorkel. Altamente automatizado, cuenta con sensores de última generación, torpedos pesados DM2A4 y capacidad para proyectar armamento táctico como misiles antibuque NSM-SL o de crucero Tomahawk.\n\nCon base en Cartagena.
Variant1=S81 Isaac Peral (Modernizado),S81 Peral			// 2035-2050
Variant2=S82 Narciso Monturiol (Modernizado),S82 Monturiol	// 2036-2050
Variant3=S83 Cosme Garcia,S83 C.García						// 2029-2050
Variant4=S84 Mateo Garcia de los Reyes,S84 M.García 		// 2034-2050