[SystemNames]
#======================================== Italy ========================================
#---------------------------------------- Visual ----------------------------------------
3JB10=3JB10|The 3JB10 is an anti-air TV targeting system.

#---------------------------------------- Radar ----------------------------------------
#----Air/Air&Surface----
Argos_5000D=Argos 5000D|The Argos 5000 is a long-range air surveillance radar and one of the earliest domestic radars produced in Italy. Due to its enormous size and high operating power requirement the sole example of this radar was mounted on the converted guided missile cruiser Giuseppe Garibaldi. 
SPS-768=MM/SPS-768|The MM/SPS-768 is an Italian long-range air search radar with modern solid-state electronics and fully digital processing capability. It was first introduced in the late 1960s and is in use on the largest surface combattants of the Italian navy.
SPS-774=MM/SPS-774|The MM/SPS-774 is an Italian medium-range combined air and surface search radar designed for use on frigate- and corvette-sized ships. It is a fully digital system with modern solid-state electronics which was first introduced in the mid 1970s.
mm_empar=EMPAR|The EMPAR is a modern air-search radar.

#----Surface only----
CFL-3_C25=CFL-3 C25|The CFL-3 C25 is an Italian navigation radar and one of the earliest domestic radars produced in Italy by the electronics company 'Selenia' in the 1950s, paving the way for the company to become one of the most important players in the Italian radar technology sector. 
SPQ-2=MM/SPQ-2|The MM/SPQ-2 is one of the earliest domestic Italian surface search radars mounted on a majority of the Marina Militares surface combattants throughout the 1950s and 1960s, often replacing older systems previously provided by the United States.
SPQ-701=MM/SPQ-701|The MM/SPQ-701 is an Italian navigation radar.
SPS-702=MM/SPS-702|The MM/SPS-702 is an Italian combined surface and low-altitude air search radar with an integrated IFF system. It is the successor of the MM/SPQ-2 and has been mounted on the majority of Italian navy surface combattants throughout the 1970s and 1980s.
SPN-703=MM/SPN-703|The MM/SPN-703 is an Italian navigation radar.
SPN-748=MM/SPN-748|The MM/SPN-748 is an Italian navigation radar used on a large number of Marina Militare surface vessels since the 1980s.
BPS-704=MM/BPS-704|The MM/BPS-704 is an Italian surface search radar designed specifically for the use on submarines.

#----Fire Control----
MLT-4=MLT-4|The MLT-4 is an Italian license-produced version of the US-made Mk. 39 fire control radar used on the Mk. 57 heavy anit-air gun director. Experience gained from manufacturing this radar would later allow Italy to develop its renowned 'Orion' series fire control radars in the 1960s.
RTN-1A=RTN-1A|The RTN-1A is the earliest member of the Italian 'Orion' fire control radar family. On board the guided missile cruiser Giuseppe Garibaldi it works in conjunction with the CLT-135/76-1A fire control computer to obtain a targeting solution for the OTO 135mm guns.
Sagittario_200=Sagittario 200|The Sagittario 200 is an early Italian fire control radar installed on the guided missile cruiser Giuseppe Garibaldi and works in conjuction with the CLT-76-1A fire control computer to obtain a targeting solution for the OTO 76mm guns.
RTN-10X=RTN-10X|The RTN-10X 'Orion' is an Italian fire control radar used to guide several models of cannons such as the OTO-Melara 76.2mm and 127mm. 
RTN-20X=RTN-20X|The RTN-20X 'Orion' is an Italian fire control radar developed from the RTN-10X radar. It is used primarily to guide the DARDO close-in weapon system.
RTN-30X=RTN-30X|The RTN-30X 'Orion' is an Italian fire control radar developed from the RTN-10X and RTN-20X radars. It is used to guide several models of weapons such as the OTO-Melara 76.2mm and 127mm guns and also the Aspide surface-to-air missile.

#---------------------------------------- Aircraft Radar ----------------------------------------
#----Air/Air&Surface----
NASARR_F-15A=NASARR F-15A|The NASARR is a search and tracking radar produced in the United States in the mid 1960s. It features a notably advanced ground-mapping capabilty for its time, making it especially useful for ground-strike missions. For this reason it is featured on the F-104G fighter-bomber variant of the F-104 Starfighter family.
NASARR_F-15G=NASARR F-15G|The NASARR is a search and tracking radar produced in the United States in the mid 1960s. It features a notably advanced ground-mapping capabilty for its time, making it especially useful for ground-strike missions. The F-15G variant of the system adds a moving-target indicator and continuous-wave illuminator, enabling guidance of SARH missiles such as the AIM-7 Sparrow.
NASARR_R-21G/M1=NASARR R-21G/M1|The NASARR is a search and tracking radar produced in the United States in the mid 1960s. It features a notably advanced ground-mapping capabilty for its time, making it especially useful for ground-strike missions. The R-21G/M1 is a significantly upgraded variant of the system, introducing look-down/shoot-down capability and frequency hopping for improved ECM resistance.

Foxhunter=AI.24 Foxhunter|The AI.24 is an advanced air-to-air radar developed for the interceptor variant of the Panavia Tornado in service with the Royal Airforce. The radar was first flight tested on a Buccaneer in 1981, but due to significant delays in its development it only entered service in the late 1980s on the F.3 variant of the Tornado interceptor.

#----Surface only----
APS-705=MM/APS-705|The MM/APS-705 was developed in the mid 1970s for use on the Marina Militare fleet of AB.212ASW helicopters. Its main roles are facilitating over-the-horizon guidance of Otomat missiles, early detection of approaching small craft as well as spotting and tracking submarine periscopes.
Seaspray=Seaspray 2000|The Seaspray is a British lightweight radar developed in the late 1970s for use on shipborne helicopters, primarily to detect small missile boats which could utilize the radar horizon of a surface vessel sensors to conceal their approach. The Seaspray 2000 is an improved version of the Seaspray which introduces a pulse-doppler mode.
DRAA-10A=Iguane|Iguane (Manufacturer’s designation: DRAA-10A (or TMV-118) is an airborne a multimode surveillance radar intended for installation on fixed-wing aircraft. The radar has the sensitivity to detect small periscope-size targets. It can operate in surface search mode and weather avoidance mode simultaneously and carries out track-while-scan. An Identification Friend or Foe (IFF) system is integrated into the radar.
ARI_23274=ARI 23274|The ARI 23274 is an advanced ground-mapping and attack radar able to simultaneously scan for targets and conduct fully automated terrain-following flight for low-level strike missions in all weather conditions.

#---------- Submarines ----------
IP-64=IP-64|The IP-64 is one of Italies first domestic sonar systems developed in the early 1960s which forms the active search component of the sonar suite on the Toti class diesel-electric submarines.
MD-64=MD-64|The MD-64 is one of Italies first domestic sonar systems developed in the early 1960s which forms the passive search component of the sonar suite on the Toti class diesel-electric submarines.
IPD-70=IPD-70|The IPD-70 is an Italian integrated sonar system developed in the late 1960s for Italys next generation of submarines.
IPD-70S=IPD-70/S|The IPD-70 is an Italian integrated sonar system developed in the late 1960s for Italys next generation of submarines. The IPD-70/S is an upgraded version of the system which introduces a modern digital controll console for the sonar operator.

#---------------------------------------- ESM ----------------------------------------
#---------- RWR ----------
ARI_18241=ARI 18241|The ARI 18241 is a modern radar detection and homing receiver manufactured by Marconi in Italy. It is capable of launch detection and recognizing a wide array of threats.
ARI_23284=ARI 23284|The ARI 23284 is a modern radar detection and homing receiver designed and manufactured in Italy. It is capable of launch detection and recognizing a wide array of threats.

#---------- ELINT ----------
SPR-A=MM/SPR-A|The MM/SPR-A is an early ESM system used on Italian ships in of the 1960s.
ELT-124-S=ELT-124/S|The ELT-124 'Thetis' is an Italian ESM system installed on the Sauro class diesel-electric submarines.
ELT-211=ELT-211|Designated MM/SLR-3 in Italian navy service the ELT-211 ESM system is part of the 'Newton' electronic warfare complex which can be found on a large number of warships due to its export success. It is a modern, fully digital system with solid-state electronics comprised of the ELT-123 preprocessor and ELT-261 IFM/library unit.
EWSS=EWSS|

#---------------------------------------- ECM ----------------------------------------
ELT-318=ELT-318|The ELT-318 is a continuous wave noise jammer integrated in the Italian 'Newton' electronic warfare complex.
ELT-512=ELT-512|The ELT-512 is a continuous wave deception jammer integrated in the Italian 'Newton' electronic warfare complex.
mm_nettuno_4100=Nettuno 4100|

#======================================== United States ========================================
#---------------------------------------- Radar ----------------------------------------
#----Surface only----
SG-6=SG-6|The SG-6 is an improved version of the SG surface-search radar originally introduced in WWII. It was mounted on a large variety of US surface combatants throughout the 1950s and 1960s until being replaced by the AN/SPS-10.

#---------- Submarines ----------
BPS-12=AN/BPS-12|

#---------------------------------------- Sonar ----------------------------------------
#---------- Surface ----------
SQS-11A=AN/SQS-11A|The AN/SQS-11 is a modernized postwar version of the late-war QHB active sonar. The SQS-11A is a further modified version upgraded with a boost capacitor to achieve higher detection ranges.
SQS-29=AN/SQS-29B|The AN/SQS-4 is an active/passive search sonar operating on the azmumith scanning method. The AN/SQS-29 is a re-designation of the AN/SQS-4 Mod 1 after being modified with Rotating Directional Transmission (RDT) capability to extend its service life.
SQS-30=AN/SQS-30|The AN/SQS-4 is an active/passive search sonar operating on the azmumith scanning method. The AN/SQS-30 is a re-designation of the AN/SQS-4 Mod 2 after being modified with Rotating Directional Transmission (RDT) capability to extend its service life.
SQS-39=AN/SQS-39|The AN/SQS-39 is an upgraded version of the AN/SQS-29 active/passive search sonar. Compared to the previous variant it has been upgraded with Steered Directional Transmission (SDT) capability and was modified with the Maintainability And Reliability Kit (MARK) to extend its service life.
SQS-43=AN/SQS-43|The AN/SQS-43 is an upgraded version of the AN/SQS-29B/C active/passive search sonar. Compared to the previous variant it has been upgraded with Steered Directional Transmission (SDT) capability and was modified with the Maintainability And Reliability Kit (MARK) to extend its service life.

#---------- Submarines ----------
AN_SQS_4_Tench=AN/SQS-4|

#----- Towed/VDS -----
SQA-10=AN/SQA-10|The AN/SQA-10 is a variable depth sonar manufactured by Litton.

#---------------------------------------- ESM ----------------------------------------
#---------- RWR ----------
APR-25=AN/APR-25|A radar detection and homing receiver installed on a multitude of US aircraft of the 1960s.

#---------------------------------------- ECM ----------------------------------------
ALQ-73=AN/ALQ-73|A defensive ECM set for small to medium-sized aircraft manufactured by Precision Instruments.



# ***********************************************************************************************
#                                          WEAPON SYSTEMS
# ***********************************************************************************************

#======================================== Italy ========================================
#---------------------------------------- Missile Launchers ----------------------------------------
OTOMAT_MK2=Otomat|Otomat launcher
SCLAR_Rockets=SCLAR launcher|SCLAR launcher
Alfa=Alfa silo|Alfa silo
Aspide=Albatros|Albatros launcher|The Albatros is an Italian surface-to-air missile system based on the US Navy's Mk. 29 Sea Sparrow system. It launches the Aspide missile, a domestically produced and significantly improved version of the RIM-7 Sea Sparrow. Unlike the Mk. 29 the Albatros launcher features its very own automatic loading system, marking a giant leap in capability compared to the manual loading required by its American relative.

#---------------------------------------- Torpedo Launchers ----------------------------------------
centauro_533mm=533mm

Menon_SL=Menon single barrel
Menon_TB=Menon triple barrel
Menon_K113=K113 Menon
DC_Drop=Depthcharge

#---------------------------------------- Land Guns ----------------------------------------

#---------------------------------------- Naval Guns ----------------------------------------
OTO135=OTO-Ansaldo 135|135mm/45 OTO-Ansaldo|The OTO-Ansaldo 135mm guns are part of the last generation of a handfull of guns in this caliber range designed and produced during the cold war. Being a further development of the WWII 135mm caliber used by Italy this new gun is fed by a fully automatic loading system and controlled by a modern radar-based fire control system, enabling it to function as a lethal dual-purpose weapon. The only ship to carry these guns would be the converted guided missile cruiser Guiseppe Garibaldi.
OTO127=OTO-Melara Compact|127mm/54 OTO-Melara Compact|The OTO-Melara Compact is an Italian dual-purpose mount and one of the most wide-spread naval guns in the world. Developed in the 1970s the OTO-Melara Compact is a modern system with a fully automatic loading mechanism and controlled remotely from a central console and by a single crew member. 
OTO76=Allargato|76.2mm/62 Allargato|The Allargato was developed in the 1960s as the first dual-purpose mount in line of the now famous Italian 76.2mm naval guns, laying the groundwork for wide-spread use of later models among countless navies across the globe. It is fed by a fully automatic loading system for a very high rate of fire and controlled remotely from the ship's CIC.
OTO76_SR=OTO-Melara SR|76.2mm/62 OTO-Melara Super Rapido|The OTO-Melara Super Rapido is an improved, faster-firing version of OTO-Melaras 76.2mm Compact turret designed specifically for close-in missile defense. Thanks to lightened moving parts, a heavily optimized loading system and improved ammunition the Super Rapido is capable of achieving an even higher fire-rate 120 round per minute. Due to this it is considered an even more effective missile defense weapon than OTO-Melaras own DARDO system.

Breda_Twin_40mm_L/70=Breda Type 106|40mm/70 Breda Type 106|
CALIBRO50=M2 Browning|The legendary Ma Deuce is one of the longest serving machine guns in existence, which is a testament to the greatness of its design.

#---------------------------------------- CIWS ----------------------------------------
Dardo=Dardo|40mm/70 OTO-Melara Compact|The OTO-Melara Compact is the actual weapon component of the Dardo close-in weapon system complex. Utilizing two fast-firing OTO-Breda 40mm guns developed from the famous 40mm Bofors AA gun it is the primary CIWS of the Marina Militare and a number of export customers.

#---------------------------------------- Aircraft Guns ----------------------------------------
BK-27=Mauser BK-27