# ver. 20260417
#
[General]
HullnumberReference=Hullnumber
EmblemReference=Emblem
NationFlagReference=Flag1
AllVariantsAreOfSameNation=True
NumberOfVariants=1

[Default]
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_spain
Nation=Spain

[Variant1]
ResourcesHullnumberFolder=ships/ae_ffg_alvaro_bazan/textures/
HullnumberTexture=spa_f105.png
ResourcesEmblemFolder=ships/ae_ffg_alvaro_bazan/textures/
EmblemTexture=41esc_emblem.png
ResourcesLiveryFolder=ships/ae_ffg_alvaro_bazan/textures/
LiveryTexture=hull_tx.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_spain
Nation=Spain
ServiceDate=2012|2050
# CustomAirGroup=True
# spa_sh-60b=Squadron1,1




