# ver. 20260706
#
[General]
HullnumberReference=Hullnumber
EmblemReference=Emblem
NationFlagReference=Flag1
AllVariantsAreOfSameNation=True
NumberOfVariants=6

[Default]
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_spain
Nation=Spain

[Variant1]
ResourcesHullnumberFolder=ships/ae_opv_meteoro/textures/
HullnumberTexture=p41.png
ResourcesEmblemFolder=ships/ae_opv_meteoro/textures/
EmblemTexture=41esc_emblem.png
ResourcesLiveryFolder=ships/ae_opv_meteoro/textures/
LiveryTexture=hull_tx.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_spain
Nation=Spain
ServiceDate=2011

[Variant2]
ResourcesHullnumberFolder=ships/ae_opv_meteoro/textures/
HullnumberTexture=p42.png
ResourcesEmblemFolder=ships/ae_opv_meteoro/textures/
EmblemTexture=41esc_emblem.png
ResourcesLiveryFolder=ships/ae_opv_meteoro/textures/
LiveryTexture=hull_tx.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_spain
Nation=Spain
ServiceDate=2011

[Variant3]
ResourcesHullnumberFolder=ships/ae_opv_meteoro/textures/
HullnumberTexture=p43.png
ResourcesEmblemFolder=ships/ae_opv_meteoro/textures/
EmblemTexture=41esc_emblem.png
ResourcesLiveryFolder=ships/ae_opv_meteoro/textures/
LiveryTexture=hull_tx.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_spain
Nation=Spain
ServiceDate=2011

[Variant4]
ResourcesHullnumberFolder=ships/ae_opv_meteoro/textures/
HullnumberTexture=p44.png
ResourcesEmblemFolder=ships/ae_opv_meteoro/textures/
EmblemTexture=41esc_emblem.png
ResourcesLiveryFolder=ships/ae_opv_meteoro/textures/
LiveryTexture=hull_tx.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_spain
Nation=Spain
ServiceDate=2011

[Variant5]
ResourcesHullnumberFolder=ships/ae_opv_meteoro/textures/
HullnumberTexture=p45.png
ResourcesEmblemFolder=ships/ae_opv_meteoro/textures/
EmblemTexture=41esc_emblem.png
ResourcesLiveryFolder=ships/ae_opv_meteoro/textures/
LiveryTexture=hull_tx.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_spain
Nation=Spain
ServiceDate=2018

[Variant6]
ResourcesHullnumberFolder=ships/ae_opv_meteoro/textures/
HullnumberTexture=p46.png
ResourcesEmblemFolder=ships/ae_opv_meteoro/textures/
EmblemTexture=41esc_emblem.png
ResourcesLiveryFolder=ships/ae_opv_meteoro/textures/
LiveryTexture=hull_tx.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_spain
Nation=Spain
ServiceDate=2019




