[Language_cn]
Name=中国地面单位包
Description=海权中国测试组出品

[Language_en]
Name=PLA Land Unit Pack
Description=create by 海权中国测试组

[Compatibility]
;ApproximateVersion is the second check and will override all statements below. This checks MAJOR and MINOR match but will accept higher PATCH.
;Would recommend this as a default case for starters.
ApproximateVersion=0.7.10