[General]
SerialnumberReferences=
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfSquadrons=1

[Default]
ResourcesLiveryFolder=assets/ships/materials/
LiveryTexture=usmc_vh-3d_marineone.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
# nations are referenced in the layout.ini file:
Nation=US
ServiceDate=1961
