[SystemNames]
#---------------------------------------- ESM ----------------------------------------
AN/APG-81 OECM=AN/APG-81 OECM|F-35 on-board offensive ECM. Late 2010s technology.
AN/ASQ-239Brcd ESM=AN/ASQ-239 Barracuda ESM|Late 2010s Technology, Air Search, Surface Search, Specific Emitter ID
AN/ASQ-239Brcd RWR=AN/ASQ-239 Barracuda RWR|Late 2010s Technology, Air Search, Surface Search, Specific Emitter ID