[Animations]
#Took this from NTU
NumberOfAnimations=7
Animation1=Advance_1
Animation2=Advance_2
Animation3=Advance_3
Animation4=Advance_4
Animation5=Advance_5
Animation6=Advance_6
Animation7=Advance_7

[Advance_1]
NumberOfSequencesToPlay=1
Sequence1=AdvanceRack1
Sequence1_Model=CSRL_Main

[AdvanceRack1]
NumberOfSteps=2
Time1=0
RotationZ1=0
Smoothness1=EaseInOut
Time2=3
RotationZ2=45
Smoothness2=EaseInOut

[Advance_2]
NumberOfSequencesToPlay=1
Sequence1=AdvanceRack2
Sequence1_Model=CSRL_Main

[AdvanceRack2]
NumberOfSteps=2
Time1=0
RotationZ1=45
Smoothness1=EaseInOut
Time2=3
RotationZ2=90
Smoothness2=EaseInOut

[Advance_3]
NumberOfSequencesToPlay=1
Sequence1=AdvanceRack3
Sequence1_Model=CSRL_Main

[AdvanceRack3]
NumberOfSteps=2
Time1=0
RotationZ1=90
Smoothness1=EaseInOut
Time2=3
RotationZ2=135
Smoothness2=EaseInOut

[Advance_4]
NumberOfSequencesToPlay=1
Sequence1=AdvanceRack4
Sequence1_Model=CSRL_Main

[AdvanceRack4]
NumberOfSteps=2
Time1=0
RotationZ1=135
Smoothness1=EaseInOut
Time2=3
RotationZ2=180
Smoothness2=EaseInOut

[Advance_5]
NumberOfSequencesToPlay=1
Sequence1=AdvanceRack5
Sequence1_Model=CSRL_Main

[AdvanceRack5]
NumberOfSteps=2
Time1=0
RotationZ1=180
Smoothness1=EaseInOut
Time2=3
RotationZ2=225
Smoothness2=EaseInOut

[Advance_6]
NumberOfSequencesToPlay=1
Sequence1=AdvanceRack6
Sequence1_Model=CSRL_Main

[AdvanceRack6]
NumberOfSteps=2
Time1=0
RotationZ1=225
Smoothness1=EaseInOut
Time2=3
RotationZ2=270
Smoothness2=EaseInOut

[Advance_7]
NumberOfSequencesToPlay=1
Sequence1=AdvanceRack7
Sequence1_Model=CSRL_Main

[AdvanceRack7]
NumberOfSteps=2
Time1=0
RotationZ1=270
Smoothness1=EaseInOut
Time2=3
RotationZ2=315
Smoothness2=EaseInOut