[Animations]
Animation1=Flaps_Takeoff
Animation2=Flaps_Takeoff_Retract
Animation3=Flaps_Landing
Animation4=Flaps_Landing_Retract
Animation5=Gear_Extend
Animation6=Gear_Retract

[Flaps_Takeoff]
NumberOfSequencesToPlay=12
Sequence1=Flapgear_Takeoff_r1
Sequence1_Model=Flapgear_r1
Sequence2=Flapgear_Takeoff_r2
Sequence2_Model=Flapgear_r2
Sequence3=Flapgear_Takeoff_r3
Sequence3_Model=Flapgear_r3
Sequence4=Flap_Takeoff_r1
Sequence4_Model=Flap_r1
Sequence5=Flap_Takeoff_r2
Sequence5_Model=Flap_r2
Sequence6=Flap_Takeoff_r3
Sequence6_Model=Flap_r3
Sequence7=Flapgear_Takeoff_l1
Sequence7_Model=Flapgear_l1
Sequence8=Flapgear_Takeoff_l2
Sequence8_Model=Flapgear_l2
Sequence9=Flapgear_Takeoff_l3
Sequence9_Model=Flapgear_l3
Sequence10=Flap_Takeoff_l1
Sequence10_Model=Flap_l1
Sequence11=Flap_Takeoff_l2
Sequence11_Model=Flap_l2
Sequence12=Flap_Takeoff_l3
Sequence12_Model=Flap_l3

[Flaps_Takeoff_Retract]
NumberOfSequencesToPlay=12
Sequence1=Flapgear_Retract_r1
Sequence1_Model=Flapgear_r1
Sequence2=Flapgear_Retract_r2
Sequence2_Model=Flapgear_r2
Sequence3=Flapgear_Retract_r3
Sequence3_Model=Flapgear_r3
Sequence4=Flap_Retract_r1
Sequence4_Model=Flap_r1
Sequence5=Flap_Retract_r2
Sequence5_Model=Flap_r2
Sequence6=Flap_Retract_r3
Sequence6_Model=Flap_r3
Sequence7=Flapgear_Retract_l1
Sequence7_Model=Flapgear_l1
Sequence8=Flapgear_Retract_l2
Sequence8_Model=Flapgear_l2
Sequence9=Flapgear_Retract_l3
Sequence9_Model=Flapgear_l3
Sequence10=Flap_Retract_l1
Sequence10_Model=Flap_l1
Sequence11=Flap_Retract_l2
Sequence11_Model=Flap_l2
Sequence12=Flap_Retract_l3
Sequence12_Model=Flap_l3

[Flaps_Landing]
NumberOfSequencesToPlay=12
Sequence1=Flapgear_Takeoff_r1
Sequence1_Model=Flapgear_r1
Sequence2=Flapgear_Takeoff_r2
Sequence2_Model=Flapgear_r2
Sequence3=Flapgear_Takeoff_r3
Sequence3_Model=Flapgear_r3
Sequence4=Flap_Takeoff_r1
Sequence4_Model=Flap_r1
Sequence5=Flap_Takeoff_r2
Sequence5_Model=Flap_r2
Sequence6=Flap_Takeoff_r3
Sequence6_Model=Flap_r3
Sequence7=Flapgear_Takeoff_l1
Sequence7_Model=Flapgear_l1
Sequence8=Flapgear_Takeoff_l2
Sequence8_Model=Flapgear_l2
Sequence9=Flapgear_Takeoff_l3
Sequence9_Model=Flapgear_l3
Sequence10=Flap_Takeoff_l1
Sequence10_Model=Flap_l1
Sequence11=Flap_Takeoff_l2
Sequence11_Model=Flap_l2
Sequence12=Flap_Takeoff_l3
Sequence12_Model=Flap_l3

[Flaps_Landing_Retract]
NumberOfSequencesToPlay=12
Sequence1=Flapgear_Retract_r1
Sequence1_Model=Flapgear_r1
Sequence2=Flapgear_Retract_r2
Sequence2_Model=Flapgear_r2
Sequence3=Flapgear_Retract_r3
Sequence3_Model=Flapgear_r3
Sequence4=Flap_Retract_r1
Sequence4_Model=Flap_r1
Sequence5=Flap_Retract_r2
Sequence5_Model=Flap_r2
Sequence6=Flap_Retract_r3
Sequence6_Model=Flap_r3
Sequence7=Flapgear_Retract_l1
Sequence7_Model=Flapgear_l1
Sequence8=Flapgear_Retract_l2
Sequence8_Model=Flapgear_l2
Sequence9=Flapgear_Retract_l3
Sequence9_Model=Flapgear_l3
Sequence10=Flap_Retract_l1
Sequence10_Model=Flap_l1
Sequence11=Flap_Retract_l2
Sequence11_Model=Flap_l2
Sequence12=Flap_Retract_l3
Sequence12_Model=Flap_l3

[Gear_Extend]
NumberOfSequencesToPlay=10
Sequence1=Nose_Gear_Down
Sequence1_Model=Gear_f
Sequence2=Nose_Gearpad_Down_1l
Sequence2_Model=Gearpad_f1l
Sequence3=Nose_Gearpad_Down_1r
Sequence3_Model=Gearpad_f1r
Sequence4=Nose_Gearpad_Down_2
Sequence4_Model=Gearpad_f2

Sequence5=Left_Gear_Down
Sequence5_Model=Gear_l
Sequence6=Left_Gearpad_Down_1
Sequence6_Model=Gearpad_l1
Sequence7=Left_Gearpad_Down_2
Sequence7_Model=Gearpad_l2

Sequence8=Right_Gear_Down
Sequence8_Model=Gear_r
Sequence9=Right_Gearpad_Down_1
Sequence9_Model=Gearpad_r1
Sequence10=Right_Gearpad_Down_2
Sequence10_Model=Gearpad_r2

[Gear_Retract]
NumberOfSequencesToPlay=10
Sequence1=Nose_Gear_Up
Sequence1_Model=Gear_f
Sequence2=Nose_Gearpad_Up_1l
Sequence2_Model=Gearpad_f1l
Sequence3=Nose_Gearpad_Up_1r
Sequence3_Model=Gearpad_f1r
Sequence4=Nose_Gearpad_Up_2
Sequence4_Model=Gearpad_f2

Sequence5=Left_Gear_Up
Sequence5_Model=Gear_l
Sequence6=Left_Gearpad_Up_1
Sequence6_Model=Gearpad_l1
Sequence7=Left_Gearpad_Up_2
Sequence7_Model=Gearpad_l2

Sequence8=Right_Gear_Up
Sequence8_Model=Gear_r
Sequence9=Right_Gearpad_Up_1
Sequence9_Model=Gearpad_r1
Sequence10=Right_Gearpad_Up_2
Sequence10_Model=Gearpad_r2

[Flapgear_Takeoff_r1]
NumberOfSteps=2
Step1=0|x,y,z|x,y,z|EaseInOut
Step2=4|x,y,z|-15,y,z|EaseInOut
[Flapgear_Takeoff_r2]
NumberOfSteps=2
Step1=0|x,y,z|x,y,z|EaseInOut
Step2=4|x,y,z|-14,y,z|EaseInOut
[Flapgear_Takeoff_r3]
NumberOfSteps=2
Step1=0|x,y,z|x,y,z|EaseInOut
Step2=4|x,y,z|-13,y,z|EaseInOut
[Flap_Takeoff_r1]
NumberOfSteps=2
Step1=0|0.047617,-0.015759,-0.058997|0,4.48,1.37|EaseInOut
Step2=4|0.049,-0.017122,-0.063724|-15.774,2.187,2.259|EaseInOut
[Flap_Takeoff_r2]
NumberOfSteps=2
Step1=0|0.097247,-0.014573,-0.07154|-0.5,23.8276,0|EaseInOut
Step2=4|0.096708,-0.015046,-0.074637|-17.73,23.45,1.334|EaseInOut
[Flap_Takeoff_r3]
NumberOfSteps=2
Step1=0|0.177126,-0.01367,-0.115572|0,30.2213,0|EaseInOut
Step2=4|0.176455,-0.013374,-0.118187|-17.41,29.7466,0.405423|EaseInOut

[Flapgear_Takeoff_l1]
NumberOfSteps=2
Step1=0|x,y,z|x,y,z|EaseInOut
Step2=4|x,y,z|-15,y,z|EaseInOut
[Flapgear_Takeoff_l2]
NumberOfSteps=2
Step1=0|x,y,z|x,y,z|EaseInOut
Step2=4|x,y,z|-14,y,z|EaseInOut
[Flapgear_Takeoff_l3]
NumberOfSteps=2
Step1=0|x,y,z|x,y,z|EaseInOut
Step2=4|x,y,z|-13,y,z|EaseInOut
[Flap_Takeoff_l1]
NumberOfSteps=2
Step1=0|-0.047617,-0.015759,-0.058997|0,0,0|EaseInOut
Step2=4|-0.049,-0.017122,-0.063724|-15.774,2.187,-1.259|EaseInOut
[Flap_Takeoff_l2]
NumberOfSteps=2
Step1=0|-0.097247,-0.014573,-0.07154|-0.5,-23.8276,0|EaseInOut
Step2=4|-0.096708,-0.015046,-0.074637|-17.73,-23.45,-1.334|EaseInOut
[Flap_Takeoff_l3]
NumberOfSteps=2
Step1=0|-0.177126,-0.01367,-0.115572|0,-30.2213,0|EaseInOut
Step2=4|-0.176455,-0.013374,-0.118187|-17.41,-29.7466,-0.405423|EaseInOut
############################################################################
############################################################################
[Flapgear_Retract_r1]
NumberOfSteps=2
Step1=0|x,y,z|-15,y,z|EaseInOut
Step2=4|x,y,z|0,y,z|EaseInOut
[Flapgear_Retract_r2]
NumberOfSteps=2
Step1=0|x,y,z|-14,y,z|EaseInOut
Step2=4|x,y,z|0,y,z|EaseInOut
[Flapgear_Retract_r3]
NumberOfSteps=2
Step1=0|x,y,z|-13,y,z|EaseInOut
Step2=4|x,y,z|0,y,z|EaseInOut
[Flap_Retract_r1]
NumberOfSteps=2
Step1=0|0.049,-0.017122,-0.063724|-15.774,2.187,2.259|EaseInOut
Step2=4|0.047617,-0.015759,-0.058997|0,4.48,1.37|EaseInOut
[Flap_Retract_r2]
NumberOfSteps=2
Step1=0|0.096708,-0.015046,-0.074637|-17.73,23.45,1.334|EaseInOut
Step2=4|0.097247,-0.014573,-0.07154|-0.5,23.8276,0|EaseInOut
[Flap_Retract_r3]
NumberOfSteps=2
Step1=0|0.176455,-0.013374,-0.118187|-17.41,29.7466,0.405423|EaseInOut
Step2=4|0.177126,-0.01367,-0.115572|0,30.2213,0|EaseInOut

[Flapgear_Retract_l1]
NumberOfSteps=2
Step1=0|x,y,z|-15,y,z|EaseInOut
Step2=4|x,y,z|0,y,z|EaseInOut
[Flapgear_Retract_l2]
NumberOfSteps=2
Step1=0|x,y,z|-14,y,z|EaseInOut
Step2=4|x,y,z|0,y,z|EaseInOut
[Flapgear_Retract_l3]
NumberOfSteps=2
Step1=0|x,y,z|-13,y,z|EaseInOut
Step2=4|x,y,z|0,y,z|EaseInOut
[Flap_Retract_l1]
NumberOfSteps=2
Step1=0|-0.049,-0.017122,-0.063724|-15.774,2.187,-1.259|EaseInOut
Step2=4|-0.047617,-0.015759,-0.058997|0,0,0|EaseInOut
[Flap_Retract_l2]
NumberOfSteps=2
Step1=0|-0.096708,-0.015046,-0.074637|-17.73,-23.45,-1.334|EaseInOut
Step2=4|-0.097247,-0.014573,-0.07154|-0.5,-23.8276,0|EaseInOut
[Flap_Retract_l3]
NumberOfSteps=2
Step1=0|-0.176455,-0.013374,-0.118187|-17.41,-29.7466,-0.405423|EaseInOut
Step2=4|-0.177126,-0.01367,-0.115572|0,-30.2213,0|EaseInOut

############ GEAR ################
[Nose_Gear_Down]
NumberOfSteps=2
Step1=2|x,y,z|-90,y,z|EaseInOut
Step2=8|x,y,z|20,y,z|EaseInOut
[Nose_Gearpad_Down_1l]
NumberOfSteps=4
Step1=0|x,y,z|x,y,0|EaseInOut
Step2=2|x,y,z|x,y,-90|EaseInOut
Step3=7|x,y,z|x,y,-90|EaseInOut
Step4=9|x,y,z|x,y,0|EaseInOut
[Nose_Gearpad_Down_1r]
NumberOfSteps=4
Step1=0|x,y,z|x,y,0|EaseInOut
Step2=2|x,y,z|x,y,90|EaseInOut
Step3=7|x,y,z|x,y,90|EaseInOut
Step4=9|x,y,z|x,y,0|EaseInOut
[Nose_Gearpad_Down_2]
NumberOfSteps=2
Step1=2|x,y,z|-76.9675,y,z|EaseInOut
Step2=8|x,y,z|40,y,z|EaseInOut

[Left_Gearpad_Down_1]
NumberOfSteps=2
Step1=2|x,y,z|x,y,88.4|EaseInOut
Step2=8|x,y,z|x,y,-60|EaseInOut
[Left_Gearpad_Down_2]
NumberOfSteps=4
Step1=0|x,y,z|x,y,0|EaseInOut
Step2=2|x,y,z|x,y,80|EaseInOut
Step3=7|x,y,z|x,y,80|EaseInOut
Step4=9|x,y,z|x,y,0|EaseInOut
[Left_Gear_Down]
NumberOfSteps=2
Step1=2|x,y,z|x,y,55|EaseInOut
Step2=8|x,y,z|x,y,-45|EaseInOut
[Right_Gearpad_Down_1]
NumberOfSteps=2
Step1=2|x,y,z|x,y,-88.4|EaseInOut
Step2=8|x,y,z|x,y,60|EaseInOut
[Right_Gearpad_Down_2]
NumberOfSteps=4
Step1=0|x,y,z|x,y,0|EaseInOut
Step2=2|x,y,z|x,y,-80|EaseInOut
Step3=7|x,y,z|x,y,-80|EaseInOut
Step4=9|x,y,z|x,y,0|EaseInOut
[Right_Gear_Down]
NumberOfSteps=2
Step1=2|x,y,z|x,y,-55|EaseInOut
Step2=8|x,y,z|x,y,45|EaseInOut

#############################################
[Nose_Gear_Up]
NumberOfSteps=2
Step1=2|x,y,z|20,y,z|EaseInOut
Step2=8|x,y,z|-90,y,z|EaseInOut
[Nose_Gearpad_Up_1l]
NumberOfSteps=4
Step1=0|x,y,z|x,y,0|EaseInOut
Step2=2|x,y,z|x,y,-90|EaseInOut
Step3=7|x,y,z|x,y,-90|EaseInOut
Step4=9|x,y,z|x,y,0|EaseInOut
[Nose_Gearpad_Up_1r]
NumberOfSteps=4
Step1=0|x,y,z|x,y,0|EaseInOut
Step2=2|x,y,z|x,y,90|EaseInOut
Step3=7|x,y,z|x,y,90|EaseInOut
Step4=9|x,y,z|x,y,0|EaseInOut
[Nose_Gearpad_Up_2]
NumberOfSteps=2
Step1=2|x,y,z|40,y,z|EaseInOut
Step2=8|x,y,z|-76.9675,y,z|EaseInOut

[Left_Gearpad_Up_1]
NumberOfSteps=2
Step1=2|x,y,z|x,y,-60|EaseInOut
Step2=8|x,y,z|x,y,88.4|EaseInOut
[Left_Gearpad_Up_2]
NumberOfSteps=4
Step1=0|x,y,z|x,y,0|EaseInOut
Step2=2|x,y,z|x,y,80|EaseInOut
Step3=7|x,y,z|x,y,80|EaseInOut
Step4=9|x,y,z|x,y,0|EaseInOut
[Left_Gear_Up]
NumberOfSteps=2
Step1=2|x,y,z|x,y,-45|EaseInOut
Step2=8|x,y,z|x,y,55|EaseInOut
[Right_Gearpad_Up_1]
NumberOfSteps=2
Step1=2|x,y,z|x,y,60|EaseInOut
Step2=8|x,y,z|x,y,-88.4|EaseInOut
[Right_Gearpad_Up_2]
NumberOfSteps=4
Step1=0|x,y,z|x,y,0|EaseInOut
Step2=2|x,y,z|x,y,-80|EaseInOut
Step3=7|x,y,z|x,y,-80|EaseInOut
Step4=9|x,y,z|x,y,0|EaseInOut
[Right_Gear_Up]
NumberOfSteps=2
Step1=2|x,y,z|x,y,45|EaseInOut
Step2=8|x,y,z|x,y,-55|EaseInOut