[AmmunitionNames]

# ---------- 空空导弹 ---------


# ---------- 反辐射导弹 ---------
usn_agm-114k=AGM-114K,地狱火,对地攻击,AGM-114地狱火是美国半主动激光制导空对地防区外武器。

usn_agm-114r=AGM-114R,地狱火II,对地攻击,AGM-114R地狱火II, 又称地狱火罗密欧, 是地狱火系列中最新的精确打击、半主动激光(SAL)制导导弹。于2012年底推出, 旨在将多个先前型号整合为一种能够打击广泛目标的多任务武器。

# ---------- 反舰导弹 ----------

usn_agm-119b=AGM-119B,企鹅 Mk2 Mod 7,反水面,AGM-119B企鹅是一种由美国和挪威合作开发的小型空射和面射反舰导弹。此为Mod 7版本, 配备红外成像导引头、更远的射程、折叠尾翼(游戏中未建模)和更低的海面掠飞高度。

#-----------对地打击导弹---------

-------------------------------------------------------------------------------------------