[ ======================================== Test ======================================== ]
[ ======================================== Test ======================================== ]

[Sylver_A43]
HorizontalDegreesPerSecond=0     // rotation speed horizontally
VerticalDegreesPerSecond=0       // rotation speed vertically
NumberOfAttachments=1            // per container
AttachmentPosition1=0,0,0
ReloadTime=1
MoveToRestPositionTime=1      // time in seconds the weapon goes back to rest position if not used
Warmup=False
SmokeEffect=effects/weapons/emitters/LauncherSmoke
SmokeEffectPosition=0,0,0.055
SmokeEffectDirectional=True
ModuleType=VLS

[Sylver_A50]
HorizontalDegreesPerSecond=0     // rotation speed horizontally
VerticalDegreesPerSecond=0       // rotation speed vertically
NumberOfAttachments=1            // per container
AttachmentPosition1=0,0,0
ReloadTime=1
MoveToRestPositionTime=1      // time in seconds the weapon goes back to rest position if not used
Warmup=False
SmokeEffect=effects/weapons/emitters/LauncherSmoke
SmokeEffectPosition=0,0,0.055
SmokeEffectDirectional=True
ModuleType=VLS

[Sylver_A70]
HorizontalDegreesPerSecond=0     // rotation speed horizontally
VerticalDegreesPerSecond=0       // rotation speed vertically
NumberOfAttachments=1            // per container
AttachmentPosition1=0,0,0
ReloadTime=1
MoveToRestPositionTime=1      // time in seconds the weapon goes back to rest position if not used
SmokeEffect=effects/weapons/emitters/LauncherSmoke
SmokeEffectPosition=0,0,0.055
SmokeEffectDirectional=True
Warmup=False
ModuleType=VLS

[SADRAL]
Lanceur SADRAL
NumberOfAttachments=6
AttachmentPosition1=-0.007366,0.00639,-0.004982
AttachmentPosition2=-0.007366,-0.000379,-0.004982
AttachmentPosition3=-0.007366,-0.006752,-0.004982
AttachmentPosition4=0.007473,0.00639,-0.004982
AttachmentPosition5=0.007473,-0.000315,-0.004982
AttachmentPosition6=0.007473,-0.006805,-0.004982
HorizontalDegreesPerSecond=180   // rotation speed horizontally
VerticalDegreesPerSecond=180     // rotation speed vertically
ReloadTime=100                  // time in seconds after firing until launcher is reloaded
Warmup=False
MoveToRestPositionTime=30.0      // time in seconds the weapon goes back to rest position if not used
SmokeEffect=effects/weapons/emitters/LauncherSmokeSmall
SmokeEffectPosition=0,0,0
ModuleType=SmallLauncher

[NEXTER-NARWHAL]
*Canon 20 mm NEXTER-NARWHAL
MissileInterceptChance=50       // For CIWS. Chance to intercept missile with 0 defense rating
AircraftInterceptChance=70      // For CIWS. Chance to intercept missile with 0 defense rating
HorizontalDegreesPerSecond=100  // rotation speed horizontally
VerticalDegreesPerSecond=86     // rotation speed vertically
FireRate=800             // rounds per minute
RoundsLoaded=2000               // number of rounds loaded
ReloadTime=100                  // magazine reload time in seconds
MoveToRestPositionTime=30.0     // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/usn_m39_burst
EffectPosition=0,0,0.034
SpawnPosition=0,0,0.0
ModuleType=CIWS

[OTO76]
76 mm naval gun.
HorizontalDegreesPerSecond=70   // rotation speed horizontally
VerticalDegreesPerSecond=50     // rotation speed vertically
FireRate=120                     // rounds per minute
BurstCount=4                   // number of shots in one burst. 
BurstDelay=0.8                 // delay between bursts in seconds
RoundsLoaded=80                // number of rounds loaded
ReloadTime=25                   // magazine reload time in seconds
RecoilTime=0.08                  // time in seconds for the recoil
RecoilStrength=0.00015          // amplitude of recoil
MoveToRestPositionTime=10.0     // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/AK726_fire_emitter
EffectPosition=-0.005,0,0.08|0.005,0,0.08
SpawnPosition=-0.005,0,0.18|0.005,0,0.18
FireSequential=True            //REQUIRED for burst fire
ModuleType=MediumTurret

[MU90-torpedo-tubes]
HorizontalDegreesPerSecond=0   // rotation speed horizontally
VerticalDegreesPerSecond=0      // rotation speed vertically
ReloadTime=60            // time in seconds after firing until launcher is reloaded
NumberOfAttachments=1
AttachmentPosition1=0,0,0
MoveToRestPositionTime=20.0     // time in seconds the weapon goes back to rest position if not used
ModuleType=SmallLauncher

[MU90-torpedo-tubes_2]
HorizontalDegreesPerSecond=0   // rotation speed horizontally
VerticalDegreesPerSecond=0      // rotation speed vertically
ReloadTime=60            // time in seconds after firing until launcher is reloaded
NumberOfAttachments=1
AttachmentPosition1=0,0,0
AttachmentPosition2=0,0,0
MoveToRestPositionTime=20.0     // time in seconds the weapon goes back to rest position if not used
ModuleType=SmallLauncher

[Exocet_MM40]
Exocet
NumberOfAttachments=4  
AttachmentPosition1=-0.00287,0.000415 ,0.009461 
AttachmentPosition2=0.00287,0.000415 ,0.009461 
AttachmentPosition3=-0.00287,-0.000415 ,0.009461 
AttachmentPosition4=0.00287,-0.000415 ,0.009461 
ReloadTime=0
MoveToRestPositionTime=3.0      // time in seconds the weapon goes back to rest position if not used
SmokeEffect=effects/weapons/emitters/LauncherSmoke
SmokeEffectPosition=0,0,0
PreLaunchDelay=2
ModuleType=MediumLauncher

[Canto]
HorizontalDegreesPerSecond=30   // rotation speed horizontally
VerticalDegreesPerSecond=0      // rotation speed vertically
ReloadTime=60            // time in seconds after firing until launcher is reloaded
NumberOfAttachments=1
AttachmentPosition1=0,0,0
MoveToRestPositionTime=20.0     // time in seconds the weapon goes back to rest position if not used
ModuleType=SmallLauncher

[NGDS]
RoundsLoaded=60
ReloadTime=60
Effect=effects/countermeasures/emitters/chaff_burst
EffectPosition=0,0,0
ModuleType=Inert

[SYLENA]
RoundsLoaded=60
ReloadTime=60
Effect=effects/countermeasures/emitters/chaff_burst
EffectPosition=0,0,0
ModuleType=Inert


[Crotale]
NumberOfAttachments=8
AttachmentPosition1=-0.024841,0,0.006946
AttachmentPosition2=-0.014998,0,0.006946
AttachmentPosition3=0.013521,0,0.006946
AttachmentPosition4=0.023417,0,0.006946
AttachmentPosition5=0.023417,-0.011759,0.006946
AttachmentPosition6=0.013521,-0.011759,0.006946
AttachmentPosition7=-0.014998,-0.011759,0.006946
AttachmentPosition8=-0.024841,-0.011759,0.006946
HorizontalDegreesPerSecond=80     // rotation speed horizontally
VerticalDegreesPerSecond=80      // rotation speed vertically
ReloadTime=1800
MoveToRestPositionTime=10.0      // time in seconds the weapon goes back to rest position if not used
Warmup=False
#SmokeEffect=effects/weapons/emitters/LauncherSmoke
SmokeEffect=effects/weapons/emitters/AK130_fire_emitter
SmokeEffectPosition=0,0,0.055
SmokeEffectDirectional=True
ModuleType=MediumLauncher

[SIMBAD]
*Lanceur SIMBAD
NumberOfAttachments=2
AttachmentPosition1=-0.004709,0.00155,-0.004511
AttachmentPosition2=-0.004892,0.000155,-0.004511
HorizontalDegreesPerSecond=18   // rotation speed horizontally
VerticalDegreesPerSecond=18    // rotation speed vertically
ReloadTime=100                  // time in seconds after firing until launcher is reloaded
Warmup=False
MoveToRestPositionTime=10.0      // time in seconds the weapon goes back to rest position if not used
SmokeEffect=effects/weapons/emitters/LauncherSmokeSmall
SmokeEffectPosition=0,0,0
ModuleType=SmallLauncher

[100TR]
# French 100mm gun
HorizontalDegreesPerSecond=40   // rotation speed horizontally
VerticalDegreesPerSecond=30     // rotation speed vertically
FireRate=78                     // rounds per minute
RoundsLoaded=35                // number of rounds loaded
ReloadTime=30                   // magazine reload time in seconds
RecoilTime=0.1                  // time in seconds for the recoil
RecoilStrength=0.00035          // amplitude of recoil
MoveToRestPositionTime=10.0     // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/AK726_fire_emitter
EffectPosition=-0.0004,0,0.077
SpawnPosition=0,0,0.12
//FireSequential=True            //REQUIRED for burst fire
ModuleType=MediumTurret

[20_mm_modèle_F2]
Canon 20 mm
MissileInterceptChance=50       // For CIWS. Chance to intercept missile with 0 defense rating
AircraftInterceptChance=70      // For CIWS. Chance to intercept missile with 0 defense rating
HorizontalDegreesPerSecond=60 // rotation speed horizontally
VerticalDegreesPerSecond=60    // rotation speed vertically
FireRate=800             // rounds per minute
RoundsLoaded=2000               // number of rounds loaded
ReloadTime=100                  // magazine reload time in seconds
MoveToRestPositionTime=30.0     // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/usn_m39_burst
EffectPosition=0,0,0.034
SpawnPosition=0,0,0.0
ModuleType=CIWS

[CSA_Mk2_Noisemaker_Ejector]
NumberOfAttachments=1
AttachmentPosition1=0,0,0
ReloadTime=30.0            // time in seconds after firing until launcher is reloaded
SpawnPosition=0,0,0
EffectPosition=0,0,0
ModuleType=Inert

[VLS]
NumberOfAttachments=1  // per container
AttachmentPosition1=0,0,0
MoveToRestPositionTime=8.0      // time in seconds the weapon goes back to rest position if not used
ModuleType=MediumLauncher

[M2]
MissileInterceptChance=-1       // For CIWS. Chance to intercept missile with 0 defense rating
AircraftInterceptChance=20      // For CIWS. Chance to intercept missile with 0 defense rating
HorizontalDegreesPerSecond=65  // rotation speed horizontally
VerticalDegreesPerSecond=65    // rotation speed vertically
FireRate=500                   // rounds per minute
BurstTime=2                   // the length of a single burst in time
RoundsLoaded=105              // number of rounds loaded
ReloadTime=20                    // magazine reload time in seconds
MoveToRestPositionTime=15.0     // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/usn_50cal_twin_burst
EffectPosition=-0.0012,0.0005,0
SpawnPosition=0,0,0.0

[AANF1]
MissileInterceptChance=-1       // For CIWS. Chance to intercept missile with 0 defense rating
AircraftInterceptChance=15      // For CIWS. Chance to intercept missile with 0 defense rating
HorizontalDegreesPerSecond=65  // rotation speed horizontally
VerticalDegreesPerSecond=65    // rotation speed vertically
FireRate=900                   // rounds per minute
BurstTime=2                   // the length of a single burst in time
RoundsLoaded=100              // number of rounds loaded
ReloadTime=20                    // magazine reload time in seconds
MoveToRestPositionTime=15.0     // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/usn_50cal_twin_burst
EffectPosition=0,0.0030,-0.012
SpawnPosition=0,0,0.0
