#XM-65 TOW Launcher
[General]
Type=Container                       // can be Projectile, Missile, RBU, ASROC, Torpedo,AerialRocket,MLRS
Mass=39                             // in kg. Used for aircraft. Container mass. Weapon mass is read from weapon ini

[Positions]
Position1=-0.0018,-0.003,0
Rotation1=0,0,0

Position2=0.0018,-0.003,0
Rotation2=0,0,0

Position3=-0.0018,-0.007,0
Rotation3=0,0,0

Position4=0.0018,-0.007,0
Rotation4=0,0,0

[Presets]
Preset1=1
Preset2=1,2
Preset3=1,2,3
Preset4=1,2,3,4

[Default]
; Amount1Presets=Preset1
; Amount2Presets=Preset2
; Amount3Presets=Preset3
Amount4Presets=Preset4

[CompositeIcon]
DisplaySize=15
RealSize_medium=20
RealSize_small=20

Position1=25,-25
Position2=-25,-25
Position3=25,25
Position4=-25,25

[Models]
ResourcesFolder=weapons/usmc_quad_tow/
ResourcesRoot=usmc_quad_tow_launcher
ResourcesMesh=usmc_quad_tow
ResourcesMaterialFolder=ships/materials/
ResourcesMaterial=usn_parts

ResourcesMeshPosition=0,-0.003,0