[General]
Type=Container                       // can be Projectile, Missile, RBU, ASROC, Torpedo,AerialRocket,MLRS
Mass=154                             // in kg. Used for aircraft. Container mass. Weapon mass is read from weapon ini

[---------- Sensor Systems ----------]
[SensorSystems]
NumberOfSensorSystems=1

[SensorSystem1]
Type=Infrared
#FLIR system
SystemName=AN/AAS-38_FLIR
Mount=Dummy
ViewArcs=-30,150|-90,30
ModuleType=Sensor

[SensorSystem2] #AN/AVQ-23
Type=LaserDesignator
SystemName=AN/AAS-38_LTD/R
Mount=Dummy
ModuleType=Sensor

[OpticalView]
Views=eo_station_an_aas-38_wide,eo_station_an_aas-38_narrow
ViewsToRemove=binocular_7x50,binocular_10x50
DefaultView=eo_station_an_aas-38_wide

[---------- Mesh definitions----------]
[Models]
ResourcesFolder=weapons/usn_aas-38/
ResourcesRoot=usn_pod_aas-38.obj
ResourcesMesh=usn_pod_aas-38
ResourcesMaterial=usn_aas-38_mat.ini
