[General]
Type=Container

[Positions]
Position1=-0.00325,0,0
Position2=-0.00325,-0.0055,0
Position3=0.00325,0,0
Position4=0.00325,-0.0055,0

#Large
Position5=-0.001,-0.0025,0
Position6=0.007,-0.0025,0

[Presets]
Preset1=1
Preset2=1,2
Preset3=1,2,3
Preset4=1,2,3,4

PresetLarge1=5
PresetLarge2=5,6

[Default]
Amount1Presets=Preset1
Amount2Presets=Preset2
Amount3Presets=Preset3
Amount4Presets=Preset4

[Large]
Amount1Presets=PresetLarge1
Amount2Presets=PresetLarge2

[CompositeIcon]
DisplaySize=15
RealSize_medium=20
RealSize_small=20

Position1=25,25
Position2=25,-25
Position3=-25,-25
Position4=-25,25
Position5=25,0
Position6=-25,0
