#Launcher for AGM-78 Standard ARM
[General]
Type=Container                       // can be Projectile, Missile, RBU, ASROC, Torpedo,AerialRocket,MLRS
Mass=83

[Positions]
NumberOfPositions=1
Position1=0,-0.0072,0
Rotation1=0,0,0

[Presets]
Preset1=1

[Default]
NumberOfAmounts=1
Amount1Presets=Preset1

[Models]
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=weapons/usn_lau-118/
ResourcesRoot=usn_lau-118
ResourcesMesh=usaf_lau-34
ResourcesMaterial=usn_lau-118_mat

ResourcesMeshPosition=0,-0.0017,0.0008
ResourcesMeshScale=1.2,1.66,1.66