#Multiple Weapon Adapter
[General]
Type=Container                       // can be Projectile, Missile, RBU, ASROC, Torpedo,AerialRocket,MLRS
Mass=11	             	           // in kg. Used for aircraft. Container mass. Weapon mass is read from weapon ini

[Positions]
NumberOfPositions=1
Position1=0,-0.0038,0
Position2=0,-0.0044,0
Position3=0,-0.0051,0

[Presets]
Preset1=1
Preset2=2
Preset3=3

[Default]
NumberOfAmounts=1
Amount1Presets=Preset1

[MK-82]
NumberOfAmounts=1
Amount1Presets=Preset1

[MK-83]
NumberOfAmounts=1
Amount1Presets=Preset2

[MK-84]
NumberOfAmounts=1
Amount1Presets=Preset3

[Offsets]
Position1=0,-0.002,0 // Centered
Rotation1=0,0,0

Position2=0,-0.0018,0 // 13.5° Right
Rotation2=0,0,13.5

Position3=0,-0.0018,0 // 13.5° Left
Rotation3=0,0,-13.5

[---------- Mesh definitions----------]
############################################################
# Main Model with collider
############################################################
[Models]
############################################################
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=weapons/usn_launchers/
ResourcesRoot=f-4j_adapter.obj
ResourcesMesh=f-4j_adapter
ResourcesMaterialFolder=aircraft/usn_f-4j/
ResourcesMaterial=usn_f-4j_mat