[General]
# Mk-46 Ferry Load
Type=Container                           // can be Projectile, Missile, RBU, ASROC, Torpedo
Mass=230                               // in kg. Used for aircraft
AmmoPoints=460                         // For Supply System. Defines "price" of ammunition based on mass, volume, complexity and availability
SupplyCategory=AirTorpedo              // For Supply System. Makes that presence of such category is required for replenishment of this weapon

[---------- Mesh definitions----------]
[Models]
############################################################
# AssetBundle related
############################################################
AssetBundleMeshes=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMaterials=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMesh=usn_mk46
AssetBundleDamagedMesh=
AssetBundleMaterial=usn_mk46_mat
AssetBundleMeshHullCollider=usn_mk46_coll
############################################################
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=weapons/usn_mk44/
ResourcesRoot=usn_mk44
ResourcesMesh=usn_mk44_dummy
ResourcesMaterial=usn_mk44_mat
