#Launcher for AA-8 / R-60M
[General]
Type=Container                       // can be Projectile, Missile, RBU, ASROC, Torpedo,AerialRocket,MLRS
Mass=39                             // in kg. Used for aircraft. Container mass. Weapon mass is read from weapon ini

[Positions]
Position1=0,-0.003,0.0035
Rotation1=0,0,0

[Presets]
Preset1=1

[Default]
NumberOfAmounts=1
Amount1Presets=Preset1

[---------- Mesh definitions----------]
############################################################
# Main Model with collider
############################################################
[Models]
############################################################
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=weapons/wp_launchers/
ResourcesRoot=wp_apu-60-1.obj
ResourcesMesh=wp_apu-60-1
ResourcesMaterialFolder=aircraft/wp_su-15t/
ResourcesMaterial=wp_su-15t_mat
