[General]
UnitType=LandUnit
LandUnitSubType=MobileUnit

DefaultCameraDistance=0.8
MinCameraDistanceForeAft=0.5
MinCameraDistanceBroadside=0.5
CameraPivotHeight=0.03

GroundOffset=0
AutoFlatten=False
MaskVegetation=True

Length=8.6                    // in meters
Beam=3.14                       // in meters
Range=281.25                      // in miles

# Hull armor: None, Minor, Moderate, Heavy
ArmorType=Minor
DamagePoints=10  //systems damage contribution substracted from this when systems destroyed, when becomes less than zero, the whole unit is considered being destroyed

[Physics]
HorsePower=520
Mass=31                      // in tons

MaxForwardVelocity=29.72      // in knots
MaxBackwardVelocity=5.5      // in knots
Braking=10                     // knots/sec
TurnRate=18                    // in degrees per second

[AI]
UnitScoreValue=1              // value for calculation of mission score
Role=Gun

[ControlSystem]
Collider=coll_hitbox  // makes unit destroyable
Integrity=10

[SensorData]
#Visual
VisualIdentificationRange=2.6  // Camouflaged  (x0.5)
IRSignature=Small
# Radar related (RCS => radar cross section)
RCS=Small

[---------- Sensor Systems ----------]
############################################################
# Sensor Systems
############################################################
[SensorSystems]
NumberOfSensorSystems=3
#---------- Visual ----------
[SensorSystem1] #AdvancedOptics
Type=Visual
SystemName=AdvancedOptics
MountPosition=0,0.03,0

[---------- Weapon Systems ----------]
############################################################
# Weapon Systems
############################################################
[WeaponSystems]
NumberOfWeaponSystems=2

[WeaponSystem1]  #Type_66_G
Type=Gun
SystemName=Type_66_G
#Sensors
#Animations
#Mount
Mount=Turret
IsMountRotatable=True
#Containers
ContainerBase=Gun
NumberOfGuns=1
Gun1=Gun
AreContainersRotatable=True
#Angles
ElevationArc=-5,65
RestAngles=0
#Loading
AssociatedMagazine=WeaponMagazineGun
#Effects
#Other
MaxReactiontime=2.5
VIDIncrease=10  // In miles. Flat base VID increace when firing.

[WeaponSystem2]  #QJC-88
Type=CIWS
SystemName=QJC-88
#Sensors
#Animations
#Mount
Mount=Turret2
IsMountRotatable=True
#Containers
ContainerBase=gun
Gun=gun
AreContainersRotatable=True
#Angles
ElevationArc=-5,75
RestAngles=0,-20
#Loading
AssociatedMagazine=WeaponMagazineQJC-88
#Effects
#Other
MaxVelocityToFire=50
WorksStandalone=True
MaxReactiontime=2.5
VIDIncrease=2.5  // In miles. Flat base VID increace when firing.
TargetAcquisitionTime=0.7

[---------- WeaponMagazines ----------]
[WeaponMagazineGun]
NumberOfAmmunitionTypes=1
Ammunition1=pla_cal_bee7-152
Ammunition1_Count=30

[WeaponMagazineQJC-88]
NumberOfAmmunitionTypes=1
Ammunition1=wp_cal_12.7mm
Ammunition1_Count=500
ModuleType=SmallMagazine



[Models]
############################################################
# Internal Resources folder related
############################################################

ResourcesFolder=assets/models/land_units/plz83/
ResourcesRoot=plz-83.obj
ResourcesMesh=hull
ResourcesMaterial=plz83_mat.ini
############################################################

[Submodels]
Turret1=Turret
Turret2=Turret2
Gun=Gun
Barrel=Barrel
Gun2=gun

[Turret]
Mesh=mount
Material=plz83_mat.ini
Position=0,0,-0.016876

[Gun]
Mesh=gun
Material=plz83_mat.ini
Parent=Turret
Position=0,0.029638,0.009318

[Barrel]
Mesh=barrel
Material=plz83_mat.ini
Parent=Gun
Position=0,0,0

[Turret2]
Mesh=mount2
Material=plz83_mat.ini
Parent=Turret
Position=0.008019,0,0.002736

[gun]
Mesh=gun2
Material=plz83_mat.ini
Parent=Turret2
Position=0,0.046826,0.007584



[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=1
AmbientAudioClip=audio/ships/Ship-Turbine-Small
AmbientAudioPosition=0,0,0
AmbientAudioRollOff=Logarithmic
AmbientAudioDistance=1,20
AmbientAudioPitchRange=1.0,1.6
AmbientAudioVolume=1.0
AmbientAudioAudibility=Above  // layer of sound audibility: Above, Below, AboveAndBelow

[Particles]
SmallFireEffectClass=VehicleSmokes
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=VehicleSmokes
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=VehicleSmokes
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffect=effects/explosions/emitters/missile_hit_ship
SecondaryExplosionEffectPosition=0,0,0

DustEffect=effects/land units/emitters/vehicle_movement_dust
DustEffectPosition=0,0,0

SecondaryPopPrefab=effects/land units/emitters/secondary_pop
TurretCookOffEffect=effects/land units/emitters/turret_cook-off
TurretFireEffect=effects/land units/emitters/turret_fire
TurretFireEffectPosition=0,0.025,0

[---------- Colliders ----------]
[Colliders]
UseKinematicCollision=False
NumberOfMeshColliders=0
NumberOfColliders=2

Collider1=coll_hitbox
Collider2=coll_collider

[coll_hitbox]
Collider=Box
Position=0,0.0152,-0.01
Rotation=0,0,0
Scale=0.045,0.03,0.09

[coll_collider]
Collider=Box
Position=0,0.0028,-0.0023
Rotation=0,0,0
Scale=0.03,0.005,0.05
Layer=Default
