[General]
UnitType=LandUnit
LandUnitSubType=MobileUnit
IsMobile=True

DefaultCameraDistance=0.8
MinCameraDistanceForeAft=0.4
MinCameraDistanceBroadside=0.4
CameraPivotHeight=0.03

GroundOffset=0
AutoFlatten=False
MaskVegetation=True

Length=14                     // in meters
Beam=3.3                       // in meters
Range=525.0                      // in miles

# Hull armor: None, Minor, Moderate, Heavy
ArmorType=Minor
DamagePoints=5  //systems damage contribution substracted from this when systems destroyed, when becomes less than zero, the whole unit is considered being destroyed

[Physics]
HorsePower=520
Mass=30                        // in tons

MaxForwardVelocity=20          // in knots
MaxBackwardVelocity=5          // in knots
Braking=13                     // knots/sec
TurnRate=15                    // in degrees per second

[AI]
UnitScoreValue=1               // value for calculation of mission score
Role=ASuW,ASM

[ControlSystem]
Collider=coll_hitbox  // makes unit destroyable
Integrity=5

[SensorData]
#Visual
VisualIdentificationRange=5  // Camouflaged  (x0.5)
IRSignature=Small
# Radar related (RCS => radar cross section)
RCS=Small

[---------- Sensor Systems ----------]
############################################################
# Sensor Systems
############################################################
[SensorSystems]
NumberOfSensorSystems=2
#---------- Visual ----------
[SensorSystem1] #Bridge
# Bridge. Does not need SystemGroup and Collider because we do not want ship to loose ability to VID targets
Type=Visual
SystemName=Optics
Mount=Dummy
MountPosition=0,0.04,0
ModuleType=Bridge
Integrity=0

[---------- Weapon Systems ----------]
############################################################
# Weapon Systems
############################################################
[WeaponSystems]
NumberOfWeaponSystems=1

[WeaponSystem1]  #
Type=Missile
SystemName=DF10ALAND
#Sensors
#Animations
#Mount
Mount=Dummy
MountRotatable=False
#Containers
NumberOfContainers=1
ContainerBase=launchpad
Container1=launchpad
AreContainersRotatable=True
#Angles
FixVerticalLaunchAngle=20
FiringArcs=-45,45
ElevationArc=0,20
#Loading
AssociatedMagazine=WeaponMagazineMissile
PreloadAmmunition=False
ForceMoveToLoadPosition=False
#Effects
#Other
MaxReactiontime=15          //最大随机反应时间
DisplayWeaponsOnSystem=True
ModuleType=Weapon
Collider=coll_hitbox
Integrity=4
VIDIncrease=15  // In miles. Flat base VID increace when firing.

[---------- WeaponMagazines ----------]
[WeaponMagazineMissile]
NumberOfAmmunitionTypes=1
Ammunition1=pla_df-10a
Ammunition1_Count=3
ModuleType=WeaponMagazine

[Models]
############################################################
# Internal Resources folder related
############################################################

ResourcesFolder=assets/models/land_units/df10aland/
ResourcesRoot=df10aland.obj
ResourcesMesh=body
ResourcesMaterial=df10aland_mat.ini
############################################################

[Submodels]
Submodel1=launchpad

[launchpad]
Mesh=launchpad
Parent=body
Position=0.024255,0.02663,-0.056708
Rotation=0,0,0
Material=df10aland_mat.ini

[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=1
AmbientAudioClip=audio/ships/Ship-Turbine-Small
AmbientAudioPosition=0,0,0
AmbientAudioRollOff=Logarithmic
AmbientAudioDistance=1,20
AmbientAudioPitchRange=1.0,1.6
AmbientAudioVolume=1.0
AmbientAudioAudibility=Above  // layer of sound audibility: Above, Below, AboveAndBelow

[Particles]
SmallFireEffectClass=SmallShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=ModerateShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=SevereShipFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffect=effects/explosions/emitters/missile_hit_ship
SecondaryExplosionEffectPosition=0,0,0

[---------- Colliders ----------]
############################################################
# Colliders definition
############################################################
[Colliders]
UseKinematicCollision=False
NumberOfMeshColliders=0
NumberOfColliders=2

Collider1=coll_hitbox
Collider2=coll_collider

[coll_hitbox]
Collider=Box
Position=0,0.01742,-0.0023
Rotation=0,0,0
Scale=0.04,0.035,0.07
Layer=Default

[coll_collider]
Collider=Box
Position=0,0.0028,-0.0023
Rotation=0,0,0
Scale=0.03,0.005,0.05
Layer=Default