[General]
UnitType=LandUnit
LandUnitSubType=MobileUnit

DefaultCameraDistance=0.8
MinCameraDistanceForeAft=0.4
MinCameraDistanceBroadside=0.4
CameraPivotHeight=0.04

GroundOffset=0
AutoFlatten=False
MaskVegetation=True

Length=7.2                     // in meters
Beam=3.2                       // in meters
Range=375                      // in miles

# Hull armor: None, Minor, Moderate, Heavy
ArmorType=Minor
DamagePoints=10  //systems damage contribution substracted from this when systems destroyed, when becomes less than zero, the whole unit is considered being destroyed

[Physics]
HorsePower=465
Mass=25                      // in tons

MaxForwardVelocity=45        // in knots
MaxBackwardVelocity=7.5          // in knots
Braking=12                     // knots/sec
TurnRate=35                    // in degrees per second

[AI]
UnitScoreValue=1               // value for calculation of mission score
Role=Gun

[ControlSystem]
Collider=coll_hitbox  // makes unit destroyable
Integrity=10

[SensorData]
#Visual
VisualIdentificationRange=2.5  // Camouflaged  (x0.5)
IRSignature=Small
# Radar related (RCS => radar cross section)
RCS=Small

[Animations]
NumberOfAnimationReferences=1
AnimationFile_1=animations_usa_ifv_bradley

[---------- Sensor Systems ----------]
############################################################
# Sensor Systems
############################################################
[SensorSystems]
NumberOfSensorSystems=2
#---------- Visual ----------
[SensorSystem1] #AdvancedOptics
Type=Visual
SystemName=AdvancedOptics
MountPosition=0,0.04,0

[SensorSystem2] #IRSight
Type=Infrared
SystemName=IRSight
MountPosition=0,0.03,0

[---------- Weapon Systems ----------]
############################################################
# Weapon Systems
############################################################
[WeaponSystems]
NumberOfWeaponSystems=4

[WeaponSystem1]  #2A42
Type=CIWS
SystemName=ZPL02
#Sensors
#Animations
#Mount
Mount=Turret
IsMountRotatable=True
#Containers
ContainerBase=Gun
Gun=Barrel2
AreContainersRotatable=True
#Angles
ElevationArc=-6,60
RestAngles=0
#Loading
AssociatedMagazine=WeaponMagazineGun
#Effects
#Other
MaxVelocityToFire=10
VIDIncrease=4  // In miles. Flat base VID increace when firing.
SharesMountWith=WeaponSystem2,WeaponSystem3

[WeaponSystem2]  #2A70
Type=Gun
SystemName=ZPL04
#Sensors
#Animations
#Mount
Mount=Turret
IsMountRotatable=True
#Containers
ContainerBase=Gun
NumberOfGuns=1
Gun1=Barrel1
AreContainersRotatable=True
#Angles
ElevationArc=-6,60
RestAngles=0
LoadAngles=0,-5
EngageOnlyInsideArc=True
#Loading
AssociatedMagazine=WeaponMagazineGun2
#Effects
#Other
MaxVelocityToFire=10
VIDIncrease=8  // In miles. Flat base VID increace when firing.
SharesMountWith=WeaponSystem1,WeaponSystem3

[WeaponSystem3]  
Type=Missile
SystemName=ZPL04_Missile
#Sensors
#Animations
#Mount
Mount=Turret
IsMountRotatable=True
#Containers
ContainerBase=Gun
NumberOfContainers=1
Container1=Barrel1
AreContainersRotatable=True
#Angles
FixVerticalLaunchAngle=5
ElevationArc=-6,60              // Min,Max
RestAngles=0                   //Horizontal, Vertical   or  Horizontal only definitions
LoadAngles=0,-5
#Loading
AssociatedMagazine=WeaponMagazine9M119
PreloadAmmunition=True           // REQUIRED!!! for non-unloading launchers with magazine, like MK29 and ASROC
#Effects
#Other
MaxVelocityToFire=10
SharesMountWith=WeaponSystem1,WeaponSystem2
VIDIncrease=6  // In miles. Flat base VID increace when firing.

[WeaponSystem4] #Chaff
Type=Chaff
SystemName=Smoke
#Sensors
#Animations
#Mount
Mount=Dummy
MountPosition=0,0,0.4
#Containers
ContainerBase=Dummy
#Angles
#Loading
Ammunition=wp_aircraft_chaff
#Effects
NumberOfEffects=2
DelayBetweenLaunches=0.1
EffectOffset=0,0,30
#Other
WorksStandalone=True

[---------- WeaponMagazines ----------]
[WeaponMagazine9M119]
NumberOfAmmunitionTypes=1
Ammunition1=pla_aps03
Ammunition1_Count=4

[WeaponMagazineGun2]
NumberOfAmmunitionTypes=1
Ammunition1=pla_3of70
Ammunition1_Count=36
ModuleType=SmallMagazine

[WeaponMagazineGun]
NumberOfAmmunitionTypes=2
Ammunition1=pla_dtc10-30
Ammunition1_Count=195
Ammunition2=pla_dty02-30
Ammunition2_Count=305
ModuleType=SmallMagazine

[Models]
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=assets/models/land_units/zbd-04a/
ResourcesRoot=zbd-04a.obj
ResourcesMesh=hull
ResourcesMaterial=zbd-04a_mat.ini
############################################################

[Submodels]
Turret=Turret
Langan=Langan
Gun=Gun
Barrel1=Barrel1
Barrel2=Barrel2

[Turret]
Mesh=turret
Material=zbd-04a_mat.ini
Position=-0.001799,0.030696,-0.012881

[Langan]
Mesh=Langan
Material=zbd-04a_langan_mat.ini
Parent=Turret

[Gun]
Mesh=gun
Material=zbd-04a_mat.ini
Parent=Turret
Position=-0.00166,0,0.010071
Rotation=0,0,0

[Barrel1]
Mesh=barrel1
Material=zbd-04a_mat.ini
Parent=Gun
Position=0,0,0
Rotation=0,0,0

[Barrel2]
Mesh=barrel2
Material=zbd-04a_mat.ini
Parent=Gun
Position=0.002368,0,0
Rotation=0,0,0


[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=1
AmbientAudioClip=audio/ships/Ship-Turbine-Small
AmbientAudioPosition=0,0,0
AmbientAudioRollOff=Logarithmic
AmbientAudioDistance=1,20
AmbientAudioPitchRange=1.0,1.6
AmbientAudioVolume=1.0
AmbientAudioAudibility=Above  // layer of sound audibility: Above, Below, AboveAndBelow

[Particles]
SmallFireEffectClass=SmallShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=ModerateShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=SevereShipFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffect=effects/explosions/emitters/missile_hit_ship
SecondaryExplosionEffectPosition=0,0,0

[---------- Colliders ----------]
[Colliders]
UseKinematicCollision=False
NumberOfMeshColliders=0
NumberOfColliders=2

Collider1=coll_hitbox
Collider2=coll_collider

[coll_hitbox]
Collider=Box
Position=0,0.0197,0
Rotation=0,0,0
Scale=0.045,0.04,0.1

[coll_collider]
Collider=Box
Position=0,0.0028,-0.0023
Rotation=0,0,0
Scale=0.03,0.005,0.05
Layer=Default
