[General]
UnitType=LandUnit
LandUnitSubType=SAM
IsMobile=True

DefaultCameraDistance=0.8
MinCameraDistanceForeAft=0.3
MinCameraDistanceBroadside=0.3
CameraPivotHeight=0.05

GroundOffset=0
AutoFlatten=False
MaskVegetation=True

# Hull armor: None, Minor, Moderate, Heavy
ArmorType=None
DamagePoints=5  //systems damage contribution substracted from this when systems destroyed, when becomes less than zero, the whole unit is considered being destroyed

[AI]
UnitScoreValue=1              // value for calculation of mission score
Role=AAW,SAM

[SensorData]
#Visual
VisualIdentificationRange=2.5  // Camouflaged  (x0.5)
IRSignature=Small
# Radar related (RCS => radar cross section)
RCS=Small

[---------- Sensor Systems ----------]
############################################################
# Sensor Systems
############################################################
[SensorSystems]
NumberOfSensorSystems=2
#---------- Visual ----------
[SensorSystem1] #Bridge
# Bridge. Does not need SystemGroup and Collider because we do not want ship to loose ability to VID targets
Type=Visual
SystemName=Optics
Mount=Dummy
MountPosition=0,0.024,0.05
ModuleType=Bridge
Integrity=0

[SensorSystem2]  #Search
Type=Radar
SystemName=HQ-7_Search
Mount=Radar
ModuleType=Sensor

[---------- Weapon Systems ----------]
############################################################
# Weapon Systems
############################################################
[WeaponSystems]
NumberOfWeaponSystems=0

[Models]
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=assets/models/land_units/hq-7/
ResourcesRoot=hq-7b_radar.obj
ResourcesMesh=hull
ResourcesMaterialFolder=assets/models/land_units/hq-9/
ResourcesMaterial=hq-9_tel_mat.ini
############################################################

[Submodels]
Radar=Radar

[Radar]
Mesh=radar
ResourcesMaterialFolder=assets/models/land_units/hq-9/
Material=hq-9_tel_mat.ini
Position=0,0.05289,-0.004263

[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=1
AmbientAudioClip=audio/ships/Ship-Turbine-Medium
AmbientAudioPosition=0,0,-0.35
AmbientAudioRollOff=Logarithmic
AmbientAudioDistance=1,20
AmbientAudioPitchRange=1.0,1.6
AmbientAudioVolume=1.0
AmbientAudioAudibility=Above  // layer of sound audibility: Above, Below, AboveAndBelow

[Particles]
SmallFireEffectClass=SmallShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=ModerateShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=SevereShipFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffect=effects/explosions/emitters/missile_hit_ship
SecondaryExplosionEffectPosition=0,0,0

[---------- Colliders ----------]
############################################################
# Colliders definition
############################################################
[Colliders]
UseKinematicCollision=False
NumberOfMeshColliders=0
NumberOfColliders=3

Collider1=coll_hitbox
Collider2=coll_radar
Collider3=coll_collider

[coll_hitbox]
Collider=Box
Position=0,0.026,0
Rotation=0,0,0
Scale=0.04,0.05,0.1

[coll_radar]
Collider=Sphere
Position=0,0.055,-0.0125
Rotation=0,0,0
Scale=0.04,0.04,0.04

[coll_collider]
Collider=Box
Position=0,0.0028,-0.0023
Rotation=0,0,0
Scale=0.03,0.005,0.05
Layer=Default
