[ ------------------------ Visual/Infared ------------------------- ]

[EORD-50 EOTS] #EOTS part of EORD-50 EOTS system
#Users: plan_j-50
Kind=Visual
Infrared=True
VIDRangeMultiplier=4.0            // Target VID range multiplied by this for identification check. 0 means it cannot identify
MaxRangeMultiplier=6.3            // Target VID range multiplied by this for detection check. Can not be less then VID multiplier
LookDownMultiplier=1.4           // Final VID/Detection range is multiplied by this in case when target observed on surface background
NightVisionLevel=1.0              // the portion of full daylight added to the visibility level where 1 is roughly a mid-day

[------------------------- Radar ---------------------------]

[---Air/Air&Surface---]

[KLJ-50]  #Byelka AESA Radar Complex System.
#Users: plan_j-50
Kind=Radar
Type=DirectedSearch         // Classes can be "DirectedSearch", "Search", "Targeting"
HasDataLink=True            // true means the sensor data will be used for the entire task force via data link, false local use only
Role=AirAndSurface          // Role can be "Surface", "Air", "AirAndSurface"
CanDetectLandTargets=True   // True means the radar can see ground objects
Mode=Illuminate             // Can be "Illuminate", "RadioCommand"
TargetChannels=64           // if applicable number of targets it can track simultaneously
WeaponChannels=16           // if applicable number of weapons (missiles) it can guide simultaneously
ViewArcs=-90,90|-85,75         // pair of values left to | is horisontal left-right angles of vision, second pair is down-up vertical angles
LookDownMultiplier=1     // multiplier that applies to max radar range when target is projected on terrain/sea background, default is 1.0
MinRange=0.2                // min range in km
MaxRange=382.4                // max range in km
MinAltitude=0               // min altitude in meters, relevant for air, unused for surface
MaxAltitude=60960           // max altitude in meters, relevant for air, unused for surface
RangeResolution=8          // defines the minimum range where two targets behind can be recognized as two; in meters
BeamWidth=1.2               // defines the beam width in degrees for BearingResolution >= 2*Dist*sin(BeamWidth/2)
Gain=55.0                   // gain in dB on the sensor
Frequency=X-Band            // frequency band
PeakPower=105.0             // output peak power in kW
RequiresAlignment=True      // For aircraft. Allows guide weapon without flying towards target

[---------------------------------------- ESM ----------------------------------------]

[RKL-50_ESM] # RWR system
#Users: plan_j-50
Kind=ESM
Type=RWR
Gain=32                             // gain of sensor in dB
HasDataLink=True                   // true means the sensor data will be used for the entire task force via data link, false local use only
AngularResolution=15.0              // in degrees
Frequencies=All          // Frequencies that current ESM system can detect


[RKL-50] 
#Users: plan_j-50
Kind=ESM
Gain=32                             // gain of sensor in dB
HasDataLink=True                   // true means the sensor data will be used for the entire task force via data link, false local use only
IdentificationRate=1.1
AngularResolution=5.0              // in degrees
Frequencies=All           // Frequencies that current ESM system can detect
OverHorizonMultiplier=1.4           // The multiplier for ESM horizon for over horison (OTH) passive detection capability


[ ------------------------------ ECM ------------------------------ ]

[RKZ-50] #Himalayas ECM Systems
#Users: plan_j-50
Kind=ECM
Frequencies=L-Band,S-Band,C-Band,X-Band,Ku-Band,K-Band,Ka-Band // radar frequency bands the ECM suite can jam
Type=Defensive                         // can be Defensive, Offensive, Universal
JamChance=0.7                          // For Defensive and Universal jammers. Base chance to jam the attacking weapon
CoverRange=10                           // in nmi, If within this range from attacked unit and within weapon seeker cone, jammer will add to combined chance to jam weapon.


