[Shader]
Path=Marmoset/Bumped Specular IBL

#[Properties]
_Color=Color,{}808080ff
_SpecColor=Color,{}ffffffff
_SpecInt=Float,1.0
_Shininess=Float,6.5
_Fresnel=Float,0.75
[Textures]

_MainTex=assets/europack/materials/Millennium_Gun/melenium_DefaultMaterial_Diffuse.png
_SpecTex=assets/europack/materials/Millennium_Gun/melenium_DefaultMaterial_Specular.png
_BumpMap=assets/europack/materials/Millennium_Gun/melenium_DefaultMaterial_Normal.png
