[ ------------------------ Radar ------------------------- ]
[IRSignature]
Zero=0
VeryTiny=0.001
Tiny=0.01
VerySmall=0.1
Small=1.0
SemiSmall=10.0
Meager=50.0
Medium=100.0
SemiLarge=1000.0
Large=10000.0
VeryLarge=100000.0

[AN/APG-78]
#Users: usa_ah-64d
Kind=Radar
Type=DirectedSearch             // Classes can be "Search", "Targeting"
HasDataLink=True       // true means the sensor data will be used for the entire task force via data link, false local use only
Role=AirAndSurface           // Role can be "Surface", "Air", "AirAndSurface"
CanDetectLandTargets=True  // True means the radar can see ground objects
ViewArcs=-181,181|-30,30      // pair of values left to | is horisontal left-right angles of vision, second pair is down-up vertical angles
LookDownMultiplier=0.9      // multiplier that applies to max radar range when target is projected on terrain/sea background, default is 1.0
Mode=Illuminate        // Can be "Illuminate", "RadioCommand"
RotationDirection=1    // -1 means left, 1 means right
TargetChannels=256       // if applicable number of targets it can track simultaneously
WeaponChannels=16       // if applicable number of weapons (missiles) it can guide simultaneously
RPM=10                 // revolutions per minute
MinRange=0.3        // (400 m)
MaxRange=16         // (40 nmi)
MinAltitude=0          // min altitude in meters, relevant for air, unused for surface
MaxAltitude=4000          // max altitude in meters, relevant for air, unused for surface
RangeResolution=15    // defines the minimum range where two targets behind can be recognized as two; in meters
BeamWidth=1.1         // defines the beam width in degrees for BearingResolution >= 2*Dist*sin(BeamWidth/2)
Gain=140               // gain in dB on the sensor
Frequency=Ka-Band      // frequency band
PeakPower=25         // output peak power in kW
ModuleType=SmallSensor

[AN/APS-64]
#Users: usn_ah-64a
Kind=Radar
Type=DirectedSearch             // Classes can be "Search", "Targeting"
HasDataLink=True       // true means the sensor data will be used for the entire task force via data link, false local use only
Role=Surface           // Role can be "Surface", "Air", "AirAndSurface"
CanDetectLandTargets=True  // True means the radar can see ground objects
ViewArcs=-181,181|-30,30      // pair of values left to | is horisontal left-right angles of vision, second pair is down-up vertical angles
LookDownMultiplier=0.9      // multiplier that applies to max radar range when target is projected on terrain/sea background, default is 1.0
Mode=Illuminate        // Can be "Illuminate", "RadioCommand"
RotationDirection=1    // -1 means left, 1 means right
TargetChannels=8       // if applicable number of targets it can track simultaneously
WeaponChannels=4       // if applicable number of weapons (missiles) it can guide simultaneously
RPM=10                 // revolutions per minute
MinRange=0.2           // min range in km
MaxRange=280           // max range in km
MinAltitude=0          // min altitude in meters, relevant for air, unused for surface
MaxAltitude=0          // max altitude in meters, relevant for air, unused for surface
RangeResolution=30    // defines the minimum range where two targets behind can be recognized as two; in meters
BeamWidth=1.1         // defines the beam width in degrees for BearingResolution >= 2*Dist*sin(BeamWidth/2)
Gain=44               // gain in dB on the sensor
Frequency=X-Band      // frequency band
PeakPower=15         // output peak power in kW
ModuleType=SmallSensor
CanDetectPeriscope=True
[ ------------------------ Visual/Infared ------------------------- ]

[AN/ASQ-170_TADS/PNVS] #AN/ASQ-170 TADS IR Navigation/targeting detector
Kind=Visual
#Infrared
VIDRangeMultiplier=2.2          // Target VID range multiplied by this for identification check. 0 means it cannot identify
MaxRangeMultiplier=2.9           // Target VID range multiplied by this for detection check. Can not be less then VID multiplier
LookDownMultiplier=0.7            // Final VID/Detection range is multiplied by this in case when target observed on surface background
NightVisionLevel=1             // the portion of full daylight added to the visibility level where 1 is roughly a mid-day

[AN/ASQ-170_M-TADS/PNVS] #AN/ASQ-170 TADS IR Navigation/targeting detector
Kind=Visual
#Infrared
VIDRangeMultiplier=2.6          // Target VID range multiplied by this for identification check. 0 means it cannot identify
MaxRangeMultiplier=3.4           // Target VID range multiplied by this for detection check. Can not be less then VID multiplier
LookDownMultiplier=0.7            // Final VID/Detection range is multiplied by this in case when target observed on surface background
NightVisionLevel=1             // the portion of full daylight added to the visibility level where 1 is roughly a mid-day

[---------------------------------------- Laser Designator ---------------------------]

[AN/ASQ-170_Laser] #AN/ASQ-170 Pave Spike
Kind=LaserDesignator
MaxRange=10.0                       // max distance in nm
NightCapable=True                   // is the designator can be used in low-visibility conditions
TargetChannels=1                    // number of targets that can be tracked at once
WeaponChannels=1000                 // if applicable number of weapons (missiles) it can guide simultaneously
ViewArcs=360.0                           // Field of View of the designator