[---------- General Data ----------]
[General]
UnitType=Submarine
DefaultCameraDistance=3.0
MinCameraDistanceForeAft=1.2
MinCameraDistanceBroadside=0.5
CameraPivotHeight=0.1

Length=58                    // in meters
Beam=6.8                       // in meters

# Hull armor: None, Minor, Moderate, Heavy
ArmorType=None

[---------- Physics and Control ----------]
[Physics]
# all damping values can go from 0 (max damping) up to 1 (no damping)
Displacement=1038               // in tons

MaxForwardVelocity=15.0        // sets the max forward velocity
MaxForwardVelocitySurfaced=15.0
MaxBackwardVelocitySurfaced=5.0
MaxBackwardVelocity=5.0        // sets the max backward velocity
TelegraphVelocities=-5,0,5,10,15

BowUnderWater=19.0             // depth in feet, when bow is under water and submerged speeds are used
SailUnderWater=40.0            // depth in feet, from where the sail is under water
LinearDrag=0.92                // this is for velocity damping (linear drag)
MaxAccelerationFactor=2.4
MinAccelerationFactor=0.2

RudderTurnRate=5.0             // turn rate of the rudder in degrees per second
DepthRudderTurnRate=5.0        // turn rate of the depth rudders in degrees per second
RudderForce=0.7                // multiplicator defining how agile the ship can turn

MaxPitchAngle=85.0
PitchChangeRate=2.0
MaxRollAngle=85.0
RollChangeRate=5.0

BallastTankChangeRate=0.00025  // just a multiplicator how quickly the sub reaches max dive rate
MaxDepthChangeUsingTanks=5.0   // in feet per second using ballast tanks only (no propulsion)

TrimDepth=0                 // default trim depth in feet
TrimAngle=0                 // default base trim angle (x-axis, so pitch)
#TrimAngle=-0.1                 // default base trim angle (x-axis, so pitch)
CenterToKeelDist=-0.068        // distance from the center of the mesh to the keel in Unity units

PeriscopeDepth=50.0            // in feet
CrushDepth=5950.0              // in feet

#Cavitation table
#10kts @ 150ft
#15kts @ 200ft
#20kts @ 300ft
#25kts @ 400ft

[Buoyancy]
Density=0.45                    // density of water is 1. Density < 1 means it will swim
OutOfWaterDrag=25.0            // drag for the water physics in case the vessel is above the water line
SubmergedDrag=25.0             // drag for the water physics in case the vessel is below the water line

[SensorData]
#Visual
VisualIdentificationRange=5.0  // Biggest range in nm at which this unit can be visually identified
IRSignature=Small
# Radar related (RCS => radar cross section)
RCS=Small
# Sonar related
BaseNoise=130                  // base sound level in db at 1m distance
FlowNoise=1.2                  // additional flow noise per knot in db (20kn would be +20db)
TargetReflectionStrength=15    // in dB for broad side
DistinctiveNoise=False         //If True, this vessel can be identified easier than usually by passive sonars

[---------- AI related ----------]
[AI]
UnitCostValue=6000            // value for the unit cost for least valuable target checks
UnitScoreValue=5              // value for calculation of mission score

#Sensors
Radar_Capability=TBD
Sonar_Capability=TBD

#Offence
AAW_Capability=0
ASuW_Capability=0
ASW_Capability=1

#Defence
#Special
Role=SSN

[---------- Main Systems ----------]
#Control System
[ControlSystem]
Collider=coll_cic
ModuleType=CIC

#Movement Systems
[MainPowerSystem]
Type=Electric
HorsePower=15000
Collider=coll_engineroom

[---------- Sensor Systems ----------]
############################################################
# Sensor Systems
############################################################
[SensorSystems]
NumberOfSensorSystems=1
#---------- Visual ----------
[SensorSystem1] #Tower_Watch
# Bridge. Does not need SystemGroup and Collider because we do not want ship to loose ability to VID targets
Type=Visual
SystemName=Optics
Mount=Dummy
MountPosition=0,0.17,0.333
ModuleType=Inert

[Models]
############################################################
# AssetBundle related
############################################################
AssetBundleMeshes=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMaterials=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMesh=biologic_blue_whale
AssetBundleDamagedMesh=biologic_blue_whale_d
AssetBundleMaterial=biologic_blue_whale_mat
AssetBundleMeshHullCollider=biologic_blue_whale_coll_hull
############################################################
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=ships/biologic_blue_whale/
ResourcesRoot=biologic_blue_whale
ResourcesMesh=biologic_blue_whale_body
ResourcesMaterial=biologic_blue_whale_mat

############################################################
NumberOfSubModels=6

SubModel1=Left_Flipper
SubModel2=Right_Flipper
SubModel3=Spine_1
SubModel4=Spine_2
SubModel5=Spine_3
SubModel6=Tail

############################################################
# Fuselage
############################################################

[Left_Flipper]
Mesh=biologic_blue_whale_flipper_left
Material=biologic_blue_whale_mat
Position=-0.023,-0.013,0.007

[Right_Flipper]
Mesh=biologic_blue_whale_flipper_right
Material=biologic_blue_whale_mat
Position=0.023,-0.013,0.007

[Spine_1]
Mesh=biologic_blue_whale_spine_1
Material=biologic_blue_whale_mat
Position=0,0,-0.052
Rotation=-2.5,0,0

[Spine_2]
Mesh=biologic_blue_whale_spine_2
Material=biologic_blue_whale_mat
Parent=Spine_1
Position=0,-0.003,-0.088
Rotation=-5,0,0

[Spine_3]
Mesh=biologic_blue_whale_spine_3
Material=biologic_blue_whale_mat
Parent=Spine_2
Position=0,-0.0022,-0.0465
Rotation=-10,0,0

[Tail]
Mesh=biologic_blue_whale_tail
Material=biologic_blue_whale_mat
Parent=Spine_3
Position=0,-0.0023,-0.0455
Rotation=15,0,0

[---------- Effects ----------]
[Particles]
SmallFireEffectClass=SmallShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=ModerateShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=SevereShipFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffectClass=SecondaryExplosions
SecondaryExplosionEffectPosition=0,0,0
#kill explosion will be played to switch over to the damage model
KillExplosionEffect=effects/explosions/emitters/missile_hit_ship_3
KillExplosionEffectPosition=0,0.2,-0.05
SubmarineImplosionEffect=effects/explosions/emitters/submarine_implosion
OilSlickEffect=effects/damage/emitters/OilSlick_Medium
OilSlickEffectPosition=0,0,0
SinkingBubblesEffect=effects/ships/emitters/sinkingbubbles_sub
SinkingBubblesEffectPosition=0,0,0
BowWave=ships/particles/bowwave_small
PropWash=ships/particles/bowwave
SailWave=ships/particles/bowwave_small
MastWave=ships/particles/periwave
Cavitation=ships/particles/pns_ss_hangor_cavitation
EmergencyBlow=ships/particles/pns_ss_hangor_emergency_blow
Bubbles=ships/particles/pns_ss_hangor_bubbles
DiveVents=ships/particles/pns_ss_hangor_dive_vents
BowWavePosition=0,0,0.42
PropWashPosition=0,-0.025,-0.42
SailWavePosition=0,0,0.0787
MastWavePeriscopePosition=0,0,0.0484
MastWaveRadarPosition=0,0,0.0674
MastWaveESMPosition=0,0,0.0332
MastWaveSnorkelPosition=0,0,-0.004

############################################################
# Foam
############################################################

[Foam]
HullFoamTexture=ships/particles/wake/Ceto_Hullwake
HullFoamPosition=0,0,0.2
HullFoamDuration=35
HullFoamSize=0.25
HullFoamSpacing=0.15
HullFoamExpansion=0.025
HullFoamMomentum=0
HullFoamSpin=0
HullFoamAlpha=2
HullFoamJitter=0.25

SternFoamTexture=ships/particles/wake/Ceto_Propwash
SternFoamPosition=0,0,-0.42
SternFoamDuration=45
SternFoamSize=0.25
SternFoamSpacing=0.1
SternFoamExpansion=0.025
SternFoamMomentum=0.01
SternFoamSpin=0
SternFoamAlpha=2
SternFoamJitter=0.25

SailFoamTexture=ships/particles/wake/Ceto_Hullwake
SailFoamPosition=0,0,0.029
SailFoamDuration=35
SailFoamSize=0.1
SailFoamSpacing=0.1
SailFoamExpansion=0.025
SailFoamMomentum=0
SailFoamSpin=0
SailFoamAlpha=2
SailFoamJitter=0.25

MastFoamTexture=ships/particles/wake/mastwave
MastFoamPosition=0,0,-0.0973
MastFoamDuration=5
MastFoamSize=0.25
MastFoamSpacing=0.1
MastFoamExpansion=0.025
MastFoamMomentum=0
MastFoamSpin=0
MastFoamAlpha=2
MastFoamJitter=0.25

OverlayHeightTexture=ships/particles/wake/bowwave_hm
OverlayHeightMaskTexture=ships/particles/wake/bowwave_hm
OverlayHeightMaxAlpha=0.1
OverlayNormalTexture=ships/particles/wake/bowwave_normal
OverlayNormalMaskTexture=ships/particles/wake/bowwave_normal
OverlayNormalMaxAlpha=10.0
OverlayFoamTexture=ships/particles/wake/bowwave_tx2
OverlayFoamMaskTexture=ships/particles/wake/bowwave_mask
OverlayFoamMaxAlpha=1.0
OverlayOffset=0.0
KelvinWaves=1.5,1.5
VelocityForMaxParticles=15  // velocity in knots from where on the particles shall show maximum effect

############################################################
# Sounds
############################################################

[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=1
EngineAudioClip=audio/submarine/Electric_Sub_v1
EngineAudioPosition=0,0,0
EngineAudioRollOff=Logarithmic
EngineAudioDistance=1.0,20
EngineAudioPitchRange=1.0,1.8
EngineAudioVolume=1.0
EngineAudioAudibility=AboveAndBelow  // layer of sound audibility: Above, Below, AboveAndBelow
AuxEngineAudioClip=audio/submarine/Electric_Sub_v1
AuxEngineAudioPosition=0,0,0
AuxEngineAudioRollOff=Logarithmic
AuxEngineAudioDistance=1.0,20
AuxEngineAudioPitchRange=1.0,1.8
AuxEngineAudioVolume=0.5
AuxEngineAudioAudibility=AboveAndBelow  // layer of sound audibility: Above, Below, AboveAndBelow
PropAudioClip=audio/submarine/Submarine-Propeller
PropAudioPosition=0,0,-0.68
PropAudioRollOff=Logarithmic
PropAudioDistance=1,20
PropAudioPitchRange=0.5,1.0
PropAudioVolume=0.5
PropAudioAudibility=Below  // layer of sound audibility: Above, Below, AboveAndBelow
FlowAudioClip=audio/ships/Ship-Flow
FlowAudioPosition=0,0,0
FlowAudioRollOff=Logarithmic
FlowAudioDistance=1,20
FlowAudioPitch=1
FlowAudioVolume=0.5
FlowAudioAudibility=AboveAndBelow  // layer of sound audibility: Above, Below, AboveAndBelow
SonarAudioClip=audio/environment/Sonar-MF
SonarAudioPosition=0,0,0
SonarAudioRollOff=Logarithmic
SonarAudioDistance=1,50
SonarAudioPitch=1
SonarAudioVolume=1
SonarAudioAudibility=Below  // layer of sound audibility: Above, Below, AboveAndBelow

[---------- Colliders ----------]
[Colliders]
UseKinematicCollision=False

NumberOfMeshColliders=0
NumberOfColliders=2


Collider1=coll_cic
Collider2=coll_engineroom

[coll_cic]
Collider=Box
Position=0,-0.0105,0.017
Rotation=0,0,0
Scale=0.065,0.05,0.07





[coll_engineroom]
Collider=Box
Position=0,-0.0105,-0.125
Rotation=0,0,0
Scale=0.05,0.05,0.2