[LoadoutNames]
#------------------------------------------ New system ------------------------------------------
# - LongRange means operating range of aircraft, not the weapons range
# ---------- Mandatory loadouts ----------
# ---------- Anti Air loadouts ----------
# ---------- Anti Surface loadouts ----------
StandoffNuclear=防区外攻击（核弹头）
StandoffLongRange=远程防区外攻击
StandoffNuclearLongRange=远程防区外攻击（核弹头）
# ---------- Anti Ship loadouts ----------
AntiShipNuclear=反舰（核弹头）
AntiShipHeavyLongRange=远程重型反舰
AntiShipNuclearLongRange=远程反舰（核弹头）
# ---------- Anti Sub loadouts ----------
# ---------- Special loadouts ----------