[LoadoutNames]
#------------------------------------------ New system ------------------------------------------
# - LongRange means operating range of aircraft, not the weapons range
# ---------- Mandatory loadouts ----------
AirToAirIntercept=AirToAirIntercept
StrikeJDAM=打击（JDAM）
StrikeJDAM2=打击（JDAM2）
Strike130=打击（AGM130）
StrikeSDB=打击（SDB）