[Animations]
NumberOfAnimations=6

Animation1=Flaps_Takeoff
Animation2=Flaps_Takeoff_Retract
Animation3=Flaps_Landing
Animation4=Flaps_Landing_Retract
Animation5=Gear_Extend
Animation6=Gear_Retract

[Flaps_Takeoff]
NumberOfSequencesToPlay=2
Sequence1=Left_Flap_Takeoff
Sequence1_Model=Left_Flap
Sequence2=Right_Flap_Takeoff
Sequence2_Model=Right_Flap

[Flaps_Takeoff_Retract]
NumberOfSequencesToPlay=2
Sequence1=Left_Flap_Takeoff_Retract
Sequence1_Model=Left_Flap
Sequence2=Right_Flap_Takeoff_Retract
Sequence2_Model=Right_Flap

[Flaps_Landing]
NumberOfSequencesToPlay=2
Sequence1=Left_Flap_Landing
Sequence1_Model=Left_Flap
Sequence2=Right_Flap_Landing
Sequence2_Model=Right_Flap

[Flaps_Landing_Retract]
NumberOfSequencesToPlay=2
Sequence1=Left_Flap_Landing_Retract
Sequence1_Model=Left_Flap
Sequence2=Right_Flap_Landing_Retract
Sequence2_Model=Right_Flap

[Gear_Extend]
NumberOfSequencesToPlay=26
Sequence1=Left_Gear_Door_1_Open
Sequence1_Model=Left_Gear_Door_1
Sequence2=Left_Gear_Door_L_1_Open
Sequence2_Model=Left_Gear_Door_L_1
Sequence3=Left_Gear_Door_R_1_Open
Sequence3_Model=Left_Gear_Door_R_1
Sequence4=Left_Gear_Door_L_2_Cycle
Sequence4_Model=Left_Gear_Door_L_2
Sequence5=Left_Gear_Door_R_2_Cycle
Sequence5_Model=Left_Gear_Door_R_2
Sequence6=Right_Gear_Door_1_Open
Sequence6_Model=Right_Gear_Door_1
Sequence7=Right_Gear_Door_L_1_Open
Sequence7_Model=Right_Gear_Door_L_1
Sequence8=Right_Gear_Door_R_1_Open
Sequence8_Model=Right_Gear_Door_R_1
Sequence9=Right_Gear_Door_L_2_Cycle
Sequence9_Model=Right_Gear_Door_L_2
Sequence10=Right_Gear_Door_R_2_Cycle
Sequence10_Model=Right_Gear_Door_R_2
Sequence11=Nose_Gear_Door_L_Open
Sequence11_Model=Nose_Gear_Door_L
Sequence12=Nose_Gear_Door_R_Open
Sequence12_Model=Nose_Gear_Door_R
Sequence13=Main_Gear_Extend
Sequence13_Model=Left_Gear
Sequence14=Main_Gear_Truck_Extend
Sequence14_Model=Left_Gear_Truck
Sequence15=Main_Gear_Piston_Extend
Sequence15_Model=Left_Gear_Piston
Sequence16=Main_Gear_Actuator_Extend
Sequence16_Model=Left_Gear_Actuator
Sequence17=Main_Gear_Arm_Extend
Sequence17_Model=Left_Gear_Arm
Sequence18=Main_Gear_Strut_Extend
Sequence18_Model=Left_Gear_Strut
Sequence19=Main_Gear_Extend
Sequence19_Model=Right_Gear
Sequence20=Main_Gear_Truck_Extend
Sequence20_Model=Right_Gear_Truck
Sequence21=Main_Gear_Piston_Extend
Sequence21_Model=Right_Gear_Piston
Sequence22=Main_Gear_Actuator_Extend
Sequence22_Model=Right_Gear_Actuator
Sequence23=Main_Gear_Arm_Extend
Sequence23_Model=Right_Gear_Arm
Sequence24=Main_Gear_Strut_Extend
Sequence24_Model=Right_Gear_Strut
Sequence25=Nose_Gear_Extend
Sequence25_Model=Nose_Gear
Sequence26=Nose_Gear_Strut_Extend
Sequence26_Model=Nose_Gear_Strut

[Gear_Retract]
NumberOfSequencesToPlay=26
Sequence1=Left_Gear_Door_1_Close
Sequence1_Model=Left_Gear_Door_1
Sequence2=Left_Gear_Door_L_1_Close
Sequence2_Model=Left_Gear_Door_L_1
Sequence3=Left_Gear_Door_R_1_Close
Sequence3_Model=Left_Gear_Door_R_1
Sequence4=Left_Gear_Door_L_2_Cycle
Sequence4_Model=Left_Gear_Door_L_2
Sequence5=Left_Gear_Door_R_2_Cycle
Sequence5_Model=Left_Gear_Door_R_2
Sequence6=Right_Gear_Door_1_Close
Sequence6_Model=Right_Gear_Door_1
Sequence7=Right_Gear_Door_L_1_Close
Sequence7_Model=Right_Gear_Door_L_1
Sequence8=Right_Gear_Door_R_1_Close
Sequence8_Model=Right_Gear_Door_R_1
Sequence9=Right_Gear_Door_L_2_Cycle
Sequence9_Model=Right_Gear_Door_L_2
Sequence10=Right_Gear_Door_R_2_Cycle
Sequence10_Model=Right_Gear_Door_R_2
Sequence11=Nose_Gear_Door_L_Close
Sequence11_Model=Nose_Gear_Door_L
Sequence12=Nose_Gear_Door_R_Close
Sequence12_Model=Nose_Gear_Door_R
Sequence13=Main_Gear_Retract
Sequence13_Model=Left_Gear
Sequence14=Main_Gear_Truck_Retract
Sequence14_Model=Left_Gear_Truck
Sequence15=Main_Gear_Piston_Retract
Sequence15_Model=Left_Gear_Piston
Sequence16=Main_Gear_Actuator_Retract
Sequence16_Model=Left_Gear_Actuator
Sequence17=Main_Gear_Arm_Retract
Sequence17_Model=Left_Gear_Arm
Sequence18=Main_Gear_Strut_Retract
Sequence18_Model=Left_Gear_Strut
Sequence19=Main_Gear_Retract
Sequence19_Model=Right_Gear
Sequence20=Main_Gear_Truck_Retract
Sequence20_Model=Right_Gear_Truck
Sequence21=Main_Gear_Piston_Retract
Sequence21_Model=Right_Gear_Piston
Sequence22=Main_Gear_Actuator_Retract
Sequence22_Model=Right_Gear_Actuator
Sequence23=Main_Gear_Arm_Retract
Sequence23_Model=Right_Gear_Arm
Sequence24=Main_Gear_Strut_Retract
Sequence24_Model=Right_Gear_Strut
Sequence25=Nose_Gear_Retract
Sequence25_Model=Nose_Gear
Sequence26=Nose_Gear_Strut_Retract
Sequence26_Model=Nose_Gear_Strut


[Left_Flap_Takeoff]
NumberOfSteps=2
Time1=0 
PositionY1=-0.0024
PositionZ1=-0.0255
RotationZ1=0
Smoothness1=EaseInOut
Time2=5 
PositionY2=0
PositionZ2=-0.035
RotationZ2=20
Smoothness2=EaseInOut

[Right_Flap_Takeoff]
NumberOfSteps=2
Time1=0 
PositionY1=-0.0024
PositionZ1=-0.0255
RotationZ1=0
Smoothness1=EaseInOut
Time2=5 
PositionY2=0
PositionZ2=-0.035
RotationZ2=20
Smoothness2=EaseInOut

[Left_Flap_Takeoff_Retract]
NumberOfSteps=2
Time1=0 
PositionY1=0
PositionZ1=-0.035
RotationZ1=20
Smoothness1=EaseInOut
Time2=5
PositionY2=-0.0024
PositionZ2=-0.0255
RotationZ2=0
Smoothness2=EaseInOut

[Right_Flap_Takeoff_Retract]
NumberOfSteps=2
Time1=0 
PositionY1=0
PositionZ1=-0.035
RotationZ1=20
Smoothness1=EaseInOut
Time2=5 
PositionY2=-0.0024
PositionZ2=-0.0255
RotationZ2=0
Smoothness2=EaseInOut

//-----------------------------------------

[Left_Flap_Landing]
NumberOfSteps=2
Time1=0 
PositionY1=-0.0024
PositionZ1=-0.0255
RotationZ1=0
Smoothness1=EaseInOut
Time2=5 
PositionY2=0
PositionZ2=-0.035
RotationZ2=30
Smoothness2=EaseInOut

[Right_Flap_Landing]
NumberOfSteps=2
Time1=0 
PositionY1=-0.0024
PositionZ1=-0.0255
RotationZ1=0
Smoothness1=EaseInOut
Time2=5 
PositionY2=0
PositionZ2=-0.035
RotationZ2=30
Smoothness2=EaseInOut

[Left_Flap_Landing_Retract]
NumberOfSteps=2
Time1=0 
PositionY1=0
PositionZ1=-0.035
RotationZ1=30
Smoothness1=EaseInOut
Time2=5
PositionY2=-0.0024
PositionZ2=-0.0255
RotationZ2=0
Smoothness2=EaseInOut

[Right_Flap_Landing_Retract]
NumberOfSteps=2
Time1=0 
PositionY1=0
PositionZ1=-0.035
RotationZ1=30
Smoothness1=EaseInOut
Time2=5 
PositionY2=-0.0024
PositionZ2=-0.0255
RotationZ2=0
Smoothness2=EaseInOut

### Gear Retraction -------------------------------------

[Left_Gear_Door_1_Open]
NumberOfSteps=4
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=2 
RotationX2=0
Smoothness2=EaseInOut
Time3=5 
RotationX3=-60
Smoothness3=EaseInOut
Time4=7 
RotationX3=-60
Smoothness3=EaseInOut

[Left_Gear_Door_1_Close]
NumberOfSteps=4
Time1=0 
RotationX1=-60
Smoothness1=EaseInOut
Time2=2 
RotationX2=-60
Smoothness2=EaseInOut
Time3=5 
RotationX3=0
Smoothness3=EaseInOut
Time4=7 
RotationX3=0
Smoothness3=EaseInOut

[Left_Gear_Door_L_1_Open]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-90
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-90
Smoothness3=EaseInOut
Time4=7 
RotationZ4=-90
Smoothness4=EaseInOut

[Left_Gear_Door_L_1_Close]
NumberOfSteps=4
Time1=0 
RotationZ1=-90
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-90
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-90
Smoothness3=EaseInOut
Time4=7 
RotationZ4=0
Smoothness4=EaseInOut

[Left_Gear_Door_R_1_Open]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=90
Smoothness2=EaseInOut
Time3=5 
RotationZ3=90
Smoothness3=EaseInOut
Time4=7 
RotationZ4=90
Smoothness4=EaseInOut

[Left_Gear_Door_R_1_Close]
NumberOfSteps=4
Time1=0 
RotationZ1=90
Smoothness1=EaseInOut
Time2=2 
RotationZ2=90
Smoothness2=EaseInOut
Time3=5 
RotationZ3=90
Smoothness3=EaseInOut
Time4=7 
RotationZ4=0
Smoothness4=EaseInOut

[Left_Gear_Door_L_2_Cycle]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-90
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-90
Smoothness3=EaseInOut
Time4=7 
RotationZ4=0
Smoothness4=EaseInOut

[Left_Gear_Door_R_2_Cycle]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=90
Smoothness2=EaseInOut
Time3=5 
RotationZ3=90
Smoothness3=EaseInOut
Time4=7 
RotationZ4=0
Smoothness4=EaseInOut

[Right_Gear_Door_1_Open]
NumberOfSteps=4
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=2 
RotationX2=0
Smoothness2=EaseInOut
Time3=5 
RotationX3=-60
Smoothness3=EaseInOut
Time4=7 
RotationX3=-60
Smoothness3=EaseInOut

[Right_Gear_Door_1_Close]
NumberOfSteps=4
Time1=0 
RotationX1=-60
Smoothness1=EaseInOut
Time2=2 
RotationX2=-60
Smoothness2=EaseInOut
Time3=5 
RotationX3=0
Smoothness3=EaseInOut
Time4=7 
RotationX3=0
Smoothness3=EaseInOut

[Right_Gear_Door_L_1_Open]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-90
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-90
Smoothness3=EaseInOut
Time4=7 
RotationZ4=-90
Smoothness4=EaseInOut

[Right_Gear_Door_L_1_Close]
NumberOfSteps=4
Time1=0 
RotationZ1=-90
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-90
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-90
Smoothness3=EaseInOut
Time4=7 
RotationZ4=0
Smoothness4=EaseInOut

[Right_Gear_Door_R_1_Open]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=90
Smoothness2=EaseInOut
Time3=5 
RotationZ3=90
Smoothness3=EaseInOut
Time4=7 
RotationZ4=90
Smoothness4=EaseInOut

[Right_Gear_Door_R_1_Close]
NumberOfSteps=4
Time1=0 
RotationZ1=90
Smoothness1=EaseInOut
Time2=2 
RotationZ2=90
Smoothness2=EaseInOut
Time3=5 
RotationZ3=90
Smoothness3=EaseInOut
Time4=7 
RotationZ4=0
Smoothness4=EaseInOut

[Right_Gear_Door_L_2_Cycle]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-90
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-90
Smoothness3=EaseInOut
Time4=7 
RotationZ4=0
Smoothness4=EaseInOut

[Right_Gear_Door_R_2_Cycle]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=90
Smoothness2=EaseInOut
Time3=5 
RotationZ3=90
Smoothness3=EaseInOut
Time4=7 
RotationZ4=0
Smoothness4=EaseInOut

[Nose_Gear_Door_L_Open]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-90
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-90
Smoothness3=EaseInOut
Time4=7 
RotationZ4=-90
Smoothness4=EaseInOut

[Nose_Gear_Door_R_Open]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=90
Smoothness2=EaseInOut
Time3=5 
RotationZ3=90
Smoothness3=EaseInOut
Time4=7 
RotationZ4=90
Smoothness4=EaseInOut

[Nose_Gear_Door_L_Close]
NumberOfSteps=4
Time1=0 
RotationZ1=-90
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-90
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-90
Smoothness3=EaseInOut
Time4=7 
RotationZ4=0
Smoothness4=EaseInOut

[Nose_Gear_Door_R_Close]
NumberOfSteps=4
Time1=0 
RotationZ1=90
Smoothness1=EaseInOut
Time2=2 
RotationZ2=90
Smoothness2=EaseInOut
Time3=5 
RotationZ3=90
Smoothness3=EaseInOut
Time4=7 
RotationZ4=0
Smoothness4=EaseInOut


### Gear Retraction -------------------------------------

[Main_Gear_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-100
Smoothness3=EaseInOut

[Main_Gear_Truck_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut
Time3=3 
RotationZ3=-75
Smoothness3=EaseInOut

[Main_Gear_Piston_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut
Time3=3 
RotationZ3=65
Smoothness3=EaseInOut

[Main_Gear_Actuator_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut
Time3=3 
RotationZ3=-108
Smoothness3=EaseInOut

[Main_Gear_Arm_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut
Time3=3 
RotationZ3=120
Smoothness3=EaseInOut

[Main_Gear_Strut_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut
Time3=4 
RotationZ3=-40
Smoothness3=EaseInOut

[Nose_Gear_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-112
Smoothness3=EaseInOut

[Nose_Gear_Strut_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2.5 
RotationZ2=0
Smoothness2=EaseInOut
Time3=5 
RotationZ3=150
Smoothness3=EaseInOut

### Gear Extension -------------------------------------

[Main_Gear_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=-100
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-100
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[Main_Gear_Truck_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=-75
Smoothness1=EaseInOut
Time2=4 
RotationZ2=-75
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[Main_Gear_Piston_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=65
Smoothness1=EaseInOut
Time2=4
RotationZ2=65
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[Main_Gear_Actuator_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=-108
Smoothness1=EaseInOut
Time2=4 
RotationZ2=-108
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[Main_Gear_Arm_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=120
Smoothness1=EaseInOut
Time2=4 
RotationZ2=120
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[Main_Gear_Strut_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=-40
Smoothness1=EaseInOut
Time2=3 
RotationZ2=-40
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[Nose_Gear_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=-112
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-112
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[Nose_Gear_Strut_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=150
Smoothness1=EaseInOut
Time2=2 
RotationZ2=150
Smoothness2=EaseInOut
Time3=4.5 
RotationZ3=0
Smoothness3=EaseInOut