[Animations]
NumberOfAnimations=12

Animation1=Wings_Extend
Animation2=Wings_Fold
Animation3=Gear_Extend
Animation4=Gear_Retract
Animation5=Nozzles_STOL
Animation6=Nozzles_STOL_Retract
Animation7=Nozzles_VTOL
Animation8=Nozzles_VTOL_Retract
Animation9=Bays_Open
Animation10=Bays_Close
Animation11=MAD_Extend
Animation12=MAD_Retract

[Canopy_Extend]
NumberOfSequencesToPlay=1
Sequence1=Canopy_Open
Sequence1_Model=Canopy

[Canopy_Retract]
NumberOfSequencesToPlay=1
Sequence1=Canopy_Close
Sequence1_Model=Canopy

[Wings_Fold]
NumberOfSequencesToPlay=2
Sequence1=Left_Wing_Fold
Sequence1_Model=Left_Wing
Sequence2=Right_Wing_Fold
Sequence2_Model=Right_Wing

[Wings_Extend]
NumberOfSequencesToPlay=2
Sequence1=Left_Wing_Spread
Sequence1_Model=Left_Wing
Sequence2=Right_Wing_Spread
Sequence2_Model=Right_Wing

[Flaps_Takeoff]
NumberOfSequencesToPlay=2
Sequence1=Flap_Takeoff
Sequence1_Model=Left_Flap
Sequence2=Flap_Takeoff
Sequence2_Model=Right_Flap

[Flaps_Takeoff_Retract]
NumberOfSequencesToPlay=2
Sequence1=Flap_Takeoff_Retract
Sequence1_Model=Left_Flap
Sequence2=Flap_Takeoff_Retract
Sequence2_Model=Right_Flap

[Flaps_Landing]
NumberOfSequencesToPlay=2
Sequence1=Flap_Landing
Sequence1_Model=Left_Flap
Sequence2=Flap_Landing
Sequence2_Model=Right_Flap

[Flaps_Landing_Retract]
NumberOfSequencesToPlay=2
Sequence1=Flap_Landing_Retract
Sequence1_Model=Left_Flap
Sequence2=Flap_Landing_Retract
Sequence2_Model=Right_Flap

[Gear_Extend]
NumberOfSequencesToPlay=14
Sequence1=Left_Gear_Door_1a_Open
Sequence1_Model=Left_Gear_Door_1a
Sequence2=Left_Gear_Door_1b_Open
Sequence2_Model=Left_Gear_Door_1b
Sequence3=Left_Gear_Door_2a_Cycle
Sequence3_Model=Left_Gear_Door_2a
Sequence4=Left_Gear_Door_2b_Cycle
Sequence4_Model=Left_Gear_Door_2b
Sequence5=Left_Gear_Extend
Sequence5_Model=Left_Gear
Sequence6=Right_Gear_Door_1a_Open
Sequence6_Model=Right_Gear_Door_1a
Sequence7=Right_Gear_Door_1b_Open
Sequence7_Model=Right_Gear_Door_1b
Sequence8=Right_Gear_Door_2a_Cycle
Sequence8_Model=Right_Gear_Door_2a
Sequence9=Right_Gear_Door_2b_Cycle
Sequence9_Model=Right_Gear_Door_2b
Sequence10=Right_Gear_Extend
Sequence10_Model=Right_Gear
Sequence11=TailWheel_Door_1_Open
Sequence11_Model=TailWheel_Door_1
Sequence12=TailWheel_Door_2l_Cycle
Sequence12_Model=TailWheel_Door_2l
Sequence13=TailWheel_Door_2r_Cycle
Sequence13_Model=TailWheel_Door_2r
Sequence14=TailWheel_Extend
Sequence14_Model=TailWheel

[Gear_Retract]
NumberOfSequencesToPlay=14
Sequence1=Left_Gear_Door_1a_Close
Sequence1_Model=Left_Gear_Door_1a
Sequence2=Left_Gear_Door_1b_Close
Sequence2_Model=Left_Gear_Door_1b
Sequence3=Left_Gear_Door_2a_Cycle
Sequence3_Model=Left_Gear_Door_2a
Sequence4=Left_Gear_Door_2b_Cycle
Sequence4_Model=Left_Gear_Door_2b
Sequence5=Left_Gear_Retract
Sequence5_Model=Left_Gear
Sequence6=Right_Gear_Door_1a_Close
Sequence6_Model=Right_Gear_Door_1a
Sequence7=Right_Gear_Door_1b_Close
Sequence7_Model=Right_Gear_Door_1b
Sequence8=Right_Gear_Door_2a_Cycle
Sequence8_Model=Right_Gear_Door_2a
Sequence9=Right_Gear_Door_2b_Cycle
Sequence9_Model=Right_Gear_Door_2b
Sequence10=Right_Gear_Retract
Sequence10_Model=Right_Gear
Sequence11=TailWheel_Door_1_Close
Sequence11_Model=TailWheel_Door_1
Sequence12=TailWheel_Door_2l_Cycle
Sequence12_Model=TailWheel_Door_2l
Sequence13=TailWheel_Door_2r_Cycle
Sequence13_Model=TailWheel_Door_2r
Sequence14=TailWheel_Retract
Sequence14_Model=TailWheel

[Nozzles_STOL]
NumberOfSequencesToPlay=1
Sequence1=Nozzle_STOL
Sequence1_Model=Nacelles

[Nozzles_STOL_Retract]
NumberOfSequencesToPlay=1
Sequence1=Nozzle_STOL_Retract
Sequence1_Model=Nacelles

[Nozzles_VTOL]
NumberOfSequencesToPlay=1
Sequence1=Nozzle_VTOL
Sequence1_Model=Nacelles

[Nozzles_VTOL_Retract]
NumberOfSequencesToPlay=1
Sequence1=Nozzle_VTOL_Retract
Sequence1_Model=Nacelles

[Bays_Open]
NumberOfSequencesToPlay=4
Sequence1=Bay_Door_Left_1_Open
Sequence1_Model=Bay_Door_1l
Sequence2=Bay_Door_Left_2_Open
Sequence2_Model=Bay_Door_2l
Sequence3=Bay_Door_Right_1_Open
Sequence3_Model=Bay_Door_1r
Sequence4=Bay_Door_Right_2_Open
Sequence4_Model=Bay_Door_2r

[Bays_Close]
NumberOfSequencesToPlay=4
Sequence1=Bay_Door_Left_1_Close
Sequence1_Model=Bay_Door_1l
Sequence2=Bay_Door_Left_2_Close
Sequence2_Model=Bay_Door_2l
Sequence3=Bay_Door_Right_1_Close
Sequence3_Model=Bay_Door_1r
Sequence4=Bay_Door_Right_2_Close
Sequence4_Model=Bay_Door_2r

[MAD_Extend]
NumberOfSequencesToPlay=1
Sequence1=Extend_Boom
Sequence1_Model=MAD

[MAD_Retract]
NumberOfSequencesToPlay=1
Sequence1=Retract_Boom
Sequence1_Model=MAD


[------------------------------ Sequences ------------------------------]
[Canopy_Open]
NumberOfSteps=2
Time1=0 
PositionY1=0
PositionZ1=0
Smoothness1=EaseInOut
Time2=5 
PositionY2=0.0031
PositionZ2=-0.0054
Smoothness2=EaseInOut

[Canopy_Close]
NumberOfSteps=2
Time1=0 
PositionY1=0.0031
PositionZ1=-0.0054
Smoothness1=EaseInOut
Time2=5 
PositionY2=0
PositionZ2=0
Smoothness2=EaseInOut

[Left_Wing_Fold]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=10 
RotationZ2=-170
Smoothness2=EaseInOut

[Left_Wing_Spread]
NumberOfSteps=2
Time1=0 
RotationZ1=-170
Smoothness1=EaseInOut
Time2=10 
RotationZ2=0
Smoothness2=EaseInOut

[Right_Wing_Fold]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=10 
RotationZ2=170
Smoothness2=EaseInOut

[Right_Wing_Spread]
NumberOfSteps=2
Time1=0 
RotationZ1=170
Smoothness1=EaseInOut
Time2=10 
RotationZ2=0
Smoothness2=EaseInOut

[Flap_Takeoff]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=5 
RotationZ2=20
Smoothness2=EaseInOut

[Flap_Takeoff_Retract]
NumberOfSteps=2
Time1=0 
RotationZ1=20
Smoothness1=EaseInOut
Time2=5 
RotationZ2=0
Smoothness2=EaseInOut

[Flap_Landing]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=10 
RotationZ2=35
Smoothness2=EaseInOut

[Flap_Landing_Retract]
NumberOfSteps=2
Time1=0 
RotationZ1=35
Smoothness1=EaseInOut
Time2=10 
RotationZ2=0
Smoothness2=EaseInOut

###Gear Struts Retraction



###Extend Gear

[Left_Gear_Door_1a_Open]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-60
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-60
Smoothness3=EaseInOut

[Left_Gear_Door_1a_Close]
NumberOfSteps=3
Time1=0 
RotationZ1=-60
Smoothness1=EaseInOut
Time2=5 
RotationZ2=-60
Smoothness2=EaseInOut
Time3=7 
RotationZ3=0
Smoothness3=EaseInOut

[Left_Gear_Door_1b_Open]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=60
Smoothness2=EaseInOut
Time3=5 
RotationZ3=60
Smoothness3=EaseInOut

[Left_Gear_Door_1b_Close]
NumberOfSteps=3
Time1=0 
RotationZ1=60
Smoothness1=EaseInOut
Time2=5 
RotationZ2=60
Smoothness2=EaseInOut
Time3=7 
RotationZ3=0
Smoothness3=EaseInOut

[Left_Gear_Door_2a_Cycle]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-90
Smoothness2=EaseInOut
Time3=4 
RotationZ3=-90
Smoothness3=EaseInOut
Time4=6
RotationZ4=0
Smoothness4=EaseInOut

[Left_Gear_Door_2b_Cycle]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=45
Smoothness2=EaseInOut
Time3=4
RotationZ3=45
Smoothness3=EaseInOut
Time4=6
RotationZ4=0
Smoothness4=EaseInOut

###-----------------------------------------

[Right_Gear_Door_1a_Open]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=60
Smoothness2=EaseInOut
Time3=5 
RotationZ3=60
Smoothness3=EaseInOut

[Right_Gear_Door_1a_Close]
NumberOfSteps=3
Time1=0 
RotationZ1=60
Smoothness1=EaseInOut
Time2=5 
RotationZ2=60
Smoothness2=EaseInOut
Time3=7 
RotationZ3=0
Smoothness3=EaseInOut

[Right_Gear_Door_1b_Open]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-60
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-60
Smoothness3=EaseInOut

[Right_Gear_Door_1b_Close]
NumberOfSteps=3
Time1=0 
RotationZ1=-60
Smoothness1=EaseInOut
Time2=5 
RotationZ2=-60
Smoothness2=EaseInOut
Time3=7 
RotationZ3=0
Smoothness3=EaseInOut

[Right_Gear_Door_2a_Cycle]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=90
Smoothness2=EaseInOut
Time3=4 
RotationZ3=90
Smoothness3=EaseInOut
Time4=6 
RotationZ4=0
Smoothness4=EaseInOut

[Right_Gear_Door_2b_Cycle]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-45
Smoothness2=EaseInOut
Time3=4 
RotationZ3=-45
Smoothness3=EaseInOut
Time4=6 
RotationZ4=0
Smoothness4=EaseInOut

###-----------------------------------------

[TailWheel_Door_1_Open]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut
Time3=5 
RotationZ3=120
Smoothness3=EaseInOut

[TailWheel_Door_1_Close]
NumberOfSteps=3
Time1=0 
RotationZ1=120
Smoothness1=EaseInOut
Time2=2 
RotationZ2=120
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[TailWheel_Door_2l_Cycle]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-90
Smoothness2=EaseInOut
Time3=4 
RotationZ3=-90
Smoothness3=EaseInOut
Time4=6 
RotationZ4=0
Smoothness4=EaseInOut

[TailWheel_Door_2r_Cycle]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=90
Smoothness2=EaseInOut
Time3=4 
RotationZ3=90
Smoothness3=EaseInOut
Time4=6 
RotationZ4=0
Smoothness4=EaseInOut

###Left Gear

[Left_Gear_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=100
Smoothness1=EaseInOut
Time2=2 
RotationZ2=100
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[Left_Gear_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut
Time3=5 
RotationZ3=100
Smoothness3=EaseInOut

[Right_Gear_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=-100
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-100
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[Right_Gear_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-100
Smoothness3=EaseInOut

[TailWheel_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=-100
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-100
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[TailWheel_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-100
Smoothness3=EaseInOut

[Nose_Gear_Wheel_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=-30
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-30
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[Nose_Gear_Wheel_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-30
Smoothness3=EaseInOut

//----------------------------

[Nozzle_STOL]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=45
Smoothness2=EaseInOut

[Nozzle_STOL_Retract]
NumberOfSteps=2
Time1=0 
RotationZ1=45
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut

[Nozzle_VTOL]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=4 
RotationZ2=90
Smoothness2=EaseInOut

[Nozzle_VTOL_Retract]
NumberOfSteps=2
Time1=0 
RotationZ1=90
Smoothness1=EaseInOut
Time2=4 
RotationZ2=0
Smoothness2=EaseInOut

//----------------------------

[Bay_Door_Left_1_Open]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=1
RotationZ2=-90
Smoothness2=EaseInOut

[Bay_Door_Left_1_Close]
NumberOfSteps=3
Time1=0 
RotationZ1=-90
Smoothness1=EaseInOut
Time2=1
RotationZ2=0
Smoothness2=EaseInOut

[Bay_Door_Left_2_Open]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=1
RotationZ2=170
Smoothness2=EaseInOut

[Bay_Door_Left_2_Close]
NumberOfSteps=3
Time1=0 
RotationZ1=170
Smoothness1=EaseInOut
Time2=1
RotationZ2=0
Smoothness2=EaseInOut

//-----------------------

[Bay_Door_Right_1_Open]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=1
RotationZ2=90
Smoothness2=EaseInOut

[Bay_Door_Right_1_Close]
NumberOfSteps=3
Time1=0 
RotationZ1=90
Smoothness1=EaseInOut
Time2=1
RotationZ2=0
Smoothness2=EaseInOut

[Bay_Door_Right_2_Open]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=1
RotationZ2=-170
Smoothness2=EaseInOut

[Bay_Door_Right_2_Close]
NumberOfSteps=3
Time1=0 
RotationZ1=-170
Smoothness1=EaseInOut
Time2=1
RotationZ2=0
Smoothness2=EaseInOut

##MAD Animation

[Extend_Boom]
NumberOfSteps=3
Time1=0 
PositionZ1=0.049
Smoothness1=EaseInOut
Time2=5
PositionZ2=0
Smoothness2=EaseInOut

[Retract_Boom]
NumberOfSteps=3
Time1=0 
PositionZ1=0
Smoothness1=EaseInOut
Time2=5
PositionZ2=0.049
Smoothness2=EaseInOut