[Animations]
NumberOfAnimations=10
Animation1=Flaps_Takeoff
Animation2=Flaps_Takeoff_Retract
Animation3=Flaps_Landing
Animation4=Flaps_Landing_Retract
Animation5=Gear_Extend
Animation6=Gear_Retract
Animation7=WeaponsBay1_OpenAnim
Animation8=WeaponsBay1_CloseAnim
Animation9=WeaponsBay2_OpenAnim
Animation10=WeaponsBay2_CloseAnim

[Flaps_Takeoff]
NumberOfSequencesToPlay=2
Sequence1=Flap_Takeoff
Sequence1_Model=Left_Flap
Sequence2=Flap_Takeoff
Sequence2_Model=Right_Flap

[Flaps_Takeoff_Retract]
NumberOfSequencesToPlay=2
Sequence1=Flap_Takeoff_Retract
Sequence1_Model=Left_Flap
Sequence2=Flap_Takeoff_Retract
Sequence2_Model=Right_Flap

[Flaps_Landing]
NumberOfSequencesToPlay=2
Sequence1=Flap_Landing
Sequence1_Model=Left_Flap
Sequence2=Flap_Landing
Sequence2_Model=Right_Flap

[Flaps_Landing_Retract]
NumberOfSequencesToPlay=2
Sequence1=Flap_Landing_Retract
Sequence1_Model=Left_Flap
Sequence2=Flap_Landing_Retract
Sequence2_Model=Right_Flap

[Gear_Extend]
NumberOfSequencesToPlay=21
Sequence1=Left_Gear_Door_L_1_Open
Sequence1_Model=Left_Gear_Door_L_1
Sequence2=Left_Gear_Door_R_1_Open
Sequence2_Model=Left_Gear_Door_R_1
Sequence3=Left_Gear_Door_L_2_Cycle
Sequence3_Model=Left_Gear_Door_L_2
Sequence4=Left_Gear_Door_R_2_Cycle
Sequence4_Model=Left_Gear_Door_R_2
Sequence5=Right_Gear_Door_L_1_Open
Sequence5_Model=Right_Gear_Door_L_1
Sequence6=Right_Gear_Door_R_1_Open
Sequence6_Model=Right_Gear_Door_R_1
Sequence7=Right_Gear_Door_L_2_Cycle
Sequence7_Model=Right_Gear_Door_L_2
Sequence8=Right_Gear_Door_R_2_Cycle
Sequence8_Model=Right_Gear_Door_R_2
Sequence9=Nose_Gear_Door_1_Open
Sequence9_Model=Nose_Gear_Door_1
Sequence10=Nose_Gear_Door_L_1_Open
Sequence10_Model=Nose_Gear_Door_L_1
Sequence11=Nose_Gear_Door_L_2_Cycle
Sequence11_Model=Nose_Gear_Door_L_2
Sequence12=Nose_Gear_Door_R_1_Open
Sequence12_Model=Nose_Gear_Door_R_1
Sequence13=Nose_Gear_Door_R_2_Cycle
Sequence13_Model=Nose_Gear_Door_R_2
Sequence14=Main_Gear_Extend
Sequence14_Model=Left_Gear
Sequence15=Main_Gear_Boogie_Extend
Sequence15_Model=Left_Gear_Boogie
Sequence16=Main_Gear_Strut_Extend
Sequence16_Model=Left_Gear_Strut
Sequence17=Main_Gear_Extend
Sequence17_Model=Right_Gear
Sequence18=Main_Gear_Boogie_Extend
Sequence18_Model=Right_Gear_Boogie
Sequence19=Main_Gear_Strut_Extend
Sequence19_Model=Right_Gear_Strut
Sequence20=Nose_Gear_Extend
Sequence20_Model=Nose_Gear
Sequence21=Nose_Gear_Strut_Extend
Sequence21_Model=Nose_Gear_Strut

[Gear_Retract]
NumberOfSequencesToPlay=21
Sequence1=Left_Gear_Door_L_1_Close
Sequence1_Model=Left_Gear_Door_L_1
Sequence2=Left_Gear_Door_R_1_Close
Sequence2_Model=Left_Gear_Door_R_1
Sequence3=Left_Gear_Door_L_2_Cycle
Sequence3_Model=Left_Gear_Door_L_2
Sequence4=Left_Gear_Door_R_2_Cycle
Sequence4_Model=Left_Gear_Door_R_2
Sequence5=Right_Gear_Door_L_1_Close
Sequence5_Model=Right_Gear_Door_L_1
Sequence6=Right_Gear_Door_R_1_Close
Sequence6_Model=Right_Gear_Door_R_1
Sequence7=Right_Gear_Door_L_2_Cycle
Sequence7_Model=Right_Gear_Door_L_2
Sequence8=Right_Gear_Door_R_2_Cycle
Sequence8_Model=Right_Gear_Door_R_2
Sequence9=Nose_Gear_Door_1_Close
Sequence9_Model=Nose_Gear_Door_1
Sequence10=Nose_Gear_Door_L_1_Close
Sequence10_Model=Nose_Gear_Door_L_1
Sequence11=Nose_Gear_Door_L_2_Cycle
Sequence11_Model=Nose_Gear_Door_L_2
Sequence12=Nose_Gear_Door_R_1_Close
Sequence12_Model=Nose_Gear_Door_R_1
Sequence13=Nose_Gear_Door_R_2_Cycle
Sequence13_Model=Nose_Gear_Door_R_2
Sequence14=Main_Gear_Retract
Sequence14_Model=Left_Gear
Sequence15=Main_Gear_Boogie_Retract
Sequence15_Model=Left_Gear_Boogie
Sequence16=Main_Gear_Strut_Retract
Sequence16_Model=Left_Gear_Strut
Sequence17=Main_Gear_Retract
Sequence17_Model=Right_Gear
Sequence18=Main_Gear_Boogie_Retract
Sequence18_Model=Right_Gear_Boogie
Sequence19=Main_Gear_Strut_Retract
Sequence19_Model=Right_Gear_Strut
Sequence20=Nose_Gear_Retract
Sequence20_Model=Nose_Gear
Sequence21=Nose_Gear_Strut_Retract
Sequence21_Model=Nose_Gear_Strut

[WeaponsBay1_OpenAnim]
NumberOfSequencesToPlay=2
Sequence1=BayOpenDoorLAnimSequence
Sequence1_Model=Bay_Door_L_1
Sequence2=BayOpenDoorRAnimSequence
Sequence2_Model=Bay_Door_R_1

[WeaponsBay1_CloseAnim]
NumberOfSequencesToPlay=2
Sequence1=BayCloseDoorLAnimSequence
Sequence1_Model=Bay_Door_L_1
Sequence2=BayCloseDoorRAnimSequence
Sequence2_Model=Bay_Door_R_1

[WeaponsBay2_OpenAnim]
NumberOfSequencesToPlay=2
Sequence1=BayOpenDoorLAnimSequence
Sequence1_Model=Bay_Door_L_2
Sequence2=BayOpenDoorRAnimSequence
Sequence2_Model=Bay_Door_R_2

[WeaponsBay2_CloseAnim]
NumberOfSequencesToPlay=2
Sequence1=BayCloseDoorLAnimSequence
Sequence1_Model=Bay_Door_L_2
Sequence2=BayCloseDoorRAnimSequence
Sequence2_Model=Bay_Door_R_2

#-------------------------------------------------- Flaps  Takeoff --------------------------------------------------

[Flap_Takeoff]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=5 
RotationZ2=20
Smoothness2=EaseInOut

[Flap_Takeoff_Retract]
NumberOfSteps=2
Time1=0 
RotationZ1=20
Smoothness1=EaseInOut
Time2=5 
RotationZ2=0
Smoothness2=EaseInOut

#-------------------------------------------------- Flaps  Landing --------------------------------------------------

[Flap_Landing]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=5 
RotationZ2=30
Smoothness2=EaseInOut

[Flap_Landing_Retract]
NumberOfSteps=2
Time1=0 
RotationZ1=30
Smoothness1=EaseInOut
Time2=5 
RotationZ2=0
Smoothness2=EaseInOut

#-------------------------------------------------- Gear Extend --------------------------------------------------

[Left_Gear_Door_L_1_Open]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-75
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-75
Smoothness3=EaseInOut
Time4=7 
RotationZ4=-75
Smoothness4=EaseInOut

[Left_Gear_Door_L_1_Close]
NumberOfSteps=4
Time1=0 
RotationZ1=-75
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-75
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-75
Smoothness3=EaseInOut
Time4=7 
RotationZ4=0
Smoothness4=EaseInOut

[Left_Gear_Door_R_1_Open]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=75
Smoothness2=EaseInOut
Time3=5 
RotationZ3=75
Smoothness3=EaseInOut
Time4=7 
RotationZ4=75
Smoothness4=EaseInOut

[Left_Gear_Door_R_1_Close]
NumberOfSteps=4
Time1=0 
RotationZ1=75
Smoothness1=EaseInOut
Time2=2 
RotationZ2=75
Smoothness2=EaseInOut
Time3=5 
RotationZ3=75
Smoothness3=EaseInOut
Time4=7 
RotationZ4=0
Smoothness4=EaseInOut

[Left_Gear_Door_L_2_Cycle]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-75
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-75
Smoothness3=EaseInOut
Time4=7 
RotationZ4=0
Smoothness4=EaseInOut

[Left_Gear_Door_R_2_Cycle]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=75
Smoothness2=EaseInOut
Time3=5 
RotationZ3=75
Smoothness3=EaseInOut
Time4=7 
RotationZ4=0
Smoothness4=EaseInOut

[Right_Gear_Door_L_1_Open]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-75
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-75
Smoothness3=EaseInOut
Time4=7 
RotationZ4=-75
Smoothness4=EaseInOut

[Right_Gear_Door_L_1_Close]
NumberOfSteps=4
Time1=0 
RotationZ1=-75
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-75
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-75
Smoothness3=EaseInOut
Time4=7 
RotationZ4=0
Smoothness4=EaseInOut

[Right_Gear_Door_R_1_Open]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=75
Smoothness2=EaseInOut
Time3=5 
RotationZ3=75
Smoothness3=EaseInOut
Time4=7 
RotationZ4=75
Smoothness4=EaseInOut

[Right_Gear_Door_R_1_Close]
NumberOfSteps=4
Time1=0 
RotationZ1=75
Smoothness1=EaseInOut
Time2=2 
RotationZ2=75
Smoothness2=EaseInOut
Time3=5 
RotationZ3=75
Smoothness3=EaseInOut
Time4=7 
RotationZ4=0
Smoothness4=EaseInOut

[Right_Gear_Door_L_2_Cycle]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-75
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-75
Smoothness3=EaseInOut
Time4=7 
RotationZ4=0
Smoothness4=EaseInOut

[Right_Gear_Door_R_2_Cycle]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=75
Smoothness2=EaseInOut
Time3=5 
RotationZ3=75
Smoothness3=EaseInOut
Time4=7 
RotationZ4=0
Smoothness4=EaseInOut

[Nose_Gear_Door_1_Open]
NumberOfSteps=4
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=2 
RotationX2=0
Smoothness2=EaseInOut
Time3=5 
RotationX3=55
Smoothness3=EaseInOut
Time4=7 
RotationX4=55
Smoothness4=EaseInOut

[Nose_Gear_Door_L_1_Open]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-90
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-90
Smoothness3=EaseInOut
Time4=7 
RotationZ4=-90
Smoothness4=EaseInOut

[Nose_Gear_Door_R_1_Open]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=90
Smoothness2=EaseInOut
Time3=5 
RotationZ3=90
Smoothness3=EaseInOut
Time4=7 
RotationZ4=90
Smoothness4=EaseInOut

[Nose_Gear_Door_L_2_Cycle]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-75
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-75
Smoothness3=EaseInOut
Time4=7 
RotationZ4=0
Smoothness4=EaseInOut

[Nose_Gear_Door_R_2_Cycle]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=75
Smoothness2=EaseInOut
Time3=5 
RotationZ3=75
Smoothness3=EaseInOut
Time4=7 
RotationZ4=0
Smoothness4=EaseInOut

[Nose_Gear_Door_1_Close]
NumberOfSteps=4
Time1=0 
RotationX1=55
Smoothness1=EaseInOut
Time2=2 
RotationX2=55
Smoothness2=EaseInOut
Time3=5 
RotationX3=0
Smoothness3=EaseInOut
Time4=7 
RotationX4=0
Smoothness4=EaseInOut

[Nose_Gear_Door_L_1_Close]
NumberOfSteps=4
Time1=0 
RotationZ1=-90
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-90
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-90
Smoothness3=EaseInOut
Time4=7 
RotationZ4=0
Smoothness4=EaseInOut

[Nose_Gear_Door_R_1_Close]
NumberOfSteps=4
Time1=0 
RotationZ1=90
Smoothness1=EaseInOut
Time2=2 
RotationZ2=90
Smoothness2=EaseInOut
Time3=5 
RotationZ3=90
Smoothness3=EaseInOut
Time4=7 
RotationZ4=0
Smoothness4=EaseInOut

### Gear Retraction -------------------------------------

[Main_Gear_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut
Time3=5 
RotationZ3=115
Smoothness3=EaseInOut

[Main_Gear_Boogie_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut
Time3=3 
RotationZ3=75
Smoothness3=EaseInOut

[Main_Gear_Strut_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut
Time3=4 
RotationZ3=-35
Smoothness3=EaseInOut

[Nose_Gear_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut
Time3=5 
RotationZ3=105
Smoothness3=EaseInOut

[Nose_Gear_Strut_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2.5 
RotationZ2=0
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-35
Smoothness3=EaseInOut

### Gear Extension -------------------------------------

[Main_Gear_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=115
Smoothness1=EaseInOut
Time2=2 
RotationZ2=115
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[Main_Gear_Boogie_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=75
Smoothness1=EaseInOut
Time2=4 
RotationZ2=75
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[Main_Gear_Strut_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=-35
Smoothness1=EaseInOut
Time2=3 
RotationZ2=-35
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[Nose_Gear_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=105
Smoothness1=EaseInOut
Time2=2 
RotationZ2=105
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[Nose_Gear_Strut_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=-35
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-35
Smoothness2=EaseInOut
Time3=4.5 
RotationZ3=0
Smoothness3=EaseInOut





#-------------------------------------------------- Open Bay Doors --------------------------------------------------
[BayOpenDoorLAnimSequence]
NumberOfSteps=2
Time1=0                // time in seconds for the start
RotationZ1=0
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time2=3            // time in seconds - here for the end
RotationZ2=-90
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry

[BayOpenDoorRAnimSequence]
NumberOfSteps=2
Time1=0                // time in seconds for the start
RotationZ1=0
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time2=3            // time in seconds - here for the end
RotationZ2=90
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry

#-------------------------------------------------- Close Bay Doors --------------------------------------------------
[BayCloseDoorLAnimSequence]
NumberOfSteps=2
Time1=0                // time in seconds for the start
RotationZ1=-90
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time2=3            // time in seconds - here for the end
RotationZ2=0
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry

[BayCloseDoorRAnimSequence]
NumberOfSteps=2
Time1=0                // time in seconds for the start
RotationZ1=90
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time2=3            // time in seconds - here for the end
RotationZ2=0
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry