[Animations]
Animation1=Canopy_Extend
Animation2=Canopy_Retract
Animation7=Gear_Extend
Animation8=Gear_Retract


[Canopy_Extend]
NumberOfSequencesToPlay=1
Sequence1=Canopy_Open
Sequence1_Model=Canopyframe

[Canopy_Retract]
NumberOfSequencesToPlay=1
Sequence1=Canopy_Close
Sequence1_Model=Canopyframe

[Gear_Extend]
NumberOfSequencesToPlay=13
Sequence1=Left_gear_door_1_cycle
Sequence1_Model=Left_Gear_Door_1
Sequence2=Right_gear_door_1_cycle
Sequence2_Model=Right_Gear_Door_1
Sequence3=Left_gear_door_2_open
Sequence3_Model=Left_Gear_Door_2
Sequence4=Right_gear_door_2_open
Sequence4_Model=Right_Gear_Door_2
Sequence5=Left_gear_open
Sequence5_Model=Left_Gear
Sequence6=Right_gear_open
Sequence6_Model=Right_Gear
Sequence7=Nose_gear_door_1_open
Sequence7_Model=Nose_Gear_Door_1
Sequence8=Nose_gear_door_3_cycle
Sequence8_Model=Nose_Gear_Door_3
Sequence9=Nose_gear_open
Sequence9_Model=Nose_Gear
Sequence10=Airbreak_Top_1_cycle
Sequence10_Model=Airbreak_1
Sequence11=Airbreak_Top_2_cycle
Sequence11_Model=Airbreak_2
Sequence12=Airbreak_Bottom_3_cycle
Sequence12_Model=Airbreak_3
Sequence13=Airbreak_Bottom_4_cycle
Sequence13_Model=Airbreak_4

[Gear_Retract]
NumberOfSequencesToPlay=9
Sequence1=Left_gear_door_1_cycle
Sequence1_Model=Left_Gear_Door_1
Sequence2=Right_gear_door_1_cycle
Sequence2_Model=Right_Gear_Door_1
Sequence3=Left_gear_door_2_close
Sequence3_Model=Left_Gear_Door_2
Sequence4=Right_gear_door_2_close
Sequence4_Model=Right_Gear_Door_2
Sequence5=Left_gear_close
Sequence5_Model=Left_Gear
Sequence6=Right_gear_close
Sequence6_Model=Right_Gear
Sequence7=Nose_gear_door_1_close
Sequence7_Model=Nose_Gear_Door_1
Sequence8=Nose_gear_door_3_cycle
Sequence8_Model=Nose_Gear_Door_3
Sequence9=Nose_gear_close
Sequence9_Model=Nose_Gear

####################################################

[Canopy_Open]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=5 
RotationX2=-45
Smoothness2=EaseInOut

[Canopy_Close]
NumberOfSteps=2
Time1=0 
RotationX1=-45
Smoothness1=EaseInOut
Time2=5 
RotationX2=0
Smoothness2=EaseInOut

[Left_gear_door_1_cycle]
NumberOfSteps=4
Step1=0|x,y,z|0,0,0|EaseInOut
Step2=2|x,y,z|0,0,90|EaseInOut
Step3=5|x,y,z|0,0,90|EaseInOut
Step4=8|x,y,z|0,0,0|EaseInOut

[Right_gear_door_1_cycle]
NumberOfSteps=4
Step1=0|x,y,z|0,0,0|EaseInOut
Step2=2|x,y,z|0,0,-90|EaseInOut
Step3=5|x,y,z|0,0,-90|EaseInOut
Step4=8|x,y,z|0,0,0|EaseInOut

[Left_gear_door_2_open]
NumberOfSteps=2
Step1=2|x,y,z|0,0,0|EaseInOut
Step2=5|x,y,z|0,0,-90|EaseInOut

[Right_gear_door_2_open]
NumberOfSteps=2
Step1=2|x,y,z|0,0,0|EaseInOut
Step2=5|x,y,z|0,0,90|EaseInOut

[Left_gear_door_2_close]
NumberOfSteps=2
Step1=2|x,y,z|0,0,-90|EaseInOut
Step2=5|x,y,z|0,0,0|EaseInOut

[Right_gear_door_2_close]
NumberOfSteps=2
Step1=2|x,y,z|0,0,90|EaseInOut
Step2=5|x,y,z|0,0,0|EaseInOut

[Left_gear_open]
NumberOfSteps=2
Step1=2|x,y,z|0,0,0|EaseInOut
Step2=5|x,y,z|40,0,-90|EaseInOut

[Right_gear_open]
NumberOfSteps=2
Step1=2|x,y,z|0,0,0|EaseInOut
Step2=5|x,y,z|40,0,90|EaseInOut

[Left_gear_close]
NumberOfSteps=2
Step1=2|x,y,z|40,0,-90|EaseInOut
Step2=5|x,y,z|0,0,0|EaseInOut

[Right_gear_close]
NumberOfSteps=2
Step1=2|x,y,z|40,0,90|EaseInOut
Step2=5|x,y,z|0,0,0|EaseInOut

[Nose_gear_door_3_cycle]
NumberOfSteps=4
Step1=0|x,y,z|0,0,0|EaseInOut
Step2=2|x,y,z|0,0,90|EaseInOut
Step3=5|x,y,z|0,0,90|EaseInOut
Step4=8|x,y,z|0,0,0|EaseInOut

[Nose_gear_door_1_open]
NumberOfSteps=2
Step1=2|x,y,z|0,0,0|EaseInOut
Step2=5|x,y,z|-90,0,0|EaseInOut

[Nose_gear_open]
NumberOfSteps=2
Step1=2|x,y,z|0,0,0|EaseInOut
Step2=5|x,y,z|-90,0,0|EaseInOut

[Nose_gear_door_1_close]
NumberOfSteps=2
Step1=2|x,y,z|-90,0,0|EaseInOut
Step2=5|x,y,z|0,0,0|EaseInOut

[Nose_gear_close]
NumberOfSteps=2
Step1=2|x,y,z|-90,0,0|EaseInOut
Step2=5|x,y,z|0,0,0|EaseInOut

[Airbreak_Top_1_cycle]
NumberOfSteps=4
Step1=5|x,y,z|0,0,6|EaseInOut
Step2=7|x,y,z|35,0,6|EaseInOut
Step3=30|x,y,z|35,0,6|EaseInOut
Step4=32|x,y,z|0,0,6|EaseInOut

[Airbreak_Top_2_cycle]
NumberOfSteps=4
Step1=5|x,y,z|0,0,-6|EaseInOut
Step2=7|x,y,z|35,0,-6|EaseInOut
Step3=30|x,y,z|35,0,-6|EaseInOut
Step4=32|x,y,z|0,0,-6|EaseInOut

[Airbreak_Bottom_3_cycle]
NumberOfSteps=4
Step1=5|x,y,z|0,0,2|EaseInOut
Step2=7|x,y,z|-35,0,2|EaseInOut
Step3=30|x,y,z|-35,0,2|EaseInOut
Step4=32|x,y,z|0,0,2|EaseInOut

[Airbreak_Bottom_4_cycle]
NumberOfSteps=4
Step1=5|x,y,z|0,0,-2|EaseInOut
Step2=7|x,y,z|-35,0,-2|EaseInOut
Step3=30|x,y,z|-35,0,-2|EaseInOut
Step4=32|x,y,z|0,0,-2|EaseInOut