[Animations]
NumberOfAnimations=8

Animation1=Flaps_Takeoff
Animation2=Flaps_Takeoff_Retract
Animation3=Flaps_Landing
Animation4=Flaps_Landing_Retract
Animation5=Gear_Extend
Animation6=Gear_Retract
Animation7=Bay_Open
Animation8=Bay_Close

[Flaps_Takeoff]
NumberOfSequencesToPlay=2
Sequence1=Left_Flap_Takeoff
Sequence1_Model=Left_Flap
Sequence2=Right_Flap_Takeoff
Sequence2_Model=Right_Flap

[Flaps_Takeoff_Retract]
NumberOfSequencesToPlay=2
Sequence1=Left_Flap_Takeoff_Retract
Sequence1_Model=Left_Flap
Sequence2=Right_Flap_Takeoff_Retract
Sequence2_Model=Right_Flap

[Flaps_Landing]
NumberOfSequencesToPlay=2
Sequence1=Left_Flap_Landing
Sequence1_Model=Left_Flap
Sequence2=Right_Flap_Landing
Sequence2_Model=Right_Flap

[Flaps_Landing_Retract]
NumberOfSequencesToPlay=2
Sequence1=Left_Flap_Landing_Retract
Sequence1_Model=Left_Flap
Sequence2=Right_Flap_Landing_Retract
Sequence2_Model=Right_Flap

[Gear_Extend]
NumberOfSequencesToPlay=12
Sequence1=Left_Gear_Door_1_Open
Sequence1_Model=Left_Gear_Door_1
Sequence2=Left_Gear_Door_2_Open
Sequence2_Model=Left_Gear_Door_2
Sequence3=Nose_Gear_Door_L_Open
Sequence3_Model=Nose_Gear_Door_L
Sequence4=Nose_Gear_Door_R_Open
Sequence4_Model=Nose_Gear_Door_R
Sequence5=Right_Gear_Door_1_Open
Sequence5_Model=Right_Gear_Door_1
Sequence6=Right_Gear_Door_2_Open
Sequence6_Model=Right_Gear_Door_2
Sequence7=Main_Gear_Extend
Sequence7_Model=Left_Gear
Sequence8=Main_Strut_Extend
Sequence8_Model=Left_Gear_Strut
Sequence9=Main_Gear_Extend
Sequence9_Model=Right_Gear
Sequence10=Main_Strut_Extend
Sequence10_Model=Right_Gear_Strut
Sequence11=Nose_Gear_Extend
Sequence11_Model=Nose_Gear
Sequence12=Nose_Strut_Extend
Sequence12_Model=Nose_Gear_Strut

[Gear_Retract]
NumberOfSequencesToPlay=12
Sequence1=Left_Gear_Door_1_Close
Sequence1_Model=Left_Gear_Door_1
Sequence2=Left_Gear_Door_2_Close
Sequence2_Model=Left_Gear_Door_2
Sequence3=Nose_Gear_Door_L_Close
Sequence3_Model=Nose_Gear_Door_L
Sequence4=Nose_Gear_Door_R_Close
Sequence4_Model=Nose_Gear_Door_R
Sequence5=Right_Gear_Door_1_Close
Sequence5_Model=Right_Gear_Door_1
Sequence6=Right_Gear_Door_2_Close
Sequence6_Model=Right_Gear_Door_2
Sequence7=Main_Gear_Retract
Sequence7_Model=Left_Gear
Sequence8=Main_Strut_Retract
Sequence8_Model=Left_Gear_Strut
Sequence9=Main_Gear_Retract
Sequence9_Model=Right_Gear
Sequence10=Main_Strut_Retract
Sequence10_Model=Right_Gear_Strut
Sequence11=Nose_Gear_Retract
Sequence11_Model=Nose_Gear
Sequence12=Nose_Strut_Retract
Sequence12_Model=Nose_Gear_Strut

[Bay_Open]
NumberOfSequencesToPlay=2
Sequence1=Bay_Door_L_Open
Sequence1_Model=Bay_Door_L
Sequence2=Bay_Door_R_Open
Sequence2_Model=Bay_Door_R

[Bay_Close]
NumberOfSequencesToPlay=2
Sequence1=Bay_Door_L_Close
Sequence1_Model=Bay_Door_L
Sequence2=Bay_Door_R_Close
Sequence2_Model=Bay_Door_R

[Left_Flap_Takeoff]
NumberOfSteps=2
Time1=0 
PositionX1=-0.075
PositionY1=-0.0079
PositionZ1=-0.041
RotationZ1=-9
Smoothness1=EaseInOut
Time2=5 
PositionX2=-0.0762
PositionY2=-0.0093
PositionZ2=-0.0464
RotationZ2=-29
Smoothness2=EaseInOut

[Right_Flap_Takeoff]
NumberOfSteps=2
Time1=0 
PositionX1=0.075
PositionY1=-0.0079
PositionZ1=-0.041
RotationZ1=-9
Smoothness1=EaseInOut
Time2=5 
PositionX2=0.0762
PositionY2=-0.0093
PositionZ2=-0.0464
RotationZ2=-29
Smoothness2=EaseInOut

[Left_Flap_Takeoff_Retract]
NumberOfSteps=2
Time1=0 
PositionX1=-0.0762
PositionY1=-0.0093
PositionZ1=-0.0464
RotationZ1=-29
Smoothness1=EaseInOut
Time2=5 
PositionX2=-0.075
PositionY2=-0.0079
PositionZ2=-0.041
RotationZ2=-9
Smoothness2=EaseInOut

[Right_Flap_Takeoff_Retract]
NumberOfSteps=2
Time1=0 
PositionX1=0.0762
PositionY1=-0.0093
PositionZ1=-0.0464
RotationZ1=-29
Smoothness1=EaseInOut
Time2=5 
PositionX2=0.075
PositionY2=-0.0079
PositionZ2=-0.041
RotationZ2=-9
Smoothness2=EaseInOut

//-----------------------------------------

[Left_Flap_Landing]
NumberOfSteps=2
Time1=0 
PositionX1=-0.075
PositionY1=-0.0079
PositionZ1=-0.041
RotationZ1=-9
Smoothness1=EaseInOut
Time2=5 
PositionX2=-0.0768
PositionY2=-0.0093
PositionZ2=-0.05
RotationZ2=-39
Smoothness2=EaseInOut

[Right_Flap_Landing]
NumberOfSteps=2
Time1=0 
PositionX1=0.075
PositionY1=-0.0079
PositionZ1=-0.041
RotationZ1=-9
Smoothness1=EaseInOut
Time2=5 
PositionX2=0.0768
PositionY2=-0.0093
PositionZ2=-0.05
RotationZ2=-39
Smoothness2=EaseInOut

[Left_Flap_Landing_Retract]
NumberOfSteps=2
Time1=0 
PositionX1=-0.0768
PositionY1=-0.0093
PositionZ1=-0.05
RotationZ1=-39
Smoothness1=EaseInOut
Time2=5 
PositionX2=-0.075
PositionY2=-0.0079
PositionZ2=-0.041
RotationZ2=-9
Smoothness2=EaseInOut

[Right_Flap_Landing_Retract]
NumberOfSteps=2
Time1=0 
PositionX1=0.0768
PositionY1=-0.0093
PositionZ1=-0.05
RotationZ1=-39
Smoothness1=EaseInOut
Time2=5 
PositionX2=0.075
PositionY2=-0.0079
PositionZ2=-0.041
RotationZ2=-9
Smoothness2=EaseInOut

[Left_Gear_Door_1_Close]
NumberOfSteps=3
Time1=0 
RotationZ1=-50
Smoothness1=EaseInOut
Time2=3 
RotationZ2=-50
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[Left_Gear_Door_2_Close]
NumberOfSteps=3
Time1=0 
RotationZ1=50
Smoothness1=EaseInOut
Time2=3 
RotationZ2=50
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[Nose_Gear_Door_L_Close]
NumberOfSteps=3
Time1=0 
RotationZ1=-90
Smoothness1=EaseInOut
Time2=3 
RotationZ2=-90
Smoothness2=EaseInOut
Time3=5
RotationZ3=0
Smoothness3=EaseInOut

[Nose_Gear_Door_R_Close]
NumberOfSteps=3
Time1=0 
RotationZ1=90
Smoothness1=EaseInOut
Time2=3 
RotationZ2=90
Smoothness2=EaseInOut
Time3=5
RotationZ3=0
Smoothness3=EaseInOut

[Right_Gear_Door_1_Close]
NumberOfSteps=3
Time1=0 
RotationZ1=50
Smoothness1=EaseInOut
Time2=3 
RotationZ2=50
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[Right_Gear_Door_2_Close]
NumberOfSteps=3
Time1=0 
RotationZ1=-50
Smoothness1=EaseInOut
Time2=3 
RotationZ2=-50
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

###Gear Struts Retraction



###Extend Gear

[Left_Gear_Door_1_Open]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-50
Smoothness2=EaseInOut

[Left_Gear_Door_2_Open]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=50
Smoothness2=EaseInOut

[Nose_Gear_Door_L_Open]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2
RotationZ2=-90
Smoothness2=EaseInOut
Time3=5
RotationZ3=-90
Smoothness3=EaseInOut

[Nose_Gear_Door_R_Open]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2
RotationZ2=90
Smoothness2=EaseInOut
Time3=5
RotationZ3=90
Smoothness3=EaseInOut

[Right_Gear_Door_1_Open]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=50
Smoothness2=EaseInOut

[Right_Gear_Door_2_Open]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-50
Smoothness2=EaseInOut

###Gear Struts Retraction

[Main_Gear_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=105
Smoothness1=EaseInOut
Time2=2 
RotationZ2=105
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[Main_Gear_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=3 
RotationZ2=105
Smoothness2=EaseInOut
Time3=5 
RotationZ3=105
Smoothness3=EaseInOut

[Main_Strut_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=-135
Smoothness1=EaseInOut
Time2=2
RotationZ2=-135
Smoothness2=EaseInOut
Time3=5
RotationZ3=0
Smoothness3=EaseInOut

[Main_Strut_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=3
RotationZ2=-135
Smoothness2=EaseInOut
Time3=5
RotationZ3=-135
Smoothness3=EaseInOut

[Nose_Gear_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=105
Smoothness1=EaseInOut
Time2=2 
RotationZ2=105
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[Nose_Gear_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=3 
RotationZ2=105
Smoothness2=EaseInOut
Time3=5 
RotationZ3=105
Smoothness3=EaseInOut

[Nose_Strut_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=-135
Smoothness1=EaseInOut
Time2=2
RotationZ2=-135
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[Nose_Strut_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=3
RotationZ2=-135
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-135
Smoothness3=EaseInOut

###Weapons Bay

[Bay_Door_L_Open]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-90
Smoothness2=EaseInOut

[Bay_Door_R_Open]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=90
Smoothness2=EaseInOut

[Bay_Door_L_Close]
NumberOfSteps=2
Time1=0 
RotationZ1=-90
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut

[Bay_Door_R_Close]
NumberOfSteps=2
Time1=0 
RotationZ1=90
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut