[Animations]
NumberOfAnimations=2
Animation1=HangarOpenAnim
Animation2=HangarCloseAnim


[HangarOpenAnim]
NumberOfSequencesToPlay=4
Sequence1=HangarOpenLeftOuterDoorSequence
Sequence1_Model=Hangar_Door_l1
Sequence2=HangarOpenLeftInnerDoorSequence
Sequence2_Model=Hangar_Door_l2
Sequence3=HangarOpenRightOuterDoorSequence
Sequence3_Model=Hangar_Door_r1
Sequence4=HangarOpenRightInnerDoorSequence
Sequence4_Model=Hangar_Door_r2

[HangarCloseAnim]
NumberOfSequencesToPlay=4
Sequence1=HangarCloseLeftOuterDoorSequence
Sequence1_Model=Hangar_Door_l1
Sequence2=HangarCloseLeftInnerDoorSequence
Sequence2_Model=Hangar_Door_l2
Sequence3=HangarCloseRightOuterDoorSequence
Sequence3_Model=Hangar_Door_r1
Sequence4=HangarCloseRightInnerDoorSequence
Sequence4_Model=Hangar_Door_r2


[------------------------------ Sequences ------------------------------]
#Open Hangar Doors
[HangarOpenLeftOuterDoorSequence]
NumberOfSteps=2
#Step<i>=Time|Position|Rotation|SmoothnessType
#Step<i>=0|None|0,0,0|Linear
Step1=0|x,y,z|x,0,z|Linear
Step2=12|x,y,z|x,75,z|Linear

[HangarOpenLeftInnerDoorSequence]
NumberOfSteps=2
Step1=0|x,y,z|x,0,z|Linear
Step2=12|x,y,z|x,-150,z|Linear

[HangarOpenRightOuterDoorSequence]
NumberOfSteps=2
Step1=0|x,y,z|x,0,z|Linear
Step2=12|x,y,z|x,-75,z|Linear

[HangarOpenRightInnerDoorSequence]
NumberOfSteps=2
Step1=0|x,y,z|x,0,z|Linear
Step2=12|x,y,z|x,150,z|Linear

#Close Hangar Doors
[HangarCloseLeftOuterDoorSequence]
NumberOfSteps=2
Step1=0|x,y,z|x,75,z|Linear
Step2=12|x,y,z|x,0,z|Linear

[HangarCloseLeftInnerDoorSequence]
NumberOfSteps=2
Step1=0|x,y,z|x,-150,z|Linear
Step2=12|x,y,z|x,0,z|Linear

[HangarCloseRightOuterDoorSequence]
NumberOfSteps=2
Step1=0|x,y,z|x,-75,z|Linear
Step2=12|x,y,z|x,0,z|Linear

[HangarCloseRightInnerDoorSequence]
NumberOfSteps=2
Step1=0|x,y,z|x,150,z|Linear
Step2=12|x,y,z|x,0,z|Linear