# ver. 20260702
#
[General]
HullnumberReference=Hullnumber
EmblemReference=Emblem
NationFlagReference=Flag1
AllVariantsAreOfSameNation=True
NumberOfVariants=5

[Default]
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/flag/
FlagTexture=flag_spain_81.png
Nation=Spain

[Variant1]
ResourcesHullnumberFolder=ships/ae_ffg_baleares/textures/
HullnumberTexture=spa_f71.png
ResourcesEmblemFolder=ships/ae_ffg_baleares/textures/
EmblemTexture=31esc_emblem.png
ResourcesLiveryFolder=ships/es_ffg_baleares/
LiveryTexture=es_ffg_baleares_tx
ResourcesFlagFolder=ships/materials/flag/
FlagTexture=flag_spain_81.png
Nation=Spain
ServiceDate=1988|2004

[Variant2]
ResourcesHullnumberFolder=ships/ae_ffg_baleares/textures/
HullnumberTexture=spa_f72.png
ResourcesEmblemFolder=ships/ae_ffg_baleares/textures/
EmblemTexture=31esc_emblem.png
ResourcesLiveryFolder=ships/es_ffg_baleares/
LiveryTexture=es_ffg_baleares_tx
ResourcesFlagFolder=ships/materials/flag/
FlagTexture=flag_spain_81.png
Nation=Spain
ServiceDate=1991|2005

[Variant3]
ResourcesHullnumberFolder=ships/ae_ffg_baleares/textures/
HullnumberTexture=spa_f73.png
ResourcesEmblemFolder=ships/ae_ffg_baleares/textures/
EmblemTexture=31esc_emblem.png
ResourcesLiveryFolder=ships/es_ffg_baleares/
LiveryTexture=es_ffg_baleares_tx
ResourcesFlagFolder=ships/materials/flag/
FlagTexture=flag_spain_81.png
Nation=Spain
ServiceDate=1989|2004

[Variant4]
ResourcesHullnumberFolder=ships/ae_ffg_baleares/textures/
HullnumberTexture=spa_f74.png
ResourcesEmblemFolder=ships/ae_ffg_baleares/textures/
EmblemTexture=31esc_emblem.png
ResourcesLiveryFolder=ships/es_ffg_baleares/
LiveryTexture=es_ffg_baleares_tx
ResourcesFlagFolder=ships/materials/flag/
FlagTexture=flag_spain_81.png
Nation=Spain
ServiceDate=1988|2009

[Variant5]
ResourcesHullnumberFolder=ships/ae_ffg_baleares/textures/
HullnumberTexture=spa_f75.png
ResourcesEmblemFolder=ships/ae_ffg_baleares/textures/
EmblemTexture=31esc_emblem.png
ResourcesLiveryFolder=ships/es_ffg_baleares/
LiveryTexture=es_ffg_baleares_tx
ResourcesFlagFolder=ships/materials/flag/
FlagTexture=flag_spain_81.png
Nation=Spain
ServiceDate=1989|2006

