#!alias vessels/usn_ffg_oliver_hazard_perry_longhull.ini
# ver. 20260818
#

[AirGroup]
spa_sh-60b_block1=Default,1

[FlightDeck]
AircraftCapacity=1
# AircraftSupported=spa_ab212,spa_md500,spa_sh-60b,spa_sh-60b_block1,fr_alouette_II,fr_as-350,iaf_md500,iqaf_md500,rn_lynx_has2,rn_wasp_has1,usn_qh-50c,usn_qh-50d,usn_sh-2f
AircraftSupported=spa_ab212,spa_md500,spa_sh-60b,spa_sh-60b_block1,fr_alouette_II,fr_as-350,iaf_md500,iqaf_md500,usn_sh-2f

[Elevator1]
RidePosition=-0.0575,0.062,-0.66

[Elevator2]
RidePosition=0.0575,0.063,-0.66

[LaunchPoint1]
Position=0,0.065,-0.765

[RecoveryPoint1]
Position=0,0.065,-0.80

[TaxiPath3]
Waypoints=

[TaxiPath4]
Waypoints=

[SensorSystems]
NumberOfSensorSystems=20

[SensorSystem20]  # FLIR/SVO sensor Mast
Type=Infrared
SystemName=FLIR_SVO
Mount=Dummy
MountPosition=0,0.396,0.1068

[SensorSystem7] #RIGEL ESM F81-F84
#RIGEL ESM + REGULUS COMINT
Type=ESM
SystemName=RIGEL_RESM
Mount=Dummy
MountPosition=0,0.392,0.088
Collider=coll_esm

[SensorSystem11] #RIGEL ECM F81-F84
# RIGEL DECM jammer + CECM REGULUS
Type=ECM
SystemName=RIGEL_RECM
Mount=Dummy
MountPosition=0,0.1944,0.3279
Collider=coll_ecm

[SensorSystem12] #SPS-49V5 F85 y F86
# Mounted on mast between bridge and main mast
Type=Radar
SystemName=SPS-49V5
Mount=SPS_49
Collider=coll_sps49

[SensorSystem13] #MK92_Mod6_FCS F85-F86
# Mk92 "Egg" fire control radar, mounted on top of the search radar in the upper half of the 'Egg' and provides the second anti-air FC channel
Type=Radar
SystemName=MK92_Mod6_FCS
Mount=Dummy
MountPosition=0,0.255,0.35
Collider=coll_mk92

[SensorSystem14] #MK92_Mod6_CORT_SearchRadar F85-F86
# Mk92 "Egg" surface search and tracking radar,exclusively surface search and can track/engage two surface targets at once
Type=Radar
SystemName=MK92_Mod6_CORT_SearchRadar
Mount=Dummy
MountPosition=0,0.245,0.35
Collider=coll_mk92

[SensorSystem15] #ELT_Nettuno_Mk3000_ESM F85-F86
# NETTUNEL ESM + ELNATH COMINT
Type=ESM
SystemName=ELT_Nettuno_Mk3000_ESM
Mount=Dummy
MountPosition=0,0.3922,0.090
Collider=coll_esm1,coll_esm2

[SensorSystem16] #ELT_Nettuno_Mk3000_ECM F85-F86
# DECM/OECM jammer + CECM ELNATH
Type=ECM
SystemName=ELT_Nettuno_Mk3000_ECM
Mount=Dummy
MountPosition=0,0.1934,0.3301
Collider=coll_ecm1,coll_ecm2

[SensorSystem17] #CIWS Optical
Type=Visual
SystemName=AdvancedOptics
Mount=Meroka_turret
Radar=Meroka_thermal

[SensorSystem18] #CIWS Radar
Type=Radar
SystemName=PVS-2_Sharpshooter
Mount=Meroka_radar_mount
Radar=Meroka_radar
RestAngles=-180,0

[SensorSystem19] #RAN-30X
# Improved Low level search radar for Meroka CIWS
Type=Radar
SystemName=eu_RAN-30x
Mount=RAN_12L
Collider=coll_ran12l
RestAngles=180,0


[WeaponSystems]
NumberOfWeaponSystems=8
AvailableLoadouts=F81-F84,F85-F86

Default_SensorsToRemove=9,10,12,13,14,15,16
Default_SubModelsToHide=CIWS1,CIWS_Gun1,NETTUNEL_EW
Empty_SensorsToRemove=9,10,12,13,14,15,16
Empty_SubModelsToHide=CIWS1,CIWS_Gun1,NETTUNEL_EW
F81-F84_SensorsToRemove=9,10,12,13,14,15,16
F81-F84_SubModelsToHide=CIWS1,CIWS_Gun1,NETTUNEL_EW
F85-F86_SensorsToRemove=2,4,7,8,9,10,11
F85-F86_SubModelsToHide=CIWS1,CIWS_Gun1

[WeaponSystem1] #MK13
AssociatedSearchSensors=SensorSystem1,SensorSystem2,SensorSystem20
FiringArcs=-145,145

[WeaponSystem1F81-F84] #MK13
Type=Missile
SystemName=MK13
AssociatedSensors=SensorSystem4,SensorSystem5
AssociatedSearchSensors=SensorSystem1,SensorSystem2,SensorSystem20
UnloadAmmunitionAnimation=UnloadAmmunition
LoadAmmunitionAnimation=LoadAmmunition
Mount=MK13_Mount
IsMountRotatable=True
ContainerBase=MK13_Rail
NumberOfContainers=1
Container1=MK13_Rail
AreContainersRotatable=True
FixVerticalLaunchAngle=False
AdditionalFixVerticalLaunchAngle=15
FiringArcs=-145,145
ElevationArc=10,85
RestAngles=180,-90
LoadAngles=180,-90
AssociatedMagazine=WeaponMagazineMK13_F81-F84
Collider=coll_mk13

[WeaponSystem1F85-F86] #MK13
Type=Missile
SystemName=MK13
AssociatedSensors=SensorSystem13,SensorSystem5
AssociatedSearchSensors=SensorSystem1,SensorSystem12,SensorSystem20
UnloadAmmunitionAnimation=UnloadAmmunition
LoadAmmunitionAnimation=LoadAmmunition
Mount=MK13_Mount
IsMountRotatable=True
ContainerBase=MK13_Rail
NumberOfContainers=1
Container1=MK13_Rail
AreContainersRotatable=True
FixVerticalLaunchAngle=False
AdditionalFixVerticalLaunchAngle=15
FiringArcs=-145,145
ElevationArc=10,85
RestAngles=180,-90
LoadAngles=180,-90
AssociatedMagazine=WeaponMagazineMK13_F85-F86
Collider=coll_mk13

[WeaponSystem4] #MK75 Gun
FiringArcs=20,340

[WeaponSystem4F81-F84] #MK75 Gun
Type=Gun
SystemName=MK75
AssociatedSensors=SensorSystem8,SensorSystem5
Mount=MK75_Turret
IsMountRotatable=True
ContainerBase=MK75_Gun
NumberOfGuns=1
Gun1=MK75_Barrel
AreContainersRotatable=True
FiringArcs=20,340
ElevationArc=-15,85
RestAngles=180
AssociatedMagazine=WeaponMagazineMK75
Collider=coll_mk75

[WeaponSystem4F85-F86] #MK75 Gun
Type=Gun
SystemName=MK75
AssociatedSensors=SensorSystem14,SensorSystem5
Mount=MK75_Turret
IsMountRotatable=True
ContainerBase=MK75_Gun
NumberOfGuns=1
Gun1=MK75_Barrel
AreContainersRotatable=True
FiringArcs=20,340
ElevationArc=-15,85
RestAngles=180
AssociatedMagazine=WeaponMagazineMK75
Collider=coll_mk75

[WeaponSystem5] #MEROKA CIWS
Type=CIWS
SystemName=Meroka_CIWS
AssociatedSensors=SensorSystem17,SensorSystem18,SensorSystem19
Mount=Meroka_turret
IsMountRotatable=True
ContainerBase=Meroka_gun
Gun=Meroka_gun
AreContainersRotatable=True
FiringArcs=20,340
ElevationArc=-15,85
RestAngles=-180
AssociatedMagazine=WeaponMagazineMeroka
WorksStandalone=True
Collider=coll_ciws

[WeaponSystem7] #Chaff
MountPosition=-0.4,0.8,1.0

[WeaponSystem8] #Chaff
MountPosition=0.4,0.6,0.9

[WeaponMagazineMK13]
Ammunition1=usn_rgm-84d
Ammunition1_Count=4
Ammunition2=spa_rim-66e_VIb
Ammunition2_Count=36
ArmorType=Minor
IsCoveredByMainArmor=True

[WeaponMagazineMK13_F81-F84]
NumberOfAmmunitionTypes=2
Ammunition1=usn_rgm-84d
Ammunition1_Count=4
Ammunition2=spa_rim-66e_VIb
Ammunition2_Count=36
ArmorType=Minor
IsCoveredByMainArmor=True
Collider=coll_mk13_magazine
ModuleType=MediumMagazine

[WeaponMagazineMK13_F85-F86]
NumberOfAmmunitionTypes=2
Ammunition1=usn_rgm-84d
Ammunition1_Count=4
Ammunition2=spa_rim-66e_VIb
Ammunition2_Count=36
ArmorType=Minor
IsCoveredByMainArmor=True
Collider=coll_mk13_magazine
ModuleType=MediumMagazine

[WeaponMagazineMK75]
Ammunition1_Count=520
ArmorType=Minor
IsCoveredByMainArmor=True

[WeaponMagazineMeroka]
NumberOfAmmunitionTypes=1
Ammunition1_Count=2000
Ammunition1=usn_cal_20mm
ArmorType=Minor
IsCoveredByMainArmor=True
Collider=coll_ciws_magazine
ModuleType=SmallMagazine


[Submodels]

SubModel3=Parts1
SubModel3B=Parts2

SubModelFairlead_2=Argos_EO
SubModelECM_1=NETTUNEL_EW

SubMode200=Meroka_turret
SubMode201=Meroka_gun
SubMode202=Meroka_base
SubMode203=Meroka_thermal
SubMode204=Meroka_radar_mount
SubMode205=Meroka_radar
SubMode206=RAN_12L

[Parts1]
ResourcesMeshFolder=ships/ae_ffg_santa_maria/
RootMesh=ae_ffg_santa_maria_parts1.obj
Mesh=parts
ResourcesMaterialFolder=ships/materials/
Material=usn_parts

[Parts2]
ResourcesMeshFolder=ships/ae_ffg_santa_maria/
RootMesh=ae_ffg_santa_maria_parts1.obj
Mesh=parts2
ResourcesMaterialFolder=ships/materials/
Material=usn_parts

[Argos_EO] # Argos15HD
ResourcesMeshFolder=ships/ae_ffg_santa_maria/
RootMesh=ae_ffg_santa_maria_parts1.obj
Mesh=Argos15HD
ResourcesMaterialFolder=ships/materials/
Material=usn_parts

[NETTUNEL_EW] # NETTUNEL Mk3000 ESM/ECM suite
ResourcesMeshFolder=ships/ae_ffg_santa_maria/
RootMesh=ae_ffg_santa_maria_parts1.obj
Mesh=NETTUNEL
ResourcesMaterialFolder=ships/materials/
Material=usn_parts

[Hullnumber]
ResourcesMeshFolder=ships/ae_ffg_santa_maria/
RootMesh=ae_ffg_santa_maria_hullnumbers.obj
Mesh=Hullnumbers
ResourcesMaterialFolder=ships/materials/hullnumbers/
Material=hullnumber

[RAN_12L]
ResourcesMeshFolder=ships/usn_lpd_austin/
RootMesh=usn_lpd_austin.obj
Mesh=usn_lpd_austin_sps_67
ResourcesMaterialFolder=ships/materials/
Material=usn_sps_67
Position=0,0.361,0.045
Rotation=0,0,0
HideWithActiveDamageModel=True

[Meroka_base]
ResourcesMeshFolder=assets/models/weapon/meroka/
RootMesh=meroka.obj
Mesh=meroka_base
ResourcesMaterialFolder=assets/models/weapon/meroka/
Material=meroka_mat.ini
Position=0,0.151,-0.5626
Rotation=0,-180,0

[Meroka_turret]
ResourcesMeshFolder=assets/models/weapon/meroka/
RootMesh=meroka.obj
Mesh=meroka_turret_test
ResourcesMaterialFolder=assets/models/weapon/meroka/
Material=meroka_mat.ini
Position=0,0.166,-0.5626
Rotation=0,-180,0

[Meroka_gun]
ResourcesMeshFolder=assets/models/weapon/meroka/
RootMesh=meroka.obj
Mesh=meroka_gun
ResourcesMaterialFolder=assets/models/weapon/meroka/
Material=meroka_mat.ini
Position=0.0,0.005539,0.003614
Parent=Meroka_turret

[Meroka_thermal]
ResourcesMeshFolder=assets/models/weapon/meroka/
RootMesh=meroka.obj
Mesh=meroka_thermal_test
ResourcesMaterialFolder=assets/models/weapon/meroka/
Material=meroka_mat.ini
Position=0.0,0.025045,-0.003777
Parent=Meroka_turret

[Meroka_radar_mount]
ResourcesMeshFolder=assets/models/weapon/meroka/
RootMesh=meroka.obj
Mesh=meroka_radar_mount_test
ResourcesMaterialFolder=assets/models/weapon/meroka/
Material=meroka_mat.ini
Position=0.01211,0.020143,-0.006929
Parent=Meroka_turret

[Meroka_radar]
ResourcesMeshFolder=assets/models/weapon/meroka/
RootMesh=meroka.obj
Mesh=meroka_radar_test
ResourcesMaterialFolder=assets/models/weapon/meroka/
Material=meroka_mat.ini
Position=-0.000762,0.006504,-0.0
Parent=Meroka_radar_mount

[Hangar_Door_A_L]
Position=-0.05,0.061,-0.5910

[Hangar_Door_B_L]
Position=-0.05,0.0759,-0.5908

[Hangar_Door_C_L]
Position=-0.05,0.0908,-0.5906

[Hangar_Door_D_L]
Position=-0.05,0.1052,-0.5904

[Hangar_Door_E_L]
Position=-0.09275,0.061,-0.591

[Hangar_Door_A_R]
Position=0.05,0.061,-0.591

[Hangar_Door_B_R]
Position=0.05,0.0759,-0.5908

[Hangar_Door_C_R]
Position=0.05,0.0908,-0.5906

[Hangar_Door_D_R]
Position=0.05,0.1052,-0.5904

[Hangar_Door_E_R]
Position=0.09275,0.061,-0.591

[Crew]
Material=nato_crew

[Colliders]
NumberOfColliders=26

Collider21=coll_esm1
Collider22=coll_esm2
Collider23=coll_ecm1
Collider24=coll_ecm2
Collider25=coll_ecm
Collider26=coll_ran12l

[coll_ciws]
Scale=0.03,0.06,0.04

[coll_ecm]
Collider=Box
Position=0,0.1944,0.3279
Rotation=0,0,0
Scale=0.13,0.02,0.032

[coll_esm]
Collider=Box
Position=0,0.392,0.088
Rotation=0,0,0
Scale=0.13,0.02,0.032

[coll_esm1]
Collider=Box
Position=-0.0729,0.3922,0.090
Rotation=0,0,0
Scale=0.01,0.018,0.03

[coll_esm2]
Collider=Box
Position=0.0729,0.3922,0.090
Rotation=0,0,0
Scale=0.01,0.018,0.03

[coll_ecm1]
Collider=Box
Position=-0.0718,0.1934,0.3301
Rotation=0,0,0
Scale=0.01,0.018,0.03

[coll_ecm2]
Collider=Box
Position=0.0718,0.1934,0.3301
Rotation=0,0,0
Scale=0.01,0.018,0.03

[coll_ran12l]
Collider=Sphere
Position=0,0.361,0.045
Rotation=0,0,0
Scale=0.04,0.04,0.04
