#!alias vessels/usn_msc_adjutant.ini
# ver. 20260721
#

[Submodels]
SubModel13=Hullnumber

[Hullnumber]
ResourcesMeshFolder=ships/ae_msc_jucar/
RootMesh=ae_msc_jucar_hullnumbers.obj
Mesh=Hullnumbers
ResourcesMaterialFolder=ships/materials/hullnumbers/
Material=hullnumber

