 [ ========================================= General ========================================== ]
[General]
DataLinkUpdateRate=1             // every x seconds there will be an update for the overall sensor image for the minimap
PassiveSensorUpdateRate=1.0        // every x seconds the passive contacts will be re-evaluated
LostPassiveContactTimeToDisable=5  // time in seconds after which a lost passive contact bearing line will be greyed out
LostContactTimeToRemove=30         // time in seconds after which a lost contact will be removed from the map


[======================================== France ========================================]

[GF300]
Kind=Radar
Type=Search
HasDataLink=True
Role=AirAndSurface
Mode=Illuminate
RotationDirection=1
RPM=60
MinRange=0.5
MaxRange=380.0                 // Légèrement en dessous de la valeur max pour le jeu
MinAltitude=0
MaxAltitude=70000
RangeResolution=25.0
BeamWidth=1.2
Gain=53.0
Frequency=S-Band
PeakPower=1200.0
ModuleType=BigSensor
TargetChannels=8          # Nombre de cibles suivies simultanément
WeaponChannels=8           # Nombre de missiles guidés simultanément (le plus important)

[Saclos]  
Kind=Visual
Type=Targeting
HasDataLink=False
Role=Surface
Mode=Illuminate
#RotationDirection=1          # Pas nécessaire pour un système optique
#RPM=0                        # Pas de rotation
MinRange=0.05
MaxRange=6.0                    // Portée efficace du MILAN ER (~5-6 km)
MinAltitude=0
MaxAltitude=3000
RangeResolution=8.0
AngularResolution=0.5           // Très important pour le guidage SACLOS
Gain=45.0
Frequency=Visible+IR           // Commentaire : Optique + Infrarouge
ModuleType=SmallSensor
# Paramètres spécifiques SACLOS
VIDRangeMultiplier=5.5
MaxRangeMultiplier=5.0
UseIRValues=True
LookDownMultiplier=0.85


[FCR]   # Fire Control Radar
Kind=Radar
Type=Targeting                    # Très important pour FCR
HasDataLink=True
Role=Surface                # Ou Surface seulement selon l'usage
Mode=Illuminate
MinRange=0.05
MaxRange=35.0                     # Doit être supérieur à la portée du missile
MinAltitude=5
MaxAltitude=15000
RangeResolution=12.0
BeamWidth=0.8
Gain=52.0                         # Gain élevé = meilleure détection
Frequency=X-Band                  # Le plus courant pour FCR
PeakPower=250.0
ModuleType=MediumSensor           # ou SmallSensor
TargetChannels=4
WeaponChannels=4