[F1]
#F1 120mm canon
HorizontalDegreesPerSecond=40   // rotation speed horizontally
VerticalDegreesPerSecond=25     // rotation speed vertically
FireRate=12                     // rounds per minute
RoundsLoaded=1                  // number of rounds loaded
ReloadTime=5                    // magazine reload time in seconds
RecoilTime=0.5                  // time in seconds for the recoil
RecoilStrength=0.000030          // amplitude of recoil
MoveToRestPositionTime=5.0     // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/5inch_fire_emitter2
EffectPosition=0,0.0268,0.104
SpawnPosition=0,0,0.223
ModuleType=MediumTurret

[M811]
#M811 25 mm canon
MissileInterceptChance=-1       // For CIWS. Chance to intercept missile with 0 defense rating
AircraftInterceptChance=10      // For CIWS. Chance to intercept aircraft with 0 defense rating
HorizontalDegreesPerSecond=50   // rotation speed horizontally
VerticalDegreesPerSecond=60     // rotation speed vertically
FireRate=400                    // rounds per minute
BurstTime=1.1                   // the length of a single burst in time
RoundsLoaded=200                // number of rounds loaded
ReloadTime=0                    // magazine reload time in seconds
MoveToRestPositionTime=5.0      // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/usn_m39_burst
EffectPosition=0,0,0.0273
SpawnPosition=0,0,0.0273


[40CTC_Gun]
HorizontalDegreesPerSecond=60   // rotation speed horizontally
VerticalDegreesPerSecond=60     // rotation speed vertically
FireRate=200                    // rounds per minute
RoundsLoaded=1               // number of rounds loaded
ReloadTime=0.3                   // magazine reload time in seconds
RecoilTime=0.1                  // time in seconds for the recoil
RecoilStrength=0.0007          // amplitude of recoil
MoveToRestPositionTime=30.0     // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/AK726_fire_emitter
EffectPosition=0,0,0.06
SpawnPosition=0,0,0.12
ModuleType=SmallTurret

[Akeron]
NumberOfAttachments=2
AttachmentPosition1=0,0.0018,0
AttachmentPosition2=0,-0.0018,0
HorizontalDegreesPerSecond=50    // rotation speed horizontally
VerticalDegreesPerSecond=0       // rotation speed vertically
ReloadTime=120                   // time in seconds after firing until launcher is reloaded
MoveToRestPositionTime=30.0      // time in seconds the weapon goes back to rest position if not used
SmokeEffect=effects/weapons/emitters/LauncherSmoke
SmokeEffectPosition=0,0,0
PreLaunchDelay=2
ModuleType=SmallLauncher


[Mag58]
MissileInterceptChance=5       // For CIWS. Chance to intercept missile with 0 defense rating
AircraftInterceptChance=15      // For CIWS. Chance to intercept missile with 0 defense rating
HorizontalDegreesPerSecond=80  // rotation speed horizontally
VerticalDegreesPerSecond=70    // rotation speed vertically
FireRate=800                   // rounds per minute
BurstTime=2                   // the length of a single burst in time
RoundsLoaded=200              // number of rounds loaded
ReloadTime=8                    // magazine reload time in seconds
MoveToRestPositionTime=12.0     // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/usn_50cal_twin_burst
EffectPosition=-0.0012,0,0
SpawnPosition=0,0,0.0

[F2]
# F2 105mm canon
HorizontalDegreesPerSecond=40   // rotation speed horizontally
VerticalDegreesPerSecond=24     // rotation speed vertically
FireRate=25                     // rounds per minute
RoundsLoaded=1                  // number of rounds loaded
ReloadTime=5                    // magazine reload time in seconds
RecoilTime=0.5                  // time in seconds for the recoil
RecoilStrength=0.00005          // amplitude of recoil
MoveToRestPositionTime=30.0     // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/5inch_fire_emitter2
EffectPosition=-0.000273,0.0277,0.077
SpawnPosition=0,0,0
ModuleType=MediumTurret


[M2_coxiale]
MissileInterceptChance=-1       // For CIWS. Chance to intercept missile with 0 defense rating
AircraftInterceptChance=20      // For CIWS. Chance to intercept missile with 0 defense rating
HorizontalDegreesPerSecond=65  // rotation speed horizontally
VerticalDegreesPerSecond=65    // rotation speed vertically
FireRate=500                   // rounds per minute
BurstTime=2                   // the length of a single burst in time
RoundsLoaded=105              // number of rounds loaded
ReloadTime=20                    // magazine reload time in seconds
MoveToRestPositionTime=15.0     // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/usn_50cal_twin_burst
EffectPosition=-0.00473,0.025,0.01073
SpawnPosition=0,0,0.0

[M2]
MissileInterceptChance=5      // For CIWS. Chance to intercept missile with 0 defense rating
AircraftInterceptChance=30      // For CIWS. Chance to intercept missile with 0 defense rating
HorizontalDegreesPerSecond=70  // rotation speed horizontally
VerticalDegreesPerSecond=60    // rotation speed vertically
FireRate=500                   // rounds per minute
BurstTime=3                   // the length of a single burst in time
RoundsLoaded=125              // number of rounds loaded
ReloadTime=9                    // magazine reload time in seconds
MoveToRestPositionTime=15.0     // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/usn_50cal_twin_burst
EffectPosition=-0.000197,-0.000221,0.0185
SpawnPosition=0,0,0.0

[AANF1_coxiale]
MissileInterceptChance=-1 
AircraftInterceptChance=10     // For CIWS. Chance to intercept aircraft with 0 defense rating
HorizontalDegreesPerSecond=55  // rotation speed horizontally
VerticalDegreesPerSecond=45    // rotation speed vertically
FireRate=900                 // rounds per minute
RoundsLoaded=200                // number of rounds in magazine
ReloadTime=12                   // magazine reload time in seconds
MoveToRestPositionTime=30.0    // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/usn_50cal_twin_burst
EffectPosition=-0.00371,0.0271,0.0191
SpawnPosition=0,0,0
ModuleType=OpenMount

[FN_Minimi]
MissileInterceptChance=1      // For CIWS. Chance to intercept missile with 0 defense rating
AircraftInterceptChance=25      // For CIWS. Chance to intercept missile with 0 defense rating
HorizontalDegreesPerSecond=70  // rotation speed horizontally
VerticalDegreesPerSecond=60    // rotation speed vertically
FireRate=950                   // rounds per minute
BurstTime=3                   // the length of a single burst in time
RoundsLoaded=200              // number of rounds loaded
ReloadTime=9                    // magazine reload time in seconds
MoveToRestPositionTime=15.0     // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/usn_50cal_twin_burst
EffectPosition=-0.00041,0.000377,-0.011
SpawnPosition=0,0,0.0

[LRM]
SalvoFireAmount=4                        // number of shots fired
SalvoFireTime=4                          // in seconds, Delay between the launches
SalvoFireTargetAreaCircleRadius=0        // in meters, circle radius for the target area where the single shots shall land. Use ONLY when CIRCULAR pattern is needed

NumberOfAttachments=12                   // per container
AttachmentPosition1=-0.0378,0.0124,0.0257
AttachmentPosition2=-0.0331,0.0124,0.0257
AttachmentPosition3=-0.0284,0.0124,0.0257
AttachmentPosition4=-0.0166,0.0124,0.0257
AttachmentPosition5=-0.0119,0.0124,0.0257
AttachmentPosition6=-0.00713,0.0124,0.0257
AttachmentPosition7=-0.0378,0.00767,0.0257
AttachmentPosition8=-0.0331,0.00767,0.0257
AttachmentPosition9=-0.0284,0.00767,0.0257
AttachmentPosition10=-0.0166,0.00767,0.0257
AttachmentPosition11=-0.0119,0.00767,0.0257
AttachmentPosition12=-0.00713,0.00767,0.0257

SmokeEffect=effects/weapons/emitters/LauncherSmoke
SmokeEffectPosition=0,0,-0.025
DustEffect=effects/weapons/emitters/MLRS_backblast
//large_artillery_firing_dust
DustEffectPosition=0,0,0        // From weapon system mount
DustEffectRotation=0,180,0        // From weapon system mount
SpawnPosition=0,0,0
ReloadTime=300                          // time in seconds after firing until launcher is reloaded
ModuleType=MediumLauncher


[SAMPT]
HorizontalDegreesPerSecond=0     // rotation speed horizontally
VerticalDegreesPerSecond=0       // rotation speed vertically
NumberOfAttachments=1            // per container
AttachmentPosition1=0,0,0
ReloadTime=1200
MoveToRestPositionTime=1      // time in seconds the weapon goes back to rest position if not used
Warmup=False
SmokeEffect=effects/weapons/emitters/LauncherSmoke
SmokeEffectPosition=0,0,0.055
SmokeEffectDirectional=True
ModuleType=VLS

[155mm]
#155mm canon
HorizontalDegreesPerSecond=14   // rotation speed horizontally
VerticalDegreesPerSecond=12     // rotation speed vertically
FireRate=6                     // rounds per minute
RoundsLoaded=18                  // number of rounds loaded
ReloadTime=40                    // magazine reload time in seconds
RecoilTime=0.25                  // time in seconds for the recoil
RecoilStrength=0.0012          // amplitude of recoil
MoveToRestPositionTime=5.0     // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/5inch_fire_emitter2
EffectPosition=0,0,0.108
SpawnPosition=0,0,0.223
ModuleType=MediumTurret

[AANF1_army]
MissileInterceptChance=1      // For CIWS. Chance to intercept missile with 0 defense rating
AircraftInterceptChance=20      // For CIWS. Chance to intercept missile with 0 defense rating
HorizontalDegreesPerSecond=70  // rotation speed horizontally
VerticalDegreesPerSecond=60    // rotation speed vertically
FireRate=900                   // rounds per minute
BurstTime=3                   // the length of a single burst in time
RoundsLoaded=200              // number of rounds loaded
ReloadTime=9                    // magazine reload time in seconds
MoveToRestPositionTime=15.0     // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/usn_50cal_twin_burst
EffectPosition=0.000663,0.000188,0.00859
SpawnPosition=0,0,0.0

[Milan]
NumberOfAttachments=1
AttachmentPosition1=0.000245,0.00619,-0.00263
HorizontalDegreesPerSecond=50    // rotation speed horizontally
VerticalDegreesPerSecond=0       // rotation speed vertically
ReloadTime=30                   // time in seconds after firing until launcher is reloaded
MoveToRestPositionTime=5.0      // time in seconds the weapon goes back to rest position if not used
SmokeEffect=effects/weapons/emitters/LauncherSmoke
SmokeEffectPosition=0,0,0
PreLaunchDelay=1
ModuleType=SmallLauncher
