[AmmunitionNames]
# ------------------ AAM ------------------

# ------------------ SAM ------------------

# ---------- Anti-radar Missiles ---------

# ---------- Anti-ship Missiles ----------

#-----------Land Strike only missiles---------

# ---------- Anti-sub  Missilies ----------

usn_agm-65d=AGM-65D,小牛,对地攻击,AGM-65D是美国的红外制导防区外空对地武器，可以在恶劣环境下锁定目标。其使用方式类似于AGM-62，由发射平台的操作员将十字准线对准所需目标进行引导。

# ------------------ RBU ------------------

# --------------- Torpedoes ---------------

# ------------------ Bombs -----------------

# ---------------- Sonobuoys ---------------

# ------------------ FFAR -----------------

# ------------------ MLRS -----------------

# ------------------ Guns -----------------

# ------------------ CIWS -----------------
usn_cal_pgu-14b=PGU-14/B,贫铀穿甲弹,,GAU-8使用的穿甲弹链
# ----------- Noisemakers/Chaff -----------

# ----------------- Decoys ----------------

# ----------------- Special ----------------

# Depth charge

# ----------------- Fueltanks ----------------


