[General]
UnitType=LandUnit
LandUnitSubType=Installation //Supported values: Airbase,SAM,Installation,MobileUnit,Radar,Port
DefaultCameraDistance=2.5
MinCameraDistanceForeAft=1.5
MinCameraDistanceBroadside=1.5
CameraPivotHeight=0.25

AutoFlatten=True
MaskVegetation=True
# Hull armor: None, Minor, Moderate, Heavy
ArmorType=Moderate
DamagePoints=120  //systems damage contribution substracted from this when systems destroyed, when becomes less than zero, the whole unit is considered being destroyed

[Tacview]
Name=Ammo Dump Bunker
Tag=Ground+Vehicle

[AI]
UnitScoreValue=25               // value for calculation of mission score
Role=Target

[ControlSystem]
Collider=coll_bunker
Integrity=1

[SensorData]
#Visual
VisualIdentificationRange=10 // Camouflaged  (x0.5)
IRSignature=Medium
# Radar related (RCS => radar cross section)
RCS=Medium

[---------- Sensor Systems ----------]
[SensorSystems]
NumberOfSensorSystems=1
#---------- Visual ----------
[SensorSystem1] #Bridge
# Bridge. Does not need SystemGroup and Collider because we do not want ship to loose ability to VID targets
Type=Visual
SystemName=Optics
Mount=Dummy
#MountPosition=0,0.255,0
MountPosition=0,1,0 //Observer on top of the tower
ModuleType=Bridge
Collider=
Integrity=6


[ ---------- HitZones ---------- ]
[HitZones]
NumberOfHitZones=1
[HitZone1]
SystemName=Bunker
Collider=coll_bunker
Integrity=120 //the number of hit points substracted from the overall damage points count when the system is destroyed

[ ---------- Target Points definitions ---------- ]
[TargetingData]
NumberOfTargetPoints=1
TargetPointPosition1=0,0,0
TargetPointAssociatedSystems1=HitZone1
TargetPointPriority1=High



[--------------------------- Mesh definitons ---------------------------]
[Models]
LODLevels=1
LOD1Distance=15  // nautical miles

############################################################
ResourcesFolder=Buildings/Ammo_bunker/
ResourcesRoot=ammobunker.obj
ResourcesMesh=ammobunker
ResourcesMaterialFolder=Buildings/Ammo_bunker/
ResourcesMaterial=ammobunker_mat.ini


[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=1
AmbientAudioClip=audio/ships/Ship-Turbine-Medium
AmbientAudioPosition=0,0,-0.35
AmbientAudioRollOff=Logarithmic
AmbientAudioDistance=1,20
AmbientAudioPitchRange=1.0,1.6
AmbientAudioVolume=0.0
AmbientAudioAudibility=Above  // layer of sound audibility: Above, Below, AboveAndBelow

[Particles]
SmallFireEffectClass=SmallShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=SmallShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=SmallShipFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffect=effects/explosions/emitters/missile_hit_ship
SecondaryExplosionEffectPosition=0,0,0

[---------- Colliders ----------]
[Colliders]
UseKinematicCollision=False
NumberOfColliders=0
NumberOfMeshColliders=1

MeshCollider1=coll_bunker


#Collider1=coll_target


[coll_bunker]
Collider=coll_ambun


#[coll_target]
#Collider=Box
#Position=0.05,0,-0.4
#Rotation=0,0,0
#Scale=0.1,0.1,0.1

