[General]
UnitType=LandUnit
LandUnitSubType=Installation //Supported values: Airbase,SAM,Installation,MobileUnit,Radar,Port
DefaultCameraDistance=2.5
MinCameraDistanceForeAft=1.5
MinCameraDistanceBroadside=1.5
CameraPivotHeight=0.25

AutoFlatten=True
MaskVegetation=True
# Hull armor: None, Minor, Moderate, Heavy
ArmorType=None
DamagePoints=60  //systems damage contribution substracted from this when systems destroyed, when becomes less than zero, the whole unit is considered being destroyed

[Tacview]
Name=Forward Operating Base
Tag=Ground+Vehicle

[AI]
UnitScoreValue=10               // value for calculation of mission score
Role=Target

[ControlSystem]
Collider=coll_guard1,coll_guard2
Integrity=10

[SensorData]
#Visual
VisualIdentificationRange=20  // Camouflaged  (x0.5)
IRSignature=VeryLarge
# Radar related (RCS => radar cross section)
RCS=VeryLarge

[---------- Sensor Systems ----------]
[SensorSystems]
NumberOfSensorSystems=1
#---------- Visual ----------
[SensorSystem1] #Bridge
# Bridge. Does not need SystemGroup and Collider because we do not want ship to loose ability to VID targets
Type=Visual
SystemName=Optics
Mount=Dummy
#MountPosition=0,0.255,0
MountPosition=0,1,0 //Observer on top of the tower
ModuleType=Bridge
Collider=
Integrity=6


[ ---------- HitZones ---------- ]
[HitZones]
NumberOfHitZones=5
[HitZone1]
SystemName=Guardtower1
Collider=coll_guard1
Integrity=20 //the number of hit points substracted from the overall damage points count when the system is destroyed

[HitZone2]
SystemName=Guardtower1
Collider=coll_guard2
Integrity=20 //the number of hit points substracted from the overall damage points count when the system is destroyed

[HitZone3]
SystemName=Hutt1
Collider=coll_hutt1
Integrity=10 //the number of hit points substracted from the overall damage points count when the system is destroyed

[HitZone4]
SystemName=Hutt2
Collider=coll_hutt2
Integrity=10 //the number of hit points substracted from the overall damage points count when the system is destroyed

[HitZone5]
SystemName=Hutt3
Collider=coll_hutt3
Integrity=10 //the number of hit points substracted from the overall damage points count when the system is destroyed

[ ---------- Target Points definitions ---------- ]
[TargetingData]
NumberOfTargetPoints=5
TargetPointPosition1=-0.4,0,-0.4
TargetPointAssociatedSystems1=HitZone1
TargetPointPriority1=High

TargetPointPosition2=0.32,0,0.4
TargetPointAssociatedSystems2=HitZone2
TargetPointPriority2=High

TargetPointPosition3=-0.3,0,-0.4
TargetPointAssociatedSystems3=HitZone3
TargetPointPriority3=Low

TargetPointPosition4=-0.15,0,-0.4
TargetPointAssociatedSystems3=HitZone3
TargetPointPriority4=Low

TargetPointPosition5=0.05,0,-0.4
TargetPointAssociatedSystems3=HitZone3
TargetPointPriority5=Low

[--------------------------- Mesh definitons ---------------------------]
[Models]
LODLevels=1
LOD1Distance=15  // nautical miles

############################################################
ResourcesFolder=Buildings/Forward_base/
ResourcesRoot=Foward_base.obj
ResourcesMesh=FOB
ResourcesMaterialFolder=Buildings/Forward_base
ResourcesMaterial=Foward_base_mat.ini


[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=1
AmbientAudioClip=audio/ships/Ship-Turbine-Medium
AmbientAudioPosition=0,0,-0.35
AmbientAudioRollOff=Logarithmic
AmbientAudioDistance=1,20
AmbientAudioPitchRange=1.0,1.6
AmbientAudioVolume=0.0
AmbientAudioAudibility=Above  // layer of sound audibility: Above, Below, AboveAndBelow

[Particles]
SmallFireEffectClass=SmallShipFire
SmallFireEffectPosition=0.084,0,-0.5
ModerateFireEffectClass=SmallShipFire
ModerateFireEffectPosition=0.084,0,-0.5
SevereFireEffectClass=SmallShipFire
SevereFireEffectPosition=0.084,0,-0.5
SecondaryExplosionEffect=effects/explosions/emitters/missile_hit_ship
SecondaryExplosionEffectPosition=0.084,0,-0.5

[---------- Colliders ----------]
[Colliders]
UseKinematicCollision=False
NumberOfColliders=0
NumberOfMeshColliders=5

MeshCollider1=coll_guard1
MeshCollider2=coll_guard2
MeshCollider3=coll_hutt1
MeshCollider4=coll_hutt2
MeshCollider5=coll_hutt3

#Collider1=coll_target


[coll_guard1]
Collider=Coll_G1
[coll_guard2]
Collider=Coll_G2
[coll_hutt1]
Collider=Coll_H1
[coll_hutt2]
Collider=Coll_H2
[coll_hutt3]
Collider=Coll_H3

#[coll_target]
#Collider=Box
#Position=0.05,0,-0.4
#Rotation=0,0,0
#Scale=0.1,0.1,0.1

