[General]
UnitType=LandUnit
LandUnitSubType=Installation //Supported values: Airbase,SAM,Installation,MobileUnit,Radar,Port
DefaultCameraDistance=2.5
MinCameraDistanceForeAft=1.5
MinCameraDistanceBroadside=1.5
CameraPivotHeight=0.25

AutoFlatten=True
MaskVegetation=True
# Hull armor: None, Minor, Moderate, Heavy
ArmorType=Heavy
DamagePoints=140  //systems damage contribution substracted from this when systems destroyed, when becomes less than zero, the whole unit is considered being destroyed

[Tacview]
Name=US ICBM Base
Tag=Ground+Vehicle

[AI]
UnitScoreValue=100               // value for calculation of mission score
Role=Target

[ControlSystem]
Collider=coll_ent
Integrity=15

[SensorData]
#Visual
VisualIdentificationRange=15 // Camouflaged  (x0.5)
IRSignature=Small
# Radar related (RCS => radar cross section)
RCS=Large

[---------- Sensor Systems ----------]
[SensorSystems]
NumberOfSensorSystems=1
#---------- Visual ----------
[SensorSystem1] #Bridge
# Bridge. Does not need SystemGroup and Collider because we do not want ship to loose ability to VID targets
Type=Visual
SystemName=Optics
Mount=Dummy
#MountPosition=0,0.255,0
MountPosition=0,1,0 //Observer on top of the tower
ModuleType=Bridge
Collider=
Integrity=1


[ ---------- HitZones ---------- ]
[HitZones]
NumberOfHitZones=12
[HitZone1]
SystemName=Entrance
Collider=coll_ent
Integrity=5 //the number of hit points substracted from the overall damage points count when the system is destroyed
[HitZone2]
SystemName=Silo 1
Collider=coll_s1
Integrity=15 //the number of hit points substracted from the overall damage points count when the system is destroyed
[HitZone3]
SystemName=Silo 2
Collider=coll_s2
Integrity=15 //the number of hit points substracted from the overall damage points count when the system is destroyed
[HitZone4]
SystemName=Silo 3
Collider=coll_s3
Integrity=15 //the number of hit points substracted from the overall damage points count when the system is destroyed
[HitZone5]
SystemName=Silo 4
Collider=coll_s4
Integrity=15 //the number of hit points substracted from the overall damage points count when the system is destroyed
[HitZone6]
SystemName=Silo 5
Collider=coll_s5
Integrity=15 //the number of hit points substracted from the overall damage points count when the system is destroyed
[HitZone7]
SystemName=Silo 6
Collider=coll_s6
Integrity=15 //the number of hit points substracted from the overall damage points count when the system is destroyed
[HitZone8]
SystemName=Silo 7
Collider=coll_s7
Integrity=15 //the number of hit points substracted from the overall damage points count when the system is destroyed
[HitZone9]
SystemName=Silo 8
Collider=coll_s8
Integrity=15 //the number of hit points substracted from the overall damage points count when the system is destroyed
[HitZone10]
SystemName=Silo 9
Collider=coll_s9
Integrity=15 //the number of hit points substracted from the overall damage points count when the system is destroyed
[HitZone11]
SystemName=Silo 10
Collider=coll_s10
Integrity=15 //the number of hit points substracted from the overall damage points count when the system is destroyed
[HitZone12]
SystemName=Underground Complex
Collider=coll_ugc
Integrity=20 //the number of hit points substracted from the overall damage points count when the system is destroyed
[ ---------- Target Points definitions ---------- ]
[TargetingData]
NumberOfTargetPoints=13

TargetPointPosition1=-0.8,0,0
TargetPointAssociatedSystems1=HitZone1
TargetPointPriority1=Low

TargetPointPosition2=-.4,0,0.25
TargetPointAssociatedSystems1=HitZone2
TargetPointPriority1=High

TargetPointPosition3=-.1,0,0.25
TargetPointAssociatedSystems1=HitZone3
TargetPointPriority1=High

TargetPointPosition4=.17,0,0.25
TargetPointAssociatedSystems1=HitZone4
TargetPointPriority1=High

TargetPointPosition5=.5,0,0.25
TargetPointAssociatedSystems1=HitZone5
TargetPointPriority1=High

TargetPointPosition6=.8,0,0.25
TargetPointAssociatedSystems1=HitZone6
TargetPointPriority1=High

TargetPointPosition7=.8,0,-0.25
TargetPointAssociatedSystems1=HitZone7
TargetPointPriority1=High

TargetPointPosition8=.5,0,-0.25
TargetPointAssociatedSystems1=HitZone8
TargetPointPriority1=High

TargetPointPosition9=.17,0,-0.25
TargetPointAssociatedSystems1=HitZone9
TargetPointPriority1=High

TargetPointPosition10=-.1,0,-0.25
TargetPointAssociatedSystems1=HitZone10
TargetPointPriority1=High

TargetPointPosition11=-.4,0,-0.25
TargetPointAssociatedSystems1=HitZone11
TargetPointPriority1=High

TargetPointPosition12=-.4,0,-0.25
TargetPointAssociatedSystems1=HitZone12
TargetPointPriority1=High
[--------------------------- Mesh definitons ---------------------------]
[Models]
LODLevels=1
LOD1Distance=15  // nautical miles

############################################################
ResourcesFolder=Buildings/US_Missile_complex/
ResourcesRoot=US_Missile_complex.obj
ResourcesMesh=Silos
ResourcesMaterialFolder=Buildings/US_Missile_complex/
ResourcesMaterial=US_Missile_complex_mat.ini


[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=1
AmbientAudioClip=audio/ships/Ship-Turbine-Medium
AmbientAudioPosition=0,0,-0.35
AmbientAudioRollOff=Logarithmic
AmbientAudioDistance=0,0
AmbientAudioPitchRange=1.0,1.6
AmbientAudioVolume=0.0
AmbientAudioAudibility=Above  // layer of sound audibility: Above, Below, AboveAndBelow

[Particles]
SmallFireEffectClass=SmallShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=SmallShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=SmallShipFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffect=effects/explosions/emitters/missile_hit_ship
SecondaryExplosionEffectPosition=0,0,0

[---------- Colliders ----------]
[Colliders]
UseKinematicCollision=False
NumberOfColliders=1
NumberOfMeshColliders=11

MeshCollider1=coll_ent
MeshCollider2=coll_s1
MeshCollider3=coll_s2
MeshCollider4=coll_s3
MeshCollider5=coll_s4
MeshCollider6=coll_s5
MeshCollider7=coll_s6
MeshCollider8=coll_s7
MeshCollider9=coll_s8
MeshCollider10=coll_s9
MeshCollider11=coll_s10

Collider1=coll_ugc


[coll_ent]
Collider=coll_ent

[coll_s1]
Collider=coll_s1

[coll_s2]
Collider=coll_s2

[coll_s3]
Collider=coll_s3

[coll_s4]
Collider=coll_s4

[coll_s5]
Collider=coll_s5

[coll_s6]
Collider=coll_s6

[coll_s7]
Collider=coll_s7

[coll_s8]
Collider=coll_s8

[coll_s9]
Collider=coll_s9

[coll_s10]
Collider=coll_s10

[coll_ugc]
Collider=Box
Position=-.8,0,-0.25
Rotation=0,0,0
Scale=0.01,0.01,0.01

