[General]
Type=Chaff                             // can be Projectile, Missile, Torpedo
TargetType=AAW                         // can be AAW, ASuW, ASW

Mass=0.1                               // in kg. Used for aircraft
AmmoPoints=0.1                         // For Supply System. Defines "price" of ammunition based on mass, volume, complexity and availability

[ECM]
# Chaff -related parameters
SpoofChance=0.6                       // Base chance to spoof missile
DefensiveEffectTime=60              // Period of defensive effect being active in seconds
ReactionRange=7                    // in miles; Distance to missile at which chaff is auto-launched

[SensorData]
IRSignature=VeryLarge
# radar related (RCS => radar cross section)
RCS=VeryLarge