[AmmunitionNames]
# ------------------ AAM ------------------

# ---------- Anti-radar Missiles ---------
usn_agm-114k_LQS=AGM-114K,地狱火,反坦克,AGM-114地狱火导弹是一种多平台、多目标的美国制导弹。主要用于反战车，但后期型号也被用于无人机攻击，精确打击高价值目标等。
# ---------- Anti-ship Missiles ----------
#-----------Land Strike only missiles---------
usn_mk50_air_LQS=MK-50,ALWT,反潜鱼雷,MK-50反潜鱼雷是美国海军装备的新一代反潜鱼雷，主要装备水面舰艇、反潜飞机，用于攻击各种潜艇。该型为机载型。

usn_ssq-77c_LQS=AN/SSQ-77C,VLAD,声纳浮标,SSQ-77C是一款垂直线阵列DIFAR无源声纳浮标,旨在对原始DIFAR型无源声纳浮标进行世代改进。该浮标的结构与DIFAR浮标相似,但采用了一个极其灵敏的声纳阵列,使声纳浮标能够实现极长的被动距离,对安静的深潜目标具有很高的能力,并在杂乱,嘈杂的水域中表现出良好的性能。

usn_ssq-75_LQS=AN/SSQ-75A,ERAPS,主动声纳浮标,AN/SSQ-75 ERAPS（一次性可靠声学路径声纳浮标）是一种定向指令激活的远程主动声纳浮标。这种声纳浮标以其在公海对抗安静潜艇的高性能而闻名,可以实现卓越的性能,但不幸的是,其采购方式极其有限,因此很少有人能够幸免。

