[AmmunitionNames]
# ------------------ AAM ------------------
iaf_python3=Python 3,,AAM,Python 3 is Israel's infrared-guided air-to-air combat missile with a longer range than other combat missiles.
# ------------------ SAM ------------------

# ---------- Anti-radar Missiles ---------

# ---------- Anti-ship Missiles ----------

#-----------Land Strike only missiles---------

# ---------- Anti-sub  Missilies ----------

wp_aa-10a=AA-10A,Alamo,AAM,This missile is a new type of medium to long range air-to-air missile developed and equipped by the former Soviet Union and Russia for frontline tactical air force fighters. It belongs to the third and fourth generation air-to-air missiles.


wp_aa-11=AA-11,Archer,AAM,The R-73 air-to-air missile is a Soviet/Russian type of close range air-to-air combat missile, and was one of the world's best performing combat infrared guided air-to-air missiles in the 1990s.

# ------------------ RBU ------------------

# --------------- Torpedoes ---------------

# ------------------ Bombs -----------------

# ---------------- Sonobuoys ---------------

# ------------------ FFAR -----------------

# ------------------ MLRS -----------------

# ------------------ Guns -----------------

# ------------------ CIWS -----------------
# ----------- Noisemakers/Chaff -----------

# ----------------- Decoys ----------------

# ----------------- Special ----------------

# Depth charge

# ----------------- Fueltanks ----------------
usaf_tank_370_f-16=F-16 Fuel Tanks,,Fule Tank

wp_tank_1500_mig-29=1500L Fuel Tank,,Fule Tank
