[Animations]
NumberOfAnimations=8

Animation1=Gear_Extend
Animation2=Gear_Retract
Animation3=Flaps_Takeoff
Animation4=Flaps_Takeoff_Retract
Animation5=Flaps_Landing
Animation6=Flaps_Landing_Retract

[Gear_Extend]
NumberOfSequencesToPlay=5
Sequence1=Nose_Gear_Down1
Sequence1_Model=Nose_Gear_Up
Sequence2=Nose_Gear_Down2
Sequence2_Model=Nose_Gear

Sequence3=Left_Gear_Down
Sequence3_Model=LeftGear

Sequence4=Right_Gear_Down
Sequence4_Model=RightGear

[Gear_Retract]
NumberOfSequencesToPlay=5
Sequence1=Nose_Gear_Up1
Sequence1_Model=Nose_Gear_Up
Sequence2=Nose_Gear_Up2
Sequence2_Model=Nose_Gear

Sequence3=Left_Gear_Up
Sequence3_Model=LeftGear

Sequence4=Right_Gear_Up
Sequence4_Model=RightGear

[Flaps_Takeoff]
NumberOfSequencesToPlay=2
Sequence1=Flap_Takeoff
Sequence1_Model=Flap_Outer
Sequence2=Flap_Takeoff
Sequence2_Model=Flap_Inner

[Flaps_Takeoff_Retract]
NumberOfSequencesToPlay=2
Sequence1=Flap_Takeoff_Retract
Sequence1_Model=Flap_Outer
Sequence2=Flap_Takeoff_Retract
Sequence2_Model=Flap_Inner

[Flaps_Landing]
NumberOfSequencesToPlay=2
Sequence1=Flap_Landing
Sequence1_Model=Flap_Outer
Sequence2=Flap_Landing
Sequence2_Model=Flap_Inner

[Flaps_Landing_Retract]
NumberOfSequencesToPlay=2
Sequence1=Flap_Landing_Retract
Sequence1_Model=Flap_Outer
Sequence2=Flap_Landing_Retract
Sequence2_Model=Flap_Inner

#############################################################

[Nose_Gear_Down1]
NumberOfSteps=2
Step1=0|x,y,z|65,y,z|Linear
Step2=3|x,y,z|-0,y,z|Linear

[Nose_Gear_Down2]
NumberOfSteps=2
Step1=1|x,y,z|65,y,z|Linear
Step2=4|x,y,z|-0,y,z|Linear

[Left_Gear_Down]
NumberOfSteps=2
Step1=0|x,y,z|85,-45,0|Linear
Step2=4|x,y,z|0,0,0|Linear

[Right_Gear_Down]
NumberOfSteps=2
Step1=0|x,y,z|85,45,0|Linear
Step2=4|x,y,z|0,0,0|Linear

#############################################################

[Nose_Gear_Up1]
NumberOfSteps=2
Step1=0|x,y,z|0,y,z|Linear
Step2=3|x,y,z|65,y,z|Linear

[Nose_Gear_Up2]
NumberOfSteps=2
Step1=1|x,y,z|0,y,z|Linear
Step2=4|x,y,z|65,y,z|Linear

[Left_Gear_Up]
NumberOfSteps=2
Step1=0|x,y,z|0,0,0|Linear
Step2=4|x,y,z|85,-45,0|Linear

[Right_Gear_Up]
NumberOfSteps=2
Step1=0|x,y,z|0,0,0|Linear
Step2=4|x,y,z|85,45,0|Linear

[Flap_Takeoff]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=1
RotationX2=-10
Smoothness2=EaseInOut

[Flap_Takeoff_Retract]
NumberOfSteps=2
Time1=0 
RotationX1=-10	
Smoothness1=EaseInOut
Time2=1 
RotationX2=0
Smoothness2=EaseInOut

[Flap_Landing]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=2
RotationX2=-20
Smoothness2=EaseInOut

[Flap_Landing_Retract]
NumberOfSteps=2
Time1=0 
RotationX1=-20	
Smoothness1=EaseInOut
Time2=2 
RotationX2=0
Smoothness2=EaseInOut
