[General]
#GBU-31(V)4/B JDAM
Type=Bomb                               // can be Projectile, Missile, RBU, ASROC, Torpedo
TargetType=ASuW                         // can be AAW, ASuW, ASW
IsInterceptable=True                   // for bombs only, if False, bomb cannot be fired upon, default is false
LandAttackCapability=Installation      // can be  All, Installation, Mobile, ShoreTargetsOnly
CanNotAttackTypes=Vessel,Submarine     // Seeker ignores objects of this type while in default mode
Mass=946                                // in kg. Used for aircraft
AmmoPoints=1000			   
AirLaunched=True                       // For Encyclopedia. Displays launch altitudes

DefaultCameraDistance=0.6
MinCameraDistanceForeAft=0.29
MinCameraDistanceBroadside=0.29
CameraPivotHeight=0.0

DecalClass=Standard  // referenced in effects/decals.ini

[SensorData]
#Visual
VisualIdentificationRange=1  // at what range in nm this unit can be visually identified
IRSignature=VerySmall
# Radar related (RCS => radar cross section)
RCS=VerySmall
# Sonar related

[---------- Warhead Data ----------]
############################################################
# Warhead Data
############################################################
#Warhead Types:
#0 = High Explosive
#1 = Armor Piercing
#2 = HEAT
#3 = Illumination
#4 = Cluster
#5 = Runway Cratering
#6 = Fragmentation

# Fuze Types: 0 = Impact Fuze, 1 = Proximity Fuze
[WarheadData]
WarheadType=1
Power=62         //Reflect armor piercing characteristics
ImpactSize=Large            // Impact size, can be small, medium, large, verylarge
Penetration=Always       		// can be minor, moderate, heavy, always

[---------- Guidance ----------]
############################################################
# Guidance System
############################################################
# Guidance Types:
# 0 = None
# 1 = IR Homing
# 2 = Semi-Active Radar Homing
# 3 = Active Radar Homing
# 4 = Anti-Radiation Homing
# 5 = Laser-Homing
# 6 = TV-Homing
# 7 = Active Sonar Homing
# 8 = Passive Sonar Homing
# 9 = Wake Homing
[Guidance]
GuidanceType=1
MidCourseCorrection=0                  // 0 = None, 1 = Radio Command, 2 = Wire Guided
InitialFlightPhaseDuration=2.0         // time in seconds where the missile moves straight on without guiding
#======================================== Flight Profile ===========================================================
GravityFactor=8
TerminalApproachDist=1000              // in N. miles. At this distance seeker will be turned on.
SupportsBanking=True                   // if the missile will bank when turning
#========================================= Launch stats ============================================================
MaxTurnRate=5                          // Maximum turnrate in degrees per second
MinLaunchRange=1                       // Minimum launch range in nautical miles
MaxLaunchRange=15                      // Maximum launch range in nautical miles
MinLaunchAltitude=2000                  // Minimum launch altitude in feet.
MaxLaunchAltitude=65000                // Maximum launch altitude in feet.
LaunchReliability=98                   // The lower the value, the greater risk of misfire or accident (0...100)
VerticalWobblingStrength=8.0           // amplitude of wobbling
VerticalWobblingSpeed=3.0              // frequency of wobbling
#========================================     Seeker     ===========================================================
CircularErrorRadius=2               // Circular error radius in meters
#Homing
SeekerGain=0.0                         // Seeker gain in dB
SeekerFOV=45.0                         // Seeker field-of-view in degrees
SeekerActiveRange=10                 // Seeker active range in nautical miles. Relevant for Semi-Active Radar Homing, Active Radar Homing, Laser-Homing and Active Sonar Homing (2, 3, 5 and 7)
SeekerPassiveRange=10                // Seeker passive range in nautical miles. Relevant for IR Homing, Semi-Active Radar Homing, Anti-Radiation Homing, TV-Homing, Passive Sonar Homing and Passive Sonar Homing (1, 2, 4, 6, 8 and 9)
Zoom=3
TargetMemory=True
#ECCM
#AntiCountermeasuresBonus=0.4           // This value substracted from probability of spoofing by countermeasures (0...1)
#Search params for torpedoes
#SelfDestruct
SelfDestructAfterTargetGone=False

[---------- Mesh definitions----------]
[Models]
AttachmentPosition=0,0,-0.001
############################################################
# AssetBundle related
############################################################
AssetBundleMeshes=/AssetBundles/StandaloneWindows/weapons
AssetBundleMaterials=/AssetBundles/StandaloneWindows/weapons
AssetBundleMesh=usn_gbu-12
AssetBundleDamagedMesh=
AssetBundleMaterial=usn_gbu-12_mat
AssetBundleMeshHullCollider=usn_gbu-12_coll
############################################################
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=assets/models/ammunition/gbu-31/
ResourcesRoot=gbu-31.obj
ResourcesMesh=JDAM
ResourcesMaterialFolder=assets/models/ammunition/gbu-31/textures/
ResourcesMaterial=gbu-31_mat.ini
############################################################
NumberOfSubModels=0
[Particles]
# Effects are referenced in /effects/effects.ini when using an effects class
# e.g. either:
# BoosterEffect=effects/weapons/emitters/submarine_torpedo_launch
# or
# BoosterEffectClass=BoosterEffects  // this will be referenced in effects.ini

# possible values (optionally with suffix "Class")
# BoosterEffect, InFligheEffect, UnderwaterTrail, ParachuteEffect, TorpedoSurfaceSplash, HitWaterSplash
# DebrisTrail, DebrisSplash, SmallFireEffect, ModerateFireEffect, SevereFireEffect,
# HitAirExplosion, HitShipExplosion, HitObjectExplosion, HitGroundExplosion, HitDefaultExplosion

InFlightEffect=None
InFlightEffectPosition=0,0,-0.02
InFlightEffectStartTime=0

HitShipExplosionClass=LargeShipHitExplosion
#HitAirExplosionClass=SmallGroundHitExplosions
HitGroundExplosionClass=MediumGroundHitExplosions
HitDefaultExplosionClass=MediumGroundHitExplosions	//MediumMissileExplosions
HitWaterSplashClass=SmallWaterSplashes

ExplosionOverwaterSplash=effects/splashes/emitters/splash_bomb

[---------- Colliders ----------]
############################################################
# Colliders definition
############################################################
[Colliders]
# creates the hit boxes for this object
Collider=col_main

[col_main]
Collider=Box
Position=0,0,0
Rotation=0,0,0
Scale=0.005,0.005,0.04291637