#=========================================================================================================================================================
#                                                  REQUIRES STATS REVISION
#=========================================================================================================================================================
[General]
#
#
Type=Missile                           // can be Projectile, Missile, Torpedo
TargetType=AAW                         // can be AAW, ASuW, ASW
#SecondaryTargetType=ASuW
RequiresWarmUp=False  //False - removes need to reload launcher before first launch

Mass=650                             // in kg. Used for aircraft

DefaultCameraDistance=0.6
MinCameraDistanceForeAft=0.29
MinCameraDistanceBroadside=0.29
CameraPivotHeight=0.0

DecalClass=SAMImpacts  // referenced in effects/decals.ini

[SensorData]
#Visual
VisualIdentificationRange=4  // at what range in nm this unit can be visually identified
IRSignature=Small
# Radar related (RCS => radar cross section)
RCS=VerySmall
# Sonar related
# Transient
TransientRCS=Small                    // Transient visibility on the radar
TransientVisualIdentificationRange=5  // Transient can be visually detected at this distance in nmi
TransientBaseNoise=200                // In db

[---------- Warhead Data ----------]
############################################################
# Warhead Data
############################################################
#Warhead Types:
#0 = Blast Fragmentation
#1 = Armor Piercing
#2 = HEAT
#3 = Illumination
#4 = Cluster
#5 = Runway Cratering

# Fuze Types: 0 = Impact Fuze, 1 = Proximity Fuze
[WarheadData]
WarheadType=0
Power=34
ImpactSize=SemiSmall                    // Impact size, can be small, medium, large, verylarge
Penetration=Always                    // can be minor, moderate, heavy, always

FuzeProximityDistance=8.0              // for proximity fuze: distance to target in meter. Also indicates that Fuze Type = Proximity Fuze
KillProbability=0.86                     // Base chance to hit

InterceptSpeedPenaltyMultiplier=0.4
[---------- Guidance ----------]
############################################################
# Guidance System
############################################################
# Guidance Types:
# 0 = None
# 1 = IR Homing
# 2 = Semi-Active Radar Homing
# 3 = Active Radar Homing
# 4 = Anti-Radiation Homing
# 5 = Laser-Homing
# 6 = TV-Homing
# 7 = Active Sonar Homing
# 8 = Passive Sonar Homing
# 9 = Wake Homing
[Guidance]
GuidanceType=2
MidCourseCorrection=3                  // 0 = None, 1 = Radio Command, 2 = Wire Guided
InitialFlightPhaseDuration=0.6         // time in seconds where the missile moves straight on without guiding
#======================================== Flight Profile ===========================================================
#flight phase 1: loft-----------------------------------------------------------------------------------------------------------------
#1st stage of missile flight - high altitude
MaxLoftAngle=60.0                      // Climb angle for initial loft
MaxLoftAlt=8000.0                     // in feet. Maximum altitude for lofting
MaxLoftVelocity=2300.0                 // Maximum speed in knots for lofting
#flight phase 2: sea skimming---------------------------------------------------------------------------------------------------------
#2nd stage of missile flight - low altitude
#flight phase 3: final flight phase (e.g. terminal popup)------------------------------------------------------------------------------
#Pop-Up. Missile climbs to higher altitude before activating the seeker. Or in some cases going even lower
#flight phase 4: terminal approach------------------------------------------------------------------------------------------------------
#Last stage - missile activates seeker and locks on target
TerminalApproachDist=5              // in N. miles. Recommended to set this distance slightly less than the seeker range. For SAM better set it to max value, 1000 miles is enough
TerminalDiveDistance=4                 // in N. miles.
LocalTerminalOnly=True                 // if true connection with a guiding radar will be severed upon entering terminal approach 
IgnoreHeightDifferenceForTargetDist=True  // useful for hight loft alt missiles to ignore the height for distance calculation
#========================================= Launch stats ============================================================
ApplyKinematics=True                   // 如果我们使用完整的运动学规则。如果这是真的，我们将只使用运动学
MaxVelocity=2200                    // Stall at 400 knots   // Maximum speed in knots
#for acceleration, instead of calculating acceleration time based on the max velocity. MaxVelocity is still used, since missile stalls at 1/4 max velocity or 500 knots, whichever is less
AccelerationTime=14                  // 初始助推器燃烧的燃烧时间
Acceleration=9.5                    // 初始燃烧阶段的加速度Gs
SustainerAccelerationTime=10            // 持续燃烧时间。若无持续燃烧，则记为-1
SustainerAcceleration=2.6               // 持续燃烧加速。若无持续燃烧，则值为-1
#---- Total Δv ≈ 1052 ≈ 3.09Ma

TypicalLaunchVelocity=0 
TypicalFiringAlt=0                    //SAM的阻力计算应该从0高度开始
TypicalTargetVelocity=0 
TypicalTargetAlt=5                   //SAM的阻力计算应该从0高度开始，目标0高0,速（拦截斜距）
DragCoefficient=-1               // 阻力系数。0表示无阻力，1表示默认阻力，数值越大表示阻力越大。默认值为-1，此时我们会根据导弹的最大射程来计算阻力系数

MaxFlightTime=200               // 基于电池等因素，导弹完全失效前的运行时间作为硬限制。默认值：无限
TerminalLoft=True
TimeLimited=True
MaxTurnRate=40.0                       // Maximum turnrate in degrees per second
LaunchTurnRate=120                     // Missiles like S-300 rapidly orient themselves after launch. in degrees per second
MinLaunchRange=0.5                    // Minimum launch range in nautical miles
MaxLaunchRange=32.4                    // Maximum launch range in nautical miles
MinAttackAltitude=5                   // Minimum altitude of a target, in feet. Outside Min/Max altitude missile deviation is greatly increaced
MaxAttackAltitude=60000                // Maximum altitude of target, in feet
MaxAttackVelocity=2500				   // Maximum velocity of target, in knots. Above this velocity, hit chance is degraded proportional to the target velocity above this speed
LaunchReliability=98                   // The lower the value, the greater risk of misfire or accident (0...100)
#========================================     Seeker     ===========================================================
CircularErrorRadius=4.7              // Circular error radius in meters (fuse 30 with CEP 15.77 = 80%)
CircularErrorRadiusLarge=6.5         // Circular error vs 'Large' aircraft (fuse 30 with CEP 12.29 = 90%)
MinAltMalusFactor=0.8                  // Factor that multiplies the CEP value if target below min alt of AAW weapon
#Homing
SeekerGain=45.0                         // Seeker gain in dB
SeekerFOV=60.0                         // Seeker field-of-view in degrees
SeekerActiveRange=0.0                  // Seeker active range in nautical miles. Relevant for  Active Radar Homing, Laser-Homing and Active Sonar Homing (3, 5 and 7)
SeekerPassiveRange=6.0    //40???     // Seeker passive range in nautical miles. Relevant for IR Homing, Semi-Active Radar Homing, Anti-Radiation Homing, TV-Homing, Passive Sonar Homing and Passive Sonar Homing (1, 2, 4, 6, 8 and 9)
SecondaryPassiveRadarGuidanceType=HomeOnJam  //Used with Active or SemiActive radar seeker. Used to detect emitting targets and home on them prior getting active target lock. Supported values: Full for both radar and ECM emissions and HomeOnJam if can home on jammers only
#ECCM
AntiCountermeasuresBonus=0.450           // This value substracted from probability of spoofing by countermeasures (0...1)
AntiJammerBonus=0.35                   // This value substracted from probability of being jammed  (0...1)
#Search params for torpedoes

#SelfDestruct
SelfDestructAfterTargetGone=True      // in case the target is destroyed and therefor lost, shall the missile be destroyed too?
SelfDestructDelay=2.0                  // delay in seconds for self destruction

[---------- Mesh definitions----------]
############################################################
# Main Model with collider
############################################################
[Models]
############################################################
# AssetBundle related
############################################################
AssetBundleMeshes=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMaterials=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMesh=usn_rim-7
AssetBundleDamagedMesh=
AssetBundleMaterial=usn_rim-7_mat
AssetBundleMeshHullCollider=usn_rim-7_coll
############################################################
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=assets/models/ammunition/hq-16/
ResourcesRoot=hq-16.obj
ResourcesMesh=hq-16a
ResourcesMaterial=hq-16_mat.ini
############################################################

NumberOfSubModels=0
[---------- Effects ----------]
# Effects are referenced in /effects/effects.ini when using an effects class
# e.g. either:
# BoosterEffect=effects/weapons/emitters/submarine_torpedo_launch
# or
# BoosterEffectClass=BoosterEffects  // this will be referenced in effects.ini

# possible values (optionally with suffix "Class")
# BoosterEffect, InFligheEffect, UnderwaterTrail, ParachuteEffect, TorpedoSurfaceSplash, HitWaterSplash
# DebrisTrail, DebrisSplash, SmallFireEffect, ModerateFireEffect, SevereFireEffect,
# HitAirExplosion, HitShipExplosion, HitObjectExplosion, HitGroundExplosion, HitDefaultExplosion
[Particles]
BoosterEffect=effects/weapons/emitters/s-300_effect
BoosterEffectPosition=0,0,-0.02
InFlightEffectClass=DefaultMissileInflightEffect
InFlightEffectPosition=0,0,-0.02
InFlightEffectStartTime=4.0  // in seconds, after that the Inflight Effect will be played if available

HitShipExplosionClass=MediumShipHitExplosion
HitAirExplosionClass=MediumMissileExplosions
HitDefaultExplosionClass=MediumMissileExplosions
HitWaterSplashClass=SmallWaterSplashes


[---------- Colliders ----------]
############################################################
# Colliders definition
############################################################
[Colliders]
# creates the hit boxes for this object
Collider=col_main

[col_main]
Collider=Box
Position=0,0,0
Rotation=0,0,0
Scale=0.005,0.005,0.043