[General]
Type=Projectile            // can be Projectile, Missile, Torpedo
TargetType=ASuW             // can be AAW, ASuW, ASW
SecondaryTargetType=AAW
DecalClass=GunImpacts      // referenced in effects/decals.ini
CanNotAttackTypes=Missile 

[Physics]
MuzzleVelocity=970         // meter per second
MaxRange=2500              // in m
CircularErrorProbable=18  // radius in meters at max range for shells to impact

[---------- Warhead Data ----------]
[WarheadData]
Power=1.3
ImpactSize=Tiny            // Impact size, can be small, medium, large, verylarge
Penetration=Moderate          // can be minor, moderate, heavy, always

[---------- Effects ----------]
[Particles]
# Effects are referenced in /effects/effects.ini
TrailEffect=None
HitShipExplosion=effects/Particle Emitters/impact_small_shell_multi
HitAirExplosionClass=SmallFlakExplosions
HitDefaultExplosionClass=SmallFlakExplosions
HitWaterSplashClass=SmallWaterSplashes