#=========================================================================================================================================================
#                                                  REQUIRES STATS REVISION
#=========================================================================================================================================================
[General]
#星光
Type=Missile                           // can be Projectile, Missile, Torpedo
TargetType=ASuW                        // can be AAW, ASuW, ASW
SecondaryTargetType=AAW
LandAttackCapability=All               // can be  All, Installation, Mobile, ShoreTargetsOnly
CanNotAttackTypes=Missile     // Seeker ignores objects of this type while in default mode
Mass=45                                // in kg. Used for aircraft

AmmoPoints=45                        // For Supply System. Defines "price" of ammunition based on mass, volume, complexity and availability

DefaultCameraDistance=0.6
MinCameraDistanceForeAft=0.29
MinCameraDistanceBroadside=0.29
CameraPivotHeight=0.0

DecalClass=Standard  // referenced in effects/decals.ini

[SensorData]
#Visual
VisualIdentificationRange=2  // at what range in nm this unit can be visually identified
IRSignature=Tiny
# Radar related (RCS => radar cross section)
RCS=VerySmall
# Sonar related

[---------- Warhead Data ----------]
############################################################
# Warhead Data
############################################################
#Warhead Types:
#0 = Blast Fragmentation
#1 = Armor Piercing
#2 = HEAT
#3 = Illumination
#4 = Cluster
#5 = Runway Cratering

# Fuze Types:
# 0 = Impact Fuze
# 1 = Proximity Fuze
[WarheadData]
WarheadType=0
Power=9
ImpactSize=Small                      // Impact size, can be small, medium, large, verylarge
Penetration=Moderate	               // can be minor, moderate, heavy, always

FuzeProximityDistance=0.2  
KillProbability=0.8                     // Base chance to hit 
[---------- Guidance ----------]
############################################################
# Guidance System
############################################################
# Guidance Types:
# 0 = None
# 1 = IR Homing
# 2 = Semi-Active Radar Homing
# 3 = Active Radar Homing
# 4 = Anti-Radiation Homing
# 5 = Laser-Homing
# 6 = TV-Homing
# 7 = Active Sonar Homing
# 8 = Passive Sonar Homing
# 9 = Wake Homing
[Guidance]
GuidanceType=5
MidCourseCorrection=0                  // 0 = None, 1 = Radio Command, 2 = Wire Guided
InitialFlightPhaseDuration=0.7           // time in seconds where the missile moves straight on without guiding
DropDuration=0.0                       // time in seconds where the missile just falls unpropelled
#======================================== Flight Profile ===========================================================
#flight phase 1: loft-----------------------------------------------------------------------------------------------------------------
#flight phase 2: sea skimming---------------------------------------------------------------------------------------------------------
#2nd stage of missile flight - low altitude
#flight phase 3: final flight phase (e.g. terminal popup)------------------------------------------------------------------------------
#Pop-Up. Missile climbs to higher altitude before activating the seeker. Or in some cases going even lower
#flight phase 4: terminal approach------------------------------------------------------------------------------------------------------
#Last stage - missile activates seeker and locks on target
TerminalApproachDist=1000              // in N. miles. Recommended to set this distance slightly less than the seeker range
TerminalDiveDistance=1000                 // in N. miles.
AxialRotation=800                      // In degrees per second. Doesnt work when 
#========================================= Launch stats ============================================================
ApplyKinematics=True                   // 如果我们使用完整的运动学规则。如果这是真的，我们将只使用运动学
MaxVelocity=1600                       // Maximum speed in knots
#for acceleration, instead of calculating acceleration time based on the max velocity. MaxVelocity is still used, since missile stalls at 1/4 max velocity or 500 knots, whichever is less
AccelerationTime=0.05                // 初始助推器燃烧的燃烧时间
Acceleration=200                    // 初始燃烧阶段的加速度Gs
SustainerAccelerationTime=0.59           // 持续燃烧时间。若无持续燃烧，则记为-1
SustainerAcceleration=145.6             // 持续燃烧加速。若无持续燃烧，则值为-1
#---- Total Δv ≈ 926 ≈ 2.72Ma


DragCoefficient=7               

MaxFlightTime=12               // 基于电池等因素，导弹完全失效前的运行时间作为硬限制。默认值：无限

MaxTurnRate=15                         // Maximum turnrate in degrees per second
MinLaunchRange=0.6                    // Minimum launch range in nautical miles
MaxLaunchRange=3.78                     // Maximum launch range in nautical miles
MinLaunchAltitude=200                  // Minimum launch altitude in feet.
MaxLaunchAltitude=5000                 // Maximum launch altitude in feet.
LaunchReliability=95                   // The lower the value, the greater risk of misfire or accident (0...100)
#========================================     Seeker     ===========================================================
#Homing
SeekerGain=0.0                        // Seeker gain in dB
SeekerFOV=45.0                         // Seeker active range in nautical miles. Relevant for  Active Radar Homing, Laser-Homing and Active Sonar Homing (3, 5 and 7)
SeekerActiveRange=0.0
SeekerPassiveRange=10.0                // Seeker passive range in nautical miles. Relevant for IR Homing, Semi-Active Radar Homing, Anti-Radiation Homing, TV-Homing, Passive Sonar Homing and Passive Sonar Homing (1, 2, 4, 6, 8 and 9)
#ECCM
AntiCountermeasuresBonus=0.05          // This value substracted from probability of spoofing by countermeasures (0...1)
#Search params for torpedoes
#SelfDestruct
SelfDestructDelay=5.0                  // delay in seconds for self destruction
[---------- Mesh definitions----------]
############################################################
# Main Model with collider
############################################################
[Models]
############################################################
# AssetBundle related
############################################################
AssetBundleMeshes=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMaterials=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMesh=usa_bgm-71a
AssetBundleDamagedMesh=
AssetBundleMaterial=ships/materials/modular_parts
AssetBundleMeshHullCollider=usn_rim-7_coll
############################################################
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=assets/models/ammunition/starstreak/
ResourcesRoot=starstreak.obj
ResourcesMesh=starstreak
ResourcesMeshForLaunch=launch
ResourcesMeshSwitchTime=0.7  // time in seconds after launch to switch from launch mesh to main mesh
ResourcesMaterial=starstreak_mat.ini
############################################################

[---------- Effects ----------]
# Effects are referenced in /effects/effects.ini when using an effects class
# e.g. either:
# BoosterEffect=effects/weapons/emitters/submarine_torpedo_launch
# or
# BoosterEffectClass=BoosterEffects  // this will be referenced in effects.ini

# possible values (optionally with suffix "Class")
# BoosterEffect, InFligheEffect, UnderwaterTrail, ParachuteEffect, TorpedoSurfaceSplash, HitWaterSplash
# DebrisTrail, DebrisSplash, SmallFireEffect, ModerateFireEffect, SevereFireEffect,
# HitAirExplosion, HitShipExplosion, HitObjectExplosion, HitGroundExplosion, HitDefaultExplosion
[Particles]
BoosterEffect=effects/weapons/emitters/rbu_effect
BoosterEffectPosition=0,0,0
InFlightEffectClass=DefaultMissileInflightEffect
InFlightEffectPosition=0,0,0.0
InFlightEffectStartTime=2

HitShipExplosionClass=RocketShipHitExplosion
HitAirExplosionClass=RocketShipHitExplosion
HitDefaultExplosionClass=RocketShipHitExplosion
HitWaterSplashClass=SmallWaterSplashes

[---------- Colliders ----------]
############################################################
# Colliders definition
############################################################
[Colliders]
# creates the hit boxes for this object
Collider=col_main

[col_main]
Collider=Box
Position=0,0,0
Rotation=0,0,0
Scale=0.0015,0.0015,0.012
