[General]
UnitType=LandUnit
LandUnitSubType=Airbase //Supported values: Airbase,SAM,Installation,MobileUnit,Radar,Port
DisplayClassName=Akureyri Airbase
DefaultCameraDistance=18.0
MinCameraDistanceForeAft=18
MinCameraDistanceBroadside=18
CameraPivotHeight=0.15

# Hull armor: None, Minor, Moderate, Heavy
ArmorType=None
DamagePoints=400  //systems damage contribution substracted from this when systems destroyed, when becomes less than zero, the whole unit is considered being destroyed

[AI]
UnitScoreValue=10              // value for calculation of mission score
Role=Airfield

[SensorData]
#Visual
VisualIdentificationRange=15.0  // Biggest range in nm at which this unit can be visually identified
IRSignature=Large
# Radar related (RCS => radar cross section)
RCS=SemiSmall
# Sonar related
BaseNoise=150                   // base sound level in db at 1m distance
FlowNoise=1                     // additional flow noise per knot in db (20kn would be +20db)
CavitationNoise=5               // additional noise for cavitation in db

[Animations]
NumberOfAnimationReferences=1
AnimationFile_1=animations_wp_large_pvo_airbase

[---------- FlightDeck Definitions ----------]
[AirGroup]
# ---------------------- Aircraft ---------------------
# ************************ USA ************************
civ_707=Random,0
civ_dc-10=Random,0
#Fighters
usaf_f-15c=Squadron1,12
usa_a-10a=Squadron1,12
#Bombers
#Recon
usaf_e-3a=Default,2
usn_ra-5c=Default,6
#EW
usn_ea-6b=Default,4
#ASW
usn_p-3c=Squadron1,8
# -------------------- Helicopters --------------------]
usn_sh-2f=Default,0
usn_sh-3h=Default,0
usn_ch-46=Default,2

[FlightDeck]
AircraftCapacity=80
NumberOfElevators=4
NumberOfLaunchPoints=4
NumberOfRecoveryPoints=4
NumberOfTaxiPoints=3
NumberOfTaxiPaths=16

ForwardsTaxiVelocity=15
BackwardsTaxiVelocity=-10
SlowTaxiVelocity=6

LaunchDelay=1

HoldWaypoints=0.5,800,0|-0.75,800,1.25|-2,800,0|-0.75,800,-1.25
LargeHoldWaypoints=3,800,0|0,800,3|-3,800,0|0,800,-3
HoldStackSeparation=200 //In feet
HoldEnterDistance=5     //In nautical miles. At this range hold waypoints are generated and aircraft enters hold
LandingSpeeds=350,350,150   //Hold,Circuit,Approach in knots

LandingWhileLaunching=False
Collider=coll_runway,coll_hangars_1,coll_hangars_2,coll_hangar_big,coll_control_tower
Integrity=400

[Elevator1]  #Plane Pad 1
AssociatedLaunchPoints=1,2
BlocksElevators=3
BlocksLaunchPoints=3
SpawnPosition=1.5,0,7.3
SpawnRotation=270
RidePosition=1.2,0,7.3
SupportsLarge=False

[Elevator2]  #Plane Pad 2
AssociatedLaunchPoints=1,2
BlocksElevators=3
BlocksLaunchPoints=3
SpawnPosition=1.5,0,7.7
SpawnRotation=270
RidePosition=1.2,0,7.7
SupportsLarge=False

[Elevator3]  #Plane Pad  1+2: Large
AssociatedLaunchPoints=3
BlocksLaunchPoints=1,2
SpawnPosition=1.5,0,7.5
SpawnRotation=270
RidePosition=1.2,0,7.5
SupportsSmall=False

[Elevator4]  #Heli Pad 1
AssociatedLaunchPoints=4
SpawnPosition=0.06,0,3.47
SpawnRotation=90
RidePosition=0.25,0,3.47

[LaunchPoint1] #Airstrip right
AllowedType=Plane,VTOL
SupportsLarge=False
SupportsSmall=True
Position=-1.07,0,4.5
HoldPosition=-1.07,0,4.8
#Position=0.224,0,-24
Rotation=180
TakeOffTime=10

[LaunchPoint2] #Airstrip left
AllowedType=Plane,VTOL
SupportsLarge=False
SupportsSmall=True
Position=-1.44,0,4.8
HoldPosition=-1.44,0,5.1

Rotation=180
TakeOffTime=10

[LaunchPoint3] #Airstrip center
AllowedType=Plane,VTOL
SupportsLarge=True
SupportsSmall=False
Position=-1.26,0,4.6
HoldPosition=-1.26,0,4.9
Rotation=180
TakeOffTime=10

[LaunchPoint4] #Heli 1
AllowedType=Helicopter
Position=0.8,0,3.47
Rotation=90
TakeOffTime=10

[RecoveryPoint1] #Airstrip right
AllowedType=Plane,VTOL
AssociatedElevators=1,2
BlocksLaunchPoints=1,2,3
Position=-1.07,0,-10.27
ExitPosition=-1.07,0,4.8
Rotation=0                              // in degrees
CircuitWaypoints=-3,800,-2|-3,800,-4|-1.5,800,-5|0,800,-3
LargeCircuitWaypoints=-5,800,-4|-3,800,-8|0,800,-5|0,800,-4|0,800,-3
LandingInterval=20
SupportsLarge=False

[RecoveryPoint2] #Airstrip left
AllowedType=Plane,VTOL
AssociatedElevators=1,2
BlocksLaunchPoints=1,2,3
Position=-1.44,0,-9.97
ExitPosition=-1.44,0,5.1
Rotation=0                              // in degrees
CircuitWaypoints=-3,800,-2|-3,800,-4|-1.5,800,-5|0,800,-3
LargeCircuitWaypoints=-5,800,-4|-3,800,-8|0,800,-5|0,800,-4|0,800,-3
LandingInterval=20
SupportsLarge=False

[RecoveryPoint3] #Airstrip center
AllowedType=Plane,VTOL
AssociatedElevators=3
BlocksLaunchPoints=1,2
Position=-1.26,0,-10.17
ExitPosition=-1.26,0,4.9
Rotation=0                              // in degrees
CircuitWaypoints=-3,800,-2|-3,800,-4|-1.5,800,-5|0,800,-3
LargeCircuitWaypoints=-5,800,-4|-3,800,-8|0,800,-5|0,800,-4|0,800,-3
LandingInterval=20
SupportsSmall=False

[RecoveryPoint4] #Heli E8
AllowedType=Helicopter

AssociatedElevators=4
Position=0.8,0,3.47
Rotation=90

CircuitWaypoints=0,200,-0.4
LandingInterval=80

[TaxiPoint1] #Planes Takeoff Path Start
Position=0.49,0,5.54

[TaxiPoint2] #Planes Takeoff Path End
Position=-0.954,0,5.312

[TaxiPoint3] #Planes Recover Path End
Position=0.49,0,5.54

[ ==================== Aircraft Taxi ==================== ]
[ -------------------- Takeoff  -------------------- ]
[ ---------- Taxi to queue  ---------- ]
[TaxiPath1] #E1->TaxiPoint1
From=Elevator1
To=TaxiPoint1
Waypoints=0.674,0,7.3|0.49,0,7.086

[TaxiPath2] #E2->TaxiPoint1
From=Elevator2
To=TaxiPoint1
Waypoints=0.674,0,7.7|0.49,0,7.486

[TaxiPath3] #E3->TaxiPoint1
From=Elevator3
To=TaxiPoint1
Waypoints=0.834,0,7.5|0.594,0,7.146|0.49,0,6.7

[ ---------- Queue to launch points ---------- ]

[TaxiPath4] #TaxiPoint1->TaxiPoint2
From=TaxiPoint1
To=TaxiPoint2
Waypoints=0.099,0,5.312

[TaxiPath5] #TaxiPoint2->LaunchPoint1
From=TaxiPoint2
To=LaunchPoint1
Waypoints=-1.07,0,5.2

[TaxiPath6] #TaxiPoint2->LaunchPoint2
From=TaxiPoint2
To=LaunchPoint2
Waypoints=-1.44,0,5.2

[TaxiPath7] #TaxiPoint2->LaunchPoint3
From=TaxiPoint2
To=LaunchPoint3
Waypoints=-1.26,0,5.1

[ -------------------- Recover  -------------------- ]
[TaxiPath8] #RecoveryPoint1->TaxiPoint2
From=RecoveryPoint1
To=TaxiPoint2
Waypoints=-1.07,0,5.2

[TaxiPath9] #RecoveryPoint2->TaxiPoint2
From=RecoveryPoint2
To=TaxiPoint2
Waypoints=-1.44,0,5.2

[TaxiPath10] #RecoveryPoint3->TaxiPoint2
From=RecoveryPoint3
To=TaxiPoint2
Waypoints=-1.26,0,5.1

[TaxiPath11] #TaxiPoint2->TaxiPoint3
From=TaxiPoint2
To=TaxiPoint3
Waypoints=0.099,0,5.312

[ ---------- Taxi to elevators  ---------- ]
[TaxiPath12] #TaxiPoint3->E1
From=TaxiPoint3
To=Elevator1
Waypoints=0.49,0,7.086|0.949,0,7.3

[TaxiPath13] #TaxiPoint3->E2
From=TaxiPoint3
To=Elevator2
Waypoints=0.49,0,7.486|0.949,0,7.7

[TaxiPath14] #TaxiPoint3->E3
From=TaxiPoint3
To=Elevator3
Waypoints=0.49,0,6.7|0.594,0,7.146|0.834,0,7.5

[ ==================== Helicopter Taxi ==================== ]
[ ---------- Takeoff  ---------- ]
[TaxiPath15] #E4->LaunchPoint4
From=Elevator4
To=LaunchPoint4

[ ---------- Recover  ---------- ]
[TaxiPath16] #RecoveryPoint4->E4
From=RecoveryPoint4
To=Elevator4

[---------- Sensor Systems ----------]
[SensorSystems]
NumberOfSensorSystems=1
#---------- Visual ----------
[SensorSystem1] #Bridge
# Bridge. Does not need SystemGroup and Collider because we do not want ship to loose ability to VID targets
Type=Visual
SystemName=Optics
Mount=Dummy
MountPosition=0.81,0.175,2.6
ModuleType=Bridge
[---------- HitZones ----------]
[HitZones]
NumberOfHitZones=7
[HitZone1]
Name=Runway
Collider=coll_runway
Integrity=250 //the number of hit points substracted from the overall damage points count when the system is destroyed

[HitZone2]
#Hungars 1
Collider=coll_hangars_1
Integrity=100 //the number of hit points substracted from the overall damage points count when the system is destroyed

[HitZone3]
#Hungars 2
Collider=coll_hangars_2
Integrity=100 //the number of hit points substracted from the overall damage points count when the system is destroyed

[HitZone4]
#Big hangar
Collider=coll_hangar_big
Integrity=120 //the number of hit points substracted from the overall damage points count when the system is destroyed

[HitZone5]
#Control Tower
Collider=coll_control_tower
Integrity=50 //the number of hit points substracted from the overall damage points count when the system is destroyed

[HitZone6]
#Area 1
Collider=coll_area_1
Integrity=40 //the number of hit points substracted from the overall damage points count when the system is destroyed

[HitZone7]
#Area 2
Collider=coll_area_2
Integrity=40 //the number of hit points substracted from the overall damage points count when the system is destroyed

[--------------------------- Target Points definitions ---------------------------]
[TargetingData]
NumberOfTargetPoints=8
#Runway 1
TargetPointPosition1=-1.265,0,-7
TargetPointAssociatedSystems1=HitZone1
TargetPointPriority1=High
#Runway 2
TargetPointPosition2=-1.265,0,8
TargetPointAssociatedSystems2=HitZone1
TargetPointPriority2=Medium
#Hungars 1
TargetPointPosition3=1.657,0,4.36
TargetPointAssociatedSystems3=HitZone2
TargetPointPriority3=High
#Hungars 2
TargetPointPosition4=0.943,0,5.332
TargetPointAssociatedSystems4=HitZone3
TargetPointPriority4=High
#Big hangar
TargetPointPosition5=1.472,0,6.647
TargetPointAssociatedSystems5=HitZone4
TargetPointPriority5=High
#Control Tower
TargetPointPosition6=0.987,0,2.63
TargetPointAssociatedSystems6=HitZone5
TargetPointPriority6=Low
#Area 1
TargetPointPosition7=-0.051,0,3.459
TargetPointAssociatedSystems7=HitZone6
TargetPointPriority7=Low
#Area 2
TargetPointPosition8=2.073,0,3.057
TargetPointAssociatedSystems8=HitZone7
TargetPointPriority8=Low

[--------------------------- Mesh definitions ---------------------------]
[Models]
############################################################
# Internal Resources folder related
############################################################

ResourcesFolder=scenery/is_airbase_akureyri/
ResourcesRoot=is_airbase_akureyri
ResourcesMesh=is_akureyri_decal
ResourcesMaterialFolder=scenery/is_airbase_reykjavik/
ResourcesMaterial=is_airbase_reykjavik_decal_mat

[Submodels]
SubModel1=Runway
SubModel2=Concrete
SubModel3=Tower
SubModel4=Hangar_1
SubModel5=Hangar_2
SubModel6=Buildings
SubModel7=Cargo
SubModel8=Containers
SubModel9=Trucks

############################################################
# Airbase model parts
############################################################

[Runway]
Mesh=is_akureyri_runway
DamagedMesh=is_akureyri_runway
ResourcesMaterialFolder=scenery/materials/
Material=runway
Position=0,0.001,0

[Concrete]
Mesh=is_akureyri_concrete
DamagedMesh=is_akureyri_concrete
ResourcesMaterialFolder=scenery/materials/
Material=concrete_bm
Position=0,0.001,0

[Tower]
Mesh=is_akureyri_tower
DamagedMesh=is_akureyri_tower
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1
Position=0,0,0

[Hangar_1]
Mesh=is_akureyri_hangar_1
DamagedMesh=is_akureyri_hangar_1
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1
Position=0,0,0

[Hangar_2]
Mesh=is_akureyri_hangar_2
DamagedMesh=is_akureyri_hangar_2
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1
Position=0,0,0

[Buildings]
Mesh=is_akureyri_buildings
DamagedMesh=is_akureyri_buildings
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1
Position=0,0,0

[Cargo]
Mesh=is_akureyri_cargo
DamagedMesh=is_akureyri_cargo
ResourcesMaterialFolder=scenery/materials/
Material=industrial_buildings_ne_us_1
Position=0,0,0

[Containers]
Mesh=is_akureyri_containers
DamagedMesh=is_akureyri_containers
ResourcesMaterialFolder=ships/materials/
Material=ms_containers_military
Position=0,0,0

[Trucks]
Mesh=is_akureyri_trucks
DamagedMesh=is_akureyri_trucks
ResourcesMaterialFolder=ships/materials/
Material=ms_cargoatlas
Position=0,0,0

[---------- Effects ----------]
[Particles]
SmallFireEffectClass=SmallShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=ModerateShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=SevereShipFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffect=effects/explosions/emitters/missile_hit_ship
SecondaryExplosionEffectPosition=0,0,0
[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=1

[---------- Colliders ----------]
[Colliders]
UseKinematicCollision=False
NumberOfColliders=11
NumberOfMeshColliders=0

Collider1=coll_runway
Collider2=coll_hangars_1
Collider3=coll_hangars_2
Collider4=coll_hangar_big
Collider5=coll_control_tower
Collider6=coll_area_1
Collider7=coll_area_2
Collider8=coll_selectionbox_1
Collider9=coll_selectionbox_2
Collider10=coll_selectionbox_3

Collider11=coll_raycast_hitbox
[coll_runway]
Collider=Box
Position=-1.26,0,0.25
Rotation=0,90,0
Scale=31.5,0.01,0.8

[coll_hangars_1]
Collider=Box
Position=1.657,0.051,4.36
Rotation=0,0,0
Scale=0.75,0.1,0.91

[coll_hangars_2]
Collider=Box
Position=0.943,0.043,5.332
Rotation=0,0,0
Scale=0.3,0.1,1.9

[coll_hangar_big]
Collider=Box
Position=1.472,0.129,6.647
Rotation=0,0,0
Scale=0.75,0.3,0.91

[coll_control_tower]
Collider=Box
Position=0.987,0.058,2.63
Rotation=0,0,0
Scale=0.5,0.12,0.75

[coll_area_1]
Collider=Box
Position=-0.051,0.022,3.459
Rotation=0,0,0
Scale=0.8,0.05,0.6

[coll_area_2]
Collider=Box
Position=2.073,0.018,3.057
Rotation=0,0,0
Scale=0.8,0.05,0.6

[coll_selectionbox_1]
Collider=Box
Position=1.33,0.01,4.91
Rotation=0,0,0
Scale=2,0.02,6

[coll_selectionbox_2]
Collider=Box
Position=-0.269,0.01,2.542
Rotation=0,0,0
Scale=1.2,0.02,1

[coll_selectionbox_3]
Collider=Box
Position=-0.269,0.01,5.3
Rotation=0,0,0
Scale=1.2,0.02,0.3
[coll_raycast_hitbox]
Collider=Box
Position=0,0,0
Rotation=0,0,0
Scale=1,0.02,1
