#!extend aircraft/usmc_av-8a.ini

[Performance]
EmptyMass=5490.0                      // in kg
MaxFuel=2340.0                        // in kg
; StallSpeed=35.0                      //in knots

[WeaponSystems]
NumberOfWeaponSystems=2

[WeaponSystem1]
NumberOfStations=6
Station6=0,0,0						//Gunpod

[WeaponSystem2] #Gun
Type=Chaff
SystemName=US_AIR_CHAFF_DISP
#Sensors
#Animations
#Mount
Mount=Dummy
MountPosition=0,-0.007,-0.025
#Containers
ContainerBase=Dummy
#Angles
#Loading
AssociatedMagazine=WeaponMagazineChaff
#Effects
NumberOfEffects=2
DelayBetweenLaunches=0.1
#Other
WorksStandalone=True
ModuleType=Weapon

[WeaponSystem1Default]
Station6=usmc_aden-pod

[WeaponSystem1AirToAir]
Station6=usmc_aden-pod

[WeaponSystem1AntiShip]
Station6=usmc_aden-pod

[WeaponSystem1Strike]
Station6=usmc_aden-pod

[WeaponSystem1SEAD]
Station6=usmc_aden-pod

[WeaponSystem1SEADAdvanced]
Station6=usmc_aden-pod

[WeaponSystem1CAS]
Station6=usmc_aden-pod

[Submodels]
SubModel25=None
