#!extend aircraft/usn_f-14a.ini

[SensorSystems]
NumberOfSensorSystems=5

[SensorSystem4] #RWR
Type=ESM
SystemName=AircraftRWR
Mount=Dummy
ModuleType=Sensor

[SensorSystem5] #Defensive ECM
Type=ECM
SystemName=AircraftDECM_Med
Mount=Dummy
ModuleType=Sensor

[WeaponSystem2] #Hardpoint
AssociatedSensors=SensorSystem3