#!extend aircraft/wp_mig-27.ini

[SensorSystems]
NumberOfSensorSystems=4

#---------- Visual ----------
[SensorSystem4] #Laser Designator
Type=LaserDesignator
SystemName=Kaira-23L
Mount=Dummy
ModuleType=Sensor