#=========================================================================================================================================================
#                                                  REQUIRES STATS REVISION
#=========================================================================================================================================================
[General]
# Roketsan SOM-J
Type=Missile                           // can be Projectile, Missile, RBU, Torpedo
TargetType=ASuW                        // can be AAW, ASuW, ASW
LandAttackCapability=All               // can be  All, Installation, Mobile, ShoreTargetsOnly


Mass=1300                               // in kg. Used for aircraft
AmmoPoints=5500                         // For Supply System. Defines "price" of ammunition based on mass, volume, complexity and availability
AirLaunched=True                       // For Encyclopedia. Displays launch altitudes

DefaultCameraDistance=0.6
MinCameraDistanceForeAft=0.29
MinCameraDistanceBroadside=0.29
CameraPivotHeight=0.0

DecalClass=Standard  // referenced in effects/decals.ini

[SensorData]
#Visual
VisualIdentificationRange=2.5  // at what range in nm this unit can be visually identified
IRSignature=Tiny
# Radar related (RCS => radar cross section)
RCS=VeryTiny
# Sonar related
TransientRCS=VeryTiny                    // Transient visibility on the radar
TransientVisualIdentificationRange=2  // Transient can be visually detected at this distance in nmi
TransientBaseNoise=0.5

[---------- Warhead Data ----------]
#Warhead Types:
#0 = Blast Fragmentation
#1 = Armor Piercing
#2 = HEAT
#3 = Illumination
#4 = Cluster
#5 = Runway Cratering

[WarheadData]
WarheadType=0
Power=70
ImpactSize=VeryLarge                       // Impact size, can be small, medium, large, verylarge
Penetration=Always                      // can be minor, moderate, heavy, always
#BombletsEjectAltitude=300      // in feet. MUST be lower than MinLaunchAltitude

[---------- Guidance ----------]
#Guidance Types:
#0 = None
#1 = IR Homing
#2 = Semi-Active Radar Homing
#3 = Active Radar Homing
#4 = Anti-Radiation Homing
#5 = Laser-Homing
#6 = TV-Homing
#7 = Active Sonar Homing
#8 = Passive Sonar Homing
#9 = Wake Homing
[Guidance]
GuidanceType=1
MidCourseCorrection=0                  // 0 = None, 1 = Radio Command, 2 = Wire Guided
DropDuration=4                       // time in seconds where the missile just falls unpropelled
InitialFlightPhaseDuration=5.0         // time in seconds where the missile moves straight on without guiding
TerrainFollowFlight=True
#======================================== Flight Profile ===========================================================
MaxLoftAngle=50.0                      // Climb angle for initial loft
MaxLoftAlt=300                          // in feet. Maximum altitude for lofting
TerminalApproachDist=8.0
TerminalAlt=400
TerminalDiveDistance=4                // in N. miles.  
TerminalPopup=False
MaxVelocity=520                       // Maximum speed in knots
Acceleration=4.0 
MaxTurnRate=25.0                       // Maximum turnrate in degrees per second
MinLaunchRange=10.0                     // Minimum launch range in nautical miles
MaxLaunchRange=250                    // Maximum launch range in nautical miles
MinLaunchAltitude=1000                  // Minimum launch altitude in feet.
MaxLaunchAltitude=40000                // Maximum launch altitude in feet.
LaunchReliability=99                   // The lower the value, the greater risk of misfire or accident (0...100)


#========================================     Seeker     ===========================================================
#Homing
SeekerGain=0                         // Seeker gain in dB
SeekerFOV=12                         // Seeker field-of-view in degrees
SeekerGimbalFOV=60                     // Seeker gimbal FOV in degrees
SeekerActiveRange=0.0
SeekerPassiveRange=15.0                // Seeker passive range in nautical miles. Relevant for IR Homing, Semi-Active Radar Homing, Anti-Radiation Homing, TV-Homing, Passive Sonar Homing and Passive Sonar Homing (1, 2, 4, 6, 8 and 9)
TargetMemory=True                      // Always locks on preselected target unless spoofed or jammed
NightVisionLevel=1.0
Zoom=2
#ECCM
AntiCountermeasuresBonus=0.7           // This value substracted from probability of spoofing by countermeasures (0...1)
AntiJammerBonus=0.6                    // This value substracted from probability of being jammed  (0...1)
#Search params for torpedoes
#SelfDestruct 
SelfDestructAfterTargetGone=False
SelfDestructDelay=5.0                  // delay in seconds for self destruction


[---------- Mesh definitions----------]
[Models]
ResourcesFolder=assets/models/weapon/ammunition/SCALP-EG/
ResourcesRoot=SCALP-EG.obj
ResourcesMesh=missile
ResourcesMeshForLaunch=launch

ResourcesMaterialFolder=assets/models/weapon/ammunition/SCALP-EG/textures/
ResourcesMaterial=SCALP-EG_mat.ini
ResourcesMeshSwitchTime=3  // time in seconds after launch to switch from launch mesh to main mesh
############################################################
Rotation=0,0,0

NumberOfSubModels=0
[---------- Effects ----------]
# Effects are referenced in /effects/effects.ini when using an effects class
# e.g. either:
# BoosterEffect=effects/weapons/emitters/submarine_torpedo_launch
# or
# BoosterEffectClass=BoosterEffects  // this will be referenced in effects.ini

# possible values (optionally with suffix "Class")
# BoosterEffect, InFligheEffect, UnderwaterTrail, ParachuteEffect, TorpedoSurfaceSplash, HitWaterSplash
# DebrisTrail, DebrisSplash, SmallFireEffect, ModerateFireEffect, SevereFireEffect,
# HitAirExplosion, HitShipExplosion, HitObjectExplosion, HitGroundExplosion, HitDefaultExplosion

[Particles]
BoosterEffect=None
BoosterEffectPosition=0,-0.00148,-0.032858

InFlightEffect=effects/weapons/emitters/turbojet_sustainer_small
InFlightEffectPosition=0,-0.00148,-0.032858
InFlightEffectStartTime=2.0  // in seconds, after that the Inflight Effect will be played if available

HitDefaultExplosionClass=LargeGroundHitExplosions
HitShipExplosionClass=MediumShipHitExplosion
HitAirExplosionClass=MediumMissileExplosions

HitWaterSplashClass=LargeWaterSplashes
HitGroundExplosionClass=LargeGroundHitExplosions

[---------- Colliders ----------]
[Colliders]
#creates the hit box for this object
Collider=col_main

[col_main]
Collider=Box
Position=0,0,-0.005587
Rotation=0,0,0
Scale=0.0042,0.03,0.04