[General]
Type=Container                       // can be Projectile, Missile, RBU, ASROC, Torpedo,AerialRocket,MLRS
Mass=208                                   // in kg. Used for aircraft. Container mass. Weapon mass is read from weapon ini


[---------- Sensor Systems ----------]
[SensorSystems]
NumberOfSensorSystems=2

[SensorSystem1]
Type=LaserDesignator
SystemName=AN/AAQ-28
Mount=Dummy
ModuleType=Sensor

[SensorSystem2]
Type=Visual
SystemName=Litening
Mount=Dummy
ModuleType=Sensor

[---------- Mesh definitions----------]
############################################################
# Main Model with collider
############################################################
[Models]
############################################################
# AssetBundle related
############################################################
############################################################
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=assets/models/weapon/ammunition/aaq-28/
ResourcesRoot=aaq-28.obj
ResourcesMesh=pod
ResourcesMaterial=aaq-28_mat.ini
############################################################
[Submodels]

SubModel1=Glas
SubModel2=Glas_Gold

[Glas]
Mesh=Glas
ResourcesMaterialFolder=aircraft/materials/
Material=cockpit_glass

[Glas_Gold]
Mesh=Glas_Gold
ResourcesMaterialFolder=aircraft/materials/
Material=cockpit_glass_gold


