[ ------------------------ Visual/Infared ------------------------- ]

[OLS-M]
Kind=Visual
#Infrared
VIDRangeMultiplier=1          // Target VID range multiplied by this for identification check. 0 means it cannot identify
MaxRangeMultiplier=1.3           // Target VID range multiplied by this for detection check. Can not be less then VID multiplier
LookDownMultiplier=0.7             // Final VID/Detection range is multiplied by this in case when target observed on surface background
NightVisionLevel=1             // the portion of full daylight added to the visibility level where 1 is roughly a mid-day


[------------------------- Radar ---------------------------]

[---Air/Air&Surface---]

[KLJ-7A]
#Users: plaaf j10c
Kind=Radar
Type=DirectedSearch    // 雷达类型
HasDataLink=False      // 数据链
Role=Air             // Role can be "Surface", "Air", "AirAndSurface"
Mode=Illuminate        // Can be "Illuminate", "RadioCommand"
TargetChannels=15      // 如果适用，它可以同时跟踪的目标数量
WeaponChannels=6       // 火力通道，如果武器（导弹）数量合适，它可以同时制导
ViewArcs=-60,60|-15,60     // 左：水平左右视场，右：垂直视场
LookDownMultiplier=0.6     // 多径地形杂波系数，当目标投影到地形/海洋背景上时，应用于最大雷达距离的乘数，默认值为1.0
MinRange=0.5           // 最小距离
MaxRange=150          // 最大距离
MinAltitude=70          // 最低海拔高度，不适用于对地
MaxAltitude=60000      // 最大高度
RangeResolution=25.5   // 识别间距，定义了后方两个目标可以被识别为两个的最小范围；单位为米
BeamWidth=1          // 定义承载分辨率>=2*Dist*sin（波束宽度/2）的波束宽度（度）
Gain=51.0              // 传感器上的增益（dB）
Frequency=X-Band       // 波段
PeakPower=100.0         // 功率 in kW
RequiresAlignment=True// 对于飞机。允许飞机制导武器的同时不飞向目标

[---------------------------------------- ESM ----------------------------------------]



