[AmmunitionNames]
# ------------------ AAM ------------------

usn_aim-9m_10=AIM-9M,Sidewinder,AAM,Low range for A-10

# ------------------ SAM ------------------

# ---------- Anti-radar Missiles ---------

# ---------- Anti-ship Missiles ----------

#-----------Land Strike only missiles---------

# ---------- Anti-sub  Missilies ----------

usn_agm-65d=AGM-65D,Maverick,AGM,AGM-65D is an infrared guided defense zone weapon from the United States that can lock onto targets in harsh environments. Its usage is similar to AGM-62, where the operator of the launch platform aligns the crosshair with the desired target for guidance.

# ------------------ RBU ------------------

# --------------- Torpedoes ---------------

# ------------------ Bombs -----------------
usn_gbu-31_10=GBU-31,JDAM,JDAM,Low range for A-10

usn_gbu-38_10=GBU-38,JDAM,JDAM,Low range for A-10

usn_gbu-39_10=GBU-39,SDB,SDB,Low range for A-10

# ---------------- Sonobuoys ---------------

# ------------------ FFAR -----------------

usa_apkws_2_m282=M282,APKWS Ⅱ,GFFAR,The AGR-20 Advanced Precision Kill Weapon System (APKWS) is a design conversion of Hydra 70 unguided rockets with a laser guidance kit to turn them into precision-guided munitions (PGMs).[7] APKWS is approximately one-third the cost and one-third the weight of the current inventory of laser-guided weapons, has a lower yield more suitable for avoiding collateral damage, and takes one quarter of the time for ordnance personnel to load and unload.

# ------------------ MLRS -----------------

# ------------------ Guns -----------------

# ------------------ CIWS -----------------
usn_cal_pgu-14b=PGU-14/B,AP,,The armor piercing ammunition chain used by GAU-8
# ----------- Noisemakers/Chaff -----------

# ----------------- Decoys ----------------

# ----------------- Special ----------------

# Depth charge

# ----------------- Fueltanks ----------------


