[Animations]
NumberOfAnimations=12

Animation1=Canopy_Extend
Animation2=Canopy_Retract
Animation3=Flaps_Takeoff
Animation4=Flaps_Takeoff_Retract
Animation5=Flaps_Landing
Animation6=Flaps_Landing_Retract
Animation7=Gear_Extend
Animation8=Gear_Retract
Animation9=Nozzles_STOL
Animation10=Nozzles_STOL_Retract
Animation11=Nozzles_VTOL
Animation12=Nozzles_VTOL_Retract

[Canopy_Extend]
NumberOfSequencesToPlay=1
Sequence1=Canopy_Open
Sequence1_Model=Canopy

[Canopy_Retract]
NumberOfSequencesToPlay=1
Sequence1=Canopy_Close
Sequence1_Model=Canopy

[Flaps_Takeoff]
NumberOfSequencesToPlay=2
Sequence1=Flap_Takeoff
Sequence1_Model=FlapLeft
Sequence2=Flap_Takeoff
Sequence2_Model=FlapRight

[Flaps_Takeoff_Retract]
NumberOfSequencesToPlay=2
Sequence1=Flap_Takeoff_Retract
Sequence1_Model=FlapLeft
Sequence2=Flap_Takeoff_Retract
Sequence2_Model=FlapRight

[Flaps_Landing]
NumberOfSequencesToPlay=2
Sequence1=Flap_Landing
Sequence1_Model=FlapLeft
Sequence2=Flap_Landing
Sequence2_Model=FlapRight

[Flaps_Landing_Retract]
NumberOfSequencesToPlay=2
Sequence1=Flap_Landing_Retract
Sequence1_Model=FlapLeft
Sequence2=Flap_Landing_Retract
Sequence2_Model=FlapRight

[Gear_Extend]
NumberOfSequencesToPlay=17
Sequence1=Nose_Gear_Down
Sequence1_Model=Gear_Nose
Sequence2=Nose_Gear_Down2
Sequence2_Model=GearFront
Sequence3=Nose_Gear_Door_Down1
Sequence3_Model=GearFrontDoor1
Sequence4=Nose_Gear_Door_Down2
Sequence4_Model=GearFrontDoor2
Sequence5=Nose_Gear_Door_Down3
Sequence5_Model=GearFrontDoor3
Sequence6=Gear_Down_L
Sequence6_Model=gear_l
Sequence7=Gear_Door_Down_L1
Sequence7_Model=gear_l_door1
Sequence8=Gear_Door_Down_L2
Sequence8_Model=gear_l_door2
Sequence9=Gear_Door_Down_L3
Sequence9_Model=gear_l_door3
Sequence10=Gear_Down_R
Sequence10_Model=gear_r
Sequence11=Gear_Door_Down_R1
Sequence11_Model=gear_r_door1
Sequence12=Gear_Door_Down_R2
Sequence12_Model=gear_r_door2
Sequence13=Gear_Door_Down_R3
Sequence13_Model=gear_r_door3
Sequence14=Gear_Down_Rear
Sequence14_Model=GearRear
Sequence15=Gear_Door_Down_Rear1
Sequence15_Model=WheelRearDoor1
Sequence16=Gear_Door_Down_Rear2
Sequence16_Model=WheelRearDoor2
Sequence17=Gear_Door_Down_Rear3
Sequence17_Model=WheelRearDoor3

[Gear_Retract]
NumberOfSequencesToPlay=17
Sequence1=Nose_Gear_Up
Sequence1_Model=Gear_Nose
Sequence2=Nose_Gear_Up2
Sequence2_Model=GearFront
Sequence3=Nose_Gear_Door_Up1
Sequence3_Model=GearFrontDoor1
Sequence4=Nose_Gear_Door_Up2
Sequence4_Model=GearFrontDoor2
Sequence5=Nose_Gear_Door_Up3
Sequence5_Model=GearFrontDoor3
Sequence6=Gear_Up_L
Sequence6_Model=gear_l
Sequence7=Gear_Door_Up_L1
Sequence7_Model=gear_l_door1
Sequence8=Gear_Door_Up_L2
Sequence8_Model=gear_l_door2
Sequence9=Gear_Door_Up_L3
Sequence9_Model=gear_l_door3
Sequence10=Gear_Up_R
Sequence10_Model=gear_r
Sequence11=Gear_Door_Up_R1
Sequence11_Model=gear_r_door1
Sequence12=Gear_Door_Up_R2
Sequence12_Model=gear_r_door2
Sequence13=Gear_Door_Up_R3
Sequence13_Model=gear_r_door3
Sequence14=Gear_Up_Rear
Sequence14_Model=GearRear
Sequence15=Gear_Door_Up_Rear1
Sequence15_Model=WheelRearDoor1
Sequence16=Gear_Door_Up_Rear2
Sequence16_Model=WheelRearDoor2
Sequence17=Gear_Door_Up_Rear3
Sequence17_Model=WheelRearDoor3

[Nozzles_STOL]
NumberOfSequencesToPlay=2
Sequence1=Nozzle_STOL
Sequence1_Model=front_engine
Sequence2=Nozzle_STOL
Sequence2_Model=rear_engine

[Nozzles_STOL_Retract]
NumberOfSequencesToPlay=2
Sequence1=Nozzle_STOL_Retract
Sequence1_Model=front_engine
Sequence2=Nozzle_STOL_Retract
Sequence2_Model=rear_engine

[Nozzles_VTOL]
NumberOfSequencesToPlay=2
Sequence1=Nozzle_VTOL
Sequence1_Model=front_engine
Sequence2=Nozzle_VTOL
Sequence2_Model=rear_engine

[Nozzles_VTOL_Retract]
NumberOfSequencesToPlay=4
NumberOfSequencesToPlay=2
Sequence1=Nozzle_VTOL_Retract
Sequence1_Model=front_engine
Sequence2=Nozzle_VTOL_Retract
Sequence2_Model=rear_engine


[------------------------------ Sequences ------------------------------]
[Canopy_Open]
NumberOfSteps=2
Time1=0 
PositionZ1=0.032789
PositionY1=0.010561
Smoothness1=EaseInOut
Time2=5 
PositionZ2=0.024523
PositionY2=0.013687
Smoothness2=EaseInOut

[Canopy_Close]
NumberOfSteps=2
Time1=0 
PositionZ1=0.024523
PositionY1=0.013687
Smoothness1=EaseInOut
Time2=5 
PositionZ2=0.032789
PositionY2=0.010561
Smoothness2=EaseInOut

[Flap_Takeoff]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=5 
RotationX2=-20
Smoothness2=EaseInOut

[Flap_Takeoff_Retract]
NumberOfSteps=2
Time1=0 
RotationX1=-20
Smoothness1=EaseInOut
Time2=5 
RotationX2=0
Smoothness2=EaseInOut

[Flap_Landing]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=10 
RotationX2=-35
Smoothness2=EaseInOut

[Flap_Landing_Retract]
NumberOfSteps=2
Time1=0 
RotationX1=-35
Smoothness1=EaseInOut
Time2=10 
RotationX2=0
Smoothness2=EaseInOut

###Retract Gear 

#Nose Gear
[Nose_Gear_Up]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=2 
RotationX2=-52.5
Smoothness2=EaseInOut

[Nose_Gear_Up2]
NumberOfSteps=2
Time1=2 
RotationX1=0
Smoothness1=EaseInOut
Time2=4 
RotationX2=-52.5
Smoothness2=EaseInOut

[Nose_Gear_Door_Up1]
NumberOfSteps=2
Time1=4 
RotationZ1=0
Smoothness1=EaseInOut
Time2=8 
RotationZ2=-85
Smoothness2=EaseInOut

[Nose_Gear_Door_Up2]
NumberOfSteps=2
Time1=4 
RotationZ1=0
Smoothness1=EaseInOut
Time2=8 
RotationZ2=85
Smoothness2=EaseInOut

[Nose_Gear_Door_Up3]
NumberOfSteps=2
Time1=4 
RotationX1=0
Smoothness1=EaseInOut
Time2=8 
RotationX2=-40
Smoothness2=EaseInOut

#Left Gear
[Gear_Up_L]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=4 
RotationX2=85
Smoothness2=EaseInOut

[Gear_Door_Up_L1]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=4 
RotationX2=55
Smoothness2=EaseInOut

[Gear_Door_Up_L2]
NumberOfSteps=2
Time1=4 
RotationZ1=0
Smoothness1=EaseInOut
Time2=8 
RotationZ2=90
Smoothness2=EaseInOut

[Gear_Door_Up_L3]
NumberOfSteps=2
Time1=4 
RotationZ1=0
Smoothness1=EaseInOut
Time2=8 
RotationZ2=-90
Smoothness2=EaseInOut

#Right Gear
[Gear_Up_R]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=4 
RotationX2=85
Smoothness2=EaseInOut

[Gear_Door_Up_R1]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=4 
RotationX2=55
Smoothness2=EaseInOut

[Gear_Door_Up_R2]
NumberOfSteps=2
Time1=4 
RotationZ1=0
Smoothness1=EaseInOut
Time2=8 
RotationZ2=90
Smoothness2=EaseInOut

[Gear_Door_Up_R3]
NumberOfSteps=2
Time1=4 
RotationZ1=0
Smoothness1=EaseInOut
Time2=8 
RotationZ2=-90
Smoothness2=EaseInOut

#Rear Gear
[Gear_Up_Rear]
NumberOfSteps=2
Time1=0 
PositionY1=-0.011232
RotationX1=0
Smoothness1=EaseInOut
Time2=4 
PositionY2=-0.005945
RotationX2=90
Smoothness2=EaseInOut

[Gear_Door_Up_Rear1]
NumberOfSteps=2
Time1=4 
RotationZ1=0
Smoothness1=EaseInOut
Time2=8 
RotationZ2=85
Smoothness2=EaseInOut

[Gear_Door_Up_Rear2]
NumberOfSteps=2
Time1=4 
RotationZ1=0
Smoothness1=EaseInOut
Time2=8 
RotationZ2=-85
Smoothness2=EaseInOut

[Gear_Door_Up_Rear3]
NumberOfSteps=2
Time1=4 
RotationX1=0
Smoothness1=EaseInOut
Time2=8 
RotationX2=90
Smoothness2=EaseInOut

#--------------------------------------------

###Extend Gear
#Nose Gear
[Nose_Gear_Down]
NumberOfSteps=2
Time1=4 
RotationX1=-52.5
Smoothness1=EaseInOut
Time2=6 
RotationX2=0
Smoothness2=EaseInOut

[Nose_Gear_Down2]
NumberOfSteps=2
Time1=5 
RotationX1=-52.5
Smoothness1=EaseInOut
Time2=8 
RotationX2=0
Smoothness2=EaseInOut

[Nose_Gear_Door_Down1]
NumberOfSteps=2
Time1=0 
RotationZ1=-85
Smoothness1=EaseInOut
Time2=4 
RotationZ2=0
Smoothness2=EaseInOut

[Nose_Gear_Door_Down2]
NumberOfSteps=2
Time1=0 
RotationZ1=85
Smoothness1=EaseInOut
Time2=4 
RotationZ2=0
Smoothness2=EaseInOut

[Nose_Gear_Door_Down3]
NumberOfSteps=2
Time1=0 
RotationX1=-40
Smoothness1=EaseInOut
Time2=4 
RotationX2=0
Smoothness2=EaseInOut

#Left Gear
[Gear_Down_L]
NumberOfSteps=2
Time1=4 
RotationX1=85
Smoothness1=EaseInOut
Time2=8 
RotationX2=0
Smoothness2=EaseInOut

[Gear_Door_Down_L1]
NumberOfSteps=2
Time1=4 
RotationX1=55
Smoothness1=EaseInOut
Time2=8 
RotationX2=0
Smoothness2=EaseInOut

[Gear_Door_Down_L2]
NumberOfSteps=2
Time1=0 
RotationZ1=90
Smoothness1=EaseInOut
Time2=4 
RotationZ2=0
Smoothness2=EaseInOut

[Gear_Door_Down_L3]
NumberOfSteps=2
Time1=0 
RotationZ1=-90
Smoothness1=EaseInOut
Time2=4 
RotationZ2=0
Smoothness2=EaseInOut

#Right Gear
[Gear_Down_R]
NumberOfSteps=2
Time1=4 
RotationX1=85
Smoothness1=EaseInOut
Time2=8 
RotationX2=0
Smoothness2=EaseInOut

[Gear_Door_Down_R1]
NumberOfSteps=2
Time1=4 
RotationX1=55
Smoothness1=EaseInOut
Time2=8 
RotationX2=0
Smoothness2=EaseInOut

[Gear_Door_Down_R2]
NumberOfSteps=2
Time1=0 
RotationZ1=90
Smoothness1=EaseInOut
Time2=4 
RotationZ2=0
Smoothness2=EaseInOut

[Gear_Door_Down_R3]
NumberOfSteps=2
Time1=0 
RotationZ1=-90
Smoothness1=EaseInOut
Time2=4 
RotationZ2=0
Smoothness2=EaseInOut

#Rear Gear
[Gear_Down_Rear]
NumberOfSteps=2
Time1=4 
PositionY1=-0.005945
RotationX1=90
Smoothness1=EaseInOut
Time2=8 
PositionY2=-0.011232
RotationX2=0
Smoothness2=EaseInOut

[Gear_Door_Down_Rear1]
NumberOfSteps=2
Time1=0 
RotationZ1=85
Smoothness1=EaseInOut
Time2=4 
RotationZ2=0
Smoothness2=EaseInOut

[Gear_Door_Down_Rear2]
NumberOfSteps=2
Time1=0 
RotationZ1=-85
Smoothness1=EaseInOut
Time2=4 
RotationZ2=0
Smoothness2=EaseInOut

[Gear_Door_Down_Rear3]
NumberOfSteps=2
Time1=0 
RotationX1=90
Smoothness1=EaseInOut
Time2=4 
RotationX2=0
Smoothness2=EaseInOut

//----------------------------

[Nozzle_STOL]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=2 
RotationX2=-45
Smoothness2=EaseInOut

[Nozzle_STOL_Retract]
NumberOfSteps=2
Time1=0 
RotationX1=-45
Smoothness1=EaseInOut
Time2=2 
RotationX2=0
Smoothness2=EaseInOut

[Nozzle_VTOL]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=4 
RotationX2=-90
Smoothness2=EaseInOut

[Nozzle_VTOL_Retract]
NumberOfSteps=2
Time1=0 
RotationX1=-90
Smoothness1=EaseInOut
Time2=4 
RotationX2=0
Smoothness2=EaseInOut

