[Animations]
NumberOfAnimations=8

Animation1=ShaftHatchOpenAnim_1
Animation2=ShaftHatchOpenAnim_2
Animation3=ShaftHatchOpenAnim_3
Animation4=ShaftHatchOpenAnim_4

Animation5=ShaftHatchCloseAnim_1
Animation6=ShaftHatchCloseAnim_2
Animation7=ShaftHatchCloseAnim_3
Animation8=ShaftHatchCloseAnim_4





[ShaftHatchOpenAnim_1]
NumberOfSequencesToPlay=3
Sequence1=ShaftHatchOpenAnimSequenceL
Sequence1_Model=Hatch_1
Sequence2=RetractPistonsExtensorsL
Sequence2_Model=Pistons_e_hatch_1
Sequence3=RetractPistonsL
Sequence3_Model=Pistons_hatch_1

[ShaftHatchOpenAnim_2]
NumberOfSequencesToPlay=3
Sequence1=ShaftHatchOpenAnimSequenceL
Sequence1_Model=Hatch_2
Sequence2=RetractPistonsExtensorsL
Sequence2_Model=Pistons_e_hatch_2
Sequence3=RetractPistonsL
Sequence3_Model=Pistons_hatch_2

[ShaftHatchOpenAnim_3]
NumberOfSequencesToPlay=3
Sequence1=ShaftHatchOpenAnimSequenceR
Sequence1_Model=Hatch_3
Sequence2=RetractPistonsExtensorsR
Sequence2_Model=Pistons_e_hatch_3
Sequence3=RetractPistonsR
Sequence3_Model=Pistons_hatch_3

[ShaftHatchOpenAnim_4]
NumberOfSequencesToPlay=3
Sequence1=ShaftHatchOpenAnimSequenceR
Sequence1_Model=Hatch_4
Sequence2=RetractPistonsExtensorsR
Sequence2_Model=Pistons_e_hatch_4
Sequence3=RetractPistonsR
Sequence3_Model=Pistons_hatch_4


### Close Missile ShaftHatches

[ShaftHatchCloseAnim_1]
NumberOfSequencesToPlay=1
Sequence1=ShaftHatchCloseAnimSequence
Sequence1_Model=Hatch_1

[ShaftHatchCloseAnim_2]
NumberOfSequencesToPlay=1
Sequence1=ShaftHatchCloseAnimSequence
Sequence1_Model=Hatch_2

[ShaftHatchCloseAnim_3]
NumberOfSequencesToPlay=1
Sequence1=ShaftHatchCloseAnimSequence
Sequence1_Model=Hatch_3

[ShaftHatchCloseAnim_4]
NumberOfSequencesToPlay=1
Sequence1=ShaftHatchCloseAnimSequence
Sequence1_Model=Hatch_4



[------------------------------ Sequences ------------------------------]

[---------- Alfa Sequences ----------]
############################################################
# ShaftHatches
############################################################

[ShaftHatchOpenAnimSequenceL]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=3                
RotationZ2=83
Smoothness2=EaseInOut

[ShaftHatchCloseAnimSequenceL]
NumberOfSteps=2
Time1=0 
RotationZ1=83
Smoothness1=EaseInOut
Time2=3                
RotationZ2=0
Smoothness2=EaseInOut

[ShaftHatchOpenAnimSequenceR]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=3                
RotationZ2=-83
Smoothness2=EaseInOut

[ShaftHatchCloseAnimSequenceR]
NumberOfSteps=2
Time1=0 
RotationZ1=-83
Smoothness1=EaseInOut
Time2=3                
RotationZ2=0
Smoothness2=EaseInOut

[RetractPistonsExtensorsL]
NumberOfSteps=2
Time1=0 
PositionY1=0.08988
RotationZ1=-10
Smoothness1=EaseInOut
Time2=3      
PositionY2=0.0866         
RotationZ2=2
Smoothness2=EaseInOut

[RetractPistonsL]
NumberOfSteps=2
Time1=0 
RotationZ1=-10
Smoothness1=EaseInOut
Time2=3                
RotationZ2=2.2
Smoothness2=EaseInOut


[RetractPistonsExtensorsR]
NumberOfSteps=2
Time1=0 
PositionY1=0.08988
RotationZ1=10
Smoothness1=EaseInOut
Time2=3      
PositionY2=0.0866         
RotationZ2=-2
Smoothness2=EaseInOut

[RetractPistonsR]
NumberOfSteps=2
Time1=0 
RotationZ1=10
Smoothness1=EaseInOut
Time2=3                
RotationZ2=-2.2
Smoothness2=EaseInOut

