[Animations]
NumberOfAnimations=4
Animation1=HangarOpenAnim
Animation2=HangarCloseAnim

Animation3=VDS_Extend
Animation4=VDS_Retract




[HangarOpenAnim]
NumberOfSequencesToPlay=4

Sequence1=HangarOpenDoor1AnimSequence
Sequence1_Model=Hangar_door_1
Sequence2=HangarOpenDoor2AnimSequence
Sequence2_Model=Hangar_door_2
Sequence3=HangarOpenDoor3AnimSequence
Sequence3_Model=Hangar_door_3
Sequence4=HangarOpenDoor4AnimSequence
Sequence4_Model=Hangar_door_4


[HangarCloseAnim]
NumberOfSequencesToPlay=4

Sequence1=HangarCloseDoor1AnimSequence
Sequence1_Model=Hangar_door_1
Sequence2=HangarCloseDoor2AnimSequence
Sequence2_Model=Hangar_door_2
Sequence3=HangarCloseDoor3AnimSequence
Sequence3_Model=Hangar_door_3
Sequence4=HangarCloseDoor4AnimSequence
Sequence4_Model=Hangar_door_4

[VDS_Extend]
NumberOfSequencesToPlay=2

Sequence1=Lower_Rail
Sequence1_Model=VDS_Rail
Sequence2=Extend_Cable
Sequence2_Model=VDS_Cable

[VDS_Retract]
NumberOfSequencesToPlay=1

Sequence1=Raise_Rail
Sequence1_Model=VDS_Rail


[------------------------------ Sequences ------------------------------]
############################################################
# Elevators
############################################################

#Open Doors
[HangarOpenDoor1AnimSequence]
NumberOfSteps=2
Time1=0             // time in seconds for the start
PositionY1=0.091525
Smoothness1=Linear  // can be: Linear, EaseInOut - transition to the next step
Time2=4               // time in seconds - here for the end
PositionY2=0.159366
Smoothness2=Linear  // can be: Linear, EaseInOut - is not used here as it's the last entry


[HangarOpenDoor2AnimSequence]
NumberOfSteps=2
Time1=0              // time in seconds for the start
PositionY1=0.108337
Smoothness1=Linear  // can be: Linear, EaseInOut - transition to the next step
Time2=3.7        // time in seconds - here for the end
PositionY2=0.159366
Smoothness2=Linear  // can be: Linear, EaseInOut - is not used here as it's the last entry

[HangarOpenDoor3AnimSequence]
NumberOfSteps=2
Time1=0              // time in seconds for the start
PositionY1=0.125149
Smoothness1=Linear  // can be: Linear, EaseInOut - transition to the next step
Time2=3.7        // time in seconds - here for the end
PositionY2=0.159366
Smoothness2=Linear  // can be: Linear, EaseInOut - is not used here as it's the last entry

[HangarOpenDoor4AnimSequence]
NumberOfSteps=2
Time1=0              // time in seconds for the start
PositionY1=0.141961
Smoothness1=Linear  // can be: Linear, EaseInOut - transition to the next step
Time2=3.7        // time in seconds - here for the end
PositionY2=0.159366
Smoothness2=Linear  // can be: Linear, EaseInOut - is not used here as it's the last entry


#Close Doors
[HangarCloseDoor1AnimSequence]
NumberOfSteps=2
Time1=0             // time in seconds for the start
PositionY1=0.159366
Smoothness1=Linear  // can be: Linear, EaseInOut - transition to the next step
Time2=4               // time in seconds - here for the end
PositionY2=0.091525
Smoothness2=Linear  // can be: Linear, EaseInOut - is not used here as it's the last entry

[HangarCloseDoor2AnimSequence]
NumberOfSteps=2
Time1=0             // time in seconds for the start
PositionY1=0.159366
Smoothness1=Linear  // can be: Linear, EaseInOut - transition to the next step
Time2=4               // time in seconds - here for the end
PositionY2=0.108337
Smoothness2=Linear  // can be: Linear, EaseInOut - is not used here as it's the last entry

[HangarCloseDoor3AnimSequence]
NumberOfSteps=2
Time1=0             // time in seconds for the start
PositionY1=0.159366
Smoothness1=Linear  // can be: Linear, EaseInOut - transition to the next step
Time2=4               // time in seconds - here for the end
PositionY2=0.125149
Smoothness2=Linear  // can be: Linear, EaseInOut - is not used here as it's the last entry

[HangarCloseDoor4AnimSequence]
NumberOfSteps=2
Time1=0             // time in seconds for the start
PositionY1=0.159366
Smoothness1=Linear  // can be: Linear, EaseInOut - transition to the next step
Time2=4               // time in seconds - here for the end
PositionY2=0.141961
Smoothness2=Linear  // can be: Linear, EaseInOut - is not used here as it's the last entry



[Lower_Rail]
NumberOfSteps=2
Time1=0                // time in seconds for the start
PositionZ1=-0.724186
PositionY1=0.027263
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time2=2                // time in seconds - here for the end
PositionZ2=-0.747617
PositionY2=0.009837
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry

[Extend_Cable]
NumberOfSteps=2
Time1=0                // time in seconds for the start
PositionZ1=-0.8
PositionY1=0.078827
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time2=2                // time in seconds - here for the end
PositionZ2=-0.825
PositionY2=0.047011
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry


[Raise_Rail]
NumberOfSteps=2
Time1=0                // time in seconds for the start
PositionZ1=-0.747617
PositionY1=0.009837
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time2=2                // time in seconds - here for the end
PositionZ2=-0.724186
PositionY2=0.027263
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry




[------------------------------ FlightDeck Taxi Sequences ------------------------------]


[Elevator2LaunchPoint3Sequence]
#FixMe
NumberOfSteps=2
Time1=0                // time in seconds for the start
PositionX1=0.042
PositionY1=0.1676
PositionZ1=-1.07
RotationY1=0
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step

Time2=10
PositionZ2=-1.28
Smoothness2=Linear  //EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry

[Elevator1LaunchPoint4Sequence]
#FixMe
NumberOfSteps=2
Time1=0                // time in seconds for the start
PositionX1=-0.1245
PositionY1=0.1676
PositionZ1=-0.61
RotationY1=0
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step

Time2=14
PositionZ2=-0.98
Smoothness2=Linear  //EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry

[RecoveryPoint1Elevator1Sequence]
NumberOfSteps=2
Time1=0                // time in seconds for the start
PositionX1=-0.1245
PositionY1=0.1676
PositionZ1=-0.98
RotationY1=0
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step

Time2=14
PositionZ2=-0.61
Smoothness2=EaseInOut

[RecoveryPoint2Elevator2Sequence]
NumberOfSteps=2
Time1=0                // time in seconds for the start
PositionX1=0.042
PositionY1=0.1676
PositionZ1=-1.28
RotationY1=0
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step

Time2=10
PositionZ2=-1.07
Smoothness2=EaseInOut
