[Animations]
NumberOfAnimations=2

#Animation1=UnloadAmmunition
Animation1=LoadAspide
Animation2=UnloadAspide
[LoadAspide]
NumberOfSequencesToPlay=15
Sequence1=SpawnMissile
Sequence1_Model=Dummy
Sequence2=ElevateLauncher
Sequence2_Model=MK29_Launcher
Sequence3=OpenHatch
Sequence3_Model=Aspide_hatch
Sequence4=RotateLauncher1
Sequence4_Model=MK29_Launcher
Sequence5=ElevateLoader
Sequence5_Model=Aspide_loader
Sequence6=MoveMissileLUp
Sequence6_Model=Aspide_L
Sequence7=MoveMissileRUp
Sequence7_Model=Aspide_R
Sequence8=DisappearL
Sequence8_Model=Aspide_L
Sequence9=DisappearR
Sequence9_Model=Aspide_R
Sequence10=LowerLoader
Sequence10_Model=Aspide_loader
Sequence11=RotateLauncher2
Sequence11_Model=MK29_Launcher
Sequence12=CloseHatch
Sequence12_Model=Aspide_hatch
Sequence13=LevelLauncher
Sequence13_Model=MK29_Launcher
Sequence14=ResetL
Sequence14_Model=Aspide_L
Sequence15=ResetR
Sequence15_Model=Aspide_R

[UnloadAspide]
NumberOfSequencesToPlay=1
Sequence1=MoveMissileDown
Sequence1_Model=SpawnedObject


[SpawnMissile]
UseLauncherPositionOffsets=True  // optional, if true means that it uses the launcher position offsets from the ammunition file in section [Launchers]
Spawn=True
NumberOfSteps=1
Time1=0
PositionZ1=0

[ElevateLauncher]
NumberOfSteps=2
Time1=0
RotationX1=0
Smoothness1=EaseInOut
Time2=4                
RotationX2=-70
Smoothness2=EaseInOut

[OpenHatch]
NumberOfSteps=2
Time1=4.1
RotationX1=0
Smoothness1=EaseInOut
Time2=7               
RotationX2=-45
Smoothness2=EaseInOut

[RotateLauncher1]
NumberOfSteps=2
Time1=7.1
RotationX1=-70
Smoothness1=EaseInOut
Time2=9               
RotationX2=-30
Smoothness2=EaseInOut

[ElevateLoader]
NumberOfSteps=2
Time1=9
PositionY1=0.101115
Smoothness1=EaseInOut
Time2=12               
PositionY2=0.11919
Smoothness2=EaseInOut

[MoveMissileLUp]
NumberOfSteps=2
Time1=12.5
PositionZ1=-0.000024
Smoothness1=EaseInOut
Time2=16              
PositionZ2=0.063
Smoothness2=EaseInOut

[MoveMissileRUp]
NumberOfSteps=2
Time1=16.5
PositionZ1=-0.000024
Smoothness1=EaseInOut
Time2=20             
PositionZ2=0.063
Smoothness2=EaseInOut

[DisappearL]
NumberOfSteps=2
Time1=16
PositionY1=0.01255
Smoothness1=EaseInOut
Time2=16.01             
PositionY2=-0.15
Smoothness2=EaseInOut
[DisappearR]
NumberOfSteps=2
Time1=20
PositionY1=0.01255
Smoothness1=EaseInOut
Time2=20.01             
PositionY2=-0.15
Smoothness2=EaseInOut

[LowerLoader]
NumberOfSteps=2
Time1=20.5
PositionY1=0.11919
Smoothness1=EaseInOut
Time2=25           
PositionY2=0.101115  
Smoothness2=EaseInOut

[RotateLauncher2]
NumberOfSteps=2
Time1=25
RotationX1=-30
Smoothness1=EaseInOut
Time2=27.9               
RotationX2=-70
Smoothness2=EaseInOut

[CloseHatch]
NumberOfSteps=2
Time1=28
RotationX1=-45
Smoothness1=EaseInOut
Time2=32               
RotationX2=0
Smoothness2=EaseInOut

[LevelLauncher]
NumberOfSteps=2
Time1=32
RotationX1=-70
Smoothness1=EaseInOut
Time2=34                
RotationX2=-0
Smoothness2=EaseInOut

[ResetL]
NumberOfSteps=2
Time1=34
PositionZ1=0.0611352
PositionY1=-0.15
Smoothness1=EaseInOut
Time2=34.01              
PositionZ2=-0.007248
PositionY2=0.01255
Smoothness2=EaseInOut

[ResetR]
NumberOfSteps=2
Time1=34
PositionZ1=0.0611352
PositionY1=-0.15
Smoothness1=EaseInOut
Time2=34.01              
PositionZ2=-0.007248
PositionY2=0.01255
Smoothness2=EaseInOut


[MoveMissileDown]
UseReverseLauncherPositionOffsets=True  // optional, if true means that it uses the reverse launcher position offsets from the ammunition file in section [Launchers]
NumberOfSteps=2
Time1=0                // time in seconds for the start
PositionZ1=0           // can be 0 here as we use the missile specific positions from the ammunition file from section [Launchers]
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time2=1                // time in seconds - here for the end
PositionZ2=0           // can be 0 here as we use the missile specific positions from the ammunition file from section [Launchers]
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry
