[AmmunitionNames]
# ------------------ AAM ------------------
su_aa-11_LQS=R-73,,AAM,The Vympel R-73 (AA-11 Archer) is an infrared AAM missile developed by the Soviet Union in the 1970s and 1980s. The R-73 pioneered the use of a vector engine, giving the missile far greater maneuverability than its contemporary missiles. It is considered one of the most threatening AAM missiles.

su_aa-12_1_LQS=R-77-1,,AAM,The Vympel R-77-1（AA-12 Adder）It is Russias active radar-guided medium-range air-to-air missile, an improvement on the R-77 with a longer range.

su_aa-12_pd_LQS=R-77-PD,,AAM,The Vympel R-77-PD（AA-12 Adder）It is Russias active radar-guided long-range air-to-air missile, using a ramjet engine, and its range has been greatly increased compared to the previous model.

su_aa-12_m_LQS=R-77M,,AAM,The Vympel R-77M（AA-12 Adder）It is Russia's active radar-guided long-range air-to-air missile,This missile employs a more powerful active phased array seeker and a dual-pulse engine, resulting in a significant performance improvement.


# ------------------ SAM ------------------

# ---------- Anti-radar Missiles ---------
su_as-17a_LQS=KH-31P,,ARM,Tactical Missiles Corporation Kh-31P（AS-17 Krypton）It is a Soviet supersonic anti-radiation missile, similar to the P-270 in many aspects. It looks like a smaller version of the P-270. There are reportedly plans to convert it into a long-range air-to-air missile.
# ---------- Anti-ship Missiles ----------
su_as-18a_LQS=Kh-59M,,ASM,Tactical Missiles Corporation Kh-59M (AS-18 Kazoo) It is a Russian subsonic air-to-surface/ship missile. Compared with the Kh-59, the M type has a longer range and a higher speed.
#-----------Land Strike only missiles---------
su_as-14_LQS=Kh-29T,,AGM,Vympel Kh-29T（AS-14 Kedge）It is a Soviet television-guided supersonic air-to-ground missile with great power that can be used to destroy ships not exceeding 10,000 tons.

su_kh-38_LQS=Kh-38ME,,AGM,Tactical Missiles Corporation Kh-38ME is Russia's tactical missile. The missile is a modular weapon with multiple guidance heads. ME is active radar guided.

# ---------- Anti-sub  Missilies ----------
su_as-20_LQS=Kh-35,,ASM,Zvezda Kh-35 (AS-20 Kayak) It is a Russian subsonic anti-ship missile. Because its appearance and performance are similar to those of the American Harpoon missile, it is nicknamed "Harpoonski". It is designed to attack ships under 5,000 tons.
su_kh-35_LQS=Kh-35,,AGM,Zvezda Kh-35 (AS-20 Kayak) It is a Russian subsonic anti-ship missile. Because its appearance and performance are similar to those of the American Harpoon missile, it is nicknamed "Harpoonski". It is designed to attack ships under 5,000 tons.It can also be used to attack ground targets.
# ------------------ RBU ------------------

# --------------- Torpedoes ---------------

# ------------------ Bombs -----------------
wp_kab-500kr_LQS=KAB-500Kr,TV,Land Attack,The KAB-500Kr is an electro-optical TV-guided fire and forget bomb developed by the Soviet Air Force in the 1980s.
# ---------------- Sonobuoys ---------------

# ------------------ FFAR -----------------

# ------------------ MLRS -----------------

# ------------------ Guns -----------------

# ------------------ CIWS -----------------

# ----------- Noisemakers/Chaff -----------

# ----------------- Decoys ----------------

# ----------------- Special ----------------

# Depth charge

# ----------------- Fueltanks ----------------
wp_tank_1200mig-35=1200L

