[AmmunitionNames]
# ------------------ AAM ------------------
uav_aim-9x=AIM-9X,响尾蛇,空对空,AIM-9X响尾蛇是美国的红外制导空对空导弹，X型进行了大幅度的升级，拥有强大的抗干扰能力更远的射程，以及令人印象深刻的越肩发射能力。

uav_aim-92=AIM-92,毒刺,空对空,FIM-92毒刺便携式防空导弹，为小型便携式防空导弹，采用红外线制导热追踪以及紫外线物体追踪，由美国研发并使用于所有美军部队，1981年服役至今。在美国和其他29个国家中。主要由雷神公司制造，授权德国的EADS和土耳其的ROKETSAN生产导弹，已经生产超过70,000枚导弹。

# ------------------ SAM ------------------

# ---------- Anti-radar Missiles ---------

# ---------- Anti-ship Missiles ----------

#-----------Land Strike only missiles---------

# ---------- Anti-sub  Missilies ----------

uav_agm-114k=AGM-114K,地狱火,空对地,AGM-114地狱火导弹是一种多平台、多目标的美国制导弹。主要用于反战车，但后期型号也被用于无人机攻击，精确打击高价值目标等。

uav_gbu-12d=GBU-12D,宝石路 II,对地攻击,美国于1970年代对宝石路I系统进行了改进，新的系统拥有可展开的尾翼，使得滑翔距离更远，且更加精准，并且价格更加低廉。改进后的宝石路系统被称为宝石路II。

uav_gbu-49=GBU-49,宝石路 IV,对地攻击,宝石路IV由旧式的GBU-12宝石路II升级而来，拥有了卫星制导与激光制导双制导模式，使其更为可靠。
# ------------------ RBU ------------------
# --------------- Torpedoes ---------------
# ------------------ Bombs -----------------

# ---------------- Sonobuoys ---------------
# ------------------ FFAR -----------------
# ------------------ MLRS -----------------
# ------------------ Guns -----------------
# ------------------ CIWS -----------------
# ----------- Noisemakers/Chaff -----------
# ----------------- Decoys ----------------
# ----------------- Special ----------------
# ----------------- Fueltanks ----------------
uav_tank_mq-9=MQ-9副油箱,,副油箱