[AmmunitionNames]
#WIKI
# ------------------ AAM ------------------
plaaf_pl-10=PL-10,,空对空,霹雳-10是中国为第四代和第五代战斗机研制的近距红外制导空空导弹。导弹导引头采用多重红外成像制导技术，具有很强的抗干扰能力，支持头盔显示器随动。导弹支持大离轴，大过载发射条件，拥有近距红外格斗弹中较远的射程。

plaaf_pl-15=PL-15,,空对空,霹雳-15是中国为第四代和第五代战斗机研制的中远程主动雷达制导空空导弹。导弹采用双脉冲固体火箭发动机，有源相控阵主动雷达导引头，具备高末端速度和优异的抗电子干扰能力。

plaaf_pl-17=PL-17,,远程空对空,霹雳-17是中国空军装备的远程主动雷达制导空空导弹，主要用于在超远距离上攻击地方辅助和支援飞机目标，包括加油机，预警机，轰炸机等，导弹射程远速度快，但机动性较差，不适合攻击高机动性的目标。


# ------------------ SAM ------------------

# ---------- Anti-radar Missiles ---------
plaaf_akf-98a=AKF-98A,,反辐射巡航导弹,AKF-98A是中国空军装备的隐身构型反辐射巡航导弹，可利用其雷达低可视特性穿透地方防空网络，对低空导弹阵地和各类雷达阵地目标发动精确打击。

plaaf_yj-91=YJ-91,,反辐射导弹,鹰击-91是中国空军装备的反辐射导弹，是引进自俄罗斯的Kh-31P反辐射导弹的国产版本。

# ---------- Anti-ship Missiles ----------
plaaf_cm401=CM-401,,反舰弹道导弹,CM-401首次亮相于2018年珠海航展，发展了舰射，空射等多种型号，曾作为055反舰弹道导弹的备选。
plaaf_cm-400akg=CM-400AKG,,短程弹道导弹,CM-400AKG是中国空军的一款短程弹道导弹，多用途，被销售给了巴基斯坦
#-----------Land Strike only missiles---------

# ---------- Anti-sub  Missilies ----------

# ------------------ RBU ------------------

# --------------- Torpedoes ---------------

# ------------------ Bombs -----------------

plaaf_ls-6_500=雷石-6（500公斤）,滑翔炸弹,对地攻击,LS-6型500千克GPS精确制导滑翔炸弹由500公斤低阻航空炸弹加装滑翔和制导组件构成，具备防区外精确制导打击能力。

plaaf_ls-6_500_zc=LS-6 500千克,增程型,滑翔炸弹,雷石-6增程型是使用滑翔套件并加装涡轮喷气发动机改装的500公斤通用航空炸弹，GPS制导，主要用于打击固定地面目标。
# ---------------- Sonobuoys ---------------

# ------------------ FFAR -----------------

# ------------------ MLRS -----------------

# ------------------ Guns -----------------

# ------------------ CIWS -----------------

# ----------- Noisemakers/Chaff -----------

# ----------------- Decoys ----------------

# ----------------- Special ----------------

# Depth charge

# ----------------- Fueltanks ----------------
