[General]
UnitType=LandUnit
LandUnitSubType=MobileUnit

DefaultCameraDistance=0.8
MinCameraDistanceForeAft=0.4
MinCameraDistanceBroadside=0.4
CameraPivotHeight=0.04

GroundOffset=0
AutoFlatten=False
MaskVegetation=True

Length=7.9                     // in meters
Beam=3.25                       // in meters
Range=310                      // in miles

# Hull armor: None, Minor, Moderate, Heavy
ArmorType=Minor
DamagePoints=5  //systems damage contribution substracted from this when systems destroyed, when becomes less than zero, the whole unit is considered being destroyed

[Physics]
HorsePower=710
Mass=35                      // in tons

MaxForwardVelocity=35.1        // in knots
MaxBackwardVelocity=7          // in knots
Braking=12                     // knots/sec
TurnRate=25                    // in degrees per second

[AI]
UnitScoreValue=1               // value for calculation of mission score
Role=Gun,AAW,SAM

[ControlSystem]
Collider=coll_hitbox  // makes unit destroyable
Integrity=5

[SensorData]
#Visual
VisualIdentificationRange=2.5  // Camouflaged  (x0.5)
IRSignature=Small
# Radar related (RCS => radar cross section)
RCS=Small

[Animations]
NumberOfAnimationReferences=1
AnimationFile_1=animations_wp_spaa_zsu-23-4

[---------- Sensor Systems ----------]
############################################################
# Sensor Systems
############################################################
[SensorSystems]
NumberOfSensorSystems=2
#---------- Visual ----------
[SensorSystem1] #AdvancedOptics
Type=Visual
SystemName=AdvancedOptics
MountPosition=0,0.04,0

[SensorSystem2]  #1RL33_Search
Type=Radar
SystemName=1RL33_Search
Mount=Radar_Turret
#Animations
OpenSystemAnimation=Search_On
CloseSystemAnimation=Search_Off
ModuleType=Sensor

[---------- Weapon Systems ----------]
############################################################
# Weapon Systems
############################################################
[WeaponSystems]
NumberOfWeaponSystems=3

[WeaponSystem1]  #2A38
Type=CIWS
SystemName=23mm_ZSU-23-4
#Sensors
#AssociatedSensors=SensorSystem2
#Animations
#Mount
Mount=Turret
IsMountRotatable=True
#Containers
ContainerBase=Gun1
Gun=Barrel1
AreContainersRotatable=True
#Angles
ElevationArc=-4,85
RestAngles=0
#Loading
AssociatedMagazine=WeaponMagazineCIWS
#Effects
#Other
MaxVelocityToFire=5
VIDIncrease=6  // In miles. Flat base VID increace when firing.
SharesMountWith=WeaponSystem2,WeaponSystem3

[WeaponSystem2]  #2A38
Type=CIWS
SystemName=23mm_ZSU-23-4
#Sensors
#AssociatedSensors=SensorSystem2
#Animations
#Mount
Mount=Turret
IsMountRotatable=True
#Containers
ContainerBase=Gun2
Gun=Barrel2
AreContainersRotatable=True
#Angles
ElevationArc=-4,85
RestAngles=0
#Loading
AssociatedMagazine=WeaponMagazineCIWS
#Effects
#Other
MaxVelocityToFire=5
VIDIncrease=6  // In miles. Flat base VID increace when firing.
SharesMountWith=WeaponSystem1,WeaponSystem3

[WeaponSystem3]  #Missile
Type=Missile
SystemName=ZSU-23-4_Igla
#Sensors
#Animations
#Mount
Mount=Turret
IsMountRotatable=True
#Containers
ContainerBase=Launcher
NumberOfContainers=1
Container1=Launcher
AreContainersRotatable=True
#Angles
FixVerticalLaunchAngle=False
AdditionalFixVerticalLaunchAngle=2
ElevationArc=-4,85
RestAngles=Any
LoadAngles=Any
#Loading
AssociatedMagazine=WeaponMagazineTOW
PreloadAmmunition=True           // REQUIRED!!! for non-unloading launchers with magazine, like MK29 and ASROC
#Effects
#Other
DisplayWeaponsOnSystem=True
VIDIncrease=4  // In miles. Flat base VID increace when firing.
SharesMountWith=WeaponSystem1,WeaponSystem2


[---------- WeaponMagazines ----------]
[WeaponMagazineTOW]
NumberOfAmmunitionTypes=1
Ammunition1=wp_9k38
Ammunition1_Count=8
ModuleType=SmallMagazine

[WeaponMagazineCIWS]
NumberOfAmmunitionTypes=1
Ammunition1=wp_cal_23mm_zsu
Ammunition1_Count=4000
ModuleType=SmallMagazine

[Models]
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=assets/models/land_units/zsu-23-4/
ResourcesRoot=zsu-23-4m4.obj
ResourcesMesh=hull
ResourcesMaterial=zsu-23-4_mat.ini
############################################################

[Submodels]
Turret=Turret
Gun1=Gun1
Gun2=Gun2
Barrel1=Barrel1
Barrel2=Barrel2
Weapon1=Launcher_Base
Weapon2=Launcher
Radar_Turret1=Radar_Turret1
Radar_Turret=Radar_Turret
Radar_Gun=Radar_Gun
Radar=Radar

[Turret]
Mesh=turret
Material=zsu-23-4_mat.ini
Position=0,0.02353,0.00118

[Launcher]
Mesh=launcher
Parent=Turret
Material=zsu-23-4_mat.ini
Position=0,0.010436,-0.031174

[Gun1]
Mesh=gun1
Material=zsu-23-4_mat.ini
Parent=Turret
Position=0,0.002616,0.013967

[Gun2]
Mesh=gun2
Material=zsu-23-4_mat.ini
Parent=Turret
Position=0,0.006999,0.009144

[Barrel1]
Mesh=barrel
Material=zsu-23-4_mat.ini
Parent=Gun1
Position=0,0.000461,-0.018643

[Barrel2]
Mesh=barrel
Material=zsu-23-4_mat.ini
Parent=Gun2
Position=0,0.000461,-0.018643

[Radar_Turret1]
Parent=Turret
Position=0,0.010377,-0.021724
Rotation=0,180,0

[Radar_Turret]
Mesh=radar_turret
Material=zsu-23-4_mat.ini
Parent=Radar_Turret1

[Radar_Gun]
Mesh=radar_gun
Material=zsu-23-4_mat.ini
Parent=Radar_Turret
Position=0,0.000176,0.000943
Rotation=90,0,0

[Radar]
Mesh=search
Material=zsu-23-4_mat.ini
Parent=Radar_Gun
Position=0,0.011067,0
Rotation=-15,0,0

[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=1
AmbientAudioClip=audio/ships/Ship-Turbine-Small
AmbientAudioPosition=0,0,0
AmbientAudioRollOff=Logarithmic
AmbientAudioDistance=1,20
AmbientAudioPitchRange=1.0,1.6
AmbientAudioVolume=1.0
AmbientAudioAudibility=Above  // layer of sound audibility: Above, Below, AboveAndBelow

[Particles]
SmallFireEffectClass=SmallShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=ModerateShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=SevereShipFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffect=effects/explosions/emitters/missile_hit_ship
SecondaryExplosionEffectPosition=0,0,0

DustEffect=effects/land units/emitters/vehicle_movement_dust
DustEffectPosition=0,0,0

[---------- Colliders ----------]
[Colliders]
UseKinematicCollision=False
NumberOfMeshColliders=0
NumberOfColliders=2

Collider1=coll_hitbox
Collider2=coll_collider

[coll_hitbox]
Collider=Box
Position=0,0.0197,0
Rotation=0,0,0
Scale=0.045,0.04,0.1

[coll_collider]
Collider=Box
Position=0,0.0028,-0.0023
Rotation=0,0,0
Scale=0.03,0.005,0.05
Layer=Default
