#!/usr/bin/env python3
"""Merge the 15 per-pack SEST outputs into one deployable pack.

Fifteen Mod Manager entries meant fifteen chances for something to jump over a
SEST pack and silently disable it — the exact way SEST_Growler_NGJ_MALICE once
went inert. One consolidated pack collapses that entire failure class: there
is one SEST entry, it sits at the top, done.

The per-pack folders under integration/*/SEST_* remain the build units (each
builder stays independently runnable and the checkers compute their rules from
them); this script runs after all of them and writes integration/dist/
SEST_Integration, which is the only thing tools/install-sest-packs.ps1 deploys.

Merge rules, in the order they are tried per colliding path:

  identical bytes            -> keep one copy (e.g. ammunition/sest_aim-424.ini,
                                shipped identically by five packs)
  language_*/ *.ini          -> key-level merge under each [Section]. The game
                                itself merges language files across mods, so
                                this reproduces in one file what the game
                                already computed from fifteen.
  systems/*.ini              -> section-level merge (sensor definitions).
  _info.ini                  -> regenerated for the consolidated pack.
  anything else              -> ERROR. Two packs shipping different bytes at
                                the same unit path is a real conflict that must
                                be resolved at the source, never auto-picked.

Same key (or section) with DIFFERENT values is always a hard error naming both
packs — the sources keep shared keys identical by design, and this enforces it.

    python3 tools/consolidate_packs.py
"""
import collections
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DIST = ROOT / "integration" / "dist" / "SEST_Integration"

INFO_HEADER = """[Language_en]
Name=SEST Integration Pack
Description={desc}

[Compatibility]
ApproximateVersion={version}
"""


def source_packs():
    """The per-pack build outputs, skipping dist itself."""
    return sorted(p for p in (ROOT / "integration").glob("*/SEST_*")
                  if p.is_dir() and p.parent.name != "dist")


def parse_kv_ini(text):
    """-> OrderedDict[section, OrderedDict[key, value]]; comments dropped."""
    sections = collections.OrderedDict()
    current = ""
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith(("#", ";", "//")):
            continue
        if stripped.startswith("[") and stripped.endswith("]"):
            current = stripped
            sections.setdefault(current, collections.OrderedDict())
            continue
        if "=" in stripped:
            key, _, value = stripped.partition("=")
            sections.setdefault(current, collections.OrderedDict())
            sections[current][key.strip()] = value
    return sections


def merge_kv(rel, contributions, problems):
    """Key-level merge of language files; conflicting values are errors."""
    merged = collections.OrderedDict()
    origin = {}
    for pack_name, text in contributions:
        for section, keys in parse_kv_ini(text).items():
            merged.setdefault(section, collections.OrderedDict())
            for key, value in keys.items():
                if key in merged[section] and merged[section][key] != value:
                    problems.append(
                        f"{rel}: [{section}] {key} differs between "
                        f"{origin[(section, key)]} and {pack_name}:\n"
                        f"      {origin[(section, key)]}: {merged[section][key]!r}\n"
                        f"      {pack_name}: {value!r}")
                    continue
                merged[section].setdefault(key, value)
                origin.setdefault((section, key), pack_name)
    lines = [f"# Generated by tools/consolidate_packs.py — merged from "
             f"{len(contributions)} pack(s). Edit the source packs, not this file."]
    for section, keys in merged.items():
        lines.append("")
        if section:
            lines.append(section)
        lines.extend(f"{k}={v}" for k, v in keys.items())
    return "\n".join(lines) + "\n"


def merge_sections(rel, contributions, problems):
    """Section-level merge of systems files; bodies kept verbatim."""
    bodies = collections.OrderedDict()   # section header -> (pack, body lines)
    for pack_name, text in contributions:
        current, buf = None, []
        def flush():
            if current is None:
                return
            body = "\n".join(buf).strip("\n")
            if current in bodies and bodies[current][1] != body:
                problems.append(f"{rel}: section {current} differs between "
                                f"{bodies[current][0]} and {pack_name}")
            else:
                bodies.setdefault(current, (pack_name, body))
        for line in text.splitlines():
            if line.strip().startswith("[") and line.strip().endswith("]"):
                flush()
                current, buf = line.strip(), []
            elif current is not None:
                buf.append(line)
        flush()
    lines = [f"# Generated by tools/consolidate_packs.py — sections from "
             f"{len(contributions)} pack(s). Edit the source packs, not this file."]
    for section, (pack_name, body) in bodies.items():
        lines += ["", f"# ---- from {pack_name} ----", section]
        if body:
            lines.append(body)
    return "\n".join(lines) + "\n"


def build_info(packs):
    names, versions = [], set()
    for pack in packs:
        text = (pack / "_info.ini").read_text(encoding="utf-8-sig", errors="replace")
        m = re.search(r"^Name=(.+)$", text, re.M)
        names.append(m.group(1).strip() if m else pack.name)
        v = re.search(r"^ApproximateVersion=(.+)$", text, re.M)
        if v:
            versions.add(v.group(1).strip())
    if len(versions) > 1:
        print(f"note: component ApproximateVersion values differ {sorted(versions)}; "
              "using the highest")
    version = max(versions, key=lambda s: [int(x) for x in re.findall(r"\d+", s)] or [0])
    desc = ("All SEST content as one pack, so a single Mod Manager entry at the top "
            "of the list carries every patch. Consolidated from: " + ", ".join(sorted(names))
            + ". Built by the Seapower-mods repo; the per-pack sources remain there.")
    return INFO_HEADER.format(desc=desc, version=version)


def main():
    packs = source_packs()
    if not packs:
        sys.exit("no built packs found — run tools/build_all.py first")

    by_rel = collections.defaultdict(list)   # rel path -> [(pack name, Path)]
    for pack in packs:
        for f in pack.rglob("*"):
            if f.is_file():
                by_rel[f.relative_to(pack).as_posix()].append((pack.name, f))

    problems, staged = [], {}
    for rel, owners in sorted(by_rel.items()):
        if rel == "_info.ini":
            continue
        blobs = [(name, path.read_bytes()) for name, path in owners]
        if len({b for _, b in blobs}) == 1:
            staged[rel] = blobs[0][1]
            continue
        texts = [(name, blob.decode("utf-8", errors="replace")) for name, blob in blobs]
        top = rel.split("/", 1)[0]
        if top.startswith("language_"):
            staged[rel] = merge_kv(rel, texts, problems).encode("utf-8")
        elif top == "systems":
            staged[rel] = merge_sections(rel, texts, problems).encode("utf-8")
        else:
            problems.append(f"{rel}: shipped with different bytes by "
                            + ", ".join(name for name, _ in owners)
                            + " — unit files must not collide; fix the sources")

    if problems:
        sys.exit("consolidation failed:\n  " + "\n  ".join(problems))

    if DIST.exists():
        import shutil
        shutil.rmtree(DIST)
    for rel, blob in staged.items():
        target = DIST / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(blob)
    (DIST / "_info.ini").write_text(build_info(packs), encoding="utf-8")

    merged = sum(1 for rel, owners in by_rel.items() if len(owners) > 1 and rel != "_info.ini")
    print(f"built {DIST.relative_to(ROOT)}: {len(staged) + 1} files from "
          f"{len(packs)} packs ({merged} colliding paths merged)")


if __name__ == "__main__":
    main()
