# Basada en el fichero eu_am_cal_27mm.ini de EuroMod, y personalizada para EF200 Español.
# ver. 20260506
#
[General]
Type=Projectile            				// Can be Projectile, Missile, Torpedo
TargetType=AAW             				// Can be AAW, ASuW, ASW
SecondaryTargetType=ASuW

Mass=0.516                              // In kg. Used for aircraft
AmmoPoints=0.516                       	// For Supply System. Defines "price" of ammunition based on mass, volume, complexity and availability

DecalClass=GunImpacts      				// Referenced in effects/decals.ini

[Physics]
MuzzleVelocity=1100        				// Meter per second
MaxRange=2500              				// In m
CircularErrorProbable=3.75				// Radius in meters at max range for shells to impact
										// A una distancia de combate estándar de 1.000 metros, mantiene un CEP de aproximadamente 1 a 2 milirradianes.
[---------- Warhead Data ----------]
[WarheadData]
Power=1
# ImpactSize=Tiny            				// Impact size, can be small, medium, large, verylarge
ImpactSize=Small           				// Impact size, can be small, medium, large, verylarge
Penetration=Minor          				// Can be minor, moderate, heavy, always

[---------- Effects ----------]
[Particles]
TrailEffect=
HitShipExplosion=effects/Particle Emitters/impact_small_shell_multi
HitAirExplosionClass=SmallFlakExplosions
HitWaterSplashClass=SmallWaterSplashes