#!alias ammunition/usaf_tank_600_f-4e.ini
# ver. 20260413
#
[General]
Fuel=1249

[Models]
ResourcesFolder=aircraft/spa_f-18a/
ResourcesRoot=spa_f-18a.obj
ResourcesMesh=330gal_fuel_tank
ResourcesMaterialFolder=aircraft/spa_f-18a/
ResourcesMaterial=spa_f-18a_mat.ini
