[Animations]
NumberOfAnimations=2

Animation1=HangarLeftOpenAnim
Animation2=HangarLeftCloseAnim

##########################################################################


[HangarLeftOpenAnim]
NumberOfSequencesToPlay=4
Sequence1=Door_Up_1
Sequence1_Model=HangarDoor

[HangarLeftCloseAnim]
NumberOfSequencesToPlay=4
Sequence1=Door_Down_1
Sequence1_Model=HangarDoor

[------------------------------ Sequences ------------------------------]

[Door_Up_1]
NumberOfSteps=2
Step1=0|x,0.139,-0.675|0,y,z|Linear
Step2=4|x,0.157,-0.675|80,y,z|Linear

[Door_Down_1]
NumberOfSteps=2
Step1=0|x,0.157,-0.675|80,y,z|Linear
Step2=4|x,0.139,-0.675|0,y,z|Linear
