# Splat map color channels:
#
#_SplatMap
#Red: Barren Ground
#Green: Vegetation Density
#Blue: Farmland Density
#Alpha: Permanent Snow
#
#_SplatMap_2
#Red: Urban Density
#Green: Water Bodies
#Blue: Global Snowline
#Alpha:

[General]
MaxParallelLoadingJobs=32
MaxParallelVegetationJobs=16
InterpolationMethod=InverseDistanceWeighted  // possible: Bilinear, InverseDistanceWeighted
IDWPower=2.0                  // power value for inverse distance weight (0.5 ... 3.0 could make sense)
ChunksViewDistance=4
UseGaussianFilter=True
GaussRadius=2
MinHeightForFilter=-100
MaxHeightForFilter=100
ApplyNoise=False
NoiseStrength=0.1             // multiplicator for the strength (map value is used as: newHeight = oldHeight + strength * (value - 128) / 128
NoiseMinHeight=10.0           // in meter, below this there won't be noise added (to avoid artefacts)
MinHeightForLandUnits=1.0     // for placed land units we assume that minimum height to avoid underwater placements
CastShadows=False
ReceiveShadows=True
DefaultFolderForPrefabs=scenery/0_Prefabs
DefaultFileForPrefabs=SceneryPrefabs

[Vegetation]
AddVegetation=True
NumberOfTexturesPerRow=2
TreeBaseSize=0.2
TreeSizeRandomize=0.05
TreeShadingRandomize=0.25
UWVegBaseSize=0.2
UWVegSizeRandomize=0.05
MinHeight=3.0
UWMinDepth=-20               // min depth in m where the underwater vegetation starts
MaxSlope=90.0
MinSplatDensity=32            // should be between 0...255 to define the lower bound to calculate the density from the green channel of the splat map
MaxSplatDensity=64          // should be between 0...255 to define the upper bound to calculate the density from the green channel of the splat map
AverageSplatDensity=False	//True      // if true, neighbor pixels are taken into account to avoid blocky look
VegetationSplatThreshold=80  // when splatmap2.g > threshold, no trees are placed
HedgerowThreshold=128        // when splatmap.b > threshold, use the cropland mask to generate hedgerows
HedgerowTiling=3
HedrerowRandomDelta=0.05
CullingDistance=450.0
UWCullingDistance=450.0
FadingDistance=450.0
CastShadows=True
ReceiveShadows=False

[DebugVegetation]
Enabled=False
UseSplatVegetationMasks=False  // splat 1 green channel
UseSplatLakeMasks=True        // splat 2 green channel
UseHedgerowsEverywhere=False  // flag if hedgerows shall be placed everywhere, ignoring the splat
UseVegetationDistributionMask=False
UseWaterMask=False

[Shorelines]
ShoreLevel=0.0
ShoreHeightSpread=20.0
ShoreHeightAlpha=1.0

[TerrainPainter]
NumberOfStampTextures=14
StampTexture1=stamp_all
StampTexture2=TestStamp1
StampTexture3=TestStamp2
StampTexture4=stamp_circular_small_soft
StampTexture5=stamp_circular_small
StampTexture6=stamp_circular_hard
StampTexture7=stamp_32x16
StampTexture8=stamp_32x32
StampTexture9=stamp_64x32
StampTexture10=stamp_bergen_49
StampTexture11=stamp_harbour_1
StampTexture12=stamp_harbour_large
StampTexture13=stamp_rota_2
StampTexture14=stamp_rota_water
SplatWaterColor=0
SplatWaterFallOffColor1=85
SplatWaterFallOffColor2=113
SplatLandColor=130

[stamp_all]
TextureFile=stamp_all.png

[TestStamp1]
TextureFile=test_32.png

[TestStamp2]
TextureFile=test_32_2.png

[stamp_circular_small_soft]
TextureFile=stamp_circular_small_soft.png

[stamp_circular_small]
TextureFile=stamp_circular_small.png

[stamp_circular_hard]
TextureFile=stamp_circular_hard.png

[stamp_32x16]
TextureFile=stamp_32x16.png

[stamp_32x32]
TextureFile=stamp_32x32.png

[stamp_64x32]
TextureFile=stamp_64x32.png

[stamp_bergen_49]
TextureFile=stamp_bergen_49.png

[stamp_harbour_1]
TextureFile=stamp_harbour_1.png

[stamp_harbour_large]
TextureFile=stamp_harbour_large.png

[stamp_rota_2]
TextureFile=stamp_rota_2.png

[stamp_rota_water]
TextureFile=stamp_rota_water.png