[Language_en]
Name=Kirov-class (Pyotr Velikiy Upgrade)
Description=This mod adds the remaining Kirov-class vessels upgraded to the Pyotr Velikiy configuration, including Kortik/Kashtan CIWS, SA-N-9 VLS launchers, and the AK-130 gun.

[Compatibility]
;ApproximateVersion is the second check and will override all statements below. This checks MAJOR and MINOR match but will accept higher PATCH.
;Would recommend this as a default case for starters.
ApproximateVersion=0.8.0