[General]
HullnumberReference=Hullnumber
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfVariants=3

[Default]
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_prc
Nation=China

[Variant1]
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=wp_cv_012
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/wp_cv_orel/
LiveryTexture=wp_cv_orel_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_prc
Nation=China

CustomAirGroup=True
#wp_mig-23a=Squadron1,12|Squadron2,12
#wp_taifun=Squadron1,12
#wp_p-42_rldn=Squadron1,4
#wp_taifun_ew=Squadron1,4
#wp_p-42=Squadron1,6
#wp_ka-27=Squadron6,8
plan_j-15a=Squadron1,12|Squadron2,12
plan_kj-600a=Squadron1,4
plan_z-18f=Squadron1,6
plan_z-18j=Squadron1,6