[AmmunitionNames]
# ------------------ AAM ------------------

# ------------------ SAM ------------------

usa_fim-92=FIM-92,Stinger,SAM,

# ---------- Anti-radar Missiles ---------

# ---------- Anti-ship Missiles ----------

#-----------Land Strike only missiles---------

# ---------- Anti-sub  Missilies ----------

# ------------------ RBU ------------------

# --------------- Torpedoes ---------------

# ------------------ Bombs -----------------

# ---------------- Sonobuoys ---------------

# ------------------ FFAR -----------------

# ------------------ MLRS -----------------

# ------------------ Guns -----------------

wp_3ubr6=3UBR6,,AP
wp_pg-15v=PG-15V,,HEAT,
wp_og-15v=OG-15V,,HE,

usa_cal_60mm=60mm,,Mortar,
# ------------------ CIWS -----------------

# ----------- Noisemakers/Chaff -----------

# ----------------- Decoys ----------------

# ----------------- Special ----------------

# Depth charge

# ----------------- Fueltanks ----------------


