[General]
UnitType=LandUnit
HideIn=Encyclopedia,MissionEditor,Signatures
LandUnitSubType=Port
MaskVegetation=False

DefaultCameraDistance=18.0
MinCameraDistanceForeAft=18
MinCameraDistanceBroadside=18
CameraPivotHeight=0.15

# Hull armor: None, Minor, Moderate, Heavy
ArmorType=None
DamagePoints=400  //systems damage contribution substracted from this when systems destroyed, when becomes less than zero, the whole unit is considered being destroyed

[AI]
UnitScoreValue=10              // value for calculation of mission score
Role=Port

[SensorData]
#Visual
VisualIdentificationRange=15.0  // Biggest range in nm at which this unit can be visually identified
IRSignature=Large
# Radar related (RCS => radar cross section)
RCS=SemiSmall
# Sonar related
BaseNoise=150                   // base sound level in db at 1m distance
FlowNoise=1                     // additional flow noise per knot in db (20kn would be +20db)
CavitationNoise=5               // additional noise for cavitation in db

[---------- Main Systems ----------]
[SensorSystems]
#Presence of this section allows object to be detectable
NumberOfSensorSystems=1
#---------- Visual ----------
[SensorSystem1] #
Type=Visual
SystemName=Optics
MountPosition=0,0.175,0

[--------------------------- Mesh definitions ---------------------------]
[Models]
############################################################
# Internal Resources folder related
############################################################

ResourcesFolder=scenery/modular_ports/
ResourcesRoot=modular_ports
ResourcesMesh=False
ResourcesMaterialFolder=scenery/modular_ports/
ResourcesMaterial=modular_ports_mat


[---------- Effects ----------]
[Particles]
SmallFireEffectClass=SmallShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=ModerateShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=SevereShipFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffect=effects/explosions/emitters/missile_hit_ship
SecondaryExplosionEffectPosition=0,0,0
[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=1
