[Animations]
NumberOfAnimations=48
Animation1=Mk56_hatch_1_1_Open
Animation2=Mk56_hatch_1_2_Open
Animation3=Mk56_hatch_1_3_Open
Animation4=Mk56_hatch_1_4_Open
Animation5=Mk56_hatch_1_5_Open
Animation6=Mk56_hatch_1_6_Open
Animation7=Mk56_hatch_1_7_Open
Animation8=Mk56_hatch_1_8_Open
Animation9=Mk56_hatch_1_9_Open
Animation10=Mk56_hatch_1_10_Open
Animation11=Mk56_hatch_1_11_Open
Animation12=Mk56_hatch_1_12_Open
Animation13=Mk56_hatch_2_1_Open
Animation14=Mk56_hatch_2_2_Open
Animation15=Mk56_hatch_2_3_Open
Animation16=Mk56_hatch_2_4_Open
Animation17=Mk56_hatch_2_5_Open
Animation18=Mk56_hatch_2_6_Open
Animation19=Mk56_hatch_2_7_Open
Animation20=Mk56_hatch_2_8_Open
Animation21=Mk56_hatch_2_9_Open
Animation22=Mk56_hatch_2_10_Open
Animation23=Mk56_hatch_2_11_Open
Animation24=Mk56_hatch_2_12_Open
Animation25=Mk56_hatch_3_1_Open
Animation26=Mk56_hatch_3_2_Open
Animation27=Mk56_hatch_3_3_Open
Animation28=Mk56_hatch_3_4_Open
Animation29=Mk56_hatch_3_5_Open
Animation30=Mk56_hatch_3_6_Open
Animation31=Mk56_hatch_3_7_Open
Animation32=Mk56_hatch_3_8_Open
Animation33=Mk56_hatch_3_9_Open
Animation34=Mk56_hatch_3_10_Open
Animation35=Mk56_hatch_3_11_Open
Animation36=Mk56_hatch_3_12_Open
Animation37=Mk56_hatch_4_1_Open
Animation38=Mk56_hatch_4_2_Open
Animation39=Mk56_hatch_4_3_Open
Animation40=Mk56_hatch_4_4_Open
Animation41=Mk56_hatch_4_5_Open
Animation42=Mk56_hatch_4_6_Open
Animation43=Mk56_hatch_4_7_Open
Animation44=Mk56_hatch_4_8_Open
Animation45=Mk56_hatch_4_9_Open
Animation46=Mk56_hatch_4_10_Open
Animation47=Mk56_hatch_4_11_Open
Animation48=Mk56_hatch_4_12_Open

####### Mk56 Block 1 #######
[Mk56_hatch_1_1_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_1_1

[Mk56_hatch_1_2_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_1_2

[Mk56_hatch_1_3_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_1_3

[Mk56_hatch_1_4_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_1_4

[Mk56_hatch_1_5_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_1_5

[Mk56_hatch_1_6_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_1_6

[Mk56_hatch_1_7_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_1_7

[Mk56_hatch_1_8_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_1_8

[Mk56_hatch_1_9_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Close
Sequence1_Model=mk56_vls_hatch_1_9

[Mk56_hatch_1_10_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Close
Sequence1_Model=mk56_vls_hatch_1_10

[Mk56_hatch_1_11_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Close
Sequence1_Model=mk56_vls_hatch_1_11

[Mk56_hatch_1_12_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Close
Sequence1_Model=mk56_vls_hatch_1_12


####### Mk56 Block 2 #######

[Mk56_hatch_2_1_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_2_1

[Mk56_hatch_2_2_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_2_2

[Mk56_hatch_2_3_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_2_3

[Mk56_hatch_2_4_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_2_4

[Mk56_hatch_2_5_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_2_5

[Mk56_hatch_2_6_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_2_6

[Mk56_hatch_2_7_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_2_7

[Mk56_hatch_2_8_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_2_8

[Mk56_hatch_2_9_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Close
Sequence1_Model=mk56_vls_hatch_2_9

[Mk56_hatch_2_10_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Close
Sequence1_Model=mk56_vls_hatch_2_10

[Mk56_hatch_2_11_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Close
Sequence1_Model=mk56_vls_hatch_2_11

[Mk56_hatch_2_12_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Close
Sequence1_Model=mk56_vls_hatch_2_12

####### Mk56 Block 3 #######

[Mk56_hatch_3_1_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_3_1

[Mk56_hatch_3_2_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_3_2

[Mk56_hatch_3_3_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_3_3

[Mk56_hatch_3_4_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_3_4

[Mk56_hatch_3_5_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_3_5

[Mk56_hatch_3_6_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_3_6

[Mk56_hatch_3_7_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_3_7

[Mk56_hatch_3_8_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_3_8

[Mk56_hatch_3_9_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Close
Sequence1_Model=mk56_vls_hatch_3_9

[Mk56_hatch_3_10_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Close
Sequence1_Model=mk56_vls_hatch_3_10

[Mk56_hatch_3_11_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Close
Sequence1_Model=mk56_vls_hatch_3_11

[Mk56_hatch_3_12_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Close
Sequence1_Model=mk56_vls_hatch_3_12

####### Mk56 Block 4 #######

[Mk56_hatch_4_1_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_4_1

[Mk56_hatch_4_2_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_4_2

[Mk56_hatch_4_3_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_4_3

[Mk56_hatch_4_4_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_4_4

[Mk56_hatch_4_5_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_4_5

[Mk56_hatch_4_6_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_4_6

[Mk56_hatch_4_7_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_4_7

[Mk56_hatch_4_8_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Open
Sequence1_Model=mk56_vls_hatch_4_8

[Mk56_hatch_4_9_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Close
Sequence1_Model=mk56_vls_hatch_4_9

[Mk56_hatch_4_10_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Close
Sequence1_Model=mk56_vls_hatch_4_10

[Mk56_hatch_4_11_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Close
Sequence1_Model=mk56_vls_hatch_4_11

[Mk56_hatch_4_12_Open]
NumberOfSequencesToPlay=1
Sequence1=VLS_Cell_Close
Sequence1_Model=mk56_vls_hatch_4_12
[------------------------------ Sequences ------------------------------]
[VLS_Cell_Open]
NumberOfSteps=2
Time1=0
Position1=x,y,z
Smoothness1=EaseInOut
Time2=0.1
Position2=x,-10,z
Smoothness2=EaseInOut

[VLS_Cell_Close]
NumberOfSteps=2
Time1=0
Position1=x,y,z
Smoothness1=EaseInOut
Time2=0.1
Position2=x,-10,z
Smoothness2=EaseInOut
