[AmmunitionNames]
# ------------------ AAM ------------------
usn_aim-9x=AIM-9X,Sidewinder,AAM,The AIM-9X Sidewinder is an American infrared-guided air-to-air missile. The X-model has been significantly upgraded, with strong anti-jam capabilities, a longer range, and an impressive backwards firing capability.

usaf_aim-120d=AIM-120D,AMRAAM,AAM,AIM-120 is an active radar-guided air-to-air missile of the United States, used to replace the old Sparrow semi-active radar-guided air-to-air missile. It is relatively small and can be carried by most aircraft.

idaf_python5=Python 5,,AAM,The Python 5 is the most powerful infrared air-to-air missile currently in the Israeli Air Force's inventory, with strong anti-interference capabilities and backward firing capabilities.

idaf_derby=I-Derby ER,,AAM,The I-Derby ER is an Israeli active radar-guided beyond-visual-range air-to-air missile featuring a dual-pulse rocket motor, mid-course datalink updates and advanced ECCM capabilities. It provides long-range engagement capability while retaining high effectiveness against maneuvering targets and electronic countermeasures.

# ------------------ SAM ------------------

# ---------- Anti-radar Missiles ---------

# ---------- Anti-ship Missiles ----------

f16_agm-158c-3=AGM-158C-3,LRASM-ER,ASM,The AGM-158C-3 is the latest variant of Lockheed Martin’s AGM-158C Long Range Anti-Ship Missile (LRASM), developed for the U.S. Air Force and Navy. It features extended range, enhanced cooperative engagement capabilities, and improved stealth penetration. it can be launched from platforms including the B-1B, F/A-18E/F, and F-15EX.

agm-84l=AGM-84L,Harpoon,ASM,The AGM-84L Harpoon Block II is a modernized American standoff anti-ship and land-attack missile widely used by NATO allies. Upgraded with an advanced GPS/INS integrated navigation system, it features a dual-role capability to strike both ships in open waters and static coastal targets. The weapon utilizes a high-resolution active radar seeker with heavily buffed ECCM capabilities to burn through modern naval jammers. It follows a highly flexible, ultra-low sea-skimming flight profile and supports tactical data-link mid-course corrections, making it a premier stand-off strike weapon of the 2000s.


#-----------Land Strike only missiles---------

# ---------- Anti-land  Missilies ----------

usn_agm-65d=AGM-65D,Maverick,AGM,The AGM-65D is a US infrared-guided standoff air-to-ground weapon that can lock onto targets in adverse environments. It is used in a similar manner to the AGM-62, with the operator at the launch platform directing the crosshairs toward the desired target for guidance.

usn_agm-88=AGM-88,HARM,ARM,AGM-88 is an airborne high-speed anti-radiation missile equipped by the U.S. Navy and Air Force. Its English abbreviation HARM is used to suppress and destroy the guidance radar, target indication radar and anti-aircraft gun aiming radar of enemy ground and ship-based air defense missile systems.

usaf_gbu-24=GBU-24,Paveway III,AGM,The GBU-24 has a longer glide range than the GBU-10 or Type II series due to the use of more efficient guidance technology. However, the Type III guidance kit is more expensive, making the GBU-24 more suitable for engaging heavily defended high-value targets.

f16_agm-158b-2=AGM-158B-2,JASSM-ER,Land Attack,Developed by Lockheed Martin. The AGM-158B-2 JASSW-ER is a stealthy extended-range cruise missile powered by a turbofan engine with a range exceeding 1,900km. Equipped with inertial navigation+GPS+infrared imaging terminal guidance and a 454kg warhead, it features an upgraded GPS receiver and anti-jamming software, enabling standoff strikes against high-value targets and compatible with multiple fighters.

tuaf_som-j=SOM-J,SOM,ASM,The SOM-J is a next-generation Turkish stealth cruise missile developed by TÜBİTAK SAGE and Roketsan. Specifically downsized for integration into internal weapon bays and modern tactical pylons, this autonomous stand-off weapon is optimized for anti-surface warfare (ASuW) and deep-strike missions. Guided by an advanced GPS/INS mid-course system with terrain-referenced navigation, it features a high-resolution Imaging Infrared (IIR) terminal seeker for precise target selection. Operating on a highly survivable, ultra-low sea-skimming profile with a reduced radar cross-section, the SOM-J provides a highly agile, low-observable strike capability against heavily defended naval and coastal assets.

scalp-eg=SCALP EG,Storm Shadow,ASM,The Storm Shadow is an Anglo-French, low-observable air-launched cruise missile (known as SCALP-EG in France) manufactured by MBDA. Designed to destroy hardened bunkers and key infrastructure, it carries a 1 million dual-charge warhead and boasts a range of over 250 km (155 miles).

# ------------------ RBU ------------------
# --------------- Torpedoes ---------------
# ------------------ Bombs -----------------

f16_gbu-31=GBU-31,JDAM,Guided Bomb,The GBU-31 is an American 2000lb GPS-guided Bomb.

us_gbu-31v3=GBU-31(V)3/B,JDAM,Bunker Buster,The GBU-31(V)3/B is an American 2000lb GPS-guided Penetrator Bomb designed to destroy hardened concrete targets.

f16_gbu-32=GBU-32,JDAM,Guided Bomb,The GBU-32 is an American 1000lb GPS-guided Bomb.

f16_gbu-53=GBU-53/B,SDB II,Guided Bomb,The GBU-53/B StormBreaker, developed by Raytheon, is the U.S. military’s second-generation small-diameter precision-guided glide bomb. It features foldable wings and a maximum range of 110km. Its core strength lies in the tri-mode seeker (millimeter-wave radar, infrared imaging, semi-active laser) and encrypted two-way data link, enabling all-weather, anti-jamming strikes against stationary and moving targets (tanks, ships, etc.)

usaf_gbu-54=GBU-54,LJDAM,Guided Bomb,The GBU-54 Laser Joint Direct Attack Munition (LJDAM) is a 500-lb dual-mode precision-guided bomb. Developed by Boeing, it combines the all-weather GPS/INS navigation of a standard JDAM with a semi-active laser seeker, allowing aircraft to precisely strike both static and fast-moving targets.

f16_gbu-39=GBU-39,SDB,Guided Bomb,The GBU-39 Small Diameter Bomb (SDB) adopts GPS/INS composite guidance, with a hit accuracy of less than 5 meters and a range of over 110 kilometers, and is capable of penetrating 90-centimeter-thick reinforced concrete structures

f16_agm-154c=AGM-154C,JSOW,Land Attack,Land Attack,The AGM-154C is a GPS/INS-guided stand-off glide weapon with an imaging infrared terminal seeker. It carries a 500 lb BROACH penetrator warhead for precision attacks against hardened structures, bunkers, airfield facilities and other high-value fixed targets. Range is approximately 28 km at low altitude and over 100 km when released from high altitude.

idaf_spice-2000=Spice-2000,Land Strike,Spice-2000 is an Israeli standoff guided bomb system. Derived from the AGM-142 Popeye, it features a sophisticated dual-mode guidance: GPS/INS for autonomous fire-and-forget capability, and an Electro-Optical (EO) man-in-the-loop seeker for terminal precision. Designed to neutralize high-value hardened targets from significant standoff ranges.

idaf_spice-1000=Spice-1000,Land Strike,Spice-1000 is an advanced medium-weight precision-guided munition. Utilizing the same battle-proven dual-mode guidance (GPS/INS + Electro-Optical) as the Spice-2000, it is optimized for high-volume strike missions against soft to medium-hardened targets. Its modular design allows F-16 configurations to carry a larger payload, providing a lethal balance of standoff range, surgical precision, and tactical flexibility.

# ---------------- Sonobuoys ---------------
# ------------------ FFAR -----------------
# ------------------ MLRS -----------------
# ------------------ Guns -----------------
# ------------------ CIWS -----------------
# ----------- Noisemakers/Chaff -----------
# ----------------- Decoys ----------------
# ----------------- Special ----------------
f16_anaaq-13=AN/AAQ-13,LANTIRN,Targeting Pod

f16_anaaq-33=AN/AAQ-33,Sniper,Advanced Targeting Pod

usaf_litening=AN/AAQ-28,Litening,Targeting Pod

usaf_anasq-213=AN/ASQ-213,HARM Targeting System,Targeting Pod

# ----------------- Fueltanks ----------------
usaf_tank_370_f16=F-16 370 gal Tanks,,Fuel Tank

usaf_tank_300_f16=F-16 300 gal Tanks,,Fuel Tank

usaf_cft_f16=F-16 Conformal Fuel tank,,Fuel Tank

usaf_tank_600_f16=F-16 600 gal Tanks,,Fuel Tank