[LoadoutNames]
#------------------------------------------ New system ------------------------------------------
# ---------- Mandatory loadouts ----------
StrikeJSOW=Strike JSOW
StrikeJASSM=Strike JASSM
StrikeSDB=Strike SDB
StrikeSDBECM=Strike SDB + ECM
StrikeStormBreaker=Strike StormBreaker
StrikeStormBreakerECM=Strike StormBreaker + ECM
StrikeLongRangeHeavy=Strike Long Range Heavy
StrikeBunkerBuster=Strike Bunker Buster
StrikeLongRangeHeavyCFT=Strike Long Range Heavy + CFT
StrikeJASSMCFT=StrikeJASSM + CFT
AntiShipLRASM=Anti Ship LRASM
SEADECM=SEAD + ECM
SEADHeavy=SEAD Heavy
AirToAirVLongRange=Air To Air VeryLongRange
AirToAirSuperiority=Air To Air Superiority
StrikeLongRangeJDAM=Strike Long Range (JDAM)
StrikeHeavyJDAM=Strike Heavy (JDAM)
StrikeLongRangeHeavyJDAM=Strike Long Range Heavy (JDAM)
StrikeBunkerBusterJDAM=Strike Bunker Buster (JDAM)
StrikeHardTargetJDAM=Strike Hard Target (JDAM)
DEAD=DEAD
DEADECM=DEAD + ECM
DEADECMAgile=DEAD + ECM (Agile)
DEADECMHeavy=DEAD + ECM (Heavy)
StrikeLaserJDAM=Strike LJDAM (GBU-54)
StrikeLaserJDAMECM=Strike LJDAM (GBU-54) + ECM
StrikeSPICE1000=Strike SPICE(1000)
StrikeSPICE1000Heavy=Strike SPICE(1000) Heavy
StrikeSPICE2000=Strike SPICE(2000)
StrikeSOMJ=Strike (SOM-J)
StrikeStormShadow=Deep Strike (STORM SHADOW)