[General]

############################################ U S A ############################################

[-------------------------- 战斗机 --------------------------]
[-------------------------- 攻击机 --------------------------]
[-------------------------- 轰炸机 --------------------------]
[-------------------------- 电子战 --------------------------]
[-------------------------- 直升机 --------------------------]
[-------------------------- 运输机 --------------------------]
[-------------------------- 炮艇 --------------------------]
[usaf_ac-130a]
Type=炮艇
Default=AC-130A,AC-130A
DefaultDescription=AC-130是美国基于C-130运输机研发而来的对地攻击机,其体型庞大速度慢，在敌人拥有一定防空火力时很容易被击落，但在拥有绝对制空权的情况下，将会是地面部队的噩梦。
Squadron1=AC-130A（第4特种作战中队）,AC-130A
Callsigns=Squadron1,幽灵

[usaf_ac-130h]
Type=炮艇
Default=AC-130H,AC-130H
DefaultDescription=AC-130是美国基于C-130运输机研发而来的对地攻击机,其体型庞大速度慢，在敌人拥有一定防空火力时很容易被击落，但在拥有绝对制空权的情况下，将会是地面部队的噩梦。
Squadron1=AC-130H（第16特种作战中队）-精神-03,精神-03
Squadron2=AC-130H（第16特种作战中队）-夜行者,夜行者
Squadron3=AC-130H（第16特种作战中队）-石中剑,石中剑
Squadron4=AC-130H（第16特种作战中队）-荡妇,荡妇
Squadron5=AC-130H（第16特种作战中队）-掘墓者,掘墓者
Squadron6=AC-130H（第16特种作战中队）-重金属,重金属
Squadron7=AC-130H（第16特种作战中队）-铁娘子,铁娘子
Squadron8=AC-130H（第16特种作战中队）-邪恶旺达,邪恶旺达
Squadron9=AC-130H（第16特种作战中队）-捕食者,捕食者
Squadron10=AC-130H（第16特种作战中队）-死亡天使,死亡天使

Callsigns=Squadron1,精神-03|Squadron2,夜行者|Squadron3,石中剑|Squadron4,荡妇|Squadron5,掘墓者|Squadron6,重金属|Squadron7,铁娘子|Squadron8,邪恶旺达|Squadron9,捕食者|Squadron10,死亡天使

[usaf_ac-130a_83]
Type=炮艇
Default=AC-130A(1983),AC-130A(1983)
DefaultDescription=AC-130是美国基于C-130运输机研发而来的对地攻击机,其体型庞大速度慢，在敌人拥有一定防空火力时很容易被击落，但在拥有绝对制空权的情况下，将会是地面部队的噩梦。
Squadron1=AC-130A（第711特种作战中队）-恶灵骑士,恶灵骑士
Squadron2=AC-130A（第711特种作战中队）-死神,死神
Squadron3=AC-130A（第711特种作战中队）-暗夜骑士,暗夜骑士
Squadron4=AC-130A（第711特种作战中队）-死亡之颚,死亡之颚
Squadron5=AC-130A（第711特种作战中队）-终局,终局

Callsigns=Squadron1,恶灵骑士|Squadron2,死神|Squadron3,暗夜骑士|Squadron4,死亡之颚|Squadron5,终局

[usaf_ac-130j]
Type=炮艇
Default=AC-130J,AC-130J
DefaultDescription=AC-130是美国基于C-130运输机研发而来的对地攻击机,其体型庞大速度慢，在敌人拥有一定防空火力时很容易被击落，但在拥有绝对制空权的情况下，将会是地面部队的噩梦。
Squadron1=AC-130J（第4特种作战中队）,AC-130J
Callsigns=Squadron1,恶灵骑士

############################################ U K ############################################
[-------------------------- 战斗机 --------------------------]
[-------------------------- 轰炸机 --------------------------]
[-------------------------- 攻击机 --------------------------]
[-------------------------- 运输机 --------------------------]
############################################ I T A L Y ############################################
############################################ F R A N C E ############################################
############################################ S A U D I A R A  B I A ############################################
############################################ I R A Q ############################################


