#Dot: This file begs for refactor...
[LanguageResources]
#---------- Movement&Control----------
#---------- Sensors ----------
#---------- Weapons ----------
#---------- Magasines ----------
#---------- Decoys&Other ----------
#---------- Land Unit hit zones ------------

[SystemNames]
# ***********************************************************************************************
#                                          Main SYSTEMS
# ***********************************************************************************************
# ***********************************************************************************************
#                                          Sensor SYSTEMS
# ***********************************************************************************************
#======================================== Generic ========================================
#---------------------------------------- Visual ----------------------------------------

#---------------------------------------- Radar ----------------------------------------
AN/APG-66=AN/APG-66|F-16A使用的使用的多模机载雷达,多用于早期F-16A。

AN/APG-70=AN/APG-70|是F-15E使用的多模机载雷达，由AN/APG-63改进而来。

AN/APQ-150=AN/APQ-150|是AC-130使用的地面扫描雷达。

AN/APQ-122=AN/APQ-122|AN/APQ-122是一款双频雷达，可用作远程导航传感器，用于规避天气和导航。

#---------- Surface ships ----------
#---Air/Air&Surface---
#---Surface only---
#---Fire Control---
#SAM
#Guns
AC-130_40mm=博福斯40毫米机炮
AC-130_20mm=20毫米M61火神
#---------- Submarines ----------
#---------------------------------------- Aircraft radar ----------------------------------------
#---------- Containers ----------
#---------------------------------------- Sonar ----------------------------------------
#Towed
#Dipping
#---------------------------------------- ESM ----------------------------------------
#---------------------------------------- ECM ----------------------------------------
#---------------------------------------- MAD ----------------------------------------
#---------------------------------------- Laser Designator ---------------------------

#============================================ France ===========================================
#---------------------------------------- Radar ----------------------------------------
#---------------------------------------- Sonar ----------------------------------------
#---------------------------------------- ESM ----------------------------------------
#---------------------------------------- ECM ----------------------------------------
#============================================ Israel ===========================================
#---------------------------------------- Radar ----------------------------------------
#---------- Surface ships ----------
#---Air/Air&Surface---

#---Surface only---
#---Fire Control---
#---------------------------------------- ESM ----------------------------------------
#---------------------------------------- ECM ----------------------------------------
#======================================== United States ========================================
#---------------------------------------- Visual ----------------------------------------
#---------------------------------------- Radar ----------------------------------------
#---------- Surface ships ----------
#---Air/Air&Surface---

#---Surface only---
#---Fire Control---
#SAM
#Guns

#---------- Submarines ----------

#---------------------------------------- Aircraft radar ----------------------------------------

#---------------------------------------- Land units radar ----------------------------------------
#---Air/Air&Surface---
#---Surface only---

#---Fire Control---
#---------------------------------------- Sonar ----------------------------------------

#---------- Submarines ----------

#Towed

#Dipping

#Sonobuoys
#---------------------------------------- ESM ----------------------------------------
#---------------------------------------- ECM ----------------------------------------
#---------------------------------------- MAD ----------------------------------------
#---------------------------------------- Laser Designator ---------------------------
#======================================== Soviet Union ========================================
#---------------------------------------- Radar ----------------------------------------
#---------- Surface ships ----------]
#---Air/Air&Surface---
#---Surface only---

#---Fire Control---
#SAM

#ASM

#Guns

#CIWS

#---------- Submarines ----------

#---------- Land Units ----------
#---Fire Control---

#---------------------------------------- Aircraft Radar ----------------------------------------
#Air/Air&Surface

#Surface only

### Sonar
#---------------------------------------- Sonar ----------------------------------------
#---------- Surface ships ----------
#----- Towed/VDS -----

#---------- Submarines ----------

#----- Towed/VDS -----

#Designation		NATO				Type		Modes			Max Range, Km	Depth, m
#Tamir-11L			Stag Ear			Bow			Active			2-2.5A, 11P
#Mars				Perch Gill			Bow			Passive			1-18
#MG-10 Feniks-M		Trout Cheek			Bow			Passive			1-7
#MG-200 Arktika-M 	Pike Jaw			Bow			Active			1-18
#MGK-100 Kerch		Shark Teeth			Bow			Active/Passive	1-20A
#MGK-300 Rubin 		Shark Teeth			Bow			Active/Passive	1-60A
#MGK-1000 Okean 	Squid Arm			Bow			Active/Passive	1-60A
#MGK-400 Rubikon 	Shark Gill			Bow			Active/Passive	1-200
#MGK-500 Skat 		Shark Gill			Bow			Active/Passive	1-200
#MG-541 Pelmida		Shark Tail			Towed		Passive			1-200
#Tamir-11L			Stag Ear			Keel		Active			2.5A		
#Pegas-2M			Buck Toe			Keel		Active/Passive	2-3A, 18P
#Herkules-2M		Wolf Paw			Keel		Active/Passive	2-4A, 18P
#MG-311 Vychegda 	Wolf Paw			Keel		Active/Passive	2-4
#MG-312 Titan 		Bull Nose			Keel		Active/Passive	1-5
#MG-332 Titan-2 	Bull Nose			Bow			Active/Passive	2-10
#MGK-335 Platina 	Bull Nose			Bow			Active/Passive	2-15
#MGK-342 Orion 		Moose Jaw			Bow			Active			2-30
#MGK-355 Polinom 	Horse Jaw			Bow			Active/Passive	2-40
#MGK-355 Polinom 	Horse Tail			Towed		Active/Passive	2-40
#MG-325 Vega		Mare Tail			Towed		Active/Passive	2-15
#MG-329 Shelon		Foal Tail			Towed		Active/Passive	2-15
#MGK-345 Bronza		Ox Tail				Towed		Active/Passive	2-6

#---------- Aircraft ----------

#---------- Sonobuoys ----------

#---------------------------------------- Visual/Infared ----------------------------------------
#---------------------------------------- ESM ----------------------------------------
#---------------------------------------- ECM ----------------------------------------
#---------------------------------------- MAD ----------------------------------------
#---------------------------------------- Laser Designator ---------------------------
#======================================== Royal Navy ========================================
#---------------------------------------- Radar ----------------------------------------
#Air/Air&Surface
#Surface only

#Fire Control
#---------------------------------------- ESM ----------------------------------------
#---------------------------------------- ECM ----------------------------------------

#---------------------------------------- Aircraft Radar ----------------------------------------
#Air/Air&Surface
#---------------------------------------- Sonar ----------------------------------------
#---------- Surface ships ----------


# ***********************************************************************************************
#                                          WEAPON SYSTEMS
# ***********************************************************************************************
#======================================== France ========================================
#======================================== Sweden ========================================
#======================================== United Kingdom ========================================
#======================================== United States ========================================
#---------------------------------------- Missile Launchers ----------------------------------------
#---------------------------------------- Torpedo Launchers ----------------------------------------
#********** Ships **********
#********** Submarines **********
#---------------------------------------- Land Guns ----------------------------------------

#---------------------------------------- Naval Guns ----------------------------------------

#---------------------------------------- CIWS ----------------------------------------
#---------------------------------------- Aircraft Guns ----------------------------------------
#---------------------------------------- Chaff ----------------------------------------
#---------------------------------------- Noisemaker ----------------------------------------
#======================================== Soviet Union ========================================
#---------------------------------------- Missile Launchers ----------------------------------------
#Navy SAM
#Surface SAM
#---------------------------------------- Torpedo Launchers ----------------------------------------
#********** Ships **********
#********** Submarines **********
#---------------------------------------- RBU ----------------------------------------
#---------------------------------------- Land Guns ----------------------------------------
#---------------------------------------- Naval Guns ----------------------------------------
#---------------------------------------- CIWS ----------------------------------------
#---------------------------------------- Aircraft Guns ----------------------------------------
#---------------------------------------- Chaff ----------------------------------------
#---------------------------------------- Noisemaker ----------------------------------------

# ***********************************************************************************************
#                                          Magazine SYSTEMS
# ***********************************************************************************************
# ------------------ SAM ------------------
# ---------- Anti-ship Missilies ----------
# ---------- Anti-sub  Missilies ----------
# ------------------ RBU ------------------
# --------------- Torpedoes ---------------

# ------------------ Guns -----------------
# ------------------ CIWS -----------------
# ----------- Noisemakers/Chaff -----------

# ***********************************************************************************************
#                                          OTHER SYSTEMS
# ***********************************************************************************************
