[General]
Type=Projectile                       // can be Projectile, Missile, Torpedo
TargetType=AAW                        // can be AAW, ASuW, ASW
SecondaryTargetType=ASuW

Mass=2.1                               // in kg. Used for aircraft
AmmoPoints=2.1                         // For Supply System. Defines "price" of ammunition based on mass, volume, complexity and availability

DecalClass=GunImpactsSmall            // referenced in effects/decals.ini

[Physics]
MuzzleVelocity=860                    // meter per second
MaxRange=4500                         // in m
GravityFactor=12
CircularErrorProbable=20              // radius in meters at max range for shells to impact

[---------- Warhead Data ----------]
[WarheadData]
Power=1.2
ImpactSize=VerySmall                       // Impact size, can be small, medium, large, verylarge
Penetration=Minor                     // can be minor, moderate, heavy, always
KillProbability=0.001                 // Chance to intercept missile. Relevant for Guns, irrelevant for CIWS
# requires direct impact to roll

[---------- Mesh definitions----------]
[Models]
ResourcesFolder=weapons/shells/
ResourcesRoot=shells_tracer_new
ResourcesMesh=shell_tiny
ResourcesMaterial=shell_mat_red

[---------- Effects ----------]
[Particles]
TrailEffect=
HitShipExplosion=effects/Particle Emitters/impact_small_shell
HitAirExplosionClass=SmallFlakExplosions
HitDefaultExplosion=effects/Particle Emitters/impact_small_shell
HitWaterSplashClass=TinyWaterSplashes
