[General]
Type=Bomb                           // can be Projectile, Missile, Torpedo
TargetType=ASuW                        // can be AAW, ASuW, ASW
HideIn=Encyclopedia,MissionEditor,Signatures

DecalClass=Standard  // referenced in effects/decals.ini
GroundDecalClass=GroundImpacts            // referenced in effects/decals.ini

[---------- Warhead Data ----------]
[WarheadData]
WarheadType=0
Power=90
ImpactSize=VeryLarge                      // Impact size, can be small, medium, large, verylarge
Penetration=Always                        // can be minor, moderate, heavy, always
Instant=True

[---------- Guidance ----------]
# Guidance Types:
# 0 = None
# 1 = IR Homing
# 2 = Semi-Active Radar Homing
# 3 = Active Radar Homing
# 4 = Anti-Radiation Homing
# 5 = Laser-Homing
# 6 = TV-Homing
# 7 = Active Sonar Homing
# 8 = Passive Sonar Homing
# 9 = Wake Homing
[Guidance]
GuidanceType=0
MidCourseCorrection=0                  // 0 = None, 1 = Radio Command, 2 = Wire Guided
InitialFlightPhaseDuration=0         // time in seconds where the missile moves straight on without guiding
#======================================== Flight Profile ===========================================================
#========================================= Launch stats ============================================================
MaxVelocity=10000.0                     // Maximum speed in knots
Acceleration=100000                     // Acceleration factor
MaxTurnRate=90.0                        // Maximum turnrate in degrees per second
MinLaunchRange=0                        // Minimum launch range in nautical miles
MaxLaunchRange=0.01                     // Maximum launch range in nautical miles
LaunchReliability=200                   // The lower the value, the greater risk of misfire or accident (0...100)
#========================================     Seeker     ===========================================================
#SelfDestruct
SelfDestructDelay=5.0                  // delay in seconds for self destruction
[---------- Mesh definitions----------]
[Models]
ResourcesFolder=weapons/rn_as_mk4/
ResourcesRoot=rn_as_mk4
ResourcesMesh=rn_as_mk4
ResourcesMaterial=rn_as_mk4_mat
############################################################

[---------- Effects ----------]
# Effects are referenced in /effects/effects.ini when using an effects class
# e.g. either:
# BoosterEffect=effects/weapons/emitters/submarine_torpedo_launch
# or
# BoosterEffectClass=BoosterEffects  // this will be referenced in effects.ini

# possible values (optionally with suffix "Class")
# BoosterEffect, InFligheEffect, UnderwaterTrail, ParachuteEffect, TorpedoSurfaceSplash, HitWaterSplash
# DebrisTrail, DebrisSplash, SmallFireEffect, ModerateFireEffect, SevereFireEffect,
# HitAirExplosion, HitShipExplosion, HitObjectExplosion, HitGroundExplosion, HitDefaultExplosion
[Particles]
InFlightEffect=None
InFlightEffectStartTime=0

HitShipExplosionClass=LargeShipHitExplosion
#HitAirExplosionClass=MediumMissileExplosions // Played when bomb explodes at water
HitDefaultExplosionClass=MediumMissileExplosions
HitWaterSplashClass=SmallWaterSplashes
HitGroundExplosionClass=LargeGroundHitExplosions

ExplosionOverwaterSplash=effects/splashes/emitters/splash_bomb

[---------- Colliders ----------]
[Colliders]
# creates the hit box for this object
Collider=coll_main

[coll_main]
Collider=Box
Position=0,0,0
Rotation=0,0,0
Scale=0.005,0.005,0.066