#=========================================================================================================================================================
#                                                  REQUIRES REMOVAL
#=========================================================================================================================================================
############################################################
# Weapons Rack
############################################################

[RackData]
//Rack Types:
//0 = Bomb
//1 = AGM
//2 = Rocket Pod
//3 = AAM

RackType=1
AttachmentType=NATO
NumWeaps=4						// Number of weapons carried
LoadLimit=150					// Maximum weight per weapon
LengthLimit=2.2					// Maximum length per weapon

[AttachmentPos001]
Position=-0.0018,0,0
Rotation=0,0,0

[AttachmentPos002]
Position=0.0018,0,0
Rotation=0,0,0

[AttachmentPos003]
Position=-0.0018,-0.004,0
Rotation=0,0,0

[AttachmentPos004]
Position=0.0018,-0.004,0
Rotation=0,0,0

############################################################
# Colliders definition
############################################################

[Colliders]
// creates the hit boxes for this object

############################################################
# Main Model with collider
############################################################

[Models]

############################################################
# AssetBundle related
############################################################

AssetBundleMeshes=/AssetBundles/StandaloneWindows/weapons
AssetBundleMaterials=/AssetBundles/StandaloneWindows/weapons
AssetBundleMesh=usmc_quad_tow
AssetBundleDamagedMesh=
AssetBundleMaterial=usn_parts
AssetBundleMeshHullCollider=usn_mer_coll
############################################################

############################################################
# Internal Resources folder related
############################################################

ResourcesFolder=weapons/usmc_quad_tow/
ResourcesRoot=usmc_quad_tow_launcher
ResourcesMesh=usmc_quad_tow
ResourcesMaterialFolder=ships/materials/
ResourcesMaterial=usn_parts
############################################################