[General]
#9М117 aka AT-10 "Sabber"
# Users: 
Type=Missile                           // can be Projectile, Missile, Torpedo
TargetType=ASuW                        // can be AAW, ASuW, ASW
LandAttackCapability=All               // can be  All, Installation, Mobile, ShoreTargetsOnly

Mass=18                                // in kg. Used for aircraft
AmmoPoints=36                          // For Supply System. Defines "price" of ammunition based on mass, volume, complexity and availability
AirLaunched=True                       // For Encyclopedia. Displays launch altitudes

DefaultCameraDistance=0.6
MinCameraDistanceForeAft=0.29
MinCameraDistanceBroadside=0.29
CameraPivotHeight=0.0

DecalClass=Standard  // referenced in effects/decals.ini

[SensorData]
#Visual
VisualIdentificationRange=4  // at what range in nm this unit can be visually identified
IRSignature=Small
# Radar related (RCS => radar cross section)
RCS=VerySmall
# Sonar related

[---------- Warhead Data ----------]
#Warhead Types:
#0 = Blast Fragmentation
#1 = Armor Piercing
#2 = HEAT
#3 = Illumination
#4 = Cluster
#5 = Runway Cratering

# Fuze Types:
# 0 = Impact Fuze
# 1 = Proximity Fuze
[WarheadData]
WarheadType=2
Power=7
ImpactSize=SemiSmall                   // Impact size, can be small, medium, large, verylarge
Penetration=Always                     // can be minor, moderate, heavy, always

[---------- Guidance ----------]
# Guidance Types:
# 0 = None
# 1 = IR Homing
# 2 = Semi-Active Radar Homing
# 3 = Active Radar Homing
# 4 = Anti-Radiation Homing
# 5 = Laser-Homing
# 6 = TV-Homing
# 7 = Active Sonar Homing
# 8 = Passive Sonar Homing
# 9 = Wake Homing
[Guidance]
GuidanceType=5
MidCourseCorrection=0                  // 0 = None, 1 = Radio Command, 2 = Wire Guided
InitialFlightPhaseDuration=2           // time in seconds where the missile moves straight on without guiding
DropDuration=1.0                       // time in seconds where the missile just falls unpropelled
TerrainFollowFlight=True
#======================================== Flight Profile ===========================================================
#flight phase 1: loft-----------------------------------------------------------------------------------------------------------------
#1st stage of missile flight - high altitude
#flight phase 2: sea skimming---------------------------------------------------------------------------------------------------------
#2nd stage of missile flight - low altitude
SeaSkimmingAlt=20                      // height in feet for sea skimming
#flight phase 3: final flight phase (e.g. terminal popup)------------------------------------------------------------------------------
#Pop-Up. Missile climbs to higher altitude before activating the seeker. Or in some cases going even lower
#flight phase 4: terminal approach------------------------------------------------------------------------------------------------------
#Last stage - missile activates seeker and locks on target
TerminalApproachDist=1000              // in N. miles. Recommended to set this distance slightly less than the seeker range. For SAM must be slightly more than max range
SupportsBanking=False                  // if the missile will bank when turning
#========================================= Launch stats ============================================================
MaxVelocity=720                        // Maximum speed in knots
Acceleration=5.0                       // Acceleration factor
MaxTurnRate=25                         // Maximum turnrate in degrees per second
MinLaunchRange=0.05                    // Minimum launch range in nautical miles
MaxLaunchRange=2.2                     // Maximum launch range in nautical miles
MinLaunchAltitude=20                   // Minimum launch altitude in feet.
MaxLaunchAltitude=2000                 // Maximum launch altitude in feet.
LaunchReliability=95                   // The lower the value, the greater risk of misfire or accident (0...100)
#========================================     Seeker     ===========================================================
#Homing
SeekerGain=0.0                         // Seeker gain in dB
SeekerFOV=90.0                         // Seeker field-of-view in degrees
SeekerPassiveRange=3                   // Seeker passive range in nautical miles. Relevant for IR Homing, Semi-Active Radar Homing, Anti-Radiation Homing, TV-Homing, Passive Sonar Homing and Passive Sonar Homing (1, 2, 4, 6, 8 and 9)
#Misc Guidance Properties
#InsDrift=120							   // In degrees per minute of unguided flight. Shifts the weapon's nose by this amount per minute whenever the missile is not being actively guided (RC, Wire, tracking a target with its seeker)
# cass: meant for making missiles drift when they lose their target, blocked for now due to unresolved issues
#ECCM
#Search params for torpedoes
#SelfDestruct
SelfDestructDelay=4.0                  // delay in seconds for self destruction

[---------- Mesh definitions----------]
[Models]
ResourcesFolder=weapons/wp_9k116/
ResourcesRoot=wp_9k116
ResourcesMesh=wp_9k116_inflight
ResourcesMeshForLaunch=wp_9k116_dummy
ResourcesMaterialFolder=ships/materials/
ResourcesMaterial=modular_parts
ResourcesMeshSwitchTime=0.5  // time in seconds after launch to switch from launch mesh to main mesh
############################################################

[---------- Effects ----------]
# Effects are referenced in /effects/effects.ini when using an effects class
# e.g. either:
# BoosterEffect=effects/weapons/emitters/submarine_torpedo_launch
# or
# BoosterEffectClass=BoosterEffects  // this will be referenced in effects.ini

# possible values (optionally with suffix "Class")
# BoosterEffect, InFligheEffect, UnderwaterTrail, ParachuteEffect, TorpedoSurfaceSplash, HitWaterSplash
# DebrisTrail, DebrisSplash, SmallFireEffect, ModerateFireEffect, SevereFireEffect,
# HitAirExplosion, HitShipExplosion, HitObjectExplosion, HitGroundExplosion, HitDefaultExplosion
[Particles]
BoosterEffect=none
InFlightEffect=effects/weapons/emitters/wp_9k116_booster
InFlightEffectPosition=0,0,-0.007
InFlightEffectStartTime=1.0  // in seconds, after that the Inflight Effect will be played if available

HitDefaultExplosionClass=RocketShipHitExplosion
HitShipExplosionClass=RocketShipHitExplosion
HitAirExplosionClass=RocketShipHitExplosion

HitWaterSplashClass=SmallWaterSplashes
HitGroundExplosionClass=RocketGroundHitExplosion

[---------- Colliders ----------]
[Colliders]
# creates the hit box for this object
Collider=col_main

[col_main]
Collider=Box
Position=0,0,0
Rotation=0,0,0
Scale=0.0015,0.0015,0.012
