[General]
Type=Container                       // can be Projectile, Missile, RBU, ASROC, Torpedo,AerialRocket,MLRS
Mass=186                             // in kg. Used for aircraft. Container mass. Weapon mass is read from weapon ini



[---------- Mesh definitions----------]
############################################################
# Main Model with collider
############################################################
[Models]
############################################################
# AssetBundle related
############################################################
AssetBundleMeshes=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMaterials=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMesh=usn_rim-7
AssetBundleDamagedMesh=
AssetBundleMaterial=usn_rim-7_mat
AssetBundleMeshHullCollider=usn_rim-7_coll
############################################################
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=weapons/wp_adapters/
ResourcesRoot=wp_adapters
ResourcesMesh=wp_AKU-58
ResourcesMaterialFolder=aircraft/wp_su-24m/
ResourcesMaterial=wp_su-24m_mat


