[General]
Type=Container                       // can be Projectile, Missile, RBU, ASROC, Torpedo,AerialRocket,MLRS
Mass=50                                    // in kg. Used for aircraft. Container mass. Weapon mass is read from weapon ini

[Ammunition]
Ammunition=wp_s-8

NumberOfAttachments=20
AttachmentPosition1=-0.00068,0.00145,-0.001
AttachmentPosition2=-0.00157,0.00033,-0.001
AttachmentPosition3=-0.00133,-0.0011,-0.001
AttachmentPosition4=0,-0.00166,-0.001
AttachmentPosition5=0.00133,-0.0011,-0.001
AttachmentPosition6=0.00157,0.00033,-0.001
AttachmentPosition7=0.00068,0.00145,-0.001
AttachmentPosition8=-0.00137,0.00263,-0.001
AttachmentPosition9=-0.00237,0.00183,-0.001
AttachmentPosition10=-0.00294,0.00065,-0.001
AttachmentPosition11=-0.00286,-0.00069,-0.001
AttachmentPosition12=-0.0022,-0.00181,-0.001
AttachmentPosition13=-0.00122,-0.00265,-0.001
AttachmentPosition14=0,-0.00293,-0.001
AttachmentPosition15=0.00122,-0.00265,-0.001
AttachmentPosition16=0.0022,-0.00181,-0.001
AttachmentPosition17=0.00286,-0.00069,-0.001
AttachmentPosition18=0.00294,0.00065,-0.001
AttachmentPosition19=0.00237,0.00183,-0.001
AttachmentPosition20=0.00137,0.00263,-0.001

SalvoFireAmount=10                       // number of shots fired

[---------- Mesh definitions----------]
############################################################
# Main Model with collider
############################################################
[Models]
############################################################
# AssetBundle related
############################################################
AssetBundleMeshes=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMaterials=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMesh=usn_rim-7
AssetBundleDamagedMesh=
AssetBundleMaterial=usn_rim-7_mat
AssetBundleMeshHullCollider=usn_rim-7_coll
############################################################
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=weapons/wp_b8m-1/
ResourcesRoot=wp_b8m-1
ResourcesMesh=wp_b8m-1
ResourcesMaterialFolder=aircraft/materials/
ResourcesMaterial=wp_pods


