[General]
Type=Projectile            // can be Projectile, Missile, Torpedo
TargetType=AAW             // can be AAW, ASuW, ASW
SecondaryTargetType=ASuW

Mass=1.52                              // in kg. Used for aircraft
AmmoPoints=1.52                        // For Supply System. Defines "price" of ammunition based on mass, volume, complexity and availability

DecalClass=GunImpacts      // referenced in effects/decals.ini

[Physics]
MuzzleVelocity=800         // meter per second
MaxRange=3500              // in m
GravityFactor=12
CircularErrorProbable=20   // radius in meters at max range for shells to impact. Relevant for Guns, irrelevant for CIWS

[---------- Warhead Data ----------]
[WarheadData]
Power=1.1
ImpactSize=VerySmall            // Impact size, can be small, medium, large, verylarge
Penetration=Minor          // can be minor, moderate, heavy, always
KillProbability=0.005                 // Chance to intercept missile. Relevant for Guns, irrelevant for CIWS
# requires direct impact to roll

[---------- Mesh definitions----------]
[Models]
ResourcesFolder=weapons/shells/
ResourcesRoot=shells_tracer_new
ResourcesMesh=shell_tiny
ResourcesMaterial=shell_mat_green

[---------- Effects ----------]
[Particles]
# Effects are referenced in /effects/effects.ini
TrailEffect=None
HitShipExplosion=effects/Particle Emitters/impact_small_shell
HitAirExplosionClass=SmallFlakExplosions
HitDefaultExplosionClass=SmallFlakExplosions
HitWaterSplashClass=SmallWaterSplashes
