#=========================================================================================================================================================
#                                                  REQUIRES STATS REVISION
#=========================================================================================================================================================
[General]
# Mobile submarine simulator MG-74
# Users: 
Type=MOSS                              // can be Projectile, Missile, Torpedo
TargetType=ASW                         // can be AAW, ASuW, ASW

Mass=497                               // in kg. Used for aircraft
AmmoPoints=994                         // For Supply System. Defines "price" of ammunition based on mass, volume, complexity and availability

DefaultCameraDistance=0.6
MinCameraDistanceForeAft=0.29
MinCameraDistanceBroadside=0.29
CameraPivotHeight=0.0

DecalClass=Standard                    // referenced in effects/decals.ini

[SensorData]
IRSignature=VeryTiny
# Radar related (RCS => radar cross section)
RCS=Small

BaseNoise=190                   // base sound level in db at 1m distance
FlowNoise=1                     // additional flow noise per knot in db (20kn would be +20db)
CavitationNoise=0               // additional noise for cavitation in db
TargetReflectionStrength=50     // reflection on active sonar
# Transient
TransientRCS=-1                        // Transient visibility on the radar
TransientVisualIdentificationRange=-1  // Transient can be visually detected at this distance in nmi
TransientBaseNoise=150                 // In db


[WarheadData]
WarheadType=-1

[ECM]
# Decoy related
SpoofChance=0.9                        // Base chance to spoof torpedo

[---------- Guidance ----------]
############################################################
# Guidance System
############################################################
# Guidance Types:
# 0 = None
# 1 = IR Homing
# 2 = Semi-Active Radar Homing
# 3 = Active Radar Homing
# 4 = Anti-Radiation Homing
# 5 = Laser-Homing
# 6 = TV-Homing
# 7 = Active Sonar Homing
# 8 = Passive Sonar Homing
# 9 = Wake Homing

[Guidance]
GuidanceType=0
MidCourseCorrection=0                  // 0 = None, 1 = Radio Command, 2 = Wire Guided 
InitialFlightPhaseDuration=2.0         // time in seconds where the missile moves straight on without guiding
#======================================== Flight Profile ===========================================================
#========================================= Launch stats ============================================================
MaxVelocity=22.0                       // Maximum speed in knots
Acceleration=1.0                       // Acceleration factor
MaxTurnRate=10.0                       // Maximum turnrate in degrees per second

MinLaunchRange=0.1                     // Minimum launch range in nautical miles
MaxLaunchRange=8                       // Maximum launch range in nautical miles

MaxDepth=1500                          // Maximum allowed depth in feet.

LaunchReliability=85                   // The lower the value, the greater risk of misfire or accident (0...100)
#========================================     Seeker     ===========================================================
# N/A
# Torpedo related
DefaultDepth=200.0                     // default depth in feet a torpedo is using for submerged targets for bearing only launches

[---------- Mesh definitions----------]
[Models]
############################################################
# AssetBundle related
############################################################
AssetBundleMeshes=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMaterials=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMesh=usn_rim-7
AssetBundleDamagedMesh=
AssetBundleMaterial=usn_rim-7_mat
AssetBundleMeshHullCollider=usn_rim-7_coll
############################################################

############################################################
# Internal Resources folder related
############################################################

ResourcesFolder=weapons/wp_mg-74/
ResourcesRoot=wp_mg-74
ResourcesMesh=wp_mg-74
ResourcesMaterial=wp_mg-74_mat
############################################################

NumberOfSubModels=2

SubModel1=Propeller_Left
SubModel2=Propeller_Right

[Propeller_Left]
Type=Propulsion
RotationDirection=Left
Mesh=wp_mg-74_propl
Rotation=-90,0,0

[Propeller_Right]
Type=Propulsion
RotationDirection=Right
Mesh=wp_mg-74_propr
Rotation=-90,0,0

[---------- Effects ----------]
# Effects are referenced in /effects/effects.ini when using an effects class
# e.g. either:
# BoosterEffect=effects/weapons/emitters/submarine_torpedo_launch
# or
# BoosterEffectClass=BoosterEffects  // this will be referenced in effects.ini

# possible values (optionally with suffix "Class")
# BoosterEffect, InFligheEffect, UnderwaterTrail, ParachuteEffect, TorpedoSurfaceSplash, HitWaterSplash
# DebrisTrail, DebrisSplash, SmallFireEffect, ModerateFireEffect, SevereFireEffect,
# HitAirExplosion, HitShipExplosion, HitObjectExplosion, HitGroundExplosion, HitDefaultExplosion
[Particles]
BoosterEffect=effects/weapons/emitters/submarine_torpedo_launch
BoosterEffectPosition=0,0,0
InFlightEffect=effects/weapons/emitters/aswtorpedo_cavitation_particle
InFlightEffectPosition=0,0,-0.028875
InFlightEffectStartTime=0

HitShipExplosionClass=MediumMissileExplosions
HitAirExplosionClass=MediumMissileExplosions
HitDefaultExplosionClass=MediumMissileExplosions
HitWaterSplashClass=SmallWaterSplashes

############################################################
# Sounds
############################################################

[Sounds]
SoundMode=1
PropAudioClip=audio/weapons/torpedo
PropAudioRollOff=Logarithmic
PropAudioDistance=1,20
PropAudioPitch=1.0
PropAudioPosition=0,0,0
PropAudioAudibility=Below

[Colliders]
Collider=col_main

[col_main]
Collider=Box
Position=0,-0.0051,0.0053
Rotation=0,0,0
Scale=0.01,0.01703,0.09293