[General]
Type=Container                       // can be Projectile, Missile, RBU, ASROC, Torpedo,AerialRocket,MLRS
Mass=200                                   // in kg. Used for aircraft. Container mass. Weapon mass is read from weapon ini

[---------- Sensor Systems ----------]
[SensorSystems]
NumberOfSensorSystems=1

[SensorSystem1] #ECM //Siren' jammer SPS-141/142/143
Type=ECM
SystemName=AircraftDECM_Med
Mount=Dummy
ModuleType=Sensor

[---------- Weapon Systems ----------]
[WeaponSystems]
NumberOfWeaponSystems=1

[WeaponSystem1] #Chaff
Type=Chaff
SystemName=WP_AIR_CHAFF_DISP
#Sensors
#Animations
#Mount
Mount=Dummy
#MountPosition=0,-0.01,-0.016
#Containers
ContainerBase=Dummy
#Angles
#Loading
AssociatedMagazine=WeaponMagazineChaff
#Effects
NumberOfEffects=3
DelayBetweenLaunches=0.1
#Other
WorksStandalone=True
ModuleType=Weapon

[---------- WeaponMagazines ----------]
[WeaponMagazineChaff]
NumberOfAmmunitionTypes=1
Ammunition1_Count=15
Ammunition1=wp_aircraft_chaff
ModuleType=WeaponMagazine

[---------- Mesh definitions----------]
[Models]
ResourcesFolder=weapons/wp_sps-141/
ResourcesRoot=wp_sps-141
ResourcesMesh=wp_sps-141-21
ResourcesMaterialFolder=aircraft/materials/
ResourcesMaterial=wp_pods