[General]
#9М37 of 9K35 Strela-10
# Users, Land SAM:
Type=Missile                           // can be Projectile, Missile, Torpedo
TargetType=AAW                         // can be AAW, ASuW, ASW

Mass=40                                // in kg. Used for aircraft
AmmoPoints=60                          // For Supply System. Defines "price" of ammunition based on mass, volume, complexity and availability

DefaultCameraDistance=0.6
MinCameraDistanceForeAft=0.29
MinCameraDistanceBroadside=0.29
CameraPivotHeight=0.0

DecalClass=SAMImpacts  // referenced in effects/decals.ini

[SensorData]
#Visual
VisualIdentificationRange=3  // at what range in nm this unit can be visually identified
IRSignature=VeryTiny
# Radar related (RCS => radar cross section)
RCS=Tiny
IRSignature=VerySmall
# Sonar related

[---------- Warhead Data ----------]
#Warhead Types:
#0 = Blast Fragmentation
#1 = Armor Piercing
#2 = HEAT
#3 = Illumination
#4 = Cluster
#5 = Runway Cratering

# Fuze Types:
# 0 = Impact Fuze
# 1 = Proximity Fuze
[WarheadData]
WarheadType=0
Power=7
ImpactSize=VeryLarge                    // Impact size, can be small, medium, large, verylarge
Penetration=Always                      // can be minor, moderate, heavy, always

FuzeProximityDistance=15.0              // for proximity fuze: distance to target in meter. Also indicates that Fuze Type = Proximity Fuze
KillProbability=0.55                    // Base chance to hit
[---------- Guidance ----------]
# Guidance Types:
# 0 = None
# 1 = IR Homing
# 2 = Semi-Active Radar Homing
# 3 = Active Radar Homing
# 4 = Anti-Radiation Homing
# 5 = Laser-Homing
# 6 = TV-Homing
# 7 = Active Sonar Homing
# 8 = Passive Sonar Homing
# 9 = Wake Homing
[Guidance]
GuidanceType=1
InitialFlightPhaseDuration=0.25        // time in seconds where the missile moves straight on without guiding
MidCourseCorrection=0                  // 0 = None, 1 = Radio Command, 2 = Wire Guided
#======================================== Flight Profile ===========================================================
#flight phase 1: loft-----------------------------------------------------------------------------------------------------------------
#1st stage of missile flight - high altitude
#flight phase 2: sea skimming---------------------------------------------------------------------------------------------------------
#2nd stage of missile flight - low altitude
#flight phase 3: final flight phase (e.g. terminal popup)------------------------------------------------------------------------------
#Pop-Up. Missile climbs to higher altitude before activating the seeker. Or in some cases going even lower
#flight phase 4: terminal approach------------------------------------------------------------------------------------------------------
#Last stage - missile activates seeker and locks on target
TerminalApproachDist=1000              // in N. miles. Recommended to set this distance slightly less than the seeker range. For SAM better set it to max value, 1000 miles is enough
#========================================= Launch stats ============================================================
MaxVelocity=1069                       // Maximum speed in knots
Acceleration=18.0                      // Acceleration factor
MaxTurnRate=30.0                       // Maximum turnrate in degrees per second
MinLaunchRange=0.25                    // Minimum launch range in nautical miles
MaxLaunchRange=2.7                     // Maximum launch range in nautical miles
MinAttackAltitude=82                   // Minimum altitude of a target, in feet. Outside Min/Max altitude missile deviation is greatly increaced
MaxAttackAltitude=11500                // Maximum altitude of target, in feet
LaunchReliability=95                   // The lower the value, the greater risk of misfire or accident (0...100)
#========================================     Seeker     ===========================================================
#Homing
IsRearAspectOnly=False                 // Rear aspect ammunition can lock on targets from their rear cone only
TargetRearCone=120                     // Horizontal and vertical cone width in degrees applied to targets of rear aspect only weapons. Ignored for all aspect weapons
SeekerFOV=2.5                          // Seeker field-of-view in degrees
SeekerGimbalFOV=90                     // Seeker gimbal FOV in degrees
SeekerPassiveRange=12                  // Seeker passive range in nautical miles. Relevant for IR Homing, Semi-Active Radar Homing, Anti-Radiation Homing, TV-Homing, Passive Sonar Homing and Passive Sonar Homing (1, 2, 4, 6, 8 and 9)
#Misc Guidance Properties
#InsDrift=120							   // In degrees per minute of unguided flight. Shifts the weapon's nose by this amount per minute whenever the missile is not being actively guided (RC, Wire, tracking a target with its seeker)
# cass: meant for making missiles drift when they lose their target, blocked for now due to unresolved issues
#ECCM
AntiCountermeasuresBonus=0.3           // This value substracted from probability of spoofing by countermeasures (0...1)
#Search params for torpedoes
#SelfDestruct
SelfDestructDelay=4.0                  // delay in seconds for self destruction
[---------- Mesh definitions----------]
[Models]
ResourcesFolder=weapons/wp_9k35/
ResourcesRoot=wp_9k35
ResourcesMesh=wp_9k35
ResourcesMaterial=wp_9k35_mat

[---------- Effects ----------]
# Effects are referenced in /effects/effects.ini when using an effects class
# e.g. either:
# BoosterEffect=effects/weapons/emitters/submarine_torpedo_launch
# or
# BoosterEffectClass=BoosterEffects  // this will be referenced in effects.ini

# possible values (optionally with suffix "Class")
# BoosterEffect, InFligheEffect, UnderwaterTrail, ParachuteEffect, TorpedoSurfaceSplash, HitWaterSplash
# DebrisTrail, DebrisSplash, SmallFireEffect, ModerateFireEffect, SevereFireEffect,
# HitAirExplosion, HitShipExplosion, HitObjectExplosion, HitGroundExplosion, HitDefaultExplosion
[Particles]
BoosterEffect=effects/weapons/emitters/aam_small_effect
BoosterEffectPosition=0,0,-0.015

InFlightEffectClass=DefaultMissileInflightEffect
InFlightEffectPosition=0,0,-0.015
InFlightEffectStartTime=2.0  // in seconds, after that the Inflight Effect will be played if available

HitShipExplosionClass=MediumMissileExplosions
HitAirExplosionClass=MediumMissileExplosions
HitDefaultExplosionClass=MediumMissileExplosions
HitWaterSplashClass=SmallWaterSplashes

[---------- Colliders ----------]
[Colliders]
# creates the hit box for this object
Collider=col_main

[col_main]
Collider=Box
Position=0,0,0
Rotation=0,0,0
Scale=0.005,0.005,0.043