[General]
Type=Container                       // can be Projectile, Missile, RBU, ASROC, Torpedo,AerialRocket,MLRS
Mass=50                                    // in kg. Used for aircraft. Container mass. Weapon mass is read from weapon ini

[Ammunition]
Ammunition=wp_s-5

NumberOfAttachments=16
AttachmentPosition1=0,0.0009,0.0016
AttachmentPosition2=-0.0009,0.0003,0.0016
AttachmentPosition3=-0.0005,-0.00074,0.0016
AttachmentPosition4=0.0005,-0.00074,0.0016
AttachmentPosition5=0.0009,0.0003,0.0016
AttachmentPosition6=-0.00094,0.0016,-0.0003
AttachmentPosition7=-0.00163,0.00094,-0.0003
AttachmentPosition8=-0.00189,0,-0.0003
AttachmentPosition9=-0.00163,-0.00096,-0.0003
AttachmentPosition10=-0.00093,-0.00164,-0.0003
AttachmentPosition11=0,-0.00186,-0.0003
AttachmentPosition12=0.00093,-0.00164,-0.0003
AttachmentPosition13=0.00163,-0.00096,-0.0003
AttachmentPosition14=0.00189,0,-0.0003
AttachmentPosition15=0.00163,0.00094,-0.0003
AttachmentPosition16=0.00094,0.0016,-0.0003

SalvoFireAmount=16                       // number of shots fired

[---------- Mesh definitions----------]
############################################################
# Main Model with collider
############################################################
[Models]
############################################################
# AssetBundle related
############################################################
AssetBundleMeshes=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMaterials=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMesh=usn_rim-7
AssetBundleDamagedMesh=
AssetBundleMaterial=usn_rim-7_mat
AssetBundleMeshHullCollider=usn_rim-7_coll
############################################################
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=weapons/wp_ub-16-57/
ResourcesRoot=wp_ub-16-57
ResourcesMesh=wp_ub-16-57_hd
ResourcesMaterialFolder=aircraft/materials/
ResourcesMaterial=wp_pods

