[General]
SerialnumberReferences=
EmblemReference=Emblem
NationFlagReference=Flag1
AllVariantsAreOfSameNation=False //Speeds up nation sorting. Only needed if there is more then 1 nation variants. Default is 'true'
NumberOfSquadrons=11

[Default]
Nation=US
ServiceDate=1971

[Squadron1]  Atlantic Airlines 
ResourcesSerialnumberFolder=aircraft/civ_dc-10/atlantic/serial/
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=aircraft/civ_dc-10/atlantic/
EmblemTexture=
ResourcesLiveryFolder=aircraft/civ_dc-10/atlantic/
LiveryTexture=civ_dc-10_tx
SpecularTexture=civ_dc-10_spec
# nations are referenced in the layout.ini file:
Nation=US

[Squadron2]  Trilateral Airlines 
ResourcesSerialnumberFolder=aircraft/civ_dc-10/trilateral/serial/
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=aircraft/civ_dc-10/trilateral/
EmblemTexture=
ResourcesLiveryFolder=aircraft/civ_dc-10/trilateral/
LiveryTexture=civ_dc-10_tx
SpecularTexture=civ_dc-10_spec
# nations are referenced in the layout.ini file:
Nation=US

[Squadron3]  Oceanic Airlines 
ResourcesSerialnumberFolder=aircraft/civ_dc-10/oceanic/serial/
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=aircraft/civ_dc-10/oceanic/
EmblemTexture=
ResourcesLiveryFolder=aircraft/civ_dc-10/oceanic/
LiveryTexture=civ_dc-10_tx
SpecularTexture=civ_dc-10_spec
# nations are referenced in the layout.ini file:
Nation=US


[Squadron4]  Air Hexagone
ResourcesSerialnumberFolder=aircraft/civ_dc-10/airhexagone/serial/
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=aircraft/civ_dc-10/airhexagone/
EmblemTexture=
ResourcesLiveryFolder=aircraft/civ_dc-10/airhexagone/
LiveryTexture=civ_dc-10_tx
SpecularTexture=civ_dc-10_spec
# nations are referenced in the layout.ini file:
Nation=France

[Squadron5]  Flughansa
ResourcesSerialnumberFolder=aircraft/civ_dc-10/flughansa/serial/
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=aircraft/civ_dc-10/flughansa/
EmblemTexture=
ResourcesLiveryFolder=aircraft/civ_dc-10/flughansa/
LiveryTexture=civ_dc-10_tx
SpecularTexture=civ_dc-10_spec
# nations are referenced in the layout.ini file:
Nation=Germany

[Squadron6]  British Albion
ResourcesSerialnumberFolder=aircraft/civ_dc-10/britishalbion/serial/
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=aircraft/civ_dc-10/britishalbion/
EmblemTexture=
ResourcesLiveryFolder=aircraft/civ_dc-10/britishalbion/
LiveryTexture=civ_dc-10_tx
SpecularTexture=civ_dc-10_spec
# nations are referenced in the layout.ini file:
Nation=UK

[Squadron7]  Britannic Airways
ResourcesSerialnumberFolder=aircraft/civ_dc-10/britannic/serial/
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=aircraft/civ_dc-10/britannic/
EmblemTexture=
ResourcesLiveryFolder=aircraft/civ_dc-10/britannic/
LiveryTexture=civ_dc-10_tx
SpecularTexture=civ_dc-10_spec
# nations are referenced in the layout.ini file:
Nation=UK

[Squadron8]  Siam Airways
ResourcesSerialnumberFolder=aircraft/civ_dc-10/siam/serial/
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=aircraft/civ_dc-10/siam/
EmblemTexture=
ResourcesLiveryFolder=aircraft/civ_dc-10/siam/
LiveryTexture=civ_dc-10_tx
SpecularTexture=civ_dc-10_spec
# nations are referenced in the layout.ini file:
Nation=Thailand

[Squadron9]  All Asian Airways
ResourcesSerialnumberFolder=aircraft/civ_dc-10/allasianairways/serial/
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=aircraft/civ_dc-10/allasianairways/
EmblemTexture=
ResourcesLiveryFolder=aircraft/civ_dc-10/allasianairways/
LiveryTexture=civ_dc-10_tx
SpecularTexture=civ_dc-10_spec
# nations are referenced in the layout.ini file:
Nation=Singapore

[Squadron10]  Kiki Delivery Service
ResourcesSerialnumberFolder=aircraft/civ_dc-10/kiki/serial/
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=aircraft/civ_dc-10/kiki/
EmblemTexture=
ResourcesLiveryFolder=aircraft/civ_dc-10/kiki/
LiveryTexture=civ_dc-10_tx
SpecularTexture=civ_dc-10_spec
NormalTexture=civ_dc-10_nm
# nations are referenced in the layout.ini file:
Nation=Japan

[Squadron11]  Air Italia
ResourcesSerialnumberFolder=aircraft/civ_dc-10/airitalia/serial/
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=aircraft/civ_dc-10/airitalia/
EmblemTexture=
ResourcesLiveryFolder=aircraft/civ_dc-10/airitalia/
LiveryTexture=civ_dc-10_tx
SpecularTexture=civ_dc-10_spec
NormalTexture=civ_dc-10_nm
# nations are referenced in the layout.ini file:
Nation=Italy