[General]
SerialnumberReferences=Serial
EmblemReference=
NationFlagReference=Flag1
NumberOfSquadrons=11

[Default]
ResourcesLiveryFolder=aircraft/fr_f1/ada/
LiveryTexture=fr_f1_tx
ResourcesEmblemFolder=textures/Misc/
EmblemTexture=transparent
Nation=France
ServiceDate=1974

[Squadron1]  #2112 Sq.
ResourcesSerialnumberFolder=aircraft/fr_f1/fae/serial/
SerialNumberPrefix=
SerialnumberTextures=01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=aircraft/fr_f1/fae/
LiveryTexture=fr_f1_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=Ecuador

[Squadron2]  #No.79 FS
ResourcesSerialnumberFolder=aircraft/fr_f1/iqaf/serial/
SerialNumberPrefix=
SerialnumberTextures=01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16,17
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=aircraft/fr_f1/iqaf/
LiveryTexture=fr_f1_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=Iraq

[Squadron3]  #No.92 FS
ResourcesSerialnumberFolder=aircraft/fr_f1/iqaf/serial/
SerialNumberPrefix=
SerialnumberTextures=18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=aircraft/fr_f1/iqaf/
LiveryTexture=fr_f1_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=Iraq

[Squadron4]  #No.1 Sq.
ResourcesSerialnumberFolder=aircraft/materials/numbers/
SerialNumberPrefix=
SerialnumberTextures=arab_black_001,arab_black_002,arab_black_003,arab_black_004,arab_black_005,arab_black_006,arab_black_007,arab_black_008,arab_black_009,arab_black_010,arab_black_011,arab_black_012,arab_black_013,arab_black_014,arab_black_015,arab_black_016
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=aircraft/fr_f1/rjaf/
LiveryTexture=fr_f1_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=Jordan

[Squadron5]  #10th FS
ResourcesSerialnumberFolder=aircraft/fr_f1/libya_f1e/serial/
SerialNumberPrefix=
SerialnumberTextures=501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=aircraft/fr_f1/libya_f1e/
LiveryTexture=fr_f1_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=Libya

[Squadron6]  #462 Sqn
ResourcesSerialnumberFolder=aircraft/fr_f1/es_ala46/serial/
SerialNumberPrefix=
SerialnumberTextures=01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16,17,18,19,20
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=aircraft/fr_f1/es_ala46/
LiveryTexture=fr_f1_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=Spain

[Squadron7]  #No.7 Sqn
ResourcesSerialnumberFolder=aircraft/fr_f1/qaf/serial/
SerialNumberPrefix=
SerialnumberTextures=01,02,03,04,05,06,07,08,09,10,11,12
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=aircraft/fr_f1/qaf/
LiveryTexture=fr_f1_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=Qatar

[Squadron8]  #Blank Grey
ResourcesLiveryFolder=aircraft/fr_f1/blank_grey/
LiveryTexture=fr_f1_tx
ResourcesEmblemFolder=textures/Misc/
EmblemTexture=transparent
Nation=France

[Squadron9]  #Blank Euro Camo
ResourcesLiveryFolder=aircraft/fr_f1/blank_euro_camo/
LiveryTexture=fr_f1_tx
ResourcesEmblemFolder=textures/Misc/
EmblemTexture=transparent
Nation=France

[Squadron10]  #Blank Desert
ResourcesLiveryFolder=aircraft/fr_f1/blank_desert/
LiveryTexture=fr_f1_tx
ResourcesEmblemFolder=textures/Misc/
EmblemTexture=transparent
Nation=France

[Squadron11]  #Blank Camo
ResourcesLiveryFolder=aircraft/fr_f1/blank_camo/
LiveryTexture=fr_f1_tx
ResourcesEmblemFolder=textures/Misc/
EmblemTexture=transparent
Nation=France