[General]
SerialnumberReferences=Serial
EmblemReference=
NationFlagReference=Flag1
NumberOfSquadrons=6

[Default]
ResourcesLiveryFolder=aircraft/fr_mirage_iii/
LiveryTexture=fr_mirage_iii_tx
ResourcesEmblemFolder=textures/Misc/
EmblemTexture=transparent
Nation=France
ServiceDate=1974

[Squadron1]  #3 Squadron RAAF - RAAF Butterworth, Malaysia
ResourcesSerialnumberFolder=aircraft/fr_mirage_iii/3sqn_raaf/serial/
SerialNumberPrefix=
SerialnumberTextures=21,31,84,100
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=aircraft/fr_mirage_iii/3sqn_raaf/
LiveryTexture=fr_mirage_iii_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=Australia
ServiceDate=1967|1986

[Squadron2]  #75 Squadron RAAF - RAAF Butterworth, Malaysia to 1981, then RAAF Base Tindal NT
ResourcesSerialnumberFolder=aircraft/fr_mirage_iii/75sqn_raaf/serial/
SerialNumberPrefix=
SerialnumberTextures=15,21,24
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=aircraft/fr_mirage_iii/75sqn_raaf/
LiveryTexture=fr_mirage_iii_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=Australia
ServiceDate=1965|1988

[Squadron3]  #77 Squadron RAAF - RAAF Base Williamtown NSW 1969
ResourcesSerialnumberFolder=aircraft/fr_mirage_iii/77sqn_raaf/serial/
SerialNumberPrefix=
SerialnumberTextures=4,20,41,42,49,54
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=aircraft/fr_mirage_iii/77sqn_raaf/
LiveryTexture=fr_mirage_iii_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=Australia
ServiceDate=1969|1987

[Squadron4]  #79 Squadron RAAF - RAAF Butterworth Malaysia 1986
ResourcesSerialnumberFolder=aircraft/fr_mirage_iii/79sqn_raaf/serial/
SerialNumberPrefix=
SerialnumberTextures=34,48,54,68
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=aircraft/fr_mirage_iii/79sqn_raaf/
LiveryTexture=fr_mirage_iii_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=Australia
ServiceDate=1969|1988

[Squadron5]
ResourcesSerialnumberFolder=aircraft/fr_mirage_iii/Swiss/serial/
SerialNumberPrefix=
SerialnumberTextures=34,48,54,68
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=aircraft/fr_mirage_iii/Swiss/
LiveryTexture=fr_mirage_iii_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=Switzerland
ServiceDate=

[Squadron6]
ResourcesSerialnumberFolder=aircraft/fr_mirage_iii/Argentina/serial/
SerialNumberPrefix=
SerialnumberTextures=34,48,54,68
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=aircraft/fr_mirage_iii/Argentina/
LiveryTexture=fr_mirage_iii_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=Argentina
ServiceDate=