[General]
SerialnumberReferences=JASDF_Serial
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfSquadrons=3
#1 PLAAF

[Default]
Nation=Japan
ServiceDate=1977

[Squadron1] #JASDF 3rd Hikotai
ResourcesSerialnumberFolder=aircraft/jasdf_f-1/serial/
SerialNumberPrefix=
SerialnumberTextures=203,212,213,224,225,226,230,231,233,237,241,243,245,247,249,253,265,267
ResourcesEmblemFolder=aircraft/jasdf_f-1/3_tfs/
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/jasdf_f-1/3_tfs/
LiveryTexture=jasdf_f-1_tx
#SpecularTexture=jasdf_f-1_spec
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_japan
# nations are referenced in the layout.ini file:
Nation=Japan

[Squadron2] #JASDF 6th Hikotai
ResourcesSerialnumberFolder=aircraft/jasdf_f-1/serial/
SerialNumberPrefix=
SerialnumberTextures=201,202,204,206,207,208,209,211,214,215,217,219,220,221,222,227,228,229,232,234,235,236,238,239,240,242,244,246,248,250,251,252,254,255,256,257,258,259,260,261,262,263,264,266,268,269,270,271,272,273,274,275,276,277
ResourcesEmblemFolder=aircraft/jasdf_f-1/6_tfs/
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/jasdf_f-1/6_tfs/
LiveryTexture=jasdf_f-1_tx
#SpecularTexture=jasdf_f-1_spec
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_japan
# nations are referenced in the layout.ini file:
Nation=Japan

[Squadron3] #JASDF 8th Hikotai
ResourcesSerialnumberFolder=aircraft/jasdf_f-1/serial/
SerialNumberPrefix=
SerialnumberTextures=205,210,216,218,223
ResourcesEmblemFolder=aircraft/jasdf_f-1/8_tfs/
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/jasdf_f-1/8_tfs/
LiveryTexture=jasdf_f-1_tx
#SpecularTexture=jasdf_f-1_spec
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_japan
# nations are referenced in the layout.ini file:
Nation=Japan