[General]
SerialnumberReferences=Serial
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfSquadrons=4
#1 PLAAF

[Default]
Nation=China
ServiceDate=1957

[Squadron1] #NK grey
ResourcesSerialnumberFolder=aircraft/materials/numbers/
SerialNumberPrefix=
SerialnumberTextures=nk_4128,nk_4228,nk_4324,nk_4326,nk_4328,nk_5012,nk_5013,nk_5015,nk_5019,nk_5020,nk_5023,nk_5024,nk_5066,nk_5071,nk_5212,nk_5213,nk_5217,nk_5262,nk_5293,nk_5338
ResourcesEmblemFolder=aircraft/pla_f-5/
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/pla_f-5/nk/
LiveryTexture=pla_f-5_tx
SpecularTexture=pla_f-5_spec
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_north_korea
# nations are referenced in the layout.ini file:
Nation=North_Korea

[Squadron2] #Pakistan grey
ResourcesSerialnumberFolder=aircraft/materials/numbers/
SerialNumberPrefix=
SerialnumberTextures=pak_4128,pak_4228,pak_4324,pak_4326,pak_4328,pak_5012,pak_5013,pak_5015,pak_5019,pak_5020,pak_5023,pak_5024,pak_5066,pak_5071,pak_5212,pak_5213,pak_5217,pak_5262,pak_5293,pak_5338
ResourcesEmblemFolder=aircraft/pla_f-5/
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/pla_f-5/pak/
LiveryTexture=pla_f-5_tx
SpecularTexture=pla_f-5_spec
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_pakistan
# nations are referenced in the layout.ini file:
Nation=Pakistan

[Squadron3]  #Blank Camo
ResourcesLiveryFolder=aircraft/pla_f-5/blank_camo/
LiveryTexture=pla_f-5_tx
ResourcesEmblemFolder=textures/Misc/
EmblemTexture=transparent
Nation=China

[Squadron4]  #Blank Grey
ResourcesLiveryFolder=aircraft/pla_f-5/blank_grey/
LiveryTexture=pla_f-5_tx
ResourcesEmblemFolder=textures/Misc/
EmblemTexture=transparent
Nation=China