[General]
SerialnumberReferences=Serial
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfSquadrons=1
#1 PLAAF

[Default]
Nation=China
ServiceDate=1957

[Squadron1] #PLAAF white
#bare metal
ResourcesSerialnumberFolder=aircraft/materials/numbers/
SerialNumberPrefix=
SerialnumberTextures=vpaf_4128,vpaf_4228,vpaf_4324,vpaf_4326,vpaf_4328,vpaf_5012,vpaf_5013,vpaf_5015,vpaf_5019,vpaf_5020,vpaf_5023,vpaf_5024,vpaf_5066,vpaf_5071,vpaf_5121,vpaf_5212,vpaf_5213,vpaf_5217,vpaf_5262,vpaf_5293,vpaf_5338
ResourcesEmblemFolder=aircraft/pla_f-5/
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/pla_f-5/
LiveryTexture=pla_f-5_tx
SpecularTexture=pla_f-5_spec
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_china
# nations are referenced in the layout.ini file:
Nation=China