[General]
SerialnumberReferences=Serial
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfSquadrons=24

[Default]
Nation=US
ServiceDate=1962
#Greece

[Squadron1] #341 MAI
ResourcesSerialnumberFolder=aircraft/usaf_f-5a/haf/serial/
SerialNumberPrefix=
SerialnumberTextures=01,02,03,04,05,06,07,08,09,11,12,13,14,15,16,17,18,19
ResourcesLiveryFolder=aircraft/usaf_f-5a/haf/
LiveryTexture=usaf_f-5a_tx
ResourcesFlagFolder=ships/materials/textures/
# nations are referenced in the layout.ini file:
Nation=Greece

[Squadron2] #343 MAI
ResourcesSerialnumberFolder=aircraft/usaf_f-5a/haf/serial/
SerialNumberPrefix=
SerialnumberTextures=20,21,22,23,24,25,26,27,28,29,31,32,33,34,35,36,37,38
ResourcesLiveryFolder=aircraft/usaf_f-5a/haf/
LiveryTexture=usaf_f-5a_tx
ResourcesFlagFolder=ships/materials/textures/
# nations are referenced in the layout.ini file:
Nation=Greece

[Squadron3] #337 MAI
ResourcesSerialnumberFolder=aircraft/usaf_f-5a/haf/serial/
SerialNumberPrefix=
SerialnumberTextures=39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56
ResourcesLiveryFolder=aircraft/usaf_f-5a/haf/
LiveryTexture=usaf_f-5a_tx
ResourcesFlagFolder=ships/materials/textures/
# nations are referenced in the layout.ini file:
Nation=Greece

#Netherlands

[Squadron4] #313 Sqn
ResourcesSerialnumberFolder=aircraft/usaf_f-5a/nl/serial/
SerialNumberPrefix=
SerialnumberTextures=001,002,003,004,005,006,007,008,009,011,012,013,014,015,016,017,018
ResourcesLiveryFolder=aircraft/usaf_f-5a/nl/rnlaf_313/
LiveryTexture=usaf_f-5a_tx
ResourcesFlagFolder=ships/materials/textures/
# nations are referenced in the layout.ini file:
Nation=Netherlands

[Squadron5] #314 Sqn
ResourcesSerialnumberFolder=aircraft/usaf_f-5a/nl/serial/
SerialNumberPrefix=
SerialnumberTextures=019,020,021,022,023,024,025,026,027,028,029,030,031,032,033,034,035,036
ResourcesLiveryFolder=aircraft/usaf_f-5a/nl/rnlaf_314/
LiveryTexture=usaf_f-5a_tx
ResourcesFlagFolder=ships/materials/textures/
# nations are referenced in the layout.ini file:
Nation=Netherlands

[Squadron6] #315 Sqn
ResourcesSerialnumberFolder=aircraft/usaf_f-5a/nl/serial/
SerialNumberPrefix=
SerialnumberTextures=037,038,039,040,041,042,043,044,045,046,047,048,049,050,051,052,053,054
ResourcesLiveryFolder=aircraft/usaf_f-5a/nl/rnlaf_315/
LiveryTexture=usaf_f-5a_tx
ResourcesFlagFolder=ships/materials/textures/
# nations are referenced in the layout.ini file:
Nation=Netherlands

[Squadron7] #316 Sqn
ResourcesSerialnumberFolder=aircraft/usaf_f-5a/nl/serial/
SerialNumberPrefix=
SerialnumberTextures=055,056,057,058,059,060,061,062,063,064,065,066,067,068,069,070,071,072
ResourcesLiveryFolder=aircraft/usaf_f-5a/nl/rnlaf_316/
LiveryTexture=usaf_f-5a_tx
ResourcesFlagFolder=ships/materials/textures/
# nations are referenced in the layout.ini file:
Nation=Netherlands

#Norway

[Squadron8] #334 Sqn
ResourcesSerialnumberFolder=aircraft/usaf_f-5a/rnaf/serial/
SerialNumberPrefix=
SerialnumberTextures=01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24
ResourcesLiveryFolder=aircraft/usaf_f-5a/rnaf/nor_334/
LiveryTexture=usaf_f-5a_tx
ResourcesFlagFolder=ships/materials/textures/
# nations are referenced in the layout.ini file:
Nation=Norway

[Squadron9] #336 Sqn
ResourcesSerialnumberFolder=aircraft/usaf_f-5a/rnaf/serial/
SerialNumberPrefix=
SerialnumberTextures=25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48
ResourcesLiveryFolder=aircraft/usaf_f-5a/rnaf/nor_336/
LiveryTexture=usaf_f-5a_tx
ResourcesFlagFolder=ships/materials/textures/
# nations are referenced in the layout.ini file:
Nation=Norway

[Squadron10] #338 Sqn
ResourcesSerialnumberFolder=aircraft/usaf_f-5a/rnaf/serial/
SerialNumberPrefix=
SerialnumberTextures=49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72
ResourcesLiveryFolder=aircraft/usaf_f-5a/rnaf/nor_338/
LiveryTexture=usaf_f-5a_tx
ResourcesFlagFolder=ships/materials/textures/
# nations are referenced in the layout.ini file:
Nation=Norway

#Philippines

[Squadron11] #6 TFS
ResourcesSerialnumberFolder=aircraft/usaf_f-5a/paf/serial/
SerialNumberPrefix=
SerialnumberTextures=01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35
ResourcesLiveryFolder=aircraft/usaf_f-5a/paf/
LiveryTexture=usaf_f-5a_tx
#SpecularTexture=usaf_f-5a_spec
ResourcesFlagFolder=ships/materials/textures/
# nations are referenced in the layout.ini file:
Nation=Philippines

#South Vietnam

[Squadron12] #522nd FS
ResourcesSerialnumberFolder=aircraft/usaf_f-5a/rvn/serial/
SerialNumberPrefix=
SerialnumberTextures=01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26
ResourcesLiveryFolder=aircraft/usaf_f-5a/rvn/
LiveryTexture=usaf_f-5a_tx
ResourcesFlagFolder=ships/materials/textures/
# nations are referenced in the layout.ini file:
Nation=South_Vietnam

[Squadron13] #536th FS
ResourcesSerialnumberFolder=aircraft/usaf_f-5a/rvn/serial/
SerialNumberPrefix=
SerialnumberTextures=27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52
ResourcesLiveryFolder=aircraft/usaf_f-5a/rvn/
LiveryTexture=usaf_f-5a_tx
ResourcesFlagFolder=ships/materials/textures/
# nations are referenced in the layout.ini file:
Nation=South_Vietnam

[Squadron14] #538th FS
ResourcesSerialnumberFolder=aircraft/usaf_f-5a/rvn/serial/
SerialNumberPrefix=
SerialnumberTextures=01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26
ResourcesLiveryFolder=aircraft/usaf_f-5a/rvn/
LiveryTexture=usaf_f-5a_tx
ResourcesFlagFolder=ships/materials/textures/
# nations are referenced in the layout.ini file:
Nation=South_Vietnam

[Squadron15] #540th FS
ResourcesSerialnumberFolder=aircraft/usaf_f-5a/rvn/serial/
SerialNumberPrefix=
SerialnumberTextures=27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52
ResourcesLiveryFolder=aircraft/usaf_f-5a/rvn/
LiveryTexture=usaf_f-5a_tx
ResourcesFlagFolder=ships/materials/textures/
# nations are referenced in the layout.ini file:
Nation=South_Vietnam

[Squadron16] #542nd FS
ResourcesSerialnumberFolder=aircraft/usaf_f-5a/rvn/serial/
SerialNumberPrefix=
SerialnumberTextures=01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26
ResourcesLiveryFolder=aircraft/usaf_f-5a/rvn/
LiveryTexture=usaf_f-5a_tx
ResourcesFlagFolder=ships/materials/textures/
# nations are referenced in the layout.ini file:
Nation=South_Vietnam

[Squadron17] #544th FS
ResourcesSerialnumberFolder=aircraft/usaf_f-5a/rvn/serial/
SerialNumberPrefix=
SerialnumberTextures=27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52
ResourcesLiveryFolder=aircraft/usaf_f-5a/rvn/
LiveryTexture=usaf_f-5a_tx
ResourcesFlagFolder=ships/materials/textures/
# nations are referenced in the layout.ini file:
Nation=South_Vietnam

[Squadron18] #716th FS
ResourcesSerialnumberFolder=aircraft/usaf_f-5a/rvn/serial/
SerialNumberPrefix=
SerialnumberTextures=01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26
ResourcesLiveryFolder=aircraft/usaf_f-5a/rvn/
LiveryTexture=usaf_f-5a_tx
ResourcesFlagFolder=ships/materials/textures/
# nations are referenced in the layout.ini file:
Nation=South_Vietnam

#Spain

[Squadron19] #Ala 21
ResourcesSerialnumberFolder=aircraft/usaf_f-5a/spain/serial/
SerialNumberPrefix=
SerialnumberTextures=01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16,17,18
ResourcesLiveryFolder=aircraft/usaf_f-5a/spain/
LiveryTexture=usaf_f-5a_tx
ResourcesFlagFolder=ships/materials/textures/
# nations are referenced in the layout.ini file:
Nation=Spain

#Turkey

[Squadron20] #151 Filo
ResourcesSerialnumberFolder=aircraft/usaf_f-5a/turkey/serial/
SerialNumberPrefix=
SerialnumberTextures=01,02,03,04,05,06,07,08,09,10,11,12,13,14,15
ResourcesLiveryFolder=aircraft/usaf_f-5a/turkey/
LiveryTexture=usaf_f-5a_tx
ResourcesFlagFolder=ships/materials/textures/
# nations are referenced in the layout.ini file:
Nation=Turkey

[Squadron21] #152 Filo
ResourcesSerialnumberFolder=aircraft/usaf_f-5a/turkey/serial/
SerialNumberPrefix=
SerialnumberTextures=16,17,18,19,20,21,22,23,24,25,26,27,28,29,30
ResourcesLiveryFolder=aircraft/usaf_f-5a/turkey/
LiveryTexture=usaf_f-5a_tx
ResourcesFlagFolder=ships/materials/textures/
# nations are referenced in the layout.ini file:
Nation=Turkey

[Squadron22] #Blank Desert Camo
ResourcesLiveryFolder=aircraft/usaf_f-5a/blank_desert_camo/
LiveryTexture=usaf_f-5a_tx
ResourcesEmblemFolder=textures/Misc/
EmblemTexture=transparent
Nation=US

[Squadron23] #Blank Grey
ResourcesLiveryFolder=aircraft/usaf_f-5a/blank_grey/
LiveryTexture=usaf_f-5a_tx
ResourcesEmblemFolder=textures/Misc/
EmblemTexture=transparent
Nation=US

[Squadron24] #Blank Sea Camo
ResourcesLiveryFolder=aircraft/usaf_f-5a/blank_grey_green_camo/
LiveryTexture=usaf_f-5a_tx
ResourcesEmblemFolder=textures/Misc/
EmblemTexture=transparent
Nation=US