[General]
SerialnumberReferences=
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfSquadrons=8

[Default]
Nation=US
ServiceDate=1977|1995

[Squadron1] #HMLA-169
ResourcesSerialnumberFolder=aircraft/usmc_ah-1t/modex/
SerialNumberPrefix=
SerialnumberTextures=730,731,732,733,734,735,736
ResourcesEmblemFolder=aircraft/usmc_ah-1t/
EmblemTexture=
ResourcesLiveryFolder=aircraft/usmc_ah-1t/
LiveryTexture=usmc_ah-1t_tx
# nations are referenced in the layout.ini file:
Nation=US

[Squadron2] #HMLA-269
ResourcesSerialnumberFolder=aircraft/usmc_ah-1t/modex/
SerialNumberPrefix=
SerialnumberTextures=730,731,732,733,734,735,736
ResourcesEmblemFolder=aircraft/usmc_ah-1t/
EmblemTexture=
ResourcesLiveryFolder=aircraft/usmc_ah-1t/
LiveryTexture=usmc_ah-1t_tx
# nations are referenced in the layout.ini file:
Nation=US

[Squadron3] #HMLA-369
ResourcesSerialnumberFolder=aircraft/usmc_ah-1t/modex/
SerialNumberPrefix=
SerialnumberTextures=730,731,732,733,734,735,736
ResourcesEmblemFolder=aircraft/usmc_ah-1t/
EmblemTexture=
ResourcesLiveryFolder=aircraft/usmc_ah-1t/
LiveryTexture=usmc_ah-1t_tx
# nations are referenced in the layout.ini file:
Nation=US

[Squadron4] #HMLA-773
ResourcesSerialnumberFolder=aircraft/usmc_ah-1t/modex/
SerialNumberPrefix=
SerialnumberTextures=730,731,732,733,734,735,736
ResourcesEmblemFolder=aircraft/usmc_ah-1t/
EmblemTexture=
ResourcesLiveryFolder=aircraft/usmc_ah-1t/
LiveryTexture=usmc_ah-1t_tx
# nations are referenced in the layout.ini file:
Nation=US

[Squadron5] #HMLA-775
ResourcesSerialnumberFolder=aircraft/usmc_ah-1t/modex/
SerialNumberPrefix=
SerialnumberTextures=730,731,732,733,734,735,736
ResourcesEmblemFolder=aircraft/usmc_ah-1t/
EmblemTexture=
ResourcesLiveryFolder=aircraft/usmc_ah-1t/
LiveryTexture=usmc_ah-1t_tx
# nations are referenced in the layout.ini file:
Nation=US

[Squadron6] #Blank Desert Camo
ResourcesLiveryFolder=aircraft/usmc_ah-1t/blank_desert/
LiveryTexture=usmc_ah-1t_tx
ResourcesEmblemFolder=textures/Misc/
EmblemTexture=transparent
Nation=US

[Squadron7] #Blank Euro Camo
ResourcesLiveryFolder=aircraft/usmc_ah-1t/blank_euro_camo/
LiveryTexture=usmc_ah-1t_tx
ResourcesEmblemFolder=textures/Misc/
EmblemTexture=transparent
Nation=US

[Squadron8] #Blank Green
ResourcesLiveryFolder=aircraft/usmc_ah-1t/blank_green/
LiveryTexture=usmc_ah-1t_tx
ResourcesEmblemFolder=textures/Misc/
EmblemTexture=transparent
Nation=US