[General]
SerialnumberReferences=Modex,Right_Outer_Wing_Modex,Left_Rudder_Modex,Right_Rudder_Modex
EmblemReference=CarrierName
NationFlagReference=Flag1
NumberOfSquadrons=10

[Default]
ResourcesSerialnumberFolder=aircraft/usn_e-2c/vaw-112/modex/
SerialNumberPrefix=
SerialnumberTextures=600,601,602,603
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=cv-64
ResourcesLiveryFolder=aircraft/usn_e-2c/vaw-112/
LiveryTexture=usn_e-2c_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
# nations are referenced in the layout.ini file:
Nation=US
ServiceDate=1973|1990

[Squadron1]  #Constellation, 600 NG
ResourcesSerialnumberFolder=aircraft/usn_e-2c/vaw-112/modex/
SerialNumberPrefix=
SerialnumberTextures=600,601,602,603
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=cv-64
ResourcesLiveryFolder=aircraft/usn_e-2c/vaw-112/
LiveryTexture=usn_e-2c_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
# nations are referenced in the layout.ini file:
Nation=US

[Squadron2]  #Kitty Hawk, 600 NL
ResourcesSerialnumberFolder=aircraft/usn_e-2c/vaw-114/modex/
SerialNumberPrefix=
SerialnumberTextures=601,602,603,604
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=cv-63
ResourcesLiveryFolder=aircraft/usn_e-2c/vaw-114/
LiveryTexture=usn_e-2c_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
# nations are referenced in the layout.ini file:
Nation=US

[Squadron3]  #Enterprise, 600 NH
ResourcesSerialnumberFolder=aircraft/usn_e-2c/vaw-117/modex/
SerialNumberPrefix=
SerialnumberTextures=600,601,602,603
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=cvn-65
ResourcesLiveryFolder=aircraft/usn_e-2c/vaw-117/
LiveryTexture=usn_e-2c_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
# nations are referenced in the layout.ini file:
Nation=US

[Squadron4]  #Eisenhower, 010 AG
ResourcesSerialnumberFolder=aircraft/usn_e-2c/vaw-121/modex/
SerialNumberPrefix=
SerialnumberTextures=011,012,013,014
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=cvn-69
ResourcesLiveryFolder=aircraft/usn_e-2c/vaw-121/
LiveryTexture=usn_e-2c_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
# nations are referenced in the layout.ini file:
Nation=US

[Squadron5]  #America, 600 AB 
ResourcesSerialnumberFolder=aircraft/usn_e-2c/vaw-123/modex/
SerialNumberPrefix=
SerialnumberTextures=600,601,602,603
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=cv-66
ResourcesLiveryFolder=aircraft/usn_e-2c/vaw-123/
LiveryTexture=usn_e-2c_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
# nations are referenced in the layout.ini file:
Nation=US

[Squadron6]  #Nimitz, 600 AJ
ResourcesSerialnumberFolder=aircraft/usn_e-2c/vaw-124/modex/
SerialNumberPrefix=
SerialnumberTextures=600,601,602,603
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=cvn-68
ResourcesLiveryFolder=aircraft/usn_e-2c/vaw-124/
LiveryTexture=usn_e-2c_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
# nations are referenced in the layout.ini file:
Nation=US

[Squadron7]  #Independence, 600 AE
ResourcesSerialnumberFolder=aircraft/usn_e-2c/vaw-122/modex/
SerialNumberPrefix=
SerialnumberTextures=600,601,602,603
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=cv-62
ResourcesLiveryFolder=aircraft/usn_e-2c/vaw-122/
LiveryTexture=usn_e-2c_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
# nations are referenced in the layout.ini file:
Nation=US

[Squadron8]  #Ranger, 600 NE
ResourcesSerialnumberFolder=aircraft/usn_e-2c/vaw-116/modex/
SerialNumberPrefix=
SerialnumberTextures=600,601,602,603
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=cv-61
ResourcesLiveryFolder=aircraft/usn_e-2c/vaw-116/
LiveryTexture=usn_e-2c_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
# nations are referenced in the layout.ini file:
Nation=US

[Squadron9]  #Forrestal, 600 AA
ResourcesSerialnumberFolder=aircraft/usn_e-2c/vaw-125/modex/
SerialNumberPrefix=
SerialnumberTextures=600,601,602,603
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=cv-59
ResourcesLiveryFolder=aircraft/usn_e-2c/vaw-125/
LiveryTexture=usn_e-2c_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
# nations are referenced in the layout.ini file:
Nation=US

[Squadron10]  #Saratoga, 600 AC
ResourcesSerialnumberFolder=aircraft/usn_e-2c/vaw-126/modex/
SerialNumberPrefix=
SerialnumberTextures=010,011,012,013
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=cv-60
ResourcesLiveryFolder=aircraft/usn_e-2c/vaw-126/
LiveryTexture=usn_e-2c_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_usn
# nations are referenced in the layout.ini file:
Nation=US