[---------- General Data ----------]
[General]
UnitType=Aircraft

DefaultCameraDistance=1
MinCameraDistanceForeAft=0.39
MinCameraDistanceBroadside=0.39
CameraPivotHeight=0.0

Length=23.3                           // in meters

GroundedPitchAngle=-2  // this angle is the pitch (x) angle at ground with gears down
GroundPivot=0,-0.03,-0.0268
LandingPitch=-5

Pilot=wp_pilot_k1m_a
PilotPositions=0,0.001,0.075
EjectChance=0.6

[OpticalView]
Views=binocular_7x50,binocular_10x50
DefaultView=binocular_7x50

[AI]
Role=Fighter

[SensorData]
#Visual
VisualIdentificationRange=6.0  // at what range in nm this unit can be visually identified
IRSignature=Medium
# Radar related (RCS => radar cross section)
RCS=Medium

[Animations]
NumberOfAnimationReferences=1
AnimationFile_1=animations_wp_mig-25bm

[---------- Flight Model ----------]
[Engine]
EngineIntakeArea=0.733

[FlightModel]
PitchGain=1                           // Vertical manuverability
VelocityGain=0.1136                   // Acceleration
HeadingGain=3                         // Horizontal manuverability
YawRateLimit=130                      // in degrees per second

BankGain=1                            // Roll change speed
MaxRollForHeading=45.0                // bank limit in normal flight
MaxRollRate=60.0                      // in degrees per second
MaxPitchRate=12

ThrustGain=0.325                      // Thrust change speed
SpeedBrakeFractionGain=10             // Speed brakes deploy speed

SpeedDeltaPerAltitudeChange=0.0885

[Performance]
#Dimensions
WingSpan=14.06                        //meters
#Parameters
MaxG=4.5                              // Mostly for horizontal turns

MaxClimbRate=186.0                    //Meters per second
EmptyMass=18800.0                     // in kg
MaxFuel=14470.0                       // in kg

PerEngineMaxThrust=73500              //Newtons
PerEngineMaxAfterburnerThrust=109800  //Newtons
EngineCount=2

Ceiling=68000.0                       // ceiling in feet
CruiseAltitude=39000                  //in feet
#"Engine" efficiency at 0ft, 37000 ft, 65000 ft. Always 1 for cruise altitude
AltitudeEfficiency=0.5,0.5,0.25       // Defines fuel consumption with altitude

#Governing of max speed
MaxSpeedAtSeaLevel=648                //in knots, Defines max speed at altitude curve
StallSpeed=125.0                      //in knots
MachLimit=2.83                        //for 37000ft, Defines max speed at altitude curve

#SpeedAndRange   MachNumbers or knots, Specified units or multiplier (except Cruise range)
RangeUnits=Miles                      // Can be: Km. Any other value = nmi. Defines measurment units of ranges of SpeedAndRange values

SpeedAndRange_Landing=0.27,0.4        // Landing
SpeedAndRange_Loiter=0.4,0.6          // Loiter
SpeedAndRange_Cruise=0.975,1004       // Cruise
SpeedAndRange_Max=2.35,880            // Attack/Fast/High/Max without AB
SpeedAndRange_Afterburner=2.83,0.2    // AB max

Altitudes=1000,3000,6000,10000,20000  // in feet

MaxClimbPitch=70.0
MaxDescentPitch=-70.0
[---------- Main Systems ----------]
[FlightControls]
NumberOfAilerons=2
Aileron1_Model=Left_Aileron
Aileron1_MinAngle=-15.0
Aileron1_MaxAngle=15.0
Aileron1_BaseAngle=0.0

Aileron2_Model=Right_Aileron
Aileron2_MinAngle=15.0
Aileron2_MaxAngle=-15.0
Aileron2_BaseAngle=0.0

NumberOfElevators=1
Elevator1_Model=Stabilator
Elevator1_MinAngle=-20.0
Elevator1_MaxAngle=20.0

NumberOfRudders=2
Rudder1_Model=Left_Rudder
Rudder1_MinAngle=-30.0
Rudder1_MaxAngle=30.0

Rudder2_Model=Right_Rudder
Rudder2_MinAngle=30.0
Rudder2_MaxAngle=-30.0

AfterBurnerSubModel=Afterburners    // optional entry
MaxAfterBurnerIntensity=0.2
AfterBurnerFadeTime=0.5

[---------- Sensor Systems ----------]
[SensorSystems]
NumberOfSensorSystems=5

[SensorSystem1] #Cockpit
Type=Visual
SystemName=Eyes  
Mount=Dummy
MountPosition=0,0.01677,0.07427
ViewArcs=-120,120|-25,91
ModuleType=Sensor

[SensorSystem2] #Smerch-A3 radar
Type=Radar
SystemName=Smerch-A3
Mount=Dummy
MountPosition=0,0,0.1272
ModuleType=Sensor

#---------- ESM ----------
[SensorSystem3] #RWR
Type=ESM
SystemName=SPO-3
Mount=Dummy
ModuleType=Sensor
[SensorSystem4] #ESM
Type=ESM
SystemName=AircraftELINT
Mount=Dummy
ModuleType=Sensor
[SensorSystem5] #ECM
Type=ECM
SystemName=AircraftDECM_Med
Mount=Dummy
ModuleType=Sensor

[---------- Weapon Systems ----------]
[WeaponSystems]
NumberOfWeaponSystems=2
AvailableLoadouts=SEAD

[WeaponSystem1]
Type=Hardpoint
SystemName=Hardpoint
AssociatedSensors=SensorSystem2
NumberOfStations=4
#Mek: to anyone concerned: hardpoints setup exclusively for AS-11/Kh-58 
#with no offset provided
Station1=-0.04878,-0.003,-0.01325    //Left Wing Station Inner
Station2=-0.0666,-0.005,-0.0285      //Left Wing Station Outer
Station3=0.04878,-0.003,-0.01325     //Right Wing Station Inner
Station4=0.0666,-0.005,-0.0285       //Right Wing Station Outer

#Rack1Positions=-0.003,0,0|0.003,0,0  // Wing Station Center
#Rack1Rotations=0,45,0|0,45,0|0,0,0
#Rack1ShowMesh=Some creative way to load a mesh not from this model

FiringArcs=-5,5
ModuleType=Weapon

[WeaponSystem2] #Chaff
Type=Chaff
SystemName=WP_AIR_CHAFF_DISP
#Sensors
#Animations
#Mount
Mount=Dummy
#MountPosition=0,-0.01,-0.016
#Containers
ContainerBase=Dummy
#Angles
#Loading
AssociatedMagazine=WeaponMagazineChaff
#Effects
NumberOfEffects=4
DelayBetweenLaunches=0.1
#Other
WorksStandalone=True
ModuleType=Weapon

[--------------------------- Loadouts ---------------------------]
#--------------- Standart --------------
[WeaponSystem1Empty]
ReadyUpTime=15               // in minutes. Time that plane will spend refueling and rearming before takeoff.
CoolDownTime=120             // in minutes. Time that plane will spend in maintenance after landing.

#MiG-25P can not use droptank, so no "Ferry" loadout

[WeaponSystem1Default]
ReadyUpTime=15               // in minutes. Time that plane will spend refueling and rearming before takeoff.
CoolDownTime=120             // in minutes. Time that plane will spend in maintenance after landing.

Station1=wp_as-11
Station2=wp_as-11
Station3=wp_as-11
Station4=wp_as-11

#--------------- SEAD --------------
[WeaponSystem1SEAD]
ReadyUpTime=15               // in minutes. Time that plane will spend refueling and rearming before takeoff.
CoolDownTime=120             // in minutes. Time that plane will spend in maintenance after landing.

Station1=wp_as-11
Station2=wp_as-11
Station3=wp_as-11
Station4=wp_as-11

[---------- WeaponMagazines ----------]
[WeaponMagazineChaff]
NumberOfAmmunitionTypes=1
Ammunition1_Count=15
Ammunition1=wp_aircraft_chaff
ModuleType=WeaponMagazine

[---------------------------Models and stuff---------------------------]
############################################################
# Main Model with collider
############################################################

[Models]

############################################################
# AssetBundle related
############################################################

AssetBundleMeshes=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMaterials=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMesh=wp_mig-25bm
AssetBundleDamagedMesh=wp_mig-25bm_d
AssetBundleMaterial=wp_mig-25bm_mat
AssetBundleMeshHullCollider=wp_mig-25bm_coll_hull
############################################################

############################################################
# Internal Resources folder related
############################################################

ResourcesFolder=aircraft/wp_mig-25bm/
ResourcesRoot=wp_mig-25bm
ResourcesMesh=wp_mig-25bm
ResourcesMaterial=wp_mig-25bm_mat

NumberOfDamageModels=3
DamageModel1=wp_mig-25bm_d_1
DamageModelMaterial1=wp_mig-25bm_mat
DamageModelLostWingSide1=Left
DamageModel2=wp_mig-25bm_d_2
DamageModelMaterial2=wp_mig-25bm_mat
DamageModelLostWingSide2=Right
DamageModel3=wp_mig-25bm_d_3
DamageModelMaterial3=wp_mig-25bm_mat
DamageModelLostWingSide3=Tail
############################################################
[Submodels]
SubModel1=Cockpit
SubModel3=WheelWells
SubModel4=Windshield
SubModel5=Canopy
SubModel6=Canopyglass
SubModel7=Crew
SubModel8=Seat
SubModel9=Left_Aileron
SubModel10=Left_Flap
SubModel11=Right_Aileron
SubModel12=Right_Flap
SubModel13=Stabilator
SubModel14=Left_Rudder
SubModel15=Right_Rudder
SubModel16=Nose_Gear
SubModel17=Nose_Gear_Door_1
SubModel18=Nose_Gear_Door_2l
SubModel19=Nose_Gear_Door_2r
SubModel20=Nose_Gear_Door_3
SubModel21=Left_Gear
SubModel22=Left_Gear_Wheel
SubModel23=Left_Gear_Strut
SubModel24=Left_Gear_Door_1
SubModel25=Left_Gear_Door_2
SubModel26=Right_Gear
SubModel27=Right_Gear_Wheel
SubModel28=Right_Gear_Strut
SubModel29=Right_Gear_Door_1
SubModel30=Right_Gear_Door_2
SubModel31=Afterburners
SubModel32=Serial
SubModel33=AKU58_inner
SubModel34=AKU58_outer


############################################################
# Fuselage
############################################################

[Cockpit]
Mesh=wp_mig-25bm_cockpit
Material=wp_mig-25bm_mat

[WheelWells]
Mesh=wp_mig-25bm_wheel_wells
Material=wp_mig-25bm_mat

[Windshield]
Mesh=wp_mig-25bm_windshield
ResourcesMaterialFolder=aircraft/materials/
Material=cockpit_glass

[Canopy]
Mesh=wp_mig-25bm_canopy
Material=wp_mig-25bm_mat
Parent=Anim_Controller
Position=0.00685,0.01193,0.07273
Rotation=4,0,0

[Canopyglass]
Mesh=wp_mig-25bm_canopyglass
ResourcesMaterialFolder=aircraft/materials/
Material=cockpit_glass
Parent=Canopy

[Crew]
Mesh=wp_mig-25bm_crew
ResourcesMaterialFolder=characters/materials/
Material=wp_pilot_a_mat

[Seat]
Mesh=wp_mig-25bm_seat
Material=wp_mig-25bm_mat

############################################################
# Left Wing
############################################################

[Left_Aileron]
Mesh=wp_mig-25bm_left_aileron
Material=wp_mig-25bm_mat
Position=-0.0548,0.0078,-0.0661
Rotation=5,-107.5,0

[Left_Flap]
Mesh=wp_mig-25bm_left_flap
Material=wp_mig-25bm_mat
Position=-0.0245,0.0104,-0.058
Rotation=5,75,0

############################################################
# Right Wing
############################################################

[Right_Aileron]
Mesh=wp_mig-25bm_right_aileron
Material=wp_mig-25bm_mat
Position=0.0548,0.0078,-0.0661
Rotation=5,107.5,0

[Right_Flap]
Mesh=wp_mig-25bm_right_flap
Material=wp_mig-25bm_mat
Position=0.0245,0.0104,-0.058
Rotation=5,105,0

############################################################
# Tail Section
############################################################

[Left_Rudder]
Mesh=wp_mig-25bm_left_rudder
Material=wp_mig-25bm_mat
Position=-0.022,0.0268,-0.1073
Rotation=-114.5,22.74,-24.74

[Right_Rudder]
Mesh=wp_mig-25bm_right_rudder
Material=wp_mig-25bm_mat
Position=0.022,0.0268,-0.1073
Rotation=-114.5,-22.74,24.74

[Stabilator]
Mesh=wp_mig-25bm_stabilator
Material=wp_mig-25bm_mat
Position=0,-0.0014,-0.1018
Rotation=0,0,0

############################################################
# Landing Gear
############################################################

[Nose_Gear]
Mesh=wp_mig-25bm_nose_gear
Material=wp_mig-25bm_mat
Position=0,-0.006,0.046
Rotation=0,-90,100

[Nose_Gear_Door_1]
Mesh=wp_mig-25bm_nose_gear_door1
Material=wp_mig-25bm_mat
Parent=WheelWells
Position=0,-0.008,0.0725
Rotation=0,90,0

[Nose_Gear_Door_2l]
Mesh=wp_mig-25bm_nose_gear_door2_l
Material=wp_mig-25bm_mat
Parent=WheelWells
Position=-0.0032,-0.008,0.0589
Rotation=0,-2.5,0

[Nose_Gear_Door_2r]
Mesh=wp_mig-25bm_nose_gear_door2_r
Material=wp_mig-25bm_mat
Parent=WheelWells
Position=0.0032,-0.008,0.0589
Rotation=0,2.5,0

[Nose_Gear_Door_3]
Mesh=wp_mig-25bm_nose_gear_door3
Material=wp_mig-25bm_mat
Parent=WheelWells
Position=0,-0.0077,0.045
Rotation=0,90,0

//----------------------------------------------------------

[Left_Gear]
Mesh=wp_mig-25bm_left_gear
Material=wp_mig-25bm_mat
Parent=WheelWells
Position=-0.0185,-0.001,-0.0266
Rotation=-15,-77.5,0

[Left_Gear_Wheel]
Mesh=wp_mig-25bm_left_gear_wheel
Material=wp_mig-25bm_mat
Parent=Left_Gear
Position=-0.001,-0.0196,-0.0002
Rotation=3,78,15

[Left_Gear_Strut]
Mesh=wp_mig-25bm_left_gear_strut
Material=wp_mig-25bm_mat
Parent=Left_Gear
Position=0.0132,-0.0013,-0.0008
Rotation=3,78,15

[Left_Gear_Door_1]
Mesh=wp_mig-25bm_main_door1_l
Material=wp_mig-25bm_mat
Position=-0.0232,-0.0048,-0.0106
Rotation=-0.11,2.5,0

[Left_Gear_Door_2]
Mesh=wp_mig-25bm_main_door2_l
Material=wp_mig-25bm_mat
Position=-0.0229,-0.0053,-0.0305
Rotation=0,0,0

//----------------------------------------------------------

[Right_Gear]
Mesh=wp_mig-25bm_right_gear
Material=wp_mig-25bm_mat
Parent=WheelWells
Position=0.0185,-0.001,-0.0266
Rotation=15,-102.5,0

[Right_Gear_Wheel]
Mesh=wp_mig-25bm_right_gear_wheel
Material=wp_mig-25bm_mat
Parent=Right_Gear
Position=-0.001,-0.0196,0.0002
Rotation=3,102,-15

[Right_Gear_Strut]
Mesh=wp_mig-25bm_right_gear_strut
Material=wp_mig-25bm_mat
Parent=Right_Gear
Position=0.0132,-0.0013,0.0008
Rotation=3,102,-15

[Right_Gear_Door_1]
Mesh=wp_mig-25bm_main_door1_r
Material=wp_mig-25bm_mat
Position=0.0232,-0.0048,-0.0106
Rotation=-0.11,-2.5,0

[Right_Gear_Door_2]
Mesh=wp_mig-25bm_main_door2_r
Material=wp_mig-25bm_mat
Position=0.0229,-0.0053,-0.0305
Rotation=0,0,0

//----------------------------------------------------------
[AKU58_inner]
Mesh=wp_mig-25bm_aku-58_inner
Material=wp_mig-25bm_mat

[AKU58_outer]
Mesh=wp_mig-25bm_aku-58_outer
Material=wp_mig-25bm_mat

//----------------------------------------------------------
[Afterburners]
Mesh=wp_mig-25bm_afterburners
ResourcesMaterialFolder=aircraft/materials/
Material=afterburner_mat
CastShadows=False

[Serial]
Mesh=wp_mig-25bm_serial
ResourcesMaterialFolder=aircraft/materials/numbers/
Material=numbers

//[Lights]
//Mesh=usn_ra-5c_lights
//ResourcesMaterialFolder=aircraft/materials/
//Material=aircraft_lights
//Position=0,0,0
//Rotation=0,0,0

[---------- Effects ----------]
[Particles]
ShotDownFireEffect=effects/aircraft_kill_effects/wp_mig-25bm_kill
ShotDownFireEffectPosition=0,0,0
HitWaterEffect=effects/splashes/emitters/splash_bomb
HitGroundEffect=effects/explosions/emitters/aircraft_hit_ground
HitAirEffectClass=LargeMissileExplosions
ExhaustSmoke=aircraft/particles/wp_mig-25p_smokeemitter
TipVortexPosition=0.1,0.0035,-0.086
TipVortex=effects/aircraft/emitters/tipvortex
LeftWingVortexPosition=0,0,0
LeftWingVortex=effects/aircraft/emitters/wingvortex_mig-25_left
RightWingVortexPosition=0,0,0
RightWingVortex=effects/aircraft/emitters/wingvortex_mig-25_right
ShockConePosition=0,0,0
ShockCone=effects/aircraft/emitters/shockcone_mig-25

############################################################
# Sounds
############################################################

[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=3
# Front
EngineAudioClip=audio/aircraft/LargeJet2_v1
EngineAudioPosition=0,0,0
EngineAudioRollOff=Logarithmic
EngineAudioDistance=1,20
EngineAudioPitchRange=1.0,2.6
EngineAudioVolumeRange=0.1,0.5
# Rear
ExhaustAudioClip=audio/aircraft/jet_rear_2
ExhaustAudioPosition=0,0,0
ExhaustAudioRollOff=Logarithmic
ExhaustAudioDistance=1,20
ExhaustAudioPitchRange=0.8,1.4
ExhaustAudioVolumeRange=1.0,1.6
# Far
FarAudioClip=audio/aircraft/jet_far_4
FarAudioPosition=0,0,0
FarAudioRollOff=Logarithmic
FarAudioDistance=5,20
FarAudioPitch=1.0
FarAudioVolume=1.0
FarAudioFadeRange=0.0,0.25	      // nautical miles min/max
# Afterburner
AfterburnerAudioClip=audio/aircraft/J79_AB
AfterburnerAudioPosition=0,0,0
AfterburnerAudioRollOff=Logarithmic
AfterburnerAudioDistance=1,20
AfterburnerAudioPitch=1.2
AfterburnerAudioVolume=1.2
# Gears
#GearsAudioClip=audio/aircraft/gears
GearsAudioClip=audio/aircraft/LandingGearRetraction_v1
GearsAudioPosition=0,0,0
GearsAudioRollOff=Logarithmic
GearsAudioDistance=1,20
GearsAudioPitch=1.0
GearsAudioVolume=1.0
# Flaps
#FlapsAudioClip=audio/aircraft/flaps
FlapsAudioClip=audio/aircraft/LandingGearRetraction_v1
FlapsAudioPosition=0,0,0
FlapsAudioRollOff=Logarithmic
FlapsAudioDistance=1,20
FlapsAudioPitch=1.0
FlapsAudioVolume=1.0

[---------- Colliders ----------]
[Colliders]
// creates the hit boxes for this object
NumberOfColliders=2
Collider1=coll_body
Collider2=coll_wings

[coll_body]
Collider=Box
Position=0,0,0
Rotation=0,0,0
Scale=0.02361928,0.02891341,0.1916716

[coll_wings]
Collider=Box
Position=0.0023026,0.0051,-0.012915
Rotation=0,0,0
Scale=0.169098,0.006968998,0.05797473
