[General]
SerialnumberReferences=Modex
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfSquadrons=6

[Default]
ResourcesLiveryFolder=aircraft/wp_mi-14/
LiveryTexture=wp_mi-14_tx
Nation=Soviet
ServiceDate=1973

[Squadron1]
ResourcesSerialnumberFolder=aircraft/materials/numbers/
SerialNumberPrefix=
SerialnumberTextures=wp_num_red_045,wp_num_red_046,wp_num_red_047,wp_num_red_048,wp_num_red_049,wp_num_red_050
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/wp_mi-14/
LiveryTexture=wp_mi-14_tx
ResourcesFlagFolder=
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=Soviet

[Squadron2]
ResourcesSerialnumberFolder=aircraft/materials/numbers/
SerialNumberPrefix=
SerialnumberTextures=wp_num_red_061,wp_num_red_062,wp_num_red_063,wp_num_red_064,wp_num_red_065,wp_num_red_066
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/wp_mi-14/
LiveryTexture=wp_mi-14_tx
ResourcesFlagFolder=
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=Soviet

[Squadron3]
ResourcesSerialnumberFolder=aircraft/materials/numbers/
SerialNumberPrefix=
SerialnumberTextures=wp_num_red_045,wp_num_red_046,wp_num_red_047,wp_num_red_048,wp_num_red_049,wp_num_red_050
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/wp_mi-14/USSR_grey/
LiveryTexture=wp_mi-14_tx
ResourcesFlagFolder=
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=Soviet

[Squadron4]
ResourcesSerialnumberFolder=aircraft/materials/numbers/
SerialNumberPrefix=
SerialnumberTextures=wp_num_red_061,wp_num_red_062,wp_num_red_063,wp_num_red_064,wp_num_red_065,wp_num_red_066
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/wp_mi-14/USSR_grey/
LiveryTexture=wp_mi-14_tx
ResourcesFlagFolder=
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=Soviet

[Squadron5] #DDR Navy dark blue generic DDR markings
ResourcesSerialnumberFolder=aircraft/materials/numbers/
SerialNumberPrefix=
SerialnumberTextures=wp_num_white_045,wp_num_white_046,wp_num_white_047,wp_num_white_048,wp_num_white_049,wp_num_white_050
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/wp_mi-14/DDR/
LiveryTexture=wp_mi-14_tx
ResourcesFlagFolder=
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=DDR

[Squadron6] #Polish Navy 28th Squadron TODO: actual numbers
ResourcesSerialnumberFolder=aircraft/materials/numbers/
SerialNumberPrefix=
SerialnumberTextures=wp_num_white_055,wp_num_white_056,wp_num_white_057,wp_num_white_058,wp_num_white_059,wp_num_white_060
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/wp_mi-14/POL/
LiveryTexture=wp_mi-14_tx
ResourcesFlagFolder=
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=Poland
