[General]
SerialnumberReferences=Serial
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfSquadrons=4

[Default]
ResourcesSerialnumberFolder=aircraft/materials/numbers/
SerialnumberTextures=wp_num_yellow_001,wp_num_yellow_002,wp_num_yellow_003,wp_num_yellow_004,wp_num_yellow_005,wp_num_yellow_006,wp_num_yellow_007,wp_num_yellow_008,wp_num_yellow_009,wp_num_yellow_010,wp_num_yellow_011,wp_num_yellow_012,wp_num_yellow_013,wp_num_yellow_014,wp_num_yellow_015,wp_num_yellow_016
# nations are referenced in the layout.ini file:
Nation=Soviet
ServiceDate=1976

[Squadron1]
ResourcesSerialnumberFolder=aircraft/materials/numbers/
SerialnumberTextures=wp_num_yellow_001,wp_num_yellow_002,wp_num_yellow_003,wp_num_yellow_004,wp_num_yellow_005,wp_num_yellow_006,wp_num_yellow_007,wp_num_yellow_008,wp_num_yellow_009,wp_num_yellow_010,wp_num_yellow_011,wp_num_yellow_012,wp_num_yellow_013,wp_num_yellow_014,wp_num_yellow_015,wp_num_yellow_016
# nations are referenced in the layout.ini file:
Nation=Soviet

[Squadron2]
ResourcesSerialnumberFolder=aircraft/materials/numbers/
SerialnumberTextures=wp_num_yellow_001,wp_num_yellow_002,wp_num_yellow_003,wp_num_yellow_004,wp_num_yellow_005,wp_num_yellow_006,wp_num_yellow_007,wp_num_yellow_008,wp_num_yellow_009,wp_num_yellow_010,wp_num_yellow_011,wp_num_yellow_012,wp_num_yellow_013,wp_num_yellow_014,wp_num_yellow_015,wp_num_yellow_016
# nations are referenced in the layout.ini file:
Nation=Soviet

[Squadron3]
ResourcesSerialnumberFolder=aircraft/materials/numbers/
SerialnumberTextures=wp_num_yellow_001,wp_num_yellow_002,wp_num_yellow_003,wp_num_yellow_004,wp_num_yellow_005,wp_num_yellow_006,wp_num_yellow_007,wp_num_yellow_008,wp_num_yellow_009,wp_num_yellow_010,wp_num_yellow_011,wp_num_yellow_012,wp_num_yellow_013,wp_num_yellow_014,wp_num_yellow_015,wp_num_yellow_016
# nations are referenced in the layout.ini file:
Nation=Soviet

[Squadron4]
ResourcesSerialnumberFolder=aircraft/materials/numbers/
SerialnumberTextures=wp_num_yellow_001,wp_num_yellow_002,wp_num_yellow_003,wp_num_yellow_004,wp_num_yellow_005,wp_num_yellow_006,wp_num_yellow_007,wp_num_yellow_008,wp_num_yellow_009,wp_num_yellow_010,wp_num_yellow_011,wp_num_yellow_012,wp_num_yellow_013,wp_num_yellow_014,wp_num_yellow_015,wp_num_yellow_016
# nations are referenced in the layout.ini file:
Nation=Soviet