[AmmunitionNames]
# ------------------ AAM ------------------


# ------------------ SAM ------------------


# ---------- Anti-radar Missiles ---------


# ---------- Anti-ship Missiles ----------
rn_seaskua=Sea Skua,ASM,ASM,British lightweight short range air to surface missile.
rn_seavenom=Sea Venom,ASM,ASM,Anglo-French lightweight short range anti ship missile.
rn_martlet=Martlet,LLM,LLM,British multi-purpose lightweight missile.
#-----------Land Strike only missiles---------

# ---------- Anti-sub  Missilies ----------


# ------------------ RBU ------------------


# --------------- Torpedoes ---------------
rn_stingray_air=Sting Ray,Mod 0,ASW Torpedo,The Sting Ray Mod 0 is the Royal Navy's acoustic homing lightweight torpedo. Designed to attack modern Soviet high-performance submarines this variant is air dropped.

# ------------------ Bombs -----------------


# ---------------- Sonobuoys ---------------
rn_jezebel=Jezebel,DIFAR,Sonobuoy,The Dowty Mini-Jezebel is a Directional Frequency Analysis and Recording (DIFAR) type sonobouy.

# ------------------ FFAR -----------------

# ------------------ MLRS -----------------
# ------------------ Guns -----------------


# ------------------ CIWS -----------------


# ----------- Noisemakers/Chaff -----------


# ----------------- Decoys ----------------

# ----------------- Special ----------------


# ----------------- Fueltanks ----------------

