[Animations]
NumberOfAnimations=10

Animation1=Flaps_Takeoff
Animation2=Flaps_Takeoff_Retract
Animation3=Flaps_Landing
Animation4=Flaps_Landing_Retract
Animation5=Gear_Extend
Animation6=Gear_Retract
Animation7=Nozzles_STOL
Animation8=Nozzles_STOL_Retract
Animation9=Nozzles_VTOL
Animation10=Nozzles_VTOL_Retract

[Wings_Fold]
NumberOfSequencesToPlay=2
Sequence1=Left_Wing_Fold
Sequence1_Model=Left_Outer_Wing
Sequence2=Right_Wing_Fold
Sequence2_Model=Right_Outer_Wing

[Wings_Extend]
NumberOfSequencesToPlay=2
Sequence1=Left_Wing_Spread
Sequence1_Model=Left_Outer_Wing
Sequence2=Right_Wing_Spread
Sequence2_Model=Right_Outer_Wing

[Flaps_Takeoff]
NumberOfSequencesToPlay=2
Sequence1=Flap_Takeoff
Sequence1_Model=Left_Flap
Sequence2=Flap_Takeoff
Sequence2_Model=Right_Flap

[Flaps_Takeoff_Retract]
NumberOfSequencesToPlay=2
Sequence1=Flap_Takeoff_Retract
Sequence1_Model=Left_Flap
Sequence2=Flap_Takeoff_Retract
Sequence2_Model=Right_Flap

[Flaps_Landing]
NumberOfSequencesToPlay=2
Sequence1=Flap_Landing
Sequence1_Model=Left_Flap
Sequence2=Flap_Landing
Sequence2_Model=Right_Flap

[Flaps_Landing_Retract]
NumberOfSequencesToPlay=2
Sequence1=Flap_Landing_Retract
Sequence1_Model=Left_Flap
Sequence2=Flap_Landing_Retract
Sequence2_Model=Right_Flap

[Gear_Extend]
NumberOfSequencesToPlay=11
Sequence1=Main_Gear_Door_1_Open
Sequence1_Model=Main_Gear_Door_1
Sequence2=Main_Gear_Door_2_L_Cycle
Sequence2_Model=Main_Gear_Door_2_l
Sequence3=Main_Gear_Door_2_R_Cycle
Sequence3_Model=Main_Gear_Door_2_r
Sequence4=Nose_Gear_Door_1_Open
Sequence4_Model=Nose_Gear_Door_1
Sequence5=Nose_Gear_Door_2_L_Open
Sequence5_Model=Nose_Gear_Door_2_l
Sequence6=Nose_Gear_Door_2_R_Open
Sequence6_Model=Nose_Gear_Door_2_r
Sequence7=Outrigger_Doors_Open
Sequence7_Model=Outrigger_Doors
Sequence8=Main_Gear_Extend
Sequence8_Model=Main_Gear
Sequence9=Nose_Gear_Extend
Sequence9_Model=Nose_Gear
Sequence10=Nose_Gear_Wheel_Extend
Sequence10_Model=Nose_Gear_Wheel
Sequence11=Outrigger_Gear_Extend
Sequence11_Model=Outrigger_Gear

[Gear_Retract]
NumberOfSequencesToPlay=11
Sequence1=Main_Gear_Door_1_Close
Sequence1_Model=Main_Gear_Door_1
Sequence2=Main_Gear_Door_2_L_Cycle
Sequence2_Model=Main_Gear_Door_2_l
Sequence3=Main_Gear_Door_2_R_Cycle
Sequence3_Model=Main_Gear_Door_2_r
Sequence4=Nose_Gear_Door_1_Close
Sequence4_Model=Nose_Gear_Door_1
Sequence5=Nose_Gear_Door_2_L_Close
Sequence5_Model=Nose_Gear_Door_2_l
Sequence6=Nose_Gear_Door_2_R_Close
Sequence6_Model=Nose_Gear_Door_2_r
Sequence7=Outrigger_Doors_Close
Sequence7_Model=Outrigger_Doors
Sequence8=Main_Gear_Retract
Sequence8_Model=Main_Gear
Sequence9=Nose_Gear_Retract
Sequence9_Model=Nose_Gear
Sequence10=Nose_Gear_Wheel_Retract
Sequence10_Model=Nose_Gear_Wheel
Sequence11=Outrigger_Gear_Retract
Sequence11_Model=Outrigger_Gear

[Nozzles_STOL]
NumberOfSequencesToPlay=2
Sequence1=Nozzle_STOL
Sequence1_Model=Nozzles_F
Sequence2=Nozzle_STOL
Sequence2_Model=Nozzles_R

[Nozzles_STOL_Retract]
NumberOfSequencesToPlay=2
Sequence1=Nozzle_STOL_Retract
Sequence1_Model=Nozzles_F
Sequence2=Nozzle_STOL_Retract
Sequence2_Model=Nozzles_R

[Nozzles_VTOL]
NumberOfSequencesToPlay=2
Sequence1=Nozzle_VTOL
Sequence1_Model=Nozzles_F
Sequence2=Nozzle_VTOL
Sequence2_Model=Nozzles_R

[Nozzles_VTOL_Retract]
NumberOfSequencesToPlay=4
NumberOfSequencesToPlay=2
Sequence1=Nozzle_VTOL_Retract
Sequence1_Model=Nozzles_F
Sequence2=Nozzle_VTOL_Retract
Sequence2_Model=Nozzles_R


[------------------------------ Sequences ------------------------------]
[Left_Wing_Fold]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=10 
RotationZ2=-90
Smoothness2=EaseInOut

[Left_Wing_Spread]
NumberOfSteps=2
Time1=0 
RotationZ1=-90
Smoothness1=EaseInOut
Time2=10 
RotationZ2=0
Smoothness2=EaseInOut

[Right_Wing_Fold]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=10 
RotationZ2=90
Smoothness2=EaseInOut

[Right_Wing_Spread]
NumberOfSteps=2
Time1=0 
RotationZ1=90
Smoothness1=EaseInOut
Time2=10 
RotationZ2=0
Smoothness2=EaseInOut

[Flap_Takeoff]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=5 
RotationZ2=20
Smoothness2=EaseInOut

[Flap_Takeoff_Retract]
NumberOfSteps=2
Time1=0 
RotationZ1=20
Smoothness1=EaseInOut
Time2=5 
RotationZ2=0
Smoothness2=EaseInOut

[Flap_Landing]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=10 
RotationZ2=35
Smoothness2=EaseInOut

[Flap_Landing_Retract]
NumberOfSteps=2
Time1=0 
RotationZ1=35
Smoothness1=EaseInOut
Time2=10 
RotationZ2=0
Smoothness2=EaseInOut

###Gear Struts Retraction



###Extend Gear

[Main_Gear_Door_1_Open]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut
Time3=5 
RotationZ3=135
Smoothness3=EaseInOut

[Main_Gear_Door_1_Close]
NumberOfSteps=3
Time1=0 
RotationZ1=135
Smoothness1=EaseInOut
Time2=2 
RotationZ2=135
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[Main_Gear_Door_2_L_Cycle]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-90
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-90
Smoothness3=EaseInOut
Time4=7 
RotationZ4=0
Smoothness4=EaseInOut

[Main_Gear_Door_2_R_Cycle]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=90
Smoothness2=EaseInOut
Time3=5 
RotationZ3=90
Smoothness3=EaseInOut
Time4=7 
RotationZ4=0
Smoothness4=EaseInOut

###-----------------------------------------

[Nose_Gear_Door_1_Open]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-135
Smoothness3=EaseInOut

[Nose_Gear_Door_1_Close]
NumberOfSteps=3
Time1=0 
RotationZ1=-135
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-135
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[Nose_Gear_Door_2_L_Open]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-90
Smoothness2=EaseInOut

[Nose_Gear_Door_2_L_Close]
NumberOfSteps=3
Time1=0 
RotationZ1=-90
Smoothness1=EaseInOut
Time2=5 
RotationZ2=-90
Smoothness2=EaseInOut
Time3=7 
RotationZ3=0
Smoothness3=EaseInOut

[Nose_Gear_Door_2_R_Open]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=90
Smoothness2=EaseInOut

[Nose_Gear_Door_2_R_Close]
NumberOfSteps=3
Time1=0 
RotationZ1=90
Smoothness1=EaseInOut
Time2=5 
RotationZ2=90
Smoothness2=EaseInOut
Time3=7 
RotationZ3=0
Smoothness3=EaseInOut

[Outrigger_Doors_Open]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut
Time3=5 
RotationZ3=105
Smoothness3=EaseInOut

[Outrigger_Doors_Close]
NumberOfSteps=3
Time1=0 
RotationZ1=105
Smoothness1=EaseInOut
Time2=3 
RotationZ2=105
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

###Left Gear

[Main_Gear_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=-97
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-97
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[Main_Gear_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-97
Smoothness3=EaseInOut

[Outrigger_Gear_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut
Time3=5 
RotationZ3=90
Smoothness3=EaseInOut

[Outrigger_Gear_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=90
Smoothness1=EaseInOut
Time2=2 
RotationZ2=90
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[Nose_Gear_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=120
Smoothness1=EaseInOut
Time2=2 
RotationZ2=120
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[Nose_Gear_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut
Time3=5 
RotationZ3=120
Smoothness3=EaseInOut

[Nose_Gear_Wheel_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=-30
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-30
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[Nose_Gear_Wheel_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-30
Smoothness3=EaseInOut

//----------------------------

[Nozzle_STOL]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=45
Smoothness2=EaseInOut

[Nozzle_STOL_Retract]
NumberOfSteps=2
Time1=0 
RotationZ1=45
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut

[Nozzle_VTOL]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=4 
RotationZ2=90
Smoothness2=EaseInOut

[Nozzle_VTOL_Retract]
NumberOfSteps=2
Time1=0 
RotationZ1=90
Smoothness1=EaseInOut
Time2=4 
RotationZ2=0
Smoothness2=EaseInOut


[Fan_Door_Open]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=2 
RotationX2=-30
Smoothness2=EaseInOut

[Fan_Door_Close]
NumberOfSteps=2
Time1=0 
RotationX1=-30
Smoothness1=EaseInOut
Time2=2 
RotationX2=0
Smoothness2=EaseInOut

[Fan_Door_l_Open]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-90
Smoothness2=EaseInOut

[Fan_Door_l_Close]
NumberOfSteps=2
Time1=0 
RotationZ1=-90
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut

[Fan_Door_r_Open]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=90
Smoothness2=EaseInOut

[Fan_Door_r_Close]
NumberOfSteps=2
Time1=0 
RotationZ1=90
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut