[Animations]
NumberOfAnimations=4

Animation1=Wings_Fold
Animation2=Wings_Extend
Animation3=Gear_Extend
Animation4=Gear_Retract

[Wings_Fold]
NumberOfSequencesToPlay=6
Sequence1=Tail_Fold
Sequence1_Model=Tail
Sequence2=Blade_1_Fold
Sequence2_Model=Blade_1
Sequence3=Blade_2_Fold
Sequence3_Model=Blade_2
Sequence4=Blade_3_Fold
Sequence4_Model=Blade_3
Sequence5=Blade_4_Fold
Sequence5_Model=Blade_4
Sequence6=Blade_5_Fold
Sequence6_Model=Blade_5

[Wings_Extend]
NumberOfSequencesToPlay=6
Sequence1=Tail_Unfold
Sequence1_Model=Tail
Sequence2=Blade_1_Unfold
Sequence2_Model=Blade_1
Sequence3=Blade_2_Unfold
Sequence3_Model=Blade_2
Sequence4=Blade_3_Unfold
Sequence4_Model=Blade_3
Sequence5=Blade_4_Unfold
Sequence5_Model=Blade_4
Sequence6=Blade_5_Unfold
Sequence6_Model=Blade_5

[Gear_Extend]
NumberOfSequencesToPlay=3
Sequence1=Nose_Gear_Down
Sequence1_Model=Nose_Gear
Sequence2=Gear_Down_L
Sequence2_Model=Gear_G
Sequence3=Gear_Down_R
Sequence3_Model=Gear_D

[Gear_Retract]
NumberOfSequencesToPlay=3
Sequence1=Nose_Gear_Up
Sequence1_Model=Nose_Gear
Sequence2=Gear_Up_L
Sequence2_Model=Gear_G
Sequence3=Gear_Up_R
Sequence3_Model=Gear_D

##########################################

[Tail_Fold]
NumberOfSteps=2
Time1=1
RotationX1=0
RotationY1=0
RotationZ1=0
Smoothness1=EaseInOut
Time2=7
RotationX2=-30 
RotationY2=-135
RotationZ2=0
Smoothness2=EaseInOut

[Tail_Unfold]
NumberOfSteps=2
Time1=6
RotationX1=-30 
RotationY1=-135
RotationZ1=0
Smoothness1=EaseInOut
Time2=12
RotationX2=0
RotationY2=0
RotationZ2=0
Smoothness2=EaseInOut

[Blade_1_Fold]
NumberOfSteps=
Time1=0
RotationY1=0
Smoothness1=EaseInOut
Time2=5
RotationY2=0
Smoothness2=EaseInOut


[Blade_1_Unfold]
NumberOfSteps=2
Time1=5
RotationY1=0
Smoothness1=EaseInOut
Time2=10
RotationY2=0
Smoothness2=EaseInOut

[Blade_2_Fold]
NumberOfSteps=2
Time1=0 
RotationY1=0
Smoothness1=EaseInOut
Time2=15
RotationY2=-62
Smoothness2=EaseInOut


[Blade_2_Unfold]
NumberOfSteps=2
Time1=0
RotationY1=-62
Smoothness1=EaseInOut
Time2=15
RotationY2=0
Smoothness2=EaseInOut



[Blade_3_Fold]
NumberOfSteps=2
Time1=0 
RotationY1=0
Smoothness1=EaseInOut
Time2=15
RotationY2=-129
Smoothness2=EaseInOut


[Blade_3_Unfold]
NumberOfSteps=2
Time1=0
RotationY1=-129
Smoothness1=EaseInOut
Time2=15
RotationY2=0
Smoothness2=EaseInOut

[Blade_4_Fold]
NumberOfSteps=2
Time1=0 
RotationY1=0
Smoothness1=EaseInOut
Time2=15
RotationY2=129
Smoothness2=EaseInOut

[Blade_4_Unfold]
NumberOfSteps=2
Time1=0
RotationY1=129
Smoothness1=EaseInOut
Time2=15
RotationY2=0
Smoothness2=EaseInOut

[Blade_5_Fold]
NumberOfSteps=2
Time1=0 
RotationY1=0
Smoothness1=EaseInOut
Time2=15
RotationY2=62
Smoothness2=EaseInOut

[Blade_5_Unfold]
NumberOfSteps=2
Time1=0
RotationY1=62
Smoothness1=EaseInOut
Time2=15
RotationY2=0
Smoothness2=EaseInOut

########## Gear Down ##################
[Nose_Gear_Down]
NumberOfSteps=2
Time1=4 
RotationX1=-0
Smoothness1=EaseInOut
Time2=8
RotationX2=-90
Smoothness2=EaseInOut

[Gear_Down_L]
NumberOfSteps=2
Time1=4 
RotationX1=0
Smoothness1=EaseInOut
Time2=8 
RotationX2=-90
Smoothness2=EaseInOut

[Gear_Down_R]
NumberOfSteps=2
Time1=4 
RotationX1=0
Smoothness1=EaseInOut
Time2=8 
RotationX2=-90
Smoothness2=EaseInOut

########## Gear Up ##################
[Nose_Gear_Up]
NumberOfSteps=2
Time1=4
RotationX1=-90
Smoothness1=EaseInOut
Time2=8
RotationX2=-0
Smoothness2=EaseInOut

[Gear_Up_L]
NumberOfSteps=2
Time1=4 
RotationX1=-90
Smoothness1=EaseInOut
Time2=8 
RotationX2=0
Smoothness2=EaseInOut

[Gear_Up_R]
NumberOfSteps=2
Time1=4 
RotationX1=-90
Smoothness1=EaseInOut
Time2=8 
RotationX2=0
Smoothness2=EaseInOut


