[Animations]
NumberOfAnimations=52
Animation1=Hangar1OpenAnim
Animation2=Hangar1CloseAnim

Animation3=Hangar2OpenAnim
Animation4=Hangar2CloseAnim

Animation5=HatchOpenAnim_1
Animation6=HatchOpenAnim_2
Animation7=HatchOpenAnim_3
Animation8=HatchOpenAnim_4
Animation9=HatchOpenAnim_5
Animation10=HatchOpenAnim_6
Animation11=HatchOpenAnim_7
Animation12=HatchOpenAnim_8

Animation13=HatchCloseAnim_1
Animation14=HatchCloseAnim_2
Animation15=HatchCloseAnim_3
Animation16=HatchCloseAnim_4
Animation17=HatchCloseAnim_5
Animation18=HatchCloseAnim_6
Animation19=HatchCloseAnim_7
Animation20=HatchCloseAnim_8

Animation21=VlsFrontOpen_1
Animation22=VlsFrontOpen_2
Animation23=VlsFrontOpen_3
Animation24=VlsFrontOpen_4
Animation25=VlsFrontOpen_5
Animation26=VlsFrontOpen_6
Animation27=VlsFrontOpen_7
Animation28=VlsFrontOpen_8

Animation29=VlsBackOpen_1
Animation30=VlsBackOpen_2
Animation31=VlsBackOpen_3
Animation32=VlsBackOpen_4
Animation33=VlsBackOpen_5
Animation34=VlsBackOpen_6
Animation35=VlsBackOpen_7
Animation36=VlsBackOpen_8

Animation37=VlsFrontClose_1
Animation38=VlsFrontClose_2
Animation39=VlsFrontClose_3
Animation40=VlsFrontClose_4
Animation41=VlsFrontClose_5
Animation42=VlsFrontClose_6
Animation43=VlsFrontClose_7
Animation44=VlsFrontClose_8

Animation45=VlsBackClose_1
Animation46=VlsBackClose_2
Animation47=VlsBackClose_3
Animation48=VlsBackClose_4
Animation49=VlsBackClose_5
Animation50=VlsBackClose_6
Animation51=VlsBackClose_7
Animation52=VlsBackClose_8

[Hangar1OpenAnim]
NumberOfSequencesToPlay=2

Sequence1=HangarOpenDoor1AnimSequence
Sequence1_Model=Hangar_door_R_1
Sequence2=HangarOpenDoor2AnimSequence
Sequence2_Model=Hangar_door_R_2


[Hangar1CloseAnim]
NumberOfSequencesToPlay=3

Sequence1=HangarCloseDoor1AnimSequence
Sequence1_Model=Hangar_door_R_1
Sequence2=HangarCloseDoor2AnimSequence
Sequence2_Model=Hangar_door_R_2

[Hangar2OpenAnim]
NumberOfSequencesToPlay=2

Sequence1=HangarOpenDoor1AnimSequence
Sequence1_Model=Hangar_door_L_1
Sequence2=HangarOpenDoor2AnimSequence
Sequence2_Model=Hangar_door_L_2


[Hangar2CloseAnim]
NumberOfSequencesToPlay=2

Sequence1=HangarCloseDoor1AnimSequence
Sequence1_Model=Hangar_door_L_1
Sequence2=HangarCloseDoor2AnimSequence
Sequence2_Model=Hangar_door_L_2


[HatchOpenAnim_1]
NumberOfSequencesToPlay=2
Sequence1=HatchOpenAnimSequence_Forward_R
Sequence1_Model=Hatch_1_front
Sequence2=HatchOpenAnimSequence_Aft_R
Sequence2_Model=Hatch_1_back

[HatchOpenAnim_2]
NumberOfSequencesToPlay=2
Sequence1=HatchOpenAnimSequence_Forward_L
Sequence1_Model=Hatch_2_front
Sequence2=HatchOpenAnimSequence_Aft_L
Sequence2_Model=Hatch_2_back

[HatchOpenAnim_3]
NumberOfSequencesToPlay=2
Sequence1=HatchOpenAnimSequence_Forward_R
Sequence1_Model=Hatch_3_front
Sequence2=HatchOpenAnimSequence_Aft_R
Sequence2_Model=Hatch_3_back

[HatchOpenAnim_4]
NumberOfSequencesToPlay=2
Sequence1=HatchOpenAnimSequence_Forward_L
Sequence1_Model=Hatch_4_front
Sequence2=HatchOpenAnimSequence_Aft_L
Sequence2_Model=Hatch_4_back

[HatchOpenAnim_5]
NumberOfSequencesToPlay=2
Sequence1=HatchOpenAnimSequence_Forward_R
Sequence1_Model=Hatch_5_front
Sequence2=HatchOpenAnimSequence_Aft_R
Sequence2_Model=Hatch_5_back

[HatchOpenAnim_6]
NumberOfSequencesToPlay=2
Sequence1=HatchOpenAnimSequence_Forward_L
Sequence1_Model=Hatch_6_front
Sequence2=HatchOpenAnimSequence_Aft_L
Sequence2_Model=Hatch_6_back

[HatchOpenAnim_7]
NumberOfSequencesToPlay=2
Sequence1=HatchOpenAnimSequence_Forward_R
Sequence1_Model=Hatch_7_front
Sequence2=HatchOpenAnimSequence_Aft_R
Sequence2_Model=Hatch_7_back

[HatchOpenAnim_8]
NumberOfSequencesToPlay=2
Sequence1=HatchOpenAnimSequence_Forward_L
Sequence1_Model=Hatch_8_front
Sequence2=HatchOpenAnimSequence_Aft_L
Sequence2_Model=Hatch_8_back

[HatchCloseAnim_1]
NumberOfSequencesToPlay=2
Sequence1=HatchCloseAnimSequence_Forward_R
Sequence1_Model=Hatch_1_front
Sequence2=HatchCloseAnimSequence_Aft_R
Sequence2_Model=Hatch_1_back

[HatchCloseAnim_2]
NumberOfSequencesToPlay=2
Sequence1=HatchCloseAnimSequence_Forward_L
Sequence1_Model=Hatch_2_front
Sequence2=HatchCloseAnimSequence_Aft_L
Sequence2_Model=Hatch_2_back

[HatchCloseAnim_3]
NumberOfSequencesToPlay=2
Sequence1=HatchCloseAnimSequence_Forward_R
Sequence1_Model=Hatch_3_front
Sequence2=HatchCloseAnimSequence_Aft_R
Sequence2_Model=Hatch_3_back

[HatchCloseAnim_4]
NumberOfSequencesToPlay=2
Sequence1=HatchCloseAnimSequence_Forward_L
Sequence1_Model=Hatch_4_front
Sequence2=HatchCloseAnimSequence_Aft_L
Sequence2_Model=Hatch_4_back

[HatchCloseAnim_5]
NumberOfSequencesToPlay=2
Sequence1=HatchCloseAnimSequence_Forward_R
Sequence1_Model=Hatch_5_front
Sequence2=HatchCloseAnimSequence_Aft_R
Sequence2_Model=Hatch_5_back

[HatchCloseAnim_6]
NumberOfSequencesToPlay=2
Sequence1=HatchCloseAnimSequence_Forward_L
Sequence1_Model=Hatch_6_front
Sequence2=HatchCloseAnimSequence_Aft_L
Sequence2_Model=Hatch_6_back

[HatchCloseAnim_7]
NumberOfSequencesToPlay=2
Sequence1=HatchCloseAnimSequence_Forward_R
Sequence1_Model=Hatch_7_front
Sequence2=HatchCloseAnimSequence_Aft_R
Sequence2_Model=Hatch_7_back

[HatchCloseAnim_8]
NumberOfSequencesToPlay=2
Sequence1=HatchCloseAnimSequence_Forward_L
Sequence1_Model=Hatch_8_front
Sequence2=HatchCloseAnimSequence_Aft_L
Sequence2_Model=Hatch_8_back


[VlsFrontOpen_1]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontOpen
Sequence1_Model=Vls_F_1

[VlsFrontOpen_2]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontOpen
Sequence1_Model=Vls_F_2

[VlsFrontOpen_3]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontOpen
Sequence1_Model=Vls_F_3

[VlsFrontOpen_4]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontOpen
Sequence1_Model=Vls_F_4

[VlsFrontOpen_5]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontOpen
Sequence1_Model=Vls_F_5

[VlsFrontOpen_6]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontOpen
Sequence1_Model=Vls_F_6

[VlsFrontOpen_7]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontOpen
Sequence1_Model=Vls_F_7

[VlsFrontOpen_8]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontOpen
Sequence1_Model=Vls_F_8


[VlsBackOpen_1]
NumberOfSequencesToPlay=1
Sequence1=VlsBackOpen
Sequence1_Model=Vls_B_1

[VlsBackOpen_2]
NumberOfSequencesToPlay=1
Sequence1=VlsBackOpen
Sequence1_Model=Vls_B_2

[VlsBackOpen_3]
NumberOfSequencesToPlay=1
Sequence1=VlsBackOpen
Sequence1_Model=Vls_B_3

[VlsBackOpen_4]
NumberOfSequencesToPlay=1
Sequence1=VlsBackOpen
Sequence1_Model=Vls_B_4

[VlsBackOpen_5]
NumberOfSequencesToPlay=1
Sequence1=VlsBackOpen
Sequence1_Model=Vls_B_5

[VlsBackOpen_6]
NumberOfSequencesToPlay=1
Sequence1=VlsBackOpen
Sequence1_Model=Vls_B_6

[VlsBackOpen_7]
NumberOfSequencesToPlay=1
Sequence1=VlsBackOpen
Sequence1_Model=Vls_B_7

[VlsBackOpen_8]
NumberOfSequencesToPlay=1
Sequence1=VlsBackOpen
Sequence1_Model=Vls_B_8




[VlsFrontClose_1]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontClose
Sequence1_Model=Vls_F_1

[VlsFrontClose_2]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontClose
Sequence1_Model=Vls_F_2

[VlsFrontClose_3]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontClose
Sequence1_Model=Vls_F_3

[VlsFrontClose_4]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontClose
Sequence1_Model=Vls_F_4

[VlsFrontClose_5]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontClose
Sequence1_Model=Vls_F_5

[VlsFrontClose_6]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontClose
Sequence1_Model=Vls_F_6

[VlsFrontClose_7]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontClose
Sequence1_Model=Vls_F_7

[VlsFrontClose_8]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontClose
Sequence1_Model=Vls_F_8


[VlsBackClose_1]
NumberOfSequencesToPlay=1
Sequence1=VlsBackClose
Sequence1_Model=Vls_B_1

[VlsBackClose_2]
NumberOfSequencesToPlay=1
Sequence1=VlsBackClose
Sequence1_Model=Vls_B_2

[VlsBackClose_3]
NumberOfSequencesToPlay=1
Sequence1=VlsBackClose
Sequence1_Model=Vls_B_3

[VlsBackClose_4]
NumberOfSequencesToPlay=1
Sequence1=VlsBackClose
Sequence1_Model=Vls_B_4

[VlsBackClose_5]
NumberOfSequencesToPlay=1
Sequence1=VlsBackClose
Sequence1_Model=Vls_B_5

[VlsBackClose_6]
NumberOfSequencesToPlay=1
Sequence1=VlsBackClose
Sequence1_Model=Vls_B_6

[VlsBackClose_7]
NumberOfSequencesToPlay=1
Sequence1=VlsBackClose
Sequence1_Model=Vls_B_7

[VlsBackClose_8]
NumberOfSequencesToPlay=1
Sequence1=VlsBackClose
Sequence1_Model=Vls_B_8

[------------------------------ Sequences ------------------------------]
############################################################
# Elevators
############################################################
#Open Doors


[HangarOpenDoor1AnimSequence]
NumberOfSteps=2
Time1=0             // time in seconds for the start
RotationX1=0
Smoothness1=Linear  // can be: Linear, EaseInOut - transition to the next step
Time2=4               // time in seconds - here for the end
RotationX2=90
Smoothness2=Linear  // can be: Linear, EaseInOut - is not used here as it's the last entry


[HangarOpenDoor2AnimSequence]
NumberOfSteps=2
Time1=0              // time in seconds for the start
RotationZ1=0
Smoothness1=Linear  // can be: Linear, EaseInOut - transition to the next step
Time2=4     // time in seconds - here for the end
RotationZ2=180
Smoothness2=Linear  // can be: Linear, EaseInOut - is not used here as it's the last entry

#Close Doors
[HangarCloseDoor1AnimSequence]
NumberOfSteps=2
Time1=0             // time in seconds for the start
RotationX1=90
Smoothness1=Linear  // can be: Linear, EaseInOut - transition to the next step
Time2=4               // time in seconds - here for the end
RotationX2=0
Smoothness2=Linear  // can be: Linear, EaseInOut - is not used here as it's the last entry

[HangarCloseDoor2AnimSequence]
NumberOfSteps=2
Time1=0              // time in seconds for the start
RotationZ1=180
Smoothness1=Linear  // can be: Linear, EaseInOut - transition to the next step
Time2=4     // time in seconds - here for the end
RotationZ2=0
Smoothness2=Linear  // can be: Linear, EaseInOut - is not used here as it's the last entry







[HatchOpenAnimSequence_Forward_L]
NumberOfSteps=2
Step1=0|x,y,z|-100,90,-90|Linear
Step2=1|x,y,z|0,90,-90|Linear

[HatchOpenAnimSequence_Aft_L]
NumberOfSteps=2
Step1=0|x,y,z|-100,90,-90|Linear
Step2=1|x,y,z|-200,90,-90|Linear

[HatchOpenAnimSequence_Forward_R]
NumberOfSteps=2
Step1=0|x,y,z|-100,-90,-90|Linear
Step2=1|x,y,z|20,-90,-90|Linear

[HatchOpenAnimSequence_Aft_R]
NumberOfSteps=2
Step1=0|x,y,z|-100,-90,-90|Linear
Step2=1|x,y,z|-200,-90,-90|Linear



######################################################################
[HatchCloseAnimSequence_Forward_L]
NumberOfSteps=2
Step1=0|x,y,z|20,90,-90|Linear
Step2=1|x,y,z|-80,90,-90|Linear

[HatchCloseAnimSequence_Aft_L]
NumberOfSteps=2
Step1=0|x,y,z|-200,90,90|Linear
Step2=1|x,y,z|-80,90,90|Linear

[HatchCloseAnimSequence_Forward_R]
NumberOfSteps=2
Step1=0|x,y,z|20,-90,-90|Linear
Step2=1|x,y,z|-80,-90,-90|Linear

[HatchCloseAnimSequence_Aft_R]
NumberOfSteps=2
Step1=0|x,y,z|-200,-90,90|Linear
Step2=1|x,y,z|-80,-90,90|Linear




[VlsFrontOpen]
NumberOfSteps=2
Step1=0|x,y,z|0,0,0|Linear
Step2=1|x,y,z|90,0,0|Linear

[VlsFrontClose]
NumberOfSteps=2
Step1=0|x,y,z|90,0,0|Linear
Step2=1|x,y,z|0,0,0|Linear

[VlsBackOpen]
NumberOfSteps=2
Step1=0|x,y,z|0,0,0|Linear
Step2=1|x,y,z|-90,0,0|Linear

[VlsBackClose]
NumberOfSteps=2
Step1=0|x,y,z|-90,0,0|Linear
Step2=1|x,y,z|0,0,0|Linear	




[------------------------------ FlightDeck Taxi Sequences ------------------------------]


[Elevator2LaunchPoint3Sequence]
#FixMe
NumberOfSteps=2
Time1=0                // time in seconds for the start
PositionX1=0.042
PositionY1=0.1676
PositionZ1=-1.07
RotationY1=0
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step

Time2=10
PositionZ2=-1.28
Smoothness2=Linear  //EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry

[Elevator1LaunchPoint4Sequence]
#FixMe
NumberOfSteps=2
Time1=0                // time in seconds for the start
PositionX1=-0.1245
PositionY1=0.1676
PositionZ1=-0.61
RotationY1=0
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step

Time2=14
PositionZ2=-0.98
Smoothness2=Linear  //EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry

[RecoveryPoint1Elevator1Sequence]
NumberOfSteps=2
Time1=0                // time in seconds for the start
PositionX1=-0.1245
PositionY1=0.1676
PositionZ1=-0.98
RotationY1=0
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step

Time2=14
PositionZ2=-0.61
Smoothness2=EaseInOut

[RecoveryPoint2Elevator2Sequence]
NumberOfSteps=2
Time1=0                // time in seconds for the start
PositionX1=0.042
PositionY1=0.1676
PositionZ1=-1.28
RotationY1=0
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step

Time2=10
PositionZ2=-1.07
Smoothness2=EaseInOut
