[Animations]
NumberOfAnimations=56
Animation1=HangarOpenAnim
Animation2=HangarCloseAnim

Animation5=HatchOpenAnim_1
Animation6=HatchOpenAnim_2
Animation7=HatchOpenAnim_3
Animation8=HatchOpenAnim_4

Animation13=HatchCloseAnim_1
Animation14=HatchCloseAnim_2
Animation15=HatchCloseAnim_3
Animation16=HatchCloseAnim_4

Animation21=VlsFrontOpen_1
Animation22=VlsFrontOpen_2
Animation23=VlsFrontOpen_3
Animation24=VlsFrontOpen_4
Animation25=VlsFrontOpen_5
Animation26=VlsFrontOpen_6
Animation27=VlsFrontOpen_7
Animation28=VlsFrontOpen_8

Animation29=VlsBackOpen_1
Animation30=VlsBackOpen_2
Animation31=VlsBackOpen_3
Animation32=VlsBackOpen_4
Animation33=VlsBackOpen_5
Animation34=VlsBackOpen_6
Animation35=VlsBackOpen_7
Animation36=VlsBackOpen_8

Animation37=VlsFrontClose_1
Animation38=VlsFrontClose_2
Animation39=VlsFrontClose_3
Animation40=VlsFrontClose_4
Animation41=VlsFrontClose_5
Animation42=VlsFrontClose_6
Animation43=VlsFrontClose_7
Animation44=VlsFrontClose_8

Animation45=VlsBackClose_1
Animation46=VlsBackClose_2
Animation47=VlsBackClose_3
Animation48=VlsBackClose_4
Animation49=VlsBackClose_5
Animation50=VlsBackClose_6
Animation51=VlsBackClose_7
Animation52=VlsBackClose_8

Animation53=Radar_out
Animation54=Radar_in

Animation55=VDS_Extend
Animation56=VDS_Retract






[HangarOpenAnim]
NumberOfSequencesToPlay=4
Sequence1=HangarOpenDoor1AnimSequence
Sequence1_Model=HangarDoor1
Sequence2=HangarOpenDoor2AnimSequence
Sequence2_Model=HangarDoor2
Sequence3=HangarOpenDoor3AnimSequence
Sequence3_Model=HangarDoor3
Sequence4=HangarOpenDoor4AnimSequence
Sequence4_Model=HangarDoor4

[HangarCloseAnim]
NumberOfSequencesToPlay=4
Sequence1=HangarCloseDoor1AnimSequence
Sequence1_Model=HangarDoor1
Sequence2=HangarCloseDoor2AnimSequence
Sequence2_Model=HangarDoor2
Sequence3=HangarCloseDoor3AnimSequence
Sequence3_Model=HangarDoor3
Sequence4=HangarCloseDoor4AnimSequence
Sequence4_Model=HangarDoor4


[HatchOpenAnim_1]
NumberOfSequencesToPlay=2
Sequence1=HatchOpenAnimSequence_Forward
Sequence1_Model=Teseo_Hatch_F_1
Sequence2=HatchOpenAnimSequence_Aft
Sequence2_Model=Teseo_Hatch_B_1

[HatchOpenAnim_2]
NumberOfSequencesToPlay=2
Sequence1=HatchOpenAnimSequence_Forward
Sequence1_Model=Teseo_Hatch_F_3
Sequence2=HatchOpenAnimSequence_Aft
Sequence2_Model=Teseo_Hatch_B_3

[HatchOpenAnim_3]
NumberOfSequencesToPlay=2
Sequence1=HatchOpenAnimSequence_Forward
Sequence1_Model=Teseo_Hatch_F_2
Sequence2=HatchOpenAnimSequence_Aft
Sequence2_Model=Teseo_Hatch_B_2

[HatchOpenAnim_4]
NumberOfSequencesToPlay=2
Sequence1=HatchOpenAnimSequence_Forward
Sequence1_Model=Teseo_Hatch_F_4
Sequence2=HatchOpenAnimSequence_Aft
Sequence2_Model=Teseo_Hatch_B_4


[HatchCloseAnim_1]
NumberOfSequencesToPlay=2
Sequence1=HatchCloseAnimSequence_Forward
Sequence1_Model=Teseo_Hatch_F_1
Sequence2=HatchCloseAnimSequence_Aft
Sequence2_Model=Teseo_Hatch_B_1

[HatchCloseAnim_2]
NumberOfSequencesToPlay=2
Sequence1=HatchCloseAnimSequence_Forward
Sequence1_Model=Teseo_Hatch_F_3
Sequence2=HatchCloseAnimSequence_Aft
Sequence2_Model=Teseo_Hatch_B_3

[HatchCloseAnim_3]
NumberOfSequencesToPlay=2
Sequence1=HatchCloseAnimSequence_Forward
Sequence1_Model=Teseo_Hatch_F_2
Sequence2=HatchCloseAnimSequence_Aft
Sequence2_Model=Teseo_Hatch_B_2

[HatchCloseAnim_4]
NumberOfSequencesToPlay=2
Sequence1=HatchCloseAnimSequence_Forward
Sequence1_Model=Teseo_Hatch_F_4
Sequence2=HatchCloseAnimSequence_Aft
Sequence2_Model=Teseo_Hatch_B_4



[VlsFrontOpen_1]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontOpen
Sequence1_Model=VLS_Hatch_F_1

[VlsFrontOpen_2]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontOpen
Sequence1_Model=VLS_Hatch_F_2

[VlsFrontOpen_3]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontOpen
Sequence1_Model=VLS_Hatch_F_3

[VlsFrontOpen_4]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontOpen
Sequence1_Model=VLS_Hatch_F_4

[VlsFrontOpen_5]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontOpen
Sequence1_Model=VLS_Hatch_F_5

[VlsFrontOpen_6]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontOpen
Sequence1_Model=VLS_Hatch_F_6

[VlsFrontOpen_7]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontOpen
Sequence1_Model=VLS_Hatch_F_7

[VlsFrontOpen_8]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontOpen
Sequence1_Model=VLS_Hatch_F_8


[VlsBackOpen_1]
NumberOfSequencesToPlay=1
Sequence1=VlsBackOpen
Sequence1_Model=VLS_Hatch_B_1

[VlsBackOpen_2]
NumberOfSequencesToPlay=1
Sequence1=VlsBackOpen
Sequence1_Model=VLS_Hatch_B_2

[VlsBackOpen_3]
NumberOfSequencesToPlay=1
Sequence1=VlsBackOpen
Sequence1_Model=VLS_Hatch_B_3

[VlsBackOpen_4]
NumberOfSequencesToPlay=1
Sequence1=VlsBackOpen
Sequence1_Model=VLS_Hatch_B_4

[VlsBackOpen_5]
NumberOfSequencesToPlay=1
Sequence1=VlsBackOpen
Sequence1_Model=VLS_Hatch_B_5

[VlsBackOpen_6]
NumberOfSequencesToPlay=1
Sequence1=VlsBackOpen
Sequence1_Model=VLS_Hatch_B_6

[VlsBackOpen_7]
NumberOfSequencesToPlay=1
Sequence1=VlsBackOpen
Sequence1_Model=VLS_Hatch_B_7

[VlsBackOpen_8]
NumberOfSequencesToPlay=1
Sequence1=VlsBackOpen
Sequence1_Model=VLS_Hatch_B_8




[VlsFrontClose_1]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontClose
Sequence1_Model=VLS_Hatch_F_1

[VlsFrontClose_2]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontClose
Sequence1_Model=VLS_Hatch_F_2

[VlsFrontClose_3]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontClose
Sequence1_Model=VLS_Hatch_F_3

[VlsFrontClose_4]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontClose
Sequence1_Model=VLS_Hatch_F_4

[VlsFrontClose_5]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontClose
Sequence1_Model=VLS_Hatch_F_5

[VlsFrontClose_6]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontClose
Sequence1_Model=VLS_Hatch_F_6

[VlsFrontClose_7]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontClose
Sequence1_Model=VLS_Hatch_F_7

[VlsFrontClose_8]
NumberOfSequencesToPlay=1
Sequence1=VlsFrontClose
Sequence1_Model=VLS_Hatch_F_8


[VlsBackClose_1]
NumberOfSequencesToPlay=1
Sequence1=VlsBackClose
Sequence1_Model=VLS_Hatch_B_1

[VlsBackClose_2]
NumberOfSequencesToPlay=1
Sequence1=VlsBackClose
Sequence1_Model=VLS_Hatch_B_2

[VlsBackClose_3]
NumberOfSequencesToPlay=1
Sequence1=VlsBackClose
Sequence1_Model=VLS_Hatch_B_3

[VlsBackClose_4]
NumberOfSequencesToPlay=1
Sequence1=VlsBackClose
Sequence1_Model=VLS_Hatch_B_4

[VlsBackClose_5]
NumberOfSequencesToPlay=1
Sequence1=VlsBackClose
Sequence1_Model=VLS_Hatch_B_5

[VlsBackClose_6]
NumberOfSequencesToPlay=1
Sequence1=VlsBackClose
Sequence1_Model=VLS_Hatch_B_6

[VlsBackClose_7]
NumberOfSequencesToPlay=1
Sequence1=VlsBackClose
Sequence1_Model=VLS_Hatch_B_7

[VlsBackClose_8]
NumberOfSequencesToPlay=1
Sequence1=VlsBackClose
Sequence1_Model=VLS_Hatch_B_8

[Radar_out]
NumberOfSequencesToPlay=2
Sequence1=OpenDoorL
Sequence1_Model=Sovraponte_door_L
Sequence2=OpenDoorR
Sequence2_Model=Sovraponte_door_R

[Radar_in]
NumberOfSequencesToPlay=2
Sequence1=CloseDoorL
Sequence1_Model=Sovraponte_door_L
Sequence2=CloseDoorR
Sequence2_Model=Sovraponte_door_R

[VDS_Extend]
NumberOfSequencesToPlay=4
Sequence1=Door_Open
Sequence1_Model=VDS_Hatch
Sequence2=Winch_Extend
Sequence2_Model=VDS_Winch
Sequence3=Actuator_Extend
Sequence3_Model=VDS_Actuator
Sequence4=Cradle_Extend
Sequence4_Model=VDS_Cradle

[VDS_Retract]
NumberOfSequencesToPlay=4
Sequence1=Door_Close
Sequence1_Model=VDS_Hatch
Sequence2=Winch_Retract
Sequence2_Model=VDS_Winch
Sequence3=Actuator_Retract
Sequence3_Model=VDS_Actuator
Sequence4=Cradle_Retract
Sequence4_Model=VDS_Cradle

[------------------------------ Sequences ------------------------------]
############################################################
# Elevators
############################################################
#Open Doors


[HangarOpenDoor1AnimSequence]
NumberOfSteps=2
Time1=0             // time in seconds for the start
RotationX1=0
Smoothness1=Linear  // can be: Linear, EaseInOut - transition to the next step
Time2=4               // time in seconds - here for the end
RotationX2=-90
Smoothness2=Linear  // can be: Linear, EaseInOut - is not used here as it's the last entry

[HangarOpenDoor2AnimSequence]
NumberOfSteps=2
Time1=0             // time in seconds for the start
RotationY1=0
Smoothness1=Linear  // can be: Linear, EaseInOut - transition to the next step
Time2=4               // time in seconds - here for the end
RotationY2=-180
Smoothness2=Linear  // can be: Linear, EaseInOut - is not used here as it's the last entry

[HangarOpenDoor3AnimSequence]
NumberOfSteps=2
Time1=0             // time in seconds for the start
RotationY1=0
Smoothness1=Linear  // can be: Linear, EaseInOut - transition to the next step
Time2=4               // time in seconds - here for the end
RotationY2=180
Smoothness2=Linear  // can be: Linear, EaseInOut - is not used here as it's the last entry

[HangarOpenDoor4AnimSequence]
NumberOfSteps=2
Time1=0             // time in seconds for the start
RotationY1=0
Smoothness1=Linear  // can be: Linear, EaseInOut - transition to the next step
Time2=4               // time in seconds - here for the end
RotationY2=-180
Smoothness2=Linear  // can be: Linear, EaseInOut - is not used here as it's the last entry



[HangarCloseDoor1AnimSequence]
NumberOfSteps=2
Time1=0             // time in seconds for the start
RotationX1=-90
RotationY1=0
RotationZ1=90
Smoothness1=Linear  // can be: Linear, EaseInOut - transition to the next step
Time2=4               // time in seconds - here for the end
RotationX2=0
RotationY2=0
RotationZ2=90
Smoothness2=Linear  // can be: Linear, EaseInOut - is not used here as it's the last entry

[HangarCloseDoor2AnimSequence]
NumberOfSteps=2
Time1=0             // time in seconds for the start
RotationY1=-180
Smoothness1=Linear  // can be: Linear, EaseInOut - transition to the next step
Time2=4               // time in seconds - here for the end
RotationY2=0
Smoothness2=Linear  // can be: Linear, EaseInOut - is not used here as it's the last entry

[HangarCloseDoor3AnimSequence]
NumberOfSteps=2
Time1=0             // time in seconds for the start
RotationY1=180
Smoothness1=Linear  // can be: Linear, EaseInOut - transition to the next step
Time2=4               // time in seconds - here for the end
RotationY2=0
Smoothness2=Linear  // can be: Linear, EaseInOut - is not used here as it's the last entry

[HangarCloseDoor4AnimSequence]
NumberOfSteps=2
Time1=0             // time in seconds for the start
RotationY1=-180
Smoothness1=Linear  // can be: Linear, EaseInOut - transition to the next step
Time2=4               // time in seconds - here for the end
RotationY2=0
Smoothness2=Linear  // can be: Linear, EaseInOut - is not used here as it's the last entry







[HatchOpenAnimSequence_Forward]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=0.2            
RotationX2=-90
Smoothness2=EaseInOut

[HatchOpenAnimSequence_Aft]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=0.2            
RotationX2=90
Smoothness2=EaseInOut



######################################################################
[HatchCloseAnimSequence_Forward]
NumberOfSteps=2
Time1=0 
RotationX1=-90
Smoothness1=EaseInOut
Time2=0.2            
RotationX2=0
Smoothness2=EaseInOut

[HatchCloseAnimSequence_Aft]
NumberOfSteps=2
Time1=0 
RotationX1=90
Smoothness1=EaseInOut
Time2=0.2            
RotationX2=0
Smoothness2=EaseInOut




[VlsFrontOpen]
NumberOfSteps=2
Step1=0|x,y,z|0,0,0|Linear
Step2=1|x,y,z|90,0,0|Linear

[VlsFrontClose]
NumberOfSteps=2
Step1=0|x,y,z|90,0,0|Linear
Step2=1|x,y,z|0,0,0|Linear

[VlsBackOpen]
NumberOfSteps=2
Step1=0|x,y,z|0,0,0|Linear
Step2=1|x,y,z|-90,0,0|Linear

[VlsBackClose]
NumberOfSteps=2
Step1=0|x,y,z|-90,0,0|Linear
Step2=1|x,y,z|0,0,0|Linear	


[OpenDoorL]
NumberOfSteps=2
Time1=0             // time in seconds for the start
PositionX1=0
PositionZ1=0
Smoothness1=Linear  // can be: Linear, EaseInOut - transition to the next step
Time2=2               // time in seconds - here for the end
PositionX2=-0.008572
PositionZ2=-0.012502
Smoothness2=Linear  // can be: Linear, EaseInOut - is not used here as it's the last entry


[OpenDoorR]
NumberOfSteps=2
Time1=0             // time in seconds for the start
PositionX1=0
PositionZ1=0
Smoothness1=Linear  // can be: Linear, EaseInOut - transition to the next step
Time2=2               // time in seconds - here for the end
PositionX2=0.008572
PositionZ2=-0.012502
Smoothness2=Linear  // can be: Linear, EaseInOut - is not used here as it's the last entry




[------------------------------ FlightDeck Taxi Sequences ------------------------------]


[Elevator2LaunchPoint3Sequence]
#FixMe
NumberOfSteps=2
Time1=0                // time in seconds for the start
PositionX1=0.042
PositionY1=0.1676
PositionZ1=-1.07
RotationY1=0
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step

Time2=10
PositionZ2=-1.28
Smoothness2=Linear  //EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry

[Elevator1LaunchPoint4Sequence]
#FixMe
NumberOfSteps=2
Time1=0                // time in seconds for the start
PositionX1=-0.1245
PositionY1=0.1676
PositionZ1=-0.61
RotationY1=0
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step

Time2=14
PositionZ2=-0.98
Smoothness2=Linear  //EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry

[RecoveryPoint1Elevator1Sequence]
NumberOfSteps=2
Time1=0                // time in seconds for the start
PositionX1=-0.1245
PositionY1=0.1676
PositionZ1=-0.98
RotationY1=0
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step

Time2=14
PositionZ2=-0.61
Smoothness2=EaseInOut

[RecoveryPoint2Elevator2Sequence]
NumberOfSteps=2
Time1=0                // time in seconds for the start
PositionX1=0.042
PositionY1=0.1676
PositionZ1=-1.28
RotationY1=0
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step

Time2=10
PositionZ2=-1.07
Smoothness2=EaseInOut

############################################################
# Deploy VDS
############################################################
[Door_Open]
NumberOfSteps=4
Time1=0                // time in seconds for the start
PositionZ1=-1.091994
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time2=4                // time in seconds - here for the end
PositionZ2=-1.0805
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry
Time3=4                // time in seconds - here for the end
PositionY3=0.079403
Smoothness3=EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry
Time4=10                // time in seconds - here for the end
PositionY4=0.05
Smoothness4=EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry

[Winch_Extend]
NumberOfSteps=2
Time1=7                // time in seconds for the start
PositionZ1=-1.006
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time2=16                // time in seconds - here for the end
PositionZ2=-1.061
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry

[Actuator_Extend]
NumberOfSteps=2
Time1=16                // time in seconds for the start
RotationX1=0
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time2=21               // time in seconds - here for the end
RotationX2=-30
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry

[Cradle_Extend]
NumberOfSteps=2
Time1=10                // time in seconds for the start
RotationX1=15
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time2=15                // time in seconds - here for the end
RotationX2=30
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry

############################################################
# Retract VDS
############################################################

[Cradle_Retract]
NumberOfSteps=2
Time1=0                // time in seconds for the start
RotationX1=30
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time2=7                // time in seconds - here for the end
RotationX2=15
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry

[Actuator_Retract]
NumberOfSteps=2
Time1=0                // time in seconds for the start
RotationX1=-30
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time2=7               // time in seconds - here for the end
RotationX2=0
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry

[Winch_Retract]
NumberOfSteps=2
Time1=7                // time in seconds for the start
PositionZ1=-1.061
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time2=12                // time in seconds - here for the end
PositionZ2=-1.006
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry

[Door_Close]
NumberOfSteps=4
Time1=12                // time in seconds - here for the end
PositionY1=0.05
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry
Time2=16                // time in seconds - here for the end
PositionY2=0.079403
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry
Time3=16                // time in seconds for the start
PositionZ3=-1.0805
Smoothness3=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time4=20                // time in seconds - here for the end
PositionZ4=-1.091994
Smoothness4=EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry