[AmmunitionNames]

# ---------- Air To Air Missile ---------


# ---------- Anti-radar Missiles ---------
usn_agm-114k=AGM-114K,Hellfire,Land Attack,The AGM-114 is an American Semi Laser-guided air-to-ground standoff weapon.

usn_agm-114r=AGM-114R,Hellfire II,Land Attack, The AGM-114R Hellfire II also known as the Hellfire Romeo, is the latest precision-strike, semi-active laser (SAL) guided missile in the Hellfire family. Introduced in late 2012, it was designed to consolidate multiple previous variants into a single, multi-mission weapon capable of defeating a wide range of targets.

# ---------- Anti-ship Missiles ----------

usn_agm-119b=AGM-119B,Penguin Mk2 Mod 7,ASM,The AGM-119B Penguin is a small air-launched and surface-launched anti-ship missile developed in collaboration between the US and Norway. This is the Mod 7 version, with an imaging-infrared seeker, a longer range, folding fins (not modeled ingame) and a lower sea skim altitude.

#-----------Land Strike only missiles---------


#-----------Bombs---------


# ----------------- Special ----------------

# ----------------- Fueltanks ----------------


-------------------------------------------------------------------------------------------