[Language_en]
Name=MIM-104
Description=by Misaka


[Language_cn]
Name=MIM-104
Description=由misaka制作


[Language_ru]
Name=MIM-104 Патриот
Description=by misaka

[Compatibility]
;ApproximateVersion is the second check and will override all statements below. This checks MAJOR and MINOR match but will accept higher PATCH.
;Would recommend this as a default case for starters.
ApproximateVersion=0.7.0